### ISSUE TITLE
Why SUI-React?

### ISSUE THREAD

**Issue by brianveltman** [Semantic-Org/Semantic-UI-React#1]
Hi,

I know that SUI behavior can be a bit tricky when using React. For example the modal does not play well with React since jQuery and React manipulates the DOM at the same time and sometimes even the same element, causing conflicts all over the place. Is this the reason why React will get a separate integration?

**Comment by levithomason** [comment]
Hi :)

Though it seems tempting, integrating React with Semantic UI jQuery plugins just isn't maintainable (nor completely possible).  I started [Stardust](https://github.com/TechnologyAdvice/stardust) a while ago attempting this same thing.  We wanted the thinnest layer possible between React and SUI while leveraging all the goodies in SUI.  We tested this in production for a few months.  In the end, it is just not feasible, even using all the lifecycle hooks in both libraries.

We decided to drop all jQuery and all SUI jQuery plugins (mostly the "modules") after trying to asynchronously fetch dropdown items.  If you use all the SUI jQuery methods for doing this, things are great.  If you use something like Redux, keeping the DOM and React's virtual DOM in sync is next to impossible.  When considering the extra work, extra hacks, and extra libs that were in the mix to make this possible we came to terms with the fact that it is just better to rewrite the modules in React's paradigm.

This means a library with no jQuery and no SUI JavaScript.  While were at this, it also makes sense to abstract the HTML markup into simple declarative component APIs.

Stardust will be the official integration that does this.  That decision was made here: https://github.com/Semantic-Org/Semantic-UI/issues/1175#issuecomment-219089114.  This is very much "new news" and there are lots of updates taking place in preparation for the transition.

I've added a todo to the migration task list to add a "Why SUI-React" section to the README.  Hope that helps!
