### ISSUE TITLE
Div inside Table ?

### ISSUE THREAD

**Issue by littlehome-eugene** [Semantic-Org/Semantic-UI-React#1011]
I want to use accordion on Table.Row

I tried
```
<Table>
 <Accordion>
    <Table.Row />
  </Accordion>
</Table>
```

and 

```
<Table>
  <Table.Row>
    <Accordion>
    </Accodion>
  </Table.Row>
</Table>
```

In both case, I get error similar to 

> warning.js:36Warning: validateDOMNesting(...): <tr> cannot appear as a child of <div>. See Resource > AccordionTitle > div > TableRow > tr.

This is problematic when I need to wrap elements in one `<div>` root in jsx as well.

If using div inside table or table row is not permitted, What's the suggested way of implementing `accordion` inside table?

**Comment by levithomason** [comment]
You can override the HTML tag of any component with the `as` prop.  So you can use `div` elements for the table:

```jsx
<Table as='div' />
```

Then, you can have a `div` child without the warning.
