### ISSUE TITLE
Form Within Modal - formData submitted returns undefined

### ISSUE THREAD

**Issue by manju4ever** [Semantic-Org/Semantic-UI-React#1016]
the onSubmit handler given inn the below code snippet returns undefined. I need some help on this.

```
import React, {Component} from "react";
import ReactDOM from "react-dom";
import { Button, Checkbox, Form, Input, Message, Radio, Select, TextArea , Modal}  from "semantic-ui-react";

export class NewDiseaseModal extends Component {
    constructor() {
      super();
      this.state = {
        formData: {},
        modalOpen: true
      };
    }

    handleSubmit(e, {formData}) {
        e.preventDefault();
        console.log(formData);
    }

    render() {
      const {formData} = this.state;
      return(
          <Modal open={this.state.modalOpen}>
              <Modal.Header>
                  Add New Disease
              </Modal.Header>
              <Modal.Content>
                <Form onSubmit={this.handleSubmit}>
                  <Form.Field>
                    <Form.Input type='text' name='username' label="username" />
                  </Form.Field>
                  <Button primary type='submit'>Submit</Button>

                  <Message>
                    <pre>formData: {JSON.stringify(formData, null, 2)}</pre>
                  </Message>
                </Form>
              </Modal.Content>
          </Modal>
      );
    }
}
```

**Comment by manju4ever** [comment]
Found that the older version was showing this erratic behavior
"Not Working" Version: ^0.61.7
"Working" Version: ^0.62.0

**Comment by levithomason** [comment]
Per the [CHANGELOG.md](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/CHANGELOG.md) there was a breaking change in `0.62.0`:

**breaking(Form|RatingIcon|Search|SearchResult): Pass data to event handlers #951 (jcarbo)**

Handler | Previous Signature | Current Signature
------- | ------------------ | -----------------
onClick | (e, formData) | (e, { ...props, formData })

**Comment by pierre-H** [comment]
@levithomason I'm sorry but since the `0.62.0` break change, I've got `fomData is undefined` (in general, not specificaly with the modal) and I tried to implement the [example](https://github.com/Semantic-Org/Semantic-UI-React/blob/4411b535457df17a44f2db72df4a3f75c8d0586a/docs/app/Examples/collections/Form/Types/FormExampleOnSubmit.js) with Redux but I still have undefined.

Is it possible to have an example how to get the new formData ? Thanks !

**Comment by levithomason** [comment]
As of `0.66` there is no `formData`.  See https://github.com/Semantic-Org/Semantic-UI-React/pull/1367 for upgrade guide and more info.

**Comment by levithomason** [comment]
You'll notice that example is gone on master now.  We're shipping more examples, which you can preview here:

[Examples/collections/Form/Usage/FormExampleCaptureValues.js](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/Examples/collections/Form/Usage/FormExampleCaptureValues.js)
[Examples/collections/Form/Usage/FormExampleClearOnSubmit.js](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/Examples/collections/Form/Usage/FormExampleClearOnSubmit.js)
