### ISSUE TITLE
Dropdown not resetting value when blurred

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#1019]
### Steps
1. open a searchable dropdown.
2. type in a search
3. close the dropdown

### Expected Result
The dropdown should display its value or the placeholder if no value is set.

### Actual Result
The search string is displayed as value of the dropdown.

### Version
0.62.1

### Testcase
http://codepen.io/immerhungrig/pen/OboZmN

**Comment by levithomason** [comment]
Thanks for the complete report :)

Looks like this was an oversight in SUIR that should be implemented.  One clarification, the core SUI Dropdown clears the query onBlur but not onClose:

![http://g.recordit.co/HEdl23PkpX.gif](http://g.recordit.co/HEdl23PkpX.gif)

**Comment by levithomason** [comment]
I've updated the title and labeled this issue accordingly.
