### ISSUE TITLE
(Accordion) Option to align dropdown icon to right or left

### ISSUE THREAD

**Issue by 13ogrammer** [Semantic-Org/Semantic-UI-React#1021]
Currently, the dropdown icon is left aligned by default. It would really nice to have the option of aligning it to the right.

![screen shot 2016-12-13 at 2 16 18 pm](https://cloud.githubusercontent.com/assets/3193879/21126227/0c010438-c13f-11e6-92c3-a9e61701da9a.png)

**Comment by levithomason** [comment]
This is a CSS issue and needs to be opened on Semantic-UI itself.  There is currently no CSS framework support for this.

**Comment by jblossom-mersive** [comment]
@levithomason thanks a pantload. if you wanted to be helpful you could have opened the issue against Semantic-UI and provided a link here. but I don't think you do ;)
