### ISSUE TITLE
Custom function in dropdown search

### ISSUE THREAD

**Issue by valin0k** [Semantic-Org/Semantic-UI-React#1022]
Hello, i try to use custom search function for dropdown module. When i return something like array, string, object or bool i see following warning `Unknown props `$$typeof`, `props`, `_owner`, `_store` on <div> tag. Remove these props from the element.` and empty results list.
Here is my code:
`              <Dropdown
                selection
                fluid
                search={(e) => {
                  let arr = [];
                  e.forEach((item, i) => {
                    let div = (
                      <span key={i}>something</span>
                    );
                    arr.push(div);
                  });
                  return arr;
                }}
                options={this.dropdownList}
              />`
What i need return for the correct results?

**Comment by levithomason** [comment]
You need to return an array of option objects: `{ text: 'My Option', value: 'my_option' }`.  These are spread as the `DropdownItem` props, so any `DropdownItem` prop is valid.

Also, if you're trying to render a `div` in each item, see here:
http://react.semantic-ui.com/modules/dropdown#item-content
