### ISSUE TITLE
Importing single module bundles entire library

### ISSUE THREAD

**Issue by pranjalk** [Semantic-Org/Semantic-UI-React#1025]
Inspite of using `import { Popup } from 'semantic-ui-react';` to import just the popup, the entire library gets imported in the bundle in webpack, Can someone please help me with this?

Semantic-UI-React version: 0.62.1

**Comment by levithomason** [comment]
Duplicate https://github.com/Semantic-Org/Semantic-UI-React/issues/862, not yet supported.

Until we get a `jsnext:main` build to support tree shaking you can [add `babel-plugin-lodash` as noted here](https://github.com/Semantic-Org/Semantic-UI-React/pull/731#issuecomment-258729112) to transform your import statements to individual file imports automatically.

It will automatically transform your imports:

```js
import { Popup } from 'semantic-ui-react'

// becomes

import Popup from 'semantic-ui-react/dist/commonjs/modules/Popup'
```

Now, you're truly importing only the Popup module.

**Comment by pranjalk** [comment]
@levithomason Thanks!
