### ISSUE TITLE
Disabled Button with Label leaves Label enabled

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#1026]
### Steps
1. Create a disabled Button with label.

### Expected Result
Both the button and the label should be disabled.

### Actual Result
Only the button is disabled, the label is not.

This is because the `disabled` prop is passed to the `button` child.  It should instead be used to create a `disabled` className for the wrapping `div`.

### Version
v0.62.1

### Testcase
http://codepen.io/levithomason/pen/pNxwMb

**Comment by tarang9211** [comment]
@levithomason can we close this issue if it's fixed?

**Comment by levithomason** [comment]
We can once the PR is merged, https://github.com/Semantic-Org/Semantic-UI-React/pull/1035.

**Comment by tarang9211** [comment]
Yea, sorry about this! I meant to comment on another (already closed) issue!
