### ISSUE TITLE
What is the Path for NPM-installed Semantic-UI-React?

### ISSUE THREAD

**Issue by quadsurf** [Semantic-Org/Semantic-UI-React#1029]
I am trying to add webpack entry points for your js, but apparently I'm using the wrong "dist module path/name" ... please the 'entry' property/key below...

Steps to Recreate:
1. npm install semantic-ui-react --save
2. npm install semantic-ui-css --save
3. in webpack.config.js, I'm doing this:
module.exports = {
  entry: [
    'script!semantic-ui-css/semantic.min.js',
    'script!semantic-ui-react/dist/semantic-ui-react.min.js',
    './app/app.jsx'
  ]
4. in my app.jsx file, I added:
require('style!css!semantic-ui-css/semantic.min.css');

Can someone please let me know what the correct module paths are? The error I get is "Module not found: Error: Cannot resolve module"

**Comment by levithomason** [comment]
Take a look in your `node_modules` directory to find the full path.  Once you find our package, you can use the `package.json` `main` field to see the full path to the main module.

**Comment by quadsurf** [comment]
Thank you @levithomason , but now that I have it all wired up properly with the correct module name/path, it throws an error saying:
Cannot read property 'Component' of undefined

When I debug, it's actually M.Component ... so it's the 'M' that's undefined.

Here's my package.json
"dependencies": {
    "axios": "^0.15.3",
    "express": "^4.14.0",
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-router": "^3.0.0",
    "semantic-ui-css": "^2.2.4",
    "semantic-ui-react": "^0.62.1"
  }

Here's my webpack.config.js:
module.exports = {
  entry: [
    'script!semantic-ui-css/semantic.min.js',
    'script!semantic-ui-react/dist/umd/semantic-ui-react.min.js',
    './app/app.jsx'
  ],

Here's it's require statement in my app.jsx:
require('style!css!semantic-ui-css/semantic.min.css');

Building this using webpack yields a successful build and does not throw the error mentioned above, however Chrome & Firefox browsers do throw the error in the console, and it breaks the app  :-(
