### ISSUE TITLE
fix(Table): Keys warning when using renderBodyRow

### ISSUE THREAD

**Issue by bzuker** [Semantic-Org/Semantic-UI-React#1030]
**Steps to Reproduce**
Using the example from http://react.semantic-ui.com/collections/table#warning-shorthand.

If you don't specify a key, you get  'Warning: Each child in an array or iterator should have a unique "key" prop.'.

I believe it should be automatic when using the shorthand prop. It can be solved by adding 

```javascript
const renderBodyRow = ({ name, status, notes }, i) => ({
  key: i
  warning: !!(status && status.match('Requires Action')),
  cells: [
    {
      content: name || 'No name specified',
      key: i
    },
   {
    status
      ? { icon: 'attention', content: status }
      : 'Unknown',
      key: i+1
    },
    {
      notes
        ? { icon: 'attention', content: notes, warning: true }
        : 'None',
      key: i+2
    }
  ],
})
```

I've never done a PR before, sorry if this is easily solved!

**Comment by bzuker** [comment]
#599 I think this was already issued

**Comment by levithomason** [comment]
Note using `index` in a key is an antipattern that you'll want to avoid:
https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318#.x50rgq3q2

That said, we do have a method for auto-generating unique keys if the shorthand props are also unique.  We're adding tests to all examples to ensure they render with no errors.  This work required auto-generating keys.  You can see more in #645.
