### ISSUE TITLE
How to create a modal that focuses on an input box when the modal is opened?

### ISSUE THREAD

**Issue by Ctesias** [Semantic-Org/Semantic-UI-React#1036]
Hi,

How do you cause auto-focus on some element of a modal when it opens?  In this particular case, I'd like the cursor to appear in the first text input area of a form that makes up the body of my modal.

Thanks.

**Comment by caycecollins** [comment]
If you found this looking for a way to focus a Form.Input element upon opening a modal, here's a solution: https://codepen.io/inergy/pen/JvOjYb
