### ISSUE TITLE
fix(Modal): your description

### ISSUE THREAD

**Issue by Rajiv-Kulkarni** [Semantic-Org/Semantic-UI-React#1041]
**Steps to Reproduce**
1. Add react-boostrap to the application: npm install react-bootstrap --save
2. Add the modal code from the semantic ui component demo page to the about page on the react-slingshot demo app

**Expected**
The Modal should display normally like on the semantic ui component demo page.

**Result**
The Modal shows with full browser height and keeps flickering vigorously.
![image](https://cloud.githubusercontent.com/assets/12962858/21272732/1aac94ae-c386-11e6-9d9d-d26a7fbe7b2a.png)

I am not able to post a video of the modal behavior.

**Testcase**
If the docs show the issue, use: http://react.semantic-ui.com/modules/modal
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by Rajiv-Kulkarni** [comment]
Here is video of the behavior (attachment).

**Comment by levithomason** [comment]
Semantic-UI-React is not designed to be used in tandem with React Bootstrap.  You should choose one or the other framework.  It is not feasible to prevent all conflicts.

**Comment by milessorce** [comment]
@levithomason I am having the exact same issue, but I am **not** using Bootstrap or any other framework. Class for the component is switching between "ui modal transition visible active" and "ui scrolling modal transition visible active". Have you encountered this issue in any circumstance outside of someone trying to use Bootstrap with Semantic-UI-React?

**Comment by levithomason** [comment]
@milessorce we recently shipped some fixes to the Modal and className management, #2004.  Please update to the latest version.  If you are still having issues, please file a new issue and complete all the info in the issue template.  We can debug and fix any remaining issues there.
