### ISSUE TITLE
Sidebar docs's broken

### ISSUE THREAD

**Issue by lednhatkhanh** [Semantic-Org/Semantic-UI-React#1048]
Here's the log when I go to [sidebar docs](http://react.semantic-ui.com/modules/sidebar):

![capture](https://cloud.githubusercontent.com/assets/9303093/21291034/d7cf6402-c503-11e6-8490-610db7d40fa3.PNG)

**Comment by levithomason** [comment]
Thanks for the report.  There's a new deploying going out with the fix.
