### ISSUE TITLE
react.semantic-ui.com doesn't work !

### ISSUE THREAD

**Issue by Tilican** [Semantic-Org/Semantic-UI-React#1051]
Hi,
today the docs doesn't work !
http://puu.sh/sUwC7/2e495b57c1.png

Bye

**Comment by iamcaleberic** [comment]
@Tilican The docs have been available all day... maybe check your connection

**Comment by levithomason** [comment]
![image](https://cloud.githubusercontent.com/assets/5067638/21320177/f0e55c50-c5c4-11e6-9b0d-aec60560372f.png)
