### ISSUE TITLE
Dropdown selection sets value on blur

### ISSUE THREAD

**Issue by eXtreme** [Semantic-Org/Semantic-UI-React#1052]
It might sound related to recently fixed #1019 but it actually triggered me to report this issue. :) 

### This is Semantic UI:
![2016-12-19_11-37-25](https://cloud.githubusercontent.com/assets/197671/21310141/6b65861e-c5e1-11e6-8f20-1c5f775da3d0.gif)

### This is React SUI:
![2016-12-19_11-40-41](https://cloud.githubusercontent.com/assets/197671/21310125/5d96f162-c5e1-11e6-8d9e-11215fcd7f26.gif)

* * *

### Steps
1. Open a dropdown selection, which have no value set.
2. Blur the dropdown.

### Expected Result
The value should not be changed. "Empty" dropdown should stay in "empty" state.

### Actual Result
It sets the first value from dropdown. Blurring actually fires onChange event, even with selected value but not changed.

### Version
0.62.3

### Testcase
n/a or just use the docs

**Comment by jeffcarbs** [comment]
There's a `selectOnBlur` prop on `Dropdown` that defaults to `true`. I think setting this to false will fix your issue:

```jsx
<Dropdown selectOnBlur={false} /* other props */ />
```

If that doesn't fix it, feel free to reopen.

**Comment by nolawnchairs** [comment]
Is it just me, or should `false` be the default for this...

**Comment by mehrad77** [comment]
@mweiczorek  of course it should
