### ISSUE TITLE
Modal doesn't support animations

### ISSUE THREAD

**Issue by nix1** [Semantic-Org/Semantic-UI-React#1054]
### Steps
Open a modal.

### Expected Result
The modal doesn't animate while opening.

### Actual Result
The modal shows immediately, without any animation.

### Version
0.62.3

**Comment by levithomason** [comment]
No transitions are included until #813 is merged.

**Comment by completer** [comment]
Now `<Transition />` is done, should `<Modal />` have animation by default? Or do we need to enable it?

**Comment by levithomason** [comment]
Now that Transition is complete, it needs to be integrated into our own components. The Dimmer is getting transitions added in #2001. 

Perhaps you could submit a PR for the modal?
