### ISSUE TITLE
fix(Table): Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by UnbrandedTech** [Semantic-Org/Semantic-UI-React#1057]
### Steps
1. Create table with shorthand and use a custom element

### Expected Result
Should render Table

### Actual Result
Errors with `Cannot convert a Symbol value to a string`

### Version
0.62.3

### Testcase
http://codepen.io/UnbrandedTech/pen/mOvGxj?editors=0010

**Comment by levithomason** [comment]
Hm, master seems to be missing the commit that fixed this.  Hang tight.

**Comment by levithomason** [comment]
Working on this in #1062 with a wider reaching solution.
