### ISSUE TITLE
Object returned onBlur vs Event?

### ISSUE THREAD

**Issue by searleb** [Semantic-Org/Semantic-UI-React#1059]
Is it possible to return the same Object onBlur as is returned from the onChange event?

onBlur returns an Event, eg:
`Event {isTrusted: false, type: "react-input", target: react, currentTarget: react, eventPhase: 2…}`

onChange returns an Object, eg:
`Object {name: "shipping_id", search: true, placeholder: "Shipping method", defaultValue: 1, options: Array[2]…}`

My use case for this is that I'd like to save form updates when the user is done typing with onBlur and not hitting my API on every keystroke with onChange. 
That or I'm missing how to get the form data from the onBlur event?

### Testcase
http://codepen.io/searleb/pen/KNJWGd

**Comment by levithomason** [comment]
We only add the second `data` object to callbacks that we explicitly handle.  There a lot of event handlers one might add, so I don't think it is reasonable to add all the potential callbacks to all components (which would be required to pass back the `data` object).

That said, we only added this extra object as many components have callbacks for which there is no SyntheticEvent nor DOM event to send back.  In that case, you are flying completely blind.  We added the `data` parameter there as a stop gap until React someday allows dispatching custom SyntheticEvents.

What are you to do if there is no `data` object?  The same as you would do with vanilla React.  In this case, you should be capturing the `value` with `onChange` and then, `onBlur`, you can post that data to your server.

**Comment by searleb** [comment]
@levithomason Thanks for the super fast reply!
> In this case, you should be capturing the value with onChange and then, onBlur, you can post that data to your server.

I hadn't thought of that taking that approach, thanks for the insight 👍

**Comment by levithomason** [comment]
No problem!

**Comment by searleb** [comment]
Just for future reference if anyone else comes across this problem, it ended up being simpler than I thought:

```js
 handleOnBlur = ({ currentTarget }) => {
    const data = {
      name: currentTarget.name,
      value: currentTarget.value,
    }
    someFunction(data)
  }
```

```js
<Form.Input
  type='text'
  name='myInputField'
  onBlur={this.handleOnBlur}
  placeholder='Some input field'
/>
```
