### ISSUE TITLE
Failed prop type: Prop `selection` in `Dropdown` conflicts with props: `children`. They cannot be defined together, choose one or the other.

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#1061]
Hi, any reason for limiting dropdown selection to specify props only via options? "Selection" is the only way to render dropdown with borders. Thanks.

**Comment by levithomason** [comment]
Yep!  We manage the DropdownItem's `active` and `selected` states as well as event handlers for keyboard navigation and clicking, which also update the state.  You can pass your own menu and dropdown items if you wish, but you'll have to manage all these yourself.
