### ISSUE TITLE
[Question]   Form.Field control={Checkbox}   vs   Form.Checkbox

### ISSUE THREAD

**Issue by quadsurf** [Semantic-Org/Semantic-UI-React#1070]
When and why would you use or not use the "sugar" syntax? What is the difference between control usage and non-control usage? Pros and Cons?

`<Form.Field control={Checkbox} label="Check Here!" />`

versus

`<Form.Checkbox label="Check Here!" />`

**Comment by quadsurf** [comment]
https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by levithomason** [comment]
This is not for controlled/uncontrolled components, rather, it is for passing your own custom component.  Per the docs: http://react.semantic-ui.com/collections/form#field-with-custom-control:

>### Field with Custom Control
>Render a field containing a label and custom form control. Use any component from any library, or your own.
>```jsx
><Form.Field label='Date' control={CustomCalendar} start='1' end='7' />
>
>vs
>
><Form.Field>
>  <label>Date</label>
>  <CustomCalendar start='1' end='7' />
></Form.Field>
>```

Controlled/Uncontrolled components deal with whether or not you are controlling their state.
