### ISSUE TITLE
Addon support for semantic-ui-react.min.js

### ISSUE THREAD

**Issue by thuey** [Semantic-Org/Semantic-UI-React#1081]
This is more of a question than it is an issue. I apologize if this is the wrong place to ask this.

I'm trying to do some optimizations with webpack by only requiring `dist/umd/semantic-ui-react.min.js`. Is that not what is is intended for? It appears that addons are not included in the min file because I'm getting this error `Module not found: Error: Can't resolve './addons/Confirm'`

**Comment by levithomason** [comment]
The UMD build is meant for running directly in a browser script tag. For instance, we use it to power the codepen.io examples. It is probably the least optimized build we have :) it bundles several large modules and cannot be separated. 

For optimizing builds with webpack see https://github.com/Semantic-Org/Semantic-UI-React/issues/1025 and the links in the response for more info on optimizing with webpack.
