### ISSUE TITLE
Allow including only used LODASH functions in app bundle

### ISSUE THREAD

**Issue by PavelPZ** [Semantic-Org/Semantic-UI-React#1082]
Using e.g.
```
import isEqual from 'lodash/isEqual';
if (!isEqual(obj1, obj2)) return;
```
instead of
```
import * as _ from 'lodash';
if (!_.isEqual(obj1, obj2)) return;
```

can save app bundle size. 
e.g. if using JSPM package manager with Rollup Optimization.

**Comment by jeffcarbs** [comment]
Duplicate of #830, see this comment: https://github.com/Semantic-Org/Semantic-UI-React/issues/830#issuecomment-259785072
> We have this done automatically by babel using https://github.com/lodash/babel-plugin-lodash. Compare the src and dist directories to see it in action.

**Comment by PavelPZ** [comment]
@jcarbo, that's great, thanks for clarification.
