### ISSUE TITLE
dist in githignore... AND in package.json

### ISSUE THREAD

**Issue by andriytyurnikov** [Semantic-Org/Semantic-UI-React#1087]
See `.gitignore`
`dist/`

See `package.json`
`"main": "dist/commonjs/index.js"`

What is the idea behind it?

**Comment by layershifter** [comment]
Main idea - don't store result of build in git repository, while build's result is inside npm-package.

![_588](https://cloud.githubusercontent.com/assets/14183168/21495161/a24bac1a-cc1e-11e6-8062-e186a83eae0d.png)
