### ISSUE TITLE
How to import components on demand?

### ISSUE THREAD

**Issue by kossel** [Semantic-Org/Semantic-UI-React#1089]
I imported a button and it increased the js file size by around 500k which I guess I am importing everything.

`import { Buttom } from 'semantic-ui-react';`

Is it possible to import on demand only the core/common + the actual component?

**Comment by layershifter** [comment]
Duplicate #1025, please refer to this [comment](https://github.com/Semantic-Org/Semantic-UI-React/issues/1025#issuecomment-266872188).
