### ISSUE TITLE
Testing with Semantic UI Components

### ISSUE THREAD

**Issue by tomasfrancisco** [Semantic-Org/Semantic-UI-React#1090]
I'm using [React Boilerplate](https://github.com/mxstbr/react-boilerplate) with MJ's [expect](https://github.com/mjackson/expect), [enzyme](https://github.com/airbnb/enzyme) and Semantic UI React, and I want to test if some of my components are rendered correctly, including some of the semantic ui components, for example:

```
Import HomeHeader from '../index';
Import {Header} of 'semantic-ui-react';

Const renderedComponent = shallow (
    <HomeHeader />
);
Expect (renderedComponent.find (Header) .length) .toEqual (1);
```

But apart to all the tests done, unfortunately, I can not set a test correctly where I can find a node `Header`.
How can I use semantic components as part of my tests?

**Comment by tomasfrancisco** [comment]
NVM. I should use mount instead of shallow in order to render children nodes. I'm leaving this here so this can help anyone.

**Comment by levithomason** [comment]
Also, this project contains ~6,500 tests.  You can reference `/test/specs` for testing examples.
