### ISSUE TITLE
Typescript: Dimmer component doesn't exist.

### ISSUE THREAD

**Issue by wcatron** [Semantic-Org/Semantic-UI-React#1091]
Currently typescript throws "module has no exported member Dimmer" sure enough in the typescript declaration file between Checkbox and Dropdown (which are before and after Dimmer in the docs) there is no Dimmer component.

```js

export class Checkbox extends React.Component<CheckboxProps, {}> {
}

// Dimmer missing here.

// Dropdown
// ----------------------------------

```

I can work on a PR (I have to regardless) unless there's a typical person whose good at creating them by hand.

**Comment by levithomason** [comment]
Closed by #1092

**Comment by IsaackRasmussen** [comment]
Hi,

I just upgraded to 0.63.3 hoping it would fix this error:
error TS2324: Property 'dimmer' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ImageProps, ComponentState>> & { childre...'.

But that's perhaps a different issue?

I get it when I try to use Image

**Update:** I got it working with this workaround {...{dimmer: ""}}
From this other issue that seems similar: https://github.com/Semantic-Org/Semantic-UI-React/issues/698

**Comment by wcatron** [comment]
@IsaackRasmussen Yes that is a different issue. This issue was about the `Dimmer` component not the `dimmer` property.

The `{...{}}` is unfortunately a common work around we have to use when using the `as` property otherwise you shouldn't have to use it. I don't think #698 is the same problem you're having. You may want to open a new issue for adding the `dimmer` property to the `Image` component typescript definition.
