### ISSUE TITLE
Typings: Missing Typings for Components Portal, Reveal and Embed

### ISSUE THREAD

**Issue by cschmidli** [Semantic-Org/Semantic-UI-React#1096]
Typings are missing for the following components:
- [x] addons/Portal
- [x] elements/Reveal
- [x] modules/Embed

PS: maybe it would make sense to have an issue tag for typings :)

**Comment by koenvg** [comment]
Hey, I created a pull request for this [1136](https://github.com/Semantic-Org/Semantic-UI-React/pull/1136)

**Comment by levithomason** [comment]
Fixed in #1136
