### ISSUE TITLE
Sidebar.Pushable: Cannot read property 'Pushable' of undefined

### ISSUE THREAD

**Issue by davidthornton** [Semantic-Org/Semantic-UI-React#1099]
### Steps
1. Implement Sidebar.Pushable exactly as described in http://react.semantic-ui.com/modules/sidebar on top of react-boilerplate https://github.com/mxstbr/react-boilerplate (as top level, only component on page)
2. Get react error in red box:
```
TypeError: Cannot read property 'Pushable' of undefined
```

### Expected Result
Page should be pushable as in example at URL.

### Actual Result
React red box type error

### Version
semantic-ui-react version 0.63.3

### Testcase
Forked http://codepen.io/levithomason/pen/ZpBaJX
at http://codepen.io/anon/pen/YNKyLj

(but I'm not sure the environment I'm working in is properly emulated by this -- I have a docker/node/react-boilerplate image for local development)

**Comment by levithomason** [comment]
Hm, this must be something in your environment.

After fixing the codepen errors (open the console), it is working.  I also logged the Sidebar.Pushable component and it is there.  http://codepen.io/levithomason/pen/wgwGXj

The doc examples are tested and they are also working:
http://react.semantic-ui.com/modules/sidebar

Based on your error, my guess is that it is not imported.  It is saying `Sidebar === undefined`.
