### ISSUE TITLE
How to make all popups close when a popup is triggered?

### ISSUE THREAD

**Issue by cytey** [Semantic-Org/Semantic-UI-React#1105]
### Steps
1. Have multiple popups on a page
2. Click on all the popups

### Expected Result
All popups should have the props exclusive from semantic ui. At any one time, there should only be one popup active.

### Actual Result
All popups remain on the page

### Version
0.63.4

**Comment by levithomason** [comment]
There is no declarative way to find all instances of a component in React.  Limited awareness is baked in.  In jQuery, you can use a query selector to automatically find and close all popups.  Doing this at the library level is not possible without some required top-level provider component, which,  we have considered but currently have no plans to pursue.

Instead, if you'd like to have exclusive Popups, you should track their state in a single location in your app and use the controlled component pattern to close all popups when a new one is opened:

http://react.semantic-ui.com/modules/popup#controlled
