### ISSUE TITLE
Dropdown menu works only for the first click

### ISSUE THREAD

**Issue by ramigg** [Semantic-Org/Semantic-UI-React#1108]
After clicking dropdown menu once it doesn't respond anymore.
It happens here: http://react.semantic-ui.com/collections/menu

**Comment by svrcekmichal** [comment]
Hi, your issue is duplicate of #659 For me solution of @eXtreme worked.

**Comment by layershifter** [comment]
Yep, it's duplicate of #659.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.4`.
