### ISSUE TITLE
Update <ListItem /> propType validation

### ISSUE THREAD

**Issue by athurman** [Semantic-Org/Semantic-UI-React#111]
the propType header of the ListItem component (as well as all other props of ListItem)
should be update from string to node

``` console
Warning: Failed propType: Invalid prop `header` of type `object` supplied to `ListItem`, expected `string`. Check the render method of `ContactCSMDropdown`
```

**Comment by layershifter** [comment]
Looks like outdated issue, `List` was completely rewritten in update for v1.
