### ISSUE TITLE
Steps overflow container when cummulative step width exceeds container width

### ISSUE THREAD

**Issue by cdaringe** [Semantic-Org/Semantic-UI-React#1114]
### Steps
- create some steps in a small container

### Expected Result
- stacked steps

### Actual Result
- stacked steps only when first `Step`'s width is constrained by parent container

i tried this on the normal `semantic-ui` examples [here](http://semantic-ui.com/elements/step.html) and they _seem_ to be a more well behaved, but it could be an implementation false positive on my part. 

### Version
- 0.64.3

### Testcase
http://codepen.io/cdaringe/pen/oBNpOV?editors=0010

![step-group-breaking mov](https://cloud.githubusercontent.com/assets/1003261/21622814/9730ee28-d1bc-11e6-96f7-8119477e8915.gif)

**Comment by levithomason** [comment]
This appears to be a valid issue but CSS related.  I can reproduce this in the core SUI docs with this markup (I duplicated the steps so there are 6):

```html
<div class="container">
  <div class="ui steps">
      <div class="step">
        <i class="truck icon"></i>
        <div class="content">
          <div class="title">Shipping</div>
          <div class="description">Choose your shipping options</div>
        </div>
      </div><div class="step">
        <i class="truck icon"></i>
        <div class="content">
          <div class="title">Shipping</div>
          <div class="description">Choose your shipping options</div>
        </div>
      </div>
      <div class="active step">
        <i class="payment icon"></i>
        <div class="content">
          <div class="title">Billing</div>
          <div class="description">Enter billing information</div>
        </div>
      </div><div class="active step">
        <i class="payment icon"></i>
        <div class="content">
          <div class="title">Billing</div>
          <div class="description">Enter billing information</div>
        </div>
      </div>
      <div class="disabled step">
        <i class="info icon"></i>
        <div class="content">
          <div class="title">Confirm Order</div>
        </div>
      </div><div class="disabled step">
        <i class="info icon"></i>
        <div class="content">
          <div class="title">Confirm Order</div>
        </div>
      </div>
    </div>
</div>
```

![image](https://cloud.githubusercontent.com/assets/5067638/21623099/b36b5076-d1b5-11e6-8132-b1b156441c28.png)

Please file an issue on https://github.com/Semantic-Org/Semantic-UI itself for a CSS change.

**Comment by cdaringe** [comment]
cool.  thanks for following up @levithomason, you're great!

**Comment by levithomason** [comment]
No problem, thanks for the report 👍

**Comment by lubber-de** [comment]
Fixed by https://github.com/fomantic/Fomantic-UI/pull/397 and supposed to be part of Fomantic-UI 2.7.2
