### ISSUE TITLE
fix(Form): Disable Form.Select open dropdown in onfocus event

### ISSUE THREAD

**Issue by jmanuel1609** [Semantic-Org/Semantic-UI-React#1115]
**Steps to Reproduce**
1. disable Form.Select component
2. go to Name field.
3. Press tab to go to Gender field
4.  the component is disabled but still open the dropdown 

**Expected**
The Form should do this

**Result**
The Form does not do this

**Testcase**
If the docs show the issue, use: http://react.semantic-ui.com/collections/form
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by levithomason** [comment]
This is is an issue with the `Form.Field`, same as the [previous issue with the required prop](https://github.com/Semantic-Org/Semantic-UI-React/issues/911).  It should pass the`disabled` prop along to the `component` but it is instead disabling the form field and consuming the `disabled` prop.

![image](https://cloud.githubusercontent.com/assets/5067638/21630630/eb90215c-d1e7-11e6-9d06-5c98afddab6e.png)

We need to pass the disabled prop along.  _Fixed_ ~~The catch here is that a disabled component has different styling.  They are made partially transparent (`opacity: 0.45` by default).  If both the field and the control are `disabled` then there is double the opacity applied, once on the field, and again on the control.  We'll need to ensure only one component has the disabled style, preferably the field.~~

**Comment by NjordTech** [comment]
Thnaks for you response. what about for readOnly property in dropdown? right now readonly only work for Form.Input

**Comment by jmanuel1609** [comment]
thanks for your response. What about readonly property? is only working in Form.Input

**Comment by levithomason** [comment]
A Field cannot be `readOnly` so it does not consume the prop and is therefore always passed to the control.

**Comment by levithomason** [comment]
PR coming.
