### ISSUE TITLE
Dropdown as Menu.Item not reopen

### ISSUE THREAD

**Issue by alessiodionisi** [Semantic-Org/Semantic-UI-React#1117]
Dropdown as Menu.Item not reopen

### Steps
1. Open the dropdown
2. Close the dropdown
3. The dropdown is stuck closed

### Expected Result
Dropdown close and reopen

### Actual Result
The dropdown closes but not reopen

### Version
0.63.4

### Testcase
http://codepen.io/anon/pen/BpaMJR

### Error
`Uncaught TypeError: _this._dropdown.blur is not a function`

I will make a pull request with fixed dropdown

**Comment by layershifter** [comment]
Duplicate of #659.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.4`.
