### ISSUE TITLE
support other labelable controls in Form.Field in addition to Checkbox and Radio

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#1122]
Hello

We wrapped every Component in our own lib to enhance your Components.
Unfortunately the check of label support uses directly the Checkbox and Radio Components.

`// pass label prop to controls that support it`
`  if (control === Checkbox || control === Radio) {`

It would be better to check, if a label property is supported.
`  if (control.propTypes && control.propTypes.label) {`

So we can use our wrapped Component and other with label support too.

Thanks

**Comment by levithomason** [comment]
It is common place to strip `propTypes` in production.  This code would then work in development, but fail in production for many users.

The shorthand syntax exists as a convenience, though, we provide all necessary subcomponents for each component for these cases.  You should use the full component markup instead.

**Comment by levithomason** [comment]
For clarity, these three are equivalent:

```jsx
<Form.Input label='Enter Password' type='password' />

<Form.Field control={Input} label='Enter Password' type='password' />

<Form.Field>
  <label>Enter Password</label>
  <Input type='password' />
</Form.Field>
```
