### ISSUE TITLE
minCharacters and saveRemoteData for Dropdown setting missing?

### ISSUE THREAD

**Issue by kunokdev** [Semantic-Org/Semantic-UI-React#1124]
Hello,
is `minCharacters` and/or `saveRemoteData` property implemented for React Semantic UI Dropdown element? Can't be found in documentation and error such as this appears:

> **"Warning: Unknown prop `saveRemoteData` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop**

**Comment by levithomason** [comment]
These are indeed missing.  Would love a PR that added them :)

**Comment by levithomason** [comment]
Fix coming in #1690.  Note, `saveRemoteData` will not be implemented for the reasons noted in the PR.  Short answer, use Redux or some other standard data layer package.
