### ISSUE TITLE
If a Popup has child popup, modal or other widgets, the parent popup closes

### ISSUE THREAD

**Issue by dkwin** [Semantic-Org/Semantic-UI-React#1125]
### Steps
1. Create a parent popup that has a child popup, modal or a widget that has a popup like feature

### Expected Result
Parent popup should not close when the child popup is being used

### Actual Result
Parent popup closes prematurely when child popups are being used and interacted with.  Please see attached code pen.

### Version
x.y.z

### Testcase

Please see code pen of issue:  https://codepen.io/cipherous/pen/WRbPGo?editors=0010

**Comment by levithomason** [comment]
Most of the noted issues can be solved with `closeOnDocumentClick={false}`, see http://react.semantic-ui.com/addons/portal which powers the Popup and Modal.

As for the Popup/Modal z-index layering issue, this appears to be a CSS issue.  The `.ui.popup` selector has `z-index: 1900` while the `.ui.dimmer` for the Modal has `z-index: 1000`.  Although, I'm not sure there is a clear way to decide if Popups should open in front or behind Modals.  If you feel this is a bug, please file a CSS change issue over at https://github.com/Semantic-Org/Semantic-UI.

I should note, the self-managed `open` state in Modals and Popups can only be so smart out of the box.  I'd suggest pulling this state into your apps state management solution (redux or other) to manage it more precisely if needed.  You can reference #1106 where I've laid out a similar suggestion.
