### ISSUE TITLE
DataTable Component

### ISSUE THREAD

**Issue by cschmidli** [Semantic-Org/Semantic-UI-React#1133]
This is a follow up of the discussion regarding #1110 (pagination support) and possibly sorting as well. I understand that you think those features should be handled outside, but nevertheless, I believe they are very useful to many users and it would be great to find a way to make them part of the library.

One idea that comes to mind is to create a "wrapper" component and call it e.g. DataTable. This component excludes a lot of the flexibility that you have with using the Table (etc.) components separately, but it offers a very efficient way to display a lot of data (>20 rows) and supports features like pagination and sorting.

Here's a gist of the "DataTable" component I created and use in some of the projects (incl. a small example how to use it): https://gist.github.com/sagax85/d1fad8de71fdcebdd384736160418dac

What do you think? If you're interested, I gladly specify it in more detail here.

**Comment by UnbrandedTech** [comment]
I did something similar to that but I also added a search bar 
https://gist.github.com/UnbrandedTech/38262b2cc2372ed356e1a03d94dd9d3d

**Comment by levithomason** [comment]
I'd like to get something like this going.  Let's start a PR and hash out the API there.  👍

**Comment by cschmidli** [comment]
@UnbrandedTech do you wanna create a pull request with your example/solution? seems like a pretty good start.

**Comment by subodhpareek18** [comment]
I have another suggestion for a data table component. The header for such a table should be sticky.

There would be two ways to do it probably, 1 is that the header is fixed and the page scrolls with the rows, the other is table is fixed in size and the tbody has an overflow scrolls.

**Comment by subodhpareek18** [comment]
Also for anyone that hasn't seen this:
https://datatables.net/examples/styling/semanticui.html

The above example looks quite good.

**Comment by levithomason** [comment]
@zusamann Fantastic, I'd love to have this implemented in SUIR (without jQuery).

**Comment by CrisLi** [comment]
@levithomason Any progress on the DataTable component?

**Comment by levithomason** [comment]
I haven't seen any PR for it yet @CrisLi.

**Comment by JustinTRoss** [comment]
Any progress on this?

**Comment by siarheipashkevich** [comment]
Do you have any progress on this?

**Comment by subodhpareek18** [comment]
For now I've been working with `react-table` https://react-table.js.org/, really easy to work with and has almost all the features I need. And definitely the most elegant minimal design. Maybe someone could write a css wrapper on top using semantic-ui

**Comment by levithomason** [comment]
Folks, please try to refrain from simply asking for progress.  We get emails and notifications for all posts on GitHub and we try to do our best to respond to all of them.  The less noise the better job we can do for you and the community.  GitHub is best used for issues, fixes, and new features.

A good place to check progress is the PR list.  If there is no PR, there is more than likely no progress as all development is done in the open.

Another great option is the [Gitter channel](https://gitter.im/Semantic-Org/Semantic-UI-React). 
 There are active members in here who can also answer questions.

Thanks for understanding and helping us stay focused!

**Comment by levithomason** [comment]
Thanks to @rijk, we have improved how we handle stale issues, see #2761.   Reopening.

**Comment by seenasabti** [comment]
Re-openning
