### ISSUE TITLE
Dropdown: prop useLabels

### ISSUE THREAD

**Issue by petlju** [Semantic-Org/Semantic-UI-React#1134]
### Steps
prop useLabels set to false

### Expected Result
http://semantic-ui.com/modules/dropdown.html#/examples
See the Without Labels example
Selected items are displayed as a count of selected items, so if 3 are selected it displays: "3 selected"
Selected items stay in the list with highlighted with bold text and they can be deselected by clicking them.
### Actual Result
It is not yet implemented so useLabels currently does nothing

### Version
0.63.5

### Testcase
http://codepen.io/anon/pen/wgKzOb

**Comment by levithomason** [comment]
Thanks for adding this per our gitter chat @petlju.

Here are direct links:
http://semantic-ui.com/modules/dropdown.html#maximum-selections (without labels)
http://semantic-ui.com/modules/dropdown.html#text-labels

Also, I like the idea of the comma separated list, although, I only find the feature to support a total count.  Where exactly did you find the separated list with overflow ellipsis version?

![http://g.recordit.co/4Ck9ucuOs4.gif](http://g.recordit.co/4Ck9ucuOs4.gif)

**Comment by petlju** [comment]
Ah, my bad. I had changed to that myself when looking at a way to accomplish useLabels. I must have glanced at the wrong window when I wrote the issue, sorry about that. Have updated the issue.

**Comment by jamesuejio** [comment]
Any update on this? Would really love to have the without labels feature in React. Also if there's any way of customizing the text that gets displayed that would be awesome similar to https://semantic-ui.com/modules/dropdown.html#text-labels

**Comment by levithomason** [comment]
Would merge a PR from whoever needs this feature.  I have no need or funding for it ATM and I haven't heard anything from the core team on it.

**Comment by levithomason** [comment]
Closing this for housekeeping.  Again, we'd love a PR from the community on this.

**Comment by thehappycoder** [comment]
My quick & dirty solution:
```
class MyMultiselectDropdown extends Dropdown {
  renderLabels = () => {
    return undefined
  }

  renderText = () => {
    const { placeholder, search } = this.props
    const { searchQuery } = this.state

    const hasSelectedValues = !!this.state.value.length

    const classes = cx(
      placeholder && !hasSelectedValues && "default",
      "text",
      search && searchQuery && "filtered"
    )

    return (
      <div className={classes} role="alert" aria-live="polite">
        {hasSelectedValues
          ? `${this.state.value.length} items`
          : this.props.placeholder}
      </div>
    )
  }
}
```
