### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#1135]
Guys, thanks for all the fantastic work! 
I have one question concerning the optimisation of your lib.
Current bundle size is almost 700Kb. For front end framework it is a hefty size.
A big part of this a prop types. 
Would you consider removing them? Nowadays with typescript checking you get those props checked anyways.
Is it in any other way possible to downsize the file?
Thanks!

**Comment by layershifter** [comment]
@tomitrescak Yes, I've made some work on it and I'm going to finish it soon. Possibly, I'll finish it on this week.

Please follow #524 and #731 for more details.
