### ISSUE TITLE
Expose palette feature?

### ISSUE THREAD

**Issue by cdaringe** [Semantic-Org/Semantic-UI-React#1138]
How do you all feel about exposing the color palette programmatically?  I know that it _could_ be a little complicated, but perhaps something like:

```jsx
import { palette } from 'smr'

palette.blue // #some-blue-ish color code
```

maybe this is too simple and limiting, but could be really nice!

**Comment by levithomason** [comment]
For now, this library only renders JSX components down to valid SUI HTML (based on className).  You color values are stored only in the CSS theme you choose to load over the top of said HTML classes.  So, there is no way to import them directly from our library.

You might find [`getComputedStyle()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) helpful for extracting active CSS styles from DOM elements.

**Comment by cdaringe** [comment]
right, `getComputedStyle` was exactly what I was thinking.  in our app, we use `<SomeSUIRComponent color='blue'>` for those components that support it, but then also want to use `blue` in other components too.  trouble is, it's not readily available.  i can definitely add a palette to my app and getComputedStyles such that I can get that information, **however**, finding  what `blue` to use seems like a good fit for _the library that is aware of the theme_.  my app, by means of using SUI, attempts to be theme-styles-knowledge agnostic.  SUIR gives me prestyled components s.t. I don't need theme/CSS knowledge.  i still think it would be nice sugar for SUIR to provide!

**Comment by levithomason** [comment]
When you add `color='blue'` we literally just add `class='blue'` to the HTML ;)
