### ISSUE TITLE
Why don't you allow style tag in components?

### ISSUE THREAD

**Issue by empz** [Semantic-Org/Semantic-UI-React#1139]
I know SUI-React components doesn't match 1-to-1 to SUI ones, but sometimes a simple style: width set to the resulting HTML container is enough but right now this is only seem possible using className. In my case I use react-css-modules, so I mostly use styleName to style components and className only for big old global CSS rules.

I think having the possibility to add style tag to the components is a small thing but makes things easier. 

By the way, I'm using TypeScript.

**Comment by levithomason** [comment]
All components consume their own props and pass along all additional props to the underlying component.  So, the `style` tag is automatically passed along:

```jsx
<Button style={{ width: 500 }}>I'm Wide</Button>
```

![image](https://cloud.githubusercontent.com/assets/5067638/21786551/36502742-d679-11e6-800a-092a10f0948d.png)

**Comment by empz** [comment]
Well I guess it's a problem of the typings then  because I cannot define style in a Dropdown.

```
ERROR in ./ClientApp/components/Demo.tsx
(114,23): error TS2339: Property 'style' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<DropdownProps, ComponentState>> & Dropdo...'.
```

**Comment by levithomason** [comment]
Ah, indeed.  See https://github.com/Semantic-Org/Semantic-UI-React/issues/1072 for details.
