### ISSUE TITLE
fix(Menu): blur error

### ISSUE THREAD

**Issue by raptoria** [Semantic-Org/Semantic-UI-React#1145]
for the Dropdown Item example (MenuExampleDropdownItem) on the main documentation page, clicking more than once on the dropdown causes the following error:

         Uncaught TypeError: a._dropdown.blur is not a function
                    at t.a.handleClose (app.6253916….js:6717)
                    at t.value (app.6253916….js:6717)
                    at e.notifyAll (react-dom.min.js:12)
                    at r.close (react-dom.min.js:14)
                    at r.closeAll (react-dom.min.js:15)
                    at r.perform (react-dom.min.js:15)
                    at o.perform (react-dom.min.js:15)
                    at o.perform (react-dom.min.js:14)
                    at Object.T [as flushBatchedUpdates] (react-dom.min.js:14)
                    at r.closeAll (react-dom.min.js:15)
                a.handleClose @ app.6253916….js:6717
                value @ app.6253916….js:6717
                e.notifyAll @ react-dom.min.js:12
                close @ react-dom.min.js:14
                closeAll @ react-dom.min.js:15
                perform @ react-dom.min.js:15
                perform @ react-dom.min.js:15
                perform @ react-dom.min.js:14
                T @ react-dom.min.js:14
                closeAll @ react-dom.min.js:15
                perform @ react-dom.min.js:15
                batchedUpdates @ react-dom.min.js:14
                u @ react-dom.min.js:14
                r @ react-dom.min.js:14
                enqueueSetState @ react-dom.min.js:14
                r.setState @ react.min.js:12
                a.trySetState @ app.6253916….js:6672
                a.close @ app.6253916….js:6717
                a.closeOnDocumentClick @ app.6253916….js:6717

**Comment by levithomason** [comment]
Duplicate #659

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.4`.

**Comment by raptoria** [comment]
just tested ... it works! but now I'm getting a TypeScript error:

ERROR in ./src/components/TopMenu/TopMenu.tsx
(18,17): error TS2339: Property 'item' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<DropdownProps, ComponentState>> & { chil...'.
Child h

```
 <Menu inverted className={styles.root} attached='top'>
      <Dropdown item className='fileDropdown' text='File'>
          <Dropdown.Menu className={styles.dropdownMenu} >
            <Dropdown.Item icon='file' text='Something 1' />
            <Dropdown.Item icon='shopping basket' text='Something 2' />
            <Dropdown.Item icon='download' text='Something 3' />
            <Dropdown.Item icon='file excel outline' text='Export to Excel' />
            <Dropdown.Item icon='sign out' text='Quit  Application' />
          </Dropdown.Menu>
        </Dropdown>
 </Menu>
```

**Comment by levithomason** [comment]
Indeed, a bug was opened and PR already merged in fact, https://github.com/Semantic-Org/Semantic-UI-React/pull/1223.  This will be released soon.  Thanks for the note.

**Comment by raptoria** [comment]
thanks! you guys are awesome!
