### ISSUE TITLE
Typings: Modal

### ISSUE THREAD

**Issue by StevenHensgen** [Semantic-Org/Semantic-UI-React#1152]
The interface ModalProps has a couple of errors

1. **mountnode?: any** this is all lower case when it should be **mountNode**;
2. closeIcon is missing;
3. defaultOpen is missing;
3. onMount is missing;
4. unMount is missing;
5. onOpen is missing;

I am new to typeScripting so i could be missing something but if you attempt to pass these props you will get a TSLint warning such as

`Property 'mountNode' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ModalProps, ComponentState>> & { childre...'.`

e.g.

`<Modal
				mountNode={mountNode}
				open={this.state.showModal}
				onClose={this.close}
				closeIcon={true}
				dimmer={'blurring'}
			>
...
</Modal>`

### Version
semantic-ui-react@0.62.4

**Comment by levithomason** [comment]
Thanks for the report.  See #1153 for the `mountNode` casing fix.  As for the missing props, please update to the latest version of the library as they are included.
