### ISSUE TITLE
[Segment] Piled Segments not piling

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#116]
@levithomason and I were pairing through creating examples for the `Segment` component and stumbled upon a display issue with [Piled Segments](http://semantic-ui.com/elements/segment.html#piled). Opening bug as a reminder to address the problem outside the related work I'm doing in #112.

Here's what Piled segments **should** look like:

<img width="740" alt="screen shot 2015-11-20 at 9 10 21 am" src="https://cloud.githubusercontent.com/assets/440298/11303186/2df19220-8f67-11e5-980e-612a299b8110.png">

Here's what they look like currently:

<img width="890" alt="screen shot 2015-11-20 at 9 21 45 am" src="https://cloud.githubusercontent.com/assets/440298/11303381/28cdb16a-8f68-11e5-8df9-ba42810d61af.png">

**Comment by levithomason** [comment]
This has now been fixed as of Semantic UI `2.1.8`.  See here https://github.com/Semantic-Org/Semantic-UI/issues/1097. `.ui.piled.segment` should now have `z-index: 1`.
