### ISSUE TITLE
Can't set style using Typescript

### ISSUE THREAD

**Issue by Ghirigoro** [Semantic-Org/Semantic-UI-React#1162]
It seems like you can't currently apply inline styles to components using Typescript. For example:

```typescript
<Input style={{width:"50%"}}/>
```
results in the following compiler error:

>  error TS2339: Property 'style' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Input> & { children?: ReactNode; } & InputProps'.

I know the typings are still a work in progress, so this may already be a known issue, but if anyone knows of any workarounds in the meantime, they'd be greatly appreciated.

**Comment by layershifter** [comment]
@Ghirigoro Hello, this issue is duplicate for #1072. I'm working on it,  you can follow progress of it in my last comment. I'm planning to make PR for `Input` tomorrow.
