### ISSUE TITLE
Re-enable babel-plugin-transform-react-constant-elements when it’s not buggy

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#1168]
Tracking https://github.com/facebookincubator/create-react-app/issues/553

**Comment by levithomason** [comment]
This might actually be done now, see https://github.com/facebookincubator/create-react-app/issues/553#issuecomment-325298356.  We should enable it, run a build, and see if it is working correctly.

If not, let's just close this issue. It has been long enough.

**Comment by brianespinosa** [comment]
@levithomason looks like this is DOA per a comment today: https://github.com/facebook/create-react-app/issues/553#issuecomment-359196326

**Comment by levithomason** [comment]
Thanks, saw that and had been meaning to close this.
