### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by mariolamacchia** [Semantic-Org/Semantic-UI-React#1173]
Hello everybody, thanks for this amazing library 👍 

I'm trying to build a table with infinite scrolling. Normally this is achievable by using the [visibility behaviour](semantic-ui.com/behaviors/visibility.html#/examples), but apparently that isn't included here.

Is there another way to implement it or any plans to add support for visibility? I'd be happy to contribute to a PR.

**Comment by levithomason** [comment]
I hadn't figured this behavior would be ported, however, seeing that it does DOM manipulation, a React port probably makes sense.  I would love to review a PR for this.

Be sure to follow the [CONTRIBUTING.md](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/.github/CONTRIBUTING.md).  It is a step-by-step guide to development in this project and meant to be read starting at the top and progressing through.  It covers everything from environment setup to docs and testing.

Cheers!

**Comment by layershifter** [comment]
Closed via #1174.
