### ISSUE TITLE
bug(Modal): "trigger" component prop disappears on production build

### ISSUE THREAD

**Issue by asandex** [Semantic-Org/Semantic-UI-React#1175]
Since version 0.64.0 on production build "trigger" prop not rendering.

Even on your landing site http://react.semantic-ui.com/modules/modal no buttons to show modals (uncontrolled ones).

**Comment by layershifter** [comment]
@Asande Thanks for report! PR is near.

**Comment by levithomason** [comment]
Fixed in `semantic-ui-react@0.64.2`.
