### ISSUE TITLE
Invalid argument to oneOf

### ISSUE THREAD

**Issue by flipvrijn** [Semantic-Org/Semantic-UI-React#1177]
### Steps
1. Use the Segment component

### Expected Result
No warnings

### Actual Result
Get warning:
`warning.js:36 Warning: Invalid argument supplied to oneOf, expected an instance of array.`

### Version
0.64.1

### Source code origin
Warning comes from this line:
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/elements/Segment/Segment.js#L90

**Comment by layershifter** [comment]
Thanks for report. This will be fixed in #1176.

**Comment by levithomason** [comment]
Fixed in `semantic-ui-react@0.64.2`.
