### ISSUE TITLE
Problems with typescript definitions

### ISSUE THREAD

**Issue by Raptoer** [Semantic-Org/Semantic-UI-React#1188]
I'm trying to use the typescript definitions provided, however I'm running into two problems within the definitions.

1. FormInputProps extends both InputProps and ReactFormEvents<HTMLInputElement>. Each of these contain an 'onChange' property that have different types.

2. Divider exports itself as Container, since Container already exists, it fails. This is probably just a typo in the definitions.

**Comment by layershifter** [comment]
@Raptoer Thanks for report. This might be fixed in #1179.

**Comment by layershifter** [comment]
Duplicate #1180.
