### ISSUE TITLE
How to call action on input

### ISSUE THREAD

**Issue by themre** [Semantic-Org/Semantic-UI-React#1189]
Hi,
I'm looking at <Input /> component and I just can't find docs where it shows how to call some function with `action` props. For example:
```
const InputExampleAction = () => (
  <Input action={{content:'Search', icon:'search'}} placeholder='Search...' />
)
```
Where do I put here callback function on Search button? Could someone help me? Thanks!

**Comment by themre** [comment]
I would also like to perform action on enter key. How can I achieve this since I don't see `onKeyDown` props?

**Comment by levithomason** [comment]
You can pass _any_ prop to the `action` as a key/value pair:
```jsx
const log (...args) => console.log(...args)

const InputExampleAction = () => (
  <Input 
    action={{ content: 'Search', icon: 'search', onKeyDown: log }} 
    placeholder='Search...'
  />
)
```

This is true for all shorthand props.  In fact, you can pass a number, string, props object, or an entire element.  So, you could also do this:

```jsx
const log (...args) => console.log(...args)

const InputExampleAction = () => (
  <Input 
    action={<Button content='Search' icon='search' onKeyDown={log} />}
    placeholder='Search...'
  />
)
```

**Comment by Thebigbignooby** [comment]
this should be in the docs, as this information is what I was missing.
also is there an easy way to get the input value in the action callback ?

**Comment by levithomason** [comment]
We do have [shorthand docs](#561) on the radar, time allowing.  This page would show many examples of all forms of our shorthand.  It will likely include examples with callbacks.

However, passing functions as props in this way is not unique to SUIR, it is just how React itself works.  Props are just an object of key/value pairs.

Given:
```jsx
const handleClick = () => console.log('you clicked me')
```

All of these are equivalent:
```jsx
<input onClick={handleClick} />

React.createElement('input', { onClick: handleClick })

const props = { onClick: handleClick }
React.createElement('input', props)

const props = { onClick: handleClick }
<input {...props} />
```

**Comment by frederikcreemers** [comment]
What does the `onKeyDown` action prop do? The `Button` component doesn't accept an `onKeyDown` prop. And even if it does, will that event fire when the user presses the enter key while the input field is focussed?

**Comment by themre** [comment]
`onKeyDown` is passed to actual input element. it's the same as you would type `<input onKeyDown={...} />`. You get `event` where you can check `event.key === 'Enter'` for Enter key or any other.

**Comment by levithomason** [comment]
>What does the onKeyDown action prop do?
The same as a vanilla React `<button onKeyDown={} />` does.
 
>The Button component doesn't accept an onKeyDown prop.

All unhandled props are passed to the underlying component.  This is a best practice but also required for expected usage.  Otherwise, you couldn't do something like `<Button data-foo />`.  We would have to explicitly code in support for every possible prop a user might pass.  Hence, we just pass all unhandled props straight through.

>And even if it does, will that event fire when the user presses the enter key while the input field is focussed?

Nope.  You are rendering the listener on an adjacent element:

```html
<div>
  <input />
  <button onKeyDown={} />
</div>
```

If you'd like to call the action when a key was pressed in the input, then you'd assign an `onKeyDown` listener to the input and call the same method on "enter" as the `action` calls `onClick`.
