### ISSUE TITLE
Dropdown.Item ignores 'value' property

### ISSUE THREAD

**Issue by Raptoer** [Semantic-Org/Semantic-UI-React#1191]
Dropdowns make a hidden select element as well as a tree of divs which are visible.
Inside the select there are options which contain both the text and the value properties.
Inside the tree of divs there are a number of div.item which contain the text, but not the value.

When the onChange handler is called the HTMLElement inside the event points to the div.item. Therefore the value property is difficult to access from the change handler.

This can actually be seen in the default codepen:
http://codepen.io/levithomason/pen/ZpBaJX
Although you have to go through the dom to find it.

**Comment by levithomason** [comment]
Use the second `data` object parameter which includes all the props of the item, including `value`.  One example is here: http://react.semantic-ui.com/modules/dropdown#allow-additions.

Once we get callback signatures listed in the docs, this will also be made more clear as the prop table will show precisely which arguments and values the callbacks are called with.  This is coming soon!

**Comment by levithomason** [comment]
I've just shipped the function signatures update to the docs.  You can now see callback arguments along with their types and descriptions:

![image](https://cloud.githubusercontent.com/assets/5067638/22144022/1c391d60-deb1-11e6-8a7a-72787825cde0.png)
