### ISSUE TITLE
How to upgrade to newer semantic-ui-react ?

### ISSUE THREAD

**Issue by littlehome-eugene** [Semantic-Org/Semantic-UI-React#1196]
I find placing form inside modal is not possible with old version. (so it seems based on other git issues)

I tried upgrading to newer semantic-ui-react but couldn't find how to.

`npm ERR! git /home/eugenekim/Documents/zibann-reservation/momsite/node_modules/semantic-ui-react: Appears to be a git repo or submodule.`

**Comment by mistakenelf** [comment]
Find what packages are outdated: `yarn outdated`
Update packages: `yarn upgrade-interactive`, then select the packages you want to upgrade

**Comment by levithomason** [comment]
Please Google around for this answer, you'll find it :)
