### ISSUE TITLE
Form inside modal?

### ISSUE THREAD

**Issue by littlehome-eugene** [Semantic-Org/Semantic-UI-React#1197]
### Steps
1. Boil water.

Display form inside modal

### Expected Result

Want to see the modal filled with form

### Actual Result

Form is shown briefly in full view (not modal), but disappears.
There is another form in outer page which hosts the modal. and the outer form seems to be submitted automatically after form trigger button is clicked.

### Version
x.y.z
tried 
0.58.3
0.64.3

### Testcase
Fork this to show the issue: http://codepen.io/levithomason/pen/ZpBaJX

```

 $(document).ready(function() {

   $("textarea#id_crontab_include").after("<div id='cronGenerator'></div>")

   ReactDOM.render(
     <Provider store={store}>
       <CronGeneratorModal />
     </Provider>,
     document.getElementById('cronGenerator')

   );
 })

 var CronGeneratorModal = React.createClass({

   getInitialState() {
     return {
       modalOpen: false,
     }                                                                                                                                                                             },

   render: function() {
     const { modalOpen } = this.state

     return (
       <Modal
         trigger={
             <Button
                 onClick={(e) => this.setState({modalOpen: true})}
                 >
             수정
           </Button>
         }
         onClose={this.closeModal}

```         open={modalOpen}

...

**Comment by littlehome-eugene** [comment]
I find it has nothing to do with form + modal. closing ..

**Comment by joonas-yoon** [comment]
I will try to this too and i found following issue. https://github.com/Semantic-Org/Semantic-UI/issues/2554

but it is not working with form validation.
I hope this helped you. 😄
