### ISSUE TITLE
Errors in Typings

### ISSUE THREAD

**Issue by L3V147H4N** [Semantic-Org/Semantic-UI-React#1198]
the following errors are thrown by the index.d.ts when using TypeScript
```

(176,11): error TS2320: Interface 'FormInputProps' cannot simultaneously extend types 'InputProps' and 'ReactFormEvents<HTMLInputElement>'.
  Named property 'onChange' of types 'InputProps' and 'ReactFormEvents<HTMLInputElement>' are not identical.
```

`(25,1): error TS2308: Module './dist/commonjs/elements/Container' has already exported a member named 'Container'. Consider explicitly re-exporting to resolve the ambiguity.`

**Comment by layershifter** [comment]
Duplicate #1180.
