### ISSUE TITLE
Modal TextArea / Input Bug

### ISSUE THREAD

**Issue by mattmacpherson** [Semantic-Org/Semantic-UI-React#1199]
When typing in a TextArea or Input (in a modal), the TextArea / Input loses focus on keypress.

https://codepen.io/methodx/pen/OWpYaW?editors=0010

**Comment by dealvz** [comment]
this change works fine

https://codepen.io/anon/pen/qRmqRQ?editors=0011

**Comment by flipvrijn** [comment]
Running in same issue: http://codepen.io/anon/pen/QdvRLj

**Comment by mattmacpherson** [comment]
@flipvrijn Reverting to 0.64.0 solved the issue for me (for now).

**Comment by levithomason** [comment]
Thanks folks, guessing it was introduced in https://github.com/Semantic-Org/Semantic-UI-React/pull/1154.  I'm taking a look now.

**Comment by levithomason** [comment]
When the parent re-renders, the portal assumes focus again.  The solution is to simply focus the Portal only on the initial render.  PR coming shortly.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.4`.
