### ISSUE TITLE
Menu Dropdown bug

### ISSUE THREAD

**Issue by johannchen** [Semantic-Org/Semantic-UI-React#1201]
There is a bug on menu dropdown at the demo site http://react.semantic-ui.com/collections/menu

It displays the dropdown correctly for the first click, but it has an error (dropdown item won't show) when the dropdown is clicked again.

here is the console error
Uncaught TypeError: a._dropdown.blur is not a function

**Comment by levithomason** [comment]
Duplicate #659

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.4`.

**Comment by johannchen** [comment]
awesome! Thanks!!
