### ISSUE TITLE
Modal "trigger" missing in Typescript Typings

### ISSUE THREAD

**Issue by tilor** [Semantic-Org/Semantic-UI-React#1202]
The typings for the Modal component miss an entry for "trigger", so the code does not compile without errors.
Adding "trigger?: any;" in Modal/index.d.ts ModalProps fixes the problem for me.

**Comment by levithomason** [comment]
This is due to the fact that the Modal itself does not advertise this prop.  Duplicate #1169.

**Comment by tilor** [comment]
This is still not solved in 0.64.5 - #1169 sounds like the problem should be gone now?

**Comment by levithomason** [comment]
I see this as an open item on that issue still.  Could you clarify what you are seeing?

***

![image](https://cloud.githubusercontent.com/assets/5067638/22601645/a8921bb0-e9f4-11e6-8a25-86ba34a1a66d.png)

**Comment by tilor** [comment]
Levi,

Sorry, I see the same view, but didn’t get that the „Modal->Portal“ item will fix the missing „target“ option.

Best,

Tilo


Von: Levi Thomason [mailto:notifications@github.com]
Gesendet: Freitag, 3. Februar 2017 18:41
An: Semantic-Org/Semantic-UI-React <Semantic-UI-React@noreply.github.com>
Cc: Tilo Rossmanith <tr@rossmanith.com>; Author <author@noreply.github.com>
Betreff: Re: [Semantic-Org/Semantic-UI-React] Modal "trigger" missing in Typescript Typings (#1202)


I see this as an open item on that issue still. Could you clarify what you are seeing?

________________________________

[image]<https://cloud.githubusercontent.com/assets/5067638/22601645/a8921bb0-e9f4-11e6-8a25-86ba34a1a66d.png>

**Comment by levithomason** [comment]
No worries, thanks for the follow up.
