### ISSUE TITLE
expand nested tags in Emmet

### ISSUE THREAD

**Issue by hyperborea** [Semantic-Org/Semantic-UI-React#1207]
Not so much an issue with semantic-ui-react but rather a question to the community: how do you expand tags like Menu.Item in Emmet without it interpreting it as css?

Example:
"Form.Input" -> Ctrl+e should be expanded to `<Form.Input />` or `<Form.Input></Form.Input>`
Instead it gets completed to `<Form className="Input"></Form>`

**Comment by levithomason** [comment]
I usually just expand the `Form` then add the subcomponent.  I've not found a way to force `.` to expand as is without assuming it is a `className`.
