### ISSUE TITLE
Typings: missing prop "item" for Dropdown

### ISSUE THREAD

**Issue by rokoroku** [Semantic-Org/Semantic-UI-React#1222]
**Steps**

```jsx
<Dropdown item/>
```

It occurs

```
[ts] Property 'item' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<DropdownProps, ComponentState>> & Readon...
```

From documentation: `item`{bool}: A dropdown can be formatted as a Menu item.

**Version**

0.64.4

**Comment by levithomason** [comment]
@layershifter when you hit Dropdown's typings, can you add this?  Thanks!

**Comment by levithomason** [comment]
Ignore me, didn't see the PR was already opened :)
