### ISSUE TITLE
Modals aren't displaying in Internet Explorer 

### ISSUE THREAD

**Issue by EwanValentine** [Semantic-Org/Semantic-UI-React#1227]
I'm not sure if this is a CSS issue or a JS issue, but modals don't seem to be appearing on I.E 10 or 11, on Windows 8.1 and Windows 10 respectively. 

I'm using version 0.64.4 of this library.

**Comment by layershifter** [comment]
I'm tested locally in IE, all works, slow but works 😄 

After #1228 will be merged, I'll take a look on our docs site.

**Comment by EwanValentine** [comment]
@layershifter thank you!

**Comment by levithomason** [comment]
@layershifter update?

**Comment by layershifter** [comment]
Windows 8, IE 11. All works fine. @EwanValentine can you make a codepen?

**Comment by layershifter** [comment]
@EwanValentine Update?

**Comment by EwanValentine** [comment]
@layershifter I'll update everything and double check tonight, and make a codepen :)

**Comment by layershifter** [comment]
Closing for housekeeping. Can be reopened if we get a codepen.
