### ISSUE TITLE
Compile errors about missing babel-runtime after update to latest

### ISSUE THREAD

**Issue by mikesparr** [Semantic-Org/Semantic-UI-React#1229]
### Steps
1. `npm uninstall semantic-ui-react` (version 0.62.4)
2. `npm install --save semantic-ui-react` (version 0.64.4)

### Expected Result
No breakage of application

### Actual Result
Compile errors:
~~~
Failed to compile.

Error in ./~/semantic-ui-react/dist/commonjs/collections/Breadcrumb/BreadcrumbDivider.js
Module not found: 'babel-runtime/helpers/extends' in /Users/mike/Work/leadsbycell-web/node_modules/semantic-ui-react/dist/commonjs/collections/Breadcrumb

 @ ./~/semantic-ui-react/dist/commonjs/collections/Breadcrumb/BreadcrumbDivider.js 7:16-56
~~~

### Version
0.64.4

**Comment by mikesparr** [comment]
I've also deleted `semantic-ui-react` folder entirely in `node_modules` and retried with same error. I even removed `Breadcrumb` import from project and same thing, and then ran `npm update` and same.

**Comment by mikesparr** [comment]
I installed `npm-check-updates` and it upgraded various packages and retried and errors go away. I suspect there is some dependency on newer version of react or react-scripts libs. Closing but might check to see what versions are minimum.

**Comment by levithomason** [comment]
NPM doesn't always get the dependency tree correct.  With the flattening introduced in NPM 3 there were several issues, though it is getting better.  Sometimes it just takes a complete `rm -rf` and `npm i` to get the proper dependency tree.

In this case, `babel-runtime` was missing or it had a bad release.
