### ISSUE TITLE
Grid column fixed width

### ISSUE THREAD

**Issue by themre** [Semantic-Org/Semantic-UI-React#1241]
Hi,
I'm looking at Grid API and I'm seeing width prop as number which calculates widths of all columns in percent. Would it be possible to add width also as string prop, so I could have one column as fixed width? E.g. `<Grid.Column width='300px' >...</Grid.Column>`? Thanks!

**Comment by layershifter** [comment]
@themre For now, this library only renders JSX components down to valid SUI HTML (based on className), so `width` prop only transforms its value to SUI classes:

```jsx
<Grid.Column width={10} /> // <div class="ten wide column"></div>
<Grid.Column width='10' /> // <div class="ten wide column"></div>
<Grid.Column width='ten' /> // <div class="ten wide column"></div>
```

If you want to set fixed width use `style`:
```jsx
<Grid.Column style={{width: '300px'}} />
```

However, remember that the main idea of SUI's grid is to be responsive (flexbox).

**Comment by themre** [comment]
ok thanks. well, with flexbox you can also fix one column and have others to take the remaining space.
