### ISSUE TITLE
Dropdown options update triggered by onSearchChange

### ISSUE THREAD

**Issue by jhartma** [Semantic-Org/Semantic-UI-React#1242]
In my dropdown module, the options consist of a list of users which are fetched remotely and based on the search value of the dropdown.

```js
<Form.Field
  allowAdditions
  control={Dropdown}
  loading={this.props.loading}
  onSearchChange={this.onSearchChange.bind(this)}
  options={this.state.users}
  placeholder="Select user"
  search
  selection
/>
```
When some characters are rendered in the seach field, the dropdown options should display the fetched results. 

Strangely, this works when there is only one result. When there are more, no results are shown. I do see the options correctly shown in as ```<options>``` in the ```<select>``` node, but the corresponding ```<DropdownItem>``` are not rendered. Logging the results in the console also shows them. When I blur the search box and focus it again, the results are all there. So it seems like the dropdown options don't update when there is more than 1 result.

**Comment by levithomason** [comment]
This is a use case for the `<Search />`. However, what you described should work as well. 

Please provide a codepen repro and we'll look into it.

**Comment by jhartma** [comment]
I cobbled together a codepen [here](http://codepen.io/anon/pen/GryKxx?editors=0011) 

And the ```<Search />``` component is great, only that I need the ```allowAdditions``` prop which the ```<Dropdown />``` offers

**Comment by jhartma** [comment]
Okay I got it working, I close the issue

**Comment by dackers86** [comment]
@jhartma Would it be possible to explain how you fixed your solution?

I am experiencing the same problem, the options will only update after a fetch once the I have clicked off screen...?

      <Dropdown
        allowAdditions
        options={this.state.addressOptions}
        placeholder='Please enter your address'
        search
        selection
        fluid
        onChange={this.handleChange}
        onSearchChange={this.handleSearchChange.bind(this)}
      />

**Comment by jhartma** [comment]
Yep, this works for some reason:

```js
<Form.Field
  allowAdditions
  control={Dropdown}
  disabled={disabled}
  fluid
  id="input-invite-user"
  loading={this.props.loading}
  onAddItem={this.handleAddition}
  onChange={this.handleChange.bind(this)}
  onSearchChange={this.onSearchChange.bind(this)}
  options={users}
  placeholder="Select user"
  search
  selection
  value={value}
  width="7"
 />
```
