### ISSUE TITLE
Bug(Popup): Clicking on another Popup's trigger doesn't close open Popups.

### ISSUE THREAD

**Issue by keeslinp** [Semantic-Org/Semantic-UI-React#1251]
### Steps
1. Open an on="click" popup
2. Click on another trigger for a different on="click" popup while the first is still open
### Expected Result
The first Popup should close and the second should open

### Actual Result
Both Popups stay open.

### Version
0.64.4
### Testcase
Here's an example:
http://codepen.io/anon/pen/XpVqKq

It happens on the doc page as well:

![screen shot 2017-01-30 at 9 53 14 am](https://cloud.githubusercontent.com/assets/3063404/22432376/f70eeb7c-e6d1-11e6-9bc1-966f23428d03.png)

**Comment by levithomason** [comment]
Yep, the trigger click handler is stopping propagation.  We should instead be checking if the click was inside the trigger node, rather than stopping the event from propagating.

https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/addons/Portal/Portal.js#L249

**Comment by levithomason** [comment]
PR coming.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.7`.

**Comment by Ivaylo-Bachvarov** [comment]
The issue seems to be back: 
![image](https://user-images.githubusercontent.com/1764612/42287439-ff6dc14e-7fbe-11e8-96ba-311556cab519.png)

**Comment by bwoodlt** [comment]
Any update on this issue? I'm having exactly the same experience as described above.

**Comment by layershifter** [comment]
Please don't post anything in the old closed issues. If you have an issue, please fill a new issue with issue template.
