### ISSUE TITLE
breaking(Popup): rename `positioning` to `position`

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#1259]
Many components currently accept a `position` prop.  The `Popup`, however, calls this prop `positioning`.  We should update the Popup prop `positioning` to be `position`.

This new prop name needs to be updated in:
- the component
- tests
- doc site usages

Since the old prop will no longer work, this will be a breaking change and ship with the next minor bump of the library (since we are pre 1.0).

**Comment by tarang9211** [comment]
@levithomason I'll pick this up.

**Comment by tarang9211** [comment]
@levithomason I thought I was picking this one up?

**Comment by levithomason** [comment]
I'd take this up with @kamdz.  I have no control over who does what since it is open source. Perhaps open your PR immediately after you begin work on the issue, as well as leave a comment.

That said, all PRs are gladly accepted from anyone who submits them :)  I surely don't want to hinder folks from contributing.

**Comment by levithomason** [comment]
Merged in #1342
