### ISSUE TITLE
Dropdown positioning preventing user interaction

### ISSUE THREAD

**Issue by 10SPD** [Semantic-Org/Semantic-UI-React#1261]
The dropdown menu module is not working like it does on the Semantic website.

Including your [examples](http://react.semantic-ui.com/modules/dropdown) - when a dropdown is near the bottom of a page, it cuts off the option list and becomes out of view. The expected behavior would be to position the dropdown values at the top of the input instead of bottom (when it does not fit on the page). 

This is causing issues for many of our popup windows and even flat pages where dropdown options are at the bottom of our pages.

**Comment by levithomason** [comment]
Please search prior to posting, duplicate #720
