### ISSUE TITLE
some help popup inside popup not work 

### ISSUE THREAD

**Issue by yjose** [Semantic-Org/Semantic-UI-React#1272]
some help please:  popup inside popup not work

**Comment by levithomason** [comment]
http://codepen.io/levithomason/pen/jyzYvy

![http://g.recordit.co/4G48maNk7K.gif](http://g.recordit.co/4G48maNk7K.gif)

**Comment by yjose** [comment]
@levithomason  can you test this example I think it doesn't work correctly

**Comment by yjose** [comment]
@levithomason

**Comment by levithomason** [comment]
Updated, the click was propagating to the document.  I've disabled `closeOnDocumentClick` to support the nested Popups:

![http://g.recordit.co/8U9tLgLKw2.gif](http://g.recordit.co/8U9tLgLKw2.gif)
