### ISSUE TITLE
bug(Dropdown): Arrow keys are not working after `No results found.`

### ISSUE THREAD

**Issue by kirillku** [Semantic-Org/Semantic-UI-React#1275]
### Steps
1. Go to [search-selection dropdown](http://react.semantic-ui.com/modules/dropdown#search-selection)
2. Type something (e.g. `af`)
3. If you will use arrow up and down keys, everything is working as expected
3. Add one letter to search field, so there will be no results (`afs`)
4. Remove this letter (`af`)
5. Arrow keys are not working anymore (`Uncaught TypeError: Cannot read property 'disabled' of undefined`)

**Comment by levithomason** [comment]
Thanks much!  PRs welcome, otherwise, I'll get this fixed soon as I can.

**Comment by levithomason** [comment]
See #1279
