### ISSUE TITLE
Typings issue when using "as" component

### ISSUE THREAD

**Issue by L3V147H4N** [Semantic-Org/Semantic-UI-React#1276]
Just as an example: 
`<Sidebar as={Menu} animation='overlay' width='thin' visible={sidebar} vertical inverted>`
missing properties on: **Sidebar** when using as={Menu} property
+ vertical
+ icon
+ inverted

The properties belong to Menu of course not to Sidebar, so Typescript reports that there are no such properties on Sidebar, which is true.

I Know that this is a false warning but: Is there a possible workaround this? is there a way to tell Typescript to look up on the properties of the "as" component instead?

**Comment by ericl85** [comment]
See #1072. It's essentially the same issue.

I'm working around it for now like this:

```
<Sidebar as={Menu} animation="push" width="thin" visible={this.props.open} {...{inverted: true, vertical: true}}>
```

**Comment by L3V147H4N** [comment]
hmm, cool, if it get rid of the error messages it should work for now, thanks!

**Comment by layershifter** [comment]
Duplicate, #1072.
