### ISSUE TITLE
label is not changing style if field is inline

### ISSUE THREAD

**Issue by AgentChris** [Semantic-Org/Semantic-UI-React#1277]
<Form.Input label='First name' placeholder='First name' inline error/>

this is happening because inline has the color black and is overwriting the red color from error class
inline:
.ui.form .inline.field>label, .ui.form .inline.field>p, .ui.form .inline.fields .field>label, .ui.form .inline.fields .field>p, .ui.form .inline.fields>label {
    display: inline-block;
    width: auto;
    margin-top: 0;
    margin-bottom: 0;
    vertical-align: baseline;
    font-size: .92857143em;
    font-weight: 700;
    /* color: rgba(0,0,0,.87); */
    text-transform: none;
}
error:
.ui.form .field.error .input, .ui.form .field.error label, .ui.form .fields.error .field .input, .ui.form .fields.error .field label {
    color: #9f3a38;
}

**Comment by AgentChris** [comment]
a quick and a dirty fix would be:
<label htmlFor={input.name} style={(error && touched) ? { color: "#9f3a38" } : {}}>{label}</label>

to overwrite the inline black clor

**Comment by levithomason** [comment]
Confirming this is an issue, however, it is a CSS issue.  This repo only contains JS React components. Please post CSS issues on the main repo at https://github.com/Semantic-Org/Semantic-UI/issues.

As an aside, SUIR cannot override the color value to `#9f3a38` as this assumes that all users' themes use the same error color.
