### ISSUE TITLE
fix(Form): your description

### ISSUE THREAD

**Issue by damandos** [Semantic-Org/Semantic-UI-React#1288]
**Steps to Reproduce**
1. Do something
2. Do something else.

**Expected**
The Form should do this

**Result**
The Form does not do this

**Testcase**
If the docs show the issue, use: http://react.semantic-ui.com/collections/form
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by levithomason** [comment]
This appears to be the default issue template that is generated when clicking the bug icon an example in the docs.  Closing for housekeeping.
