### ISSUE TITLE
RFC: New types for typings

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#1289]
We have `customPropTypes` for our shorthands and it works fine :smile: But, their represent in typings is not obvious.

My suggestion is to add new types for `customPropTypes` and update existing typings:

```ts
type ShorthandCollection = Array<ShorthandItem>; // for customPropTypes.collectionShorthand
type ShorthandContent = React.ReactNode; // for customPropTypes.contentShorthand
type ShorthandItem = any; // for customPropTypes.itemShorthand
```

@levithomason any feedback?

**Comment by levithomason** [comment]
This sounds really sane.  It will make updates much easier to these special types.

**Comment by layershifter** [comment]
I block this issue before we have the decision in #1364.
