### ISSUE TITLE
feat(Confirm): use shorthands for content and buttons definition

### ISSUE THREAD

**Issue by lemol** [Semantic-Org/Semantic-UI-React#1290]
### Steps
1. Render the `Confirm` addon with a content that is an object: `<Confirm content={<b>hi!</b>} {...rest} />`

### Expected Result
It should be rendered without any warning.

### Actual Result
It renders correctly, but gives a warning: **content prop have to be a string**.

See src/addons/Confirm/Confirm.js#L53

**Comment by layershifter** [comment]
@lemol Thanks for report. However, I've made #1282 for it yesterday.
