### ISSUE TITLE
fix(Label): Label not appearing as it is shown in the example

### ISSUE THREAD

**Issue by sauravexodus** [Semantic-Org/Semantic-UI-React#1291]
**Steps to Reproduce**
1. Copy paste the code

**Expected**
Should appear exactly as it is show in the example.

**Result**
The icon appears bordered and white in color, with smaller variation.
<img width="115" alt="screen shot 2017-02-06 at 9 17 18 pm" src="https://cloud.githubusercontent.com/assets/7869346/22654106/bd59ad78-ecb1-11e6-9222-8d3d8bb5ba0a.png">

**Comment by layershifter** [comment]
@sauravexodus Can you make a codepen? I donэt understand how it happened.

**Comment by levithomason** [comment]
It looks like a CSS issue on your page, however, there is not enough information here to help.  We'll take a look at the codepen or other code if posted.
