### ISSUE TITLE
Dropping Component on runtime 

### ISSUE THREAD

**Issue by pbpraveen1988** [Semantic-Org/Semantic-UI-React#1295]
Hello ,

I drop the Button component in Container at Run-time , when i call its children it treats the component as string. So i cant see the button under the container but i can see the full component string.

For ex: <code><     Button label="default" /></code>

Please help me on this.
Thanks

**Comment by levithomason** [comment]
There is not enough information to help here.  However, `< Button label="default" />` should be `<Button label="default" />` (no space after the `<`).  This could be your issue.
