### ISSUE TITLE
Dropdown sizer not always hidden

### ISSUE THREAD

**Issue by tobijoh** [Semantic-Org/Semantic-UI-React#1298]
### Steps
1. Create a `Dropdown` component with the following configuration:
```jsx
<Dropdown
    options={optionList}
    placeholder={placeholder}
    search
    selection
    fluid
    multiple
    allowAdditions
    additionLabel="Add tag: "
    value={selectedValues}
    scrolling
    onAddItem={(e, item) => onAddedItem(item.value)}
    onChange={(e, item) => onChange(id, item.value)} />
```

### Expected Result
It should look like this:
![screen shot 2017-02-08 at 10 19 05](https://cloud.githubusercontent.com/assets/11481537/22730649/209d8788-ede8-11e6-9e16-3560831faf28.png)

### Actual Result
It looks like this:
![screen shot 2017-02-08 at 10 20 23](https://cloud.githubusercontent.com/assets/11481537/22730684/41ea57e0-ede8-11e6-8000-06f92af8af7f.png)

So it looks like it renders the `sizer` in the wrong place? Is anyone else experiencing this or am I misunderstanding how it is supposed to work?

A work-around that works for me is to add this to `componentDidUpdate()`: 
```javascript 
_.first(document.getElementsByClassName('sizer')).style.display = 'none';
```

It seems like row 1053 in Dropdown.js is not working: 
```javascript
this._sizer.style.removeProperty('display')
```

### Version
0.64.7
Tried it on Safari and Chrome on macOS Sierra 10.12.2

**Comment by levithomason** [comment]
This is odd. It is working in our apps and in the docs.  I've pasted the example above into the docs and removed the variables:

![image](https://cloud.githubusercontent.com/assets/5067638/22851827/7f1e6a24-efe2-11e6-9bc9-f093b3db9adb.png)

This could be something in your theme, or even a browser extension injecting styles into the page.  I'd suggest inspecting the CSS directly as done above and make a determination from there.

Note, the position of the sizer doesn't matter, just the width is used to calculate the width of the search input.  However, the style should be `display: none;` at all times as far as the user is concerned.

**Comment by jingxinxin** [comment]
I encountered the same problem,the class not working for me

**Comment by levithomason** [comment]
Could you provide more information?  We are happy to help, but, we need a broken example in order to debug.

**Comment by codeaid** [comment]
I have the same problem. Change `selection` to `selection={false}` in [this](https://react.semantic-ui.com/modules/dropdown#dropdown-example-multiple-allow-additions) example and it will render like this:
![image](https://user-images.githubusercontent.com/637799/26898685-bba709ae-4bc4-11e7-9353-d62e83a4a053.png)

Is there a way to have a search box that allows adding multiple items? I need an element which would allow users to add entries to the list, e.g. tags as per the usual example. I don't need the dropdown bit, just an empty text area that allows me to type, press enter and add and item.

**Comment by levithomason** [comment]
Thanks @codeaid.  I think we should just override the style to always make it `display: none` ourselves.  We can do so [here](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L1076), instead of removing the display attribute we just set it to `none`.

>I need an element which would allow users to add entries to the list, e.g. tags as per the usual example. ...an empty text area that allows me to type, press enter and add and item.

This sounds like a custom component to me.  I'd use an `Input` or a `TextArea` and an `onKeyDown` handler to get the value and persist it on enter.
