### ISSUE TITLE
Programatically set value for Dropdown?

### ISSUE THREAD

**Issue by littlehome-eugene** [Semantic-Org/Semantic-UI-React#1302]
### Steps
```
import React from 'react'
import { Field, reduxForm } from 'redux-form'
import { Form, Dropdown, Button } from 'semantic-ui-react'


var PurchaserForm = React.createClass({

  render () {

    var { users } = this.state
    var { user } = this.props.checkout

    var userOptions = users.map((user) => {
      return {
        key: user.id,
        value: user.id,
        text: `${user.fullname} ${user.phone}`,
      }
    })
    // https://github.com/Semantic-Org/Semantic-UI-React/pull/686
    userOptions.push({
      key: '-',
      value: '-',
      text: '',
    })

    var disabled = false
    if (user.id != '-') {
      disabled = true
    }
    return (
      <Form
        >
        <Form.Field>
          <Field
            component={Dropdown}
            name="name"
            type="text"
            fluid
            search
            selection
            options={userOptions}
            onSearchChange={this.handleNameSearchChange}
            onChange={this.handleUserChange}
            value={user.id}
            disabled={disabled}
            />
        </Form.Field>
        <Button type="submit" >Submit</Button>

      </Form>
    )
  },
}
```

set a new user in the redux store, and PurchaserForm gets rerendered with the new 
```
  user: {
    id: '-',
    fullname: null,
    phone: null
  }
```

then `value={user.id}` becomes `value='-'`

### Expected Result

I expect to see "" empty text because
userOptions have 
```
{
      key: '-',
      value: '-',
      text: '',
}
```

### Actual Result

But it still shows the text from the previous selection

### Version

0.64.3

### Testcase

I think it's a bit hard to set it up

**Comment by levithomason** [comment]
Programmatically setting a dropdown's value works and is fully tested. There is a working example here:

https://react.semantic-ui.com/modules/dropdown#remote

Clicking random programmatically changes the value. If you believe there is a bug please create a repro demonstrating the bug so we can investigate further.

**Comment by TallOrderDev** [comment]
I've found this link a couple times going through your issues, it seems to be broken. Might want to make them more long lasting and standardized.

**Comment by levithomason** [comment]
Link fixed, thanks.

http vs https issue beyond my control at present.

**Comment by navini** [comment]
Can we set the options of the dropdown programatically?

**Comment by MikeGriffinReborn** [comment]
I have not found away, this is the #1 thing folks would do in programming and there is no example, we need an example that sets the options after it's created say from an HTTP Get call?
