### ISSUE TITLE
bug(Form): incomplete typings for Form.TextArea

### ISSUE THREAD

**Issue by ak99372** [Semantic-Org/Semantic-UI-React#1304]
version 0.64.7
using TypeScript

**This works ok**
`import { Form, TextArea } from 'semantic-ui-react'`
`<Form.Field>
                    <label>Comments</label>
                    <TextArea value='Text In Here' />
</Form.Field>`

**This doesn't compile**
`<Form.TextArea label='Comments' value='Text In Here' />`

**Error:**

> Property 'value' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<FormTextAreaProps, ComponentState>> & Re...'.

**Checking [FormTextAreaProps] in index.d.ts it does not include [value]** 

Also not sure if this is the proper format but this doesn't work either

`<Form.Field control={TextArea} value='Text In Here' />`

**Comment by layershifter** [comment]
@ak99372 Thanks for report. Indeed, typings for `Form.TextArea` looks incomplete.

**Comment by ak99372** [comment]
Did some more testing today and Form.Input seems to be missing [value] field as well on the interface InputProps, though the value can still be used (I'm assuming thanks to [key: string]: any)
