### ISSUE TITLE
Modal window fixed height

### ISSUE THREAD

**Issue by iamdanthedev** [Semantic-Org/Semantic-UI-React#1308]
Hello

Is there any simple way to open modal at fixed screen height (minus margins) ?
By default a modal window tries to center itself vertically which causes problematic UX when modal content changes

**Comment by levithomason** [comment]
The answer is yes, you _should_, but you cannot currently.  It appears the Modal does not spread the user's style prop on the Modal.  Technically, you should be able to do this to pin the modal's top position:

```jsx
<Modal style={{ marginTop: '1rem' }} />
```

The `marginTop` style is calculated for centering, however, the props are applied like so:
```jsx
<ElementType {...rest} className={classes} style={{ marginTop }} ref={c => (this._modalNode = c)}>
```

Style here should be: `style={{ marginTop, ...style }}` where the style variable is from props.  PRs welcome!

**Comment by lazy-ninja** [comment]
Hi, @levithomason can I work on it?
