### ISSUE TITLE
Add `size` prop to Comment.Group

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#1311]
It is missing in SUI core docs, but is available in the CSS.

```jsx
<Comment.Group className="small" />
```

Should be accomplished with 

```jsx
<Comment.Group size="small" />
```

**Comment by tarang9211** [comment]
@levithomason what are the possible values?

**Comment by levithomason** [comment]
https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/comment.css#L232

**Comment by tarang9211** [comment]
PR is here #1327
