### ISSUE TITLE
fix(Sidebar): your description

### ISSUE THREAD

**Issue by create5068** [Semantic-Org/Semantic-UI-React#1313]
**Steps to Reproduce**
1. Do something
2. Do something else.

**Expected**
The Sidebar should do this

**Result**
The Sidebar does not do this

**Testcase**
If the docs show the issue, use: http://react.semantic-ui.com/modules/sidebar
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by layershifter** [comment]
@create5068 Can you tell us more about your issue?

**Comment by levithomason** [comment]
Strange, this is the second issue we've had recently that is an exact copy of the template.  This is the template that is created when you click the bug button on an example.  In this case, a Sidebar example.
