### ISSUE TITLE
Progress bar issue in Meteor

### ISSUE THREAD

**Issue by da-moon** [Semantic-Org/Semantic-UI-React#1339]
Hello!
I am not sure if this is a CSS issue or there is something wrong with the Semantic-UI-React package. 
Whenever I use progress bar component in my project which is built on top of Meteor, After passing a string as a value to be shown as a label, nothing shows up.Also , it does not show progress percentage correctly.  I tried nesting a component within progress bar; the component didn't show up either. Any help is appreciated.

**Comment by layershifter** [comment]
@damoonazarpazhooh Can you please provide a codepen with example of code that uses `Progress`? Also, you can check [examples](http://react.semantic-ui.com/modules/progress) of `Progress` usage in our docs.

**Comment by da-moon** [comment]
@layershifter 
Here is the link to where I am using Progress component.
I have went over all of your examples, I don't know what is causing this issue.  

https://f-aperture-damoona.c9users.io/artist-dashboard

import React, { Component } from 'react';
import { Card, Icon, Image , Rating,Button, Progress, Message, Container, Segment} from 'semantic-ui-react'

export default class ArtistDonations extends Component {
         constructor(props){
    super(props);
    this.state = {
      error: '',
      percent: 33
    };
    }
        
        render() {
              let increment = () => this.setState({
    percent: this.state.percent >= 100 ? 0 : this.state.percent + 20,
  })

    return(   <Segment fluid>
     <Message
      attached
      header='Donate-O-Meter'
      content='Cha-Ching!'
    />
    
        <Progress percent={this.state.percent} color='red'> 
            Blah Blah Blah
        </Progress>
        <Button onClick={increment}>Increment</Button>
      </Segment>
);
        }

}

**Comment by levithomason** [comment]
Pasting the Progress provided (with inlined state) into the docs I get this:

![image](https://cloud.githubusercontent.com/assets/5067638/23146275/282aead0-f78a-11e6-991c-272d7789caf9.png)

The app you provided has issues with the CSS.  The size of progress bar causes the label to overflow, which is hidden:

![image](https://cloud.githubusercontent.com/assets/5067638/23146413/667dea7a-f78b-11e6-88bd-faee963a0f86.png)


>After passing a string as a value to be shown as a label, nothing shows up.

The `label` prop takes either `percent` or `ratio` and controls what type of progress label is shown.  If you want to show a label child, use the `<Progress />` children.

BTW, I think this is super confusing and proposed that we rework this for this exact reason here #1355 only a few minutes ago.

>Also , it does not show progress percentage correctly.

What is it showing, and what is the expected correct display?
