### ISSUE TITLE
bug(Popup): invalid usage of oneOfType in propTypes

### ISSUE THREAD

**Issue by subodhpareek18** [Semantic-Org/Semantic-UI-React#1344]
```js
// index.js
import React from 'react';
import { render } from 'react-dom';
import App from './containers/App';
import '../node_modules/semantic-ui-css/semantic.min.css';

render(
  <App />,
  document.getElementById('root')
);
```
```js
// App.js
import React, { Component } from 'react';
import { Header } from 'semantic-ui-react';

class App extends Component {
  render() {
    return (
      <div>
        <Header>lalalalal</Header>
      </div>
    );
  }
}

export default App;
```

```js
// warning in browser console
Warning: Invalid argument supplied to oneOfType, expected an instance of array.
```

As you can see it's quite a simple example, in fact I've tried with multiple `semantic-ui-react` components, `Header` `Icon`... all of them show the same warning. Which comes as soon as you import them in a file.

-----
```js
// using create react app
"devDependencies": {
    "react-scripts": "0.9.0",
    "semantic-ui-css": "^2.2.4",
    "semantic-ui-react": "^0.65.0",
  },
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
```

**Comment by subodhpareek18** [comment]
Full warning screenshot:
![image](https://cloud.githubusercontent.com/assets/12589797/23092660/2a4ca5fa-f5f6-11e6-9510-52ab3d8a510d.png)

**Comment by layershifter** [comment]
@zusamann Thanks for report, I've found single place where `oneOfType` used incorrectly. I've created #1345 that fixes it.

**Comment by kaelhem** [comment]
I've got another very simple example that produce this error.
Just created a a sample app via create-react-app, added semantic-ui, and replaced the generated App.js with:

```js
import React, { Component } from 'react';
import 'semantic-ui-css/semantic.min.css';
import { Button } from 'semantic-ui-react';

class App extends Component {
  render() {
    return (
        <Button basic color='orange'>Orange</Button>
    );
  }
}
export default App;
```

The console shows:
```bash
Warning: Invalid argument supplied to oneOfType, expected an instance of array.
[Violation] Long running JavaScript task took 301ms
```

**Comment by harmon25** [comment]
something happened in this version `v0.65.0 (2017-02-17)` to cause the bug.
Switching to the older release `0.64.8` solves it for now...

**Comment by levithomason** [comment]
PR is up and will be released soon.  Note for the future if you're considering a rollback, propType warnings (while annoying) are not errors and are therefore harmless to your app.
