### ISSUE TITLE
UTF8 support for Menu Labels

### ISSUE THREAD

**Issue by dbrrt** [Semantic-Org/Semantic-UI-React#1349]
Hello, I was just wondering if UTF8 characters will be supported in headers for Menu component,

For instance : 

`<Menu.Item name='thé' active={activeItem === 'thé'} onClick={this.handleItemClick.bind(this)} />`
`<Menu.Item name='vin' active={activeItem === 'vin'} onClick={this.handleItemClick.bind(this)} />`

You'll see a label Menu like this : 

The, Vin

**Comment by levithomason** [comment]
Duplicate #1340

**Comment by levithomason** [comment]
Specific answer: https://github.com/Semantic-Org/Semantic-UI-React/issues/1340#issuecomment-280720627

Use the `content` prop to set the item content.  The `name` prop is the programmatic name, if `content` is not provided, the `name` will be Start Cased and used as the `content`.
