### ISSUE TITLE
feat(Card): Add `link` prop to Card

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#1350]
This should be a boolean prop that adds the `link` className.  See SUI core [docs](http://semantic-ui.com/views/card#link-card) for more.

```jsx
<Card link />
// => <div className="ui link card"></div>
```

**Comment by BrainMaestro** [comment]
I'm interested in picking this up, but what does the `link` prop actually do? It's not immediately obvious. The first example has a `href` property which links the entire card to that hyperlink because the card is in an `anchor` tag. The second example with the actual link property doesn't seem to do anything. Am I missing something?

**Comment by levithomason** [comment]
The `link` prop simply adds the `link` className.  The link className makes the card behave as a link (hover effects, pointer cursor), even when using a `div` or tagName other than an `a`.

Compare these two methods of making a card a "link":
```html
<a class="ui card" href="http://www.dog.com">...
<div class="ui link card">
```

**Comment by BrainMaestro** [comment]
Okay that means the description in the docs is confusing. It says 
> A card can be formatted so that the entire contents link to another page.

Which doesn't match what it actually does which is make the card behave like a link (hover effect and pointer cursor). Does the documentation need to be updated?

Anyway, I'll make a PR to fix this issue

**Comment by levithomason** [comment]
You make a good point.  It can be formatted _to appear as_ a link :)

**Comment by ZimNovich** [comment]
In the documentation (https://react.semantic-ui.com/views/card/) it still says:
`link {bool}	A card can be formatted to link to other content.`
