### ISSUE TITLE
Add `label` docs usage example for Progress

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#1351]
The Progress component can take a `label` enum prop to control the type of label displayed within the Progres bar:

## ratio
```jsx
<Progress value='3' total='5' label='ratio' />
```

![image](https://cloud.githubusercontent.com/assets/5067638/23110541/088221b6-f6d7-11e6-974c-8f51aee5af5b.png)

## percent
```jsx
<Progress value='3' total='5' label='percent' />
```

![image](https://cloud.githubusercontent.com/assets/5067638/23110577/3d80f6f8-f6d7-11e6-845a-14b938e863ae.png)

**Comment by tarang9211** [comment]
PR is #1356
