### ISSUE TITLE
Progress bar always shows progress label when using value/total

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#1352]
The value inside the bar indicating the current progress is optional:

![image](https://cloud.githubusercontent.com/assets/5067638/23111139/6906466c-f6db-11e6-98f8-887113803af7.png)

However, when the `value` and `total` props are used the progress is always shown:

```jsx
<Progress value={2} total={3}  />
```
![image](https://cloud.githubusercontent.com/assets/5067638/23111168/9b9eb532-f6db-11e6-8910-67b8bd78cd66.png)

We should only show the progress value when the `progress` prop is present or the `label='ratio|percent'` prop is present.

**Comment by BrainMaestro** [comment]
Can I pick this up?

**Comment by layershifter** [comment]
@BrainMaestro Yes, it will be awesome 👍

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.67`.
