### ISSUE TITLE
Usage with webpack

### ISSUE THREAD

**Issue by gadyonysh** [Semantic-Org/Semantic-UI-React#1353]
Hello.

I use webpack in my project to bundle frontend modules. Some time ago I choose semantic-ui-react to implement UI elements, but I want to be able include sui elements as independent modules. So I wrote 2 webpack-loaders [(semantic-ui-less-module-loader](https://github.com/gadyonysh/semantic-ui-less-module-loader) & [semantic-ui-react-less-loader](https://github.com/gadyonysh/semantic-ui-react-less-loader)) and it allows me to import sui-react elements directly:
```
import React from 'react';

import Header from 'semantic-ui-react/src/elements/Header';
import Grid from 'semantic-ui-react/src/collections/Grid';
```
What downsides has this approach?

**Comment by levithomason** [comment]
This seems like a fine approach to me.  You might also be interested in automatic import cherry picking:

https://github.com/Semantic-Org/Semantic-UI-React/issues/1025

**Comment by levithomason** [comment]
Also note, we now have an ES / JS Next build #1210.

**Comment by gadyonysh** [comment]
@levithomason Thank you.
