### ISSUE TITLE
bug(Input): cannot backspace / delete if Input has predefined `value` prop

### ISSUE THREAD

**Issue by kenvunz** [Semantic-Org/Semantic-UI-React#1358]
### Steps
Add `value` prop to an `Input` component
```
<Input icon='search' placeholder='Search' value="foo"/>
```

### Expected Result
Should be able to remove the predefined value

### Actual Result
Cannot remove the predefined value

### Version
0.65.0

### Testcase
http://codepen.io/anon/pen/wgVKbp

**Comment by levithomason** [comment]
This is not due to SUIR but is how React itself works:

https://facebook.github.io/react/docs/forms.html

Use `defaultValue` if you'd like the value to be editable.
