### ISSUE TITLE
RFC: Support submenus in Menu `items` shorthand prop

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#1365]
# Problem

Currently, the `Menu` component allows defining `items` as a shorthand prop:

```jsx
const items = [
  'One',
  { key: 'two', content: 'Two' },  // props object usage shown here
  'Three',
]

<Menu vertical items={items} />
```
![image](https://cloud.githubusercontent.com/assets/5067638/23188391/652c147c-f843-11e6-8fbd-6042c4f75572.png)

A Menu can also have a submenu, by placing a `Menu.Menu` in a `Menu.Item`:

```jsx
<Menu vertical>
  <Menu.Item>Top Level Item 1</Menu.Item>
  <Menu.Item>
     Top Level Item 2
      <Menu.Menu>
        <Menu.Item>Submenu Item 1</Menu.Item>
        <Menu.Item>Submenu Item 2</Menu.Item>
      </Menu.Menu>
    </Menu.Item>
  <Menu.Item>Top Level Item 3</Menu.Item>
</Menu>
```
![image](https://cloud.githubusercontent.com/assets/5067638/23188293/078cedd2-f843-11e6-9c05-e12b2985bd92.png)

However, there is no way to add a submenu when using the `items` prop shorthand definition.

# Proposed Solution

It would be great to be able to define a submenu as a key on an item's shorthand object:

```jsx
const items = [
  'Top Level Item 1',
  {
    key: 'item-2',
    content: 'Top Level Item 2',
    menu: [
      'Sub Item 1',
      'Sub Item 2',
    ],
  },
  'Top Level Item 3',
]

<Menu vertical items={items} />
```

![image](https://cloud.githubusercontent.com/assets/5067638/23188293/078cedd2-f843-11e6-9c05-e12b2985bd92.png)

By default, this would enable support for `<Menu.Item menu={...} />`, as the `menu` config above would be passed to the menu item's `menu` prop.

# Handling Callbacks and Active Item State

What is unclear from here is how the `onItemClick` callback and `activeItemIndex` would be handled.

One idea is to use simply disregard the nested nature of the submenu's items when traversing indices and consider the index of an item to be its natural order in the menu.  The example above would have 5 menu items where:

- index 0 = `Top Level Item 1`
- index 1 = `Top Level Item` 
- index 2 = `Sub Item 1`
- index 3 = `Sub Item 2`
- index 4 = `Top Level Item 3`

Given the above proposed submenu shorthand config, we'd render like so:
```jsx
<Menu vertical items={items} activeItemIndex={2} />
```
![image](https://cloud.githubusercontent.com/assets/5067638/23188963/90b1d594-f845-11e6-9dd8-fbd3da149785.png)

**Comment by levithomason** [comment]
This would also scale nicely to the Dropdown's submenus.  An DropdownItem can also contain a menu:

```jsx
const options = [
  {
    text: 'Left Menu',
    menu: {
      position: 'left',
      items: [
        { key: 1, text: 'Left Item 1' },
        { key: 2, text: 'Left Item 2' },
        { key: 3, text: 'Left Item 3' },
      ],
    }
  },
  {
    text: 'Right Menu',
    menu: {
      position: 'right',
      items: [
        { key: 1, text: 'Right Item 1' },
        { key: 2, text: 'Right Item 2' },
        { key: 3, text: 'Right Item 3' },
      ],
    }
  },
]

<Dropdown options={options} />
```

**Comment by GregoryPotdevin** [comment]
Does `activeIndex` need to be an integer, or could it be a string like "1.1.2" to access submenus (or an array [1, 1, 2] ?

**Comment by levithomason** [comment]
Anything that makes sense to us I suppose.  I like the idea of preserving the hierarchical reference as you're hinting at.

There are use cases where multiple indexes make sense, like in the Accordion's [exclusive example](http://react.semantic-ui.com/modules/accordion#accordion-example-exclusive), where you can have multiple panels active at the same time.  We use an array for allowing multiple active indexes.  Because of this, I'd lean toward avoiding the use of an array for nested items and keep that for cases where we want multiple items active.

I like the string idea as some kind of "active item path" if you will.  It confuses the prop name, but perhaps we change the prop name as well, `activeItem`?:

```jsx
<Menu activeItem={1} />   // second item
<Menu activeItem='1.2' /> // second item, third child
```

In this case, we can pass an index or an "index path" of parent/child items. Thoughts?

**Comment by levithomason** [comment]
Bikeshed: this could also just use array notation for clarity and ease of access:
```jsx
<Menu activeIndex='[1][2]' />

activeItem = _.get(activeIndex, items)
```

**Comment by GregoryPotdevin** [comment]
`activeItem` kind of feels a bit too much like an `activeKey` rather than an index/path. Not sure I have a better idea, though.

Not sure about the '[1][2]', it's a bit tough to read/write and parse. 

Haven't tried, but this probably works
```jsx
<Menu activeIndex='1.2' />

activeItem = _.get(items, activeIndex.split('.'))
```

(example from lodash's doc : `_.get(object, ['a', '0', 'b', 'c']);` )

**Comment by levithomason** [comment]
Cool, since we'll be recursively parsing the shorthand object anyway to drill down through the items/menus I think your proposal makes more sense.

Would be great to get a PR going for this is you're up for it.  I can offer any assistance once it is rolling as well.

**Comment by GregoryPotdevin** [comment]
Started playing around with this. The version with activeIndex is actually very straightforward to build. Might be tough to have both activeIndex and activeItem at the same time, though.

Here's a quick hack, didn't prepare a PR yet as I just wanted to discuss the idea

```jsx
  renderItems() {
    const { items } = this.props
    const { activeIndex } = this.state
    
    let globalIndex = 0

    const renderItem = (item) => {
      if (item.menu){
        return (
          <Menu.Item key={item.key || item.name}>
            <Menu.Header>{item.content || item.name}</Menu.Header>
            <Menu.Menu>
              {_.map(item.menu, renderItem)}
            </Menu.Menu>
          </Menu.Item>
        )
      } else {
        const index = globalIndex++;
        return (
          MenuItem.create(item, {
            defaultProps: {
              active: activeIndex === index,
              index,
            },
            overrideProps: this.handleItemOverrides,
          })
        )
      }
    }
    
    return _.map(items, renderItem)
  }
```

The main idea is to test if it's a menu, and use a global index counter instead of the map function's index.

It should be pretty simple to replace activeIndex with activeItem (and pass an `activeIndex` prefix to `renderItem`, and update `handleItemOverrides` to use it). Just not sure how you want to handle backwards compatibility for this.

**Comment by levithomason** [comment]
>Might be tough to have both activeIndex and activeItem at the same time, though.

I think we just stick with activeIndex.  We can retain the current usage while adding new support and not breaking anything:

```jsx
activeIndex={1}   // current use
activeIndex='1'   // current use
activeIndex='1.2' // new feature, nested item
```

### Item Shorthand

Components have shorthand props any time there is a child tree supported.  Since a `MenuItem` can contain a `Menu.Header` and a `Menu.Menu`, we should technically allow:

```jsx
<Menu.Item header='...' menu={ ... } /> // item with a submenu
```

This would offload some of the rendering burden from the Menu to the MenuItem.  I can't quite visualize exactly how this would change your current update.  Let's start the PR and see where it goes.

**Comment by GregoryPotdevin** [comment]
Thanks for your feedback, I'll do a PR with that in mind. 
Would that mean that for "top level" menu entries, activeIndex would be a number, and would use a string when going down to subitems ? And it would allow both numbers and strings as props.

**Comment by GregoryPotdevin** [comment]
Thinking about it some more, there is a way to have both coexist: if `activeIndex` only works for the top-level items. So activeItem '1.2' would have corresponding activeIndex 1 (loss of information). In that case, activeIndex would just tell you that something in item submenu "1" is active.

**Comment by levithomason** [comment]
>Would that mean that for "top level" menu entries, activeIndex would be a number, and would use a string when going down to subitems ? And it would allow both numbers and strings as props.

Yep, although,`activeIndex` can already be a string or number since both are valid JS:
```jsx
const arr = ['one', 'two']
arr[1]   // => 'two'
arr['1'] // => 'two'
```
>...there is a way to have both coexist...

After chatting this over with @davezuko, I think we just keep `activeIndex` and also allow it to be a dot notated string of indexes that represent nested items.

This makes sense with the Accordion as well.  It uses `activeIndex` but also allows it to be an array of indexes for non-exclusive panels (multiple open at once).  There is a PR up which supports nested Accordions.  I can see reusing this dot notated string of index for nested Accordions as well.   Even for multiple panels where some are nested:

```jsx
<Accordion activeIndex={0} />           // first panel
<Accordion activeIndex='0.1' />         // first panel's second child
<Accordion activeIndex={['0.1', 2]} />  // first panel's secdon child AND third panel
```

This then is consistent with the Menu's `activeIndex`.  The `activeIndex` prop then is not strictly an index value, but more of a description of the indexes of the active child elements.

**Comment by dvdzkwsk** [comment]
For clarity on my stance, I'm operating under the following assumptions:

1) Specifying a path to an active item is less intuitive than explicitly marking the item as `active`. If you wish to manually control which item is active, explicitly labeling that item as `active` is a more ergonomic approach that colocates your data + its active state, rather than managing the two separately from each other. This is also why using indexes is often complicated, since the data you are targeting is meaningful independently from its position.

2) Because of #1, it's unlikely that `activeIndex` will be used very frequently, because managing a path like `1.2.3` does not provide much meaning to the developer. A big assumption, but one that I find intuitive. This means that the decision made for this API is likely going to account for only a very narrow use case. I see the use of `Menu` as follows, ranked in order of likelihood:

    1) Shorthand props, Menu is auto controlled. No need to manage `activeIndex` since it's the default behavior.
    2) Shorthand props, initial Menu state needs to be rehydrated but the default behavior after that is adequate. This is solved by using a `defaultActiveIndex` and not managing `activeIndex` yourself.
    3) Need to manually control active items. Likely to use shorthand objects with `active` properties as needed. No need for `activeIndex` since it's redundant.
    4) Need to manually control active items, but don't want to convert shorthand strings into objects. This is the only time that `activeIndex` is needed.

**Comment by GregoryPotdevin** [comment]
That's true. A component with a similar behavior would be Tabs (though you generally don't have sub-tabs, those are in a different component and managed independently). Most Tab components don't use activeIndex (or equivalent) but rely on an `activeKey`, and each tab must be given an `itemKey` (or whatever) for it to work. This also works better when dynamically adding/removing tabs. 

Though I think for the current issue the question is more related to having a default that "just works", especially for menus/submenus that are dynamically generated (such as search results, which could be in a dropdown) and could be navigated with the keyboard.

**Comment by JonSilver** [comment]
So this was a highly popular suggestion, well discussed, but was eventually auto-closed as stale... was it ever implemented in any form?
