### ISSUE TITLE
Dropdown search doesn't work if Dropdown items are defined using JSX

### ISSUE THREAD

**Issue by raptoria** [Semantic-Org/Semantic-UI-React#1378]
the search works this way:

`   <Dropdown options={arr} search selection />`

the search doesn't work if I do this (inside another JSX component):

```
   <Dropdown placeholder='Select Baskets..' selection search className={styles.root}>
          <Dropdown.Menu>
            { this.props.values.map((option) => 
              <Dropdown.Item key={option.value} {...option} >
                <Icon name='attention' className='right floated' />
                 {option.text}
              </Dropdown.Item>
              )}
          </Dropdown.Menu>
        </Dropdown>
```

Dropdown.Item has key, value and text (as props)

**Comment by levithomason** [comment]
This is a known limitation and is under development.  You can see more context in #1380 which also updates several doc examples and adds clarifying messages regarding known limitations.

If anyone would like to go further and help out adding support for those limitations, we need to extend the props API to allow defining more complex menu configurations.  See #1365 for a great start.
