### ISSUE TITLE
No clear way to make the "Search" component fill the width of its container

### ISSUE THREAD

**Issue by tashburn** [Semantic-Org/Semantic-UI-React#1381]
### The problem
The "input" property suggests it could somehow be set to make the <Search/> component fill its container. But it's unclear what that setting would be (<Search input='????' />), and I don't see it doing anything in the code either.

### What I want
The existing "fluid" property (<Search fluid />) makes the _search results_ fill the container, not the input field itself. That's an inconsistent meaning for the property "fluid", which is used in other components to make the component itself fill the width of its container. I propose that <Search fluid /> make the component fill its container's width, and <Search fluidResults /> make the search results fill it's container width. That's more consistent and clearer to use.

### Possible solution
It seems that a Search component property (like repurposing "fluid") just needs to be passed as the Input property "fluid" in the renderSearchInput function.

### Version
2.2.2

**Comment by levithomason** [comment]
Duplicate https://github.com/Semantic-Org/Semantic-UI-React/issues/1104

```jsx
<Search input={{ fluid: true }} />
```

**Comment by levithomason** [comment]
Sidenote, looks like you need to use some backticks `` ` `` around your code when commenting.  Otherwise, GitHub tries to render it as HTML.

`<strong>Like this</strong>` instead of <strong>like this</strong>.

***
<img src="https://cloud.githubusercontent.com/assets/5067638/23292367/2b19ab28-fa14-11e6-957f-0fdd5efdf324.png" width=300 />

**Comment by tashburn** [comment]
Thanks for the suggestion on the backticks. I'm glad there's an existing solution for this. I'd suggest updating the documentation for the Search component's `input` property to make this clearer -- something like: "Pass properties to the input component (e.g. `input={{ fluid: true }}`)"

**Comment by levithomason** [comment]
Yep, PRs welcome! There are a lot of great ideas lying around here waiting for willing and able hands :)
