### ISSUE TITLE
Field.Input, Field.Select Get Rendered w/ Different Heights 

### ISSUE THREAD

**Issue by rizedr** [Semantic-Org/Semantic-UI-React#1382]
### Steps
1. Get your app running w/ CDN styles link.
2. Put in a view a `Field.Input` and a `Field.Select` side by side in a `Form.Group` or a Grid.

### Expected Result
The fields to have the same height.

### Actual Result
There is a 1px difference between them.

### Version
0.66.0

### Testcase
A good place where you can view the issue is [in the docs](https://react.semantic-ui.com/collections/form#form-sub-components).

Looking at the library of css classes, this issue does not replicate [there](https://semantic-ui.com/collections/form.html).

**Comment by rizedr** [comment]
The line-height property seems to be different from the react library, `1.2142em`, and the css library, `1.21428571em`.

**Comment by levithomason** [comment]
Please post CSS issues at https://github.com/Semantic-Org/Semantic-UI.  This repo only concerns React components.

**Comment by rizedr** [comment]
@levithomason as I stated in the first post, the issue does **not** replicate in the css library. ;)

**Comment by levithomason** [comment]
Our CSS was simply out of date, it has been resolved by updating the SUI CSS on the doc site.
