### ISSUE TITLE
Docs site is down

### ISSUE THREAD

**Issue by ben174** [Semantic-Org/Semantic-UI-React#1383]
http://react.semantic-ui.com/  not resolving for me.

**Comment by levithomason** [comment]
Hm, this is the second issue posted about docs not loading recently, #1373.  They continue to work from my location.

@ryan4888 any update on the cdnjs issue you were having?

@ben174 when you say not resolving, any more info you could provide here?

**Comment by ryndshn** [comment]
@levithomason The day I posted the issue, it was down for the entire day. Came into work the next day and it seemed to work fine. Not sure what the issue actually was.

**Comment by levithomason** [comment]
Odd, thanks for the update anyhow.

**Comment by levithomason** [comment]
Given this is isolated and random, I'm going to close this issue as well for now.  There is nothing I can do without a repro.  If it becomes a larger issue, we'll take another look.  Thanks for the reports guys.

**Comment by levithomason** [comment]
Track #1404
