### ISSUE TITLE
fix(Segment): loading with clearing does not show the icon

### ISSUE THREAD

**Issue by rkosafo** [Semantic-Org/Semantic-UI-React#1384]
**Steps to Reproduce**
1. Using the segment sample with loading
2. Add clearing

**Expected**
The Segment should show the loading icon

**Result**
The Segment does not show the loading icon

**Testcase**
If the docs show the issue, use: http://react.semantic-ui.com/elements/segment
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

````
import React from 'react'
import { Image, Segment } from 'semantic-ui-react'

const SegmentExampleLoading = () => (
  <Segment loading clearing>
    <Image src='http://semantic-ui.com/images/wireframe/paragraph.png' />
  </Segment>
)

export default SegmentExampleLoading
````

**Comment by levithomason** [comment]
This seems sane to me, however, this is a CSS issue and this repo only deals with React components.  The CSS for SUI is here: https://github.com/Semantic-Org/Semantic-UI.

A workaround is to manually place a loader within the Segment:

http://react.semantic-ui.com/elements/loader

```jsx
import React from 'react'
import { Dimmer, Image, Loader, Segment } from 'semantic-ui-react'

const SegmentExampleLoading = () => (
  <Segment clearing>
    <Dimmer active inverted>
      <Loader inverted />
    </Dimmer>

    <Image src='http://semantic-ui.com/images/wireframe/paragraph.png' />
  </Segment>
)

export default SegmentExampleLoading
```

![image](https://cloud.githubusercontent.com/assets/5067638/23342145/dfb4ae24-fc09-11e6-8245-7325f9ea7a97.png)
