### ISSUE TITLE
fix(Segment): using loading and clearing together makes clearing lose its effect

### ISSUE THREAD

**Issue by rkosafo** [Semantic-Org/Semantic-UI-React#1385]
**Steps to Reproduce**
1. Using the loading sample, replace image with right floated button
2. Add clearing to the segment

**Expected**
The Segment should be large enough to contain the button.

**Result**
The Segment shrinks in size as if clearing has not been applied.

**Testcase**
If the docs show the issue, use: http://react.semantic-ui.com/elements/segment
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

````
import React from 'react'
import { Image, Segment, Button } from 'semantic-ui-react'

const SegmentExampleLoading = () => (
  <Segment clearing loading>
    <Button floated="right">Test</Button>
  </Segment>
)

export default SegmentExampleLoading
````

**Comment by levithomason** [comment]
As with #1384, this also seems sane to me, however, this is also a CSS issue and therefore should be posted on https://github.com/Semantic-Org/Semantic-UI.
