### ISSUE TITLE
index.d.ts file with semanticUIReact

### ISSUE THREAD

**Issue by oldrich-s** [Semantic-Org/Semantic-UI-React#1392]
How can I have typed `semanticUIReact` in a TypeScript file? I have tried:

    /// <reference path="../node_modules/semantic-ui-react/index.d.ts" />
    const { Menu } = semanticUIReact

But I get `cannot find name semanticUIReact` error.

**Comment by layershifter** [comment]
@czb Use `import`:

```ts
import { Menu } from 'semantic-ui-react'
```

With reference you will get only to import type information which doesn't makes sense there.

**Comment by oldrich-s** [comment]
@layershifter I do not want to use ES6 modules... Is it not possible to include `export as namespace semanticUIReact;` into the `.d.ts` file to allow consuming it via `semanticUIReact`?

**Comment by layershifter** [comment]
@czb Yes, it makes sense, I'll make a PR.
