### ISSUE TITLE
Loader isn't run in Modal

### ISSUE THREAD

**Issue by netfull95** [Semantic-Org/Semantic-UI-React#1393]
I can't get Loader in to Modal . How can i do with my issues ?

**Comment by layershifter** [comment]
This is a CSS issue and this repo only deals with React components. The CSS for SUI is here: https://github.com/Semantic-Org/Semantic-UI.

A workaround is to place a Loader inside Dimmer, [codepen](http://codepen.io/layershifter/pen/vxOazz).

**Comment by netfull95** [comment]
Oh! I got it . thank you so much !
