### ISSUE TITLE
fix github topic

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#1394]
![image](https://cloud.githubusercontent.com/assets/14183168/23379039/0571991c-fd3e-11e6-9827-0fa1ff73f0db.png)

@levithomason Please update topic from `js-libary` to `js-library` 😄

**Comment by dvdzkwsk** [comment]
Fixed, good catch :).

**Comment by levithomason** [comment]
Haha, oh my goodness.
