### ISSUE TITLE
Modal missing property declaration (TypeScript) for closeOnDimmerClick, closeOnDocumentClick

### ISSUE THREAD

**Issue by raptoria** [Semantic-Org/Semantic-UI-React#1398]
ERROR in ./src/components/Modal/AssignBasketModal/AssignBasketModal.tsx
(34,42): error TS2339: Property 'closeOnDocumentClick' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ModalProps, ComponentState>> & { childre...'.

Needs to be added to Types:
closeOnDimmerClick
closeOnDocumentClick

**Comment by levithomason** [comment]
This will be done in #1169.  Those are Portal props, which the Modal composes.

**Comment by layershifter** [comment]
However, [these props](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.66.0/src/modules/Modal/index.d.ts#L26) are in latest version.

**Comment by layershifter** [comment]
@raptoria Can you post a fragment of code that causes error? Possible, it's same problem like in #1400.

**Comment by raptoria** [comment]
as of 0.66.0 there are no errors!
