### ISSUE TITLE
 position='right center' is not working?

### ISSUE THREAD

**Issue by sairamrishi** [Semantic-Org/Semantic-UI-React#1403]
**Steps to Reproduce
> I'm trying to make the position of popup right centre, but it's always coming default . Please
anybody can help. Even if i using the attribute position = "right center".

**Comment by layershifter** [comment]
Please make a codepen. [Examples](http://react.semantic-ui.com/modules/popup#position) in docs works as expected.

**Comment by levithomason** [comment]
```jsx
<Popup
  trigger={<Icon name='heart' color='red' size='large' circular />}
  content='I am positioned to the right center'
  position='right center'
/>
```
![image](https://cloud.githubusercontent.com/assets/5067638/23495396/51d766b6-fecd-11e6-8d51-314d4b122faf.png)

**Comment by sairamrishi** [comment]
Thank u levithomason for responding me back. Actually it's working in Codepen. But in my project on the default top-left position is coming even if i use the position = 'right center'. But the styles are there for 
'right center'

**Comment by levithomason** [comment]
I am not sure if you are still having an issue.  If you are, I will try to take a look if you post your code here or, even better, in a codepen.

**Comment by dominikdosoudil** [comment]
Hello, I don't know if it doesn't work for same reason but I've got this problem as well. It apparently happens when I put more than one JSX element into `content` prop.
```
<Popup
  trigger={<Button size="massive" onClick={this.onDeferClick}>Deffer</Button>}
  content={
    <Flexbox justify="center" alignContent="center">
      <div className="ui input labeled">
        <div className="ui label label"><FormattedMessage id={localization.Date} defaultMessage="Date" /></div>
        <Datetime onChange={this.onDateChange} value={moment(date)} />
      </div>
      <Button color="green">Ok</Button>
    </Flexbox>
  }
  on="click"
  position="bottom center"
/>
```
Positioned `top left`, should be `bottom center` __DOESN'T WORK__
_the reason isn't using flexbox, tested even without it_

```
<Popup
  trigger={<Button size="massive" onClick={this.onDeferClick}>Deffer</Button>}
  content={
    <Datetime onChange={this.onDateChange} value={moment(date)} />
  }
  on="click"
  position="bottom center"
/>
```
__WORKS__

**Comment by JuanOtavaloMaigua** [comment]
In v2 you can use this format:`<Popup popperModifiers={{ preventOverflow: { padding: 0 } }} />` or this if you want to move at top or right: `popperModifiers={{ preventOverflow: { padding: {top: -100, right: -90}} }}`. You can find more modifications here: https://popper.js.org/docs/v2/utils/detect-overflow/#padding
