### ISSUE TITLE
feat(Sidebar): Full page sidebar

### ISSUE THREAD

**Issue by UnbrandedTech** [Semantic-Org/Semantic-UI-React#1408]
Posting an issue for feed back.

Given the idea behind [this feature](https://github.com/Semantic-Org/Semantic-UI-React/pull/905#pullrequestreview-9709670), I can only see on small issue.

This is my use case.
```
<Sidebar.Pushable>
  <Sidebar as={Menu} visible vertical inverted >
    <Menu.Item name='home'>
      <Icon name='home' />
      Home
    </Menu.Item>
    <Menu.Item name='gamepad'>
      <Icon name='gamepad' />
      Games
    </Menu.Item>
    <Menu.Item name='camera'>
      <Icon name='camera' />
      Channels
    </Menu.Item>
  </Sidebar>
  <Sidebar.Pusher >
    //maybe another menu here for the top nav
    <Segment basic>
      {React.Children.toArray(this.props.children)}
    </Segment>
  </Sidebar.Pusher>
</Sidebar.Pushable>
```

In @levithomason's comment he said add a page prop to the `Sidebar` component. Which would be fine but what would happen if someone did this?

```
<Sidebar.Pushable>
  <Sidebar as={Menu} visible vertical inverted page>
    ...
  </Sidebar>
  <Sidebar.Pusher >
   ...
  </Sidebar.Pusher>
</Sidebar.Pushable>
```

Do we add a pushable to both the pushable div and the body? Should we throw a warning?

**Comment by levithomason** [comment]
>In @levithomason's comment he said add a page prop to the Sidebar component. Which would be fine but what would happen if someone did this?
>
> [ ...shows page sidebar in pushable component ]
>
>Do we add a pushable to both the pushable div and the body? Should we throw a warning?

I think there is only so much we can do to prevent misuse.

However, upon reflection t is probably a good idea to keep the full page sidebar API usage as close to the other usage as possible as well.  Proposals welcome.

**Comment by codeaid** [comment]
Any update on this? Would really like to use this library in my project but hard to get started without a decent "holy grail" full-page layout example.

**Comment by rafalradomski** [comment]
@levithomason Same issue, how to force sidebar to cover the whole page?

**Comment by levithomason** [comment]
Would love a PR on this, there has not been a business need to date on my end to fund the time to complete it.

Regarding above comments, you can find layout examples here:
https://react.semantic-ui.com/layouts

You can also reference the [docs Sidebar](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/Components/Sidebar/Sidebar.js) which is just a left fixed menu.  We just put it in a very simple [flex layout](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/Components/DocsLayout.js#L55).

This, however, does not implement animations as the `<Sidebar />` component does.  For that, we need a PR.

**Comment by patrikmolsson** [comment]
Hey,

I managed to do a work-around forcing the sidebar to be full-page, using ```min-height: 100vh;```

This is my implementation:

```javascript
  render() {
    const { children } = this.props;

    return (
      <Sidebar.Pushable styleName="sidebar-container">
        <Sidebar as={Menu} vertical inverted visible={this.state.sidebar_open} animation={'push'}>
          <Menu.Item name="Departments">
            Departments
            <Icon name={'home'} />
          </Menu.Item>
        </Sidebar>
        <Sidebar.Pusher as={Container}>
          <SidebarToggle callback={this.toggleSidebar} />
          {children}
        </Sidebar.Pusher>
      </Sidebar.Pushable>
    );
```

This is placed in a div with ```min-height: 100vh;```, also the styleName ```sidebar-container``` adds ```min-height: 100vh;``` to the Sidebar.Pushable.

It could probably be implemented alternatively in a more general manner.

**Comment by webciter** [comment]
i had this problem, try on mouse leave hide the sidebar. This will clean things up, You could probably use a scroll inside the sidebar itself, like youtube style.
