### ISSUE TITLE
Input with side label will not color label red, if input is given error prop

### ISSUE THREAD

**Issue by nbkhope** [Semantic-Org/Semantic-UI-React#1409]
### Steps
1. Make an Input component with an error property set to true, as described in the docs.
2. Add a label, say, to the right-hand side of the input

### Expected Result
The whole input colored light red due to validation error.

### Actual Result
Only the input part is colored red, not the right-hand side label.

### Version
0.67.0

### Testcase
See the screenshot

![screen shot 2017-03-01 at 4 48 41 pm](https://cloud.githubusercontent.com/assets/13649002/23488107/636ee62a-fe9f-11e6-8dcb-b36c0db4d7e2.png)

The only think I can think of is to add a color property of 'red' to the label, although it won't exactly match the light red color of the input. So was it intentional to leave only the input colored?

![screen shot 2017-03-01 at 4 55 29 pm](https://cloud.githubusercontent.com/assets/13649002/23488193/ec3c5898-fe9f-11e6-8859-e9e7925163eb.png)

**Comment by levithomason** [comment]
This is a CSS issue and should be posted on https://github.com/Semantic-Org/Semantic-UI.  This repo only concerns itself with React components.
