### ISSUE TITLE
Cannot load the react semantic-ui.com site: http://react.semantic-ui.com/

### ISSUE THREAD

**Issue by jaylord-github** [Semantic-Org/Semantic-UI-React#1412]
Hi guys, I cannot load the page, are you having issues accessing the page also: http://react.semantic-ui.com/

Error's below:
GET http://cdnjs.cloudflare.com/ajax/libs/anchor-js/3.2.1/anchor.min.js net::ERR_CONTENT_DECODING_FAILED
react.semantic-ui.com/:1
GET http://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.css net::ERR_CONTENT_DECODING_FAILED
react.semantic-ui.com/:28
GET http://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.23.1/babel.min.js net::ERR_CONTENT_DECODING_FAILED
react.semantic-ui.com/:28
GET http://cdnjs.cloudflare.com/ajax/libs/Faker/3.1.0/faker.min.js net::ERR_CONTENT_DECODING_FAILED
react.semantic-ui.com/:28
GET http://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.6.11/beautify-html.min.js net::ERR_CONTENT_DECODING_FAILED
react.semantic-ui.com/:28
GET http://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react.min.js net::ERR_CONTENT_DECODING_FAILED
react.semantic-ui.com/:28
GET http://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.min.js net::ERR_CONTENT_DECODING_FAILED
react.semantic-ui.com/:28
GET http://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom-server.min.js net::ERR_CONTENT_DECODING_FAILED
vendor.1632bf1….js:1
Uncaught SyntaxError: Unexpected identifier
app.d09631b….js:1
Uncaught SyntaxError: Unexpected identifier

**Comment by levithomason** [comment]
Duplicate #1404 #1383.  Let's consolidate on #1404.
