### ISSUE TITLE
Missing responsive navbar?

### ISSUE THREAD

**Issue by ghoshnirmalya** [Semantic-Org/Semantic-UI-React#1415]
I'm unable to find any particular way through which I can make a responsive navbar. Is that component available here?

**Comment by levithomason** [comment]
Menus can collapse to take up only as much space as needed, stack on mobile devices, stretch to take up the full width of their container, and evenly divide their items.

https://react.semantic-ui.com/collections/menu#compact
https://react.semantic-ui.com/collections/menu#stackable
https://react.semantic-ui.com/collections/menu#fluid
https://react.semantic-ui.com/collections/menu#evenly-divided

Additionally, you can put a Menu in a Grid for even more responsive control:

https://react.semantic-ui.com/collections/grid

***

**EDIT** `http` -> `https` links, thanks @clodal

**Comment by clodal** [comment]
Links provided above are broken. The following are the updated versions:

https://react.semantic-ui.com/collections/menu#menu-example-compact
https://react.semantic-ui.com/collections/menu#menu-example-stackable
https://react.semantic-ui.com/collections/menu#menu-example-fluid
https://react.semantic-ui.com/collections/menu#menu-example-evenly-divided

**Comment by layershifter** [comment]
Little outdated, but I've made a [codepen](https://codesandbox.io/s/325y47xk36) that shows how to make it.

**Comment by levithomason** [comment]
Haha, boy, it seems my response got mix feelings.  I have no idea why, but it sure does make me curious.

![image](https://user-images.githubusercontent.com/5067638/30776014-5471a3b4-a053-11e7-9b84-ca05f36c70b8.png)

**Comment by jjwilliams42** [comment]
Somewhat unrelated, but, why is the semantic ui react documentation not responsive at all? When I visit on my phone, i have to pinch and zoom everywhere, unlike the CSS doc site.

I'm a long time fan of semantic ui, wrote a yeoman extension for it even for .NET Core project generation (the CSS version). But I've had problems getting the React version to be responsive, or maybe it's because of my lack of understanding of the proper pieces that must be used to make it responsive.

**Comment by brianespinosa** [comment]
@jackjwilliams All components that are responsive in SUI are responsive in SUIR. `Item`, `Form`, and `Grid` can all be defined with responsive props which render them with the proper SUI markup for collapsing, doubling, etc.

Regarding the docs... no. They are not responsive. That would probably be a good addition to the project which we could make a separate issue for if one does not already exist.

**Comment by veswill3** [comment]
@jackjwilliams and @brianespinosa - I noticed that the docs were not responsive a while ago and created an issue for this #2230. Still waiting for the fix to push.

Thanks for the example @layershifter, any chance that could be added as an example to the docs, maybe in the [layouts](https://react.semantic-ui.com/layouts) area?

**Comment by brianespinosa** [comment]
@veswill3 @jackjwilliams looks like https://github.com/Semantic-Org/Semantic-UI-React/pull/2231 was merged 3 days ago so I assume that means when the next release of SUIR goes out we will get the necessary viewport tags added to the docs.

**Comment by levithomason** [comment]
This sounds like a feature request, please open a new issue.
