### ISSUE TITLE
Form.Select required prop is not passed to <select> tag

### ISSUE THREAD

**Issue by mull** [Semantic-Org/Semantic-UI-React#1423]
### Steps
```<Form.Select options={[{value: 'something', text: 'something'}]} required />```

### Expected Result
<select> HTML tag should have the `required` property

### Actual Result
The <div> that contains the <select> has 

### Version
0.67

### Testcase
I don't have one, sorry

### Screenshot
![semantic-ui-select-required](https://cloud.githubusercontent.com/assets/646665/23651827/0c8a033a-0327-11e7-80e3-c910eea41ef7.png)

### Solution
The required property should be passed on to the <select> tag rather than its parent <div>

**Comment by layershifter** [comment]
Hi, @mull 

I agree with this idea, but `select` can't be `required` because it's hidden field, so we will have another error:
```
An invalid form control with name='' is not focusable.
```

In fact we doesn't have there input that can be really focused. My proposal is skip `required` prop if we deal with `Dropdown` in `Form.Select`.

@levithomason Do you have better ideas?

**Comment by mull** [comment]
Rather than being hidden could it not be hidden through CSS (I know that is not the responsibility of this project)? I get the problem for sure though in the use case of writing forms it essentially makes Form.Dropdown useless (without writing a bunch of additional validation code.) Looking forward to hearing what can be done, happy to try and assist!

**Comment by levithomason** [comment]
In the end, this won't work as intended, so we cannot implement it.  Here is more info and context:

Regarding passing down extra props through shorthand, to clarify, the purpose of shorthand (i.e. `Form.Select`) is to power the majority of use cases.  If shorthand fails to suit the purpose, you should use the full markup which gives you full control over every component and all props.  This addresses the need to pass certain props down to the control element:

```jsx
<Form.Field>
  <label>Select one</label>
  <Select />
<Form.Field>
```

Regarding the `required` prop, the `Select` (which is a [`Dropdown`](http://react.semantic-ui.com/modules/dropdown)) does not support a `required` prop.  The `required` prop in this use case would only be valid on the `Form.Field` for displaying the red asterisk.  See SUI core example [here](https://semantic-ui.com/collections/form#required).

Regarding form validation behavior associated with the `required` attribute, I don't think it is idiomatic React to delegate validation to the form controls themselves.  Form state should be hoisted up the tree and validated independent of the Form and its controls.

We do have form validation on the radar including a list of many helpful packages that work with SUIR here, #407.

**Comment by karimjavith** [comment]
The Select does support required field
`https://www.w3schools.com/TAGS/tryit.asp?filename=tryhtml5_select_required`
