### ISSUE TITLE
New Basic Usage Example: `semantic-ui-react-todos`

### ISSUE THREAD

**Issue by wyc** [Semantic-Org/Semantic-UI-React#1426]
Hey,

There are some great examples in the documentation on how to configure the individual components, but I haven't seen many basic usage examples, a la https://github.com/Semantic-Org/Semantic-UI-React/issues/836.

I created a new example that modifies the well-known [react-redux Todo List example](https://github.com/reactjs/redux/tree/master/examples/todos) to use Semantic UI components. There is also a short write-up on the process. If this could be useful to newcomers, then I'd be happy to include it in the documentation or have a link point to it. Otherwise, feel free to just close this issue.

https://github.com/wyc/semantic-ui-react-todos

Thanks!

**Comment by levithomason** [comment]
This is awesome!  I'd love to start an `Examples & Tutorials` section in the `README.md`.  Would you like to submit a PR that adds this?  It can do directly between "documentation" and "built with":

```
Documentation
...

Examples & Tutorials
...

Built With Semantic-UI-React
...
```

**Comment by levithomason** [comment]
Also, you may be happy to know about the layout examples coming along in #1039.

**Comment by levithomason** [comment]
Thanks!
