### ISSUE TITLE
The http://react.semantic-ui.com website is down

### ISSUE THREAD

**Issue by tashburn** [Semantic-Org/Semantic-UI-React#1429]

**Comment by ryndshn** [comment]
Could be related to #1404. There have been isolated issues with the site over the last couple weeks.

**Comment by brianespinosa** [comment]
The issues outlined in #1404 seem to be different. The console error I am getting when trying to reach the site is: ```GET http://react.semantic-ui.com/ net::ERR_NAME_NOT_RESOLVED```

**Comment by estaub** [comment]
Confirming @brianespinosa 's finding: I get a 105 error (ERR_NAME_NOT_RESOLVED) as well.  @ryan4888 , do you not see the same?

**Comment by ryndshn** [comment]
I said it "could" be related. I hadn't investigated much at the time. Looks like I also get 
`GET http://react.semantic-ui.com/ net::ERR_NAME_NOT_RESOLVED`

**Comment by mpasternacki** [comment]
The `react.semantic-ui.com` DNS entry does not resolve for me (trying cloudflare's DNS listed as for the domain, google's public resolvers, and my ISP's DNS servers – all return no results).

**Comment by levithomason** [comment]
Not sure what is up with the DNS, I've added a temporary github.io url for now.  Images will be borked, but the most of the docs are usable:

https://semantic-org.github.io/Semantic-UI-React

We'll figure this out as soon as we're able.  Thanks everyone!

**EDIT**
Updated to https.

**Comment by levithomason** [comment]
I've also updated the README.me and links on the repo home page with this information.

**Comment by mpasternacki** [comment]
For the record, the correct URL for temporary docs is https://semantic-org.github.io/Semantic-UI-React/

**Comment by jlukic** [comment]
This is fixed now. It's my fault. I ported DNS over to cloudflare to try to setup SSL/HTTS a couple days ago. 

Cloudflare "imported" my DNS rules from existing records but somehow this one was lost. The CNAME is now setup again and everything should be working.

**Comment by levithomason** [comment]
OK, folks, docs are back up!  I've removed the temporary docs warning from the README.md.

I've also updated all doc site images to use our local images, fixing #1441.  I've also updated all HTTP links to semantic-ui.com to use HTTPS so that they work with the new changes.

If there are any more issues please let us know.

Thanks much @jlukic.
