### ISSUE TITLE
[Form Validation] Regular Expression Validator not working

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#143]
Trying to validate a [US Phone Number](http://html5pattern.com/Phones) but am unable to achieve even simple validation right now using the regular expression validator.

Here's my validation rule:

``` js
phone: {
  identifier: 'phone',
  rules: [
    {
      type: 'regExp[/^\d{10}$/]',
      prompt: 'Must be a valid US phone number'
    }
  ]
}
```

Here's the result I get when the validator is run:

<img width="735" alt="screen shot 2016-01-08 at 1 53 41 pm" src="https://cloud.githubusercontent.com/assets/440298/12207990/9a786ad0-b60f-11e5-80f7-dcb0a1488968.png">

And here's [validation it should work](http://rubular.com/r/6RZvAI9fFw).

**Comment by levithomason** [comment]
I suspected it was the escaping as that string is not a real regex string.  True, you'll need to escape the backslash again `\\d`:

``` js
phone: {
  identifier: 'phone',
  rules: [
    {
      type: 'regExp[/^\\d{10}$/]',
      prompt: 'Must be a valid US phone number'
    }
  ]
},
```

![image](https://cloud.githubusercontent.com/assets/5067638/12210487/36f2ff48-b60f-11e5-993b-4846c14dab8a.png)

![image](https://cloud.githubusercontent.com/assets/5067638/12210490/3d62b0c6-b60f-11e5-94b9-00ba45598130.png)
