### ISSUE TITLE
Receive "Unknown prop 'position' on <div> tag." when trying to use in Popup component.

### ISSUE THREAD

**Issue by ryndshn** [Semantic-Org/Semantic-UI-React#1436]
Issue: When trying to use the 'position' prop on the Popup component I receive the following error. 
![image](https://cloud.githubusercontent.com/assets/10523324/23798233/a7dc1dae-0571-11e7-9527-c7e179d5585f.png)

Here is my usage... 

![image](https://cloud.githubusercontent.com/assets/10523324/23798248/bd9feb3e-0571-11e7-9d22-f743cf107337.png)

### Expected Result
Popup should appear in the bottom right.

### Actual Result
It appears on top. 

### Version
0.64.7

**Comment by layershifter** [comment]
`position` property was renamed from `positioning` only in `0.67.0`, #1259. So, you need update to latest version.
