### ISSUE TITLE
Cannot pass `name` props to Search component

### ISSUE THREAD

**Issue by ivosabev** [Semantic-Org/Semantic-UI-React#1437]
Passing prop `name` to `Search` should set it as an attribute to the `<input>`, not the `<div>`.

### Code
```
<Search name="foo" />
```

### Expected Result
```
<div class="ui fluid search">
  <div class="ui icon input">
    <input name="foo" type="text" placeholder="Name" value="" class="prompt" tabindex="0" autocomplete="off">
...
```

### Actual Result
```
<div name="foo" class="ui fluid search">
  <div class="ui icon input">
    <input type="text" placeholder="Name" value="" class="prompt" tabindex="0" autocomplete="off">
...
```

### Version
0.63.5

**Comment by layershifter** [comment]
@ivosabev Thanks for report 👍 I've made PR for this.

**Comment by lexarion1** [comment]
Hello. What about Dropdown? The same as with search, will be great to pass name attribute

**Comment by ZimNovich** [comment]
@layershifter Yes, what about Dropdown? How to pass the `name` attribute to the nested `<input>`?
