### ISSUE TITLE
Segment.Group child Segments do not display basic formatting

### ISSUE THREAD

**Issue by enjoyjeremy-bc** [Semantic-Org/Semantic-UI-React#1439]
**Steps to Reproduce**
Create a Segment.Group with child Segment basic property set to true.

**Expected**
Child segments should display with basic formatting, as when a segment is not part of a Segment.Group

**Result**
"basic" does not have any effect on formatting.

**Testcase**
http://codepen.io/enjoyjeremy/pen/jBmbEg

**Comment by levithomason** [comment]
This is a CSS issue so it should be posted on https://github.com/Semantic-Org/Semantic-UI.

However, I believe you are looking for a `padded` Grid in this case:

http://codepen.io/levithomason/pen/GWmxOw

![image](https://cloud.githubusercontent.com/assets/5067638/23829025/37a9e1b4-0699-11e7-8497-ed42e108755d.png)
