### ISSUE TITLE
Examples with images in React Docs are broken due to protocol change

### ISSUE THREAD

**Issue by tyusupov** [Semantic-Org/Semantic-UI-React#1441]
Likely due to DNS changes several days ago, all examples in docs with image references that use http urls are broken.

For example, here's the code from Reveal Fade example from http://react.semantic-ui.com/elements/reveal 

```
const RevealExampleFade = () => (
  <Reveal animated='fade'>
    <Reveal.Content visible>
      <Image src='http://semantic-ui.com/images/wireframe/square-image.png' size='small' />
    </Reveal.Content>
    <Reveal.Content hidden>
      <Image src='http://semantic-ui.com/images/avatar/large/ade.jpg' size='small' />
    </Reveal.Content>
  </Reveal>
)
```

Changing reference to https fixes the issue.

**Comment by levithomason** [comment]
Thanks!  We actually have all images here locally at `/assets/images`.  I've updated all the doc examples and they are live now.

**Comment by tyusupov** [comment]
Thanks a lot for a quick fix!

**Comment by tyusupov** [comment]
Just noticed that some of the images are still not showing up, it seems to be that avatars in this directory are 404:

/assets/images/avatar2

Example can be found here: http://react.semantic-ui.com/collections/table
