### ISSUE TITLE
Consider publishing individual components as packages

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#1443]
A tool like https://github.com/lerna/lerna could enable us to publish individual components as standalone packages.

**Comment by themre** [comment]
that would be very nice. would it be possible also to split CSS into component packages?

**Comment by layershifter** [comment]
CSS is splitted by SUI team, [Table](https://github.com/Semantic-Org/UI-Table) for example. At now this repo doesn't deal with CSS at all.

**Comment by themre** [comment]
ok. but should we try to split CSS into separate components? 'cause now CSS bundle is more than 500 kB.

**Comment by layershifter** [comment]
If you use vanilla SUI it's already done, take a look on link that I've provided:
```js
import 'semantic-ui-table/table.css';
```

If you use styled [SUI](https://github.com/Semantic-Org/Semantic-UI) you can [define](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/semantic.less) components that you want use:

```js
import './semantic/semantic.less';
// Or
import './semantic/definitions/globals/reset.less';
import './semantic/definitions/globals/site.less';
```

I don't understand your problem there. Here is a [small how-to](https://www.artembutusov.com/webpack-semantic-ui/).

**Comment by themre** [comment]
ok thanks.

**Comment by levithomason** [comment]
I've marked this for the v1 release.

**Comment by levithomason** [comment]
We should consider shipping the commonjs, es, and umd build targets as separate packages as well.  It would make the imports much cleaner for devs.

```js
import { Button } from 'semantic-ui-react-es'
```

Versus our current practice of exposing our dist directory structure, which is leaky and brittle:

```js
import { Button } from 'semantic-ui-react/dist/es'
```

**Comment by layershifter** [comment]
Sometime ago @levithomason has already proposed this. I'm think it's a good idea for V2, some utils like `eventStack` can be moved in separate packages.
