### ISSUE TITLE
Accordion defaultActiveIndex when exclusive={false}

### ISSUE THREAD

**Issue by egorshulga** [Semantic-Org/Semantic-UI-React#1449]
### Steps
http://codepen.io/egorshulga/pen/bqREBV

### Expected Result
'what kinds of dogs are there?' active

### Actual Result
none active

### Version
0.67.0

**Comment by dylankiss** [comment]
You should use an array of active indexes when setting exclusive to false.
`<Accordion defaultActiveIndex={[1]} exclusive={false}>`

**Comment by layershifter** [comment]
@dylankiss Thanks for correct answer :+1:

**Comment by dylankiss** [comment]
@layershifter Maybe this should be added to the `exclusive` example in the Accordion docs? Currently you can only find out by looking at the code.

**Comment by layershifter** [comment]
@dylankiss I'm performing `Accordion` refactor #1375, there is updated example that shows work with [indexes](https://github.com/Semantic-Org/Semantic-UI-React/blob/95433c0eb45cc3a60151cb49adf11ceeca626157/docs/app/Examples/modules/Accordion/Usage/AccordionExampleExclusive.js).
