### ISSUE TITLE
<Menu.Item fitted="vertically"> doesn't work

### ISSUE THREAD

**Issue by tashburn** [Semantic-Org/Semantic-UI-React#1453]
<Menu.Item fitted="horizontally"> works.
<Menu.Item fitted="vertically"> does not work (to eliminate the top and bottom padding).

**Comment by levithomason** [comment]
Could you post a codepen demonstrating the issue?  This works in the docs:

http://react.semantic-ui.com/collections/menu#menu-example-fitted

![image](https://cloud.githubusercontent.com/assets/5067638/23886385/ba377566-0837-11e7-89ef-ee9a6c608299.png)

**Comment by tashburn** [comment]
I expect no vertical padding to do this (see picture). That's not what it does for me, or in the docs. 
What's it supposed to do?

<img width="179" alt="ex" src="https://cloud.githubusercontent.com/assets/1438053/23911659/170d347c-08a3-11e7-9b3c-f0e99dfbc9dc.png">

**Comment by levithomason** [comment]
The green shading in the image above is the padding.  Note the vertical padding is removed.

This more clear in a `vertical` menu:

![image](https://cloud.githubusercontent.com/assets/5067638/23917313/14c7a32e-08ac-11e7-8d4f-e8e42f16e3c4.png)

A `.ui.menu` has a `min-height: 2.85714286em;` so the height does not collapse by default.

**Comment by tashburn** [comment]
I see. Thanks.

**Comment by levithomason** [comment]
❤️ I've added #1468 which adds a vertical menu for clarity:

![image](https://cloud.githubusercontent.com/assets/5067638/23968421/dc045be8-097f-11e7-8831-3b4b3d77d6b6.png)

**Comment by tashburn** [comment]
Nice!
