### ISSUE TITLE
TypeScript definition errors in v0.67.1

### ISSUE THREAD

**Issue by mihai-dinculescu** [Semantic-Org/Semantic-UI-React#1456]
Greetings,

The latest version introduces several TypeScript errors.

**a) Internal errors:**
```
node_modules\semantic-ui-react\dist\commonjs\collections\Table\TableFooter.d.ts
(2,10): error TS2305: Module '"node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableHeader"'
has no exported member 'TableHeaderProps'.

node_modules\semantic-ui-react\dist\commonjs\collections\Table\TableHeaderCell.d.ts
(2,10): error TS2305: Module '"node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableCell"'
has no exported member 'TableCellProps'.
```

**b) Props interfaces that are no longer exported:**
```
Module '"node_modules/semantic-ui-react/index"' has no exported member 'LabelProps'.
Module '"node_modules/semantic-ui-react/index"' has no exported member 'InputProps'.
Module '"node_modules/semantic-ui-react/index"' has no exported member 'IconProps'.
Module '"node_modules/semantic-ui-react/index"' has no exported member 'IconGroupProps'.
Module '"node_modules/semantic-ui-react/index"' has no exported member 'ButtonProps'.
etc.
```

**Comment by DanHarman** [comment]
I just stumbled on this myself. Glad you found it too, as new to typescript and semantic-ui-react and was wondering if my webpack setup was borked.

Do you happen to know the latest working version? edit 0.67.0 appears to be fine.

**Comment by DanHarman** [comment]
Looking at the history, probably related to  #1395? @layershifter might be your change? I get the error just just trying to import `{ Menu }`. Didn't hit the interfaces issue yet.

**Comment by layershifter** [comment]
PR for "a" is comming. However, I'm not sure that we need to export props interfaces. Can you clarify your needs of them?

**Comment by rokoroku** [comment]
If we have exported props, we can prepare an object for expected props easily by using types.

Rather than, I'd suggest using `namespace` so that we can use `Icon` interface and `Icon.Props` inside `Icon` namespace

**Comment by mihai-dinculescu** [comment]
@layershifter those props come in handy many times. The most used scenarios that I can think of right now are defining event handlers and, like rokoroku said, prepping the props so you can cleanly assign them to the element using the spread operator.

**Comment by layershifter** [comment]
I heard you guys. I will make PR for this.

**Comment by mpsk** [comment]
@layershifter, just add an `export` before interface definition.
Example:
`export interface TableHeaderProps{...}`
in `src/collections/Table/TableHeader.d.ts`

**Comment by layershifter** [comment]
@mpsk There is already PR for this
