### ISSUE TITLE
Plans for versioning the documentation

### ISSUE THREAD

**Issue by cguedes** [Semantic-Org/Semantic-UI-React#1457]
Do you have plans to have the documentation versioned?

----
_🎉 👍 for a fantastic product._

**Comment by levithomason** [comment]
Yes sir.  Once we hit v1.0.0 there will be a few changes related to stability and maintenance.  One of them will be versioned docs.

I'll leave this issue open as a reminder, thanks!

**Comment by levithomason** [comment]
Thanks to @rijk, we have improved how we handle stale issues, see #2761.   Reopening.
