### ISSUE TITLE
Suggestion : change Button.Or text for i18n

### ISSUE THREAD

**Issue by Tilican** [Semantic-Org/Semantic-UI-React#1461]
Hi,

Can you add a props in Button.Or to change text ?
And set basic text to "or" ?

Have fun

**Comment by levithomason** [comment]
Thanks for the suggestion.  The content of the Or button is set via CSS:

![image](https://cloud.githubusercontent.com/assets/5067638/23923659/bbb4cd7a-08c4-11e7-8826-e8c8129e8a42.png)

So this change would need to happen in the CSS which is at https://github.com/Semantic-Org/Semantic-UI. The React project only includes React components.

That said, you can also simply add an override CSS rule that changes the `content` property as well.

**Comment by layershifter** [comment]
@levithomason You're not right there, [it can be done](https://semantic-ui.com/elements/button.html#conditionals) with `data-text`:

```html
<div class="ui buttons">
  <button class="ui button">un</button>
  <div class="or" data-text="ou"></div>
  <button class="ui positive button">deux</button>
</div>
```

I think we need this functionality via `text` prop.

**Comment by levithomason** [comment]
Thanks for the catch @layershifter!
