### ISSUE TITLE
Material theme icons produce propTypes warnings

### ISSUE THREAD

**Issue by MindFreeze** [Semantic-Org/Semantic-UI-React#1472]
### Steps
1. Use `material` theme for icons
2. Add an icon with `name="apps"` (or `notifications` or others)

### Expected Result
This should just render the material icon.

### Actual Result
Icons are rendered but console warnings are produced:
```
Failed prop type: Invalid prop `name` of value `apps` supplied to `Icon`.
```

### Version
0.67.0

Maybe material icon names should be added ICON_ALIASES in https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/SUI.js . Or maybe just disable validation of the name as you can't possibly cover all themes including any custom icons ppl may add. Possibly add another prop that would disable this validation?

**Comment by layershifter** [comment]
> Maybe material icon names should be added

Nope. We use only defined icon names from SUI.

> Possibly add another prop that would disable this validation?

Use `className` prop to add your custom classes:

```jsx
<Icon className="apps" />
```

**Comment by levithomason** [comment]
You can find more info on customizing icons here https://github.com/Semantic-Org/Semantic-UI-React/issues/931#issuecomment-263643210.
