### ISSUE TITLE
Close controlled Popup on click outside

### ISSUE THREAD

**Issue by ryndshn** [Semantic-Org/Semantic-UI-React#1474]
I want to close a controlled Popup when the user clicks outside of it's area. This was working before I changed my Popup to be controlled. But now that it's controlled, I need some kind of event to trigger this to change state. Is this baked into the Popup component or do I need to add this?

**Comment by levithomason** [comment]
Just as a controlled React input will still call its `onChange` handler even though the `value` is controlled, a Popup will still call its `onOpen` and `onClose` handlers even though the `open` prop is controlled.  You should hook into these callbacks and toggle the `open` prop manually.

http://react.semantic-ui.com/modules/popup#popup-example-controlled
