### ISSUE TITLE
Add focus method to Input component

### ISSUE THREAD

**Issue by jonmajorc** [Semantic-Org/Semantic-UI-React#1475]
When Input component is used with [DatePicker](https://hacker0x01.github.io/react-datepicker/) it is expected to return a DOM node which has a focus method. @levithomason  had mention The ref is a reference to the Input class instance and we need to add a focus method to the Input component. This is also considered best practice.

```
Uncaught TypeError: this.refs.input.focus is not a function
    at Object.focus (bundle.js:86206)
    at Object.setFocus (bundle.js:86206)
    at bundle.js:86206
    at bundle.js:86212
```

**Comment by levithomason** [comment]
Fixed in #1477
