### ISSUE TITLE
Form state should not have effect on the visibility of inner message

### ISSUE THREAD

**Issue by zhaoyao91** [Semantic-Org/Semantic-UI-React#1476]
### Version
0.67.1

By now, messages within a form will only be shown if their state equals with that of the form. I think this layer of logic is useless because in React, we can easily sync the state and visibility of all of them.

With such a constrain, some fine grained controls become odd. For example, If I wanna show some error message and some warning message, as the form can have only one state, I have to set these messages' visible to true to enforce it.

Also, for components like Message, visible prop seems like an anti-pattern. Component should take care of the styles of itself, but problems like **should it be rendered** and **where to place it** should be handled by the user or consumer component.

**Comment by levithomason** [comment]
Messages within a Form are shown/hidden via CSS.  Please post CSS issues on the main repo https://github.com/Semantic-Org/Semantic-UI.  This project only concerns itself with React components.
