### ISSUE TITLE
TextArea autoHeight initialState with SSR

### ISSUE THREAD

**Issue by lokhmakov** [Semantic-Org/Semantic-UI-React#1478]
With server side render (SSR) TextArea does not set init styles and showed full sized before scripts started.

[http://imgur.com/a/IgjYt](url)

I use some hack:

```js
<TextArea
  style={ description === `` ? {  minHeight: 0, resize: `none`, height: `41px` } : {} }
  autoHeight
/>
```

But think we can do it inside `TextArea`.

**Comment by levithomason** [comment]
Thanks @lokhmakov.

We have to wait for one render in order to measure the textarea and size it.  We should likely apply the minimum height style on the first render to prevent this issue.  We may need to remove the style when making the measurement to ensure the content can size the textarea.

**Comment by lokhmakov** [comment]
If we cannot determine initial height then we can set initial rows, like this:

```js
  rows={ value === `` ? 1 : null }
```

**Comment by levithomason** [comment]
Closing for housekeeping as there isn't much activity over here.  We're open to a PR on this issue.
