### ISSUE TITLE
Clear selection from a dropdown

### ISSUE THREAD

**Issue by KevinGorjan** [Semantic-Org/Semantic-UI-React#1484]
Any chance we get an option to clear the selected value in a dropdown?

Like react-select is doing?

![image](https://cloud.githubusercontent.com/assets/789614/24104639/03a72bba-0d83-11e7-9896-63fa65d6b19e.png)

**Comment by levithomason** [comment]
This seems like a cool option.  It would need to first be added to SUI core so there is CSS for it.  Then, we can implement it in the React components.

Please post this issue over at: https://github.com/Semantic-Org/Semantic-UI

### Workaround
You could add your own override CSS that adds this extra icon and a wrapper component that handled its click and cleared the Dropdown.

**Comment by wild-lotus** [comment]
@levithomason Could you provide some sample code for this workaround?

**Comment by levithomason** [comment]
https://codesandbox.io/s/q35695z1kw

![http://g.recordit.co/95riZzd41n.gif](http://g.recordit.co/95riZzd41n.gif)
