### ISSUE TITLE
Dropdown: Search + Mouse Selection

### ISSUE THREAD

**Issue by maniax89** [Semantic-Org/Semantic-UI-React#1485]
### Description

When the dropdown component is used with `search={true}` and the mouse is used to select an option after performing a filtering action, the selected index corresponds to the filtered list, not the overall list.

This is exhibited in the documentation demo page https://react.semantic-ui.com/modules/dropdown#dropdown-example-search-selection

### Steps
1. Open the dropdown
1. Filter the dropdown by typing enough to reduce the number of items in the dropdown
1. Select an item in the dropdown using the mouse, not the keyboard
1. Re-open the dropdown.

### Expected Result

The dropdown placeholder text (and the selected item) should be set to the originally mouse-selected item.

### Actual Result

The dropdown placeholder text (and the selected item) is set to a completely different option. My guess is that the index from the filtered list was used to select the item from the unfiltered list on dropdown open.

### Version

0.67.1

### Testcase

Fork this to show the issue: http://codepen.io/anon/pen/ZerKvp

**Comment by levithomason** [comment]
Superb reporting, thanks much.  I had run into this issue myself and was unable to reproduce the state.

**Comment by levithomason** [comment]
I should note you are correct in your diagnosis of index issue.  You can look in `Dropdown.js` for `handleItemClick` if you care to peruse the logic.

**Comment by VincentVerne** [comment]
I take it, it has not been fixed.

**Comment by levithomason** [comment]
See #2375

**Comment by layershifter** [comment]
I verified this it's no longer present in the latest releases.

### `0.68.4`

![dropdown-0684](https://user-images.githubusercontent.com/14183168/90119705-2e314f00-dd5a-11ea-9798-b41b60c695b9.gif)

### `1.2.0`

![dropdown-120](https://user-images.githubusercontent.com/14183168/90119709-2ec9e580-dd5a-11ea-8d9a-bd1f0b3a2362.gif)

---

CodeSandbox: https://codesandbox.io/s/lingering-sunset-yc54h?file=/index.js
