### ISSUE TITLE
Dropdown: change active item on keyboard up/down

### ISSUE THREAD

**Issue by Neketch** [Semantic-Org/Semantic-UI-React#1487]
Hello, do you plan on changing dropdown selection with keyboard keys ?
Just as mentionned in Semantic UI 2.2 news :

**Faster Dropdown Selection**
_Dropdowns now change selections on keyboards without hitting "enter", this lets users quickly navigate between dropdown elements in a form without having to hit "enter" before "tab" after each field entry, saving an additional keystroke._

Thank you !

**Comment by levithomason** [comment]
Hm, I have a feeling the date on this is old or they are repeating old features.  This is the default behavior of our current dropdown and was the original design.

A dropdown opens on focus and selects the item on blur.  When you TAB over to a Dropdown, it opens and the first item is highlighted, use arrow up/down to navigate items, pressing TAB again blurs the dropdown, closing it and selecting the item.

You can configure all of this behavior with the props provided, namely, `openOnFocus`, `selectOnBlur`, and `closeOnBlur`.

http://react.semantic-ui.com/modules/dropdown

**Comment by Neketch** [comment]
Hello, thank you for your answer.
Actually both dropdowns have a different behavior on keyboard navigation, I will write a better report.

### Description
When navigating with <kbd>up</kbd> and <kbd>down</kbd> keys, the dropdown selection does not change until <kbd>enter</kbd> is hit or the dropdown goes blur.

### Steps

1. Open the dropdown
2. Navigate with <kbd>up</kbd> and <kbd>down</kbd> keys

### Expected Result
The dropdown selection should immediately change (the selected item should go active) on keyboard navigation.

### Actual Result
The dropdown selection does not change on keyboard navigation, it needs to hit <kbd>enter</kbd> or the dropdown has to go blur.

### Version
0.67.2

### Testcase
http://codepen.io/Neketch/pen/KWxOVK
Two dropdowns are implemented : the first one is the original one from Semantic-UI and the second one is from Semantic-UI-React.
As you can see, the `onChange` handler is fired on <kbd>up</kbd> and <kbd>down</kbd> keystrokes for the original one :
![](https://media.giphy.com/media/l4FGlQLF76xpycUpO/giphy.gif)

**Comment by levithomason** [comment]
Beautiful report, very helpful!  Yep, we need to change the value on <kbd>up</kbd> and <kbd>down</kbd>.

**Comment by Bebersohl** [comment]
I got this one.
