### ISSUE TITLE
Watch tasks

### ISSUE THREAD

**Issue by pedrocostadev** [Semantic-Org/Semantic-UI-React#1503]
Hi guys,

I am interested in start contributing for Semantic UI-React so I read the CONTRIBUTING.md file.
Despite that, i still have a doubt. How dev team usually do to see new changes in components?. I know you have the tasks to build but i didn't find any "watch" task. Each guy have own demo or use something like react story book?

Thanks

**Comment by levithomason** [comment]
Awesome news, we'd be glad to have you!  The doc site functions as the storybook in this case.  After running `npm start`, open `localhost:8080` which includes hot module reloading for all components and all examples.
