### ISSUE TITLE
Multiple Modals Scrolling issue

### ISSUE THREAD

**Issue by wangyueming** [Semantic-Org/Semantic-UI-React#1504]
### Steps
1. From a main window, open a modal which is higher than main window, a scrollbar appears to let me scroll my modal window, it is good. (I notice the body classes are  "dimmable dimmed scrolling")
2. From the modal window, open a new modal window which is a small window, the prior scrollbar disappears.  (I notice the body classes are "dimmable dimmed")
3. Close the second small modal window, return the first high modal window. (I notice the body class is empty)

### Expected Result
The scrollbar should appear again.

### Actual Result
There is no scrollbar.

### Version
0.67.0

**Comment by levithomason** [comment]
Duplicate #1157
