### ISSUE TITLE
RFC: ability to make Table columns resizable

### ISSUE THREAD

**Issue by notgiorgi** [Semantic-Org/Semantic-UI-React#1513]
It would be convenient to have a ability to make table columns resizable.

**Comment by levithomason** [comment]
This would indeed be great.  I'm not sure how far we can go without updating SUI core to offer some CSS support for this as well.

I'll leave this open for further ideas on the best way to achieve this.

**Comment by notgiorgi** [comment]
Also props like `isSorted` / `isSortedDesc` would be great. If you provide one of them true, column will have  an arrow

**Comment by levithomason** [comment]
@notgiorgi note there are props available that are yet to be documented which manage the CSS for sorting: https://github.com/Semantic-Org/Semantic-UI-React/issues/1195

The topic of table sorting/pagination/etc can be followed in this issue: https://github.com/Semantic-Org/Semantic-UI-React/issues/1133.

**Comment by ghost** [comment]
I think, needs to be done both in the [Fixed Data Table](https://facebook.github.io/fixed-data-table/example-resize.html)

**Comment by levithomason** [comment]
Closing for housekeeping, we're still open to PRs that can achieve this.

**Comment by navini** [comment]
What's the status on this?

**Comment by layershifter** [comment]
We are not going to implement this as a part of SUIR: it will require changes in CSS which can't be handled on our side.
