### ISSUE TITLE
DropDown ignores new options on componentWillReceiveProps when passed as JSON list

### ISSUE THREAD

**Issue by dfsp-spirit** [Semantic-Org/Semantic-UI-React#1514]
### Steps
Use DropDown as a live search component with server-side searching/filtering, where the options passed to the DropDown are updated whenever the user changes the search query in the input box (like in the _Remote_ example given on http://react.semantic-ui.com/modules/dropdown, but update the options in the _handleSearchChange_ method). This means that the DropDown will receive new options on componentWillReceiveProps(). 

Pass the options as a list of plain objects, e.g., options = [{ value: 1224, text: "item 1" }, { value: 12344, text: "item 2" }].

The error will **not** show up if you use sub components, i.e., use DropDown.Menu and pass options as children of type DropDown.Item (but doing so will make you lose auto state management).

### Expected Result
The options should be updated and show up in the list immediately.

### Actual Result
The options do not or only party show up (e.g., you pass it a list of 50 items to render, and it only shows items no. 2, 13, 14, and 35). You can make all of the options show up by performing certain actions in the browser (like pressing CTRL+SHIFT+i in Chrome to open the developer console). 

### Workaround
Use DropDown with the DropDown.Menu sub component and pass children of type DropDown.Item to it. You will have to give them an onClick function to get the selected value (and store in state of your wrapper component, most likely). Then pass this value as 'text' prop to the DropDown in the render method (will be done it next render loop).

### Version
0.64.4

### Testcase
Currently working on a minimal example, will update issue with a link when ready...

**Comment by levithomason** [comment]
>Currently working on a minimal example, will update issue with a link when ready...

❤️

**Comment by layershifter** [comment]
@dfsp-spirit Any updates?

**Comment by dfsp-spirit** [comment]
It worked in the minimal example I made, so it seems it is related to other stuff we do, but I'm not sure to what exactly. We are still using the workaround I mentioned above. Since nobody else has complained about this issue here so far, I guess this can be closed for now. I will let you know if I dig deeper and find something.

**Comment by levithomason** [comment]
Thanks for the update.  Let us know if you are able to reproduce the issue in an isolated environment and we'll help out with a fix.
