### ISSUE TITLE
"Open link in new tab" doesn't work with Menu.item?

### ISSUE THREAD

**Issue by RoniFinTech** [Semantic-Org/Semantic-UI-React#1519]
Hi,

I'm using semantic-ui-react and I built a very simple nav-bar. 
One thing I noticed was that I couldn't copy the menu items... I then noticed that if I right-click, I don't have the option "open link in the new tab"... Am I doing something wrong or this is how it's built?

**Comment by levithomason** [comment]
Sounds like they are not anchor elements:

```jsx
<Menu.Item as='a' href='https://google.com'>
  Google
</Menu.Item>
```
![image](https://cloud.githubusercontent.com/assets/5067638/24391735/a815df76-1345-11e7-9722-29c252423b29.png)

**Comment by RoniFinTech** [comment]
Thank you for the help.
Is it possible to have it this way (with href) but without rendering the whole application?

This is what I have now:
<Menu.Item
                name='Profile'
                as='a'
                href='/profile'
                active={location.pathname==='/profile'}
                onClick={()=> history.push('/profile')}
/>
