### ISSUE TITLE
How to control text inside Form.Input (like grabbing and clearing after submit)?

### ISSUE THREAD

**Issue by zarnihpyoe** [Semantic-Org/Semantic-UI-React#1520]
I don't see any props and example of controlling text inside Form.Input in the [documentation](http://react.semantic-ui.com/collections/form) . It'd be great if there's an example in documentation.

**Comment by levithomason** [comment]
Because our components are inline with vanilla React behavior, you can refer to React's docs for more info on how to work with Forms:

https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by zarnihpyoe** [comment]
Thanks levi. That helps a lot.

**Comment by levithomason** [comment]
I'm adding detailed usage examples for both these cases as well.  You can see them here for now:

https://github.com/Semantic-Org/Semantic-UI-React/pull/1521/files

**Comment by filipetedim** [comment]
As per this issue here: https://github.com/Semantic-Org/Semantic-UI/issues/1870 , the default option where you can't edit values should not appear as editable, as it may confuse users.
