### ISSUE TITLE
Dropdown does not repopulate without clicking away from the component.

### ISSUE THREAD

**Issue by dackers86** [Semantic-Org/Semantic-UI-React#1523]
This is a duplicate of https://github.com/Semantic-Org/Semantic-UI-React/issues/1242. However, this was closed without an explanation as to how to solve the issue...?

**Comment by levithomason** [comment]
In order for us to help, please use the issue template.  There is not enough information here to reproduce the bug and find a solution.  I will reopen on receiving the info needed to help.

**Comment by dackers86** [comment]
### Steps
1. Type an address and populate data from google address api (temporary key provided in example).

### Expected Result
It should update the dropdown list with the responses on render. For example type "71 esc". 

### Actual Result
It is intermittently not populating. Clicking off screen will update the list.

### Version
0.67.1

### Testcase
http://codepen.io/anon/pen/NpOmVP?editors=0011

**Comment by l-astro** [comment]
Has there been any update on this? I see the same issue in version 0.68.5. Thanks for a great framework guys :)

**Comment by levithomason** [comment]
This is working correctly.  The search `71 esc` returns results which do not contain the string `71 esc`.  So the state is updated, the options are populated, but they are filtered by `71 esc` which yields no visible options in the list.  Clicking away clears the search, hence, showing the option.

Here you can now see the state and why the option is not shown.

https://codepen.io/anon/pen/XgeWEo
