### ISSUE TITLE
How to prevent property propagation?

### ISSUE THREAD

**Issue by vincaslt** [Semantic-Org/Semantic-UI-React#1524]
I am using styled-components, and I pass color via component props, however, they get propagated to div element, and I'm getting an error of `Unknown prop `blinkColor` on <div> tag`.

Component:

```
// @flow

import React from 'react'
import { Segment } from 'semantic-ui-react'
import styled, { keyframes } from 'styled-components'
import { colors } from '../../constants'

type PropTypes = {
  blinkColor: string
}

const blink = blinkColor => (keyframes`
  from {
    background-color: ${blinkColor};
  }

  to {
    background-color: ${colors.shadow};
  }
`)

const ColoredSegment = styled(Segment)`
  animation: ${props => blink(props.blinkColor)} 0.7s !important;
  background-color: ${colors.shadow} !important;
`

export default (props: PropTypes) => <ColoredSegment {...props} />
```

Usage:

```
<ColoredSegment blinkColor={colors.error}>
  Header as="h3">{word}</Header>
</ColoredSegment>
```

I  don't want to manually remove properties, is there any other approach you can suggest?

**Comment by levithomason** [comment]
You can ask usage questions in our Gitter room: https://gitter.im/Semantic-Org/Semantic-UI-React.  We reserve GitHub for bugs and features.

That said, your component should consume its own props and spread the rest.  Refer also to React's docs: https://facebook.github.io/react/warnings/unknown-prop.html.

**Comment by levithomason** [comment]
You can ask usage questions in our Gitter room: https://gitter.im/Semantic-Org/Semantic-UI-React.  We reserve GitHub for bugs and features.

That said, your component should consume its own props and spread the rest.  Refer also to React's docs: https://facebook.github.io/react/warnings/unknown-prop.html.

**Comment by glowingjade** [comment]
You can use it like this
```
// wrap semantic component and don't pass blinkColor to semantic component
const SegmentContainer = ({ blinkColor, ...props }) => (<Segment {...props} />)

const ColoredSegment = styled(SegmentContainer)`
  animation: ${props => blink(props.blinkColor)} 0.7s !important;
  background-color: ${colors.shadow} !important;
`
```
