### ISSUE TITLE
Discussion about Styled Components

### ISSUE THREAD

**Issue by rizedr** [Semantic-Org/Semantic-UI-React#1526]
Has anyone thought on how you could use this library with [styled components](https://github.com/styled-components/styled-components)?

The reasons one might want to do that are:
- more modularity & faster compile time;
- using semantic-ui css & a custom css layer on top to make your styles unique does not work because of [webpack style order import bug](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/200);
- using semantic-ui less has a huge compile time, 20s to compile all .less and around 10 second to compile a change when watching.

I'm thinking that one way you could use this library w/ styled components is to write, in your project, for each react semantic-ui components, a styled component on top, and use that in your project. Furthermore, maybe there should be a semantic-ui-css version written as styled components?

What do you think?

**Comment by levithomason** [comment]
Yep, duplicate #1009.  Would love feedback there.
