### ISSUE TITLE
Popup css bug

### ISSUE THREAD

**Issue by Tilican** [Semantic-Org/Semantic-UI-React#1528]
Hi,

I use "semantic-ui-react": "^0.67.2"
When you try to add an overflow / max-height style on pop-up, it loose the pointing arrow.

`<Popup
                trigger={<Button inverted circular icon='alarm' color="grey"/>}
                hoverable
                wide
                style={
                  {
                    overflow: 'auto',
                    maxHeight: 300
                  }
                }
              >
                test
</Popup>`

Thanks

**Comment by levithomason** [comment]
Per the issue template:
>CSS issue?
>-----------------
>Post on https://github.com/Semantic-Org/Semantic-UI.
>
>Semantic UI React only concerns itself with React components that render valid Semantic-UI markup. There is no HTML nor CSS code in this project.
