### ISSUE TITLE
Semantic-UI-React custom styling help

### ISSUE THREAD

**Issue by ranjit-battewad** [Semantic-Org/Semantic-UI-React#1529]
Using Semantic-UI-React in my latest application. I want apply custom styling to components like card ( background color )how can we do that ?

Tried below items: 

1) Added className prop to card component
2) Create .css file and importing it using css-loader as > import styles from './mystyles.css' 
but fails to load file and apply styling.

Thanks in advance.

**Comment by levithomason** [comment]
https://github.com/Semantic-Org/Semantic-UI-React#faq

**Comment by patientplatypus** [comment]
This is unhelpful. Could you not provide a simple example? I am having the same issue.

**Comment by levithomason** [comment]
Please understand, the core team is made of 2 unpaid individuals with families.  We just don't have the time to debug and post solutions for every issue/user.  We do our best to help and provide good docs for others to follow.

Have you already read all the documentation I linked to in the FAQ?  It covers everything you need to know.  The rest is up to you.

### FAQ

![image](https://user-images.githubusercontent.com/5067638/30785191-7b3e46f4-a117-11e7-82aa-edca85bba68c.png)

If there is a bug or missing information in the docs, please let us know.

**Comment by trkaplan** [comment]
If you are using Create React App, see this tutorial: [How to use Semantic UI with a custom theme in your CRA app](https://jsramblings.com/2018/03/04/how-to-use-semantic-ui-with-a-custom-theme-in-your-CRA-app.html)
