### ISSUE TITLE
Website won't stack 

### ISSUE THREAD

**Issue by mblodorn** [Semantic-Org/Semantic-UI-React#1538]
✔ BUGS → This form is required:

### Steps

When I access my website from google chrome device toolbar it stack and work as expected in mobile size, but when I actually access it from mobile the website appear like the desktop version.

### Expected Result

Stack everything in mobile

### Actual Result

When I access my website from google chrome device toolbar it stack and work as expected in mobile size, but when I actually access it from mobile the website appear like the desktop version.

### Version
Latest

### Testcase
http://www.animapp.com.br
https://github.com/animapp-dev/animapp

**Comment by levithomason** [comment]
https://webdesign.tutsplus.com/articles/quick-tip-dont-forget-the-viewport-meta-tag--webdesign-5972
