### ISSUE TITLE
Gradually display sub menus

### ISSUE THREAD

**Issue by anhldbk** [Semantic-Org/Semantic-UI-React#1539]
Hi guys,
The current version of `Menu` will instantly display its content. How to add animation effects to make it gradually appear?

**Comment by levithomason** [comment]
I'm not entirely sure what you mean.  Are you trying to stagger the items?  Although, you may have better luck on Gitter as this is a usage question.  Github is used for bugs and new features so usage questions may not get as much attention here.

**Comment by anhldbk** [comment]
![screenshot from 2017-04-03 08-24-18](https://cloud.githubusercontent.com/assets/3270746/24592838/01313708-1847-11e7-952c-439154801803.png)

I'm sorry if my question is a little bit vague. For example, when I click on menu item `More`, React-based Semantic UI will **instantly** display its sub items. But the original version of Semantic UI will **gradually** (via a smooth animation effect) make them appear.

My question is how to implement such effect using this React-based version.

**Comment by levithomason** [comment]
I see.  This library currently does not include animations.  We're working on the `<Transition />` component in #1435.  Once merged, this will enable the use of animations in all components.
