### ISSUE TITLE
Icons and Flags are missing on the selected option of Dropdowns!?

### ISSUE THREAD

**Issue by itshallrun** [Semantic-Org/Semantic-UI-React#1541]
Hey,

I wonder why there are no icons of the selected option in the dropdown like in the picture below:

semantic-ui:
![image](https://cloud.githubusercontent.com/assets/21173275/24596028/26856930-183c-11e7-9ded-e8bc42f23703.png)

semantic-ui-react: no icons
![image](https://cloud.githubusercontent.com/assets/21173275/24595923/3a7dcffa-183b-11e7-8bb7-e0c0ac37e658.png)

Can I somehow achieve this?

**Comment by levithomason** [comment]
Duplicate https://github.com/Semantic-Org/Semantic-UI-React/pull/1172

**Comment by levithomason** [comment]
See the original issue for more info and workarounds https://github.com/Semantic-Org/Semantic-UI-React/issues/1147
