### ISSUE TITLE
fix(Divider): Vertical Divider on docs rendered incorrectly

### ISSUE THREAD

**Issue by val-samonte** [Semantic-Org/Semantic-UI-React#1544]
**Steps to Reproduce**
1. Use <Divider vertical> in a Grid component

**Expected**
The Divider should render between Grid.Columns

**Result**
The Divider instead render on the left side

**Testcase**
http://react.semantic-ui.com/elements/divider#divider-example-vertical

**Comment by levithomason** [comment]
There is a W3C spec change issue causing this bug in the CSS:

https://github.com/Semantic-Org/Semantic-UI/issues/4342

**Comment by levithomason** [comment]
Note, you can work around this by putting dividers inside of a column rather than in between them:

![image](https://cloud.githubusercontent.com/assets/5067638/24672946/585abd1c-192b-11e7-9f49-8c397b12b6aa.png)

```jsx
import React from 'react'
import { Grid, Segment, Divider } from 'semantic-ui-react'

const DividerExampleVertical = () => (
  <Grid columns='equal' padded>
    <Grid.Column>
      Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio.
    </Grid.Column>
    <Grid.Column width='1'>
      <Divider vertical>Or</Divider>
    </Grid.Column>
    <Grid.Column>
      Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio.
    </Grid.Column>
    <Grid.Column width='1'>
      <Divider vertical>Or</Divider>
    </Grid.Column>
    <Grid.Column>
      Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio.
    </Grid.Column>
  </Grid>
)

export default DividerExampleVertical
```

**Comment by val-samonte** [comment]
thanks @levithomason, sorry i forgot to check the open issues.

**Comment by levithomason** [comment]
No worries.
