### ISSUE TITLE
Dropdown onChange : Text acces ?

### ISSUE THREAD

**Issue by GreGGus** [Semantic-Org/Semantic-UI-React#1546]
Hey ! I'm using Dropdown with my data referential. It's working but I really need to store inside my JSON the 'data refs code' and the 'data refs value'.
ex:  code : '0032'  , value : 'New York'.
      code : '0033',  value :'Los Angeles'.

My options are like  : 

data : {
   key : dataRef.code,
   text : dataRef.textLabel,
   value: dataRef.code
}

When I use onChange(e,d), I only receive the 'value' from my options data. Actually i really need text AND value  to send to my service.

Is it possible ? Thanks.

**Comment by levithomason** [comment]
The `onChange` callback is the change handler for the Dropdown so it only receives the `value` of the Dropdown.  Compare this to an Input's `onChange`.

To get the `text`, find the option with the matching value.

Dupes:

https://github.com/Semantic-Org/Semantic-UI-React/issues/1368
https://github.com/Semantic-Org/Semantic-UI-React/issues/912#issuecomment-262356714
https://github.com/Semantic-Org/Semantic-UI-React/issues/754
