### ISSUE TITLE
Multiple Selection Dropdown backspace does not delete items

### ISSUE THREAD

**Issue by fracmak** [Semantic-Org/Semantic-UI-React#1547]
### Steps
Select any item from a multiple selection dropdown (not multiple search selection dropdown), press delete to remove that entry from the list

### Expected Result
Item is removed

### Actual Result
Item does not get removed

### Version
0.67.2

### Testcase
http://react.semantic-ui.com/modules/dropdown#dropdown-example-multiple-selection

It appears to work fine when search is turned on.

**Comment by layershifter** [comment]
Closing for housekeeping, [1548#comment](https://github.com/Semantic-Org/Semantic-UI-React/pull/1548#issuecomment-292598766)
