### ISSUE TITLE
fix(Form|Label): Form.Input with pointing label has extra margin

### ISSUE THREAD

**Issue by blackhill** [Semantic-Org/Semantic-UI-React#1551]
**Steps to Reproduce**
```
<Form.Field>
     <label>A label</label>
     <Form.Input error placeholder='Placeholder'/>
      <Label basic color='red' size='small' pointing>Please enter a value</Label>
</Form.Field>
```

**Expected**
The label should stick to the Input. No 14px margin should be present
![image](https://cloud.githubusercontent.com/assets/1117282/24753362/1761f002-1ad2-11e7-96d7-77bdb4c2631f.png)

**Result**
![image](https://cloud.githubusercontent.com/assets/1117282/24753274/acb4423c-1ad1-11e7-8e0c-41be5f790cf6.png)

Pointing label is behaving correctly when using 'input' instead of 'Form.Input'

**Comment by layershifter** [comment]
You should use `Input` in this case. `Form.Input` is shortcut for `Form.Field` + `Input`, you can see this in your markup:

```html
<form class="ui form">
  <div class="error field">
    <label>A label</label>
    <div class="error field">
      <div class="ui input">
        <input type="text" placeholder="Placeholder" />
      </div>
    </div>
    <div class="ui red pointing small basic label">Please enter a value</div>
  </div>
</form>
```

Here is codepen that shows correct usage: http://codepen.io/layershifter/pen/jBomoo

**Comment by blackhill** [comment]
Thanks @layershifter 
It would be nice to add this example to the documentation. It's a common usecase

**Comment by layershifter** [comment]
Technically, it's already [there](http://react.semantic-ui.com/elements/label#label-example-pointing-colored)

**Comment by blackhill** [comment]
In the exemple **input** is used instead of **Input**.
```
<Form.Field>
<input type='text' placeholder='First name' />
<Label basic color='red' pointing>Please enter a value</Label>
</Form.Field>
```

So you cannot use the **error** property.
New R-SUI users must be careful to use the Input component and not the input html element
