### ISSUE TITLE
Warning `Accessing PropTypes via the main React package is deprecated` in React 15.5+

### ISSUE THREAD

**Issue by mattiagalati** [Semantic-Org/Semantic-UI-React#1564]
### Steps
- npm install
  - react@15.5.3
  - react-dom@15.5.3
  - babel-core@6.24.1
  - babel-preset-latest@6.24.1
  - babel-preset-react@6.24.1
- Create an extended custom React.Component that imports Semantic UI React Icon Component
- Build and open app in Chrome Browser

### Expected Result
No warnings
### Actual Result
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
printWarning	@	warning.js?8a56:36
warning	@	warning.js?8a56:60
get	@	React.js?24ef:95
(anonymous)	@	IconGroup.js?f416:40

`
process.env.NODE_ENV !== "production" ? IconGroup.propTypes = {
  /** An element type to render as (string or function). */
  as: customPropTypes.as,

  /** Primary content. */
  children: PropTypes.node,

  /** Additional classes. */
  className: PropTypes.string,

  /** Size of the icon group. */
  size: PropTypes.oneOf(_without(SUI.SIZES, 'medium'))
`

### Version
0.67.2

### Testcase
[Fork, update, and replace this pen to show the bug]:
http://codepen.io/levithomason/pen/ZpBaJX

**Comment by layershifter** [comment]
PR will come soon
