### ISSUE TITLE
react.semantic-ui.com site not rendering with Privacy Badget add-on

### ISSUE THREAD

**Issue by sgarrity** [Semantic-Org/Semantic-UI-React#1566]
### Steps
1. Loaded the http://react.semantic-ui.com/ site in the latest version of Firefox with the [Privacy Badger extension](https://www.eff.org/privacybadger) on MacOS (also tried the latest Firefox Developer Edition).

### Expected Result
Expected to see the beautiful website.

### Actual Result
Instead saw a blank white page (with no errors in the console).

### Version
0.67.2

Turns out the site works in Chrome and Firefox without Privacy Badger enabled, but doesn't work with it enabled.

**Comment by sgarrity** [comment]
Looks like this has to do with the Privacy Badger add-on, not Firefox. I'll update the issue accordingly.

I have also reported the issue to Privacy Badger (they have a 'did we break this site?' button)

**Comment by levithomason** [comment]
Thanks for the updates, closing this as our site is working and valid.
