### ISSUE TITLE
Dropdown text produce a warning when passing a node on text prop

### ISSUE THREAD

**Issue by pradel** [Semantic-Org/Semantic-UI-React#1567]
The Dropdown element produce a warning when you pass to the text prop a node element.
The prop only accept a string for now.

### Steps
```
<Menu.Item as={Dropdown} text={<FormattedMessage id="basic.language" />}>
```
### Expected Result
No warning.

### Actual Result
Produce a warning invalid text prop.

### Version
0.67.2

**Comment by layershifter** [comment]
`text` prop accepts only string, there is no bug. If you want to pass a custom content you should use `content` prop, check [this](http://react.semantic-ui.com/modules/dropdown#dropdown-example-item-content) example.

![_831](https://cloud.githubusercontent.com/assets/14183168/24951744/22f93ea6-1f7e-11e7-8615-1717422c0248.png)

-----

I superficially think that we can use our factories there for `text` prop, possible that @levithomason can clarify that when he'll become available.

**Comment by levithomason** [comment]
For now, please use `content` as directed by @layershifter.

Note that there is also a hidden `<select>` within the Dropdown.  The `text` and `value` strings/numbers are used for the `<options>`.  We cannot allow components to be passed as `text` as you'll trade our validation error for React's validation error:

```
Warning: Only strings and numbers are supported as <option> children.
```

We may remove the hidden select at some point (it is legacy) and this would allow more flexibility for passing `text`.  However, the text is used as the text within the Dropdown input itself so custom components may likely break the styles as well.

Will close and mark as won't fix, for now.  Though, someday we may address this.

**Comment by pradel** [comment]
Okay thank you 😄
