### ISSUE TITLE
Support autocorrect on input

### ISSUE THREAD

**Issue by Jameskmonger** [Semantic-Org/Semantic-UI-React#1572]
`autoCorrect` is not supported on the `Input` component (whereas `autoComplete` and `autoCapitalize` are).

Adding it to the component adds it to the `div` wrapper rather than the actual `input` element.

**Comment by layershifter** [comment]
PR is ready, #1573

**Comment by Jameskmonger** [comment]
Thanks @layershifter. As a related question, why are the properties in `htmlInputProps.js` not included in the typings for Input in `Input.d.ts`?

**Comment by layershifter** [comment]
We don't expose the common HTML props in components without really need ([1072#comment](https://github.com/Semantic-Org/Semantic-UI-React/issues/1072#issuecomment-268848820)).
