### ISSUE TITLE
No typings for input properties

### ISSUE THREAD

**Issue by Jameskmonger** [Semantic-Org/Semantic-UI-React#1575]
A number of properties on the `Input` component do not have any typings around them and thus no type safety when developing in TypeScript.

**Comment by layershifter** [comment]
[1572#comment](https://github.com/Semantic-Org/Semantic-UI-React/issues/1572#issuecomment-293529877)

**Comment by Jameskmonger** [comment]
@layershifter I think there would be a large benefit in having them listed explicitly in the typings.

Not doing so causes two issues:

- When using the `Input` component, when I begin typing `autoComplete` or `autoCorrect` I suddenly lose all Intellisense. Are they supported? **I don't know** (without investigating). Running the code reveals that `autoComplete` works and `autoCorrect` doesn't (#1572) - but there's no hints about why.
- I can pass anything I want into the properties at compile time. I can give "blablabla" as the value for `autoComplete` and get no compiler support at all. Compiler support is the entire point of TypeScript!

The only argument I can see on that thread about not having them listed in the typings is that "users should only see custom properties". I don't agree with this at all. Any property supported by the component should be listed in the types. The typings should be all encompassing so that the user can have type information about any manifestation of the component.

I also don't think that any user ever looks through the typings to see what they can use - that's what the documentation is for. The typings are just there to affirm that what they are trying to use exists and is correct.

**Comment by layershifter** [comment]
@Jameskmonger your position has the right to life. However, personally I want left all as is. Possible @levithomason has another opinion at this question

**Comment by levithomason** [comment]
These are valid points, thanks for the supporting arguments as well.  The current implementation follows the community consensus thus far. If we get more requests for adding native DOM node props we will do so.

**Comment by Jameskmonger** [comment]
Thanks for the responses @levithomason and @layershifter - I believe that with TypeScript I can actually merge the interfaces so locally I can have my own type information for the native DOM properties, so it isn't an issue for me. Just something to consider about the wider community.
