### ISSUE TITLE
no inverted prop for dropdown menu

### ISSUE THREAD

**Issue by raptoria** [Semantic-Org/Semantic-UI-React#1577]
I'd like to have a dark dropdown menu!

**Comment by layershifter** [comment]
@raptoria You need create a NFR on [CSS repo](https://github.com/Semantic-Org/Semantic-UI), vanilla dropdown [doesn't have](https://github.com/Semantic-Org/UI-Dropdown/blob/master/dropdown.css) inverted variation.
