### ISSUE TITLE
Ref is not passed with `getUnhandledProps`

### ISSUE THREAD

**Issue by Industrial** [Semantic-Org/Semantic-UI-React#1582]
Hi.

In my case it's a 'ref' prop passed to Form.TextArea;

example: https://gist.github.com/Industrial/7d4b76ad129e4983e4baf55002165ebc#file-a-js-L22

This div's ref is logged. The one above of the TextArea is not. This is a real problem for me, as I want to select all text in the textarea when the component is mounted.

**Comment by layershifter** [comment]
@Industrial It will be nice if you will follow our `ISSUE_TEMPLATE`, however thanks for report.

I've made a [codepen](http://codepen.io/layershifter/pen/eWmEKN) that shows problem, it's looks like bug in #1581:

@levithomason wrote:
> Refs are not passed through props. React makes them undefined. We'll have to accept the ref on a different prop name, or, update factories to include refs in the overrides.

In short, I think that we need to update `getUnhandledProps` to pass `ref` from component if it exists and it makes sence (Form's  and Table's aliases). @levithomason it will be great to see your thoughts.

----

Workaround for this issue use `Form.Field` + `TextArea` instead of `Form.TextArea`:

```jsx
<Form.Field>
  <TextArea ref={__refHandler__} />
</Form.Field>

**Comment by Industrial** [comment]
Thanks 👍

**Comment by levithomason** [comment]
@layershifter you are correct in all regards.  Since our factories are really a more powerful version of `createElement`, I think it makes perfect sense to pass along the `ref`.

This is valid:
```js
createElement(Button, { children: 'Click Me', ref: this.handleRef })
```

So this should be as well:
```jsx
Button.create({ children: 'Click Me', ref: this.handleRef })
```

I'll open a PR for this.

**Comment by levithomason** [comment]
This will not solve the issue with `Form.*` as those components do not use factories, but are simply composing the `FormField` with a predefined `control`:

```jsx
function FormTextArea(props) {
  const { control } = props
  const rest = getUnhandledProps(FormTextArea, props)
  const ElementType = getElementType(FormTextArea, props)

  return <ElementType {...rest} control={control} />
}
```

@Industrial 
In this case, the `ref` is working as expected.  A `ref` on `FormTextArea` will not be forwarded to any underlying component.  React also does not support `refs` on stateless components (i.e. `Form.TextArea`).  So, the `ref` will always return `null`.

For now, @layershifter's solution of putting a ref on the `TextArea` works.  Just know that this is also by chance, as the `TextArea` happens to be a class component and therefore React allows refs.

Another option is to add a special class and select the DOM node with native APIs.  This will work on any React component, stateless or class:

```js
componentDidMount() {
  this.textAreaNode = document.querySelector('.my-textarea-field textarea')
}

<Form.TextArea className='my-textarea-field' />
```

In this case, we are adding a className to the form field that wraps the `textarea` node.  Then, we are simply selecting the textarea within the form field (`.my-textarea-field textarea`)

***

I'll still open the PR for handling refs in factories.

**Comment by levithomason** [comment]
As I go to implement this, I also find that factories already handle refs as well:

```
Button.create(<button data-element ref={c => console.log(c)} />)
// => <button data-element="true"></button>

Button.create({ ref: c => console.log(c) })
// => { ...Button instance }
```

**Comment by Industrial** [comment]
Sorry, I guess the issue was my lack of understanding of React :)
