### ISSUE TITLE
fix(Comment): Comments that are missing content stack oddly

### ISSUE THREAD

**Issue by NickHeiner** [Semantic-Org/Semantic-UI-React#1584]
If a comment does not have enough content, subsequent comments will stack oddly.

**Steps to Reproduce**
1. Go to the [Comment docs](http://react.semantic-ui.com/views/comment#comment-example-avatar)
1. Enter the following code:

```jsx
import React from 'react'
import { Comment } from 'semantic-ui-react'

const CommentExampleAvatar = () => (
  <Comment.Group>
    <Comment>
      <Comment.Avatar src='/assets/images/avatar/small/elliot.jpg' />
      <Comment.Content>
        <Comment.Author as='a'>Elliot Fu</Comment.Author>
      </Comment.Content>
    </Comment>
    <Comment>
      <Comment.Avatar src='/assets/images/avatar/small/elliot.jpg' />
      <Comment.Content>
        <Comment.Author as='a'>Elliot Fu</Comment.Author>
      </Comment.Content>
    </Comment>
  </Comment.Group>
)

export default CommentExampleAvatar
```

**Expected**
![image](https://cloud.githubusercontent.com/assets/829827/25072611/0476b4ce-22a1-11e7-9145-6123798b2ac5.png)

**Result**
![image](https://cloud.githubusercontent.com/assets/829827/25072605/f1a98e66-22a0-11e7-9422-add1680670b3.png)

**Comment by GregoryPotdevin** [comment]
Looks like a CSS issue, unrelated to the React implementation of Semantic UI. Might be worth reporting to https://github.com/Semantic-Org/Semantic-UI

It displays correctly if you add an empty `Comment.Metadata` : 
```jsx
import React from 'react'
import { Comment } from 'semantic-ui-react'

const CommentExampleAvatar = () => (
  <Comment.Group>
    <Comment>
      <Comment.Avatar src='/assets/images/avatar/small/elliot.jpg' />
      <Comment.Content>
        <Comment.Author as='a'>Elliot Fu</Comment.Author>
      </Comment.Content>
      <Comment.Metadata />
    </Comment>
    <Comment>
      <Comment.Avatar src='/assets/images/avatar/small/elliot.jpg' />
      <Comment.Content>
        <Comment.Author as='a'>Elliot Fu</Comment.Author>
      </Comment.Content>
      <Comment.Metadata />
    </Comment>
  </Comment.Group>
)

export default CommentExampleAvatar
```

**Comment by levithomason** [comment]
@GregoryPotdevin thanks for the investigation, you are indeed correct.
@NickHeiner please post a CSS issue on the main repo for this one.
