### ISSUE TITLE
Auto-controlled props emit spurious warning when set to undefined (missing undefined check).

### ISSUE THREAD

**Issue by DylanLukes** [Semantic-Org/Semantic-UI-React#1586]
### Steps

For any auto-controlled property `x`, set both `x` and `defaultX` to `undefined`. For example, `open` and `value` in `Dropdown`.

### Expected Result

These values should be treated as if they are undefined/do not exist.

### Actual Result

Warning: `Dropdown prop "open" is auto controlled. Specify either defaultOpen or open, but not both.`

### Version
0.68.0

### Testcase

http://codepen.io/anon/pen/xdGPxz?editors=1111

### Suggested Fix

Here in [AutoControlledComponent.js](https://github.com/Semantic-Org/Semantic-UI-React/blob/4ca4d03d0094d52489c8d492f0214f22e12dbe04/src/lib/AutoControlledComponent.js#L139), replace:

```js
  if (defaultPropName in this.props && prop in this.props) { ... }
```

by 

```js
  if (_.has(this.props, defaultPropName) 
      && !_.isUndefined(this.props[defaultPropName])  
      && _.has(this.props, prop) 
      && !_.isUndefined(this.props[props]) {
    ...
  }

**Comment by DylanLukes** [comment]
In case anyone is wondering, "why on earth would you set `open` and `defaultOpen` to `undefined`?"...

The answer is interop with other languages targeting JS. For example, using ScalaJS with a `Props` facade type. When constructing an instance of `Props`, all of the factory/constructor arguments must be specified or defaulted to `js.undefined`, as there is no concept of an "unset" attribute.

**Comment by levithomason** [comment]
At first glance, I think this will still pass tests and be backward compatible.  In fact, we likely should've been treating `undefined` as not present to begin with.

Let's get a PR and see what happens.  Note, the logic can be reduced to this as we only care that they are `undefined`, not that they are present at all:

```jsx
if (!_.isUndefined(this.props[defaultPropName]) && !_.isUndefined(this.props[prop]) {
  ...
}
```

**Comment by jonmajorc** [comment]
Hey @levithomason and @DylanLukes I am looking to contribute. I am guessing this issue is still open and is needing to be done, so I would love to help! This is also my first open source contribution too.
