### ISSUE TITLE
Deprecation warnings on PropTypes with React >= 15.5.0

### ISSUE THREAD

**Issue by robgietema** [Semantic-Org/Semantic-UI-React#1587]
As of React 15.5.0 PropTypes should be imported from the prop-types package and not from the main React package anymore (see: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html).

### Steps
Render any component which uses PropTypes.

### Expected Result
No deprecation warnings.

### Actual Result
Deprecation warnings.

### Version
0.68.0

### Testcase
http://codepen.io/anon/pen/dWoJOM

**Comment by g1eny0ung** [comment]
Is the Dropdown give a warning? I open a pr #1588
