### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by lucasriondel** [Semantic-Org/Semantic-UI-React#1590]
Your documentation is down. http://react.semantic-ui.com/

Errors from the console : 
vendor.efab3c6822920f9f6af1.js:1 Uncaught SyntaxError: Unexpected token <
app.d0cf20c18c32b5eeee50.js:1 Uncaught SyntaxError: Unexpected token <

**Comment by subodhpareek18** [comment]
Working fine for me

**Comment by lucasriondel** [comment]
Ok, i've looked it up, and Zain (an ISP in Bahrain) is blocking your website because it thinks cdn.rawgit.com it is malicious. Thanks anyway...

**Comment by lucasriondel** [comment]
Is there a way for me to download the documentation so i don't have to go through a vpn everytime ?

**Comment by subodhpareek18** [comment]
How about trying to build your own docs locally? 
```
git clone https://github.com/Semantic-Org/Semantic-UI-React.git
npm run docs 
```

**Comment by lucasriondel** [comment]
Perfect, thanks a lot.

**Comment by cosmin-seviciu** [comment]
Web site is down again. by down I mean that nothing shows at all.

**Comment by layershifter** [comment]
Works fine to me. Can you check your's browser console?

**Comment by cosmin-seviciu** [comment]
this is what i get in the console

```
adsbygoogle.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vendor.6f18c3b4638e2693a9f5.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
app.c26c115a832541f037ef.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by layershifter** [comment]
There is something with your Adblock or browser settings, make sure that `https://cdn.rawgit.com` is whitelisted there.

**Comment by levithomason** [comment]
Heads up, this is just the Google ad script for the Advertisement component.  We do not use advertisements nor trackers on the docs, so you're safe to disabled ABP for `react.semantic-ui.com`.

If you leave it enabled, there is not much impact either.  The Advertisement component docs just won't load ads.

**Comment by cosmin-seviciu** [comment]
Yep, addblock was the issue. Thanks.
But for a normal user point of view, this should not happen, me as a user I should not experience this.
I consider this to be a problem.

Thanks again :)
