### ISSUE TITLE
Search: Pressing up/down arrow in the search input with no results throws errors to console

### ISSUE THREAD

**Issue by maciej-gurban** [Semantic-Org/Semantic-UI-React#1592]
**Steps to Reproduce**
1. Start typing in the search input box (random characters, just make sure there's no results)
2. While still having the input focused, press arrow up or down on the keyboard

Reproducible in all [demos of search component](http://react.semantic-ui.com/modules/search)

**Expected**
No error should be thrown

**Result**
The following error is shown in the console:
```
Uncaught TypeError: Cannot read property 'offsetTop' of null
    at t.a.scrollSelectedItemIntoView (app.d0cf20c….js:7194)
    at t.a.moveSelectionBy (app.d0cf20c….js:7194)
    at HTMLDocument.a.moveSelectionOnKeyDown (app.d0cf20c….js:7194)
```

**Comment by levithomason** [comment]
Fixed in #1600

**Comment by maciej-gurban** [comment]
Damn, you guys are fast. Thanks!

Also, I've been working with the library for a few days now, and I have to say it's pretty damn well written and so nicely extensible.

**Comment by levithomason** [comment]
Woot! :owl:
