### ISSUE TITLE
Dropdown - arrow keys don't work with Dropdown search in menu example

### ISSUE THREAD

**Issue by GregoryPotdevin** [Semantic-Org/Semantic-UI-React#1597]
### Steps

- go to https://react.semantic-ui.com/modules/dropdown#dropdown-example-search-in-menu
- open the filter dropdown
- use the arrow keys and observe the console output
![image](https://cloud.githubusercontent.com/assets/1522455/25129268/8d01b738-243d-11e7-9ba7-d6c6e10bdea8.png)

### Expected Result
Dropdown items should be selected when using the arrow keys

### Actual Result
Selection using the arrow keys doesn't work, and an error is output in the console :

![image](https://cloud.githubusercontent.com/assets/1522455/25129290/a395e726-243d-11e7-956e-0fa69a7567df.png)

### Version
0.67.2

### Testcase

http://codepen.io/GregoryPotdevin/full/GmpOQR/

### Cause

Using the arrow keys in a dropdown triggers [Dropdown.moveSelectionBy](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L905), which fails because there are no options.

Seems non trivial to fix as the dropdown needs to manage its own items for this to work. Might require to add specific code for a "searchable dropdown" (that would use the dropdown menu options logic, but would render both a search input and a title label)

**Comment by levithomason** [comment]
Duplicate #958, #889 

Please note the message above this and several other Dropdown examples:

![image](https://cloud.githubusercontent.com/assets/5067638/25155637/0077948c-244b-11e7-9146-cdb886584b0b.png)

It is indeed non-trivial, hence the long running issue here.  First step is to get Menu shorthand in place and replicate it for the `Dropdown.Menu`, see #1365 for more on this.

**Comment by GregoryPotdevin** [comment]
Sorry for the duplicate, not sure how I missed the warning (even though I saw it for other Dropdown features).

**Comment by levithomason** [comment]
No worries!
