### ISSUE TITLE
Docs are not properly generated with Type column of component

### ISSUE THREAD

**Issue by jonmajorc** [Semantic-Org/Semantic-UI-React#1608]
Docs are not properly generated with the correct Type for the component. Each component in react-semantic-ui has a Type with its property `{custom}`. This does not seem correct, as I do remember seeing the Type being rendered properly. I am happy to help if I can on this. I am a new contributor to not only this project but to an open source project 😊 

![image](https://cloud.githubusercontent.com/assets/7799266/25306076/00d90420-274c-11e7-9393-204a282a01d4.png)

**Comment by levithomason** [comment]
Strange, locally on the latest master these are correct, see below.  I'll cut a new release right now which will update the docs and we'll see what they look like then.

![image](https://cloud.githubusercontent.com/assets/5067638/25306159/a28dce6e-273c-11e7-9bd3-b8a57b2e0721.png)

**Comment by levithomason** [comment]
This was indeed fixed in the latest release.  Not sure what caused the issue initially, however.

**Comment by jonmajorc** [comment]
Awesome. Thanks @levithomason !
