### ISSUE TITLE
Interface 'ConfirmProps' incorrectly extends interface 'ModalProps'

### ISSUE THREAD

**Issue by Grmiade** [Semantic-Org/Semantic-UI-React#1612]
Interface 'ConfirmProps' incorrectly extends interface 'ModalProps'
Property 'content' is optional in type 'ConfirmProps' but required in type 'ModalProps'.

### Steps
- Compile Typescript project with `react-semantic-ui`

### Expected Result
- Success

### Actual Result
- Error
<img width="903" alt="capture d ecran 2017-04-23 a 23 18 49" src="https://cloud.githubusercontent.com/assets/11244106/25317578/8eb24b1e-287b-11e7-8962-5fc02521f430.png">

### Version
0.68.1

**Comment by vincaslt** [comment]
Getting the same error.

**Comment by layershifter** [comment]
Duplicate, will be fixed by #1611

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.68.2`.

**Comment by Grmiade** [comment]
And it's not over ^^'
<img width="955" alt="capture d ecran 2017-04-24 a 17 30 01" src="https://cloud.githubusercontent.com/assets/11244106/25344870/bd4c8e06-2913-11e7-94b4-ac5c301e4e51.png">
`Statictic` :)

**Comment by levithomason** [comment]
Could you double confirm the installed version? `npm ls semantic-ui-react`?

**Comment by levithomason** [comment]
@layershifter if this is a current issue, could we simply add a compile test to the TS tests?

**Comment by Grmiade** [comment]
`0.68.2`
<img width="926" alt="capture d ecran 2017-04-24 a 17 36 43" src="https://cloud.githubusercontent.com/assets/11244106/25345192/b18c5924-2914-11e7-99e9-43ed3ad15da5.png">

**Comment by levithomason** [comment]
Thanks much for the confirmation.  I've posted this here: #1621.  For now, you should downgrade until we ship a bug fix.  Hopefully will be today.
