### ISSUE TITLE
New 'upward' attribute on Dropdown should be optional (v0.68.1)

### ISSUE THREAD

**Issue by mcrawshaw** [Semantic-Org/Semantic-UI-React#1614]
### Steps
Compile existing project with Typescript that uses ```Dropdown``` and doesn't have ```upward``` set.

### Expected Result
No error.

### Actual Result
```Property 'upward' is missing in type```

### Version
0.68.1

See PR
https://github.com/Semantic-Org/Semantic-UI-React/pull/1603

**Comment by layershifter** [comment]
Duplicate, will be fixed by #1611

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.68.2`.
