### ISSUE TITLE
TypeScript compile errors

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#1621]
The latest bug fix broke further typings.  Ref #1612.

![https://cloud.githubusercontent.com/assets/11244106/25345192/b18c5924-2914-11e7-99e9-43ed3ad15da5.png](https://cloud.githubusercontent.com/assets/11244106/25345192/b18c5924-2914-11e7-99e9-43ed3ad15da5.png)

**Comment by mihai-dinculescu** [comment]
Yep, I get the same errors.

**Comment by layershifter** [comment]
@levithomason Working on a new PR

**Comment by layershifter** [comment]
I've opened #1624, however, we still need rendering tests there

**Comment by noah79** [comment]
Same.

**Comment by layershifter** [comment]
@levithomason There is #1624 and #1625 that adds new tests that validate typings. We need your attention.

**Comment by vcardins** [comment]
Not ideal, but for the time being I hacked by doing this:
```js
loaders: ['react-hot-loader/webpack', `awesome-typescript-loader?${JSON.stringify({ignoreDiagnostics:[2320, 2307]})}`],
```

**Comment by tomitrescak** [comment]
Thanks for the hard work! Looking forward to the fix!
