### ISSUE TITLE
classNameBuilders don't handle 0 properly I think

### ISSUE THREAD

**Issue by haruleekim** [Semantic-Org/Semantic-UI-React#1623]
```javascript
// lib/classNameBuilders.js
export const useKeyOnly = (val, key) => val && key
export const useValueAndKey = (val, key) => val && val !== true && `${val} ${key}`
export const useKeyOrValueAndKey = (val, key) => val && (val === true ? key : `${val} ${key}`)
```
Maybe these functions should regard `0` as truty value
Is it a bug?

**Comment by layershifter** [comment]
@harukim95  thanks that you take attention to this, but it's not a bug. 

These functions are used to form classnames from component's props and accept as value only `bool` or `string` in general. Component's props are validated by `propTypes`. So yes, they will not handle 0 correctly, but is no reasonable way to pass it.
