### ISSUE TITLE
Search component doesn't accept iconPosition prop

### ISSUE THREAD

**Issue by maciej-gurban** [Semantic-Org/Semantic-UI-React#1628]
While most of the props are spread onto Input component, including being able to pass a custom Icon - all of these making Search component very extensible, it doesn't seem to be possible to change the positioning of icon to appear on the left side instead of the right.

Is that something that could be supported? Or is there any other way to achieve that?

**Comment by layershifter** [comment]
`Search` component fully supports `Input` shorthand:

```jsx
<Search input={{ icon: 'user', iconPosition: 'left' }} />
```

![_848](https://cloud.githubusercontent.com/assets/14183168/25491739/88267cb0-2b79-11e7-89b9-287bf213f907.png)

```jsx
<Search input={{ icon: 'user', iconPosition: 'right' }} />
```
![_847](https://cloud.githubusercontent.com/assets/14183168/25491738/86e71a26-2b79-11e7-845d-8fa8c512eeae.png)

However, it will be awesome to get this in docs.

**Comment by levithomason** [comment]
I very much agree with this.
