### ISSUE TITLE
Popup on attribute suggested enhancement, take more than one type of event trigger

### ISSUE THREAD

**Issue by raptoria** [Semantic-Org/Semantic-UI-React#1629]
It would be nice if for the Popup's on attribute, I could supply both hover and click, eg.

      <Popup
       inverted
       on='hover, click'
      ...

**Comment by levithomason** [comment]
Hm, I believe this would lead to conflicting interactions.  Example, `on='click'` does not close on blur while `on='hover'` does close on blur.  There are more complications when you consider `on='focus'`.

Note that these are just "presets", if you will, for the underlying Portal props.  You can set them explicitly yourself if you wish to be more precise about the behavior:

https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Popup/Popup.js#L253
