### ISSUE TITLE
Search: fluid search doesn't work properly

### ISSUE THREAD

**Issue by finbarr** [Semantic-Org/Semantic-UI-React#1632]
### Steps

Use `<Search fluid />`.

### Expected Result

The input gets a class of `ui fluid icon input`.

### Actual Result

The search wrapper gets a class of `ui fluid search` and the input does not become fluid.

### Version
0.67.2 and whichever is in the pen.

### Testcase
http://codepen.io/anon/pen/wdojYw

**Comment by layershifter** [comment]
Looks like bug, I will make PR soon. For now you can simply solve this by:
```jsx
<Search fluid input={{ fluid: true }} />
```

**Comment by levithomason** [comment]
This is actually not a bug, though it can be confusing initially.  The Search consists of an Input and some results.  The Search component's `fluid` prop makes the Search _results_ fluid:

>A search can have its **results** take up the width of its container.
>http://react.semantic-ui.com/modules/search#search-example-fluid

An `Input` component can also have a `fluid` prop, which makes the input itself, making it fill its container width:

>An input can take on the size of its container.
>http://react.semantic-ui.com/elements/input#input-example-fluid

If you'd like the `Input` subcomponent of the Search component to be fluid, please use the `input` prop shorthand suggested by @layershifter.  If you'd like the Search results to be `fluid`, use the top-level `fluid` prop.
