### ISSUE TITLE
Dropdown: Should work with keys instead of values

### ISSUE THREAD

**Issue by karlludwigweise** [Semantic-Org/Semantic-UI-React#1634]
The Dropdown component is working with each option's value internally. Whereas using the key, if supplied, would be correct.

### Steps
Throw a set of options into a Dropdown with two identical values.

### Expected Result
Show both options.

### Actual Result
1. Only the first option will be displayed.
2. Additionally a React warning is thrown in console: "Warning: flattenChildren(...): Encountered two children with the same key..."

### Version
0.68.1

### Testcase
http://codepen.io/karlludwigweise/pen/xdRvYL

And yes, this is a very very awkward use-case.

**Comment by levithomason** [comment]
Thanks, this is being worked on in #1639.  I'll leave this open until that is merged.
