### ISSUE TITLE
Theming in semantic-ui-react

### ISSUE THREAD

**Issue by nitish24p** [Semantic-Org/Semantic-UI-React#1636]
Semantic ui can be themed according to some styles by overriding default variables and initialising a build process via gulp. Can the same be done here ? if yes how?

**Comment by mcrawshaw** [comment]
Yes, react semantic still uses the same underlying css.
https://react.semantic-ui.com/usage#css

**Comment by levithomason** [comment]
@mcrawshaw is correct:
https://github.com/Semantic-Org/Semantic-UI-React#can-i-use-a-custom-css-theme

**Comment by uli28** [comment]
Change theme:
$ npm install semantic-ui --save-dev
Follow instructions, be aware that semantic.json is in root folder.

You can add your theme like shown in this tutorial. http://g14n.info/2016/11/react-semantic-customized/
Included are the themes basic,default,github,material. (you can change /src/theme.config to one of those 4)
gulp-build (after changing)

include "import '../semantic/dist/semantic.min.css';" to index.js to load that customized css.

**Comment by GerbenCdg** [comment]
Check out this repo which is already setup for theming (I was looking to do so and this helped me)
[https://github.com/ucorina/semantic-ui-react-theming]()

**Comment by levithomason** [comment]
Just wanted to let everyone know, we're working on better theming here in Semantic UI React and in Stardust.  The coming year should yield a lot of great things in this area.

See #2939, #2938, and #2710
