### ISSUE TITLE
Modal: getting unknown prop warning on `triggerClose` for shorthand actions

### ISSUE THREAD

**Issue by kirillku** [Semantic-Org/Semantic-UI-React#1642]
### Steps
Copied exact the same [Shorthand Modal](https://react.semantic-ui.com/modules/modal#modal-example-shorthand) to my project, but getting unknown prop warning.
### Expected Result
No warnings
### Actual Result
![unknown prop warning](https://cloud.githubusercontent.com/assets/3331461/25528513/e6281690-2c26-11e7-9b37-baea56457c5f.png)

### Version
0.68.2

**Comment by layershifter** [comment]
@kirillku Yes, it's a known problem, it will be solved by #1599.

**Comment by levithomason** [comment]
Fixed in `0.72.0`, note it was a breaking change: #1599.
