### ISSUE TITLE
fix(Menu): Menu.Item is not highlighted on hovering

### ISSUE THREAD

**Issue by chuan137** [Semantic-Org/Semantic-UI-React#1645]
**Steps to Reproduce**
1. I use the component without onClick property, instead I use React Router Link

```
<Menu scondary>
  <Link to='/'>
        <Menu.Item name='home' active={true}/>
  </Link>
</Menu>
```

**Expected**
the item should be highlighted when hovering, somehow it does not show any changes

**Result**\

**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/collections/menu#menu-example-secondary
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by levithomason** [comment]
You should augment the `Link` component:

```jsx
<Menu.Item as={Link} to='/' name='home' active />
```

Or, render as an `a` tag:
```jsx
  <Link to='/'>
  <Menu.Item name='home' active={true}/>
</Link>
```

Why?  Semantic UI CSS only adds hover effects to menu items that have an `a` tag.  The default tag is a `div`.
