### ISSUE TITLE
TextArea: add minHeight property with autoHeight

### ISSUE THREAD

**Issue by rijk** [Semantic-Org/Semantic-UI-React#1647]
It would be cool if we'd have a `minHeight` property to combine with the `autoHeight` property. This way, we can make a textarea to start at e.g. 4 rows, and grow from there.

Right now, this is impossible, due to the inline styles applied in the [updateHeight](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/addons/TextArea/TextArea.js#L85-L89) method.

**Comment by droms** [comment]
It would be my second contribution but I would like to give it a go.

Let me know if thats Ok and i'm the right track with the below change.

A prop minHeight should be added with a default value of zero and `this.ref.style.minHeight = '0'` in the method mention above should be changed to `this.ref.style.minHeight = minHeight`

**Comment by levithomason** [comment]
Merged in #1679
