### ISSUE TITLE
Progress: indicating progressbar does not change its color

### ISSUE THREAD

**Issue by soraphis** [Semantic-Org/Semantic-UI-React#1650]
**Steps to Reproduce**
1. visit the [react.semantic-ui/modules/progress](https://react.semantic-ui.com/modules/progress#progress-example-indicating) website 
2. checkout the indicating example
3. compare it with the original [semantic-ui](https://semantic-ui.com/modules/progress.html) example

**Expected**
The Progress should change its color with increasing value

**Result**
The Progress does not do this

**Comment by layershifter** [comment]
@soraphis Thanks for report. SUI uses CSS selector based on `data-percent` attribute:

![_851](https://cloud.githubusercontent.com/assets/14183168/25666025/ee8aa44c-3027-11e7-86fa-1d9a093c6612.png)

We should add `data-percent` attribute [there](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.68.2/src/modules/Progress/Progress.js#L196).
