### ISSUE TITLE
fix(Menu): Inverted pointing vertical with colors shows dark diamond

### ISSUE THREAD

**Issue by hufftheweevil** [Semantic-Org/Semantic-UI-React#1651]
First off, I just found Semantics-UI and am blown away by both the ability of the library and the documentation. Who needs Bootstrap when you have this? Anyway, to the issue at hand:

**Steps to Reproduce**
1. Start with this example: https://react.semantic-ui.com/collections/menu#menu-example-inverted-pointing 
2. Add ` color='blue'` to the first `Menu.Item`

**Expected**
The pointer for the menu item should also be blue.

**Result**
The menu item is blue, but the pointer remains the dark gray.
![image](https://cloud.githubusercontent.com/assets/26534009/25681549/a735b6e0-3022-11e7-8642-cde6c1291962.png)

**Notes**
I've found [ issues and fixes](https://github.com/Semantic-Org/Semantic-UI/issues/2355) for this from a while back, but the fixes may have only been applied to menus that were not vertical. And I just noticed that the linked issue is for the main Semantic-UI, not specific to React, so maybe that has something to do with it?

**Comment by agustif** [comment]
Should have nothing to do since CSS problems are foreign to semantic-ui-react...

It seems just nobody cared to send a PR.

**Comment by layershifter** [comment]
@jhalbsgut Thanks for notify, but @agustif is right, we don't handle issues with CSS, so need to create an issue on SUI repo.

Here is html that reproduces problem:
```html
<div class="ui inverted pointing vertical menu">
  <a class="blue active item">Home</a>
  <a class="item">Messages</a>
  <a class="item">Friends</a>
</div>
```

**Comment by ghost** [comment]
@jhalbsgut ^
