### ISSUE TITLE
scrolling issue w/multiple long modals 

### ISSUE THREAD

**Issue by mcku** [Semantic-Org/Semantic-UI-React#1652]
### Steps
Go to example. http://codepen.io/anon/pen/aWLdxg?editors=0011
Child modal's `dimmer`attribute set to `true` 
Click the trigger button
Click the proceed button on the modal
Click on dimmer of the child modal 
The child modal closes.

### Expected Result
Parent modal's scrolling should work

### Actual Result
It doesn't

### Version
0.68.2

### Testcase
http://codepen.io/anon/pen/aWLdxg?editors=0011

**Comment by marcdibold** [comment]
Duplicate #1157
