### ISSUE TITLE
Cannot type in Input in Dropdown

### ISSUE THREAD

**Issue by zhaoyao91** [Semantic-Org/Semantic-UI-React#1654]
### Steps
see https://react.semantic-ui.com/modules/dropdown#dropdown-example-input
I can never focus on the Input. When I click the Input, the dropdown disapears.

### Expected Result
Dropdown does not disapear when click and type in inner Input

### Actual Result
The dropdown disapears

### Version
0.68.2

**Comment by layershifter** [comment]
Dupe, #1593.
