### ISSUE TITLE
Search component value

### ISSUE THREAD

**Issue by namezero** [Semantic-Org/Semantic-UI-React#1655]
we get the selected item through onResultSelect props (e, value)=>{}
what if i select an item, then i backspace and delete the input value? 
it still the old value selected, you should trig onResultSelect (e,null) onBlur if the value of the input is different from the (actual) selected value

**Comment by layershifter** [comment]
Please, follow our issue template and rewrite issue. At now, I personally don't understand what you want to do.

**Comment by layershifter** [comment]
I close this issue, because I haven't received a response from the @namezero 

We can reopen it if we get more details.
