### ISSUE TITLE
Semantic UI not working when lodash installed separately as dependency

### ISSUE THREAD

**Issue by qoalu** [Semantic-Org/Semantic-UI-React#1656]
### Steps
1. have semantic ui installed
2. npm install --save lodash

### Expected Result
working app

### Actual Result
```
Error in ./~/semantic-ui-react/dist/commonjs/modules/Popup/Popup.js
Module not found: [CaseSensitivePathsPlugin] `my-app\node_modules\lodash\pick.js` does not match the corresponding path on disk - File does not exist.
[...]
Error in ./~/semantic-ui-react/dist/commonjs/lib/customPropTypes.js
Module not found: 'lodash/fp/isObject' in my-app\node_modules\semantic-ui-react\dist\commonjs\lib
[...]
```

many more errors, mostly of 2 like above. This is a shortened version

### Version
0.62.0

**Comment by layershifter** [comment]
Can you make a fresh install of deps? `rm -r node_modules; npm i`
Also, are you using Windows?

**Comment by levithomason** [comment]
Note, TA uses Semantic UI React with lodash installed as a separate dependency.  I believe @layershifter is likely correct here.

This is a missing dependency issue and does not appear to be directly related to Semantic UI React code.  Will close for now, willing to reopen if we can get a reproduction case.
