### ISSUE TITLE
Modal: Enter ESC should only close the top layer modal

### ISSUE THREAD

**Issue by zhaoyao91** [Semantic-Org/Semantic-UI-React#1657]
### Steps
1. open multiple modal
2. enter ESC

### Expected Result
only the top layer modal was closed

### Actual Result
all modals were closed

### Version
0.68.2

### Testcase
https://react.semantic-ui.com/modules/modal#modal-example-multiple

**Comment by layershifter** [comment]
It's same problem that in #1157, however I don't sure that it's need to be closed as dupe.
