### ISSUE TITLE
Sidebar.Pushable as property

### ISSUE THREAD

**Issue by matheusrocha89** [Semantic-Org/Semantic-UI-React#1661]
There are some examples of `Sidebar.Pushable` with as property passing an Element I'd like to know if there is a way of passing properties to these elements on `as` of a `Sidebar.Pushable`.

For example:
```
<Sidebar.Pushable as={Segment}>
```
I want to pass `basic` to this Segment on `as` property, how can I do that? 

I tried something like this:
```
<Sidebar.Pushable as={() => <Sidebar basic />}
```

But nothing rendered.

**Comment by levithomason** [comment]
The `as` prop accepts a string or component (function or class) but not a JSX Element.  Just create your special component first, then pass it:

```jsx
const BasicSidebar = props => <Sidebar basic />

<Sidebar.Pushable as={BasicSidebar}
```

**Comment by levithomason** [comment]
I'd expect your original example to also do nearly the same thing.  I'm not sure you want to be passing a Sidebar as the `Sidebar.Pushable` though.  That would create some odd nested behavior.

Typically, the Sidebar.Pushable is something like a Segment:
```jsx
<Sidebar.Pushable as={Segment}>
```

**Comment by matheusrocha89** [comment]
@levithomason I wrote wrong, I will update, the right example was:
```
<Sidebar.Pushable as={() => <Segment basic />}
```

My bad.
![](https://media.giphy.com/media/3o7btUg31OCi0NXdkY/giphy.gif)
