### ISSUE TITLE
Overriding by class doesn't often work well.

### ISSUE THREAD

**Issue by adamdonahue** [Semantic-Org/Semantic-UI-React#1665]
The ability to perform overrides by passing in a `className` seems reasonable, but in practice it doesn't work so smoothly.  Is there a plan to address this?

A specific example.  Assume I have class:

```
.override {
    color: white;
}
```

and I want to apply it to a label:

```
<Label className="override" color="green" ribbon><Header>Header</Header></Label>
 ```

The text remains black.  In order to get it to be white I have to define a style using a rule like:

```
.override.ui.ribbon.label .ui.header  {
    color: white;
}
```

But this is exposing implementation details of the Label components that might change.

What's the correct approach here, if any?  Note that just overriding on a site-wide basis night not always be desired.

**Comment by levithomason** [comment]
The proper solution here is to customize a theme, which includes a LESS file for defining override styles.  If you're looking for a quick and dirty way, you may need to use `!important`, though, I'd highly suggest using a theme.  https://github.com/Semantic-Org/Semantic-UI-React#can-i-use-a-custom-css-theme

This is ultimately a CSS issue and this repo only contains React components.  Please direct further CSS issues to the main repo https://github.com/Semantic-Org/Semantic-UI.
