### ISSUE TITLE
feat(Input): 'autoWidth' prop

### ISSUE THREAD

**Issue by AaronHarris** [Semantic-Org/Semantic-UI-React#1666]
# The problem

Input fields currently have only two types of sizing: fixed, and fluid. Either the textbox is a specified fixed width, or it automatically expands to become the width of its parent container.

# The solution

An `autoWidth` prop, similar to the `autoHeight` prop on TextArea, what results in a behavior where as the text inside the input field grows, so does the input element, up until it reaches the width of the parent container (at which point it looks identical to the 'fluid' layout). This ensures that text inside the input is always visible (up until it is even longer than the parent container), which especially improves the user experience for `transparent` input elements.

 # Possible problem

I could imagine this opens a can of worms when it comes to things like Search that use input (it would need to expand/shrink whenever a result is selected), or other input, as well as resizing the box when the window resizes. Also opening this issue to see what people's opinion of this is.

# Example

![Expanding input](https://i.imgur.com/IvMHkdf.gif)
[eww jQuery equivalent](https://goodies.pixabay.com/jquery/auto-grow-input/demo.html)

**Comment by levithomason** [comment]
Thank you for the request.  I'd like to leave this up to users to wrap the `Input` for now.  My reasoning is that this is not an SUI core feature and this is the first request we've had for it.  If we get more requests for this, I'll consider adding it to SUIR.

**Comment by AaronHarris** [comment]
Thanks for the feedback! I suggested this here since SUI Core doesn't have much dedicated form functionality compared to SUI React - not even an autoheight class to be added to textarea; instead you have to guess the number of rows.

**Comment by MKrivenko** [comment]
+1

**Comment by layershifter** [comment]
We don't going to implement this. Similar functionality from `TextArea` was removed in the previous release.
