### ISSUE TITLE
 in input field: iconPosition doesn't accept the value'Right'.

### ISSUE THREAD

**Issue by riyagarg** [Semantic-Org/Semantic-UI-React#1668]
Warning: Failed prop type: Invalid prop `iconPosition` of value `right` supplied to `Input`, expected one of ["left"].

**Comment by layershifter** [comment]
It doesn't accept `right` because it's right by default:

```jsx
<Input /> // equals to <Input iconPosition='right' /> 
```

So, it's doesn't make sence. Also, [SUI's css](https://github.com/Semantic-Org/UI-Input/blob/2.2.10/input.css#L280) doesn't have class for `right`.

**Comment by riyagarg** [comment]
but how to deal with the iconPosition in RTL?
As if we are giving the iconPosition = 'left' in the input then its moving to right in RTL. 
 if we are using the default position for icons in the rightside then its position is not changing in RTL,  ideally it should move to left.
but if I am providing the iconPosition ='right', it works fine in the RTL but I am getting the above logged warning.

**Comment by layershifter** [comment]
I don't understand your problem. If you need icon on right, don't set `iconPosition` prop.

However, possible there is another behaviour in RTL SUI.

### LTR

```jsx
<Input icon='users' />
```

![_854](https://cloud.githubusercontent.com/assets/14183168/25953437/0a874ad4-366c-11e7-8ed9-2358934740e2.png)

```jsx
<Input icon='users' iconPosition='left' />
```

![_855](https://cloud.githubusercontent.com/assets/14183168/25953430/0313cb42-366c-11e7-9ac1-385b991ccc97.png)

### RTL

```jsx
<Input icon='users' />
```

![_858](https://cloud.githubusercontent.com/assets/14183168/25953498/3d99df2c-366c-11e7-86a1-d5b180dccf4d.png)

```jsx
<Input icon='users' iconPosition='left' />
```

![_856](https://cloud.githubusercontent.com/assets/14183168/25953490/384e48d2-366c-11e7-90df-f42ffb80d859.png)

**Comment by riyagarg** [comment]
I want the same icon which has a default position (right) in LTR to shift to Left in RTL. which is not happening untill I provide the iconPosition = 'right' in LTR.

**Comment by levithomason** [comment]
I think there might be a valid issue here.  Could you create a codepen that demonstrates the problem?  Fork this to get started: codepen.io/levithomason/pen/ZpBaJX

**Comment by mcfoton** [comment]
@levithomason made an example here: https://codepen.io/mcfoton/pen/wmLxeY?editors=0010 will that do?

**Comment by genehynson** [comment]
I also believe this is a valid issue. If I want to apply custom css to the input part of the input box, I have to split the input box like so:
```js
<Input>
    <input className='custom'/>
    <Icon name='calendar'/>
</Input>
```
...which looks like:
![image](https://user-images.githubusercontent.com/6411855/40016530-988a1386-5784-11e8-8be9-f48701f5d431.png)
...but if I apply the `iconPosition='right'` flag like so:
```js
<Input iconPosition='right'>
    <input className='custom'/>
    <Icon name='calendar'/>
</Input>
```
...it looks like:
![image](https://user-images.githubusercontent.com/6411855/40016571-b9bae4ea-5784-11e8-9f97-85f14681e3a2.png)
...but then I get a PropTypes exception.

**Comment by layershifter** [comment]
It's strange that this issue doesn't contain my reply. Correct usage for the children API:

```jsx
<Input icon>
  <input className="custom" />
  <Icon name="calendar" />
</Input>
```
