### ISSUE TITLE
Dropdown: Not showing icon/image

### ISSUE THREAD

**Issue by zerazeru** [Semantic-Org/Semantic-UI-React#1669]
### Steps
If the Dropdown.Item has an icon or an image set the icon/image is not showing after selection, only the item's text.
Same when the dropdown has the defaultValue set.

### Expected Result
The closed dropdown should show the selected item's icon/image like in Semantic UI:
http://jsfiddle.net/t9vfxo5t/

### Actual Result
Only the text of the selected item is shown on closed dropdowns.

### Version
0.68.3

### Testcase
http://codepen.io/anon/pen/aWYqzE

**Comment by layershifter** [comment]
Dupe, #1147. PRs are welcome.
