### ISSUE TITLE
Grid: should have inverted prop

### ISSUE THREAD

**Issue by tobiashort** [Semantic-Org/Semantic-UI-React#1673]
### Steps
Divided grid with the "inverted" attribute on a dark background

### Expected Result
Grid dividers are inverted and visible

### Actual Result
Grid does not accept "inverted" attribute. Dividers are too dark to be recognized on a dark background

### Version
0.68.3

### Workaround
```
<Grid className="inverted">
</Grid>
```

**Comment by layershifter** [comment]
As I [see](https://github.com/Semantic-Org/UI-Grid/blob/master/grid.css#L1117), `Grid` can really be inverted. We should add an `inverted` prop to `Grid` with docs example.

**Comment by levithomason** [comment]
Fixed in #1677
