### ISSUE TITLE
Dropdown: Consider avoid force recalculation styles

### ISSUE THREAD

**Issue by a-x-** [Semantic-Org/Semantic-UI-React#1674]
// Excuse my beginner's English

Look at this code please:
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L953

Forced reflow is a likely performance bottleneck.

In this lines of code, DOM is reading and writing immediately.

Would be cool, if dom reading will be removed in favor of calculations on variables. Maybe DOM reading could be async (via `requestAnimationFrame`).

**Comment by a-x-** [comment]
My case — 2000 items in the Dropdown — that's not too much.

<img width="1680" alt="dropdown-slow" src="https://cloud.githubusercontent.com/assets/6201068/26017315/a370e74a-3771-11e7-91ff-dcbefb96512b.png">

**Comment by levithomason** [comment]
Thanks for spotting this.  I have not invested in any performance improvements, yet.  Any work in this area would be very much appreciated.

PRs with before/after benchmarks are welcome.

**Comment by qoalu** [comment]
Wanted to open a new issue, but this actually fits into the issue I am having with autoSized TextAreas
![image](https://cloud.githubusercontent.com/assets/1624045/26063062/1761cbfc-398d-11e7-9863-ba08ca3aa265.png)

I am getting 3 rerenders for a TextArea here. For now replaced with another plugin which does not cause this to happen.

Here is a useful overview of Javascript that causes layout to happen from Paul Irish
https://gist.github.com/paulirish/5d52fb081b3570c81e3a 

It's probably one of those. For TextArea this seems to be `getComputedStyle` in the updateHeight Method:


```
let { borderTopWidth, borderBottomWidth } = window.getComputedStyle(this.ref)
borderTopWidth = parseInt(borderTopWidth, 10)
borderBottomWidth = parseInt(borderBottomWidth, 10)

this.ref.rows = '1'
this.ref.style.minHeight = '0'
this.ref.style.resize = 'none'
this.ref.style.height = 'auto'
this.ref.style.height = (this.ref.scrollHeight + borderTopWidth + borderBottomWidth) + 'px'
```

**Comment by glee23** [comment]
I'm not well versed enough in react to be able to implement a fix, but this performance issue prevents me from being able to use this library for my project :(

**Comment by levithomason** [comment]
We should investigate implementing [react-virtualized](https://github.com/bvaughn/react-virtualized) for the Dropdown list.  This could resolve perf issues with large lists.

**Comment by ibolton336** [comment]
Having an issue with this also. 1500 values in a dropdown may be my problem.

**Comment by anjapadu** [comment]
I will give it a try on my free time mr bot :)

**Comment by Shenrak** [comment]
Hi guys,

Just wanted to let you know that i have the same performance issue with ~800 values
Something like 800ms delay when opening and same when choosing a value.

**Comment by levithomason** [comment]
Hey folks, please use the reaction button on the main thread to show support.  This makes issues sortable by most reactions and helps assess their potential impact.  Comments confirming the issue ping a lot of people and get lost in the noise.

This issue has been labeled `optimization` and `help wanted` meaning it is valid, we are aware many people are experiencing the problem, and we'd love a PR.  With ❤️ , thank you!

**Comment by nikc3work** [comment]
I am also having performance issue for 1000+ values. There is lot of lags while inputting text in search.

**Comment by RonenMars** [comment]
Having a performance issue for 1800 values. Awful lags on dropdown open, select and even close.
