### ISSUE TITLE
Be able to pass any kind of array to the Search component

### ISSUE THREAD

**Issue by juank11memphis** [Semantic-Org/Semantic-UI-React#1681]
### Steps
`
results = [
  {id: 1, title: 'title1', description: 'desc', bandName: 'maiden', genre: 'heavy metal'},
  {id: 1, title: 'title1', description: 'desc', bandName: 'maiden', genre: 'heavy metal'}
];
<Search
          loading={isLoading}
          onSearchChange={this.handleSearchChange}
          results={results}
          value={value}
          resultRenderer={this.resultRenderer}
        />
`
### Expected Result
This should not show any warnings

### Actual Result
Displays this warning:
`Warning: Failed prop type: Invalid prop `results` supplied to `Search`.`

### Version
0.68.3

**Comment by layershifter** [comment]
It looks that this issue can be solved by simplifying of prop's validator, but it needs more attention.

**Comment by kunokdev** [comment]
So it's not a bug on our side? Passing array of objects like before is still ok? I didn't have this warning before I upgraded Semantic-UI and React 16...

**Comment by debugpoint136** [comment]
sorry what is the solution for this?

**Comment by noinkling** [comment]
Same as #1141 I believe

**Comment by FrancoisPecasse** [comment]
Is there a solution for this?

**Comment by MieszkoWrzeszczynski** [comment]
Anyone has a possible solution?

**Comment by layershifter** [comment]
Dulpicate of #1681.

**Comment by HemalR** [comment]
@layershifter 

Typo alert, should read:

Duplicate of https://github.com/Semantic-Org/Semantic-UI-React/issues/1141

**Comment by lednhatkhanh** [comment]
Any solutions for this?
