### ISSUE TITLE
Render button with content and icon take about 70ms

### ISSUE THREAD

**Issue by sylvain-pauly** [Semantic-Org/Semantic-UI-React#1686]
### Steps

Render a button with an icon named in 2 words (via props or children has the same effect) :
`
const example = () => <Button icon="square check" content="ON" />
`
### Expected Result

The button with text and icon rendered in more or less than 1ms.
(A button with an icon named in one word take less than 1ms)

### Actual Result

Somehow the render take about 60-70ms.

### Version
0.68.3

**I'm sorry but I couldn't get Perf working in codepen**

**Comment by layershifter** [comment]
I'm think that you meet the same problem that described in #1184. Can you check render performance of `Button` without an icon?

**Comment by sylvain-pauly** [comment]
You're right, it's the same problem. I'll use the "className" prop instead of "name".

Thanks a lot !
