### ISSUE TITLE
fix(Table): sortable stomps on th color when inverted

### ISSUE THREAD

**Issue by ChadNicholas** [Semantic-Org/Semantic-UI-React#1688]
**Steps to Reproduce**
Create a <Table inverted sorted>

**Expected**
Header text should be white

**Result**
Header text is black due to:
.ui.sortable.table thead th {
    cursor: pointer;
    white-space: nowrap;
    border-left: 1px solid rgba(34,36,38,.15);
    color: rgba(0,0,0,.87);  <--- this is stomping on inverted's color
}

**Testcase**
Add sortable to https://react.semantic-ui.com/collections/table#table-example-selectable-inverted-row

**Comment by layershifter** [comment]
@ChadNicholas Thanks for the report. But, this is ultimately a CSS issue and this repo only contains React components. Please direct further CSS issues to the main repo https://github.com/Semantic-Org/Semantic-UI.
