### ISSUE TITLE
Button: Icon button has different width if content is 0 (number)

### ISSUE THREAD

**Issue by kirillku** [Semantic-Org/Semantic-UI-React#1691]
When icon button content is `0` (number), it's rendered with different width. Should be the same as with `'0'` (string).

### Steps
```javascript
  <Button icon='world' content={0} />
  <Button icon='world' content='0' />
```
### Expected Result
![expected](https://cloud.githubusercontent.com/assets/3331461/26299623/21567eda-3ee4-11e7-9c68-8d890f59c564.png)

### Actual Result
![actual](https://cloud.githubusercontent.com/assets/3331461/26299615/1b8882be-3ee4-11e7-8285-b343a3daf677.png)

### Version
0.68.3

### Testcase
[codepen](http://codepen.io/kirillku/pen/gWZYaM)

**Comment by layershifter** [comment]
@kirillku Thanks for awesome report. PR is coming.
