### ISSUE TITLE
Button: redundant prop in Vertical Group example

### ISSUE THREAD

**Issue by andreipfeiffer** [Semantic-Org/Semantic-UI-React#1697]
**Steps to Reproduce**
1. Look at the docs
2. https://react.semantic-ui.com/elements/button#button-example-group-vertical

**Expected**
The last button (bottom) from the vertical group should have the top-left corner not rounded.

**Result**
Instead, it is rounded.

**Testcase**
https://react.semantic-ui.com/elements/button#button-example-group-vertical

**Possible fix**
The problem seams to be related to the fact that the parent has the classes `top attached`.
Those classes are used apparently by the __Vertically Attached__ examples.
If you remove `attached='top'` from the example, it looks fine.

**Comment by layershifter** [comment]
@andreipfeiffer Thanks for report, looks like a copy-paste issue. We should simply remove `attached='top'` from this example.

**Comment by andreipfeiffer** [comment]
Glad to help.
BTW, great work guys.

**Comment by andreipfeiffer** [comment]
@layershifter I want to create a PR for this. Is this an accepted commit message?
"docs(Button): redundant prop in Vertical Group example (#1697)"

**Comment by layershifter** [comment]
@andreipfeiffer "docs(Button): remove redundant prop in Vertical Group example"
