### ISSUE TITLE
Browser tab not showing `Icon` when viewing Icon docs

### ISSUE THREAD

**Issue by gitname** [Semantic-Org/Semantic-UI-React#1709]
✔ BUGS → This form is required:

### Steps

1. Visit https://react.semantic-ui.com/.
2. Click the `Header` link in the sidebar.
3. Notice the browser tab says `Header | UI React`.
4. Click the `Icon` link in the sidebar.
5. Notice the browser tab **still** says `Header | UI React` (instead of saying `Icon | UI React`).
6. Click the `Image` link in the sidebar.
7. Notice the browser tab says `Image | UI React`.

### Expected Result

After completing step 4, I expect the browser tab to say `Icon | UI React`.

### Actual Result

After completing step 4, the browser tab continues to show `Header | UI React`.

Here's a screencast showing the bug (the browser tab is near the top left of the window):

![2017-05-27_21-35-21](https://cloud.githubusercontent.com/assets/7143133/26526147/92d1d138-4324-11e7-8731-6acd5977825a.gif)

### Version

I see this behavior in the version of the repository currently deployed to https://react.semantic-ui.com/ - I don't know its version number or ID.

My web browser is Google Chrome 58 (64-bit).

### Testcase

None

**Comment by layershifter** [comment]
@gitname Thanks for report :+1: 

![image](https://cloud.githubusercontent.com/assets/14183168/26527405/596e4b9c-439c-11e7-8669-761f49fce88e.png)

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.68.5`.
