### ISSUE TITLE
Workaround for label when combining with third party form elements

### ISSUE THREAD

**Issue by sonarforte** [Semantic-Org/Semantic-UI-React#1715]
### Steps
It's clear that this library is exceedingly useful, and one of the reasons is that elements can be composed with other elements. 

For example, I'm making a lot of forms and this is a common pattern:
```
import {
  Form as UIForm,
} from 'semantic-ui-react'
import { Control, } from 'react-redux-form'
...
        <UIForm.Field
          as={Control.text}
          model="forms.widget.number"
          placeholder="0"
        />
```

### Expected Result

However, if I would like to be able to use a `required` tag on the semantic component, I can't do so since that requires a `labal` tag, which, according to the docs, is "mutually exclusive with children."

Thus when I try this:

        <UIForm.Field
          as={Control.text}
          model="forms.widget.number"
          placeholder="0"
          label="foobar"
          required
        />

### Actual Result

I get this:

> Uncaught Error: input is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`. Check the render method of Control.

Are there any known workarounds for this problem? How else could I use the correct form elements and still get the behavior from the semantic library?

### Version
0.67.0

**Comment by layershifter** [comment]
@sonarforte Your markup don't work because `Control.text` returns an `input` element which can't have children, while `Form.Field` wants to render them. You have two variants there:

```jsx
<Form.Field label="Foo" placeholder="foo" required>
  <Control.text model=".foo" />
</Form.Field>
```

```jsx
<Form.Input
  as={Control.text}
  label="Bar"
  model=".bar"
  placeholder="bar"
  required  
/>
```

If they will not work, you can also try:

```jsx
<Form.Input label="Baz" required>
  <Control.text model=".baz" placeholder="bar" />
</Form.Input>
```

Let us know which of them is correctly working.

**Comment by sonarforte** [comment]
The first option just prints the label and a red * showing that it's required, but no field for me to type in.

The second variant gives the following error: 

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

It seems like the third is the only one that works.

**Comment by layershifter** [comment]
@sonarforte Thanks for the feedback, I'm glad that the solution is found.

However, one from two first variants should be working. I don't have any experience with `react-redux-form`, but if we will create a repo with minimal repro, I will take a look.

**Comment by sonarforte** [comment]
@layershifter After some more playing it looks like a syntactical variation on the first option works:

 ```
       <UIForm.Field required>
          <label>Hello</label>
          <Control.text model=".foo" />
        </UIForm.Field>
```
