### ISSUE TITLE
Input: remove need for icon to support 'loading' prop

### ISSUE THREAD

**Issue by TimNZ** [Semantic-Org/Semantic-UI-React#1716]
Allow 'loading' prop to work on Input without the need for an 'icon' to be specified.

I'm currently using **icon=" "** which throws a validation error, still works though.

**Comment by layershifter** [comment]
I'm not sure that it's really need to be implimented, here is description of a loading example:
> An **icon** input field can show that it is currently loading data.

Here is example html output of your workaround:

```jsx
<Input loading icon=' ' placeholder='Search...' />
```

```html
<div class="ui loading icon input">
  <input type="text" placeholder="Search..." />
  <i aria-hidden="true" class="  icon"></i>
</div>
```

It renders an empty `i` element, it's required markup by SUI, BTW. So, I'm not sure that it's a correct use case, however @levithomason can have an another opinion.

**Comment by TimNZ** [comment]
I agree with what you are saying now I read the documentation more thoroughly.

The question is why whoever originally decided Loading only needed to apply to icons.

I'll look at alternatives. 
Thanks.

**Comment by levithomason** [comment]
Per the [loading](http://react.semantic-ui.com/elements/input#input-example-loading) docs, an icon is required in order to show the loading state:

>Loading inputs automatically modify the input's icon on loading state to show loading indication.

This seems silly, I'd expect the `loading` state to work just as `error` and `success` states work when used alone.  I'd gladly take a PR that adds this.

### Proposal
If no icon is specified but `loading` is, we can simply render _any_ icon, perhaps a `spinner`.
```jsx
<Input loading placeholder='Search...' />
```
```html
<div class="ui loading icon input">
  <input type="text" placeholder="Search..." />
  <i aria-hidden="true" class="spinner icon"></i>
</div>
```

**Comment by TimNZ** [comment]
Great.  I was going to work on a PR but since I've committed to MVP critical path things for a launch didn't need the distraction and had a work-around.

Plus I would have to spend time understanding the src structure, you fancy coders confuse me :)

In the calendar to do next week.
