### ISSUE TITLE
Floating dropdown with button doesn't behave properly

### ISSUE THREAD

**Issue by jtokoph** [Semantic-Org/Semantic-UI-React#1717]
### Steps
```jsx
import React from 'react'
import { Button, Dropdown } from 'semantic-ui-react'

const options = [
  { key: 'edit', icon: 'edit', text: 'Edit Post', value: 'edit' },
  { key: 'delete', icon: 'delete', text: 'Remove Post', value: 'delete' },
  { key: 'hide', icon: 'hide', text: 'Hide Post', value: 'hide' },
]

const DropdownExampleFloating = () => (
  <Button.Group color='teal'>
    <Button>Save</Button>
    <Dropdown options={options} floating button className='icon' />
  </Button.Group>
)

export default DropdownExampleFloating
```

### Expected Result
<img width="180" alt="screen shot 2017-05-30 at 12 47 30 am" src="https://cloud.githubusercontent.com/assets/346225/26573182/997dfb0c-44d1-11e7-8f21-5b97dd57b63e.png">

Above screenshot from: https://semantic-ui.com/modules/dropdown.html

### Actual Result
The text of the dropdown sections shows up in the button area.
<img width="590" alt="screen shot 2017-05-30 at 12 44 59 am" src="https://cloud.githubusercontent.com/assets/346225/26573203/b25746e2-44d1-11e7-88f3-821edac897ea.png">

Above screenshots from: https://react.semantic-ui.com/modules/dropdown#dropdown-example-floating

### Version
0.68.4

**Comment by layershifter** [comment]
@jtokoph Thanks for your eyes. It's happens because `Dropdown` will always render text which will contain a current value or a `trigger` element.

Here is workaround for this issue, however it's a very dirty solution.

```jsx
  <Button.Group color='teal'>
    <Button>Save</Button>
    <Dropdown options={options} floating button className='icon' trigger={<div />} />
  </Button.Group>
```
