### ISSUE TITLE
Dropdown: minCharacters breaks search input

### ISSUE THREAD

**Issue by ayastreb** [Semantic-Org/Semantic-UI-React#1718]
I believe this issue is caused by #1690
When minCharacters is set to 1 (by default) - it is not possible to delete the last character in search query.
When minCharacters is set to > 1 - it is not possible to enter the search query at all.

### Steps
* Create a dropdown with default minCharacters
* Create a dropdown with minCharacters = 2
* Click on dropdown and start typing search query (e.g. -> "Afgan")
* Now you want to change your search query to "USA", so delete first query and start typing "USA"
### Expected Result
* It should be possible to type in and change search query
### Actual Result
* when minCharacters is set to 1 (by default) it is not possible to delete the last character, it always remains in the input
* when minCharacters is set to > 1 it is not possible to enter the search query at all
### Version
0.68.4

### Testcase
https://codepen.io/anon/pen/PmMPMN

@dyesseyumba would you like to check this?

**Comment by layershifter** [comment]
@ayastreb Thanks for the excellent report :+1:

I will take a look on this, seems we need more tests there after the fix.

**Comment by layershifter** [comment]
I've made a some investigation there, as I see #1690 doesn't implemented `minCharacters` feature correctly. How it works in SUI (*minCharacters 3*):

### Without input

![peek 2017-05-31 12-37](https://cloud.githubusercontent.com/assets/14183168/26626082/b813104c-45fe-11e7-8700-aba73ee9f2f5.gif)

### Two characters

![peek 2017-05-31 12-44](https://cloud.githubusercontent.com/assets/14183168/26626140/f43774aa-45fe-11e7-9ee4-d56d936b6a0e.gif)

### There characters

![peek 2017-05-31 12-46](https://cloud.githubusercontent.com/assets/14183168/26626189/245d1d7e-45ff-11e7-9556-be2655dc10d5.gif)

**Comment by krunal222** [comment]
# **try for it.** 
```
fullTextSearch : true,     // default : false
minCharacters : 3        // default : 0
```
**i hope Solve for your problems**
