### ISSUE TITLE
'npm install semantic-ui-react' has error

### ISSUE THREAD

**Issue by hoangta79** [Semantic-Org/Semantic-UI-React#1723]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - http://stackoverflow.com/search?q=semantic-ui-react

✔ BUGS → This form is required:
When I run 'npm install semantic-ui-react', I get error as below:
"Refusing to install semantic-ui-react as a dependency of itself"
Can you support me to pass this error?

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
http://codepen.io/levithomason/pen/ZpBaJX

**Comment by joshmanders** [comment]
> "Refusing to install semantic-ui-react as a dependency of itself"

You're trying to run it inside of the actual semantic-ui-react project.

**Comment by hoangta79** [comment]
I'm newbie to use it. I am following guideline in https://react.semantic-ui.com/usage.

**Comment by joshmanders** [comment]
Either you are inside the semantic-ui-react project, or named your project that in `package.json` you can't install a dependency named the same I guess.

**Comment by hoangta79** [comment]
Thanks guy. I can fix  my issue now.
