### ISSUE TITLE
Upward dropdown is not supported

### ISSUE THREAD

**Issue by riyagarg** [Semantic-Org/Semantic-UI-React#1728]
Unknown prop upward on 'div' tag. Remove this prop from the element.

**Comment by layershifter** [comment]
In fact, it's [supported](https://react.semantic-ui.com/modules/dropdown#dropdown-example-upward-selection) from `0.68.1`, make sure that you use this version or higher.

**Comment by levithomason** [comment]
@layershifter Heads up, make sure to use `https` links or else the docs will not load the specific example.  The link will go to the main page only.  I updated your comment above.

Why?

Github doesn't offer routing abilities for gh-pages sites.  We use a hack to [capture the full url in the 404 page](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/404.html#L4), write it storage, then redirect to index.html.  When the app loads, we [check for the redirect in storage](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/index.ejs#L10).

All this only works with `https` as storage between `http` and `https` is not shared.  More hacks can probably fix this, but it is a low priority.
