### ISSUE TITLE
Webpack build error - `Module parse failed`

### ISSUE THREAD

**Issue by polarathene** [Semantic-Org/Semantic-UI-React#173]
```
ERROR in ./~/stardust/src/index.js
Module parse failed: /react-project-path/node_modules/stardust/src/index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import { deprecateComponents } from './utils/deprecate'
```

I took a look at what babel settings were used in your [`.babelrc`](https://github.com/TechnologyAdvice/stardust/blob/master/.babelrc), as well as the notes on webpack loader on the README. Babel loader looks like the following:

```
..

webpackConfig.module.loaders = [{
  test: /\.(js|jsx)$/,
  exclude: /node_modules/,
  loader: 'babel',
  query: {
    cacheDirectory: true,
    plugins: ['transform-runtime', "add-module-exports"],
    presets: ['es2015', 'react', 'stage-0', 'stage-1'],
    env: {
      development: {
        plugins: [
          ['react-transform', {
            transforms: [{
              transform: 'react-transform-hmr',
              imports: ['react'],
              locals: ['module']
            }, {
              transform: 'react-transform-catch-errors',
              imports: ['react', 'redbox-react']
            }]
          }]
        ]
      }
    }
  }
}

..
```

I'm new to babel and webpack, this is taken from the [webpack config](https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L107) in [`react-redux-starter-kit`](https://github.com/davezuko/react-redux-starter-kit). I've done an npm install of the two added plugins/presets like so:

```
npm install --save-dev babel-preset-stage-1
npm install --save-dev babel-plugin-add-module-exports
```

Running the webpack server with `npm start` for the project brings up the mentioned error above.

**Comment by dvdzkwsk** [comment]
The annoying part for right now is that you need to process Stardust with babel. If you change your exclude for the js loader to:

``` js
exclude: /node_modules\/(?!(stardust)/,
```

That should work as at least a temporary solution.

**Comment by polarathene** [comment]
If I need to compile it, any reason a pre-compiled version isn't being made available?

**Comment by dvdzkwsk** [comment]
Still a relatively young project, I don't believe they were prepared to release it to the public just yet.

**Comment by ghost** [comment]
@polarathene Thanks for the issue! As @davezuko suggests it's still very much in its infancy. But the capabilities provided for client-side form validation and easily creating slick UIs is pretty incredible already. We've outlined [a Roadmap for v1](https://github.com/TechnologyAdvice/stardust/blob/master/ROADMAP.md). Please feel free to open a pull request against that if you feel it's missing anything you'd like to see as we work towards an initial release. Meanwhile, I hope you enjoy using the project.

**Comment by levithomason** [comment]
@polarathene As of [this PR](https://github.com/TechnologyAdvice/stardust/pull/176), Stardust now includes a CommonJS build in `dist/` when you install.  You no longer need to build the `src/` yourself.

I've also left the `src/` in for backwards compatibility and the option to compile yourself if you like.  Cheers!

**Comment by polarathene** [comment]
@levithomason Much appreciated, thanks :)

**Comment by levithomason** [comment]
No problem!
