### ISSUE TITLE
overflow:scroll breaks Dropdown

### ISSUE THREAD

**Issue by alexanderwe** [Semantic-Org/Semantic-UI-React#1736]
**Steps to Reproduce**
1. add `overflow:auto` or `overflow:scroll` to `ui vertical menu` where a Dropdown is inside.

**Expected**
The Dropdown should appear right to the menu.

**Result**
The Dropdown does not show up

**Testcase**
Add `overflow:auto` in the Chrome Inspector at: https://react.semantic-ui.com/modules/dropdown#dropdown-example-pointing-two` to the parent with the class `ui vertical menu`

Is this an intended behavior ? Because I need to add the overflow property in the vertical menu for my project and I was wondering why the dropdown is not working with it.

![bildschirmfoto 2017-06-04 um 18 49 34](https://cloud.githubusercontent.com/assets/12934015/26763661/b648067c-4956-11e7-95f0-6ae39498ca86.png)

**Comment by layershifter** [comment]
> Is this an intended behavior ?

Yes, I think. However, this is ultimately a CSS issue and this repo only contains React components. Please direct further CSS issues to the main repo https://github.com/Semantic-Org/Semantic-UI.

**Comment by alexanderwe** [comment]
@layershifter Thanks for your answer and your recommendation issue this problem in the main repo.
