### ISSUE TITLE
Button: add focus() method

### ISSUE THREAD

**Issue by Sole-Valero** [Semantic-Org/Semantic-UI-React#1740]
### Steps
It is not possible to call focus() method when you hav a ref to an Button component
<Button   ref={(button) => this.buttonRef=button} >Select All</Button>

This is a similar issue also solved for Input component:
https://github.com/Semantic-Org/Semantic-UI-React/issues/1475

### Expected Result
this.buttonRef.focus() --> send the focus to the button
### Actual Result
 Uncaught TypeError:this.buttonRef.focus is not a function

**Comment by levithomason** [comment]
I think focusing a Button is common enough that this makes sense to implement this.  Thanks for the idea.

In the meantime, here's a workaround:

```jsx
const $button = document.querySelector('#my-button')
if ($button) $button.focus()

<Button id='my-button' />
```
