### ISSUE TITLE
How do you change active color of a toggle button?

### ISSUE THREAD

**Issue by cbll** [Semantic-Org/Semantic-UI-React#1741]
I've tried various methods but I can't seem to solve it; How do you change the active color of a toggle button, as such:

```
<Button toggle compact active={active} onClick={this.someFunction}>
    <Icon name='add' /> New
</Button>
```

The "inactive" color(that being, standard grey color) is fine for when it isn't active. But how do you change the active color? It's green per default, but I'd like it to be red instead(for example, when I toggle the option to delete stuff on a list)

Changing the `color` prop will only change the default color from grey -->{color} but it won't change the active color from green when toggling. 

Thanks! :)

**Comment by layershifter** [comment]
@cbll Everything that you need to keep in mind is that currectly SemanticUI React doesn't handle CSS, it only forms a valid HTML markup that can be used with Semantic UI. So, any real styling should be performed with CSS and possibly using SUI's [theming](https://semantic-ui.com/usage/theming.html), here is helpful [instructions](https://github.com/Semantic-Org/Semantic-UI-React#can-i-use-a-custom-css-theme).

I've made a [codepen](https://codepen.io/layershifter/pen/LLpmVW) that will show how to solve your problem.

**Comment by levithomason** [comment]
@cbll A toggle button is only intended to show the `positive` state.  If you'd like a different color, you can use the `active` value to toggle the `color` prop:

```jsx
<Button
  active={active}
  compact
  color={active ? 'red' : null}
  icon='add'
  content='New'
  onClick={this.someFunction}
/>
```
