### ISSUE TITLE
Missing attributes in html

### ISSUE THREAD

**Issue by makarov-roman** [Semantic-Org/Semantic-UI-React#1743]
### Steps
```javascript
const props = {
      autoFocus:false,
      autoComplete: "username",
      disabled:false,
      error:false,
      id:"username",
      onBlur: () => {},
      onChange: () => {},
      placeholder:"",
      type:"text",
      value:"",
      name:"username"
}
<Input {...props} />
```
### Expected Result
props autofocus, name, value and some others are passed to html
### Actual Result
only type (by default I guess) passed
### Version
0.68.5

### Testcase
[CodePen](https://codepen.io/rmakarovWithPen/pen/ZybQaO)

**Comment by layershifter** [comment]
@rmakarov94 Thanks for the report, PR is coming.

**Comment by makarov-roman** [comment]
Nice work! Thanks
