### ISSUE TITLE
Dropdown not clearing characters

### ISSUE THREAD

**Issue by fingermark** [Semantic-Org/Semantic-UI-React#1745]
### Steps

Navigate to the "Search Selection" demo on the [official demo page](https://react.semantic-ui.com/modules/dropdown).

Type in `f` hit backspace.

### Expected Result

The 'f' goes away.

### Actual Result

The 'f' stays.

### Version
0.68.5

### Testcase
[Fork, update, and replace this pen to show the bug]:
http://codepen.io/levithomason/pen/ZpBaJX

**Comment by codeaid** [comment]
Also having the same issue. Works if you set `minCharacters` to `0` but obviously that's not a fix.

**Comment by layershifter** [comment]
Duplicate #1718, there is also PR that fixes this bug #1722, see [my comment](https://github.com/Semantic-Org/Semantic-UI-React/pull/1722#issuecomment-306915979).
