### ISSUE TITLE
How do you trigger a popup via props and not a button click/hover/focus?

### ISSUE THREAD

**Issue by cbll** [Semantic-Org/Semantic-UI-React#1749]
Main question is here:

https://stackoverflow.com/questions/44436189/semantic-ui-react-how-do-i-trigger-a-popup-without-it-being-click-hover

**Comment by layershifter** [comment]
You can manage the `Popup` state with the `open` prop:

```jsx
  <Popup
    trigger={<Button icon='add' />}
    content='Add users to your feed'
    open={true}
  />
```
However, it's not usable because currently `Popup`'s position is calculated only when trigger action acquired, there is issue for this (#1065).

**Comment by Alice-Ke** [comment]
And after that how can set back the open property to false, so that it can be used for the next popup? Thanks!
