### ISSUE TITLE
Dropdown: click on header or divider should not close menu

### ISSUE THREAD

**Issue by saitonakamura** [Semantic-Org/Semantic-UI-React#1755]
### Steps

Create a dropdown with `Header` or `Divider` in it an click on it

### Expected Result

Dropdown menu doesn't closes
[original Semantic UI docs proof](https://semantic-ui.com/modules/dropdown.html#dropdown)

### Actual Result

Dropdown menu closes

### Version
0.68.5

### Testcase
[https://codepen.io/saitonakamura/pen/GEoxOj?editors=0010](https://codepen.io/saitonakamura/pen/GEoxOj?editors=0010)

**Comment by saitonakamura** [comment]
Strange thing, I can't reproduce it when using `search` dropdown

**Comment by levithomason** [comment]
We currently do not support Headers and Dividers in Dropdowns.  This discussion is best suited your RFC #1724.  We need to work out the shorthand API for this.

Odds are, we will do away with the Dropdown sub component API in favor of a proper shorthand API.
