### ISSUE TITLE
AutoControlledComponent throws warning in React 16

### ISSUE THREAD

**Issue by apiv** [Semantic-Org/Semantic-UI-React#1761]
### Steps
1) Upgrade to React 16
2) Place any of the `AutoControlledComponent`s in your app

### Expected Result
It should render without warning

### Actual Result
It renders with the warning `Warning: Dropdown.componentWillMount(): Assigning directly to this.state is deprecated (except inside a component's constructor). Use setState instead.`
![screen shot 2017-06-12 at 10 32 06 am](https://user-images.githubusercontent.com/2035141/27039228-5307bba6-4f5b-11e7-93fb-a1375b0d7942.png)

### Version
0.68.5

### Testcase
It seems to be caused by this line: `src/lib/AutoControlledComponent.js:149`. I'll open a PR shortly so we can continue to fully support React 16.

**Comment by levithomason** [comment]
>It seems to be caused by this line: src/lib/AutoControlledComponent.js:149. I'll open a PR shortly so we can continue to fully support React 16.

Awesome, thanks much.

**Comment by layershifter** [comment]
Seems that same problem is here, #1682.
