### ISSUE TITLE
fix(Menu): I type "&" to name of Menu.Item but it is not show

### ISSUE THREAD

**Issue by ChampyW** [Semantic-Org/Semantic-UI-React#1765]
**Steps to Reproduce**
1. I type "&" to attribute name e.g. name={'Black & White'}.

**Expected**
Text in Menu item must show "&".

**Result**
Text in Menu item is not show "&" 

**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/collections/menu#menu-example-colored
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by wangyueming** [comment]
Using content={'Black & White'} rather than name={'Black & White'} works, tested on version 0.71.0.

**Comment by levithomason** [comment]
Indeed. The if no `content` is provided then we `_.startCase` the name and use that for the `content`.  This method removes special characters.

See https://github.com/Semantic-Org/Semantic-UI-React/issues/1340#issuecomment-280720627.
