### ISSUE TITLE
RFC: Form submition

### ISSUE THREAD

**Issue by makarov-roman** [Semantic-Org/Semantic-UI-React#1769]
Hi! Since semantic-ui force us to use Form component as wrapper to Input, TextArea etc, It would cool to set default hof callback to prevent page reload if `action` prop have not provided
```javascript
(e, callback) => {
  !this.props.action && e.preventDefault()
   callback(e)
}
```

**Comment by levithomason** [comment]
This sounds like a great idea, PRs welcome!

**Comment by levithomason** [comment]
PR up.

**Comment by darkadept** [comment]
I'm wondering, does this have anything to do with this error I'm getting? I'm using React Formal (https://github.com/jquense/react-formal) and using it like this:

```javascript
import {default as Formal} from 'react-formal'; //They both have a component called <Form>
import {Form, Button} from 'semantic-ui-react';

class Thing extends Component {
  handleSubmit = (data) => {
  }

  render() {
    return {
      <Form
        as={Formal}
        schema={mySchema}
        onSubmit={this.handleSubmit}
      >
        // fields here...
        <button type="submit">Submit</button>
      </Form>
    }
  }
}
```

When I go to submit I get the following error on the console:

```
Uncaught TypeError: e.preventDefault is not a function
```

Is Semantic UI doing something strange here?

**Comment by layershifter** [comment]
@darkadept Nope, as I see `react-formal` doesn't pass `event` object as the first argument, I don't think that it's correct behaviour. However, I think we can easy fix this to make it compatible with following change in `Form`'s `onSubmit`:
```diff
-if (!action) e.preventDefault()
+if (!action) _.invoke(e, 'preventDefault')
```
