### ISSUE TITLE
Dropdown won't accept defaultValue change!

### ISSUE THREAD

**Issue by FateRiddle** [Semantic-Org/Semantic-UI-React#1772]
https://codesandbox.io/s/pQoyXymr2
Here's the demo. It seems Dropdown only receive defaultValue once, and not changing after, why?

**Comment by FateRiddle** [comment]
Solved. I should use 'value' instead of 'defaultValue'

**Comment by hero9** [comment]
> Solved. I should use 'value' instead of 'defaultValue'

Hi!
Also changed defaultValue to value and then it work's, but when I change value of dropdown it doesn't change. I suppose because of value of dropdown set.
So your solve doesn't fix the problem properly

**Comment by uusa35** [comment]
@FateRiddle thank you for sharing ur answer
