### ISSUE TITLE
Button animated="fade" doesnt work.

### ISSUE THREAD

**Issue by reetou** [Semantic-Org/Semantic-UI-React#1774]
### Steps

I copied code from example here https://react.semantic-ui.com/elements/button#button-example-animated 
Just writing animated prop in button component is working, but if I add animated="fade" prop, button is disappearing.

### Version
semantic-ui-react - 0.68.5
semantic-ui-css - 2.2.10

**Comment by layershifter** [comment]
Docs work fine, please add a codepen and we can investigate problem.

**Comment by reetou** [comment]
Here's my entire component https://codepen.io/anon/pen/NgbZjZ

**Comment by layershifter** [comment]
Please make a minimal example of problem, it seems that it's your local issue. Did you modify SUI's CSS? Make sure that [these](https://github.com/Semantic-Org/UI-Button/blob/master/button.css#L216) CSS classes applied to your buttons.

**Comment by layershifter** [comment]
I will close this issue until we have a codepen that represents a problem with SUIR. Now it looks like a CSS problem or conflict.
