### ISSUE TITLE
Import absolute path of the component

### ISSUE THREAD

**Issue by haotangio** [Semantic-Org/Semantic-UI-React#1776]
I just figured out that `semantic-ui-react` is so heavy, I would like to use the components like
```
import Button from 'semantic-ui-react/Button'
```
instead of
```
import { Button, Form, Input, Menu, Segment } from 'semantic-ui-react';
```
 in a hope to reduce the file size. But this import doesn't work.

Do you have any suggestion?

**Comment by haotangio** [comment]
This is the analytic data for size of the library, it's so big (1.3MB parsed size) and I don't want to import all of the elements to my bundle (I just use a few elements).
![capture](https://user-images.githubusercontent.com/8952752/27235922-cf863a5e-52fd-11e7-90fe-114c9bde9717.PNG)
Do you have any suggestions to deal with this issue?

**Comment by layershifter** [comment]
BTW, [here](https://stackoverflow.com/a/43288212/6488546) is detailed answer how to reduce bundle size.

**Comment by eduludi** [comment]
Why is this issue closed?

**Comment by layershifter** [comment]
Because this problem has a solution and was [answered](https://github.com/Semantic-Org/Semantic-UI-React/issues/1922#issuecomment-319893085) many times?
