### ISSUE TITLE
Mixed content warnings

### ISSUE THREAD

**Issue by amingilani** [Semantic-Org/Semantic-UI-React#1777]
### Steps

Cross posted from https://github.com/Semantic-Org/Semantic-UI/issues/5476

Generate a new react app and install:

```
    "semantic-ui-css": "^2.2.10",
    "semantic-ui-react": "^0.68.5"

```

Use components and serve via HTTPS

### Expected Result

No mixed content errors

### Actual Result

<img width="569" alt="screen shot 2017-06-18 at 9 17 06 am" src="https://user-images.githubusercontent.com/1188552/27258025-dd68e742-5407-11e7-8ace-33ddf9e907a0.png">

### Version

```
    "semantic-ui-css": "^2.2.10",
    "semantic-ui-react": "^0.68.5"

```

### Testcase

https://planetlauncher.com

Source: https://github.com/amingilani/planetlauncher-frontend/

**Comment by layershifter** [comment]
This issue isn't related so SUIR, because we don't handle CSS at all. I also don't see warning at your page, however, SUI imports fonts from `https` and it requires only `Lato` font by default.
