### ISSUE TITLE
List: Header and description are given the same key if their values are the same

### ISSUE THREAD

**Issue by szrharrison** [Semantic-Org/Semantic-UI-React#1778]
## Steps to Reproduce
1. Map over an array in order to create `List.Item`s
2. Give each `List.Item` a header, description, and key via shorthand 
```jsx
    const examples = props.examples.map( example => (
          <List.Item
            key={example.slug}
            as={Link}
            to={`/${props.basePath}/${example.slug}`}
            header={example.instance}
            description={example.instance}
          />
        ))
```

## Expected
The List header and description should be rendered without any errors and with unique keys

## Result
The List threw this error:
```
Warning: flattenChildren(...): Encountered two children with the same key, `example.instance`. 
Child keys must be unique; when two children share a key, only the first child will be used.
```
and only rendered the `header`s for each List.Item

## Suggested Fix
Append/prepend a unique identifier to the key for any HTML element that gets created. E.g: for the header div, the key would become:
```js
key={`${example.instance}h`
```
and for the description div, the key would become:
```js
key={`${example.instance}d`}
```

**Comment by levithomason** [comment]
Shorthand factories can only use the value you provide as the `key`.  There is one factory that powers all shorthand props.

If you need a unique key, please use an object:

```jsx
<List.Item
  header={{ key: 'h', content: example.instance }}
  description={{ key: 'd', content: example.instance }}
/>
```
