### ISSUE TITLE
Modal: nested Modal displays below main Modal

### ISSUE THREAD

**Issue by anthonygreco** [Semantic-Org/Semantic-UI-React#1779]
### Steps
Following the docs example: [https://react.semantic-ui.com/modules/modal#modal-example-multiple](https://react.semantic-ui.com/modules/modal#modal-example-multiple)

### Expected Result
Nested modal should display **above** main modal.

### Actual Result
Nested modal is displayed **below** main modal.

### Version
semantic-ui: ```2.2.10```
semantic-ui-react: ```0.68.5```

### Testcase
Example straight from the docs link above: [https://codepen.io/anthonygreco/pen/KqWKZP](https://codepen.io/anthonygreco/pen/KqWKZP)

Initially, I thought I had an issue with the way I was building the modals (without trigger props; [CodePen here](https://codepen.io/anthonygreco/pen/weJvME)), but discovered the same issue occurred with the docs example -- on CodePen at least -- as it works fine in the docs.

**Comment by layershifter** [comment]
Problem is quite simple, all modals should be rendered inside one dimmer. However, I don't have an awesome idea how to solve this issue.

**Comment by levithomason** [comment]
I don't believe SUI core support multiple modals _with_ multiple dimmers.  Note their example here: https://semantic-ui.com/modules/modal#multiple-modals.  There is only one dimmer.

# Semantic UI
Note a single dimmer is used on the main modal.
![image](https://user-images.githubusercontent.com/5067638/27293611-caacdb3a-54cb-11e7-8048-53c157fe5466.png)


# Semantic UI React

![image](https://user-images.githubusercontent.com/5067638/27412059-ed6d701c-56a6-11e7-9756-641d8d0f3638.png)

**Comment by levithomason** [comment]
The issue is that the `z-index` would need to be adjusted for each consecutive modal.  CSS is beyond the scope of this project.

**Comment by anthonygreco** [comment]
Thanks. Worth noting, in case others land here, I had `dimmer={false}` as a prop for the child modal [here](https://codepen.io/anthonygreco/pen/weJvME) -- removed and working now. The prop has to be entirely absent. Setting to false isn't enough.

**Comment by levithomason** [comment]
@anthonygreco In your example, the child modal must be a literal child of the parent modal.  You'll need to put the child into the `Modal.Content` of the parent.  When this is done, they render correctly:

Fork: https://codepen.io/anon/pen/xrrRee

![http://g.recordit.co/Yyna2jRDqg.gif](http://g.recordit.co/Yyna2jRDqg.gif)

**Comment by scharf** [comment]
> the child modal must be a literal child of the parent modal.

I had a case where that was not enough. Sometimes, the dialog did not show. 

The following code did not (always) work:

```jsx

<a href="javascript:void(0);" onClick={showDialog}>
    Show Dialog
    <MyDialog confirm={confirmCancel}/>
</a>
```

When I turned it upside down (the dialog contained the button/link), then it worked:

```jsx
<MyDialog
    trigger={
        <a href="javascript:void(0);" onClick={showDialog}>
            Show Dialog
        </a>
    }
    confirm={confirmCancel}
/>
```

**Comment by levithomason** [comment]
Modals have new a new CSS layout based on flex box in SUI 2.3. This will change things soon once we update SUIR to support SUI 2.3. Please file new issues for current bugs.
