### ISSUE TITLE
Dropdown: one character cannot be deleted with backspace

### ISSUE THREAD

**Issue by kirillku** [Semantic-Org/Semantic-UI-React#1784]
### Steps
1. Go to [dropdown-example-search-selection](https://react.semantic-ui.com/modules/dropdown#dropdown-example-search-selection)
2. Input some characters to search select
3. Try to delete the characters with backspace
### Expected Result
Search select is empty
### Actual Result
One character stays and cannot be deleted
### Version
0.68.5

### Testcase
[codepen](https://codepen.io/kirillku/pen/EXmBQa)

**Comment by kaikun213** [comment]
Confirmed. Was just about to post the same.

**Comment by layershifter** [comment]
Duplicate, here is PR #1722. There is also a workaround, you can set `minCharacters` to `0`.
