### ISSUE TITLE
Dropdown: problems with minCharacters

### ISSUE THREAD

**Issue by klerkendev** [Semantic-Org/Semantic-UI-React#1787]
### 1. Single select - Not allowing for typing
**Steps**
- Click the placeholder

**Expected Result**
- Able to start typing

**Actual Result**
- Not able to start typing

### 2. Single select - Active selection not greyed out
**Steps**
- Click the dropdown (behind the placeholder)
- Start typing (e.g. 'CDE') and select an option
- Click again

**Expected Result**
- Active selection is greyed out, to indicate that typing is allowed again

**Actual Result**
- Font color remains black

### 3. Multi select - Not allowing for typing at all
**Steps**
- Click the dropdown (doesn't matter where)

**Expected Result**
- Able to start typing

**Actual Result**
- Not able to start typing

### 4. User experience
These two items just don't feel intuitive:

1. There's no indication that there's a minimum number of characters required. You could put instructions outside the dropdown, but I should expect them inside while using the dropdown. Initially you could use the placeholder, but after selecting a value, the instructions are obviously gone.
2. From user perspective the arrow down is frozen most of the time.

### Version
v0.69.0

### Testcase
https://codepen.io/klerkendev/pen/PjKWyK

**Comment by layershifter** [comment]
@klerkendev Thanks for the awesome report, I will work on it tomorrow.

Also, click on `dropdown icon` should always open dropdown.

**Comment by klerkendev** [comment]
Great! It's a great feature that we'd love to use.

Regarding the opening on icon click, I think it shouldn't open always. Maybe it should be disabled/disappear or something like that as long as the minimum number of characters has not yet been entered. In our case there are quite a lot options in the dropdown, so the limitation is necessary in order to not slow down the navigation when it's open.
