### ISSUE TITLE
Modal closeOnDimmerClick mobile device not working

### ISSUE THREAD

**Issue by CarlosOlave** [Semantic-Org/Semantic-UI-React#1800]
I'm using a MODAL to display an image. The modal is configured with closeOnDimmerClick=true and it works as expected in desktop browser. However the modal does not close on mobile desktop browser - I'm looking at iPhone7 mobile device. My current workaround is added closeIcon prop and clicking on the close icon X.

Did a quick search here about a related issue but found nothing. 

### Steps

Setup a simple MODAL 

      <Modal open={this.state.open} closeOnDimmerClick={true} onClose={this.handleClose.bind(this)}>
                <Modal.Content>
                    <img style={{width: '100%'}} src={data.src} />
                </Modal.Content>
            </Modal>

### Expected Result

When clicking on dimmer modal closes

### Actual Result

It does in Desktop browser. It does NOT on mobile device browser

### Version
0.68.5

### Testcase
No test case (sorry)

**Comment by reohjs** [comment]
Touches seem to pass through both dimmer and modal.. you can scroll the page even with them open in both Safari & Chrome 59 (iOS)

**Comment by chainlink** [comment]
Experiencing the same thing would this help? https://github.com/zilverline/react-tap-event-plugin If so I can look at implementing

**Comment by levithomason** [comment]
See https://github.com/Semantic-Org/Semantic-UI-React/pull/1833#issuecomment-313713611.  This is actually Apple's fault :/

**Comment by CarlosOlave** [comment]
Ahh apple!!! Thanks for the info
