### ISSUE TITLE
Country dropdown box, pressing the backspace key will not delete the first character typed in

### ISSUE THREAD

**Issue by jeremyadell** [Semantic-Org/Semantic-UI-React#1805]
✔ BUGS → This form is required:

### Steps
Type single character in country search box.
Press backspace
### Expected Result
The character you typed in should be erased

### Actual Result
First character typed in will not delete

### Version
2.2.10

### Testcase
<Dropdown placeholder='Select Country' fluid search selection options={countryOptions} />

**Comment by layershifter** [comment]
@jeremyadell Please provide the correct version of SUIR and provide codepen or link to docs. The described problem was fixed in `0.70.0`.

**Comment by jeremyadell** [comment]
Thanks for the quick reply.

I was running 0.68.5

Upgrading to 0.70.0 fixed the issue

Appreciate it.

**Comment by layershifter** [comment]
Excellent, thanks for the feedback.
