### ISSUE TITLE
RFC: Dropdown loses the focus on the search input

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#1806]
Extracted from #1795.

Possible I missed something, but the behaviour of our component is different from SUI's. After a click on an item SUI's dropdown still focused while our lost the focus. However, I think that it's correct and we don't need to change something there.

### SUI behaviour

![9fc54ec24746f0c3c35dfc04221fb941](https://user-images.githubusercontent.com/14183168/27509088-3793df48-58fd-11e7-9291-a12a58d72d28.gif)

### SUIR behaviour

![56dd2717a103bfe027625c8b242a3f43](https://user-images.githubusercontent.com/14183168/27509095-50bb2f62-58fd-11e7-8232-9b463c162e8d.gif)

**Comment by levithomason** [comment]
@layershifter is this fixed in `0.72.0`?

**Comment by layershifter** [comment]
No, there was another fix.

[SUI example](https://semantic-ui.com/modules/dropdown.html#search-selection)
[SUIR example](https://react.semantic-ui.com/modules/dropdown#dropdown-example-search-selection)

## Steps
1. Open example
2. Click on dropdown input, it will capture focus
3. Select a dropdown item

SUI example: will select item and keep focus
SUIR example: will select item and lose focus

----

In fact, we need to make a decision what behaviour is correct.

**Comment by sahilfullstack** [comment]
can I implement SUI behavior in SUIR example

**Comment by sahilfullstack** [comment]
@layershifter  @levithomason

**Comment by sahilfullstack** [comment]
@layershifter  @levithomason

**Comment by layershifter** [comment]
Don't spam please. If you have a solution, feel free to contribute and open PR.
