### ISSUE TITLE
Modal unknown properties in Button from actions array

### ISSUE THREAD

**Issue by TroySchmidt** [Semantic-Org/Semantic-UI-React#1813]
### Steps
<Modal basic
                dimmer='blurring'
                trigger={<Icon link name='trash'></Icon>}
                header='Delete Route Batch?'
                content={`Are you sure you want to delete ${props.routeBatch.description}`}
                actions={[
                { key: 'no', content: 'No', color: 'red', triggerClose: true },
                { key: 'yes', content: 'Yes', color: 'green', triggerClose: true, onClick:() => props.deleteRouteBatch(props.routeBatch.routeBatchId) },
                ]}
            />  

### Expected Result
Works but with warning

### Actual Result
Warning about unknown props on Button coming from the actions.  It works as expected.  Now if I change onClick to onActionClick it complains about that property as well.  So it isn't peeling off enough of the properties when it is passing it along to create.

I am using Redux so adding a bunch of properties to the state tree to manage a whole bunch of modal dialogs open state with a property isn't really an efficient / clean solution.  So I like tapping into the triggerClose property but would like for the React 0.15.2 warnings about unknown properties to stop.

### Version
0.70.0

**Comment by layershifter** [comment]
Duplicate, #1642.
