### ISSUE TITLE
Form Select: Set a value

### ISSUE THREAD

**Issue by DnPako** [Semantic-Org/Semantic-UI-React#1816]
Hey,

### Steps
My problem is simple, I'm wondering if there is a way I can set a select value progmatically, the same way as setting a value of input using ref or a similar way. 
### Expected Result
Set a select.
### Actual Result
No available way to do that.
### Version
0.68.5

thanks.

**Comment by layershifter** [comment]
> the same way as setting a value of input using ref or a similar way

If you want to set values you should follow the React's [controlled](https://facebook.github.io/react/docs/forms.html#controlled-components) components pattern. `Form.Select` is a just wrapper around the `Dropdown` so value can be passed as `value` prop:

```jsx
const options = [
  { key: 'm', text: 'Male', value: 'male' },
  { key: 'f', text: 'Female', value: 'female' },
]

const App = () => (
  <Form.Select label='Gender' options={options} placeholder='Gender' value='male' />
)
```
