### ISSUE TITLE
<Reveal /> Component

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#182]
http://semantic-ui.com/elements/reveal.html

**Comment by Jlassos** [comment]
Hey I would like to try tackling this component

**Comment by levithomason** [comment]
Start with the [CONTRIBUTING.md](https://github.com/TechnologyAdvice/stardust/blob/master/CONTRIBUTING.md), you can hit me up on slack if you have any issues!

**Comment by layershifter** [comment]
Are there any activity or I can take it in work?

**Comment by levithomason** [comment]
Bump @Jlassos

**Comment by Jlassos** [comment]
Still working as time permits
