### ISSUE TITLE
Dropdown always open 

### ISSUE THREAD

**Issue by ssageghi** [Semantic-Org/Semantic-UI-React#1824]
Hi 
i used Form and dropdown menu and dropdown is always open 
Expected behaviour:
![image](https://user-images.githubusercontent.com/24605214/27760688-0c7aa182-5e63-11e7-89fb-4c07f5f5000a.png)

actual result :
![image](https://user-images.githubusercontent.com/24605214/27760705-6facf854-5e63-11e7-944a-2bae9854d82d.png)
the div does not have visible and still it's showing 
 I use v 0.70.0

**Comment by layershifter** [comment]
Please provide a codepen.

**Comment by ssageghi** [comment]
i used this ways
`Form.Field>
                <Form.Dropdown fluid placeholder="language" multiple selection={true} options={options} />
            </Form.Field>`
Sorry I don't know how to make a codepen

**Comment by ssageghi** [comment]
[https://codepen.io/anon/pen/gReMWQ](url)
this is my code on localhost 
but it work fine on codepen

**Comment by layershifter** [comment]
You don't need wrap `Form.Dropdown` into `Form.Field`, `Form.Dropdown` is sugar for `Form.Field` + `Dropdown`.

The fact that you can't reproduce the problem with a codepen shows that it is locally. I think it's in CSS, do you use a custom CSS or custom-build of SUI? I saw the similar problem when `transition.css` wasn't included.

**Comment by layershifter** [comment]
Issue can be reopened if we will have more information about problem with SUIR.
