### ISSUE TITLE
Popup: Popup in a Popup closes when you interact with the inner Popup

### ISSUE THREAD

**Issue by kungfoolabs** [Semantic-Org/Semantic-UI-React#1831]
### Steps

- Create a `Popup` in a `Popup` both set to trigger `on` `click`
- When you click in the inner `Popup`, it closes the outer `Popup`.

### Expected Result
- Expect to interact with the inner `Popup` without closing outer `Popup`

### Actual Result
- Outer popup should remain open

### Version
0.70

### Testcase
https://codepen.io/kungfoo/pen/JJZXpQ

**Comment by vritant24** [comment]
Hi. I would like to try solving this bug, if no one else has taken it.

**Comment by layershifter** [comment]
@vritant24 Contributions are welcome 👍
