### ISSUE TITLE
Dropdown: Touch event is not closing/collapsing the dropdown

### ISSUE THREAD

**Issue by hetmann** [Semantic-Org/Semantic-UI-React#1832]
### Description
When the dropdown component is used with mobile touch events the dropdown items list is not closed when touching the outer layer of the component (e.g.: "touchend" event on document or body). This is due to the fact that "touchend" event is not added/listed on componentDidUpdate lifecycle.

### Steps
1. Open the dropdown
2. Touch on outer layer using a mobile device
 
### Expected Result
The dropdown should close on touching the outer layer of the component (document or body) as in web devices when using the mouse & click on the outside layer.

### Actual Result
The dropdown remains open until a value is selected or the dropdown is touched again.

### Version
0.70.0

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codepen.io/hetmann/pen/dRKJwQ

**Comment by levithomason** [comment]
This is actually an iOS design decision, see https://github.com/Semantic-Org/Semantic-UI-React/pull/1833#issuecomment-313713611.
