### ISSUE TITLE
Modal closeIcon is invisible with dimmer='inverted'

### ISSUE THREAD

**Issue by radix** [Semantic-Org/Semantic-UI-React#1838]
Hey semantic-ui-react maintainers! Thanks for the great library, I've been using it to great effect. I'm having a minor issue with Modals with close icons, though. I'm using inverted-dimmer modals so that the dimmer is white instead of black. I recently tried adding a closeIcon to these modals but I couldn't see it, because it seems to be rendering with a white font. It seems like if you're using a dimmer='inverted' and `closeIcon`, it should probably default to swapping the color of the close icon so it's visible?

I'm not sure if this is strictly a CSS issue since it seems like it only comes about through certain combination of features that semantic-ui-react uses together in the `<Modal />` component. But if it is, please let me know and I can file a ticket in the CSS repo.

### Steps

`<Modal dimmer='inverted' closeIcon="close" header="Hello" content="Content" />`

### Expected Result

Visible close icon

### Actual Result

Invisible close icon (white on white)

### Version
semantic-ui-react 0.70.0 
semantic-ui-css 2.2.10

### Testcase
https://codepen.io/anon/pen/GEBjpG

**Comment by radix** [comment]
I'm sorry, I guess it is just a CSS issue. I found it here: https://github.com/Semantic-Org/Semantic-UI/issues/3070

**Comment by lubber-de** [comment]
This is fixed since https://github.com/fomantic/Fomantic-UI 2.6.4
