### ISSUE TITLE
Webpack 3 release: Can we fix the bundle size issue?

### ISSUE THREAD

**Issue by haotangio** [Semantic-Org/Semantic-UI-React#1840]
Webpack 3 released, do we have any plan to fix (or guideline how to fix) the tree shaking issue?

Right now the bundle is too big as it contains all components in 1 import which is very bad for performance on production .

**Comment by layershifter** [comment]
@haotangio Nothing changed, the tree shaking still don't work in webpack 3, so [this answer](https://stackoverflow.com/a/43288212/6488546) is still actually. Also you should use `babel-plugin-lodash`.

**Comment by haotangio** [comment]
Yep, I used that approach to resolve `lodash` issue.
However, `sematic-ui-react` still import all of its component even if I just need to use a `dropdown`.
How can we resolve it?

**Comment by layershifter** [comment]
Please follow notes in [webpack 2](http://react.semantic-ui.com/usage#webpack-2) section, you need to [use](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/examples/webpack2/.babelrc#L8) `babel-lodash-plugin` for SUIR, too.

**Comment by haotangio** [comment]
Hi @layershifter,

Thanks for your suggestion.

I did use `babel-lodash-plugin` for SUIR. However, the bundle still contains all SUIR modules.

```
{
  "plugins": [
    "transform-react-jsx",
    [
      "lodash",
      {
        "id": [
          "lodash",
          "semantic-ui-react"
        ]
      }
    ]
  ],
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": 7
        }
      }
    ],
    [
      "es2015",
      {
        "modules": false
      }
    ],
    "react",
    "babel-preset-stage-3"
  ]
}

```

**Comment by layershifter** [comment]
### With `babel-lodash-plugin`

![image](https://user-images.githubusercontent.com/14183168/28006378-b89c2b84-6557-11e7-881b-832db7bba1c9.png)

### Without `babel-lodash-plugin`

![image](https://user-images.githubusercontent.com/14183168/28006424-e695df1c-6557-11e7-8802-ad7f4b05c070.png)

----

You can use [webpack-bundle-analyzer](https://github.com/th0r/webpack-bundle-analyzer) to gain stats. You should keep in mind, that some of our components are dependent from each other, i.e.:
- `Button` requires `Icon`  and `Label`
- `Label` requires `Icon` and `Image`
- `Image` requires `Dimmer`
- `Dimmer` requires `Portal`.

However, plugin will allow to strip such components as `Rail`, `Reveal` and `Advertisement` if you don't use them.

**Comment by traverse** [comment]
@layershifter Would the `babel-plugin-lodash` also work with DLL builds that include `semantic-ui-react`? Because I'm not seeing any difference using `webpack-bundle-analyzer`.

**Comment by layershifter** [comment]
@Traverse I've tested with minimal config from [there](https://gist.github.com/Eoksni/83d1f1559e0ec00d0e89c33a6d763049) and it's worked.

**Comment by traverse** [comment]
@layershifter I can't seem to get it to work properly. Using the minimal config you provided and `plugin-babel-lodash` still doesn't remove unused components for me.

Bundle analyzer result:

![bundle_result](https://user-images.githubusercontent.com/7240988/28211788-bbb47930-689e-11e7-8a21-202e47677697.JPG)

That's the result I get when only using a header component. I might be doing something wrong but if I knew what I was doing wrong I wouldn't be here. 😉 

Could you _(if you have time)_ provide a fully working example?

**Comment by layershifter** [comment]
@Traverse Oh, I tested again and seems, that you're right :cry: Where did I look? :thinking: 

It's not cool and it won't work with webpack's DLL. I see there only the one way, you can create own `semantic-ui-react.js` and make there reexport of our components:

```js
import { Button, Header } from 'semantic-ui-react'

export Button
export Header
```

`babel-plugin-lodash` will transform it to:

```js
import Button from 'semantic-ui-react/dist/es/elements/Button'
import Header from 'semantic-ui-react/dist/es/elements/Header'

export Button
export Header
```

And you will have only that you need in bundle. Can you check it?

**Comment by traverse** [comment]
I'll try it when I'm back at work which will be Tuesday. 😉

**Comment by raitucarp** [comment]
Also, how do I combine technique in this issue with create-react-app?

**Comment by levithomason** [comment]
Create react app offers zero configuration so you cannot implement these build design decisions. You must "eject" and configure them yourself. Note that ejecting cannot be undone.

**Comment by raitucarp** [comment]
Alright, that's what I mean. The decision to use eject probably not good.

**Comment by haotangio** [comment]
I think SUR team should consider splitting the repo into sub-repo for each ui-component, as most of users won't use ALL semantic-ui components for sure. This approach may help us gain independence from `webpack` and similar dependency issues in the future.

(This is just my idea, I know how painful that splitting process would be.)

**Comment by vrmontes** [comment]
I used https://github.com/Semantic-Org/Semantic-UI-React/issues/2175#issuecomment-339172112
 to avoid having to eject from create-react-app and only import the used semantic-ui react and css, all lodash still there but is good enough for me.

**Comment by cbengtson85** [comment]
@layershifter why is the entire lodash library needed?  You can't be using all the methods... is there anyway when you are bundling the module to only include the lodash methods you are using?

**Comment by brianespinosa** [comment]
@cbengtson85 Webpack's tree shaking will removed any unused methods if you have it set up correctly. This is only a feature of Webpack 2 or better. See this section for notes: https://react.semantic-ui.com/usage#webpack-2

**Comment by cbengtson85** [comment]
@brianespinosa Yep, I have my config set up to use the babel-lodash-plugin and tree shaking I am also directly importing the component ```import Button from 'semantic-ui-react/dist/es/elements/Button/Button.js```.  I have a simple app where I just render ```<Button />``` and the entire lodash library is part of my vendor bundle.  If I remove ```<Button />``` and then the lodash library is not included.

**Comment by brianespinosa** [comment]
@cbengtson85 if tree shaking is working for you then I do not understand your question. If tree shaking is working correctly then when you include the `Button` component, all of Lodash should not be added. Only the methods that are used in `Button` should be imported. If that is not what you are experiencing then tree shaking is not working correctly.

**Comment by cbengtson85** [comment]
@brianespinosa Hmmm it seems to be working correctly as semantic-ui-react is being tree shaken correctly.  The vendor bundle only contains Button and its imports...

**Comment by brianespinosa** [comment]
@cbengtson85 that is not tree shaking. That's just Webpack crawling the import tree. Tree shaking is when a package is updated that contains multiple modules but only the modules that are used in that component get included in the build.

You are directly importing the `Button` component so there's no way Webpack would be importing anything else from SUIR unless you imported those components anywhere else.

Please take a look at the Webpack docs on Tree Shaking for more information on this. https://webpack.js.org/guides/tree-shaking/

I am going to close out this issue now. If it turns out the example in our documentation is not working again for webpack 2+ please open a separate issue for that and @layershifter can take a look at it. I just checked it again and it is the same configuration I have running in my current project and it's working.

**Comment by layershifter** [comment]
In short: don't rely on the tree-shaking, it doesn't work in most cases. There are good chances that `pure` modules will improve this situation.

SUIR uses [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash), it transforms imports to direct. So, we **don't** import full `lodash`, only its parts.

### Full imported `lodash`

![image](https://user-images.githubusercontent.com/14183168/32511436-6bd149ca-c3fc-11e7-8c6b-8a9ca0bb4e34.png)

### `lodash` modules used by SUIR

![image](https://user-images.githubusercontent.com/14183168/32511512-a37de9dc-c3fc-11e7-960e-0d6fa1af1c71.png)
