### ISSUE TITLE
fix(Dropdown): performance issue, useless re-render

### ISSUE THREAD

**Issue by pierrebiver** [Semantic-Org/Semantic-UI-React#1841]
Hello,

I'm using Dropdown to render a list of countries( I have 120 countries). And I Have huge performance issues.
After some investigation via "why did you update" npm package I realised the component was re-render even when props did not change. I check on one of your examples (see below) and it seems to be the same problem.

PS: I'm using version 0.70.0
[https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/Examples/modules/Dropdown/Usage/DropdownExampleAllowAdditions.js]

**Comment by layershifter** [comment]
Dropdown has performance issues and there is issue for this, #1674. Contributions are much appreciated.
