### ISSUE TITLE
Search onResultSelect broken

### ISSUE THREAD

**Issue by jchapuis** [Semantic-Org/Semantic-UI-React#1842]
### Steps
Upgrade to 0.71.0

### Expected Result
User selection still triggers onResultSelect the same way

### Actual Result
Somehow onResultSelect doesn't fill the data property well, the title is an empty string. Just upgrading broke my application.

### Version
0.71.0

**Comment by layershifter** [comment]
`0.71.0` has a breaking change, see #1828.

**Comment by levithomason** [comment]
@jchapuis note that you can find breaking changes in the [CHANGELOG.md](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/CHANGELOG.md).  Under each minor version bump you'll see entries like `breaking(scope): description`.

Refer to the heading in the README.md for more:

>Hey, we're in development. Prior to reaching v1.0.0:
>
>1. MINOR versions represent breaking changes
>2. PATCH versions represent fixes and features
>3. There are no deprecation warnings between releases
>4. You should consult the [CHANGELOG](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/CHANGELOG.md) and related issues/PRs for more information
