### ISSUE TITLE
TextArea: wrong autoHeight counting

### ISSUE THREAD

**Issue by slunecniborecek** [Semantic-Org/Semantic-UI-React#1843]
### Steps

1. create `TextArea` instance with `autoHeight` property
`<TextArea autoHeight />`
2. put a content in there (just keep typing or copy & paste some text); while doing this do not press `<enter>` key

### Expected Result
TextArea grows with the content 

### Actual Result
TextArea keeps the original size; It only grows when pressing `<enter>` key. Actually it only counts newLines * lineHeight (simplified) which is IMO wrong

### Version
0.71.0

### Testcase
https://react.semantic-ui.com/addons/text-area#text-area-example-auto-height

### Contribution
I have a fix ready locally if interested

**Comment by levithomason** [comment]
Confirmed issue. PRs are very much welcome.

**Comment by slunecniborecek** [comment]
@levithomason PR is ready for review

**Comment by slunecniborecek** [comment]
@levithomason thanks for merging. Unfortunately with your last commit you broke the functionality on IE browsers.

steps 1: 
1) copy a long text
2) paste using context menu

steps 2:
1) make text area to grow some height
2) select all text in it
3) using context menu, click 'delete' or 'cut'

Expected:
textarea is resized properly in both steps1 and steps2

Actual:
the height stays
