### ISSUE TITLE
"Built With Semantic UI React" list is outdated

### ISSUE THREAD

**Issue by therealgilles** [Semantic-Org/Semantic-UI-React#1848]
A number of the websites listed in "Built With Semantic UI React" do not use Semantic UI anymore.

- http://stoplight.io uses vue.js
- https://roadmap.space/ uses a divi theme on top of wordpress
- http://www.brewhousesolutions.com/ uses a weebly theme

The list should be reviewed and updated.

**Comment by levithomason** [comment]
Hm, I think you're loading only the home pages.  Typically, static landing pages do not use React.  Most businesses use React for their actual application which is often behind a login.  I did some quick checks and found:

- https://app.stoplight.io/login loads a React app, though may be using custom CSS
- https://app.roadmap.space/#/signin loads a React app that appears to be SUIR
- https://mmmbrew.ophousesolutions.com/login also appears to still be using SUIR

Being that these entries are added by the owners themselves, I'd prefer to have them remove themselves from the list as well.

**Comment by therealgilles** [comment]
Thank you for enlightening me 👍

**Comment by levithomason** [comment]
No worries mate!  Some of these may indeed be outdated and I'm certainly open to correcting it.  I just didn't want to spend too much time trying to figure out what is truly out of date 😛
