### ISSUE TITLE
<Advertisement /> Component

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#185]
http://semantic-ui.com/views/advertisement.html

**Comment by tarang9211** [comment]
@levithomason this is still good to work on right?

**Comment by tarang9211** [comment]
PR for this is here: https://github.com/Semantic-Org/Semantic-UI-React/pull/1292

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.67.1`.
