### ISSUE TITLE
Dropdown: Filtered list resets when using arrow keys

### ISSUE THREAD

**Issue by JulianAnthes** [Semantic-Org/Semantic-UI-React#1858]
### Steps
I'm using a `Dropdown` component. When entering a `searchQuery` and then using the `arrow keys` on my keyboard, the filter resets while cycling. This is only happening when `multiple=false`. In `multiple=true`, everything works properly.

### Expected Result
I would expect the same behavior for both modes.

### Actual Result
The filtered list resets

### Version
0.71.0

### Testcase
[Inside the documentation, scroll to Remote](https://react.semantic-ui.com/modules/dropdown)

[Link to demo video](http://webm.land/media/dLAK.webm)

**Comment by layershifter** [comment]
Will be fixed by #1795, see `Single select, arrows` section. Thanks for the detailed report.
