### ISSUE TITLE
<Card /> Component

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#186]
http://semantic-ui.com/views/card.html

**Comment by eanplatter** [comment]
This is being developed on: #202

**Comment by eanplatter** [comment]
#202 was closed due to api changes, this is not currently under development.

**Comment by levithomason** [comment]
The docs still look good.  You wanna reopen #202 and build it in light of the `<Label />` component for reference?

**Comment by eanplatter** [comment]
I think the branch for that is long gone, I can make a new PR for this though.

**Comment by levithomason** [comment]
Awesome, I just restored the branch as well.

**Comment by eanplatter** [comment]
re-opened, I'll hop on this!

**Comment by levithomason** [comment]
Heads up @eanplatter, @athurman began work on this today.

**Comment by layershifter** [comment]
Closing this issue, because #387 is merged :+1:

**Comment by levithomason** [comment]
Thank ya much!
