### ISSUE TITLE
Tab: browser throwing a warning - getInitialState

### ISSUE THREAD

**Issue by Edrees** [Semantic-Org/Semantic-UI-React#1863]
**Steps to Reproduce**
1. Using the Tab component and importing it to my page

**Expected**
The Tab should do this: there shouldn't be any errors or warnings

**Result**
The Tab does not do this: the browser gives a warning:

> Warning: getInitialState was defined on Tab, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?

The Tab.js (in the semantic-ui-react node_module) is using getInitialState which is not used in ES6
```
getInitialState() {
    return { activeIndex: 0 }
}
```
Could you please help me with this if there is a way to fix this or is changing the syntax to ES6 by using constructor and assigning the state is the only way to go?
Thanks!

**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/modules/tab#tab-example-secondary-pointing
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by layershifter** [comment]
What version of React do you use?

**Comment by Edrees** [comment]
"react": "15.5.4"

**Comment by layershifter** [comment]
Hm, I can't reproduce this on `15.5`, however warning really exists on `15.4`.

I will make PR.

**Comment by Edrees** [comment]
Thanks for your prompt responses! I tried if I can get rid of it by updating react to "15.6.1", but it didn't work and I still have the problem.

**Comment by Edrees** [comment]
@layershifter @levithomason you guys are awesome and thanks for picking up this so fast and fixing it 👍
