### ISSUE TITLE
Dropdown: PropType validation too strict o text prop when using custom content

### ISSUE THREAD

**Issue by brianespinosa** [Semantic-Org/Semantic-UI-React#1864]
When creating custom dropdown content and you want to pass other content into the dropdown's `text` property, you get PropType warnings for passing anything other than a `string`.  *I propose we relax these warnings to not allow only a `string` so we can pass a node instead as in my pen below.*

I am not seeing the PropType warnings in the pen with that markup, but I think that is because we are including the SUIR compiled source from unpkg which I assume has PropType warnings removed.

In the event that there's a different way SUIR expects us to do this, let me know.

### Steps
Create custom `Dropdown` content with `text` prop (see pen).

### Expected Result
No PropType warnings.

### Actual Result
PropType warnings for `string` expected on `Dropdown`'s `text` prop.

### Version
0.71.0

### Testcase
https://codepen.io/brianespinosa/pen/xrMmQN

**Comment by levithomason** [comment]
Use the `trigger` prop for passing an element:

https://react.semantic-ui.com/modules/dropdown#dropdown-example-trigger

**Comment by levithomason** [comment]
FWIW, you can see all kinds of discussion and reasoning as to why this cannot be done with the `text` prop here:

https://github.com/Semantic-Org/Semantic-UI-React/issues/477

**Comment by brianespinosa** [comment]
Thanks @levithomason. I had a feeling I might have missed something here.
