### ISSUE TITLE
Tabs: items missing "key" prop, React warning displayed

### ISSUE THREAD

**Issue by JulianAnthes** [Semantic-Org/Semantic-UI-React#1866]
### Steps
When making use of the Tab component, an react error is shown in the console.

I've implemented the component as shown on the documentation like this
```
const panes = [
  { menuItem: 'Tab 1', render: () => <Tab.Pane attached={false}>Tab 1 Content</Tab.Pane> },
  { menuItem: 'Tab 2', render: () => <Tab.Pane attached={false}>Tab 2 Content</Tab.Pane> },
  { menuItem: 'Tab 3', render: () => <Tab.Pane attached={false}>Tab 3 Content</Tab.Pane> },
]

const TabExamplePointing = () => (
  <Tab menu={{ pointing: true }} panes={panes} />
)
```
**Error in console**
```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Tab`. See https://fb.me/react-warning-keys for more information.
```

### Expected Result
No error should occur 

### Actual Result
:trollface: 

### Version
0.71.0`

### Testcase
[Fork, update, and replace this pen to show the bug]:
http://codepen.io/levithomason/pen/ZpBaJX

Will provide a testcase when needed, just ping me :slightly_smiling_face:

**Comment by levithomason** [comment]
The `panes` array is not rendered by SUIR, so there is no `key` required.  We only use it to call the `render` prop of the pane at the `activeIndex`.

This must be coming from another array on your page.  Will re-open and investigate a minimal working example showing the issue.  Note however that the docs do not show this error when rendered locally.

**Comment by AO19** [comment]
I'm having the same issue, in my case the menuItems do have the same title... So I need to have the key prop, which SUIR does not deliver.

https://codesandbox.io/s/semantic-ui-example-6cqen
