### ISSUE TITLE
Creating a Checkbox or Modal emits an error in the console when using Preact

### ISSUE THREAD

**Issue by rbscott** [Semantic-Org/Semantic-UI-React#1869]
### Steps

1. Using the preact-cli, build a basic project.
1. `npm install --save semantic-ui-react`
1. Add a simple form with a checkbox element anywhere in the project.
Sample code:
```
<Form>
    <Form.Checkbox label='Why the errors?'/>
</Form>
```

1. The following errors show up in the console log.
   1. `Checkbox is missing "defaultChecked" propTypes validation for auto controlled prop "checked".`
   1. `Checkbox is missing propTypes validation for auto controlled prop "checked".`
   1. `Checkbox is missing "defaultIndeterminate" propTypes validation for auto controlled prop "indeterminate".`
   1. `Checkbox is missing propTypes validation for auto controlled prop "indeterminate".`

### Expected Result

No errors are emitted.

### Actual Result

4 errors are emitted.

### Version
0.71.1

### Testcase

Repository is pretty barebones, but had to make a separate project in order to demonstrate the issue.
https://github.com/rbscott/auto-controlled-error

### Notes

I am not sure if Preact is official supported, but it seems to mostly work. If someone points me in the right direction, I could put together a Pull Request.

**Comment by layershifter** [comment]
@rbscott Thanks for report. However, you're right, PReact isn't officially supported. Help there is much appreciated. Warnings are come from [AutoControlledComponent](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/AutoControlledComponent.js#L85), but issue is quite strange.

**Comment by levithomason** [comment]
PRs increasing interop with other libraries are very much welcomed.  Closing for housekeeping as there are no errors with React and this library is intended to be used with React only.

**Comment by levithomason** [comment]
In case it is of help, these are errors for developers that are only logged when `NODE_ENV !== 'production'`.  We check that the `Component.constructor.propTypes` include the necessary keys for the component.  Preact must be doing something to the propTypes so that some are missing.  Namely, the `default*` propType for `checked` and `indeterminate`.

**Comment by rbscott** [comment]
@levithomason thanks for the info. It looks like preact removes prop types for all builds. There is a [PR](https://github.com/developit/preact-cli/pull/259) to change this behavior so it only removes propTypes during production builds. I believe this will resolve this issue.

**Comment by brianjd** [comment]
@rbscott [preact-compat](https://github.com/developit/preact-compat) is the solution you are looking for.
