### ISSUE TITLE
How active accordion when enter key pressed

### ISSUE THREAD

**Issue by SergioDiniz** [Semantic-Org/Semantic-UI-React#1871]
### Steps
hey guys, someone can help me
I need active a accordion when enter key pressed
how can I do that?
the accordion is selected with tab key

### Version
0.64.8

thanks

**Comment by levithomason** [comment]
This is a usage question.  Please Use these dedicated resources:
  Docs - http://react.semantic-ui.com
  Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
  SO - http://stackoverflow.com/search?q=semantic-ui-react
