### ISSUE TITLE
Animate accordion transitions

### ISSUE THREAD

**Issue by Nilesh3105** [Semantic-Org/Semantic-UI-React#1873]
Can we get animated transitions instead of instant ones? Like in the original Semantic-UI? also with a variable `duration` to control the delay?

**Comment by layershifter** [comment]
No, there are no transitions at this moment. `Transition` component is WIP, see #1435.

After it will be merged, we will implement transitions in each component that requires them.

**Comment by Maxhodges** [comment]
why was this closed? It appears to be unimplemented right?

**Comment by levithomason** [comment]
I'd like to have a master list of components that need transitions implemented.  We now have the Transition component complete.  It just needs to be integrated into the components that have transitions.

Would you like to start a new issue for this @Maxhodges or @layershifter?

**Comment by Maxhodges** [comment]
tracked here
https://github.com/Semantic-Org/Semantic-UI-React/issues/2114

**Comment by maverickdude** [comment]
New updates here: #2114
