### ISSUE TITLE
Icon: Some icons are not working

### ISSUE THREAD

**Issue by hubertguillemain** [Semantic-Org/Semantic-UI-React#1880]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - http://stackoverflow.com/search?q=semantic-ui-react

✔ BUGS → This form is required:

### Steps
Try to show the icon "address card", with a simple tag

<Icon name='address card'  size="large"/>

### Expected Result
The address card icon is shown
### Actual Result
Nothing is shown
### Version
0.71.1

### Testcase
In the following codepen, the default arrow-up was replaced by address card icon
https://codepen.io/youbi/pen/jwgrev

Note: in the docs it seems to work !

**Comment by layershifter** [comment]
Please use latest SUI CSS, current is `2.2.11`.

**Comment by hubertguillemain** [comment]
Thanks works !

Thanks for the amazingly fast answer !

Would be worth it updating the sample codepen project suggested in the Gihub issue template if you can 

Thanks again!
