### ISSUE TITLE
fix(Dropdown): your description

### ISSUE THREAD

**Issue by feifeiJun** [Semantic-Org/Semantic-UI-React#1884]
**Steps to Reproduce**
1. click the dropdown to select item
2. select  the subitem

**Expected**
1. The Dropdown should do show the subitem list after click item

**Result**
The Dropdown does not do this.
**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/modules/dropdown#dropdown-example-menu-direction
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by levithomason** [comment]
This appears to be a partially completed issue.  Closing I think it was an accidental submission.  If not, please update the issue with more complete information and a test case and we'll gladly reopen it.
