### ISSUE TITLE
Set Grid.props.columns={12} to 100% of width

### ISSUE THREAD

**Issue by patricksviftnet** [Semantic-Org/Semantic-UI-React#1886]
### Steps

```
<Grid columns={12}>
  <Grid.Row>
    <Grid.Column width={3}>...</Grid.Column>
    <Grid.Column width={6}>...</Grid.Column>
    <Grid.Column width={3}>...</Grid.Column>
  </Grid.Row>
</Grid>
```

### Expected Result

I expect that the columns will now be 100% width, since 12 should be the full amount of columns. (3 + 6 + 3 = 12). 

### Actual Result

Eventhough i set Grid.props.columns to 12, the full with is still calculated to be 16, so the 12 columns are not 100% of the width, but instead 75% of the width.

### Version

0.68.4

**Comment by layershifter** [comment]
Total width of `Grid`/`Grid.Row` is **16**. First of all you should __only__ one prop:
- or `columns` on `Grid` or `Grid.Row`
- or `width` on `Grid.Column`.

`<Grid columns={12} />` will reserve space for 12 `Grid.Column`s, each `Grid.Column` will have width `16/12` of `Grid`.
`<Grid.Column={3}>` will create a column with width `3/16` of nearest `Grid.Row` or `Grid`.

Take a look on [SUI](https://semantic-ui.com/collections/grid.html) docs and [our](http://react.semantic-ui.com/collections/grid) examples.

**Comment by egorshulga** [comment]
@layershifter, this definitely should be added to the documentation. I've stuck with the problem and found it is a feature only in this issue.

**Comment by levithomason** [comment]
@egorshulga I would merge a PR for this.

**Comment by howardya** [comment]
I also encounter this issue. 

So does it mean there is no natural way to have three columns ? Due to the fact that 16/3 is not an integer? If this is the case, would not 12 be better than 16?

**Comment by howardya** [comment]
What I want is that I will have three columns on "computer" and 2 columns on tablet and 1 column on  "mobile".

Do I need to do the following even though the ... is the same?

```jsx
<Grid>
  <Grid.Row columns={3} only="computer">
    ...
  </Grid.Row>
  <Grid.Row columns={2} only="tablet">
    ...
  </Grid.Row>
  <Grid.Row columns={1} only="tablet">
    ...
  </Grid.Row>
</Grid>
```

I tried to use the following but it only works for total columns 16
```jsx
      <Grid.Column mobile={16} tablet={8} computer={4}>
        <Image src='/assets/images/wireframe/paragraph.png' />
      </Grid.Column>
```

**Comment by layershifter** [comment]
@howardya SUI uses 16 column grid, so there is no natural way to have three columns with `width` or responsive props. Only this path:
```jsx
<Grid columns={3} />
<Grid.Row columns={3} />
```

You can also [override](https://github.com/Semantic-Org/Semantic-UI/blob/285a49dd3e88b2adace0e2b320c780855c3a692c/src/themes/default/globals/site.variables#L674) witdh of columns with custom theme and make your grid 12 column.

**Comment by levithomason** [comment]
To be clear, you are not limited to 16 columns, only a max of 16.  You also don't need to update your theme to change the column count nor behavior.

***

### Change the number of Grid columns

You can use a 12 column grid like this:

```jsx
<Grid columns='3'>
  <Grid.Column />
  <Grid.Column />
  <Grid.Column />
</Grid>
```

### Use a dynamic number of columns

Make columns take up equal space, no matter how many there are.

```jsx
<Grid columns='equal'>
  <Grid.Column />
  <Grid.Column />
  <Grid.Column />
</Grid>
```

You can also make individual columns certain widths and the rest will take up equal remaining space.  This works with any number of columns as well:

```jsx
<Grid columns='equal'>
  <Grid.Column width='2' />               {/* takes up 2/16 columns */}
  <Grid.Column style={{ width: 200 }} />  {/* takes up 200px */}
  <Grid.Column />                         {/* takes up what ever is left */}
</Grid>
```

**Comment by howardya** [comment]
Thanks for the suggestions. I need a responsive width, so I guess the following works best for me
```jsx
<Grid>
  <Grid.Row columns={3} only="computer">
    ...
  </Grid.Row>
  <Grid.Row columns={2} only="tablet">
    ...
  </Grid.Row>
  <Grid.Row columns={1} only="tablet">
    ...
  </Grid.Row>
</Grid>
```

**Comment by jacknevitt** [comment]
Out of curiousity, why was 16 picked as the default and maximum? 12 is divisible by 2, 3, 4 and 6 whereas 16 is only divisible by 2, 4 and 8. Unless I'm missing something, this means I can't do columns of 2/3 and 1/3.

**Comment by brianespinosa** [comment]
@jacknevitt you'll want to [ask that question on the core SUI project](https://github.com/Semantic-Org/Semantic-UI) for more clarity on that decision. This React project is intended to replicate markup/functionality of that core project in a React way.

**Comment by webberwang** [comment]
@levithomason 

``` react
<Grid columns='12'>
  <Grid.Column width='4' />
  <Grid.Column width='4' />
  <Grid.Column width='4' />
</Grid>
```

This method doesn't work

**Comment by brianespinosa** [comment]
@webberwang Please open a new issue with what you are trying to accomplish.

For anyone else landing here:

The width of your `Grid` column are either defined by setting the `columns` count on `Grid` or setting the `width` (out of 16) individually on a `Grid.Column`. The `Grid` component also accepts some other responsive values to `columns` like "equal".

`Grid.Row` will also accept the same values as `Grid` if you want to control columns differently by row.

Mixing control between `Grid`/`Grid.Row` and `Grid.Column` is not advised. You need to decide to control width per column, or via the parent row or grid.

If you feel like you need to have a different grid system with a different count of columns and gutter widths, you'll need to build your own CSS with build tools for SUI.
