### ISSUE TITLE
fix(Progress): your description

### ISSUE THREAD

**Issue by brijeshbhakta30** [Semantic-Org/Semantic-UI-React#1892]
**Steps to Reproduce**
1. Just add Progress component.
2. Add bootstrap in the same project.

**Expected**
The Progress should have to original CSS.

**Result**
The Progress does not have a proper UI.

**Cause**
The default class that is added by Semantic-UI is progress and bootstrap also has the same class name which creates a problem for CSS.

**Proposed Solution**
Add prefix all the default className added by Semantic UI.

**Comment by layershifter** [comment]
Semantic-UI-React is not designed to be used in tandem with Bootstrap. You should choose one or the other framework. It is not feasible to prevent all conflicts.
