### ISSUE TITLE
Dropdown: item clipped if positioned right of a Menu

### ISSUE THREAD

**Issue by hubertguillemain** [Semantic-Org/Semantic-UI-React#1897]
### Steps
Create a top menu bar with the last item being a dropdown and with position ="right".
Some of the downdown's items have a long content
### Expected Result
The dropdown is displayed completely and not clipped when expanded
### Actual Result
The dropdown items are clipped and not fully visible
### Version
0.71.1

### Testcase
https://codepen.io/youbi/pen/RZNWjz

**Comment by levithomason** [comment]
The Dropdown currently does not support [menu direction](http://react.semantic-ui.com/modules/dropdown#dropdown-example-menu-direction).  PRs welcome.

### The Fix
We need to add a `direction` prop to the `Dropdown.Menu` which simply adds the `left` className when `direction='left'`.

We then need to also add a `direction` prop to the `Dropdown`.  The `Dropdown` would pass the direction value to the `Dropdown.Menu` when rendering it.  The CSS will then open it on the correct side.

### A Workaround
Adding an inline style to the `Dropdown.Menu` will get the results you need for now:
https://codepen.io/levithomason/pen/XaXjma
```jsx
<Dropdown.Menu style={{ left: 'auto', right: 0 }}>
```

Note that in future versions we are considering deprecating the Dropdown sub component API.  We would then have only props for defining the menu and items.  This will only happen if we can support all features via props, but I wanted to make you aware.

**Comment by mprambadi** [comment]
is the ticket available can i contribute to this issue ?

**Comment by levithomason** [comment]
@mprambadi I've not seen a PR for this yet.  I think you're in the clear.

[Dropdown PRs](https://github.com/Semantic-Org/Semantic-UI-React/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20dropdown)
