### ISSUE TITLE
Dropdown current selection [feature enhancement]

### ISSUE THREAD

**Issue by raptoria** [Semantic-Org/Semantic-UI-React#1899]
Dropdown needs a prop so that you can pass it a current selection. DefaultValue only works the first time the Dropdown is mounted. I need to dynamically pass the dropdown a new selection

**Comment by levithomason** [comment]
You'll need to use the controlled component pattern.  Use `value` to set the currently active item(s).  You'll also need to capture `onChange` to update the value.

React docs: https://facebook.github.io/react/docs/forms.html#controlled-components

SUIR example: https://react.semantic-ui.com/modules/dropdown#dropdown-example-remote
