### ISSUE TITLE
Attribute the icons to FontAwesome

### ISSUE THREAD

**Issue by dkniffin** [Semantic-Org/Semantic-UI-React#1901]
It took me a while, and a little source code digging to find where the icon set was coming from (FontAwesome). It's [mentioned on the other doc site](https://semantic-ui.com/elements/icon.html), but not on the react one. I think it should be added there, and the readme of this repo and the main repo.

**Comment by brianespinosa** [comment]
There are no fonts or styles in this repository. All styles are from Semantic UI proper.

**Comment by dkniffin** [comment]
Yes, but doesn't this repo control this page?: https://react.semantic-ui.com/elements/icon What I'm saying is that page should mention fontawesome, so it's clear where the icons are coming from.

**Comment by levithomason** [comment]
A simple Message up top that notifies the user where icons are from should do.

**Comment by yeskunall** [comment]
Hey @levithomason, should this be added [here](https://github.com/Semantic-Org/Semantic-UI-React/blob/3a09c0fe7c1c5d6daab78304d1c4fc19f9aa022e/src/elements/Icon/Icon.js#L18-L21), or somewhere else? I'd like to make a PR.

**Comment by layershifter** [comment]
@yeskunall I'm sure that it should be added [there](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.71.3/docs/app/Examples/elements/Icon/index.js#L34):

```jsx
<Message>
  Semantic includes ....
</Message>
```
