### ISSUE TITLE
Popup not triggered by custom component

### ISSUE THREAD

**Issue by weijiangan** [Semantic-Org/Semantic-UI-React#1902]
I recently bumped into this problem after I decide to turn some code into their own sub-component.

### Steps
Create a basic React component
```jsx
class Foo extends Component {
  render() {
    return (
      <a href="sdf">sdafsd</a>
    );
  }
}
```
The popup doesn't appear
```jsx
<Popup                  
  trigger={<Foo />}
  content='Comments are coming soon!'
  inverted    
  />
```
but it shows up fine with this
```jsx
<Popup                  
  trigger={<a href="sdf">sdafsd</a>}
  content='Comments are coming soon!'
  inverted    
  />
```

### Expected Result
Popup should appear

### Actual Result
Nothing happens

### Version
I'm using `semantic-ui-css@2.2.11` and `semantic-ui-react@0.71.2`

### Test case
I'm not sure how to make one as I'm not really sure what's the underlying issue :\

**Comment by layershifter** [comment]
Duplicate #1187. There is a simple fix, your component should spread unhandled props:

```jsx
class Foo extends Component {
  render() {
    const { children, ...rest } = this.props
    return (
      <a {...rest} href="sdf">{children}</a>
    );
  }
}
```
