### ISSUE TITLE
Dropdown closes when attempting to focus child input

### ISSUE THREAD

**Issue by stevenleeg** [Semantic-Org/Semantic-UI-React#1905]
### Steps
1) Open the [search in menu](http://react.semantic-ui.com/modules/dropdown#dropdown-example-search-in-menu) example on the docs.
2) Click the "Filter Posts" button
3) Click on the input within the dropdown menu that appears.

### Expected Result
The search input is focused and I am able to enter text

### Actual Result
The dropdown menu immediately closes, preventing me from inputting any text and making me feel sad.

### Version
0.71.2

**Comment by layershifter** [comment]
Duplicate #1593.
