### ISSUE TITLE
Callback data should exclude children

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#1906]
We currently provide `(e, data)` in all callbacks.  This is very useful as the data usually includes props, significant state, and any proposed new values.  However, `children` should be removed.

We should encapsulate the handling of our callback data in a lib function `getCallbackData()`:

**Before**
```js
const data = { ...this.props, checked: !checked, indeterminate: false }
_.invoke(this.props, 'onChange', e, data)
```

**After**
```js
const data = getCallbackData({ ...this.props, checked: !checked, indeterminate: false })
_.invoke(this.props, 'onChange', e, data)
```

### Why?

1. It is an opaque data structure that is not to be touched directly.
2. It is extremely large as it contains the entire tree of ancestors via the `_owner._currentElement` references.
3. There are references to children's `ref`s and `key`s in here, again not something you should be messing with.
***
The motivation for this issue came form using Storybook with the `actions` addon.  The callback args are logged.  They are parsed with a circular JSON safe parser first.  Because the `children` prop is so massive, this gives a huge performance hit.

**Comment by levithomason** [comment]
Thanks to @rijk, we have improved how we handle stale issues, see #2761.   Reopening.

**Comment by layershifter** [comment]
Unstale, please :cat
