### ISSUE TITLE
Inline Loader inside of Modal is inverted

### ISSUE THREAD

**Issue by 4ndv** [Semantic-Org/Semantic-UI-React#1907]
### Expected Result

Non-inverted loader

### Actual Result

Inverted loader

### Version
0.71.2

### Testcase
https://codepen.io/andv/pen/vJNdxy

**Comment by layershifter** [comment]
This is ultimately a CSS issue and this repo only contains React components. Please direct further CSS issues to the main repo https://github.com/Semantic-Org/Semantic-UI.

BTW, issue about this problem has already exists Semantic-Org/Semantic-UI#4014. Also, see #879 for a workaround.
