### ISSUE TITLE
verticalAlign does not function for Grid component

### ISSUE THREAD

**Issue by vmgarcia** [Semantic-Org/Semantic-UI-React#1908]
### Steps
Go to https://react.semantic-ui.com/layouts/login and refresh 

Also does not function on the following codepen https://codepen.io/anon/pen/gxPMjQ

### Expected Result
Login form will remain centered on the page.

### Actual Result
Login form moves to top of page.

### Version
Google Chrome Version 59.0.3071.115
Semantic-UI-React 0.71.2

### Testcase
https://codepen.io/anon/pen/gxPMjQ

**Comment by layershifter** [comment]
I've forked your codepen, [here](https://codepen.io/layershifter/pen/MvjGwM) is a working example. I've added `height: 100%` to the root div and `Container`.

I will make a PR that fixes this in our docs.
