### ISSUE TITLE
Serbian Flag

### ISSUE THREAD

**Issue by ekv88** [Semantic-Org/Semantic-UI-React#1914]
There is a flag: Serbia - CS
Well that flag is just wrong, it's blue/white/red and it was representing some things. Like: We did used it for some very trivial things and had to have flag for some reason, but we actually didn't use it anywhere. So my suggestion is to just remove it.

Serbian - RS flag is fine.

**Comment by layershifter** [comment]
You should post this issue on [Semantic UI](https://github.com/Semantic-Org/Semantic-UI) repository. `.cs` class is [present](https://github.com/Semantic-Org/Semantic-UI/blob/2.2.11/src/themes/default/elements/flag.overrides#L200) in current definitions, so it should present there too.

However, the [CS](https://en.wikipedia.org/wiki/ISO_3166-2:CS) country code and [its flag](https://en.wikipedia.org/wiki/Flag_of_Serbia) is really outdated.
