### ISSUE TITLE
No CSS for Item.Header

### ISSUE THREAD

**Issue by lednhatkhanh** [Semantic-Org/Semantic-UI-React#1915]
The Item.Header has no css (no css is provided for the header class) so it stay the same to the Item.Description:

![image](https://user-images.githubusercontent.com/9303093/28789016-939c69be-764d-11e7-8b0b-58c2116bcdf3.png)

```javascript
<Item
                  header={post.title}
                  description={post.content}
                  meta={post.updatedAt}
                />
```

**Comment by layershifter** [comment]
See [our](https://react.semantic-ui.com/views/item#item-example-items) docs, it seems that you forget to include `Item`'s CSS. Also, make sure that you wrap your `Item`'s into an `Item.Group`.
