### ISSUE TITLE
fix(Dropdown): Filter dropdown close when click input or any item

### ISSUE THREAD

**Issue by samundrak** [Semantic-Org/Semantic-UI-React#1917]
**Steps to Reproduce**
1. Goto https://react.semantic-ui.com/modules/dropdown#dropdown-example-search-in-menu and click of dropdown
2. It will show input and items and  click on input or any item

**Expected**
Dropdown should allow user to enter input to filter or can select multiple item

**Result**
Dropdown is closing when trying to enter something on input or select any items.

**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/modules/dropdown#dropdown-example-search-in-menu
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by samundrak** [comment]
While opening dropdown if you click and hold then you can enter input while holding click.

**Comment by layershifter** [comment]
Duplicate #1593.
