### ISSUE TITLE
Form: add unstackable

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [Semantic-Org/Semantic-UI-React#1919]
Semantic UI supports "unstackable" forms as of 2.2.11. [This issue](https://github.com/Semantic-Org/Semantic-UI/issues/2866) describes the intended behavior.

With Semantic UI 2.2.11 CSS files you can apply unstackable with `className`: https://codepen.io/anon/pen/PKzyQP
It would be nice if this was a prop.

**Comment by layershifter** [comment]
@JamiesWhiteShirt Thanks, this feature is missing in SUI's release notes. I will make a PR today.
