### ISSUE TITLE
<Nag /> Component

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#192]
http://semantic-ui.com/modules/nag.html

**Comment by dcfranca** [comment]
Hi guys, is there any prediction about when Nag will be available?

**Comment by levithomason** [comment]
There have been no takers on it to date.  PRs welcome!

**Comment by jeffcarbs** [comment]
@levithomason - correct me if I'm wrong, but it doesn't seem like this component is fully baked in SUI-core. The docs (http://semantic-ui.com/modules/nag.html) say it's only 60% complete and need documentation (which is fine) and re-coding (which is a red flag, imho). I think we should consider removing from the v1 milestone.

@jlukic - can you confirm whether this is a fully-fleshed component or just an idea still?

**Comment by levithomason** [comment]
Looks correct, going to close this for now since we don't want to chase development versions.  It would be great to have something like this or a toastr type component.
