### ISSUE TITLE
DropDown

### ISSUE THREAD

**Issue by ssageghi** [Semantic-Org/Semantic-UI-React#1920]
Hi 
I didn't find any docs about using drop-down with divider and header 
I change this 
![image](https://user-images.githubusercontent.com/24605214/28864197-0242dea0-7781-11e7-8319-83b85ba26d61.png)
to this
![image](https://user-images.githubusercontent.com/24605214/28864339-7ada9d1c-7781-11e7-9190-0cf60876057c.png)

my problem is when I select the option it doesn't change 
Is it a bug? or I making a mistake?

**Comment by layershifter** [comment]
If you use the subcomponent API, you should manage the state yourself.
The props API doesn't support diveders and menus currently, see #1757.
