### ISSUE TITLE
[Installation] How to install only a few components?

### ISSUE THREAD

**Issue by shankara403** [Semantic-Org/Semantic-UI-React#1922]
Hello, I wish to use only a few components of SUI in my react application. Even if I import only a few components the whole library which is close to 1 MB uncompressed is imported. Is there anyway I can only import an element and its dependencies?

Any help is appreciated! Thank you.

**Comment by layershifter** [comment]
Please post your questions on [SO](https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes&pageSize=50). You can directly import components:

```jsx
import Button from 'semantic-ui-react/dist/commonjs/elements/Button'
```

But recommended way is to use `babel-plugin-lodash`, see #609 and [our](http://react.semantic-ui.com/usage#bundlers) docs. Also see this [reply](https://stackoverflow.com/questions/43255151/semantic-ui-react-webpack-size-is-1-74m/43288212#43288212) on SO.

**Comment by eduludi** [comment]
With

```js
import Button from 'semantic-ui-react/elements/Button'
```
 
I get 
```
Module not found: Error: Can't resolve 'semantic-ui-react/elements/Button' in '...'
```

Does this requires a special Webpack configuration? 

Thanks.

**Comment by layershifter** [comment]
There was a typo, correct:

```js
import Button from 'semantic-ui-react/dist/commonjs/elements/Button'
```
