### ISSUE TITLE
Github Example from https://github.com/Semantic-Org/example-github

### ISSUE THREAD

**Issue by marcellodesales** [Semantic-Org/Semantic-UI-React#1924]
Has anyone implemented the Github Example using React? 

This is really what I need for an internal project... https://github.com/Semantic-Org/example-github

Thank you!

**Comment by layershifter** [comment]
This example utilizes SUI's [theming](https://semantic-ui.com/usage/theming.html), I don't see there anything that can't be implemented with SUIR. You can check our [layout](http://react.semantic-ui.com/layouts) examples.
