### ISSUE TITLE
IE: TextArea: wrong autoHeight counting

### ISSUE THREAD

**Issue by slunecniborecek** [Semantic-Org/Semantic-UI-React#1925]
Based on https://github.com/Semantic-Org/Semantic-UI-React/issues/1843 which was closed. Unfortunately the very last commit contains an issue in IE browsers

**steps 1:**
copy a long text
paste using context menu

**steps 2:**
make text area to grow some height
select all text in it
using context menu, click 'delete' or 'cut'

**Expected:**
textarea is resized properly in both steps1 and steps2

**Actual:**
the height is not changed

**Comment by slunecniborecek** [comment]
@levithomason ^

**Comment by levithomason** [comment]
Thanks for the follow-up.  Looks like we'll need to use the `onInput` method for IE.  When this is done, we'll need to also update the callback signature to follow our conventions.  See the `onChange` propType description and handler for that pattern.

**Comment by nickpedersen** [comment]
Could I help out with this one? I can prepare a PR right now
