### ISSUE TITLE
fix(Dropdown): your description

### ISSUE THREAD

**Issue by gregor-mueller** [Semantic-Org/Semantic-UI-React#1927]
**Steps to Reproduce**
1. Have a Dropdown with a Search or Input as Dropdown.Item
2. Open the Dropdown
3. Click into the Input

**Expected**
The Dropdown should stay open

**Result**
The Dropdown instantly closes

**Testcase**
See in example: https://react.semantic-ui.com/modules/dropdown#dropdown-example-search-in-menu

**Hint**
If you hold down the mouse button and move out of the Input before releasing it, the Dropdown will stay open and you can start typing (so only full click on Child does close the Dropdown here).

**Bonus Gif**
![dropdown_close_on_search_click](https://user-images.githubusercontent.com/28727932/28930531-90debfec-7873-11e7-932d-a49a8dea155e.gif)

**Comment by levithomason** [comment]
Please note the message above the example.  Dropdown state is not self-managed when using the subcomponent API.  We need PRs extending the shorthand API so that it can generate the same markup but with self-managed state.

See #1757 for the latest on this work.
