### ISSUE TITLE
Multilevel Nested Dropdowns

### ISSUE THREAD

**Issue by Smaxor5** [Semantic-Org/Semantic-UI-React#1928]
Hi everyone, very new to posting a bug like this but I'm having some trouble getting Nested dropdowns to work with this and am wondering if they are even supported.  I have a JSON that is given to the component I built to determine the necessary dropdown hierarchy.  Here is the code being run, ill attach the JSON.

<Dropdown item simple text='Dropdown'>
                        <Dropdown.Menu>
                            {props.items.map((item)=> {
                                return(
                                <Dropdown.Item>
                                    <i className='dropdown icon' />
                                    <span className='text'>{item.title}</span>
                                     <Dropdown.Menu>
                                        {item.categories.map((item2)=>{
                                            return (
                                                <Dropdown.Item>
                                                    <i className='dropdown icon' />
                                                    <span className='text'>{item2.title}</span>
                                                    <Dropdown.Menu>
                                                        {item2.subcategories.map((item3)=> {
                                                            return (
                                                                <Dropdown.Item>
                                                                    <i className='dropdown icon' />
                                                                    <span className='text'>{item3.title}</span>
                                                                      <Dropdown.Menu>
                                                                        {item3.dashboards.map((dashboard)=>{
                                                                            return (
                                                                                <Dropdown.Item>
                                                                                    <span href={dashboard.href} className='text'>{dashboard.title}</span>   
                                                                                </Dropdown.Item>
                                                                            )
                                                                        })}    
                                                                    </Dropdown.Menu>
                                                                </Dropdown.Item>
                                                            )
                                                        })}
                                                    </Dropdown.Menu>
                                                </Dropdown.Item>
                                            )
                                        })}
                                    </Dropdown.Menu> 
                                </Dropdown.Item>
                                )
                            })}
                        </Dropdown.Menu>
                    </Dropdown>

This should result in a dropdown that would have Operational Intelligence -> Water -> etc etc.  Unfortunately it just stops at Water and refuses to drill anything further.  Apologies if this issue is formatted terrible...pretty new at this!

Thanks!

[DropdownJSON.txt](https://github.com/Semantic-Org/Semantic-UI-React/files/1197809/DropdownJSON.txt)

**Comment by brianespinosa** [comment]
Hi @Smaxor5,

Currently the Dropdowns shorthand API does not support nested menus the way you are trying. There are open discussions on the progress of adding support for it but they are not yet released.

Some notes about this are in the Dropdowns area of the documentation: https://react.semantic-ui.com/modules/dropdown#dropdown-example-menu-direction.

**Comment by layershifter** [comment]
I close this in favor of another issues.
