### ISSUE TITLE
Can not using systemjs to load component

### ISSUE THREAD

**Issue by SolardiaX** [Semantic-Org/Semantic-UI-React#1930]
I'm using systemjs in my new project with SUI.
SystemJS.config using semantic-ui-react.min.js for 'semantic-ui-react' map.
And add special mapping for 'React' and 'ReactDOM' used by semantic-ui-react.min.js

Following script will got error: **Error: Cannot read property 'Field' of undefined**

```javascript
import React from 'react';
import { Form, Input } from 'semantic-ui-react';

export class FormEditor extends React.Component<{}, {}> {
    public render(): JSX.Element | null {
        return (
            <div className='groupbox'>
                <div className='groupbox-header'>
                    <strong>Info Editor</strong>
                </div>
                <div className='groupbox-content'>
                    <Form>
                        <Form.Field inline>
                            <label>Title</label>
                            <Input placeholder='The Title' />
                        </Form.Field>
                    </Form>
                 </div>
            </div>
        );
    }
}
```

**Comment by layershifter** [comment]
I'm not familiar with `systemjs`. If you want to get help, you need to create a minimal  repository that reproduces the described problem. But keep in mind that it will not be a high priority issue.

However, I'm almost sure that imports doesn't work because `Form` is undefined.

**Comment by layershifter** [comment]
Closing for housekeeping.
