### ISSUE TITLE
fix(Grid): Doubling doesn't reduce to single column

### ISSUE THREAD

**Issue by ericis** [Semantic-Org/Semantic-UI-React#1931]
**Steps to Reproduce**
1. https://react.semantic-ui.com/collections/grid#grid-example-doubling
2. Resize the window to very small

**Expected**
The Grid should reduce to one column.

**Result**
The Grid only reduces to 2-column and begins to horizontally scroll. Is this expected? I expected reducing to 1-column.

**Testcase**
Docs show the issue, use: https://react.semantic-ui.com/collections/grid#grid-example-doubling

**Comment by ericis** [comment]
This link appears to work with responsive desktop, but no emulated mobile devices:
https://react.semantic-ui.com/layouts/grid

Using Chrome Dev Tools and Device emulation, switching to iPhone 6 in portrait mode and refreshing the page doesn't show responsive changes.

![react semantic-ui com- iphone 6](https://user-images.githubusercontent.com/974919/28979824-464de678-7919-11e7-89f7-18ca4adb2568.png)

**Comment by layershifter** [comment]
[Duplicate](https://github.com/Semantic-Org/Semantic-UI-React/issues/1932#issuecomment-320308768), #1932.
