### ISSUE TITLE
Web Docs are not formated correctly in Firefox.

### ISSUE THREAD

**Issue by CodeAmend** [Semantic-Org/Semantic-UI-React#1933]
✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - http://stackoverflow.com/search?q=semantic-ui-react

✔ BUGS → This form is required:

### Steps
Use Firefox.
Go to ANY semantic react component such as:
https://react.semantic-ui.com/views/card#card-example-groups

And click view code Sample.

### Expected Result
Expect the code window to be fully expanded to the container.

### Actual Result
Does not expand and you have to scroll to see it all.

### Version
Sorry, I do not know where to put this. It is a website error.
[https://i.imgur.com/X1Yf816.png](url)

**Comment by layershifter** [comment]
Duplicate, #1912.
