### ISSUE TITLE
Dropdown: keyboard navigation in non-search Dropdown

### ISSUE THREAD

**Issue by allthesignals** [Semantic-Org/Semantic-UI-React#1935]
### Steps
Click dropdown, type "P"

### Expected Result
Dropdown selects "Products"

### Actual Result
Dropdown does nothing

### Version
0.71.3

### Testcase
https://codepen.io/anon/pen/yogpVR

Semantic vanilla seems to support this: https://semantic-ui.com/modules/dropdown.html#selection.

**Comment by damienleri** [comment]
This is a really annoying UX bug, does anyone have ideas for a solution or workaround, other than not using Semantic-react for Selects? The html <select> tag is hidden so I guess keyboard events would need to be bound at the level of <div role="listbox"..>

**Comment by levithomason** [comment]
### Workaround 

1. Capture `onKeyDown`
1. Find the option with `text` that starts with the pressed `key`
1. Set the `value` to the option's `value`

Working example:
https://codepen.io/levithomason/pen/VMvEzX

⚠️ Note, `key` (used in the codepen) is not fully supported in all browsers.  It is the defacto key identifier moving forward.  Semantic UI React contains a utility for handling it crossbrowser.  That will be used when we implement this.
