### ISSUE TITLE
Checkbox onClick provides wrong data [onChange works fine]

### ISSUE THREAD

**Issue by niiapa** [Semantic-Org/Semantic-UI-React#1936]
✔ BUGS → This form is required:

### Steps
Check or uncheck a checkbox

### Expected Result
Checked empty checkbox returns true for 'checked' value in data params and vice versa

### Actual Result
onClick registers too early and the 'checked' value is what is was prior (inverse of truth) 

### Version
0.71.3

### Testcase
Toggle a checkbox and view the data params for checked. It's the inverse of what it's supposed to be. I'm assuming the onClick event registers before it actually changes.

**Comment by layershifter** [comment]
I think that current behaviour is correct. `onClick` represents only `click` event and changes nothing, while `onChange` represents the state change.

I'll left this issue open, possible @levithomason has another opinion.

**Comment by levithomason** [comment]
The order of events is correct and the `onChange` handler should be used instead.  However, comparing this to vanilla React with an `<input type='checkbox' />`, both `onClick` and `onChange` events return `e.target.checked === true` when clicking a controlled input.

We should update ours to behave identically:

- create an unchecked Checkbox
- user clicks Checkbox
- `onClick` fires with `checked: true` (the proposed new value)
- `onChange` fires with `checked: true` (the proposed new value)

**Comment by areinmeyer** [comment]
I just ran across this issue as well.  I'd be interested in trying out a PR for this and will try to put one together for it this week.
