### ISSUE TITLE
Modal has inconsistent behavior after added controlled state to the open prop

### ISSUE THREAD

**Issue by eldyvoon** [Semantic-Org/Semantic-UI-React#1937]
The Modal cannot be closed when I click on the dimmer area, before I use state for the open prop, the dimmer worked just fine. I tried to add closeOnDimmerClick prop but no luck too.

### Steps
Pass state as props to Modal component, the Modal cannot be closed clicking on the dimmer area.
### Expected Result
Modal component should behave like before
### Actual Result
https://codesandbox.io/s/RgvpVxZ4O
### Version
0.71.3
### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/RgvpVxZ4O

**Comment by layershifter** [comment]
Modal implements [uncontrolled](https://facebook.github.io/react/docs/uncontrolled-components.html) behaviour by the `trigger` prop and [controlled](https://facebook.github.io/react/docs/forms.html#controlled-components) by the `open` prop.

I've [modified](https://codesandbox.io/s/kRng402mv) your code to work correctly. See docs for [uncontrolled](https://react.semantic-ui.com/modules/modal#modal-example-modal) and [controlled](https://react.semantic-ui.com/modules/modal#modal-example-controlled) examples.

**Comment by eldyvoon** [comment]
@layershifter No wonder. But the Confirm component isn't working that way. Anyway thanks!
