### ISSUE TITLE
Tab.Pane unknown prop warning when using as='div'

### ISSUE THREAD

**Issue by dfilipidisz** [Semantic-Org/Semantic-UI-React#1941]
### Steps
1. Use Tab.Pane with ```as='div'```:
```js
<Tab.Pane as='div'>Tab1</Tab.Pane>
```
2. Receive react warning:
```
Warning: Unknown prop `loading` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

### Expected Result
Not to receive the warning.

### Actual Result
Warning displayed.

### Version
0.71.3

### Testcase
https://codepen.io/dfilipidisz/pen/yoMBRe

**Comment by levithomason** [comment]
Thanks, PR open.  This was an old design artifact.  You can safely ignore the warning as it causes no harm to your app.
