### ISSUE TITLE
Step: Step.Group with unstackable prop generates incorrect classname

### ISSUE THREAD

**Issue by aert** [Semantic-Org/Semantic-UI-React#1942]
Just a small typo in the `Step` component : an invalid comma is added to the generated html class for `unstackable`
The issue is here: https://github.com/Semantic-Org/Semantic-UI-React/blob/dc403d0094cc79afe3633413b6b834fc66cad88b/src/elements/Step/StepGroup.js#L38

### Steps

1. Run `<Step.Group unstackable />`

### Expected Result

In generated html : `class="unstackable"`

### Actual Result

In generated html : `class="unstackable**,**"`

### Version
0.71.3

### Testcase
[Fork, update, and replace this pen to show the bug]:
http://codepen.io/levithomason/pen/ZpBaJX

**Comment by layershifter** [comment]
@aert Thanks for report. PR for this will be awesome :+1:

**Comment by Joel-Raju** [comment]
submitted a [PR](https://github.com/Semantic-Org/Semantic-UI-React/pull/1943)

**Comment by aert** [comment]
Thank you @joel-raju

**Comment by aert** [comment]
Thanks to you @layerfixer
