### ISSUE TITLE
Popup: component should support a dimmer property

### ISSUE THREAD

**Issue by davewthompson** [Semantic-Org/Semantic-UI-React#1945]
It would be nice if the Popup control could support a dimmer, so that a large popup can grab user attention such as a main navigation menu.

**Comment by layershifter** [comment]
As I remember, there are no such feature in SUI.

It will be awesome if someone impliment it, however it will be not a high priority for core team.

**Comment by davewthompson** [comment]
A modal would be centred while the dropdown is relatively to the triggering component.

On Aug 11, 2017 11:49 AM, "Levi Thomason" <notifications@github.com<mailto:notifications@github.com>> wrote:

Why not use a Modal?

**Comment by levithomason** [comment]
Oh, of course :) If the zIndex of the Dimmer plays nicely with Popups in this way, we might be able to support this.

Another feature (beyond the scope of our project) which may be helpful to you is to also keep the element that the popup is pointing to visible.  This way the user can see the Popup and the element only.  If so, you may be interested in something like https://github.com/gilbarbara/react-joyride.

I'm still up for a PR adding basic Dimmer support to the Popup and seeing how it goes.  The Modal `dimmer` prop logic can be duplicated for this.
