### ISSUE TITLE
Credit Card icon is adding "card" class to css.

### ISSUE THREAD

**Issue by quinnvaughn** [Semantic-Org/Semantic-UI-React#1957]
Both the credit card icon and credit card alternative have a small grey border when generated, as if they're being treated as < Card /> components.

![credit_card1](https://user-images.githubusercontent.com/9911021/29236063-5f1e29e4-7ecb-11e7-94df-b8f71f902085.png)

![credit_card2](https://user-images.githubusercontent.com/9911021/29236064-5f1ef5ea-7ecb-11e7-8e6a-6fd795a834be.png)

**Comment by levithomason** [comment]
Could you complete all the required fields in the issue template, please?  I cannot tell what you are expecting the result to be.  We also need to know which version and have a codepen to investigate.

The only thing I can say right now is that the `card` class is expected for both the `<Card />` and `<Icon name='credit card' />`.

**Comment by layershifter** [comment]
Closing for housekeeping.
