### ISSUE TITLE
Docs: Cannot access the site

### ISSUE THREAD

**Issue by guxi11** [Semantic-Org/Semantic-UI-React#1958]
### Steps

visit http://react.semantic-ui.com

### Expected Result

access the docs

### Actual Result

get a blank page and errors:
[Error] Failed to load resource: The request timed out. (vendor.0d08050bb3e6e692bae7.js, line 0)
[Error] Failed to load resource: The request timed out. (app.b81b0a758e41a3857a51.js, line 0)

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
http://codepen.io/levithomason/pen/ZpBaJX

**Comment by levithomason** [comment]
Duplicate #1870

See that issue for more details and discussion.
