### ISSUE TITLE
Feature request: context prop to Visibility component

### ISSUE THREAD

**Issue by frogbandit** [Semantic-Org/Semantic-UI-React#1959]
Apologies if this is not the right forum to make this request, but it would be great to have a `context` prop for the Visibility component, much like you can change the `context` in Semantic UI: https://semantic-ui.com/behaviors/visibility.html#/settings. 

For example. I want to change the `scroll` event listener to listen on the scroll of a surrounding <List> component (i.e. a component which has a height less than the window height, but has an overflow so is scrollable). 

Currently, when this component is scrolled, none of the Visibility component's props fire because it does not think that the window is being scrolled. 

Thanks!

**Comment by levithomason** [comment]
Yep, we should accept a component and/or DOM node for this.  Note, we should also use the `<Ref />` component from #1879 in order to ensure we can get the DOM node from components passed in.

**Comment by mariolamacchia** [comment]
There is the same issue on the Sticky (#1747), I can fix both of them. 

@levithomason I would just add a prop that accepts an HTML element. Or do you think of something different using `<Ref />`?

**Comment by index01d** [comment]
Server rendering was broken

```
/node_modules/semantic-ui-react/dist/commonjs/behaviors/Visibility/Visibility.js:260
  context: window,
           ^

ReferenceError: window is not defined
    at Object.<anonymous> (/node_modules/semantic-ui-react/dist/commonjs/behaviors/Visibility/Visibility.js:260:12)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/semantic-ui-react/dist/commonjs/behaviors/Visibility/index.js:8:19)
```

**Comment by frogbandit** [comment]
Hi there, thank you for adding the context prop for the Visibility component! :+1: :+1: for moving so fast on this.

However, I've tried using it and `context` doesn't seem to accept either a React ref or an HTML element. I took a look at the source code and it's just supposed to be a `PropTypes.object`. Can you give some more info on how to use it? i.e. what kind of element should be passed in.

**Comment by mariolamacchia** [comment]
@frogbandit `context` and `scrollContext` accept an html element. [Here](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/Examples/modules/Sticky/Types/StickyAdjacentContextExample.js) is an example of how to use `context` with Sticky.

Beware that React does not support using `ref` on stateless components.

**Comment by levithomason** [comment]
@frogbandit @mariolamacchia Note we are adding a `Ref` component that will enable SUIR to support React elements everywhere we support DOM nodes.  This includes stateless functional components.  I responded here https://github.com/Semantic-Org/Semantic-UI-React/pull/1978#issuecomment-326746794 as well.  You can see #1879 for the work being done.

**Comment by sbrouil** [comment]
@levithomason with the current implementation v0.76.0 on Visibility component scroll event are only atteched to the context property in componentDidMount() so it doesn't work well when the context is changed. 
```javascript
    handleContextRef = (contextRef) => this.setState({ contextRef })

    render() {
        const { contextRef } = this.state; // contextRef is undefined no first render() call
        return (
            <div ref={this.handleContextRef}  style={{ height: 700, overflowX: 'auto' }} >
                <div style={{ height: 1200 }} />

                <Visibility
                    context={contextRef}
                   ...
            <div>
         );
     }
```
A workaround is to add a check on contextRef so that Visibility component is only mounted when contextRef is defined.
```javascript
    render() {
        const { contextRef } = this.state; // contextRef is undefined no first render() call
        return (
            <div ref={this.handleContextRef}  style={{ height: 700, overflowX: 'auto' }} >
                <div style={{ height: 1200 }} />
               { contextRef &&
                <Visibility
                    context={contextRef}
                    ...
               }
            <div>
         );
     }
```

**Comment by layershifter** [comment]
If you have an issue, create a new issue.
