### ISSUE TITLE
react warning props `input`, `meta` on <div> tag in Form.Select

### ISSUE THREAD

**Issue by dmitrymalakhov** [Semantic-Org/Semantic-UI-React#1961]
I use Form.Select with Field of redux-form and get warning

![screenshot from 2017-08-14 15-48-29](https://user-images.githubusercontent.com/2477267/29272457-d700eade-8108-11e7-8a0e-997d3f45bb39.png)

**Comment by layershifter** [comment]
Could you complete all the required fields in the issue template, please? We also need to know which version and have a codepen to investigate.

**Comment by levithomason** [comment]
We can reopen upon receiving more info.
