### ISSUE TITLE
Menu.Item - disabled=true - onClick still firing...intentional?

### ISSUE THREAD

**Issue by harmon25** [Semantic-Org/Semantic-UI-React#1964]
### Steps
MenuItem with prop `disabled=true` - the onClick event is being triggered.

### Expected Result
When a menu item is disabled, and onClick is fired - internally the MenuItem component should override the onClick prop with an empty anonymous function - effectively `disabling` the menu item.

I have done the following as a work around - however I believe it should be handled internal to the Menu.Item component.
```
<Menu.Item disabled={activePageIndex === pages.length - 1}
    onClick={
      activePageIndex === pages.length - 1
      ? () => {}
      : this.handleNextPage}  
/>
```
### Actual Result
onClick is being fired on `disabled` menu items. Requiring the above pattern to 'disable' the onClick handler.

Is this intentional to handle some kind of edge cases?
Thoughts?

### Version
0.71.4

### Testcase
https://codepen.io/harmon25/pen/GvMdow

**Comment by layershifter** [comment]
It looks confusing, but what if you need to handle `onClick` on disabled item? [`Button`](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.71.4/src/elements/Button/Button.js#L186) has a same behaviour, it calls `onClick` handler in all cases and I think that it's correct.

You can make a simple workaround for this:

```jsx
const onClick = (e, props) => {
  const { disabled } = props

  if(disabled) return
  // do something...
}

<MenuItem disabled onClick={onClick} />
```

I will left this open until @levithomason will comment this, possible he has another thoughts about this.

**Comment by levithomason** [comment]
We want to maintain as much parity with vanilla React and HTML as possible.  It appears we need to skip only call the handlers when not `disabled`:

```jsx
<button onClick={() => alert('fires?')} disabled>Nope</button>
```

Note, we should update all components that accept a disabled prop (there aren't many).
