### ISSUE TITLE
Stackable not working for <Card.Group>

### ISSUE THREAD

**Issue by ShocKwav3** [Semantic-Org/Semantic-UI-React#1966]
**Steps to Reproduce**
<Card.Group stackable={true}> //stuff </Card.Group>

**Expected**
Stacked when resize

**Result**
Reduces to 3 per row and no further

Any ideas how to make it work? :)

**Comment by layershifter** [comment]
Could you complete all the required fields in the issue template, please? We also need to know which version and have a codepen to investigate.

However, I almost sure that you haven't define a [viewport](https://webdesign.tutsplus.com/articles/quick-tip-dont-forget-the-viewport-meta-tag--webdesign-5972).
