### ISSUE TITLE
Clicking on label does not focus input field

### ISSUE THREAD

**Issue by iwllyu** [Semantic-Org/Semantic-UI-React#1968]
### Steps
Create Form.Input with label

### Expected Result
clicking on label will focus the input field

### Actual Result
clicking on label does nothing

### Version
https://unpkg.com/semantic-ui-react@0.71.4/dist/umd/semantic-ui-react.min.js

### Testcase
https://codepen.io/anon/pen/jLarrp?editors=0010

### Suggested Fix
if Form.Input has an id, that id should be copied to the label `htmlFor` property

**Comment by levithomason** [comment]
The suggested fix is currently what is supported by Semantic UI React.  Your codepen does not have an `id` on `Form.Input`.   Here's a working fork where I added an `id` to the `Form.Input`:

https://codepen.io/anon/pen/JyOKBK?editors=0010

**Comment by iwllyu** [comment]
thanks, sorry about the noise

**Comment by levithomason** [comment]
No worries!  I appreciate the complete report none the less.
