### ISSUE TITLE
<Sidebar /> Component

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#197]
http://semantic-ui.com/modules/sidebar.html

**Comment by UnbrandedTech** [comment]
@levithomason Has anyone picked this up? I'd be willing to jump in if no one else is doing it.

**Comment by levithomason** [comment]
This one is up for grabs!

If you haven't already, read through the contributing guide for a walk through on how we go about adding a new component. It reads like a step by step manual. You can also reference other recent new component PRs. 

Cheers!

**Comment by UnbrandedTech** [comment]
Should the discussion about implementation happen here or on the PR?

**Comment by levithomason** [comment]
Yes sir.

**Comment by kevflynn** [comment]
@UnbrandedTech you grinding on this?

**Comment by jeffcarbs** [comment]
I think per https://github.com/Semantic-Org/Semantic-UI-React/pull/774#issuecomment-260376943 this issue is back up for grabs.

**Comment by levithomason** [comment]
See #905 for the latest run at this, looking really good.

**Comment by neekey** [comment]
Hi, is Sidebar already released? I found this module in the docs but not in my local downloaded node module.

**Comment by levithomason** [comment]
Yep, install the latest. Also note, the docs use the latest release themselves. So, whatever is in the docs is the latest library.
