### ISSUE TITLE
Input: 'focus' method does not exist in typings

### ISSUE THREAD

**Issue by InExtremaRes** [Semantic-Org/Semantic-UI-React#1970]
### Steps

This example was tested using [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript)

```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Input } from 'semantic-ui-react';

ReactDOM.render(
    <Input ref={(i) => { if (i) { i.focus(); } }} />,
    document.getElementById('root') as HTMLElement
);
```

### Expected Result
It compiles and work.
The same example works with Babel using ES6 only (no TypeScript, as with [create-react-app](https://github.com/facebookincubator/create-react-app)).

### Actual Result
It fails to compile with error:

```
(6,37): error TS2339: Property 'focus' does not exist on type 'Component<InputProps, ComponentState>'.
```
### Version
0.71.4
(React 15.6.1)

**Comment by InExtremaRes** [comment]
I do not test but it's very likely that `focus` method does not exist in others typings as well (as `Button`, for instance).

**Comment by layershifter** [comment]
@InExtremaRes Thanks for notice, `TextArea` has `focus`, too. I've updated PR.
