### ISSUE TITLE
Accordion component performance

### ISSUE THREAD

**Issue by LeoAref** [Semantic-Org/Semantic-UI-React#1971]
I was benchmarking my application, and I found that we have a performance problem in the Accordion component:

<img width="841" alt="screen shot 2017-08-16 at 07 06 28" src="https://user-images.githubusercontent.com/6577222/29348101-768a7824-8251-11e7-9bad-b303093ad595.png">

It's not a big deal so far, but using it in more places will increase the wasted rendering time, I found some issues for refactoring the Accordion component, but I'll try to create small PR to fix that

**Comment by layershifter** [comment]
There is PR for Accordion refactor #1375, performance improvements are always welcome. However, I will close this issue, because it's a not priority for core team until `1.0` will be reached.

**Comment by ghost** [comment]
@LeoAref what is that table? Where it come from? Any performance tool?
