### ISSUE TITLE
fix(Form): setState is not a function

### ISSUE THREAD

**Issue by Cicko** [Semantic-Org/Semantic-UI-React#1974]
**Steps to Reproduce**

I am using electron to create a desktop app with semantic and react. All works fine but something very strange happen with the following code:

```jsx
import $ from 'jquery'

import React, { Component } from 'react'
import { Button, Checkbox, Form, Input, Radio, Select, TextArea } from 'semantic-ui-react'

const options = [
  { key: 'm', text: 'Male', value: 'male' },
  { key: 'f', text: 'Female', value: 'female' },

]

const types = ['Book','API','FAQ','Other']

const info = {
  type: types[0]
}

class Creator extends Component {

  constructor () {
    super();
    this.state = {};
  }

  handleChange (e, {value}) {
    console.log("Value: " + value);
    info.type = value;
    this.setState({ value })  // <=== ERROR: setState is not a function.
  }

  render() {
    const { value } = this.state;
    return (
      <Form>
        <Form.Group widths='equal'>
          <Form.Field control={Input} label='First name' placeholder='First name' />
          <Form.Field control={Input} label='Last name' placeholder='Last name' />
          <Form.Field control={Select} label='Gender' options={options} placeholder='Gender' />
        </Form.Group>
        <Form.Group inline>
          <label>Quantity</label>
          <Form.Field control={Radio} label={types[0]} value={types[0]} checked={info.type === types[0]} onChange={this.handleChange} />
          <Form.Field control={Radio} label={types[1]} value={types[1]} checked={info.type === types[1]} onChange={this.handleChange} />
          <Form.Field control={Radio} label={types[2]} value={types[2]} checked={info.type === types[2]} onChange={this.handleChange} />
          <Form.Field control={Radio} label={types[3]} value={types[3]} checked={info.type === types[3]} onChange={this.handleChange} />
        </Form.Group>
        <Form.Field control={TextArea} label='About' placeholder='Tell us more about you...' />
        <Form.Field control={Checkbox} label='I agree to the Terms and Conditions' />
        <Form.Field control={Button}>Submit</Form.Field>
      </Form>
    )
  }
}
```

**Expected**
I expected to get no errors because I just copy and paste the sample code. 

**Result**
this.setState function inside the handleChange method doesn't exist. That is what the console told me. If I delete this line the app works correctly but the radio checkboxes not.
![image](https://user-images.githubusercontent.com/16807198/29383387-244c05d8-82c8-11e7-9142-5c5bf5567ecf.png)

**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/collections/form#form-example-field-control
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by Cicko** [comment]
Another thing is that I changed the function little bit from:
```ES6
  handleChange = (e, { value }) => this.setState({ value })
```

because in that way I get other error:

![image](https://user-images.githubusercontent.com/16807198/29383738-6384f952-82c9-11e7-9262-694a8eb2d87e.png)


So the most logic thing is that Electron don't support ES6

**Comment by layershifter** [comment]
I almost sure that your code is transpiled by Babel. It seems your preset doesn't support [Class properties transform](https://babeljs.io/docs/plugins/transform-class-properties/).

[Binding to methods of React class](http://egorsmirnov.me/2015/08/16/react-and-es6-part3.html)
