### ISSUE TITLE
How to change the text color of an <Input /> component knowing that I'm using the Semantic-Ui-React CDN ?

### ISSUE THREAD

**Issue by aziz-boudi4** [Semantic-Org/Semantic-UI-React#1975]
I'm trying to change the text color of the <Input /> component but with no success .
1- I tried using the prop className.
2- I tried to override the Input css class.

nothing worked so far

**Comment by layershifter** [comment]
SUIR doesn't provine any styles. SUI uses inheritance in CSS classes, so you should satisfy [priorites](http://www.hongkiat.com/blog/css-priority-level/) or use `!important`.

```css
.ui.input input {
  color: red;
}
```

Please use SO for such questions.

**Comment by anuragpatil94** [comment]
Is there any way to do this using styled-components?

Here is the [link](https://spectrum.chat/styled-components/general/trying-to-style-input-from-semantic-ui-using-styled-components~f5ebaa8c-4277-4325-9425-c0076b306d5b) of question I asked.

**Comment by geochronology** [comment]
@anuragpatil94 Styled components is able to change most but not all input properties. 

From what I can tell, styled-components _cannot_ change font attributes. 

Here's how I structure my own code:

In `styles.css`:
```
.ui.input > input {
  font-size: 1.2rem;
  background-color: purple !important;
}

.ui.input > input:focus {
  color: rgba(238, 238, 238, .9) !important;
  opacity: .85;
  transition: all .1s ease-in;
}
```

In App.js:

```
import React from 'react'
import {
  Button,
  Container,
  Divider,
  Grid, Header, Input,
} from 'semantic-ui-react'
import './styles.css'
import styled from 'styled-components'

const StyledInput = styled(Input)`
  height: 48px;
  width: 400px;
`

export const App = () => {

return (
  <Container>
    <StyledInput placeholder="4 out of 5 dentists agree..." />
  </Container>
)}

```

Note: !important **is** required for color and background-color, but it's **not** required for font-size. ¯\_(ツ)_/¯
