### ISSUE TITLE
<Sticky /> Component

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#198]
http://semantic-ui.com/modules/sticky.html

**Comment by arrterian** [comment]
I want implement this component within hacktoberfest.
Can you add hacktoberfest lable to this issue?

**Comment by levithomason** [comment]
@RomanValihura we don't have a hacktoberfest label, is this a standardized label that is required for the competition?  If not, your comment is sufficient to claim the issue for yourself.

**Comment by arrterian** [comment]
@levithomason Hacktoberfest is ended, but I still want implement this feature.
I don't need this lable already.

**Comment by levithomason** [comment]
Sounds good, we'd love to have this one implemented!  You can reference our [CONTRIBUTING.md](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/.github/CONTRIBUTING.md) guide as a step-by-step to setup and development for new components.  Let us know if you have any issues.

**Comment by arrterian** [comment]
@levithomason  OK, I will start on this week :)

**Comment by zeneben** [comment]
In the meantime, if I wanted to make an element sticky - would it be possible without jQuery? I tried following the semantic-ui usage at http://semantic-ui.com/modules/sticky.html#/usage  but it didn't seem to do anything to the element. I've managed to get this far in my project without having to resort to any non semantic-ui-react components, but this is a component which would actually come in very handy.

**Comment by levithomason** [comment]
Semantic-UI-React has no Sticky component, yet.  You cannot use the Semantic-UI Sticky docs since that only works with the jQuery plugin.  We'll add our own non-jQuery version of the Sticky component.

In the meantime, you may also find these helpful (I just googled react sticky):

1. https://github.com/captivationsoftware/react-sticky
1. https://github.com/yahoo/react-stickynode

**Comment by zeneben** [comment]
Thanks! `position: fixed` ended up being suitable to get me by until the
component is developed.

**Comment by levithomason** [comment]
I see.  It is worth noting that a "sticky" component is one that scrolls with the page until it "hits" some boundary (e.g. a header, the top of the page, etc.) then it "sticks" to that position following the user down the page.  So, it is sometimes `position: fixed` and other times not.  This is the distinction between the two.

**Comment by zeneben** [comment]
Agreed, and a true 'Sticky' would be ideal for my use case, but the fixed
position is sufficient for now.

**Comment by AdamBCo** [comment]
What's the update on the <Sticky/> component? :)

**Comment by layershifter** [comment]
@mariolamacchia You said that I would like to pick this issue. Could clarify this?

**Comment by mariolamacchia** [comment]
@layershifter Yes, hopefully it will be ready by next week

**Comment by layershifter** [comment]
Linking #1747
