### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ochanje210** [Semantic-Org/Semantic-UI-React#1987]
From the latest version: 0.71.5, server-side rendering produces following issue

```
/var/app/current/node_modules/semantic-ui-react/dist/commonjs/behaviors/Visibility/Visibility.js:260
  context: window,
           ^
ReferenceError: window is not defined
    at Object.<anonymous> (/var/app/current/node_modules/semantic-ui-react/dist/commonjs/behaviors/Visibility/Visibility.js:260:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/app/current/node_modules/semantic-ui-react/dist/commonjs/behaviors/Visibility/index.js:8:19)
    at Module._compile (module.js:569:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowy-console@1.0.0 start: `NODE_ENV=production node build/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowy-console@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by PaulBrunache** [comment]
+1

**Comment by lott-ai** [comment]
Looks like the issue is coming from this commit: https://github.com/Semantic-Org/Semantic-UI-React/commit/e350886fbaad1f696b02cdd00b92852c5713df6f

Perhaps we should wrap the defaultProps "context": window with an "isBrowser" check

**Comment by uicomponent** [comment]
+1

ChrisNLott thanks for help!

I commented all changes from this commit (+two related comments in Sticky.js and Visibility.js) and my project start to work.

Hope it can help somebody)

**Comment by kien8995** [comment]
Thank @ilinyevg, I try this and it work ! 
```javascript
const hasWindow =
typeof window === 'object' && window !== null && window.self === window;

Visibility.defaultProps = {
  context: hasWindow ? window : {},
  continuous: false,
  once: true
};
```

**Comment by arthur-nesterenko** [comment]
I have wrote temporary script for fix this, perhaps  for somebody will be useful

```
const fs = require( 'fs' );

const visibilityFile = 'node_modules/semantic-ui-react/dist/commonjs/behaviors/Visibility/Visibility.js';
const stickyFile = 'node_modules/semantic-ui-react/dist/commonjs/modules/Sticky/Sticky.js';

fs.readFile( visibilityFile, 'utf8', function ( err, data ) {
  if ( err ) {
    return console.error( err );
  }
  const result = data.replace( 'context: window', 'context: typeof window === \'object\' && window !== null && window.self === window ? window : {}' );

  fs.writeFile( visibilityFile, result, 'utf8', function ( err ) {
    if ( err ) return console.error( err );
  } );
} );

fs.readFile( stickyFile, 'utf8', function ( err, data ) {
  if ( err ) {
    return console.error( err );
  }
  const result = data.replace( 'scrollContext: window', 'scrollContext: typeof window === \'object\' && window !== null && window.self === window ? window : {}' );

  fs.writeFile( stickyFile, result, 'utf8', function ( err ) {
    if ( err ) return console.error( err );
  } );
} );
```

**Comment by WoLfulus** [comment]
How's this going? Everything broke here :(

**Comment by ochanje210** [comment]
Falling back to 0.71.3 should be fine until this is fixed.

**Comment by WoLfulus** [comment]
I'm in a loop xD
Some features I use are broken in .3

I'll try the workarounds

**Comment by Maxhodges** [comment]
I'm getting an error related to "window is not defined" when deploying to gatsby.
https://www.gatsbyjs.org/docs/debugging-html-builds/

I see multiple issues about this here and lots of discussion. Is there any consensus regarding a solution? if so should we add something to the docs?

- https://github.com/Semantic-Org/Semantic-UI/issues/4146
- https://github.com/Semantic-Org/Semantic-UI-React/issues/1987
- https://github.com/Semantic-Org/Semantic-UI-React/issues/712

**Comment by layershifter** [comment]
Just wait until #1990 will be merged and released in new version.

**Comment by prateekrastogi** [comment]
@layershifter  Any eta on when project maintainers are planning to do so?

**Comment by levithomason** [comment]
I do my best to make a release every weekend.  Sometimes I don't cause of life and free software :)

**Comment by ddenysov** [comment]
I still have this error in 0.72.0

scrollContext: typeof window === 'object' && window !== null && window.self === window ? window : {},

The code above fixed  problem

**Comment by lookagit** [comment]
node V7.9.0
npm V4.2.0

**Comment by levithomason** [comment]
If users are having issues on the latest release, please open a new issue if there is not one already.  The fields in the issue template are necessary for us to debug and ship fixes.

**Comment by curran** [comment]
Experiencing this error with SSR on version `0.75.1`.

**Comment by moshest** [comment]
I add to webpack on the server side the following plugin:

```js
  plugins: [
    // Define free variables
    // https://webpack.js.org/plugins/define-plugin/
    new webpack.DefinePlugin({
      window: undefined,
    }),
  ],
```

**Comment by levithomason** [comment]
We're happy to look at new issues posted against the latest version `0.77.0`.
