### ISSUE TITLE
Floated segments do not align vertically

### ISSUE THREAD

**Issue by gregor-mueller** [Semantic-Org/Semantic-UI-React#1988]
### Steps

1. Just use 2 segments, one floated left and one floated right.

### Expected Result
Floated segments are vertically aligned
![image](https://user-images.githubusercontent.com/28727932/29509428-89c12bda-8658-11e7-9b43-7dccafe35661.png)
(screenshot from Semantic-UI example page: https://semantic-ui.com/elements/segment#floated)

### Actual Result
Floated segments are not vertically aligned
![image](https://user-images.githubusercontent.com/28727932/29509464-aa202548-8658-11e7-909d-017d14690cec.png)
(screenshot from Sematic-UI-React example page https://react.semantic-ui.com/elements/segment#segment-example-floated)

### Version
v0.71.5

### Testcase
https://react.semantic-ui.com/elements/segment#segment-example-floated

**Comment by gregor-mueller** [comment]
I just found out that it will break in normal Semantic UI as well.. So it seems like a CSS issue.
Click on the `show source` button in the example (https://semantic-ui.com/elements/segment#floated) and it will break.

![image](https://user-images.githubusercontent.com/28727932/29604087-ab543d0c-87e6-11e7-86e8-946fdd374d20.png)

I posted the issue on the Semantic-UI project as well:
https://github.com/Semantic-Org/Semantic-UI/issues/3438

**Comment by layershifter** [comment]
Yep, it's a CSS issue. Closing because we don't handle CSS there.
