### ISSUE TITLE
fix(Modal): Opening and closing multiple modal

### ISSUE THREAD

**Issue by tejpratap46** [Semantic-Org/Semantic-UI-React#1992]
**Steps to Reproduce**
1. Open multiple modal: [example](https://react.semantic-ui.com/modules/modal#modal-example-multiple)
2. Close last (child) modal, enables window scrollbars.

**Expected**
No window scrollbars should appear until all modals are not closed

**Result**
Parent Modal stopped not scrolling but entire window.

**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/modules/modal#modal-example-multiple

**Comment by layershifter** [comment]
Duplicate, #1157
