### ISSUE TITLE
Dropdown: `selectOnKeydown` option from docs is not implemented

### ISSUE THREAD

**Issue by rijk** [Semantic-Org/Semantic-UI-React#1993]
### Steps
Used the `selectOnKeydown={false}` option as [mentioned in the docs](https://semantic-ui.com/modules/dropdown.html#/settings):

> Whether dropdown should select new option when using keyboard shortcuts. Setting to false will require enter or left click to confirm a choice.

### Expected Result

Keyboard navigation moving selection, without actually changing value.

### Actual Result

Value changes and dropdown closes when pressing e.g. arrow down key. + React warning:

```
Warning: Unknown prop `selectOnKeydown` on <div> tag. Remove this prop from the element.
```

### Version
0.71.5

I think the problem is here: https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L543

This line should be IMO something like this:

`if (!multiple && selectOnKeydown) this.makeSelectedItemActive(e)`

**Comment by rijk** [comment]
Ah doh, this is the Semantic docs, not the Semantic React. Even so, it would be nice to see this option implemented. Having the value selected right away when pressing down arrow just feels really unintuitive.

**Comment by layershifter** [comment]
Done in #2009 as `selectOnNavigation`.
