### ISSUE TITLE
Layouts: Sticky layout sample does not work

### ISSUE THREAD

**Issue by hubertguillemain** [Semantic-Org/Semantic-UI-React#1994]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - http://stackoverflow.com/search?q=semantic-ui-react

✔ BUGS → This form is required:

### Steps
Go to
https://react.semantic-ui.com/layouts/sticky
Scroll
### Expected Result
Some parts stick to top of the viewport when scrolling down
### Actual Result
Nothing sticks
### Version
0.71.5

### Testcase
[Fork, update, and replace this pen to show the bug]:
http://codepen.io/levithomason/pen/ZpBaJX

**Comment by layershifter** [comment]
This example was made before `Sticky` component was merged. PRs that will make this layout example fully functional are welcome.
