### ISSUE TITLE
closeOnBlur={false} doesn't work

### ISSUE THREAD

**Issue by a-x-** [Semantic-Org/Semantic-UI-React#1995]
### Steps
1. add `closeOnBlur={false}` to dropdown
2. blur dropdown by outside click or esc

### Expected Result
popup will not be closed

### Version
0.68.5

### Testcase
try it out in your documentation: https://react.semantic-ui.com/modules/dropdown#dropdown-example-close-on-blur

**Comment by lott-ai** [comment]
Fixed with https://github.com/Semantic-Org/Semantic-UI-React/pull/1998

**Comment by a-x-** [comment]
We'll check it soon, thank you so much for fast reaction!
