### ISSUE TITLE
Card: link prop and <Button> do not coexist well

### ISSUE THREAD

**Issue by hubertguillemain** [Semantic-Org/Semantic-UI-React#1997]
### Steps
Create a card with prop "link" and href and add a button in it (anywhere: content, Description, Meta...)
### Expected Result
Clicking on the button does not redirect to the href but only executes the button
### Actual Result
Clicking on the button  redirect to the href AND executes the button
### Version
0.71.5

### Testcase
https://codepen.io/youbi/pen/yoEjGx?editors=0010

**Comment by lott-ai** [comment]
Couldn't you just add `onClick={(e) => e.preventDefault()}` to the button?

**Comment by layershifter** [comment]
This cannot be fixed, because there is no way to fix this at library level. When `Card` has `href`, it will be rendered as `a` element, so all content inside it will be a link. And it's correct.

Use @ChrisNLott's workaround.

**Comment by hubertguillemain** [comment]
Many thanks for the prompt explanation and workaround, that'll do !
I'm amazed by the dedication of the contributors, keep up the good work :)
