### ISSUE TITLE
Can you style with Accordion's props  className?

### ISSUE THREAD

**Issue by darewreck54** [Semantic-Org/Semantic-UI-React#1999]
I'm not sure if this a bug or it's the way it's designed.  Sorry if it's not.

With the Accordion component, what's the point of the className.  I pass in a style class and it has no effect on the component.   There isn't much documentation on how to really style an accordion, for example I just want to change the font color.  It allows for basic styling with a flag set to true or false.

Both the Accordion component, Accordion.Title, Accordion.Content all have className props.  

In terms of usage, I posted the question on https://stackoverflow.com/questions/45853891/how-to-change-font-color-in-semantic-ui-react-accordion.

So this question is more on is there a bug in className?  If you know how to workaround this then a the hacky css solution in the stackoverflow question, please let me know as well. 

Thanks,
Derek

**Comment by darewreck54** [comment]
actually, I realized that you can just use the individual tags and add any html element within the tags and style it yourself.   

So I guess the real question is what is the purpose of className props if the class styles you pass in have no effect?

Thanks,
Derek

**Comment by layershifter** [comment]
## Styling with `className`

`className` prop adds a class to the rendered element:

```jsx
<Accordion.Title className='foo' />
```
```html
<div class="title foo">
```

[Use a CSS Class to Style an Element](https://www.freecodecamp.org/challenges/use-a-css-class-to-style-an-element). However, correct way is use the [SUI theming](http://learnsemantic.com/developing/customizing.html), because some style definitions are cascading or use `important` word.

**Comment by darewreck54** [comment]
@layershifter Thanks for the response.

I took a look at the SUI theming and it's not clear to me how you actually add the specific styling for a component or associate it within a react application.  

So right now the index.html will have the link to the default style

`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Test</title>

  
  <link href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/semantic.css" rel="stylesheet">
</head>
<body>
  <script src="bundle.js"></script>
</body>
</html>`

Where would site.variables go or how do you configure the react app to read from the site.variables mentioned in the SUI theming?   Can you point me to any useful links on an example?

Simple use case: Using a label and wanted to change it to a color that is not supported.  How would you go about applying it to a specific color?

In this case, you have the semantic ui label component <Label>.  What is the correct way to update to configure it to be a color other then they ones SUI supports.

Thanks,
Derek

**Comment by brianespinosa** [comment]
@darewreck54 The styles are completely separate from the react components. You can simply include the default CSS in your project or compile your own theme with the build tools in SUI proper. All of the props you apply to your react components with SUIR will add the correct class names.

If you want to customize something you can either customize your theme that you are compiling or write your own styles and attach those classes to your components.
