### ISSUE TITLE
Portal: boolean 'didFocusPortal' is not accurate

### ISSUE THREAD

**Issue by austinfox** [Semantic-Org/Semantic-UI-React#2002]
### Steps
Create a popup that triggers on focus of trigger element. Place content inside popup. Trigger the popup by focusing on the trigger, and then click inside the popup (not on a link or button, but on any empty space or text)

### Expected Result
Popup stays open, as the 'focus' is still inside the generated Portal component

### Actual Result
Popup closes

*Note*: After the popup opens, if you click on an html element that is allowed to receive focus (links, buttons, inputs etc...) the popup does not close, so it works as expected. The reason for this is that the boolean didFocusPortal inside the Popup is not defined correctly. It relies on the onBlur event from the target element, which has a reference to 'relatedTarget'. If an element that is allowed to receive focus is clicked on, the relatedTarget is not null and the function is able to correctly calculate if the element is within the portal. If, however, you click on an element that is not allowed to receive focus (divs, text, etc...), the 'relatedTarget' for the onBlur event is null, and 'didFocusPortal' is incorrectly set to false. The exact line of code where this is broken is here:

https://github.com/Semantic-Org/Semantic-UI-React/blob/23ec465c77e0f2c69efe22a3d8f7f0c24c951af3/src/addons/Portal/Portal.js#L230

I'm not exactly sure the best solution though, so I would like to open a discussion surrounding this issue.

### Version
0.71.5

### Testcase
I made two test cases to illustrate the issue. One where the popup works as it should (when links or buttons inside the Portal are clicked first) and one where the popup closes when it shouldn't (when empty space or text or other elements are clicked inside the Portal)

https://codepen.io/anon/pen/brKQPp

**Comment by austinfox** [comment]
For anyone looking for a quick fix for this, the solution is to wrap all the content inside the Popover in an <a> tag. Just set href='javascript:void(0)' and the style={{cursor: 'default'}}. This works perfectly, but I get the following warning raised by React in the console:

> Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.

What is inserted into the DOM is not technically valid HTML. Although it works for my use case, I would like to fix this at the source (Portal component) so others can benefit without adding this 'hack'.

**Comment by austinfox** [comment]
I've made the following change to the handleTriggerBlur() function:

```
handleTriggerBlur = (e) => {
    const { trigger, closeOnTriggerBlur } = this.props

    // Call original event handler
    _.invoke(trigger, 'props.onBlur', e)

    // do not close if focus is given to the portal
    // document.activeElement is set to 'body' until blur event completes
    // e.relatedTarget is null for elements that cannot receive focus such as div, so it can't be used
    setTimeout(() => {
      const didFocusPortal = _.invoke(this, 'rootNode.contains', document.activeElement)

      if (!closeOnTriggerBlur || didFocusPortal) return

      debug('handleTriggerBlur()')
      this.close(e)
    }, 1)
  }
```

I believe this fixes the problem. e.relatedTarget just isn't something that can be used as far as I understand, because it is not getting set when the focus is moved to an un-focusable element. So some brief searching online led me to document.activeElement. The problem is that when a BlurEvent is triggered, the browser clears activeElement and sets it to the document body. As soon as the focus event is called for the new element, document.activeElement is set to the correct element. But for the moment inside the BlurEvent, we can't use activeElement either. Setting a timeout of 1 and then accessing activeElement and completing the function works. Unfortunately it feels like a hack, but I can't find a better solution at the moment. 

I've never made a pull request before, but I am trying to make one for this change. Unfortunately the "closes the portal on blur when set" test in Portal-test.js is failing, but I'm not sure why. Can anyone guide me on this?

**Comment by levithomason** [comment]
There is a known issue and limitation here.  I'd love to solve it.  Please open a PR and we'll chat there.

**Comment by levithomason** [comment]
Oh, is your original issue solved with the `hoverable` prop?  This allows you to hover and click within the Popup.

**Comment by austinfox** [comment]
No, the issue is not solved via adding the hoverable prop. I don't want the popover to be triggered on hover. Also I'd be happy to open a PR but I don't really have any good solutions at the moment. I was hoping we could discuss options

**Comment by levithomason** [comment]
My time and budget for this particular issue are unfortunately non-existent.  I can help review a PR for the issue, however.

Note, I do use SUIR in my daily work as well.  If this issue pops up there, I will be able to tackle it at that time.
