### ISSUE TITLE
Unable to render local image in modal, only able to render images from hosted sites

### ISSUE THREAD

**Issue by robertkng** [Semantic-Org/Semantic-UI-React#2008]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - http://stackoverflow.com/search?q=semantic-ui-react

✔ BUGS → This form is required:

### Steps

1. Create a modal as instructed.
2. Place image src inside the modal.

### Expected Result

- Be able to see image saved locally.

### Actual Result

- Header and content description all renders, but the image saved locally does not.

### Version
0.71.3

### Testcase
https://codepen.io/robertng85/pen/vJzdgL

**Comment by layershifter** [comment]
Use [import](https://stackoverflow.com/a/35454832/6488546) for images or provide a correct path to image, I'm almost sure that your webserver returns 404.
