### ISSUE TITLE
Multiple Search Selection Dropdown keeps input when selecting

### ISSUE THREAD

**Issue by kirillku** [Semantic-Org/Semantic-UI-React#2015]
Multiple Search Selection Dropdown keeps input when selecting. It should be cleaned every time user selects some item. Notices that everything works fine when there are only one option found, but when multiple, the input is not reset. Or is it expected behavior? Then, in my opinion, it still should be disabled when using `closeOnChange` prop.

### Steps
1. Type something in dropdown
2. Chose any and press enter

### Expected Result
Item is selected, input is empty

### Actual Result
Item is selected, input text stays

### Version
0.72.0

### Testcase
[codepen](https://codepen.io/kirillku/pen/oeQvbV)

**Comment by layershifter** [comment]
Duplicate #1954. This behaviour was introduced in #1795, there was also PR for this #1955, but it wasn't finished.
