### ISSUE TITLE
Cannot read property 'Group' of undefined

### ISSUE THREAD

**Issue by renehauck** [Semantic-Org/Semantic-UI-React#2020]
### Steps
I import the **Transition**-Module :
`import { ...,Transition } from 'semantic-ui-react';`

and would like to use it like this:
```
 <Transition.Group animation={"drop"} duration={2000}>
       {this.props.searchStore.searchResult ? <SearchResultList />: <ElementDetails />}
  </Transition.Group>
```
### Expected Result
No Errors :smiley: 
### Actual Result
I get this Error:
`Cannot read property 'Group' of undefined`
### Version
"semantic-ui-react": "^0.72.0"

**Comment by layershifter** [comment]
Can you make a fresh install of deps? `rm -rf node_modules; npm i` It seems that you use another version.

**Comment by renehauck** [comment]
works :+1: , thanks
