### ISSUE TITLE
Image can't be centered if href is provided

### ISSUE THREAD

**Issue by dguo** [Semantic-Org/Semantic-UI-React#2022]
### Steps
Create an `Image` with `centered` set to true and with a `href` defined (to render it as an `<a>` tag). Apologies if this is actually a CSS issue. As a workaround, I'm putting the `Image` in a `Container` with `textAlign` set to `center`.

### Expected Result
The image is centered, and it links to the href.

### Actual Result
The image is left-aligned, and it links to the href.

### Version
0.71.4

### Testcase
https://codepen.io/anon/pen/qXQpyx

Both images have the centered property, but the first one has the href set.

**Comment by layershifter** [comment]
@dguo Thanks for detailed report, but it's really a CSS issue, [Semantic-UI#4708](https://github.com/Semantic-Org/Semantic-UI/issues/4708).
