### ISSUE TITLE
Dropdown: items missing "key" prop, React warning displayed

### ISSUE THREAD

**Issue by SidecarMaster** [Semantic-Org/Semantic-UI-React#2023]
### Steps

1. Wrote Dropdown code:
```
        <Dropdown
          selection
          options={options}
          error={errorAttr}
          >
        </Dropdown>
```

2. Passed in options:
`[{key: "react", value: "react", text: "react"}, {key: "redux", value: "redux", text: "redux"}]`

### Expected Result
`<div key="react" class="text" role="alert" aria-live="polite">react</div>`
This should have key="...".

### Actual Result
`<div class="text" role="alert" aria-live="polite">react</div>`
which doesn't have key="...".

### Version
semantic-ui-react@0.72.0

**Comment by levithomason** [comment]
`key`s are not rendered to the DOM, so you won't see them.  They are used by React internally.

Are you sure this error is from this usage?  I do not see this is issue.  A repro would be very helpful.

**Comment by SidecarMaster** [comment]
@levithomason Ah I see. But the error has keywords "array, key prop" in it. So I am assuming it has something to do with not having a key in each item?

This is the error I am getting from the console:
```
Warning: Each child in an array or iterator should have a unique "key" prop. 
Check the render method of `Dropdown`. 
See https://fb.me/react-warning-keys for more information.
    in DropdownItem (created by Dropdown)
    in Dropdown (at PostForm.js:52)
    in div (at PostForm.js:51)
    in renderSelection (created by ConnectedField)
    in ConnectedField (created by Connect(ConnectedField))
    in Connect(ConnectedField) (created by Field)
    in Field (at PostForm.js:81)
    in form (at PostForm.js:80)
    in div (at PostForm.js:78)
    in PostForm (created by Connect(PostForm))
    in Connect(PostForm) (created by Form(Connect(PostForm)))
    in Form(Connect(PostForm)) (created by Connect(Form(Connect(PostForm))))
    in Connect(Form(Connect(PostForm))) (created by ReduxForm)
    in ReduxForm (created by Route)
    in Route (at App.js:20)
    in div (at App.js:18)
    in App (at index.js:22)
    in Router (created by BrowserRouter)
    in BrowserRouter (at index.js:21)
    in Provider (at index.js:20)
```

This is my GitHub repository:
[Readable](https://github.com/willshu2049/Readable)

The Dropdown is in the PostForm component.

**Comment by layershifter** [comment]
Your `key` generated [there](https://github.com/willshu2049/Readable/blob/4e62e2caba9098d32cf2302223a33956295c5fe1/src/components/PostForm.js#L41) isn't unique while React [requires](https://facebook.github.io/react/docs/lists-and-keys.html) unique keys. Similar answer was [there](https://stackoverflow.com/a/45920479/6488546).

**Comment by SidecarMaster** [comment]
@layershifter In the original code, I assigned a different key to each object-"react", "redux", etc. What do you mean by "unique" keys? I tried random string such as ''inee0sga" by modifying the code to be `ele.key = Math.random().toString(36).substr(-8)`, still doesn't work.

**Comment by layershifter** [comment]
I'm not able to run code from your repository, it doesn't work. Please make a **minimal** repro.

Unique means unique,  they shouldn't repeat inside `options` array. Options that you provide will not produce warning, thats why Levi asked you about repro. While these options **will** produce warning:

```js
[
  {key: "react", value: "react", text: "react"},
  {key: "react", value: "redux", text: "redux"}
]
```

There is a `console.log`, please its output.

**Comment by SidecarMaster** [comment]
@layershifter I console.logged, the results are 'react', 'redux'. You may run my code by downloading it and running in the terminal "npm install" and "npm start". If you don't have time to look into it, that's okay. I will just use the react and redux to render the dropdown. Thanks.

**Comment by layershifter** [comment]
Minimal example:

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { Dropdown } from 'semantic-ui-react'

ReactDOM.render(
  <Dropdown
    selection
    options={[
      {key: "react", value: "react", text: "react"},
      {key: "redux", value: "redux", text: "redux"},
    ]}
    placeholder='Select Category'
  />,
  document.getElementById('root')
);
```

It will not produce warning. Again, there is something wrong with generated keys. Make a **minimal** example and I can look at it.

---

I've pulled `master`, it's not working. `redux` is missing in deps, after install:

![_999 020](https://user-images.githubusercontent.com/14183168/29863100-46de88aa-8d77-11e7-9405-fa55a25d3e22.png)

**Comment by ValeriaGrabnitskaya** [comment]
I found the solution. 
openTimeFrom = [
 { label: 1, value: "01:00" },
 { label: 2, value: "02:00" },
 { label: 3, value: "02:00" }
];
<Dropdown value={this.state.bookingTimeFrom} options={this.openTimeFrom} onChange={(e) => this.setState({ bookingTimeFrom: e.value })} filter={true} placeholder="Выберите время бронирования" filterBy="label,value" showClear={true} />

I think you must to create an Array with parameters label, value.
