### ISSUE TITLE
<Modal /> with property "actions" close dialog

### ISSUE THREAD

**Issue by realgvard** [Semantic-Org/Semantic-UI-React#2025]
### Steps
1. Set in <Modal /> property actions (button)
2. Try click on any of these buttons

### Expected Result
I would like to prevent closing Modal. Is it possible? Before of that (in **0.71.5** v.), this function was responsible for that: http://prntscr.com/get7wg

### Actual Result
In any cases, Modal is closing. And it's not possible to prevent.

### Testcase
https://codepen.io/anon/pen/mMQQEO

**Comment by layershifter** [comment]
This was made in #1599 as breaking change, because `triggerClose` caused warnings.

You should use full markup if you want to keep modal open.
