### ISSUE TITLE
select and dropdown not work if just import correspond css file

### ISSUE THREAD

**Issue by jomalonejia** [Semantic-Org/Semantic-UI-React#2029]
i wanna just import a dropdown component  in my react project, but it not work,
if  just  import 'semantic-ui-css/components/dropdown.css'
it would not work like this (click it and the item list would  not show)
![default](https://user-images.githubusercontent.com/26531282/29914433-0975deba-8e6b-11e7-985c-1c5a535c5521.PNG)

if import 'semantic-ui-css/semantic.css'
![2](https://user-images.githubusercontent.com/26531282/29914453-1dea6046-8e6b-11e7-8233-eea66c76d295.PNG)
it worked now , but the other style would been changed ,i don't like this,
i tried to import some compoents ,but also not work
![3](https://user-images.githubusercontent.com/26531282/29914550-87ed415c-8e6b-11e7-9014-32ab281ff0fa.PNG)

so , how can fix it ? thanks

**Comment by layershifter** [comment]
Please use SO questions. `Dropdown` also requires CSS from `Transition`.

**Comment by jomalonejia** [comment]
i have soluted it :)
the dropdown component need three css file : dropdown.css transition.css and reset.css
