### ISSUE TITLE
(Dropdown): when used as Menu Item, 'description' overlays 'text'

### ISSUE THREAD

**Issue by hubertguillemain** [Semantic-Org/Semantic-UI-React#2031]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - http://stackoverflow.com/search?q=semantic-ui-react

✔ BUGS → This form is required:

### Steps
Create a dropdown as a menu item (either child of <Menu.Item> or with prop item, which has a text and the description
### Expected Result
Description displays inline with text, floated right
### Actual Result
Description overlays text
### Version
0.72.0

### Testcase
https://codepen.io/youbi/pen/BdvGrw?editors=0010

**Comment by levithomason** [comment]
Looks like a valid issue, however, it is due to the CSS.  Please post at https://github.com/Semantic-Org/Semantic-UI.

### Workaround

You can explicitly set the width of the item to allow it to fit.  Here's a working fork:

https://codepen.io/levithomason/pen/RLWYpK
