### ISSUE TITLE
Popup - displays empty content, bug?

### ISSUE THREAD

**Issue by adam-26** [Semantic-Org/Semantic-UI-React#2032]
### Steps
Define a popup, without any of these props:
 * children
 * content
 * header

### Expected Result
I would expect the popup not to be displayed

### Actual Result
An empty popup is displayed

### Version
0.72.0

### Testcase
https://codepen.io/anon/pen/qXLGjK

If empty content prevented the popup from displaying, it would be very easy only _activate_ the popup for specific conditions. A specific use-case would be form validation using a popup. 

Is there another way to achieve the same behavior? I see the `open` prop in the documentation, but setting this to false does not prevent a popup from opening, it only closes an open popup.

Thanks.

**Comment by cdaringe** [comment]
opening the codepen results in an infinite reload loop from me. not sure if it's your code or codepen.  also having Popup issues today

**Comment by adam-26** [comment]
@cdaringe its working in my browser - I opened it in Chrome... what browser(s) are you using?

**Comment by cdaringe** [comment]
ya, looks like it was probably a codepen bug.  it works now!

**Comment by layershifter** [comment]
This is not bug, all other our components have the same behaviour. The visibility of `Popup` should be controlled with `open` prop, however it's compicated until #1190 will be merged.

**Comment by adam-26** [comment]
@layershifter, thanks for your response. You say that the `open` prop should control visibility... if this is true, then the [controlled popup example](https://react.semantic-ui.com/modules/popup#popup-example-controlled) should **never open**, even when it is clicked - as the popup is assigned an initial `open: false` value.

The `open` prop from what I understand can be used to close the popup, but it doesn't control visibility. 

So, there is no way to control a popup visibility? Is the behavior of the `open` prop a bug? If so, I'll open a new issue...

**Comment by layershifter** [comment]
@adam-26 

> should never open,

Why?

See example of [controlled Modal](https://react.semantic-ui.com/modules/modal#modal-example-controlled). `Popup` has a same behaviour because it also relies on `Portal`, but there is problem with initial position (#1190).

**Comment by adam-26** [comment]
@layershifter, thanks for the response. The Portal `openOnTrigger*` props was what I needed.
