### ISSUE TITLE
Popup does not render content for externally defined component

### ISSUE THREAD

**Issue by cdaringe** [Semantic-Org/Semantic-UI-React#2033]
✔ BUGS → This form is required:

### Steps

- `Popup`s using functional stateless components (maybe more) are not rendered

### Expected Result

- on `hover`, `Popup` content to yield

### Actual Result

- no content popped up

### Version

0.71.x-0.72.0

### Testcase

https://codepen.io/cdaringe/pen/prGoaK

**Comment by cdaringe** [comment]
i'm not sure _why_, but a hack is to wrap the target Popup content component in some basic JSX, https://codepen.io/cdaringe/pen/vJbYjK

**Comment by layershifter** [comment]
Duplicate, #1187.
