### ISSUE TITLE
Feature Request: Support Popup close onClick when hoverable

### ISSUE THREAD

**Issue by cdaringe** [Semantic-Org/Semantic-UI-React#2034]
### Steps

- add a `Popup` with `hoverable`

### Expected Result

- on click within the `Popup`, call first my `onClick` handler, then propagate event to internal `Popup` code, which closes the `Popup`

### Actual Result

- on click of a `hoverable` Popup, Popup remains visible.  To close it, I have to manually manage some state to _not_ render Popup childern

### Version
0.72.0

### Testcase

https://codepen.io/cdaringe/pen/RZvwdp

**Comment by levithomason** [comment]
This would be a new [Portal](https://react.semantic-ui.com/addons/portal) prop.  I suggest:

```jsx
<Portal closeOnPortalClick />
```

It should default to `false` for backward compatibility.  It would then be exposed in the `Popup`.  I suggest:

```jsx
<Popup closeOnClickInside />
```

How does this sound?

**Comment by cdaringe** [comment]
Yup, sounds great.  There may be cases where such an effect would be undesirable when it generally is desirable.  Maybe exposing a `shouldClose` hook that accepts a function to let the user decide would be an elegant, simple API to support all of the use cases.  I may be over complicating it, but I can see that function firing on mouseout, click, etc.  For instance, if my popup has a clickable submenu in it, I may want to keep it open to expand that submenu.

Just thinkin out loud :)

**Comment by cdaringe** [comment]
in retrospect, i could always just `evt.stopPropagation()` for those things that I don't want to auto-close the popup with.  disregard my latter proposal!

**Comment by levithomason** [comment]
Per the PR, a controlled component pattern solves the issue.  Set `open` via `onClick`.
