### ISSUE TITLE
Can't input chinese - the cursor move to the end automatically

### ISSUE THREAD

**Issue by hughjfchen** [Semantic-Org/Semantic-UI-React#2035]
### Steps
1.create a form with a input 
2.turn on  chinese input
3.try to type some chinese character 
4.the input only show the ascii character instead of the chinese
 
### Expected Result
the input should get the chinese character 

### Actual Result
The input only show the ascii character

### Version
semantic-ui-react: 0.72.0
mac osx: 10.12.6
chrome: 60.0.3112.113

**Comment by levithomason** [comment]
The default `<Input />` renders a plain HTML `<input />`.  If this does not work it is likely something unrelated to SUIR.  Does this work for you with a default React `<input />` element?

**Comment by hughjfchen** [comment]
I did some more test and found that the input component has following problem even input english:
I input some english character, move the cursor to the beginning, try to input some characters, however, the cursor will move to the end automatically after I input ONE chacracter so the rest characters will be input into the end.

**Comment by levithomason** [comment]
Please fork http://codepen.io/levithomason/pen/ZpBaJX and demonstrate the problem.  Will reopen if we can show the issue.  Right now, I believe the docs and tests are all working correctly.
