### ISSUE TITLE
Wrong position for Icon in Input when are (action || labeled)

### ISSUE THREAD

**Issue by cesarve77** [Semantic-Org/Semantic-UI-React#2036]
### Steps
Look [https://codepen.io/anon/pen/LjqpOP]

### Expected Result
The Icon stay inside the input

### Actual Result
The icon is inside the action dropdown
### Version
0.72.0

### Testcase

https://codepen.io/anon/pen/ayXvGg

**Comment by layershifter** [comment]
The generated markup is correct, this issue is CSS only because `icon` should have a position before `Dropdown`. Since our project doesn't deal with CSS, only React components, please post this over at https://github.com/Semantic-Org/Semantic-UI.
