### ISSUE TITLE
fix(Dropdown): Dropdown closing when clicking on input ("Input" Section example)

### ISSUE THREAD

**Issue by JacquesFernandes** [Semantic-Org/Semantic-UI-React#2039]
In: https://react.semantic-ui.com/modules/dropdown#dropdown-example-input
Browser: Chromium Version 60.0.3112.101 (Developer Build) Fedora Project (64-bit)

**Steps to Reproduce**
1. Click on dropdown to open
2. Try to click in the input box

**Expected**
Dropdown should stay open for user to type in data

**Result**
Dropdown closes when the user clicks to focus on input box

**Testcase**
https://react.semantic-ui.com/modules/dropdown#dropdown-example-input

**Comment by layershifter** [comment]
Duplicate #1593.
