### ISSUE TITLE
Dropdown: ignores closeOnChange if it has children and isn't a search

### ISSUE THREAD

**Issue by 9teen90nine** [Semantic-Org/Semantic-UI-React#2041]
**Steps to Reproduce**
1. Create a dropdown with children and closeOnChange={false}
2. Select an option

**Expected**
The Dropdown should not close

**Result**
The Dropdown closes

**Testcase**

https://codepen.io/9teen90nine/pen/PKLzQz

**Comment by 9teen90nine** [comment]
A little digging got the bug back.

**Comment by layershifter** [comment]
@9teen90nine Thanks for detailed report :+1:

**Comment by levithomason** [comment]
Per the docs, using children is not supported and requires you to manage the state yourself:

![image](https://user-images.githubusercontent.com/5067638/30524955-534a9ad6-9bb2-11e7-9405-05c3973a9918.png)

Note that we'll likely completely remove support for using children and replace it with shorthand props only.  See #1757 for that work.

If the JSX children in the codepen are changed to the supported `options` prop, each case works correctly: https://codepen.io/levithomason/pen/wrKxjo?editors=0010

I will close this for now.  We'll still merge the PR if it is inline with the future Dropdown API.
