### ISSUE TITLE
multiple dropdown lose values on change

### ISSUE THREAD

**Issue by EdsonAlcala** [Semantic-Org/Semantic-UI-React#2042]
### Steps

Create a dropdown with multiple option

### Expected Result

Being able to select multiple values

### Actual Result

The values are lost 

### Version

0.72.0

### Testcase

https://gyazo.com/f37fdaf48f9010f90d854108e3093a8f

**Comment by layershifter** [comment]
Please fill our issue template and I will reopen issue.

**Comment by EdsonAlcala** [comment]
can you reopen?

**Comment by layershifter** [comment]
Please make a codepen.

**Comment by levithomason** [comment]
To be clear, tests are passing for this and a minimal example is working:

https://react.semantic-ui.com/modules/dropdown#dropdown-example-multiple-search-selection

The bug then appears to be in the project's codebase and not in Semantic UI React.

**Comment by confuser** [comment]
For anyone else that comes across this issue as I did just now, it's due to the way options are handled. In order to prevent this occurring with remote data, you must ensure `options` always contains data for selected values, otherwise they will not display.

Example:
```js
handleSearchChange = async (e, { searchQuery }) => {
  this.setState({ loading: true })
    
  const results = await // From AJAX/Fetch/Whatever
  const options = results.concat(this.state.options.filter(opt => this.state.value.indexOf(opt.value) !== -1))

  this.setState({ options, loading: false })
}
```
