### ISSUE TITLE
fix(Advertisement): your description

### ISSUE THREAD

**Issue by GAVISHSETHI** [Semantic-Org/Semantic-UI-React#2045]
![git bug](https://user-images.githubusercontent.com/28700899/30022227-15487822-9188-11e7-8929-76e9217ddc4a.png)
i am not able to use advertisment whats the error in the code its happening only for advertisements i have latest versions of node npm react and sementic

**Comment by layershifter** [comment]
Please fill our issue template and make a codepen.
