### ISSUE TITLE
fix(Dropdown): Search + sub-components does not clear search string on selection

### ISSUE THREAD

**Issue by mhaas** [Semantic-Org/Semantic-UI-React#2050]
We use  `<Dropdown search selection>`. Search is handled on the server side; we use the `onSearchChange` prop and render our search results via the sub-component API as `<Dropdown.Item>` components. We have `onClick` handlers on the `Dropdown.Item` instances, which close the search and set the text prop on the `<Dropdown>`.

In more recent releases of SUI-React, clicking on a search result no longer clears the search string from the input. Before, the search string would be cleared and the `<Dropdown>` would correctly display its `text` prop. Now, the `<Dropdown.Menu>` containing the `<Dropdown.Item>` vanishes, but the search string is still displayed instead of the text prop of the `<Dropdown>`

**Manually invoking the `clearSearchString()` method on the `Dropdown` fixes the issue, so it's possible one of these calls got lost.**

**Steps to Reproduce**
1. I have attempted to repro the issue on a Codepen, but that only renders a blank screen w/o any error messages. Still, the code may be useful to understand how we use the Dropdown: https://codepen.io/anon/pen/ayrbeR

**Expected**
The Dropdown should display the `text` prop once its `open` prop is set to false

**Result**
The Dropdown keeps displaying the search string.

**Testcase**
Attempt repro case, but it's not working at all: https://codepen.io/anon/pen/ayrbeR

**Comment by layershifter** [comment]
Keep in mind, that subcomponent API of `Dropdown` will be fully dropped before 1.0.

Your codepen don't work because `this.state` isn't defined, define it in constructor:

```js
  constructor(props) {
    super(props)
    this.state = {}
  }
```

However, I don't understand what you're actually trying to do. `Dropdown` also doesn't have `clearSearchString` method.

**Comment by mhaas** [comment]
@layershifter We'll keep in mind that the subcomponent API will go away. Thank you for the reminder! We're already managing lots of state ourselves, so we won't have a lot of trouble porting the rest. I do assume we will still be able to use child components for a Dropdown, we just have to do all state management ourselves?

Thanks for the hint about initializing `this.state`. Just got back from a vacation (with a cold), so my React is a bit shaky.

I have updated the codepen to show the issue that we're seeing: https://codepen.io/anon/pen/dzEGqG

Steps to reproduce:
1) Click into dropdown
2) enter any search string
3) select the single search result, labeled "a search result"

Current behavior:
* The search menu closes, but the search string is not displayed (although the `text` prop of `<Dropdown>` has been updated from state)

Desired behavior:
* The closed `<Dropdown>` should not display the search string, but the `text` prop

I have previously stated that earlier versions of SUI-react did exhibit the desired behavior; but I cannot reproduce this now with older versions in the codepen. That's pretty weird, because the current behavior would have never passed our QA.

Anyways, it looks like what I consider a bug/regression may well be the intended behavior. It would still be nice to be able to display the text prop instead of the text of the search input.

**Comment by levithomason** [comment]
>I do assume we will still be able to use child components for a Dropdown, we just have to do all state management ourselves.

Odds are no.  We intend to build a props API that will be as flexible as children and more robust than most any user would want to try to build.  There are many cases you don't want to try to handle yourself, such as keyboard navigation, selected vs active state management, etc.  The Dropdown is the most complicated component in the library at well over 1,300 LOC with well over 2,300 LOC in tests.

The other driving force for this is the overwhelming number of issues posted for children in Dropdowns, even though it is not supported.  It will be best for the library, the users, and the maintainers to not support children in the future.

***

The issue here is the custom state management is not correct.  I don't have the bandwidth to debug it, but if I simply remove all the custom state management, the Dropdown works as expected:

https://codepen.io/levithomason/pen/OxyoEv

```jsx
<Dropdown
  fluid
  search
  selection
  placeholder="Default!"
  options={[{ text: "A search result", value: 'a-search-result' }]}
/>
```
