### ISSUE TITLE
Dropdown: onSearchChange signature should match that of Search

### ISSUE THREAD

**Issue by mcphailtom** [Semantic-Org/Semantic-UI-React#2052]
### Steps
onSearchChange previously provided event, value however the event.target no longer provides target data like name.

We have been using a generic search handler on a series of Dropdown components that populates state using field names and stripping the -search

I've noted several issues in recent months changing all event handler signatures to match a (event, data) pattern. Should this also be the case for Dropdown onSearchChange?

```
const name = event.target.name.match(/(\w+?)-search/)[1]
```

### Expected Result

name is a valid fieldname on the form

### Actual Result

event.target.name evaluates to null

Inspection of target in the console shows it no longer includes a name attribute

### Version
0.72.0

**Comment by layershifter** [comment]
This can be done with `searchInput` shorthand.

```jsx
<Dropdown onSearchChange={e => console.log(e.target.name)} /> // null
```

```jsx
<Dropdown searchInput={{ name: 'test' }} onSearchChange={e => console.log(e.target.name)} /> // 
'test'
```

I don't think that rely on `e.target.name` is best idea.

**Comment by levithomason** [comment]
I agree with @layershifter, however, this callback also has an invalid signature for our library as @mcphailtom points out.

#### Search.d.ts
```js
  /**
   * Called on search input change.
   *
   * @param {SyntheticEvent} event - React's original SyntheticEvent.
   * @param {object} data - All props, includes current value of search input.
   */
  onSearchChange?: (event: React.MouseEvent<HTMLElement>, data: SearchProps) => void;
```

#### Dropdown.d.ts
```js
  /**
   * Called on search input change.
   *
   * @param {SyntheticEvent} event - React's original SyntheticEvent.
   * @param {string} value - Current value of search input.
   */
  onSearchChange?: (event: React.SyntheticEvent<HTMLElement>, value: string) => void;
```

Aside from matching the Search component, all signatures in the lib should have a consistent `data` argument.  It should be an object containing all props and any relevant state data.
