### ISSUE TITLE
Dropdown: scrolling dropdown doesn't show pointer

### ISSUE THREAD

**Issue by 9teen90nine** [Semantic-Org/Semantic-UI-React#2055]
**Steps to Reproduce**
1. Create dropdown with both scrolling and pointing props
2. Open dropdown menu

**Expected**
The Dropdown should show pointer

**Result**
The Dropdown does not show pointer

**Testcase**
https://codepen.io/9teen90nine/pen/Yxowwb

**Comment by 9teen90nine** [comment]
I think this happens because scrolling dropdown has another overflow css.

**Comment by layershifter** [comment]
Both of this props are applying only `className`s, so it looks like CSS issue. Since our project doesn't deal with CSS, only React components, please post this over at https://github.com/Semantic-Org/Semantic-UI.
