### ISSUE TITLE
Dropdown text prop of type string

### ISSUE THREAD

**Issue by dominikdosoudil** [Semantic-Org/Semantic-UI-React#2056]
Hello guys,
I bumped in to a use case, where I want a dropdown that has custom icon along with the default dropdown icon as a static text. Like that
![snimek obrazovky 2017-09-08 v 9 42 06](https://user-images.githubusercontent.com/15929942/30201160-0187d324-947a-11e7-8ff4-d7a23daabc2d.png)

Dropdown actually can handle that however proptype is set to string. But it could be also an array or object IMHO. Is there another way how to do that or ignoring proptypes is just fine? I think that I could make a PR (which would actually just change the proptypes...) but I wanted to ask if I'm not doing something wrong first.

```
<Dropdown
  floating
  text={<Icon name="file text outline" style={{ margin: '0px' }} />}
  options={...}
/>
```
array example
```
<Dropdown
  floating
  text={[<Icon name="file text outline" style={{ margin: '0px' }} />, "example"]}
  options={...}
/>
```
### Version
0.72.0

**Comment by layershifter** [comment]
Duplicate #1864.
