### ISSUE TITLE
Rating: RatingIcon throws warning in React 16

### ISSUE THREAD

**Issue by DennisKo** [Semantic-Org/Semantic-UI-React#2057]
### Steps
Take the Rating example from the docs:
`<Rating maxRating={5} defaultRating={3} icon='star' size='mini' />`
### Expected Result
It works without warning.
### Actual Result
React throws a warning:
`Warning: Setting defaultProps as an instance property on RatingIcon is not supported and will be ignored. Instead, define defaultProps as a static property on RatingIcon.`
### Version
0.72.0 + React 16.0.0-rc.2

**Comment by layershifter** [comment]
@DennisKo Thanks for report. There is a typo.

#### RatingIcon.js

```diff
- defaultProps = {
+ static defaultProps = {
```
