### ISSUE TITLE
Dropdown: allow hiding `noResultsMessage`

### ISSUE THREAD

**Issue by rijk** [Semantic-Org/Semantic-UI-React#2064]
When passing `noResultsMessage=""`, the dropdown looks a little weird on focus:

<img width="342" alt="screen shot 2017-09-10 at 14 42 54" src="https://user-images.githubusercontent.com/159500/30249548-832b16da-9636-11e7-93c6-1ec3bddadde4.png">

I think a better handling would be to not expand in this case (which is actually what I was after).

Note that `openOnFocus={false}` has no effect here — which might be a bug. Same for `minCharacters={1}` (`minCharacters={2}` does work btw).

https://codepen.io/anon/pen/BdXOLB

**Comment by layershifter** [comment]
There is condition for `noResultsMessage`, pass `noResultsMessage={null}` and it will be not displayed.

Only `minCharacters > 1` makes sence because if we will start counting from `0`, you will can't enter anything.
