### ISSUE TITLE
Icon is changed to Logo of Medium.com when setting icon size to medium

### ISSUE THREAD

**Issue by korkeatw** [Semantic-Org/Semantic-UI-React#2065]
I found a little funny bug when using `Icon` component of Semantic UI React.
I didn't test with normal Semantic UI library. I'm not sure it happened only Semantic UI React or both.

### Steps
1. Use any `Icon` component
2. Set prop `size` to `medium`

### Expected Result
The icon supposed to be bigger/smaller

### Actual Result
The icon is changed to logo of Medium.com 

### Version
Semantic UI React 0.72.0

### Testcase
https://codepen.io/khasathan/pen/OjKajo

**Comment by layershifter** [comment]
`Icon` doesn't have `medium` size because it has `medium` icon, Semantic-Org/Semantic-UI#4793

**Comment by levithomason** [comment]
Note, no `size` is the would-be "medium" size.

**Comment by rinormaloku** [comment]
Isn't this fixable or what?

I don't see any reason why not to fix this. no size is medium size? Kidding me 

```
size={ iconSize ? '': 'large'}
```

Doesn't this give you a WTF millisecond? Even though a millisecond there is no reason for its existence.
If you want I can fix this. Just open it.

**Comment by layershifter** [comment]
It's not fixable, reason was described.

**Comment by brianespinosa** [comment]
@rinormaloku you may want to take a look at the core SUI styles. Click the "Definitions" tab and scroll down to the examples for "Size". You could "fix" that all day long in this React project but that is literally not how the core markup and styles are written.

https://semantic-ui.com/elements/icon.html
