### ISSUE TITLE
No CHANGELOG for v0.73.0

### ISSUE THREAD

**Issue by brianespinosa** [Semantic-Org/Semantic-UI-React#2066]
Perhaps I am missing something... but I do not see a CHANGELOG.md entry for v0.73.0 yet. NPM is up to date with the newer version. Are we keeping version changes in a different place now?

**Comment by layershifter** [comment]
I think @levithomason just forgot to update it :thinking:

**Comment by levithomason** [comment]
Thanks for the report.  The generator failed, fixed and pushed.

https://github.com/Semantic-Org/Semantic-UI-React/blob/master/CHANGELOG.md
