### ISSUE TITLE
Rating: more icons types

### ISSUE THREAD

**Issue by dbrrt** [Semantic-Org/Semantic-UI-React#2068]
Would it be possible to have more icons for the Rating component, for instance `money` for a budget rating?

**Comment by levithomason** [comment]
TL;DR - not readily available.  It requires an update to the CSS and markup at https://github.com/Semantic-Org/Semantic-UI.

**More Context**

The CSS for the Rating icon is quite different than it is for regular Icons.  This includes having multiple states and border colors.  Also, there is predefined colors for each.  The heart is red, the star is gold.

We _may_ be able to pull this off by taking in a color name and an Icon name and generating the icons manually on our end.  I would be interested in a PR exploring this idea.  Would you like to contribute?

**Comment by dbrrt** [comment]
@levithomason Yes, I'd like to contribute to this feature !

**Comment by layershifter** [comment]
@dbrrt do you still have plans for this?

**Comment by dbrrt** [comment]
@layershifter I do, but I didn't find time to work on this feature until now, I'll have a look ASAP on it.

I don't get why in examples, when I replace  `heart` per `star`, I don't get the yellow star. In RatingIcon component, how is decided that an icon will be the one passed as a Property, and the custom colors for these icons? I can't find the location of these definitions.

Any information will be appreciated :)

**Comment by levithomason** [comment]
They come from the CSS.  Specifically, the `::before` pseudo element sets the `content` directly to the unicode for the icon.  Icons in SUI are font powered, this unicode value is the character value of the particular icon in the font set:

![image](https://user-images.githubusercontent.com/5067638/31597405-03a91f50-b1fd-11e7-8784-4503281c23b1.png)

You can find unicode values for icon names by looking at the `content` value in the [icon.css](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/icon.css#L534) file.

Have a look at my previous comment in light of this one.  This is why we _may_ be able to pull this off but not for sure.  Rating icon CSS is special cased for ratings.  Regular icon CSS doesn't provide all the states needed.

**Comment by dbrrt** [comment]
Ok I got it, so to implement new rating icons, it has to be implemented on the SUI-CSS repo first...

**Comment by layershifter** [comment]
Closing until this will be not implimented in the main repo.
