### ISSUE TITLE
Tab grid props doesn't working.

### ISSUE THREAD

**Issue by santhi-nyros** [Semantic-Org/Semantic-UI-React#2069]
I am developing a reactjs app using semantic ui. So I am using react semantic ui components.I am trying to display tabs in vertical manner. so I have used the code in this example, but it's not working in page. 
I found the issue is grid ui classes are not added, I don't know what happening. But remaining reactJs semantic components working fine.

Please help me to fix it.

**Comment by layershifter** [comment]
Please fill our issue template and make a codepen.
