### ISSUE TITLE
[Dropdown] Animation Not working in case of semantic-ui-react 

### ISSUE THREAD

**Issue by gsahni** [Semantic-Org/Semantic-UI-React#2071]
In dropdowns, animation is not working if we are using semantic ui react. While animation is there in normal semantic-ui

**Comment by layershifter** [comment]
Transitions aren't supported in `Dropdown` yet, ref #1435, #2001. Contributions are welcome.

**Comment by james-work-account** [comment]
Hi @layershifter, has there been any progress on adding animations to [Dropdown](https://react.semantic-ui.com/modules/dropdown/)?
