### ISSUE TITLE
npm install semantic-ui-react --save produces  several directories deleted inside node-modules in a create-react-app

### ISSUE THREAD

**Issue by porkopek** [Semantic-Org/Semantic-UI-React#2072]
✔ BUGS → This form is required:

### Steps
**npm v 5.0.3
 node v 8.1.3**

npm install create-react-app
create-react-app myapp
cd myapp
npm install semantic-ui-react --save
npm start

### Expected Result
Working app

### Actual Result
When creating a react app with create-react-app, everything is fine. It installs like 900 folders in node_modules. npm start works

After installing semantic-ui-react with npm, npm deletes a lot of folders in node_modules, needed by create-reac-app. Among them, several files inside react-scripts folder.

### Version
0.73.0

**Comment by layershifter** [comment]
`npm` has latest version `5.4.1`. `5.0.3` is outdated and caused many bugs with CRA, see Dan's [tweet](https://twitter.com/dan_abramov/status/905729594216591360).

**Comment by porkopek** [comment]
Oh, so sorry for not finding this sooner. Thanks for your quick answer.

**Comment by levithomason** [comment]
@layershifter speaking of `npm` issues, SUIR is one of the only projects I use today that is still on `npm`.  Expect a `yarn` update soon.
