### ISSUE TITLE
missing property error in TextArea

### ISSUE THREAD

**Issue by cesarve77** [Semantic-Org/Semantic-UI-React#2076]
Looks like TextArea need a property like Input, just to be consistent

I know is posible handle it just for css, but if I can do it for Input why not for TextArea

**Comment by layershifter** [comment]
`Textarea` is addon component, this means that it's not represented in vanilla SUI. As you can see, it's always wrapped with `Form`. You can use `error`, if you will use `TextArea` inside `Form.Field`:

```jsx
<Form>
  <Form.Field error>
    <TextArea placeholder='Tell us more' />
  </Form.Field>
  <Form.TextArea error placeholder='Tell us more' />
</Form>
```
