### ISSUE TITLE
fix(Checkbox): Label color black on inverted segment

### ISSUE THREAD

**Issue by hubertguillemain** [Semantic-Org/Semantic-UI-React#2077]
**Steps to Reproduce**
<Segment inverted><Checkbox label='Make my profile visible' /></Segment>

**Expected**
The label's color should change based on the parent container's inverted state

**Result**
The label color stays black

**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/modules/checkbox#checkbox-example-checkbox
<Segment inverted><Checkbox label='Make my profile visible' /></Segment>

**Comment by layershifter** [comment]
Take a look on this [example](https://react.semantic-ui.com/collections/form#form-example-inverted). There should be correct markup for correct work of `inverted` prop.

**Comment by hubertguillemain** [comment]
Thanks a lot for such prompt response.
Simple checkbox works like this indeed.
I have found that with that example if you add the toggle prop, the issue persists.
Is that a SUI CSS issue ? Should this ticket be reopened ?

**Comment by layershifter** [comment]
Yes, non-inverted `<Checkbox toggle />` is CSS issue and should be reported on SUI repo. Don't forget to convert your code to HTML when you'll submit issue :+1:
