### ISSUE TITLE
Docs: parse {custom} and display correct values

### ISSUE THREAD

**Issue by Maxhodges** [Semantic-Org/Semantic-UI-React#2078]
should list some acceptable values here

```
only |   | {custom} | A row can appear only for a specific device, or screen sizes.
```
i get error
```
ReferenceError: computer is not defined
```
on `<Grid.Column only={computer}>`

**Comment by layershifter** [comment]
You're trying to use `computer` as variable while it's a string value:

```jsx
<Grid.Column only='computer'>
```

**Comment by layershifter** [comment]
However, our docs plugin should parse all `custom` values, but it will be not easy. I saw sometime ago on [`react-docgen`](https://github.com/reactjs/react-docgen) and seems they [allow](https://github.com/reactjs/react-docgen/blob/1f3cac2f4cbf1b45a0c657817b273dd8c54a8309/src/__tests__/main-test.js#L44) to pass custom handlers. Help in this direction is very necessary.

We also need to convert `union`'s to `enum`'s [there](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.73.0/gulp/plugins/util/parseType.js#L23).
