### ISSUE TITLE
srcSet missing from Image

### ISSUE THREAD

**Issue by Maxhodges** [Semantic-Org/Semantic-UI-React#2079]
srcSet should probably be a property of Image
`Warning: Unknown DOM property srcset. Did you mean srcSet?`

**Comment by layershifter** [comment]
All unhandled props are passed to component's container, [codepen](https://codesandbox.io/s/x32w133z4p).

**Comment by Maxhodges** [comment]
why do you provide src but not srcSet? I understand it's not defined by SUI, but do you think it shoul be?

**Comment by layershifter** [comment]
Because, `src` is handled and is needed by our factories. While `srcSet` is a simple prop, we don't need to expose all possible HTML props in components.

**Comment by Maxhodges** [comment]
OK. thank you sir!

**Comment by codekiln** [comment]
@layershifter while I agree that SemanticUI shouldn't expose *all* HTML props in components, `srcSet` seems very important. Browsers already know how to render responsive images so we can handle the difference between Retina, iPhone and normal resolution, and without `srcSet` placed directly on the `<img`, what is the proposed method? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Example_3_Using_the_srcset_attribute

Update / Workaround: I just figured out you can achieve the same thing by placing your own image inside the Image component: 
```
<Item.Image size="tiny" shape="circular">
<img 
  src={withPrefix(avatar.responsiveResolution.src)}
  srcSet={getPrefixedSrcSet(avatar.responsiveResolution.srcSet)}/>
</Item.Image>
```

That's not so bad after all.

**Comment by Maxhodges** [comment]
The `picture` element is "beginning to land in browsers". Google is recommending it here. Perhaps this is something SUI should get behind. @jlukic 
https://developers.google.com/web/fundamentals/design-and-ux/responsive/images

**Comment by layershifter** [comment]
I've added #2316, handling of HTML props were improved, examples were added.
