### ISSUE TITLE
Missing Font Awesome icon(s)

### ISSUE THREAD

**Issue by sibljon** [Semantic-Org/Semantic-UI-React#2084]
### Steps
1. Attempt to use the `user-md` icon

### Expected Result
`<Icon name='user-md' />` renders this icon: [user-md](http://fontawesome.io/icon/user-md/)

### Actual Result
`<Icon name='user-md' />` renders a blank `Icon` element

### Version
0.73.1

### Testcase
https://codepen.io/jonsibley/pen/OxMbxr

### Comments
It's possible this isn't a bug, but rather a misunderstanding on how Font Awesome icons are grouped, or what Sematnic-UI-React makes available out of the box. However, the following comment [from the docs](https://react.semantic-ui.com/elements/icon) leads me to believe that the `user-md` icon (and likely more) are unintentionally missing:

> Semantic includes a complete port of Font Awesome 4.7.0 designed by Dave Gandy for its standard icon set.

**Comment by layershifter** [comment]
Semantic UI uses own [icon names](https://semantic-ui.com/elements/icon.html) for FontAwesome icons, i.e. `fa-user-md` is `doctor`. So, you should use `<Icon name='doctor' />`. 

See Semantic-Org/Semantic-UI#2952.
