### ISSUE TITLE
Vertical divider appears to be rendering incorrectly in Chrome

### ISSUE THREAD

**Issue by dburles** [Semantic-Org/Semantic-UI-React#2085]
See documentation

https://react.semantic-ui.com/elements/divider#divider-example-vertical

**Comment by levithomason** [comment]
Dupe, this is an issue Semantic UI and Chrome.  There is a deep-seated history. See #1544 for more info and workaround.

**Comment by dburles** [comment]
Thanks @levithomason

**Comment by levithomason** [comment]
Sure thing!
