### ISSUE TITLE
fix(Button): onClick seems to be acting weird

### ISSUE THREAD

**Issue by HemalR** [Semantic-Org/Semantic-UI-React#2087]
**Steps to Reproduce**
I've created a button (not yet wired up to my back-end). As per usual, I do a console log to make sure everything is in place, but the below code keeps on failing (nothing logs to console).

```
<Button
							positive
							fluid
							onClick={()=>{console.log('Clicking button')}}
							size='big'
>Send</Button>
```

Reading more into the docs, the function should be passing event and data parameters. So I tried this:

```
<Button
							positive
							fluid
							onClick={(event, data)=>{
                                                            console.log(event); //Logs to console
                                                            console.log(data); //Nothing logs
                                                            console.log('Clicking button') //Nothing logs
                                                          }}
							size='big'
>Send</Button>
```
I'm stumped. The function seems to be firing, based on the fact that 'event' is logging, but nothing else is.

Note - I also tried to register an `onClick` handler to a div with similar effects. The onClick handler didn't do anything.

Does anything seem glaringly out of place in my code?

**Comment by layershifter** [comment]
Check your code, all works as expected, even your code, [codepen](https://codesandbox.io/s/jp13xn1pw5).

**Comment by HemalR** [comment]
Hmm.. Some underlying issue then, maybe in Meteor... Thanks for that! @layershifter
