### ISSUE TITLE
fix(Modal): closeOnEscape not included in initial props in docs

### ISSUE THREAD

**Issue by jeffgietz-zz** [Semantic-Org/Semantic-UI-React#2089]
Hey guys, I really like this feature; I just noticed that it wasn't in the initial prop documentation.

**Steps to Reproduce**
1. Visit https://react.semantic-ui.com/modules/modal#modal-example-close-config
2. Search for all references to close in the props portion of the page.

**Expected**
closeOnEscape | false | {bool} | Whether or not the Modal should close when the Escape key is pressed.

**Result**
Information only down the page.

Cheers,
Jeff

**Comment by layershifter** [comment]
`closeOnEscape` is `Portal` prop and its definition is aviable in `Portal` docs. However, it's really should be defined in `Modal`. Duplicate #1169.
