### ISSUE TITLE
Cannot pass tabIndex props to Search component

### ISSUE THREAD

**Issue by kfuglsang** [Semantic-Org/Semantic-UI-React#2092]
### Steps
Passing prop `tabIndex` to `Search` should set it as an attribute on the `<input>` element, not the containing `<div>` element.

### Expected Result
```
<div class="ui fluid search">
<input type="text" tabindex="5" class="prompt" autocomplete="off">
</div>
```

### Actual Result
```
<div tabindex="5" class="ui fluid search">
<input type="text" tabindex="0" class="prompt" autocomplete="off">
</div>
```

### Version
0.73.1

**Comment by layershifter** [comment]
[Example](https://react.semantic-ui.com/modules/search#search-example-input) from docs.

```jsx
<Search input={{ input: { autoComplete: 'off', className: 'prompt', tabIndex: 5 }}} />
```

**Comment by kfuglsang** [comment]
Thanks. Didn't notice this syntax before.
