### ISSUE TITLE
removeIcon for Label conflicts with children

### ISSUE THREAD

**Issue by jaqua** [Semantic-Org/Semantic-UI-React#2098]
### Steps
I'm trying to use a label with `removeIcon`:

    <Label color='blue' name='type' onRemove={this.handleRemove} removeIcon>Test</Label>

### Expected Result
Add 'x' Icon, which listen to `onRemove`.

### Actual Result
    Warning: Failed prop type: Prop `removeIcon` in `Label` conflicts with props: `children`. They cannot be defined together, choose one or the other.

### Version
0.73.1

**Comment by layershifter** [comment]
`removeIcon` is the shorthand prop, it's not possible to combine shorthand props with `children`. You should use `content` prop there:

```jsx
  <Label 
    content='Test'
    onRemove={() => {}}
  />
  <Label 
    content={<div>Test</div>}
    onRemove={() => {}}
  />
```

BTW, it's not required to use `removeIcon` prop, it will be added by default if `onRemove` callback is present. However, you can use for some tricks like this:

```jsx
  <Label 
    content='Test'
    onRemove={() => {}}
    removeIcon={{ color: 'red', name: 'delete' }}
  />
```
