### ISSUE TITLE
Button: `attached` prop should accept `true` as value

### ISSUE THREAD

**Issue by kasbah** [Semantic-Org/Semantic-UI-React#2104]
### Steps

Add a `Button` with boolean `attached` prop

### Expected Result

No warnings

### Actual Result
Warning logged: 

```
"Warning: Failed prop type: Invalid prop `attached` of value `true` supplied to `t`, expected one of ['left','right','top','bottom'].
    in t (created by App)
    in App"
```

### Version
0.67.1

### Testcase
https://codepen.io/anon/pen/YrGjqx?editors=1112

**Comment by layershifter** [comment]
The `attached` prop can take only one from these values: `left`, `right`, `top`, `bottom`. Why do think that it can accept `boolean`?

[`Button` docs](https://react.semantic-ui.com/elements/button)

**Comment by kasbah** [comment]
Because that's how the [`Segment`](https://react.semantic-ui.com/elements/segment) works. A value of `true` (i.e. just adding the prop without an `=`) means attached in the middle. There is no other way to attach in the middle. It currently works with buttons as well but gives a warning. I think the warning is invalid and `bool` should be added to the proptypes.

**Comment by layershifter** [comment]
Hm, seems you're right. Nice catch :+1: 

```jsx
  <div>
    <Button attached='top'>Top</Button>
    <Button attached>Middle</Button>
    <Button attached='bottom'>Bottom</Button>
  </div>
```

This looks like valid markup. As I see we can to update `propTypes`, classNames and tests on `Button` and `Button.Group`. It should work in same way as `Segment`.
