### ISSUE TITLE
close sidebar when click outside component??

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#2107]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - http://stackoverflow.com/search?q=semantic-ui-react

✔ BUGS → This form is required:

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
http://codepen.io/levithomason/pen/ZpBaJX

**Comment by layershifter** [comment]
Duplicate #1158, you can also find there a solution. Also take a look on this [example](https://codesandbox.io/s/325y47xk36).

**Comment by mortezakia** [comment]
for bootstrap4.3
