### ISSUE TITLE
Autofocus of dropdown search field

### ISSUE THREAD

**Issue by jaqua** [Semantic-Org/Semantic-UI-React#2108]
### Steps
I'm trying to get focus on search input field initially, so the user do not have to click on the dropdown. Instead the user should be able so start typing/searching...

    <Dropdown
      autoFocus
      name={name}
      placeholder='Select type'
      search
      selection
      onChange={this.handleChange}
      options={options}
    />

### Expected Result
Autofocus search input field

### Actual Result
No focus of input field

### Version
0.73.1

**Comment by layershifter** [comment]
[Example in docs](https://react.semantic-ui.com/modules/dropdown#dropdown-example-search-input)

```jsx
<Dropdown searchInput={{ autoFocus: true }} />
```

[Codepen](https://codesandbox.io/s/mzjlqzp41y)
