### ISSUE TITLE
Modal description (and possibly others) incorrectly specifies style option in docs!

### ISSUE THREAD

**Issue by patientplatypus** [Semantic-Org/Semantic-UI-React#2115]
This is a CSS issue HOWEVER, it appears that semantic ui react does not accept inline styling, EVEN THOUGH, it mentions that it does in the documentation. 

So, I'm looking at https://react.semantic-ui.com/modules/modal#modal-example-modal, specifically where it says 

style |   | {object} | Custom styles.
-- | -- | -- | --

At the top where it says how you can style objects. However, no combination of inline styling options works on the modal. (For example `style={color: 'purple'}` does not work, nor does `style={'color: purple'}` etc). Can someone post an example, or update the documentation by taking down that option? It's a little frustrating having incorrect or incomplete documentation - I only found out this won't work after implementing the modal.

**Comment by levithomason** [comment]
React docs: https://facebook.github.io/react/docs/dom-elements.html#style
Working SUIR Modal style: https://codepen.io/levithomason/pen/mBOXOe

Note, you're missing the style object's curly braces, the first braces are JSX syntax for starting the JS expression: 

```jsx
<Modal style={ color: 'purple' } />
<Modal style={{ color: 'purple' }} />
```

Here's a step through:
```jsx
<Modal style={/* JS expression */} />

const myStyle = { color: 'purple' }
<Modal style={style} />

// or

<Modal style={{ color: 'purple' }} />
```

Please complete the issue template next time.  Less shouting would also be much appreciated.
