### ISSUE TITLE
fix(Input): no "defaultValue" prop in documentation

### ISSUE THREAD

**Issue by vasilevich** [Semantic-Org/Semantic-UI-React#2124]
**Steps to Reproduce**
1. [look into the table of possible props for Input and notice there is no "defaultValue"](https://react.semantic-ui.com/elements/input#props)

**Expected**
The documentation should clearly tell how to insert defaultValue into the input as this is important, and if there is value and any other fields, it should list them all.
moreover, I don't know if its managed within this repository but the typescript typings miss defaultValue too, or atleast it didn't suggest in my IDE (webstorm).

**Result**
Had to spend 20+ minutes to look for an alternative only to find that [this example](https://react.semantic-ui.com/elements/input#input-example-left-action-labeled-button) contains 'defaultValue' event ho it was not mentioned in the possible props.

Thank you for your work!
cheers.

**Comment by levithomason** [comment]
Note, `defaultValue` is a React prop and not a Semantic UI React specific prop.  We only list props that we have logic around.  All other props are valid and passed directly to the component.  It is not practical to list every valid React prop a user may pass.
