### ISSUE TITLE
docs(Dropdown): Recent update breaks DropdownExampleRemote

### ISSUE THREAD

**Issue by patrikmolsson** [Semantic-Org/Semantic-UI-React#2125]
**Steps to Reproduce**
1. Write something in the dropdown

**Expected**
state.searchQuery should equal that string

**Result**
state.searchQuery instead equals the entire Dropdown's state

This can be fixed the same way like https://github.com/Semantic-Org/Semantic-UI-React/pull/2110,

but instead on https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/Examples/modules/Dropdown/Usage/DropdownExampleRemote.js#L24

**Comment by layershifter** [comment]
@patrikmolsson Thanks for the notice. Would you like to make PR? 😃

**Comment by patrikmolsson** [comment]
@layershifter On it!

**Comment by patrikmolsson** [comment]
Issue is solved in PR: https://github.com/Semantic-Org/Semantic-UI-React/pull/2126
