### ISSUE TITLE
Transition: Transition.Group doesn't perform transitions correctly

### ISSUE THREAD

**Issue by inspiral** [Semantic-Org/Semantic-UI-React#2127]
**Steps to Reproduce**
1. Adding at least 2 new elements with the '+' sign, then trying to remove elements with the '-' results errorneous behaviour, since the list items will not disappear properly according to the clicks on '-'.

**Expected**
The Transition should do remove item 1 by 1 when i click on the '-' sign.

**Result**
The Transition does not do this

**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/modules/transition#transition-example-group
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by layershifter** [comment]
@ianunruh Thanks for your eyes, it's caused by #2047. PR is coming.
