### ISSUE TITLE
After upgrading to React v16: Getting warning in console

### ISSUE THREAD

**Issue by maxmantz** [Semantic-Org/Semantic-UI-React#2128]
Hi,

after upgrading my project to use React v16, my app now renders with warnings. The warning I receive is related to a `Modal` inside my app and gives the following stacktrace:

![image](https://user-images.githubusercontent.com/6616421/30906846-5e0cf1d4-a379-11e7-915d-5b2c9f5723c2.png)

This is my `YesNoModal` throwing the warning:

```
function YesNoModal(props) {
  return (
    <Modal
      open={props.open}
      trigger={props.trigger}
    >
      <Modal.Header>
        {props.header}
      </Modal.Header>
      <Modal.Description>
        {props.description}
      </Modal.Description>
      <Modal.Actions>
        <IconButton positive icon="tick" onClick={props.onYesButtonClick}>
          <FormattedMessage id="app.Yes" />
        </IconButton>
        <IconButton negative icon="cancel" onClick={props.onNoButtonClick}>
          <FormattedMessage id="app.No" />
        </IconButton>
      </Modal.Actions>
    </Modal>
  );
}
```

And it is rendered here:

```
<YesNoModal
          trigger={
            <Form.Button negative onClick={props.onDeleteButtonClick}>
              <FormattedMessage id="app.components.RoleDetailView.deleteRole" />
            </Form.Button>
          }
          open={props.showDeleteConfirmModal}
          onClose={props.onDeleteCancel}
          onNoButtonClick={props.onDeleteCancel}
          onYesButtonClick={props.onDeleteConfirm}
          header={
            <FormattedMessage id="app.Warning" />
          }
          description={
            <FormattedMessage id="app.components.RoleDetailView.deleteDialog" />
          }
/>
```

Do you know what could cause this? Thank you in advance!

**Comment by layershifter** [comment]
I'm almost sure that you have something like this:

```jsx
<Modal>
  <Form.Button ref={handler} />
</Modal>
```

It's useless because `Form.Button` is stateless component and [can't have](https://stackoverflow.com/a/37269500/6488546) `ref` prop.

**Comment by maxmantz** [comment]
Thanks for the quick response but as you can see from my code I have no occurrence of a `ref` prop being passed into a button in my modal.

**Comment by layershifter** [comment]
Oh, I see now.

You passing it as `trigger`, this will be solved by #1879. For now, you can easily fix it (`Form.Button` is a sugar for `Form.Field` + `Button`):

```jsx
<Form.Field>
  <YesNoModal trigger={<Button></Button>} />
</Form.Field>
```

**Comment by maxmantz** [comment]
Perfect. Thank you!

**Comment by levithomason** [comment]
Good thing Button is also not a stateless functional component ;)
