### ISSUE TITLE
Support for Multiselection for the Search Module?

### ISSUE THREAD

**Issue by darewreck54** [Semantic-Org/Semantic-UI-React#2129]
Originally this was a question https://stackoverflow.com/questions/46445044/does-react-semantic-ui-search-support-multiselection

But not sure if this is the right place to request this feature or if there is a workaround to achieve the same effect.  It would make the dropdown module and the search module more consistent in behavior.

Thanks,
Derek

**Comment by layershifter** [comment]
Semantic UI [doesn't support](https://semantic-ui.com/modules/search.html) anything like this within the Search component. Non SUI features aren't priority for core team. However, contributions are welcome.

I think that use need `Dropdown` there, check [this example](https://react.semantic-ui.com/modules/dropdown#dropdown-example-remote), there is a small bug (#2126), but you can understand the idea. Pairing with [another](https://react.semantic-ui.com/modules/dropdown#dropdown-example-open-on-focus) usage features can be give possible same result.

**Comment by darewreck54** [comment]
@layershifter Thanks for the example.  Is there anyway to group the drop down selection.

Ex:

Click on drop down and i see

```
School            School1
                       School2
                       School3
City                 San Diego
                       LA

```
I notice that the options are just (key,text,value).  

In the search, there is the concept of cateogries and also resultRenderer that allows you to customize the look of the results in the search.  Does this exist for dropdown? 

Thanks,
Derek
