### ISSUE TITLE
Clicking on the title of the accordion should unfold the content

### ISSUE THREAD

**Issue by jfhenon** [Semantic-Org/Semantic-UI-React#2132]
BUG? 

### Steps
Using the component Accordion

### Expected Result
Clicking on the title of the accordion should unfold the content. 
### Actual Result
The accordion content is not visible after the click..

### Version
0.74.2

### Testcase
https://codepen.io/jfhenon/full/BwWGzW

**Comment by layershifter** [comment]
Please visit [docs](https://react.semantic-ui.com/modules/accordion), `Accordion` received the breaking refactor in #1375.

**Comment by jfhenon** [comment]
Indeed, sorry. 
JF
