### ISSUE TITLE
Search: the `id` prop on SearchResult should accept `string` as value

### ISSUE THREAD

**Issue by darewreck54** [Semantic-Org/Semantic-UI-React#2135]
From looking at the type definition for SearchResult.d.ts, the [key:strig]: any should allow me to add any additional props.  However, when in typescript it will give warnings about them.

Warning: Failed prop type: Invalid prop results supplied to Search

It seems like it doesn't effect the functionality, but console gets flooded with these warnings  Is this a typescript issue only and is there a workaround.

Example:

When you define the results:

```
  {
    "title": "Gusikowski LLC",
    "description": "User-friendly reciprocal parallelism",
    "image": "https://s3.amazonaws.com/uifaces/faces/twitter/alecarpentier/128.jpg",
    "price": "$34.11"
  }
```

In my case, I added 

```
  {
    "tester": "a"
    "title": "Gusikowski LLC",
    "description": "User-friendly reciprocal parallelism",
    "image": "https://s3.amazonaws.com/uifaces/faces/twitter/alecarpentier/128.jpg",
    "price": "$34.11"
  }

```

"tester" will be treated as an unknown property and warnings will come.

Also another question, is it possible to update the id to be an any.  In my case, i have a string value of a GUID but because it's a number I can't set it.  

```
export interface SearchResultProps {
  [key: string]: any;

  /** An element type to render as (string or function). */
  as?: any;

  /** The item currently selected by keyboard shortcut. */
  active?: boolean;

  /** Additional classes. */
  className?: string;

  /** Additional text with less emphasis. */
  description?: string;

  /** A unique identifier. */
  id?: number;
```
Thanks,
Derek

**Comment by layershifter** [comment]
> Warning: Failed prop type: Invalid prop results supplied to Search

This comes from `propTypes` and duplicates #1681.

> Also another question, is it possible to update the id to be an any. 

`any` - no, but I almost sure that it can string. Good suggestion, PR is comming.
