### ISSUE TITLE
Header - color props

### ISSUE THREAD

**Issue by Tilican** [Semantic-Org/Semantic-UI-React#2139]
"semantic-ui-css": "^2.2.12",
    "semantic-ui-react": "^0.74.2"

Error in Header component
```javascript
 <Header as='h2' color='instagram' textAlign='center'>}Log-in to your account</Header>
```
![error](https://i.imgur.com/rp1Gx1G.png)

but in documention they said "instagram" available

**Comment by layershifter** [comment]
Where have you seen this? `Header` doesn't support social colors, only `Button` component has them.
