### ISSUE TITLE
Search results with custom render throw warnings

### ISSUE THREAD

**Issue by HemalR** [Semantic-Org/Semantic-UI-React#2140]
### Steps
1. Create a standard Search component with a custom renderer as per docs here: https://react.semantic-ui.com/modules/search#search-example-standard-custom
2. Define a function that takes in the result and returns a renderable node (with a unique key)

### Expected Result
1. The rendered result nodes should have the key that is passed to them (and no other props)

### Actual Result
Each result is instead wrapped in an element (I believe a div) with all result properties passed on to this element as props. This throws two warnings:
1. Each child in an array or iterator should have a unique "key" prop. Check the render method of `Search`
2. Unknown prop `<property name 1, 2 3...>` on <div> tag. Remove this prop from the element. 

Example here: https://codesandbox.io/s/3rxzrq0rxp

- - - 
Note - Everything does work fine in terms of expected user interactions (they are both just minor warnings).

A workaround to number (1) is to ensure that the result object has a 'key' property. However, fixing (2) would break the workaround for (1).

I tried looking through the source code to see if I could find the cause/possibly a fix, but it's a bit too advanced for me :( 

For example - https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Search/SearchResult.js - the key 'content' in defaultRenderer would be the same across all results, which should throw off a warning as they should be unique?

I'll have another read through it all...

**Comment by layershifter** [comment]
Duplicate #1681.
