### ISSUE TITLE
Allow multiple labels for Input

### ISSUE THREAD

**Issue by madvas** [Semantic-Org/Semantic-UI-React#2148]
In normal Semantic-UI it's possible to have multiple labels for input. For example one on left side and one on right side. Semantic-UI-React Input component takes only 1 label parameter, so it's not possible to do here.

**Comment by madvas** [comment]
Okay, figured out I can do workaround with action property

**Comment by levithomason** [comment]
For others looking:

https://react.semantic-ui.com/elements/input#input-example-actions
