### ISSUE TITLE
Modal: Scrolling doesn't work properly after reopen

### ISSUE THREAD

**Issue by kien8995** [Semantic-Org/Semantic-UI-React#2150]
### Steps
1. Open scroll modal
2. Scroll modal
3. Close scroll modal
4. Open scroll modal again
5. Scroll modal 
### Expected Result
Modal must be scrollable
### Actual Result
Modal no longer scrollable
### Version
0.74.2

### Testcase
https://react.semantic-ui.com/modules/modal

**Comment by layershifter** [comment]
There are no need to scroll this modal. In fact, error comes from this [condition](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.74.2/src/modules/Modal/Modal.js#L258). After modal will be closed it should reset scrolling state as I think:

```diff
  handleClose = (e) => {
    debug('close()')

    const { onClose } = this.props
    if (onClose) onClose(e, this.props)

-    this.trySetState({ open: false })
+    this.trySetState({ open: false }, { scrolling: undefined })
  }
```
