### ISSUE TITLE
Docs: local docs site is broken with React 15.6.2

### ISSUE THREAD

**Issue by ayastreb** [Semantic-Org/Semantic-UI-React#2153]
### Steps
- I do a clean install (`rm -rf ./node_modules/ && node install`)
- I try to run local docs site for local development
- I run `npm start` as per [contributing.md](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/.github/CONTRIBUTING.md#documentation)
- I open `http://localhost:8080/` in a browser
### Expected Result
- Local docs side is loaded
### Actual Result
- I get blank page and JS error `Uncaught ReferenceError: React is not defined` and HTTP 404 http://cdnjs.cloudflare.com/ajax/libs/react/15.6.2/react.min.js

Looks like it happens because I have React 15.6.2 installed and cloudflare CDN doesn't have this version for some reason.
A workaround could be to lock React to 15.6.1 in `package.json`, e.g. `"react": "15.6.1"` instead of `"react": "^15.6.1"`
Any other ideas? 🤔

**Comment by layershifter** [comment]
Use `yarn`? :smile: We have lockfile, so you can install deps without any problems. However, now we use three CDNs. I'm think that we can switch to jsdelivr as they have all needed deps.

**Comment by ayastreb** [comment]
Hmm, yes, maybe I should finally try using `yarn`. I assumed `yarn` and `npm` are interchangeable and was always too lazy to install `yarn` 😆

**Comment by brianespinosa** [comment]
@ayastreb let us know if that worked for you. Performance is better with `yarn` since it caches packages locally once you've installed them. Additionally, it is just better at consistently resolving packages. Lots of great stuff in there.

**Comment by ayastreb** [comment]
@brianespinosa yes, it works with `yarn`, thanks!

**Comment by levithomason** [comment]
`npm` has sadly become a mess.
