### ISSUE TITLE
Several warnings on Attached Layout

### ISSUE THREAD

**Issue by arimourao** [Semantic-Org/Semantic-UI-React#2154]
I just installed semantic-ui-react to do some tests and maybe implement in an ongoing project. Right off the bat I get plenty of warnings just copying and pasting the sample code given in "attached content" layout section. It seems to work ok, but here are some of the warnings:

`Warning: Failed prop type: Invalid prop `attached` supplied to `Message`.`

`Warning: Unknown prop `verticalAllign` on <table> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

`Warning: validateDOMNesting(...): <th> cannot appear as a child of <thead>. See AdminPanel > TableHeader > thead > TableHeaderCell > TableCell > th.`

`Warning: Unknown prop `verticalAllign` on <table> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

**Comment by layershifter** [comment]
Please fill our issue template.

**Comment by levithomason** [comment]
We've misspelled `verticalAllign` in the example. Align should not have 2 Ls.  I wonder why we aren't seeing these prop warnings locally though?

**Comment by levithomason** [comment]
We also have `<Message attached='top' />` in the example, but the prop type is:

```js
    attached: PropTypes.oneOfType([
      PropTypes.bool,
      PropTypes.oneOf(['bottom']),
    ]),
```

We should arguably accept `top` as a valid value for symmetry.
