### ISSUE TITLE
Upgrade peer dependency to allow React 16?

### ISSUE THREAD

**Issue by nwwells** [Semantic-Org/Semantic-UI-React#2157]
I'm happy to help test this more extensively, but my initial tests seem promising: that is, it doesn't just blow up.

The release announcement: https://reactjs.org/blog/2017/09/26/react-v16.0.html
Breaking changes: https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes

### Steps
Install the package

### Expected Result
No warnings about incompatible peer dependencies

### Actual Result
Warnings about incompatible peer dependencies:
```
warning "semantic-ui-react@0.74.2" has incorrect peer dependency "react@>=0.14.0 <= 15".
warning "semantic-ui-react@0.74.2" has incorrect peer dependency "react-dom@>=0.14.0 <= 15".
```

### Version
semantic-ui-react@0.74.2

### Testcase
N/A

**Comment by layershifter** [comment]
Duplicate #2131.
