### ISSUE TITLE
Transition Group example in docs doesn't reflect removed users

### ISSUE THREAD

**Issue by Inucoder** [Semantic-Org/Semantic-UI-React#2160]
### Steps
1. Go to Transition Group example at https://react.semantic-ui.com/modules/transition#transition-example-group
2. Click on the `plus`button 3 times, as expected 6 users show up and `plus` button gets disabled.
3. Click on the `minus` button once, as expected, the last user in the list (Helen) is removed.
4. Click on the `minus` button once again.
### Expected Result
The last user from the list (Elliot) should be removed from it the second time the `minus` button is clicked.
### Actual Result
The last user from the list (Elliot) remains there.
### Version
0.74.2

### Testcase
![image](https://user-images.githubusercontent.com/1755681/31140891-7be08ce0-a83b-11e7-9924-18dd181b3e1d.png)

**Comment by levithomason** [comment]
Duplicate https://github.com/Semantic-Org/Semantic-UI-React/issues/2127.

It was fixed and will be updated with the next release.
