### ISSUE TITLE
Dropdown: Does not display value on enter when using search selection

### ISSUE THREAD

**Issue by davidhenley** [Semantic-Org/Semantic-UI-React#2161]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - http://stackoverflow.com/search?q=semantic-ui-react

✔ BUGS → This form is required:

### Steps
```
<Form.Dropdown
      label={label}
      search
      selection
      selectOnBlur={false}
      selectOnNavigation={false}
      options={options}
      value={input.value}
      onChange={(param,data) => input.onChange(data.value)}
    />
```

Search a couple of letters in dropdown search selection
Arrow down to selection
Hit enter

### Expected Result
Call onChange and displays new value in input box

### Actual Result
Calls onChange but displays the searched letters instead of new value
OnBlur sets display of input box to value

### Version
0.74.2

### Testcase
[Fork, update, and replace this pen to show the bug]:
http://codepen.io/levithomason/pen/ZpBaJX

**Comment by layershifter** [comment]
Please respect our time and fill issue template fully, i.e. make a working codepen.
