### ISSUE TITLE
the code not working

### ISSUE THREAD

**Issue by raghuth** [Semantic-Org/Semantic-UI-React#2169]
**Steps to Reproduce**
1. Do something
2. Do something else.

**Expected**
The Search should do this

**Result**
The Search does not do this

**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/modules/search#search-example-category-custom
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by levithomason** [comment]
This appears to be working to me.  Please complete the form if there is a bug.

![http://g.recordit.co/lf2LsYkiao.gif](http://g.recordit.co/lf2LsYkiao.gif)
