### ISSUE TITLE
(List): Getting error "React.createElement: type is invalid"

### ISSUE THREAD

**Issue by tugaybaltaci** [Semantic-Org/Semantic-UI-React#2172]
I tried to use SemanticUI.List component in my listing page but I got this error below.
PS: I tried import without brackets, same error.

```javascript
import React, {Component} from 'react'
import {List} from 'semantic-ui-react'
```
```javascript
export default class ListPageBlabla extends Component {
```
```javascript
render() {
    return (
    <List>
        <List.Item key={item.key}>
            <List.Icon name="globe" size="large" verticalAlign="middle"/>
                <List.Content>
                    <List.Header as="a">{item.name} <small>{item.url}</small></List.Header>
                        <List.Description>
                            <Link to={`/${item.key}/add`}><Icon color="blue" name="plus"/></Link>
                            <Link to={`/${item.key}`}><Icon color="green" name="pencil"/></Link>
                            <Link to={item.url} target="_blank"><Icon color="black" name="eye"/></Link>
                            <Link to="#" onClick={() => this.removeSite(item.key)}><Icon color="red" name="remove"/></Link>
                        </List.Description>
                </List.Content>
        </List.Item>
    </List>
    );
}
```

**Expected**
Listing items

**Result**
Error: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/elements/list#list-example-divided
Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by layershifter** [comment]
You're using `Icon` from `semantic-ui-react` and `Link` from `react-router`, while I don't see imports for them.

Please, push your code to https://codesandbox.io/ There is no error with library.

**Comment by thatramen** [comment]
I had a scope function named "List". That's why I've got that error. Solved ^^
