### ISSUE TITLE
Button text not showing in Firefox 56.0

### ISSUE THREAD

**Issue by mjsolidarios** [Semantic-Org/Semantic-UI-React#2177]
### Steps
Visit [Symantic UI React buttons documentation](https://react.semantic-ui.com/elements/button#button-example-button) using Firefox 56.0 or Firefox Developer Edition.

### Expected Result
![snap2](https://user-images.githubusercontent.com/7346165/31324084-4f818ffa-ace1-11e7-9bb5-0d2991219ff1.png)

### Actual Result
![snap1](https://user-images.githubusercontent.com/7346165/31324061-0d3ba504-ace1-11e7-9450-e86277a11d1b.png)

### Version
0.74.2

**Comment by layershifter** [comment]
Checked with `56.0` and `57.0b6` on Ubuntu. Can't confirm this bug.

Please check it again add more information (OS, etc.).

**Comment by mjsolidarios** [comment]
Thanks! Got it fixed after reinstalling FF.
