### ISSUE TITLE
Cannot read property 'findDOMNode' of undefined when putting Popup nav bar

### ISSUE THREAD

**Issue by Smaxor5** [Semantic-Org/Semantic-UI-React#2183]
Hey guys, 

Trying to make an "amazon like" menu in my navbar.  Decided on using Popup instead of Dropdown since I need a grid and segments in there.  Tried putting the following in my code:

<Popup
                    trigger={<Button icon='add' />}
                        flowing
                        hoverable
                    >
                        <Grid>
                            <Grid.Column width={4}>
                                <Menu  vertical tabular>
                                    <Menu.Item name='bio'   />
                                    <Menu.Item name='pics'   />
                                    <Menu.Item name='companies'  />
                                    <Menu.Item name='links'   />
                                </Menu>
                            </Grid.Column>

                            <Grid.Column width={12}>
                                <Segment>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar pharetra ornare. Mauris sed finibus nulla. Ut molestie placerat augue nec consequat. In tristique quis mauris ut consectetur. Mauris dignissim tempor eros et gravida. Ut vel faucibus nisl, ac porta dolor. Morbi quis ultricies urna. Suspendisse scelerisque auctor risus sit amet faucibus. Nunc non orci et nisl fringilla euismod.</p>
                                    <p>Suspendisse potenti. Vestibulum tincidunt vitae lorem id pellentesque. Cras vitae dapibus lacus. In elementum orci tellus. Duis tortor nulla, placerat ut cursus at, auctor at mi. Integer fermentum commodo congue. Nunc molestie ultricies pellentesque. Maecenas scelerisque vitae arcu at mollis. Mauris quis quam leo.</p>
                                    <p>Donec accumsan metus neque. Nam consequat nisl risus, ut ornare tellus efficitur id. Donec in leo est. Proin molestie enim vitae nulla ultrices, rutrum tristique metus varius. Proin volutpat nisi vitae erat faucibus varius in in leo. Quisque sit amet libero id augue accumsan finibus in ullamcorper libero. Sed ipsum quam, gravida suscipit magna eu, viverra bibendum elit.</p>
                                </Segment>
                            </Grid.Column>
                        </Grid>
                    </Popup>

and I get "Cannot read property 'findDOMNode' of undefined".  Can still see the button though.  Looked around google and couldn't find anything on this.  It doesn't break when I take the button out.  Any idea on what could be the cause of this?

Thanks!

**Comment by brianespinosa** [comment]
Hi, @Smaxor5 could you please make a codepen example of your issue? Having a working code example is going to be easier to investigate your issue. You can fork this Pen to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by layershifter** [comment]
```jsx
<Popup trigger={} />
```

I'm almost sure that problem is that the `trigger` is empty while it should a valid React node. Closing until we'll have the disproving codepen.

**Comment by Smaxor5** [comment]
It isnt because of the empty trigger, I copied the wrong code.  It has the following and doesn't work 

```
{<Button icon='add' />}
```

**Comment by brianespinosa** [comment]
@Smaxor5 sorry... it is all guessing unless we have a working codepen example to look at.

**Comment by Smaxor5** [comment]
FYI: I had to put ReactDom before react-semantic in page sources.  All set!
