### ISSUE TITLE
Form.Select can't accept `null` as its value.

### ISSUE THREAD

**Issue by RickyLin** [Semantic-Org/Semantic-UI-React#2185]
I'm a rookie of TypeScript/React, trying to use this excellent project to study React development with TypeScript. I got a problem, the `Form.Select` doesn't accept `null` as its `value`.

### Steps

Here's a sample code:

```
<Form.Input label="undefined" value={undefined} />
<Form.Input label="null" value={null} />

<Form.Select label="undefined" options={[{ key: 1, text: 'AAA', value: 'aaa' }]} value={undefined} />
<Form.Select label="null" options={[{ key: 1, text: 'AAA', value: 'aaa' }]} value={null} />
```

### Expected Result

There's no error at all.

### Actual Result

`Form.Input` can accept both `undefined` and `null` as its value, but `Form.Select` can only accept `undefined` as its value, `null` value results in the following error:

> error TS2322: Type '{ label: "null"; options: { key: number; text: "AAA"; value: string; }[]; value: null; }' is not assignable to type 'IntrinsicAttributes & FormSelectProps & { children?: ReactNode; }'.
>  Type '{ label: "null"; options: { key: number; text: "AAA"; value: string; }[]; value: null; }' is not assignable to type 'FormSelectProps'.
>    Types of property 'value' are incompatible.
>      Type 'null' is not assignable to type 'string | number | Key[] | undefined'.

### Version
"react": "^16.0.0",
"react-dom": "^16.0.0",
"react-scripts-ts": "2.7.0",
"semantic-ui-css": "^2.2.12",
"semantic-ui-react": "^0.74.2"

### Testcase
https://codepen.io/anon/pen/dVjoLw?editors=1111

It works in codeine.io, I think my problem is about type definition in TypeScript

### Why I need to set `null` as value of `React.Select`

I get data in the form of `{ countryId: null }` from server side and I use it like this: `<Form.Select value={this.props.address.countryId}`

in server side, it's C# code:

```csharp
public class Address
{
    // it will generate { countryId: null } if the value of this property is null 
    public int? CountryId { get; set; }
}
```

**Comment by layershifter** [comment]
The `null` isn't valid value in fact, you should use `undefined`.

The `Form.Input` accepts it because this prop isn't actually controlled by component. All unhandled props can be [`any`](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.74.2/src/elements/Input/Input.d.ts#L11). I'm almost sure that we don't need to change something there because optional props in typescript should match defined type or be `undefined`.

**Comment by GregorioF2** [comment]
how `undefined` is more of a value than `null`. I don't remember any SQL storing `undefined` values on it's rows.

**Comment by layershifter** [comment]
You can't do the same with React primitives:

```tsx
<select value={null} />
//             ^ Type 'null' is not assignable to type 'string | number | readonly string[] | undefined'.ts(2322)
//               index.d.ts(2272, 9): The expected type comes from property 'value' which is declared here on type 'DetailedHTMLProps<SelectHTMLAttributes<HTMLSelectElement>, HTMLSelectElement>'
```

https://codesandbox.io/s/eloquent-haze-d8wcs?file=/src/App.tsx:98-122
