### ISSUE TITLE
Accordion does not open and close anymore.  Worked in 0.71.5 and not in 0.74.2

### ISSUE THREAD

**Issue by darewreck54** [Semantic-Org/Semantic-UI-React#2186]
### Steps
1) https://codepen.io/darewreckk/pen/pWKXNd?editors=1111 (working open and closing of accordion 0.71.5)
2) https://codepen.io/darewreckk/pen/GMGbrp?editors=1111 (not working and closing of accordion 0.74.2)

It works when you use the panels props for Accordion, but if you choose to fill in the child yourself it's broken

### Expected Result
1) https://codepen.io/darewreckk/pen/pWKXNd?editors=1111 (working open and closing of accordion 0.71.5)

open and closing of the accordion

### Actual Result
 https://codepen.io/darewreckk/pen/GMGbrp?editors=1111 (not working and closing of accordion 0.74.2)

Accordion doesn't open and close

### Version
0.74.2

### Testcase
Test Case is above

**Comment by brianespinosa** [comment]
@darewreck54 there was a breaking refactor change to Accordion in 0.74.0. Changes like this _should_ show up in the Changelog. https://github.com/Semantic-Org/Semantic-UI-React/blob/master/CHANGELOG.md#v0740-2017-09-24

**Comment by darewreck54** [comment]
ic.  Thanks it was confusing because the documentation usage of accordion has not been updated.    Maybe if possible put a note of this.

**Comment by layershifter** [comment]
There was a breaking change in #1375.

> it was confusing because the documentation usage of accordion has not been updated

All examples were updated and work correctly, if any example there doesn't work, please create the new issue.
