### ISSUE TITLE
Long modals are only scrollable the first time they are opened

### ISSUE THREAD

**Issue by hanshenrik** [Semantic-Org/Semantic-UI-React#2187]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - http://stackoverflow.com/search?q=semantic-ui-react

✔ BUGS → This form is required:

### Steps
1) Go to https://react.semantic-ui.com/modules/modal
2) Open a long modal that will cause the scrollbar to appear
3) Scroll
4) Close the modal
5) Open it again
6) Try to scroll

### Expected Result
The scrollbar should be available every time the modal is opened

### Actual Result
The scrollbar is only available the first time the modal is open, leaving the user unable to scroll down to see the whole modal on subsequent openings.

### Version
0.74.2

### Testcase
https://react.semantic-ui.com/modules/modal

![long-modal-only-scroll-first-open](https://user-images.githubusercontent.com/3757042/31495243-2b8ff302-af57-11e7-9cd7-d7ff320ac683.gif)

**Comment by patrikmolsson** [comment]
Already fixed in https://github.com/Semantic-Org/Semantic-UI-React/pull/2152

**Comment by layershifter** [comment]
Duplicate #2150.
