### ISSUE TITLE
(feat): support transparent for TextArea

### ISSUE THREAD

**Issue by hubertguillemain** [Semantic-Org/Semantic-UI-React#2188]
for Read only fields, I use <Form.Input> with the props transparent and readOnly, which renders a nice text, not editable but still selectable.

I would like to  have the same look and feel for TextArea

**Comment by layershifter** [comment]
`transparent` is the `Input` prop, it simply passed to it from `Form.Input`. `TextArea` doesn't support any styling except proposed by the `Form`.

We don't handle any CSS issues there, you should post your request on the main repo: https://github.com/Semantic-Org/Semantic-UI

P.S. Don't forget to fill the issue there fully and convert all code in it to the HTML markup.
