### ISSUE TITLE
Dropdown control doesn't handle new options if the dropdown is open.

### ISSUE THREAD

**Issue by davewthompson** [Semantic-Org/Semantic-UI-React#2189]
### Steps
1. Create a Dropdown control with Multiple and Search modes enabled. Options should be read from the state, a-la this.state.options.
2. Add code in the onSearchChange method to request options from a remote URL.
3. On response set the options using this.setState({options:[xx]});

### Expected Result
The dropdown will populate with items inside the options collection.

### Actual Result
No items are added to the open dropdown.

### Version
0.71.1

### Testcase
To be added...

**Comment by layershifter** [comment]
Please fill issue template fully and add codepen.
