### ISSUE TITLE
docs(ButtonExampleLabeledIcon): buttons aren't labeled

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#2190]
**Steps to Reproduce**
1. Open the link in the testcase.

**Expected**
The Buttons should each be `labeled icon` buttons.

**Result**
The Buttons have an icon, but aren't labeled.  They should also be `vertical` as inline `labeled icon` buttons do not look good.

**Testcase**
https://react.semantic-ui.com/elements/button#button-example-labeled-icon

***

### SUIR

![image](https://user-images.githubusercontent.com/5067638/31516513-a7cd3f56-af4d-11e7-84d0-861297b2ecde.png)

### SUI Core

![image](https://user-images.githubusercontent.com/5067638/31516518-aee4370e-af4d-11e7-98e8-8ff4bae66be3.png)

***

### The Fix

The Button.Group in the example should be updated to include `vertical labeled icon` props.

**Comment by patrikmolsson** [comment]
@levithomason I opened a PR for this in https://github.com/Semantic-Org/Semantic-UI-React/pull/2191
