### ISSUE TITLE
Update Search widget documentation with supported "placeholder"

### ISSUE THREAD

**Issue by darewreck54** [Semantic-Org/Semantic-UI-React#2194]
Hi,

This isn't really a bug, but just realized that the search widget has a property called "placeholder" that is not in the usage documentation.  

Thanks,
Derek

**Comment by richin13** [comment]
That's an HTML property and not a element prop. Just like `style` or `className`

**Comment by layershifter** [comment]
Fully agree with @richin13

**Comment by darewreck54** [comment]
Thanks.  Didn't know the html property carries over like that with a react component.

**Comment by richin13** [comment]
It's more a Semantic UI React feature, I think :smile:

**Comment by darewreck54** [comment]
@richin13 is this stated in any of the usage documentation that  semantic react takes the input html property as well?

**Comment by richin13** [comment]
I am not an expert but I think it has to do something with the Augmentation feature stated in https://react.semantic-ui.com/introduction. It says:

> Extra props are passed to the component you are rendering `as`

Even though you are not using `as` in the Search component, the "extra props" (the ones not in the documentation --html "native" props e.g--) are still passed down to the component's children
