### ISSUE TITLE
Modal with inverted dimmer hides close icon on desktop

### ISSUE THREAD

**Issue by zachhale** [Semantic-Org/Semantic-UI-React#2201]
### Steps

Open modal with inverted dimmer on desktop.

### Expected Result

The close icon is grey on inverted dimmer mode.

### Actual Result

The close icon is white and invisible.

### Version
0.75.0

### Testcase
https://codesandbox.io/s/4mm54nm7w

**Comment by layershifter** [comment]
This issue is valid, but it's a CSS only, please post in on main repo: https://github.com/Semantic-Org/Semantic-UI Don't forget, to port your markup to HTML when you will create an issue.
