### ISSUE TITLE
Dropdown: Clicking input field in menu immediately closes menu instead of providing chance to type

### ISSUE THREAD

**Issue by wallslide** [Semantic-Org/Semantic-UI-React#2203]
### Steps

https://react.semantic-ui.com/modules/dropdown#dropdown-example-search-in-menu

Open the dropdown, attempt to type in the input field.

### Expected Result

Clicking on the input will place cursor inside input, and allow user to type

### Actual Result

Dropdown menu immediately closes upon clicking on input

**Comment by layershifter** [comment]
Duplicate #1593.
