### ISSUE TITLE
Responsive: "ReferenceError: window is not defined"

### ISSUE THREAD

**Issue by mrtysn** [Semantic-Org/Semantic-UI-React#2206]
### Steps
Use Responsive component in a server side rendered project.

### Expected Result
The component works as expected.

### Actual Result
Throws error
> ReferenceError: window is not defined

### Version
0.75.0

### Testcase
Pull, and deploy https://github.com/mrtysn/heroku-nextjs to heroku.
OR
Visit: https://mrtysn-sui-responsive-ssr.herokuapp.com/. You might have to wait for it to "wake up" since it's a free instance.

I've stumbled upon #1990, which fixes this issue for Sticky and Visibility. Since Responsive was introduced recently at v0.73.0, I believe this occasion was not though of.

**Comment by layershifter** [comment]
@mrtysn Thanks for report, was fixed in #2209
