### ISSUE TITLE
Reveal on Fade blocks user input for hidden (then visible) content

### ISSUE THREAD

**Issue by joehannes-zz** [Semantic-Org/Semantic-UI-React#2207]
✔ BUG

### Steps
Create Reveal with Button in hidden content with fade-animation

### Expected Result
Button is clickable and actionable

### Actual Result
visible overlay only seems to be opacity invisible and still blocks input from hidden (now visible) content (button) -> can't click button

### Version
semantic-ui: 2.2.13
semantic-ui-react: 0.72.0

### Testcase
https://codesandbox.io/s/2wk9jjz4n0

**Comment by layershifter** [comment]
This issue is valid, but it's a CSS only, please post in on main repo: https://github.com/Semantic-Org/Semantic-UI Don't forget, to port your markup to HTML when you will create an issue.

Hidden content is unaccessible because it has lower `z-index` than visible.

**Comment by joehannes-zz** [comment]
Sorry, don't have time to report this twice. Anyway, I think it reuires js to resolve this. Z-Index alone won't. You need to display: none, or z-index after the transition, which requires js. Cheers

**Comment by levithomason** [comment]
As a workaround, you could disable pointer events on the Reveal Content:

```jsx
<Reveal.Content visible style={{ pointerEvents: 'none' }} />
```

This is not ideal as it causes the button to be clickable at all times, however, it is more desirable than a non-clickable button.

**Comment by levithomason** [comment]
Also, this doesn't require JS as the z-index can be accomplished with the same CSS transition rules in place for the content animation.  Here's an example where the `z-index` of the child is changed 1s after `:hover` on the container:

https://codepen.io/levithomason/pen/qPgBba

![http://g.recordit.co/RbL2ZCUJ74.gif](http://g.recordit.co/RbL2ZCUJ74.gif)
