### ISSUE TITLE
can't set undefined value for control input or textfield

### ISSUE THREAD

**Issue by ElfenLiedGH** [Semantic-Org/Semantic-UI-React#2210]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes

✔ BUGS → This form is required:

### Steps

try set undefined value for Input or TextArea via state

### Expected Result

input value is undefined

### Actual Result

state.value === undefined but input value is old value

### Version
0.71.2

### Testcase
https://codesandbox.io/s/3q51385485
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/3q51385485

**Comment by levithomason** [comment]
In React, `undefined` is equivalent to not setting any value.  Set an empty string `''` to clear an input or textarea's value.  Working fork:

https://codesandbox.io/s/3qymy21px5

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.75.1`
