### ISSUE TITLE
Scrollbar in long dropdown doesn't work correctly in Firefox

### ISSUE THREAD

**Issue by jiriseda** [Semantic-Org/Semantic-UI-React#2214]
### Steps
1. have dropdown with tens of items and scrollbar
2. try to move scrollbar down by the help of catching  and moving mouse cursor down

### Expected Result
Scrolling works

### Actual Result
Scrollbar stay in top position (scrolling via mouse wheel works fine)
### Version
0.73.0

**Comment by layershifter** [comment]
Please make a codepen and provide your version of Firefox. Closing until we will able to reproduce that.

**Comment by levithomason** [comment]
When submitting the reproduction case, please use the latest version as well.  While in development, we only support the current `0.x` version.

**Comment by jiriseda** [comment]
I used latest Firefox 56.0.1.

Sorry, I cannot easy perform test with latest version of Semantic-UI-React because of your refactoring of Accordion in 0.74.0, I think, there is also bug, because after the refactoring handling onTitleClick doesn't work correctly in combination of exclusive={false} activeIndex={activeIndex}
