### ISSUE TITLE
Image: Inconsistent prop usage between Image and Icon for circular shape

### ISSUE THREAD

**Issue by zxlin** [Semantic-Org/Semantic-UI-React#2217]
### Steps
Currently to create a circular image and a circular icon, we would do the following:
```html
<Image shape='circular' src='url' />

<Icon circular name='icon' />
```
but that's really inconsistent, especially where `Image` and `Icon` can be used interchangeably such as in `Header`
### Expected Result
Ideally, both `Image` and `Icon` would use bool props for adjective based attributes as it is the case with many other attributes like `disabled`, `bordered`, etc...
```html
<Image circular src='url' />

<Icon circular name='icon' />
```
### Version
0.75.1

Please let me know if there is a reason to keep it the way it is.

**Comment by layershifter** [comment]
`Image` supports also `rounded` shape, that's why we have `rounded` prop. I think that the better solution will replace `circular` prop with `shape`. @levithomason what you think?

**Comment by zxlin** [comment]
That's fine too, there just needs to be some consistency with this.

**Comment by layershifter** [comment]
@zxlin feel free to open PR :+1:

**Comment by levithomason** [comment]
Yes on consistency.  The `shape` grouping is the odd ball here:

```jsx
<Buton circular />
<Label circular />
<Segment circular />
<Icon circular />
```

Let's fix the `Image` to be consistent.

**Comment by RetroCraft** [comment]
I think this is what @levithomason was getting at, please review and let me know if there's anything wrong. 

I'm pretty new to this whole open source thing.
