### ISSUE TITLE
Cannot load fonts on Meteor 1.5

### ISSUE THREAD

**Issue by pippo111** [Semantic-Org/Semantic-UI-React#2218]
Hi,

I'm using Meteor 1.5 with React Semantic UI 0.75.1 and CSS 2.2.12.

After importing sui in my client/index.js
`import 'semantic-ui-css/semantic.min.css'`

Icons are not loading:
`Failed to decode downloaded font: http://localhost:3000/items/themes/default/assets/fonts/icons.woff2
tickets:1 OTS parsing error: invalid version tag
tickets:1 Failed to decode downloaded font: http://localhost:3000/items/themes/default/assets/fonts/icons.woff
tickets:1 OTS parsing error: invalid version tag
tickets:1 Failed to decode downloaded font: http://localhost:3000/items/themes/default/assets/fonts/icons.ttf
tickets:1 OTS parsing error: invalid version tag`

When I copied font files into public it is working but only on root path. On subpages they are not loading.

How to fix this ?

**Comment by layershifter** [comment]
We don't handle CSS related issues there. I almost sure that there is problem with the path of fonts, it seems that they doesn't exist there. There also was similar issue Semantic-Org/Semantic-UI-Meteor#55.
