### ISSUE TITLE
Dropdown: maxSelections

### ISSUE THREAD

**Issue by davioliveiira** [Semantic-Org/Semantic-UI-React#2224]
This element `<Dropdown />` not have support for `maxSelections`? #

**Comment by layershifter** [comment]
No, we don't have support of `maxSelections`. Contributions are welcome.

**Comment by patrikmolsson** [comment]
How would this work? Would it simply just not allow the user to select more items when the cap is reached?

How can we communicate this to the user? Shall we leave it to the developer how to handle when the cap is reached - maybe with a custom callback?

**Comment by patrikmolsson** [comment]
@layershifter Any suggested implementation for this? I would gladly help with it.

**Comment by layershifter** [comment]
@patrikmolsson you can use [these](https://semantic-ui.com/modules/dropdown.html#maximum-selections) examples as reference behaviour

**Comment by patrikmolsson** [comment]
@layershifter Thanks! :grin:  I'm on it.

**Comment by fazlulkarimweb** [comment]
I'm posting my workaround here for people who are trying to find a solution on google. 

At first, save the values in the state (preferably redux state) after every onChange. React state also would do fine. Then, make it disabled when a certain array length of the value is reached. 

```js
const districtData = ['Dhaka', 'Bagerhat', 'Bandarban', 
'Barguna', 'Barishal', 'Bhola']

const [districtValue, setDistrictValue] = useState();

<Dropdown
onChange={async (e, { name, value }) => {setDistrictValue(value)}}
options={districtData.map((currentValue, index) => {
    return {
    key: `${currentValue}`,
    value: `${currentValue}`,
    text: `${currentValue}`,
    disabled: districtValue.length > 2 ? true : false 
}
// Do other things here
// Max 3 values here, then options will be disabled. 
// Will be live again if any selected options are less than 3 here                

/>
```
