### ISSUE TITLE
Test: Cannot run local tests without modifying test config

### ISSUE THREAD

**Issue by patrikmolsson** [Semantic-Org/Semantic-UI-React#2227]
When running ```yarn test``` on local environment (Arch Linux) I ran into the issues described in: https://github.com/GoogleChrome/puppeteer/issues/290. Although, just adding the flags as described in the referred issue wasn't enough. 

I also had to rename the browser: https://github.com/Semantic-Org/Semantic-UI-React/blob/4f29636738fffbaf3b8bcd179f85b0f2c2248b7b/karma.conf.babel.js#L32 in the test config file to reflect the key in the customLaunchers: https://github.com/Semantic-Org/Semantic-UI-React/blob/4f29636738fffbaf3b8bcd179f85b0f2c2248b7b/karma.conf.babel.js#L47

I.e. I renamed ```ChromeHeadless``` browser to ```puppeteer``` and added the flags ```--no-sandbox``` and ```--disable-setuid-sandbox``` on the customLauncher, since the flags wasn't respected when trying to run the browser. This leads me to believe the flag present today (```--stack-trace-limit 50000```) isn't respected as well.

Is this something we need to address? We should maybe communicate how to do the work-around to add the ```--no-sandbox``` and ```--disable-setuid-sandbox``` flags in case more users run into this issue as well.

**Comment by layershifter** [comment]
@patrikmolsson Thanks :+1: Feel free to open PR that will contain described changes.

**Comment by patrikmolsson** [comment]
@layershifter Sure, I'll get to it the upcoming week :)
