### ISSUE TITLE
Dropdown: can't enter a space while the dropdown is closed

### ISSUE THREAD

**Issue by matb33** [Semantic-Org/Semantic-UI-React#2229]
### Steps
See Testcase below.

### Expected Result
Should be able to enter a space while the dropdown does not yet have its `open` state set to `true` while manually controlling `open` via prop.

### Actual Result
User is prevented from hitting space, due to this line:
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L564

### Version
0.75.1

### Testcase
https://codesandbox.io/s/6kplzo63w

### Recommended fix
It is insufficient to rely on `this.state.open` to determine if one should act on `openOnSpace` or `openOnFocus`. Before even checking for `this.state.open`, it should be checked if `this.props.open` is also truthy. The lines in question are:
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L453-L454

I suggest changing line 453 from:

```
if (!this.state.open) {
```
to
```
if (!this.props.open && !this.state.open) {
```

That being said, I have not opened a pull request because I suspect there may be more to fixing this due to how `open` is controlled via `AutoControlledComponent` and how props are copied to state... I don't fully comprehend the ramifications so I will leave this one to you guys.

**Comment by layershifter** [comment]
Thanks for report and test case, it is appreciated :+1: As I see this problem comes from this [method](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.75.1/src/modules/Dropdown/Dropdown.js#L558), however I'm not sure that it's safely to remove `e.preventDefault()` there

**Comment by matb33** [comment]
Right, and I agree don’t remove that line. The issue is simply that when the open state of the dropdown is manually controlled by the open prop, this should ultimately override the openOnSpace and openOnFocus functionality.

**Comment by beaugunderson** [comment]
we hit this too, our (incredibly janky) workaround was something like this:

```
onFocus = () => this.setState({ forceOpen: true },
  () => this.setState({ forceOpen: false }));
```

```
isOpen = () => this.state.forceOpen || realCondition;
```

```
<Dropdown open={this.isOpen()} />
```

**Comment by Victor2333** [comment]
My solution:
```
import { Dropdown } from 'semantic-ui-react';
export default class PageDropdown extends Dropdown {
    constructor(props) {
        super(props);
    }

    openOnSpace = (e) => {
        return;
    }
} 
```
It works. But it will give up openOnSpace function.
