### ISSUE TITLE
Portal: Button has undefined data in event handler

### ISSUE THREAD

**Issue by Yoruba** [Semantic-Org/Semantic-UI-React#2233]
### Steps
Click on 'button with popup'

### Expected Result
Data to be defined in event handler

### Actual Result
Data is undefined

### Version
0.75.1

### Testcase
[Codepen with code](https://codepen.io/Yoruba/pen/OxGjRB)

Click on 'button with popup' 

> undefined

Click on 'button'

> {icon: "add", children: "button", as: "button", onClick: ƒ}

**Comment by layershifter** [comment]
@Yoruba Thanks for report, will be fixed by #2234.
