### ISSUE TITLE
GRID: Warning when using the padded property

### ISSUE THREAD

**Issue by brahimmouhamou** [Semantic-Org/Semantic-UI-React#2237]
### Steps
Just use the padded property on a Grid component:
`<Grid padded={1}></Grid>`

### Expected Result
This should not trigger an warning.

### Actual Result
```
Warning: Failed prop type: Invalid prop `padded` supplied to `Grid`.
    in Grid (created by App)
    in App
```

### Version
0.75.1

### Testcase
https://codesandbox.io/s/mq6x0z76vj

**Comment by brianespinosa** [comment]
@brahimmouhamou the `padded` prop is either boolean or one of the following enum strings: `horizontally`, `vertically`. A number, as you are trying to pass, will throw a prop type error.

https://react.semantic-ui.com/collections/grid

**Comment by brianespinosa** [comment]
@levithomason I don't see the controls to close this issue. Do I need to confirm my contributor duties somewhere?

**Comment by layershifter** [comment]
@brianespinosa gave correct answer.

>  I don't see the controls to close this issue.

I think it will be better if you will write to Levi on email :smile:
