### ISSUE TITLE
toogle button data.checked value is inversed

### ISSUE THREAD

**Issue by jasan-s** [Semantic-Org/Semantic-UI-React#2240]
Fore some reason the toggle button returns `true` when the toggle button is inactive and when toggles to active state the
`data.checked` returns false. 
I have to do the following `  handleToogle = (event, data) => {
  	console.log(!data.checked)
  }`

to correct this.

using `"semantic-ui-react": "^0.71.4",`

**Comment by layershifter** [comment]
We don't support outdated versions, please update to `semantic-ui-react@0.75.1`. If the issue still persists, please fill **fully** our issue template and make a pen on codesandbox.
