### ISSUE TITLE
fix(Accordion): An accordion can have multiple levels of nested content. showing error at time of run

### ISSUE THREAD

**Issue by dmosyash** [Semantic-Org/Semantic-UI-React#2241]
**Steps to Reproduce**
1. Copy pasted the example of nested accordion in create-react-app app.
2. Does show an error: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

**Expected**
The Accordion should run without error

**Result**
 React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

**Testcase**
 https://react.semantic-ui.com/modules/accordion#accordion-example-nested

**Comment by dmosyash** [comment]
small changes in example to make it work

`import React from 'react'
import { Accordion } from 'semantic-ui-react'

const level1Panels = [
    { title: 'Level 1A', content: 'Level 1A Contents' },
    { title: 'Level 1B', content: 'Level 1B Contents' },
]

const Level1Content = (
    <div>
        Welcome to level 1
        <Accordion panels={level1Panels} />
    </div>
)

const level2Panels = [
    { title: 'Level 2A', content: 'Level 2A Contents' },
    { title: 'Level 2B', content: 'Level 2B Contents' },
]

const Level2Content = (
    <div>
        Welcome to level 2
        <Accordion panels={level2Panels} />
    </div>
)

const rootPanels = [
    { title: 'Level 1', content: Level1Content, key: "1" },
    { title: 'Level 2', content: Level2Content, key: "2" }
]

const AccordionExampleNested = () => (
    <Accordion panels={rootPanels} styled />
)

export default AccordionExampleNested`

**Comment by dmosyash** [comment]
Changes in the example to run it successfully:-
Need to use `Accordion` instead of `Accordion.Accordion`.
And content should only contain a reactNode not an object:
`{ title: 'Level 1', content: Level1Content, key: "1" }`
instead of 
`{ title: 'Level 1', content: { content: Level1Content, key: 'content-1' } }`

**Comment by layershifter** [comment]
Please check your environment, this example works perfectly on [codesandbox](https://codesandbox.io/s/nr2wq4k4vj). If you still expiriencing this issue, please make a repro on codesandbox.
