### ISSUE TITLE
Way to make Dropdown Form Fields required?

### ISSUE THREAD

**Issue by exapsy** [Semantic-Org/Semantic-UI-React#2245]
### I want to report a
- [ ] Bug
- [x] Feature

I have a **Form**, in which form there are many **Dropdowns**. Is there a way to make these Dropdown Fields **required**? And if not, is there any probable update that will fill that unfilled feature?

```
{/*
  Like this ... but this piece of code does not work itself.
*/}
<Form>
  <Form.Field control={Dropdown} options={ [ { value: 'foo', text: 'foo' } ] } required />
</Form>
```

**Comment by hubertguillemain** [comment]
Hi @Eksapsy 

Try it like this
```
<Form>
<Form.Field required>
<label>Your label</label>
<Dropdown selection multiple fluid />
</Form.Field>
</Form>
```

**Comment by layershifter** [comment]
Duplicate, please refer to [#1423#comment](https://github.com/Semantic-Org/Semantic-UI-React/issues/1423#issuecomment-285896180), there is workaround for this issue, too
