### ISSUE TITLE
fix(Tab): "export 'Tab' was not found in 'semantic-ui-react'

### ISSUE THREAD

**Issue by laneholcombe** [Semantic-Org/Semantic-UI-React#2247]
**Steps to Reproduce**
1. Copy the code in the example here: https://react.semantic-ui.com/modules/tab#tab-example-custom-menu-item
2. Run the example

**Expected**
The example should be rendered as illustrated on the page

**Result**
The example does not render and the following error is logged in the browser console:
"export 'Tab' was not found in 'semantic-ui-react'

**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/modules/tab#tab-example-custom-menu-item.
Using      "semantic-ui-react": "^0.68.3",

**Comment by layershifter** [comment]
1. We don't support outdate versions now.
2. Please check your enviourment, [codesandbox](https://codesandbox.io/s/vn1xjzv3vl) runs this example perfectly.

If the issue still persists, please fill issue template fully and add a pen on codesandbox.
