### ISSUE TITLE
fix(Divider): Divider is not visible on the documentation page

### ISSUE THREAD

**Issue by ydsood** [Semantic-Org/Semantic-UI-React#2253]
**Steps to Reproduce**
1. Go to the [Vertical Divider Example](https://react.semantic-ui.com/elements/divider#divider-example-vertical)

**Expected**
The Divider should be visible with text **Or**

**Result**
The Divider is not visible

![image](https://user-images.githubusercontent.com/6724811/32006719-86f82804-b975-11e7-9d53-06679bb452a1.png)

**Testcase**
If the docs show the issue, use: https://react.semantic-ui.com/elements/divider#divider-example-vertical

**Comment by brianespinosa** [comment]
Thanks for the complete report @ydsood 

There is actually an issue with styles from the main SUI repo. It is a known issue which can be tracked here: https://github.com/Semantic-Org/Semantic-UI/issues/4342
