### ISSUE TITLE
Some icon when using props size="medium" it will not trigger size of the icon, instead render medium brand icon

### ISSUE THREAD

**Issue by dwncy** [Semantic-Org/Semantic-UI-React#2261]
### Steps
Example using icon search:
`<Icon name="search" size="medium" />`

### Expected Result
It will render icon search with size medium,

### Actual Result
It will render medium brand icon

### Version
0.72.0

### Testcase
[Codepen with code](https://codepen.io/darwincahyadi/pen/OOLvMY)

**Comment by layershifter** [comment]
Duplicate #2065.
