### ISSUE TITLE
Modal is not longer scrollable after closing on modal's actions

### ISSUE THREAD

**Issue by romanveryovkin** [Semantic-Org/Semantic-UI-React#2263]
As example of this behaviour can be used one of the modal [here](https://react.semantic-ui.com/modules/modal#modal-example-dimmer)

### Steps
1. Open a modal on the screen size, where it should be scrollable.
2. Close a modal using modals actions in the bottom.
3. Open this modal again. On the body element there is not a 'scrolling' class and therefore a modal is not longer scrollable.

### Expected Result
A modal should stay scrollable, when closing on modal's actions ('scrolling' class should be added). It is not reproducible when modal closing on escape, on dimmer click or on close icon.

### Actual Result
A modal is **not** scrollable, when closing on modal's actions.

### Version
0.75.1

**Comment by levithomason** [comment]
This is interesting, thanks for the excellent report.

Also worth noting that the scrolling state is applied correctly when expanding the browser height taller than the modal then shrinking the browser height shorter than the Modal.  Seems the Modal is not properly comparing the height after the initial mount.

**Comment by levithomason** [comment]
Just tested this locally, it has been fixed in #2254.  It will be available in the next release.  I try to release every weekend, so perhaps tomorrow.
