### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by Gallevy** [Semantic-Org/Semantic-UI-React#2267]
There is 2 really basic components I would really like to see being implemented:

1. Datepicker
2. Slider/Range

**Comment by brianespinosa** [comment]
Hi @Gallevy, this repository is only a React implementation of [Semantic UI](https://github.com/Semantic-Org/Semantic-UI) proper. You should consider making your request on the parent repository. I know there are a number of requests for these items already. Additionally, this repository has actually started work on a date picker component that used mostly Semantic UI components but it is not complete yet.

**Comment by levithomason** [comment]
`<Datetime />` is a long-running issue, but in progress #1240

**Comment by taviroquai** [comment]
Sorry about insisting on this...

I can see that the rating module already implements a slider:
https://react.semantic-ui.com/modules/rating
Maybe with few adjustments it can became the range slider...

Eventually, I will have to implement by myself to finish this project that I'm working on.
Is this rating module a good starting point to implement the range slider?

Thanks!

**Comment by brianespinosa** [comment]
@taviroquai If you are looking for a new component not already part of SUI, I would suggest you open an issue on the core project repo. Anything implemented there will be implemented downstream here. https://github.com/Semantic-Org/Semantic-UI
