### ISSUE TITLE
Tab adds space when caps followed by lower case

### ISSUE THREAD

**Issue by nialloc9** [Semantic-Org/Semantic-UI-React#2271]
This seems to be a bug with Menu.Item component. When I add a name and pass in capital letters like below it adds a space between my last capital letter and the immediate lowercase letter after that.

![code](https://user-images.githubusercontent.com/14121652/32233160-aa846b80-be51-11e7-9d3d-ac58416ab609.png)
![tab](https://user-images.githubusercontent.com/14121652/32233163-ab89ecee-be51-11e7-89b8-d011c3d17d93.png)

**Comment by layershifter** [comment]
Please fill issue template fully and add codepen.

Looks like your name contains special chars, see https://github.com/Semantic-Org/Semantic-UI-React/issues/1340#issuecomment-280720627.
