### ISSUE TITLE
RFC: <button with-conformation="text-to-type"/>

### ISSUE THREAD

**Issue by chrismatheson** [Semantic-Org/Semantic-UI-React#2272]
![delete with confirmation example](https://user-images.githubusercontent.com/420915/32233665-d38f3aea-be52-11e7-823e-96a3bd495d04.gif)

Im currently in the process of creating this component for my own needs and was wondering if its something that would be useful / welcome as part of semantic UI ?

obviously its still in development and needs some polish but the idea would be that the onClick is only actually called if the conformation is completed correctly. 

id imagine that the usage could be something along the lines of

```
<Button with-conformation="text-to-type">
    Click Here
 </Button>
```

id imagine this idea would need substantial changes etc to fit in line with the API's of the semantic UI library, which id be happy to implement as the end result is all im after personally

**Comment by levithomason** [comment]
Hi @chrismatheson, thanks for taking the time to propose this idea.  I think this is best left as a specialized implementation.  If we get a substantial number of requests for this feature, or if this feature.

Just in case you hadn't seen it, we also have a `<Confirm />` addon.  This is a simplified `<Modal />` for the purposes of capturing user confirmation:

https://react.semantic-ui.com/addons/confirm#confirm-example-confirm

**Comment by harel** [comment]
I like it, and think building a library of addons would be a great thing. Those unique components give an edge to the whole library. Or, as an alternative, adding a mechanism to provide external 3rd party addons (with a SUR dependency) - even if its just a doc page explaining what is required etc.
