### ISSUE TITLE
:ActiveHover  is not a valid selector error

### ISSUE THREAD

**Issue by jasan-s** [Semantic-Org/Semantic-UI-React#2273]
I'm trying to use this lib css `http://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.11/semantic.min.css` with `react-snap` which uses `puppeteer`  to pre-render static` html` and I get this error:
`Failed to execute 'querySelector' on 'Document': '.ui.labels a.active.label:ActiveHover:before' is not a valid selector.`

**Comment by layershifter** [comment]
The error is correct, provided selector is not valid.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors

**Comment by jasan-s** [comment]
@layershifter any suggestion on  what I should do to get this lib working with `react-snap` ? since this is the error that is the cause for not being able to integrate the two libs.

**Comment by brianespinosa** [comment]
@jasan-s that CSS file is built using SUI core. I'd open an issue on the core project about this. The error is indeed correct. That's not a valid CSS selector. 

I did a quick search for you though and didn't see any issues open about it (https://github.com/Semantic-Org/Semantic-UI/search?utf8=%E2%9C%93&q=%3AActiveHover&type=). It only occurs in the Label component. If you are not going to use the label component, you could do your own build of the CSS that does not contain the label component and it would work fine. That would be outside of the scope of the SUIR project here.
