### ISSUE TITLE
Releases information

### ISSUE THREAD

**Issue by martlaboloa** [Semantic-Org/Semantic-UI-React#2276]
there are no comment s whatsoever in releases, is it somewhere else, other than github?
can i assume that there are no breaking changes ?

**Comment by NikaBuligini** [comment]
Here is the link for changelog https://github.com/Semantic-Org/Semantic-UI-React/blob/master/CHANGELOG.md

**Comment by layershifter** [comment]
On the top of README :baby_chick: 

![image](https://user-images.githubusercontent.com/14183168/32290668-772440b0-bf43-11e7-8c9e-bcab050d4c1b.png)
