### ISSUE TITLE
Dropdown - if display value doesn't match input, passed item gets ignored and therefore not rendered

### ISSUE THREAD

**Issue by kunokdev** [Semantic-Org/Semantic-UI-React#2279]
#### 1. Request data and set state

```
axios.get(`...`).then((response) => {
  const results = response.data.results.map((e, i) => ({
    key: i,
    text: e.text,
    value: e.value,
    content: (
      <Header key={e.key} size={'tiny'} icon={e.icon} content={e.text} subheader={e.subheader} />
    )
  }))
  console.log('results', results)

  this.setState({
    results,
  }, () => console.log(this.state))
})
```

#### 2. Pass results to component via props

```
<Dropdown
  selection
  search
  options={props.results}
  value={props.value}
  onSearchChange={props.onSearchChange}
  onChange={props.onChange}
/>
``` 

### Actual Result

Now user types `new york` in dropdown input, and this is result in state:

![image](https://user-images.githubusercontent.com/13220754/32288316-ce93cb28-bf33-11e7-96a9-c2e0197b3da1.png)

and it is displayed correctly:

![image](https://user-images.githubusercontent.com/13220754/32288359-ed4d4896-bf33-11e7-99d3-c9478d31bec8.png)

however, is user types `york new` result is still in state (API returns it) however it is not displayed in DOM:

![image](https://user-images.githubusercontent.com/13220754/32288412-1c8e038e-bf34-11e7-836d-f08572309766.png)
![image](https://user-images.githubusercontent.com/13220754/32288420-28919d30-bf34-11e7-805b-f44cce98e40f.png)

If user for examaple writes `bali` (API still returns data)

![image](https://user-images.githubusercontent.com/13220754/32288746-2ed8b7ea-bf35-11e7-95cd-376f6b0a47df.png)

the first item (the one that doesn't match in display name) is ignored (item at array index 0)

![image](https://user-images.githubusercontent.com/13220754/32288568-9e2d8e6e-bf34-11e7-96dc-7e450bc8d292.png)

### Expected Result

I expect this component to render whatever is passed to it, rather than doing internal check (if that is the issue)

### Version
0.75.1

**Comment by layershifter** [comment]
You should use [custom search](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.75.1/src/modules/Dropdown/Dropdown.js#L802) function where you can make any search queries.

```jsx
const customSearch = (filteredOptions, searchQuery) => {
  return filteredOptions.includes(searchQuery)
}

<Dropdown search={customSearch} />
```

**Comment by kunokdev** [comment]
Thanks, I missed that. 
Btw, in my case, backend handles this logic so my function looks like this:
(returning all data which backend returned)

```
const customSearch = (filteredOptions, searchQuery) => {
  return filteredOptions
}
```

Hope it helps if someone comes across similar problem.
