### ISSUE TITLE
Form.Select how to use custom array options

### ISSUE THREAD

**Issue by eranabir** [Semantic-Org/Semantic-UI-React#2281]
From.Select needs to have a specific array like that :
```javascript
const options = [
 { key: 'm', text: 'Male', value: 'male' },
 { key: 'f', text: 'Female', value: 'female' },
]
```
and using it like that :
```javascript
<Form.Field control={Select} label='Gender' options={options} placeholder='Gender' />
```

if i want to use other array with custom keys and values like that for example :
```javascript
const options = [
 { date: 'somedate', title: 'sometitle', },
 { date: 'somedate', title: 'sometitle', },
]
```
i am getting an error about using wrong props

my question is how can i use my own array with this Select Component thanks !

**Comment by brianespinosa** [comment]
@electrozed `Select` is a sugar for a `Dropdown` with the `selection` prop added to it. There are lots of examples on how to use the `options` prop correctly there. I'd recommend starting here: https://react.semantic-ui.com/modules/dropdown#dropdown-example-multiple-selection

**Comment by levithomason** [comment]
Your array must match the shape the component needs.  You should `map()` your array into the proper shape before passing it.  Take a look at the link provided above.
