### ISSUE TITLE
Embed component Google Maps

### ISSUE THREAD

**Issue by mrtysn** [Semantic-Org/Semantic-UI-React#2283]
There isn't any example of how to use google maps in an <Embed> component  although the [docs](https://react.semantic-ui.com/modules/embed) mention that you can.
> An embed displays content from other websites like YouTube videos or Google Maps.

Additionally, the source prop only accepts 'youtube' or 'vimeo'. Providing the src of iframe doesn't work out.

**Comment by brianespinosa** [comment]
@mrtysn the `url` prop is what you should use for embed sources other than YouTube or Vimeo.
```
<Embed
    placeholder='your_placeholder.png'
    url='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25354.94046166276!2d-121.97574860000002!3d37.40478635!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fc9c6db85b8ab%3A0x72af1434e8036575!2sCalifornia&#39;s+Great+America!5e0!3m2!1sen!2sus!4v1509633245458'
  />
```
