### ISSUE TITLE
Package: module not found fbjs/lib/shallowEqual

### ISSUE THREAD

**Issue by zerazeru** [Semantic-Org/Semantic-UI-React#2285]
[src/lib/shallowEqual.js](../blob/v0.74.2/src/lib/shallowEqual.js) is importing from `fbjs` which is not listed as a depencendy.

I am getting this error from webpack
```Module not found: Can't resolve 'fbjs/lib/shallowEqual'```

react 16.0.0
webpack 3.5.1
semantic-ui-react 0.74.2

**Comment by layershifter** [comment]
Fixed in #2292, thanks for report.
