### ISSUE TITLE
RFC: Support for labeled child panes

### ISSUE THREAD

**Issue by davidsusu** [Semantic-Org/Semantic-UI-React#2287]
Would it be possible to extend `Tab.Pane` with a `title` or `label` prop for using it as a menu label, automatically?

```
<Tab menu={{ pointing: true }} />
    <Tab.Pane label="First tab" attached={false}>First tab content</Tab.Pane>
    <Tab.Pane label="Second tab" attached={false}>And the second tab content</Tab.Pane>
</Tab>
```

This is a more handy syntax. In this case, of course, `Tab` must watch the props of its children.

**Comment by levithomason** [comment]
I think in this case we'd provide a `renderMenuItem` callback prop.  You can then handle how the menu items are rendered and insert your label there.  Would this work?
