### ISSUE TITLE
Docs down?

### ISSUE THREAD

**Issue by RobinKuiper** [Semantic-Org/Semantic-UI-React#2289]
https://react.semantic-ui.com/ shows a white page after loading, tested in Chrome and Firefox.

**Comment by gitname** [comment]
I see the same thing. Here's an animated GIF showing my browser window as I reload the page:

![2017-11-04_17-12-50](https://user-images.githubusercontent.com/7143133/32410658-80b35cfa-c183-11e7-9232-752ac6fc115a.gif)

**Comment by gitname** [comment]
I think one of the URLs the docs website is using is missing a period (`.`) character.

Here's a screenshot showing the URL according to CDNJS (top) and the URL the docs website is using (bottom):

![image](https://user-images.githubusercontent.com/7143133/32410710-b322e362-c184-11e7-9aeb-ac206f220be9.png)

**Comment by kwent** [comment]
Same here

**Comment by gitname** [comment]
I think I found the line containing the bug. I think the new line 72 here is missing the period:

https://github.com/Semantic-Org/Semantic-UI-React/commit/470c7b50310e84b5849207febd0a340de682dc9b#diff-ca761db59bf3bc241d74bbbe4b51c0a2

**Comment by gitname** [comment]
I'll submit a PR with a fix in 5 mins.

**Comment by gitname** [comment]
### :construction: Workaround in Google Chrome :construction:

Here's the workaround I'm using to view the docs website while the issue persists:

1. In Google Chrome, visit [https://react.semantic-ui.com](https://react.semantic-ui.com).
2. Press F12 (Command+Option+I on Mac) to reveal Chrome's Developer Tools (i.e. DevTools) panel.
3. In the DevTools panel, click the "Sources" tab and open the `top`>`react.semantic-ui.com`>`(index)` file.
4. Add a breakpoint (i.e. a blue and white arrow) to Line 8 by clicking on its line number.
5. Click the circular arrow icon to reload the web page. This time, execution will stop at Line 8.
6. In the DevTools panel, click the "Console" tab and run the following commands:

    ```javascript
    var script = document.createElement('script'); script.type = 'text/javascript'; script.src = 'https://cdnjs.cloudflare.com/ajax/libs/prop-types/15.5.10/prop-types.min.js'; document.head.appendChild(script);
    ```

7. In the DevTools panel, click the "Sources" tab and click the Play/Pause icon to resume execution. The docs website will load normally.

Here's a depiction of the above instructions:

![image](https://user-images.githubusercontent.com/7143133/32411056-6a1d30fa-c18e-11e7-944b-f2d358c7565b.png)

**Comment by kamilml** [comment]
nice ty @gitname ! ;)

**Comment by Tushant** [comment]
Its still showing the same error.

**Comment by FMCorz** [comment]
This was a good opportunity to build the docs locally.

```
git clone https://github.com/Semantic-Org/Semantic-UI-React.git
cd Semantic-UI-React
yarn install
yarn run docs
```

Then open `http://localhost:8080`.

**Comment by lightning-zgc** [comment]
I set up a mirror on my own server temporarily:
http://sur.lt-lab.cc

**Comment by Maxhodges** [comment]
![image](https://user-images.githubusercontent.com/957271/32412686-ee6ff1f8-c242-11e7-8928-a2c4cacc4394.png)

**Comment by Maxhodges** [comment]
thanks @lightning-zgc

**Comment by layershifter** [comment]
#2290 is merged, I've deployed docs. Now docs works correct. Thanks to all.
