### ISSUE TITLE
Tab component with input issue

### ISSUE THREAD

**Issue by pmogollons** [Semantic-Org/Semantic-UI-React#2300]
### Steps
Create a Tab component inside a form and put inputs in the different tabs. If the input in the first tab has text and you change to the second tab the same text of the input in the first tab will be displayed on the input of the second tab.

### Expected Result
Inputs on every tab should be independent of each other, values of the inputs on different tabs should not be duplicated.

### Actual Result
The value of the inputs on different tabs are duplicated when the value is other than undefined or ''.

### Version
0.71.2

### Testcase
https://codesandbox.io/s/ly4r5llw19

Input some text on the input of the first tab and then switch to the second tab.

**Comment by brianespinosa** [comment]
@pmogollons take a look at the console error in your codesandbox example. You do not have keys on your `Segment` components so as far as React knows they are the same component. Once you resolve your console error they function as you're expecting.

**Comment by andresilveirah** [comment]
I had the same problem and unfortunately the console didn't show me any errors. When I added the key prop to the `Tab.Pane` component, the form inputs worked as expected.
