### ISSUE TITLE
Highlight in the Documentation: Dropdown requires className='link item'

### ISSUE THREAD

**Issue by ZoeVonFeng** [Semantic-Org/Semantic-UI-React#2304]
When trying to create a simple dropdown menu, as I thought className is user defined so I removed it, then it took me a good one hour to debug why my dropdown button is out of place. 
`<Dropdown text='Shopping' pointing className='link item'>`
  
I think such kind "hard requirement" should be highlighted in Props.

**Comment by layershifter** [comment]
I dont understand about what you are speaking. Please fill the issue  template and add more details.

**Comment by ZoeVonFeng** [comment]
Sorry, let me try it again. This was just a request to make Documentation contains more details regarding to this issue.     
WIth the original code;
```
  <Menu>
    <Menu.Item>
      Home
    </Menu.Item>
    <Dropdown text='Shopping' pointing className='link item'>
    </Dropdown>
  </Menu>
```
![image](https://user-images.githubusercontent.com/16110020/32629551-74c0193c-c54e-11e7-8348-0666af3f7c81.png)

If we remove className, since in REACT className could be optional.  So the dropdown code would be like:  
` <Dropdown text='Shopping' pointing >
`
![image](https://user-images.githubusercontent.com/16110020/32629749-0f805950-c54f-11e7-8f1a-7ae11a7407d4.png)
  
I just think if Sematic UI is using `link item` as reserved className. it should be mentioned in the Documentation.

**Comment by layershifter** [comment]
This is a temporialy workaround, this should be following:
```jsx
Dropdown as={Menu.Item}
```

But, it's not possible to do now, see  #2306
