### ISSUE TITLE
fix(Menu): <Menu color= 'green' inverted pointing> inverts pointing's own color instead of menu's color

### ISSUE THREAD

**Issue by ZoeVonFeng** [Semantic-Org/Semantic-UI-React#2307]
**Steps to Reproduce**
This is the simplified example that is directly from documentation. 
1. 
```
 <Menu pointing>
          <Menu.Item name='home' active={activeItem === 'home'} onClick={this.handleItemClick} />
        </Menu>
```
![image](https://user-images.githubusercontent.com/16110020/32629413-f778bc4a-c54d-11e7-970e-6081d16ffb62.png)

2. Do something else.
 <Menu color= 'green' pointing inverted>
          <Menu.Item name='home' active={activeItem === 'home'} onClick={this.handleItemClick} />
        </Menu>

**Expected**
Both menu and pointing should all be green. 
**Result**
![image](https://user-images.githubusercontent.com/16110020/32629371-d8858458-c54d-11e7-9683-c4df59afacd1.png)

**Testcase**
https://react.semantic-ui.com/collections/menu#menu-example-pointing

**Comment by layershifter** [comment]
It's a CSS bug, see Semantic-Org/Semantic-UI#2355
