### ISSUE TITLE
Multiple modal scroll issues

### ISSUE THREAD

**Issue by bionicvapourboy** [Semantic-Org/Semantic-UI-React#2315]
### Steps
Click on "Multiple Modals" button in examples page.
Resize screen in order to get the modal scroll with the page.
Click "Proceed" to open the 2nd modal.
Click "All done" to close the 2nd modal.

### Expected Result
Still able to scroll the first modal

### Actual Result
Can't scroll the first modal ("scrolling" class on body is missing)

### Version
0.76.0

### Testcase
https://react.semantic-ui.com/modules/modal

**Comment by layershifter** [comment]
Duplicate #2248.
