### ISSUE TITLE
Input of type number does not trigger onChange when pasting text

### ISSUE THREAD

**Issue by jephtta** [Semantic-Org/Semantic-UI-React#2317]
### Steps
Copy and paste some text (not a number) into an < Input type="number" />

### Expected Result
The onChange event of the Input should be triggered.

### Actual Result
The onChange event of the Input is not triggered. However, onChange is triggered if the input's type is not a number.

### Version
0.76.0

**Comment by layershifter** [comment]
It's a known React's issue, see facebook/react#11142.
