### ISSUE TITLE
Sidebar scaledown wide option bad work.

### ISSUE THREAD

**Issue by top1st** [Semantic-Org/Semantic-UI-React#2321]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes

✔ BUGS → This form is required:

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y
![image](https://user-images.githubusercontent.com/23559697/32816556-3ff2448c-c9f4-11e7-9b96-7fe281848ae8.png)

![image](https://user-images.githubusercontent.com/23559697/32816576-53b7a3cc-c9f4-11e7-9c12-b53bd9fb7c18.png)

Now scale down over on pusher .
Please solve this problem

**Comment by layershifter** [comment]
I don't understand what you mean, please fill issue template fully with expected and actually section.
