### ISSUE TITLE
On Using custom icon getting warning :  Failed prop type: Invalid prop `name` of value `icon-camera-off` supplied to `Icon`.

### ISSUE THREAD

**Issue by avinlakhera** [Semantic-Org/Semantic-UI-React#2322]
Hi,

I am getting the warning in browser console  **Failed prop type: Invalid prop `name` of value `icon-camera-off` supplied to `Icon`.**  when I am using some another icon font file. Is there any way to add custom icon in Icon component 
### Steps
`<Icon name='icon-chat-off'  />`
### Expected Result

Should not get the warning in browser console 

### Actual Result

Icons Renders in the browser but getting the warning message in console 

### Version
0.75.1

Thanks

**Comment by layershifter** [comment]
You're making me sad :sob: 

![image](https://user-images.githubusercontent.com/14183168/32835797-29abcaba-ca10-11e7-8796-a8956499625e.png)
