### ISSUE TITLE
Visibility: onOnScreen doesn't fire if element is onScreen on first render

### ISSUE THREAD

**Issue by boostup** [Semantic-Org/Semantic-UI-React#2324]
Hello Guys!

I'm basically trying to show a react element that is onScreen on first render. So, I found [Visibility: onOnScreen doesn't fire if element is onScreen on first render](https://github.com/Semantic-Org/Semantic-UI-React/issues/1911), which lead me to [this page](https://github.com/Semantic-Org/Semantic-UI-React/pull/2018).

1)According to the comment on there on Sep 11, a fix was released at version 0.73.0
I have version 0.76.0 in my project. However, when wrapping it with a Visibility react tag, an element, say an image, does not show until I scroll, even though the image is already partially onScreen.  

Here is a [codesandbox](https://codesandbox.io/s/nr5k9k6zwp) to show this issue. 

2)Also, if I include the fireOnMount prop on the Visibility tag, then calculations.onScreen is always equal to true. Is that normal? I can't understand the reason for this...What is fireOnMount for? I don't get it from the docs https://semantic-ui.com/behaviors/visibility or https://react.semantic-ui.com/behaviors/visibility

Thanks for any assistance on these 2 points

**Comment by layershifter** [comment]
1. You need to set `fireOnMount`, see [forked codepen](https://codesandbox.io/s/mly620lz8) as `Visibity` doesn't fire events on component mount by default.

2.  Yes, it's on normal. `onScreen` represents position of an element, if it's `true` that means that element is visible on the screen. See [forked codepen](https://codesandbox.io/s/kmq1rk98q5) and scroll down, once element will not visible, `onScreen` will become `false`.

**Comment by boostup** [comment]
Hi layershifter!

I was finally able to resume my work on this and just checked the forked pens.  
Thanks for taking the time: it did help me out!
