### ISSUE TITLE
fix(Message.List): encoding errors on bullet point

### ISSUE THREAD

**Issue by ruimcf** [Semantic-Org/Semantic-UI-React#2325]
**Steps to Reproduce**
1. Require semantic UI from https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css
2. Use a Message component with a list prop to render a list

**Expected**
Each li element shows a bullet point "•" in ::before content

**Result**
Each li element shows 'â€¢' in  ::before content

**Testcase**
https://codepen.io/anon/pen/gXGEYp

This bug is not observable every time, and sometimes it takes a lot of tries to reproduce.

This is probably an encoding issue cause by an external tool in the browser. To fix this issue change all occurrences of li:before { content } to bullet's point utf-8 escape sequence '\2022'

**Comment by layershifter** [comment]
At first, I thought it was a typo, but the example convinced me in the opposite.

This version of SUI isn't supported and it's not compatible with Semantic UI, please use the latest `2.2.13`. However, your problem comes from CSS and can't be solved in this repo.

**Comment by anthonyalbertyn** [comment]
I have just opened an issue for this in https://github.com/Semantic-Org/Semantic-UI/issues/6867

For anyone who has this issue in their project. If you are able to override variables in your project, a fix is to change @bulletCharacter: '•'; to @bulletCharacter: '\2022'; in the default theme.
