### ISSUE TITLE
how the heck do you do a modal event???

### ISSUE THREAD

**Issue by BrianCodes33** [Semantic-Org/Semantic-UI-React#2326]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes

✔ BUGS → This form is required:

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by starrodkirby86** [comment]
I think this is more appropriate as a usage question.

Have you checked the [examples in the docs' Modal page?](https://react.semantic-ui.com/modules/modal) You can actually view the sources for the examples by clicking on the </> icon.

Notice that for a Modal component, the `trigger` prop should be a component (like a Button) that helps display the inner contents of the Modal. Those inner contents are the actual contents of your Modal. The `open` bool prop is what's actually controlling whether the Modal is visible. If you don't want to have a button controlling this, you can have this prop controlled by a state and have callbacks trying to control this opening or close.

**Comment by layershifter** [comment]
I don't see issue there, please fill issue template.
