### ISSUE TITLE
Test suite failed to run: SyntaxError: Unexpected token import.

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#2328]
### Steps

New "`create-react-app`";
`yarn add semantic-ui-react`;
new component with simply this code:

import React, { PureComponent } from "react";
import Dropdown from "semantic-ui-react/dist/es/modules/Dropdown/Dropdown";

```
class NavbarRightMenu extends PureComponent {
  render() {
    <Dropdown item trigger={myTrigger}>
      <Dropdown.Menu>Something! Booom!</Dropdown.Menu>
    </Dropdown>;
  }
}
```

### Expected Result

`yarn test` everything ok!

### Actual Result

Instead now I got this:

```
src\index.test.js
  ● Test suite failed to run

    C:\Project\node_modules\semantic-ui-react\dist\es\modules\Dropdown\Dropdown.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import _defineProperty from 'babel-runtime/helpers/defineProperty';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (src/components/common/navbar_components/NavbarRightMenu.js:3:17)
      at Object.<anonymous> (src/components/common/NavbarCommon.js:6:24)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.05s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.
```

### Version
0.76.0

### Testcase
https://codesandbox.io/s/736j2w2ol6

I don't know how to test on codesandbox.

**Comment by layershifter** [comment]
Looks like issue with CRA, see facebookincubator/create-react-app#3334. As workaround, you can CommonJS build.

We also don't recommend to use direct exports, `babel-plugin-lodash` is more preferable solution. You can search in issues, that was discussed many times.
