### ISSUE TITLE
fix(Divider): your description

### ISSUE THREAD

**Issue by lenaguerrero** [Semantic-Org/Semantic-UI-React#2335]
**Steps to Reproduce**
1. Use Google Chrome to access the testcase

**Expected**
Divider splits sections of Lorem Ipsum Vertically, with vertical lines appearing

**Result**
Vertical dividers did not appear, nor the text "OR" or "AND" as listed in the example code. They appear to be rendering to the far left of the example. Screenshot attached.

![screen shot 2017-11-20 at 2 49 02 pm](https://user-images.githubusercontent.com/24362129/33040966-5c7adb7a-ce02-11e7-8367-f5861106345e.png)

**Testcase**
https://react.semantic-ui.com/elements/divider#divider-example-vertical

**Comment by brianespinosa** [comment]
@lenaguerrero This is actually an issue with the W3C spec change causing this bug in the CSS and unrelated to this SUIR repository. It is documented in the SUI core repository:

https://github.com/Semantic-Org/Semantic-UI/issues/4342
