### ISSUE TITLE
Dropdown: Invalid activeIndex after item selection in search Dropdown

### ISSUE THREAD

**Issue by kourosz** [Semantic-Org/Semantic-UI-React#2336]
**Steps to Reproduce**
1. Set the dropdown with search and enough items (e.g. 50 items) to make it scrollable.
2. Type in something in order to get one of the bottom items.
3. Use arrow-down/up to move between filtered items. 
4. Press Enter.
(
Or
3. choose an item from end of the list by mouse click
)

**Expected**
The Dropdown should select the item in the text box and selected item becomes active item.

**Result**
The Dropdown does not do this. Instead the search text stays as it was. If you clear the text from the search box, then the selected item will not be the active item. This is not the same behaviour as the original Semantic-UI with JQuery. Users are annoyed by this.

**Testcase**
https://codepen.io/kourosz/pen/LOQJBE

This is very critical for us as we are migrating from Semantic-UI/jQuery to React in a very important project.

**Comment by layershifter** [comment]
I can't reproduce this.

Please add more detailed description for steps, i.e. what I need to type in search. And if possible add GIFs with correct and incorrect behaviour.

**Comment by kourosz** [comment]
Please go to https://codepen.io/kourosz/pen/LOQJBE

This is based on one of the examples in your web site. Please follow the
following steps:

1. In the search box type in: No
you will see this:

[image: Inline image 1]

2. Select NorthDakota, you will see this:
[image: Inline image 2]

3. Now click on the search box, you will see:
[image: Inline image 3]

I expect to see NorthDakota in the search box, and also in the list.
Instead, the Arizona is presented as Selected.

Repeat the same steps, but this time with NorthCarolina. Then you will see
Alaska is selected.

I have the same problem with my data, and found that whatever you select
from the filtered list, that index will be used to mark the item as
selected within the whole set. In our example, the NorthDakota has the
index of 34. When you select it by filter, the index# 2 (because
NorthDakota is the 3rd item) is taken and used for setting the selected
item, but it actually should be 34.

Hope this is clear for you.

Thanks and regards,
Kouros

**Comment by layershifter** [comment]
Confirmed bug, thanks. Screenshots are broken, but it's enough to understand problem.

**Comment by brody2consult** [comment]
What is the actual status of this one?

**Comment by brianespinosa** [comment]
@brodybits if you take a look above your comment, there is an open PR referencing this issue. #2375 

I just went to look at it and it is attempting to resolve this issue. More info can be seen there.

**Comment by namikklapic** [comment]
I am having the same problem. Is there any progress?

**Comment by MarianSulgan** [comment]
Same issue here. What is the current standing?

**Comment by layershifter** [comment]
Was fixed in `semantic-ui-react@0.87.2` by #3584.


- `0.87.1` https://codesandbox.io/s/currying-river-j7b6f?file=/example.js
- `0.87.2` https://codesandbox.io/s/damp-pond-cdv5l
