### ISSUE TITLE
Dividers with no text are not rendered inside grids

### ISSUE THREAD

**Issue by Ghirigoro** [Semantic-Org/Semantic-UI-React#2337]
### Steps
Create a divider with no text inside a Grid: 

```
<Grid>
  <Grid.Row>
    <Divider/>
  </Grid.Row>
</Grid>
```

### Expected Result
A line is rendered

### Actual Result
No line is rendered

### Testcase
https://codesandbox.io/s/2l3n74j9y

**Comment by brianespinosa** [comment]
@Ghirigoro your codesandbox test case does not contain an example of your issue. Please update your report with an example and we can reopen this issue.

**Comment by layershifter** [comment]
```jsx
<Grid>
  <Grid.Row>
    <Divider/>
  </Grid.Row>
</Grid>
```

The markup abowe isn't valid, you can't use `Divider` directly inside `Grid.Row`.

You should use it inside `Grid` or `Grid.Column`:

```jsx
  <Grid>
    <Grid.Row />
    <Divider />
  </Grid>

  // or

  <Grid>
    <Grid.Row>
      <Grid.Column>
        <Divider />
      </Grid.Column>
    </Grid.Row>
  </Grid>
```

**Comment by Ghirigoro** [comment]
Thanks for letting me know. I may have missed it in the documentation, but is the idea that `Grid.Row`s are purely structural and only to be used for organizing `Grid.Column`s?

**Comment by layershifter** [comment]
@Ghirigoro Yes, usage of `Grid.Row` doesn't make sense without `Grid.Column`.

**Comment by levithomason** [comment]
Note, there are `celled` and `divided` props for the `Grid` which can divide your Grid in all sorts of ways:

[divided](https://react.semantic-ui.com/collections/grid#grid-example-divided-number)
[divided='vertically'](https://react.semantic-ui.com/collections/grid#grid-example-divided-vertically)
[celled](https://react.semantic-ui.com/collections/grid#grid-example-celled)
[celled='internally'](https://react.semantic-ui.com/collections/grid#grid-example-celled-internally)
