### ISSUE TITLE
Please how can I deploy your docs folder locally, so I can have it running on localhost ?

### ISSUE THREAD

**Issue by acmoune** [Semantic-Org/Semantic-UI-React#2338]
Please how can I deploy your docs _folder/app_ locally, so I can have it running on localhost ?

**Comment by acmoune** [comment]
Sorry, I got it working.
Just in case somebody is trying to do the same thing:

```
yarn install
yarn run build:docs
yarn run docs
```

It is available on http://localhost:8080 by default.

**Comment by levithomason** [comment]
The best way is to follow the [CONTRIBUTING.md](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/.github/CONTRIBUTING.md) guide.
