### ISSUE TITLE
Menu dropdown icon position/two icons

### ISSUE THREAD

**Issue by farebord** [Semantic-Org/Semantic-UI-React#2341]
```
<Dropdown className="icon" item icon='caret down' text='Account'>
    <Dropdown.Menu>
        <Dropdown.Item></Dropdown.Item>
    </Dropdown.Menu>
</Dropdown>
```

With above code you cant set up a Dropdown, but you can't align icon left nor you can't have two icons like this:
![imagen](https://user-images.githubusercontent.com/602693/33228014-d891690a-d18f-11e7-98d8-9786eab63564.png)

Why? I'm using React, do I have to use Semantic UI (not react one) to achieve that?

**Comment by layershifter** [comment]
Duplicate, see #1147 for workaround.

**Comment by farebord** [comment]
Thats not what I asked. I mean two icons on Dropdown text, not options. :/

**Comment by layershifter** [comment]
![image](https://user-images.githubusercontent.com/14183168/33228412-938071c4-d1c3-11e7-8b52-cbf0e648ace3.png)

```jsx
<Dropdown trigger={<span><Icon name='user'/>File</span>} />
```

**Comment by levithomason** [comment]
>do I have to use Semantic UI (not react one) to achieve that?

Note, you'll run into lots of issues trying to run SUI's jQuery plugins on top of React's virtual DOM.  They both will be making changes to the DOM and will get out of sync.  You should use one or the other.

**Comment by mchurichi** [comment]
is there any option other than using the `text` prop? that one is supposed to be a string, and using @layershifter's solution it works, but triggers a PropTypes validation warning.
```javascript
/** The text displayed in the dropdown, usually for the active item. */
text: PropTypes.string,
```

**Comment by layershifter** [comment]
It was wrong advice, use the `trigger` prop:
```jsx
<Dropdown trigger={<span><Icon name='user'/>File</span>} />
```

The result will be same.

**Comment by mchurichi** [comment]
Thanks! it works like a charm
