### ISSUE TITLE
Dropdown: prop text only allows 'string'

### ISSUE THREAD

**Issue by nopol** [Semantic-Org/Semantic-UI-React#2343]
don't know if this is a bug; i think its a feature request

If you use a Dropdown Element with a Custom text Node
You'll receive a

        Warning: Failed prop type: Invalid prop `text` of type `object` supplied to `Dropdown`, expected `string`.

But. The render of the text element is working as intended.
It would be great to allow Node elements in text prop to render custom content for the Dropdown Element.

**Comment by farebord** [comment]
**text** type should be **any**.

**Comment by nopol** [comment]
currently it's string (via Docs & Code)
perhaps it should be changed to any?

**Comment by layershifter** [comment]
Duplicate #1864.
