### ISSUE TITLE
Strange behavior of Icon component

### ISSUE THREAD

**Issue by PaulRosset** [Semantic-Org/Semantic-UI-React#2345]
Concerning the Icon component.

Strange behavior.

### Steps

Just asking about something I find strange, but may not necessarily be a bug, since the size of an icon by default is ```medium```.

### Expected Result

```
<Icon name="minus" size="medium"/>
```
Expect to render an Icon as a minus icon.

### Actual Result

The Rendering is a Medium brand icon.

### Version
0.75.1

### TestCase
[Here is the demo](https://codesandbox.io/s/vy33r2959l)

Tell me if Im wrong.

**Comment by layershifter** [comment]
Duplicate #2065. `medium`  size isn't supported.

**Comment by levithomason** [comment]
Note, no size is equal to "medium" in this case.
