### ISSUE TITLE
Controlled Popup doesn't handle hideOnScroll

### ISSUE THREAD

**Issue by amaury1093** [Semantic-Org/Semantic-UI-React#2346]
### Steps

1. Create a controlled Popup with `hideOnScroll` prop set to true.

```jsx
        <Popup
          trigger={...}
          content="..."
          on="click"
          hideOnScroll
          open={this.state.isOpen}
          onOpen={this.handleOpen}
          onClose={this.handleClose}
        />
```

2. Click on the trigger to show the popup

3. Scroll the page

### Expected Result

The popup should hide, and the onClose method should be called.

### Actual Result

The popup hides only during scroll, and reappears at scroll end. onClose is never called.

### Version
0.75.1

### Testcase
https://codesandbox.io/s/8x9pryv602

**Comment by smallbrownbike** [comment]
@amaurymartiny No issues with this on 0.77.0. Have you thought about updating?

**Comment by amaury1093** [comment]
Correct, closing.
