### ISSUE TITLE
Transition: Not working properly when 'show' duration is less than 'hide'

### ISSUE THREAD

**Issue by alphapseudo** [Semantic-Org/Semantic-UI-React#2347]
### Steps
Create a transition with a show duration smaller than hide duration
```jsx
<Transition duration={{show: 100, hide: 2000}} animation="fade">
   <h1>Nippertown</h1>
</Transition>
```
### Expected Result
The transition should take 2 seconds to hide the child.

### Actual Result
The hide transition will be interrupted at the show duration (e.g. 100 ms) without completing the intended duration (2 seconds).

### Version
0.77.0

### Testcase
This is reproducible with the example in the [documentation](https://react.semantic-ui.com/modules/transition#transition-example-duration). Configure the sliders to reflect a show value less than the show value.

**Comment by layershifter** [comment]
@alphapseudo Thanks for report, fixed in #2350.
