### ISSUE TITLE
fix(Dropdown): Dropdown with an Input (text) Item closed when clicked

### ISSUE THREAD

**Issue by kourosz** [Semantic-Org/Semantic-UI-React#2353]
**Steps to Reproduce**
1. Create a dropdown with an Input item
2. Open the dropdown
3. Click on the Input item

**Expected**
The Dropdown should stay open and user should be able to enter the text

**Result**
The Dropdown is closed and user cannot enter anything

**Testcase*
https://codepen.io/kourosz/pen/VrRaem

**Comment by brianespinosa** [comment]
@kourosz The docs where your example come from have a note regarding this: https://react.semantic-ui.com/modules/dropdown#dropdown-example-search-in-menu

![image](https://user-images.githubusercontent.com/1161781/33565419-eb25b10e-d8d1-11e7-88a4-0bf853823938.png)

If you need a dropdown to behave differently than the default, you'll have to control the state yourself.
