### ISSUE TITLE
New DropDown Index problem

### ISSUE THREAD

**Issue by top1st** [Semantic-Org/Semantic-UI-React#2356]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes

✔ BUGS → This form is required:

### Steps
Hello guys here is real problem.
https://codesandbox.io/s/3vw22xk7y5
please check
After one selection then when i try next select dropdown text auto change to before selected

### Version
x.y.z

**Comment by kourosz** [comment]
Just change the handler to the following line. The change handler prototype was not correct.

handleChange = (event, value) => this.setState({ value: value })

**Comment by layershifter** [comment]
Duplicate #2296.
