### ISSUE TITLE
Dropdown hides when inside form get focus. 

### ISSUE THREAD

**Issue by farebord** [Semantic-Org/Semantic-UI-React#2358]
```
<Dropdown item icon={null} trigger={
    <Button className="sell-button" inverted>
        <Icon name="sign in" />
        Log In
    </Button>
}>
    <Dropdown.Menu>
        <Segment basic>
            <Form>
                <Form.Input tabIndex="1" placeholder="Email" />
                <Form.Input tabIndex="2" placeholder="Password" type="password" />
                <Form.Button fluid content="Log In" positive />
            </Form>
        </Segment>
    </Dropdown.Menu>
</Dropdown>
```

If I add simple to dropdown, it will work, but its not the approach I like. What should I do?

**Comment by layershifter** [comment]
Duplicate #1593. There is no easy workaround for this issue, you should manually control the `open` prop. However, it's bad idea as we will fully remove children API for Dropdown.

**Comment by tcopple** [comment]
@layershifter is there an issue reference describing the development of dropdown components and how things will work once the children api is removed?
