### ISSUE TITLE
RFC: Be able to define fallback order for Popup position

### ISSUE THREAD

**Issue by WiNloSt** [Semantic-Org/Semantic-UI-React#2359]
The behavior of a Popup is if our desired `position` doesn't fit in the viewport, the component will [calculate the next possible fallback position based on a predefined constant `POSITIONS`](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Popup/Popup.js#L240).

While this is convenient that users doesn't need to defined their own fallback position order. Some users, like me, might prefer having another fallback order for visual purpose. So, being able to override this `POSITIONS` variable somehow would benefit in this case.

I imagine if there would be something like this

```js
<Popup
  trigger={<Icon name="heart" color="red" size="large" circular />}
  content="I am positioned to the top left"
  position="top left"
  fallbackPositions={["bottom left", "bottom center"]}
/>
```

What do you think?

**Comment by layershifter** [comment]
I have an idea to switch positioning of `Popup` to [Popper.js](https://popper.js.org/) after we will finish with `ref`s (#2306).

In fact, current positioning is poorly tested and I don't want to add more complexivity there. However, I think that we will accept PR for current implementation.
