### ISSUE TITLE
searchable dropdown selectedIndex mess up using search

### ISSUE THREAD

**Issue by zhenximi** [Semantic-Org/Semantic-UI-React#2360]
https://github.com/Semantic-Org/Semantic-UI-React/blob/f9348a287b356434b8dfb9a8248dff57435c7d4b/src/modules/Dropdown/Dropdown.js#L922

Please help~
the selectedIndex is updated according to the 'search filtered' options, which doesn't match with the original options array. It's an issue when you open the dropdown again, the pre-active item in the unfiltered list is using the selectedIndex from the filtered options in the initial search.

I try to setState with the correct selectedIndex, but the component does accept it.
please let me know if anyone has a way to fix it or work around it? appreciated!

**Comment by layershifter** [comment]
Duplicate #2336.
