### ISSUE TITLE
Could I  Coutom <Card/>  height or width?

### ISSUE THREAD

**Issue by wildfrontend** [Semantic-Org/Semantic-UI-React#2362]
I Found <Card>  Image were equal width and height look like this:

<img width="1012" alt="2017-12-07 10 27 45" src="https://user-images.githubusercontent.com/20965813/33695937-dbc42478-db3a-11e7-9d10-ac1ba216f9c8.png">

yeah i know becouse <Card.Group> 

but i need to Chang this appear style look like this:

![](https://cloud.githubusercontent.com/assets/2993947/14738104/5e28601c-08b2-11e6-8262-5351a575f3fb.png)

or this

<img width="1643" alt="2017-12-07 10 42 09" src="https://user-images.githubusercontent.com/20965813/33696039-4f11ee10-db3b-11e7-9a04-9e2ba7779562.png">

Coule i ?

**Comment by layershifter** [comment]
Use CSS and style anything what you need. `Card` doesn't have this behavior by default.
