### ISSUE TITLE
Sidebar with default width pushes too far

### ISSUE THREAD

**Issue by sundeer** [Semantic-Org/Semantic-UI-React#2364]
OP issue  #1459 (2) is still a problem.

https://react.semantic-ui.com/modules/sidebar#sidebar-example-left-push
Remove width='thin' prop. I like that default width but content is still pushed way to far.

**Comment by layershifter** [comment]
You should report this bug to SUI repo as it's a CSS only problem. `Sidebar` has width by default:

![image](https://user-images.githubusercontent.com/14183168/33735980-b21beb6a-db99-11e7-9022-452d804732d9.png)

But `Menu` with `icon` class overrides width:

![image](https://user-images.githubusercontent.com/14183168/33736021-d3c9b2b0-db99-11e7-81b1-3d311b808ddd.png)

As workaround you can define width manually:

```jsx
<Sidebar style={{ width: 260 }} />
```
