### ISSUE TITLE
Modal does not open on ReactDOM components with Popup on them

### ISSUE THREAD

**Issue by iamankit1995** [Semantic-Org/Semantic-UI-React#2367]
I was trying to have a button with a popup on it and clicking the button I will get a modal. 

**Expected Result**
Popup opens on hover and on clicking the modal opens

**Actual Result**

The popup opens on hover but the modal does not open on clicking

**Version** 
semantic-ui-react : 0.77.0
semantic-ui for css : 2.2.13

**Sample code** 

`import React from 'react'
import { Button, Header, Icon, Modal, Popup } from 'semantic-ui-react'

const ModalBasicExample = () => (
  <Modal trigger={<Popup trigger={<Button>Basic Modal</Button>} content = "basic" />} basic size='small'>
    <Header icon='archive' content='Archive Old Messages' />
    <Modal.Content>
      <p>Your inbox is getting full, would you like us to enable automatic archiving of old messages?</p>
    </Modal.Content>
    <Modal.Actions>
      <Button basic color='red' inverted>
        <Icon name='remove' /> No
      </Button>
      <Button color='green' inverted>
        <Icon name='checkmark' /> Yes
      </Button>
    </Modal.Actions>
  </Modal>
)

export default ModalBasicExample`

**Sample screen** - https://codesandbox.io/s/j390m4kkj3

**Comment by layershifter** [comment]
Please fill issue template fully and make minimal codepen that represents issue.

Now I see incorrect usage, you can't use `Popup` as trigger.

**Comment by iamankit1995** [comment]
@layershifter any suggestions on how to have a popup on hover and modal on click on the button?

**Comment by layershifter** [comment]
Handle click manually and use controlled Modal. See Portal examples for reference of controlled usage.
