### ISSUE TITLE
RFC: set selectOnNavigation to false by default in Dropdown

### ISSUE THREAD

**Issue by karlludwigweise** [Semantic-Org/Semantic-UI-React#2369]
This is not a bug. Rather a request to change the default behavior of the new selectOnNavigation prop on the Dropdown component and its default value _true_. I would expect the default to be _false_.

A value in a regular select has to be confirmed with RETURN as well.

On my end this caused an avalanche of back-end actions and harmful data changes on the fly. I'm pretty sure this breaks other apps as well.

**Comment by layershifter** [comment]
I'm sure that we don't need to make it `false` by default, however @levithomason can have another opinion.

**Comment by levithomason** [comment]
Currently, it is on by default in parity with SUI's jQuery implementation.  Let's leave this open a while and see what the community thinks.

My personal opinion is that it is OK as is.  I think it is the responsibility of the implementation to test and handle callbacks accordingly.  Very happy to be outvoted though :)

**Comment by layershifter** [comment]
Closing for housekeeping, opened for discussions there
