### ISSUE TITLE
Dropdown: openOnHover

### ISSUE THREAD

**Issue by bgub** [Semantic-Org/Semantic-UI-React#2376]
I love Semantic-UI, but one major reason why I haven't started using Semantic-UI-React is because there is no option for Dropdowns to openOnHover, like there is in regular Semantic-UI; this is a critical part of my user interface. Is there a way to do this that I'm just missing? If not, I think this would be a great feature to add.

**Comment by brianespinosa** [comment]
@nebrelbug to achieve that effect you would have to handle the state of your `Dropdown` component yourself. You can use React `onMouseEnter` and `onMouseLeave` synthetic events for this. Then you can set the `open` prop for `Dropdown`.

https://codesandbox.io/s/mm6mpzwqj9

**Comment by bgub** [comment]
Thank you!
