### ISSUE TITLE
Sidebar: Different way to implement? [Feature request]

### ISSUE THREAD

**Issue by bgub** [Semantic-Org/Semantic-UI-React#2377]
Right now, sidebar syntax looks like this:

```
<Sidebar.Pushable as={Segment}>
          <Sidebar as={Menu} animation='overlay' width='thin' visible={visible} icon='labeled' vertical inverted>
            <Menu.Item name='home'>
              <Icon name='home' />
              Home
            </Menu.Item>
            <Menu.Item name='gamepad'>
              <Icon name='gamepad' />
              Games
            </Menu.Item>
            <Menu.Item name='camera'>
              <Icon name='camera' />
              Channels
            </Menu.Item>
          </Sidebar>
          <Sidebar.Pusher>
            <Segment basic>
              <Header as='h3'>Application Content</Header>
              <Image src='/assets/images/wireframe/paragraph.png' />
            </Segment>
          </Sidebar.Pusher>
        </Sidebar.Pushable>
```

Is it a possibility to add a way to implement sidebars, so that you could load them from external sources, for example, or render most of the page (the pusher content) without rendering? I would have asked the question on Gitter, but it doesn't look like anybody has answered any questions on there recently.

**Comment by brianespinosa** [comment]
@nebrelbug I am not sure I understand what you are asking here. Maybe a little more context of what you are trying to achieve? I am making a guess here based on what you are asking... that most likely you'd end up making another component and wrapping the `Sidebar` component to feed the data and props down that you need.

**Comment by bgub** [comment]
I was hoping that there was a way I could do something like the following:

```
<div id="mySidebar"></div>
<h1>My Cool page!</h1>
<p>And so on, so I wouldn't have to render the main body of my page with HTML. I could just render Sidebar to 'mySidebar'.</p>
```

I could have most of the page be static, just `ReactDom.render(<MySidebar/>, document.getElementById('mySidebar'));`

**Comment by brianespinosa** [comment]
@nebrelbug I guess technically there's nothing stopping you from rendering another React tree this way if you really wanted to. You could do it right now. But if `<div id="mySidebar"></div>` is within your main React tree, you cannot do it. That's not how React works.

```
<div id="mySidebar"></div>
<h1>My Cool page!</h1>
<p>And so on, so I wouldn't have to render the main body of my page with HTML. I could just render Sidebar to 'mySidebar'.</p>
<div id="app"></div>
```
Rendering separate applications into either `mySidebar` or `app` should work in the above. The example below would not. You'd be manipulating the DOM directly inside the `app` tree when React expects it to look a certain way. This is not a function of SUIR. It's how React works.

```
<div id="app">
    <div id="mySidebar"></div>
    <h1>My Cool page!</h1>
    <p>And so on, so I wouldn't have to render the main body of my page with HTML. I could just render Sidebar to 'mySidebar'.</p>
</div>
```

**Comment by bgub** [comment]
I guess what I was asking was if SUIR would consider creating a separate application specifically for use without the pusher, one that could just render into "mySidebar" in the first example, without having to wrap the rest of the page content. Is that a possible feature?

**Comment by brianespinosa** [comment]
@nebrelbug do you want to just render the markup for the `Sidebar` alone? If so, you can already do that. Just include `visible` prop on the `Sidebar` component and it will be shown. The `Sidebar.Pusher` component is not required. `Sidebar` can be used independently.

**Comment by bgub** [comment]
I was hoping to be able to toggle the Sidebar too, and have it push page content. I just would prefer not to have the page content / pusher content wrapped in a div. Is that possible?

**Comment by brianespinosa** [comment]
@nebrelbug If you want all of the same functionality but different markup, then that would require different CSS. The active styles for the `Sidebar.Pusher` and `Sidebar` come from active classes. They are not applied inline to those containing components. If that is what you want you're best writing your own JS to toggle transition styles to your off canvas sidebar and body content. Modifying the markup/styles of SUI is out of scope for this particular project.
