### ISSUE TITLE
Opening a router link to a modal overrides the router's children

### ISSUE THREAD

**Issue by acmoune** [Semantic-Org/Semantic-UI-React#2379]
I am using semantic-ui-react with react-router. I created a route to display a modal, the modal trigger is just a router link. when I open the link, the modal is well displayed, but the router children is replaced by a new link.

Is it possible to just show the modal and leave the router children as it is,  whatever it is ?

Thanks in advance.

**Comment by layershifter** [comment]
Use SO for usage question, if you think that there is real issue, please fill issue template and make a repro on codesandbox.

**Comment by acmoune** [comment]
Ok, https://stackoverflow.com/questions/47799507/opening-a-router-link-to-a-modal-overrides-the-routers-children
