### ISSUE TITLE
Doc site is broken

### ISSUE THREAD

**Issue by kenkouot** [Semantic-Org/Semantic-UI-React#238]
Trying to see the demo of your port and tool around with the React dev tools, but the doc site is broken.

**Comment by levithomason** [comment]
Indeed it is.  Taking a look, thanks!

**Comment by levithomason** [comment]
That should do it, will take a few minutes for CI to deploy the new docs.  Thanks again for the report.

**Comment by levithomason** [comment]
Confirmed all is well now: https://technologyadvice.github.io/stardust/

I'm pushing some more fixes and perf improvements as well.
