### ISSUE TITLE
TransitionablePortal: doesn't close on closeOnDocumentClick

### ISSUE THREAD

**Issue by grean** [Semantic-Org/Semantic-UI-React#2382]
hi,
It works with Portal but not with Transitionable..
Note that the Portal controlled demo here https://react.semantic-ui.com/addons/portal doesn't work too.

Version 0.76.0

**Comment by brianespinosa** [comment]
@grean We don't currently support outdated versions of SUIR. Current version of SUIR is 0.77.1

The docs you are linking to are working as expected. Please update to the most current version. If you are still experiencing a problem, please open an issue report with a codesandbox example showing what you are experiencing.

**Comment by grean** [comment]
Ok concerning the bug in docs that i've mentionned, i always experiencing it using last version of firefox 57.0.2 but in chrome..
I've updated to 0.77.1 and the behavior is the same. (i'm using chrome for dev and firefox for web)
Here is my code that works good with a simple Portal but not with a TransitionalPortal.

Here codesandbox with Portal that works as expected : https://codesandbox.io/embed/03z6nq5zv0
and there with TransitionablePortal that doesn't work for me : https://codesandbox.io/s/m7zxwo44lx

**Comment by layershifter** [comment]
There is real bug, thanks for report.
