### ISSUE TITLE
Docs: Home Page template is not responsive

### ISSUE THREAD

**Issue by azias** [Semantic-Org/Semantic-UI-React#2386]
I am not able to say if it is "just" a problem in the example or a problem inside the implementation of Semantic UI React itself.

I thought having read that the menu of this page is not supposed to be responsive in Semantic-UI-React so I do not point this here (while it is a difference with the original one) but there is a vertical grey overlay that seems to be a bug.

### Steps
- Go to https://react.semantic-ui.com/layouts/homepage
- in chrome : F12, then Ctrl+Shift M, then choose "Nexus 5X" in the dropdown (or you can use a smartphone)

### Expected Result
- I suppose we must obtain the same result as the one at https://semantic-ui.com/examples/homepage.html

### Actual Result
-  there is a vertical grey overlay on the right that prevents to acess log in and sign  up buttons

### Version
0.77.1

**Comment by layershifter** [comment]
Responsive menu was not implimented, I will make PR tomorrow.
