### ISSUE TITLE
Message type warning not working

### ISSUE THREAD

**Issue by Dscheksn** [Semantic-Org/Semantic-UI-React#2387]
**Steps to Reproduce**
1. Import Message from "semantic-ui-react"
2. Use Message with type warning

**Expected**
The Message should be orange

**Result**
The Message does not appear

**Testcase**
Tested with 'positive'. Result: Appears as expected
Tested with 'negative'. Result: Appears as expected
Tested with 'warning'. Result: Doesn't appear at all!

**Comment by layershifter** [comment]
Please fill issue fully and make a repro on codesandbox.
