### ISSUE TITLE
Popup closes when clicking delete icon from dropdown multiple selection

### ISSUE THREAD

**Issue by fracmak** [Semantic-Org/Semantic-UI-React#2388]
### Steps
1: Given a popup
2: Inside the popup is a Dropdown component with the multiple property set
3: Select an item inside the dropdown
4: Click the "X" to delete it 

### Expected Result
Popup remains open

### Actual Result
Popup closes

### Version
0.77.1

### Testcase
https://codesandbox.io/s/lxp9kpxkzq

**Comment by ghost** [comment]
Found the bug.. Preparing PR :smile: 

The bug is related to Portal logic, which means that the bug maybe produce in other than Select components under a specific circumstances that I'll explain in the commit message

**Comment by ghost** [comment]
Submitted the PR, waiting for review

**Comment by ak1394** [comment]
I've just run into the same issue. Would like to see it merged soon.

**Comment by layershifter** [comment]
In fact, it's a duplicate of #1831 and will be fixed by #2384.
