### ISSUE TITLE
Form.Dropdown required attribute not working

### ISSUE THREAD

**Issue by ashinzekene** [Semantic-Org/Semantic-UI-React#2393]
### Steps
```jsx
<Form.Dropdown
  label="Circle" 
  value={ circle.value }
  onChange={ this.handleChange }
  required
  options= { options }
  placeholder='Which of your circles' />
```
### Expected Result
Form should not submit until this field has been filled
### Actual Result
Form submits even if empty
### Version
0.75.1

### Testcase
https://codesandbox.io/s/oo0r17pj26

**Comment by ghost** [comment]
Hi,
I tested your CodeSandBox in my chrome and it's working as expected.

Browser: Version 63.0.3239.108 (Official Build) (64-bit)
OS: Linux Mint

![image](https://user-images.githubusercontent.com/7091543/34246486-83bc0248-e637-11e7-8121-7bc6f3757863.png)

**Comment by ashinzekene** [comment]
Only the name field enforces the `required` attribute. The form submits even if the circle field which is required is empty

**Comment by layershifter** [comment]
Duplicate, please refer to [#1423#comment](https://github.com/Semantic-Org/Semantic-UI-React/issues/1423#issuecomment-285896180), there is workaround for this issue, too
