### ISSUE TITLE
Button warning

### ISSUE THREAD

**Issue by eanplatter** [Semantic-Org/Semantic-UI-React#24]
I get this warning:
<img width="970" alt="screen shot 2015-10-05 at 5 31 09 pm" src="https://cloud.githubusercontent.com/assets/3782604/10295540/ed92ff4c-6b86-11e5-8452-d8abe062b702.png">

when running this code:

``` jsx
<Button className='icon ui fluid inverted button'>
  Earnings
  <i className='dropdown icon' />
</Button>
```

**Comment by levithomason** [comment]
Fixed in #59
