### ISSUE TITLE
Cannot read property 'firstElementChild' of null in Portal.js line 311

### ISSUE THREAD

**Issue by eldyvoon** [Semantic-Org/Semantic-UI-React#2401]
✔ BUGS → This form is required:

### Steps
https://drive.google.com/file/d/1d471crHVkIgjvBSXsVMTq3B4WWau6NqR/view

### Expected Result
This is should not show an error

### Actual Result
Error on
TypeError: Cannot read property 'firstElementChild' of null
node_modules/semantic-ui-react/dist/es/addons/Portal/Portal.js:311

### Version
"semantic-ui-react": "^0.77.0"

### My code

my container

```
render() {

  const { ad, redirectTo } = this.props

  return(
    <Container>
      {redirectTo && <Redirect to={redirectTo} />}
      {ad && <AdDetail 
        data={ad}
        applyAd={()=>this.applyAd()}
        openModal={()=>this.setState({isOpen: true})}
        closeModal={()=>this.setState({isOpen: false})}
        isOpen={this.state.isOpen} />}
    </Container>
  )
}
```

AdDetail component

```
import Modal from './modal'

export const AdDetailBody = ({data}) => (
    <Card
      fluid
      className='ad'
      header={data.title}
      meta={
        <div className='meta'>
          <Label>{data.category}</Label>
          <Label>{data.language}</Label>
          <p>{data.requirements}</p>
        </div>
      }
      extra={
        <div className='extra'>
          <div className='extra'>
            <p className='left'>{`RM ${data.reward}`}</p>
            <p className='right'>{data.expiry_date && `Expiry date: ${data.expiry_date}`}</p>
          </div>
        </div>
      }
    />
)

export const AdApplyBody = ({openModal, closeModal, isOpen, applyAd}) => (
  <div>
  <center>
    <Button onClick={openModal} primary>Take this job</Button>
  </center>
  <Modal 
    isOpen={isOpen}
    closeModal={closeModal}
    onSuccess={applyAd}
    header={'Confirm'}
    content={'I have read the requirements and able to deliver the task.'}
    cancelText={'Cancel'}
    successText={'Yes'}
  />
  </div>
)

const AdDetail = ({data, openModal, closeModal, isOpen, applyAd}) => (
  <div>
      <AdDetailBody data={data} />
      <br />
      <AdApplyBody 
        openModal={openModal}
        closeModal={closeModal}
        isOpen={isOpen}
        applyAd={applyAd}
      />
  </div>
)
```

Modal.js
```
import React, { Component } from 'react'
import { Button, Modal } from 'semantic-ui-react'

class MyModal extends Component {

  render() {

    return (
        <Modal open={this.props.isOpen} onClose={this.props.closeModal}>
          <Modal.Header>
            {this.props.header}
          </Modal.Header>
          <Modal.Content>
            {this.props.content}
          </Modal.Content>
          <Modal.Actions>
            <Button negative onClick={this.props.closeModal}>
              {this.props.cancelText}
            </Button>
            <Button positive onClick={this.props.onSuccess}>
              {this.props.successText}
            </Button>
          </Modal.Actions>
        </Modal>
    )
  }
}

export default MyModal
```

I'm clueless here, I think the flow is pretty straight forward but I got error caused by Portal.js

**Comment by layershifter** [comment]
Please create a minimal repro on codesandbox.

**Comment by eldyvoon** [comment]
@layershifter couldn't import my repo into codesandbox, but I've created a demo repo with temp db for this issue

https://github.com/eldyvoon/react-redux-express-auth/tree/semantic-portal-bug
after `npm install` run `npm start` and `node server` then login using username `semantic@gmail.com` and password `123456`

Thanks!

PS: I've no clue where to debug, I used both `Modal` and `Confirm` component end up getting an error from Portal.js. I think the `Redirect` of react-router-v4 might be the cause.

**Comment by layershifter** [comment]
Sorry, but we don't have time to debug your code. Thats why we require a minimal repro on codesandbox.

**Comment by eldyvoon** [comment]
Just couple of seconds to see the demo. I've even setup a temp db for this
issue. I'm not sure why I can't import into codesanbox. It's definitely a
bug, I didn't use any portal in my project why there is a portal error when
I try to use modal and confirm?

**Comment by vanpelt** [comment]
I've been getting this same error.  It seems to be a race condition, as it doesn't always happen.  I just monkey patched Portal.js to check for `this.rootNode` here: https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/addons/Portal/Portal.js#L367 and it seems to be working now.
