### ISSUE TITLE
Unit Tests on Headless Firefox

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#2402]
✔ BUGS → This form is required:

This bug is related to my failed PR that was not compatible with Firefox (https://github.com/Semantic-Org/Semantic-UI-React/pull/2397). The fail was not recognize since all the test were passing on Headless Chrome, then when I tried to test my changes in Firefox it simply FAILED which made me disappointed a little bit, but I thought about running all the big number of unit testing on Headless Firefox to see if some implementations has this cross-browser incompatibility issue.. And guess what: I found some of those whose is failing in Firefox 57.0.0 [ (What about older firefoxes?!)]

Those test fails include my own PR changes that Firefox not compatible with - That if was covered in test hook then they can save my time thinking for another approaches instead of waiting for the PR review)!

### Steps
- Plug karma-firefox-launcher to launch unit testing on Firefox
- Use this karma configuration:
```js
  config.set({
    browsers: ['FirefoxHeadless'],
    customLaunchers: {
      FirefoxHeadless: {
        base: 'Firefox',
        flags: [ '-headless' ],
      },
    },
  })
```
### Expected Result
All Unit tests are passing

### Actual Result
Some unit tests fails

### Version
0.77.1

### Summary
SUMMARY:
✔ 9433 tests completed
✖ 1 test failed **[Mine also added 3 test fails regarding my mentioned PR above]**

FAILED TESTS:
  TransitionablePortal
    onOpen
      ✖ changes `portalOpen` to true
        Firefox 57.0.0 (Ubuntu 0.0.0)
        event is not defined
        @test/specs/addons/TransitionablePortal/TransitionablePortal-test.js:155:0

### Testcase
Fork to check the Firefox results:
https://github.com/Attrash-Islam/Semantic-UI-React/tree/headlessFirefox
run `yarn test`

**Comment by ghost** [comment]
karma-firefox-launcher & Headless Firefox karma config
(https://github.com/Attrash-Islam/Semantic-UI-React/commit/85f7c88a8a5baa3ef0ab092e77ef6b44f9fa34e2)

**Comment by layershifter** [comment]
We run tests in Chrome as it easy installable with [puppeteer](https://github.com/GoogleChrome/puppeteer), after v1.0 release we will use [BrowserStack](https://www.browserstack.com/) or something similar.
