### ISSUE TITLE
floating label supports right to left

### ISSUE THREAD

**Issue by sag1v** [Semantic-Org/Semantic-UI-React#2403]
When we use a label with a `floating`  prop we get [this](https://react.semantic-ui.com/elements/label#label-example-floating):
![label](https://user-images.githubusercontent.com/9153149/34378132-280d0b52-eafd-11e7-9cca-08f88270056e.png)

This is the main rule that responsible for this:
```
.ui.floating.label {
    position: absolute;
    z-index: 100;
    top: -1em;
    left: 100%;
    margin: 0 0 0 -1.5em!important;
}
```
If i want to attach the floating label to the left (to support RTL languages) i would need to change it to this:
```
.ui.floating.label {
    position: absolute;
    z-index: 100;
    top: -1em;
    right: 100%;
    margin: 0 -1.5em 0 0!important;
}
```
And i will get the result:
![labelrtl](https://user-images.githubusercontent.com/9153149/34378289-c6d80bc4-eafd-11e7-8b36-0731da326d24.png)

Is there a native way to achieve this result? i was looking at semantic-ui docs as well as semantic-ui-react, but no luck so far.

**Comment by layershifter** [comment]
Semantic-UI-React only concerns itself with JS components that render down to valid Semantic-UI markup. Issues with CSS and HTML markup should be posted on the main repo:

https://github.com/Semantic-Org/Semantic-UI

Also please check that you're using RTL version, [see there](https://semantic-ui.com/introduction/build-tools.html) how to build it.
