### ISSUE TITLE
Solved - Table borders not appearing on header and footer

### ISSUE THREAD

**Issue by jamesjryan** [Semantic-Org/Semantic-UI-React#2408]
**Steps to Reproduce**
1. Install fresh copy of create-react-app
2. Add semantic-ui-react and semantic-ui-css as deps
3. Add `import 'semantic-ui-css/semantic.min.css`to `index.js`
4. Copy paste table code from https://react.semantic-ui.com/collections/table#table-example-pagination

Versions from `yarn.lock`:
```
semantic-ui-css@^2.2.12:
  version "2.2.12"
  resolved "https://registry.yarnpkg.com/semantic-ui-css/-/semantic-ui-css-2.2.12.tgz#afc462e5bb4f8a0dcfe3dca11274499a997490dd"
  dependencies:
    jquery x.*

semantic-ui-react@^0.77.1:
  version "0.77.1"
  resolved "https://registry.yarnpkg.com/semantic-ui-react/-/semantic-ui-react-0.77.1.tgz#38d4009cc8c7c20efac6ad8ba4497de3bb3287e2"
  dependencies:
    babel-runtime "^6.25.0"
    classnames "^2.2.5"
    fbjs "^0.8.16"
    lodash "^4.17.4"
    prop-types "^15.5.10"
```

**Expected**
Table should render as shown on https://react.semantic-ui.com/collections/table#table-example-pagination

**Result**
Table renders without borders on header and footer (see image)
https://i.imgur.com/TfFaYyL.png

**Testcase**
~~This issue is not reproducible when forking the codepen link:~~

Edit: issue is reproducible using this link - zoom out on Chrome ~63 to reproduce. Set zoom to 0 to render table borders correctly.

https://codepen.io/anon/pen/baYbVg?editors=1111

**Comment by layershifter** [comment]
Made step-by-step install, see result:

![image](https://user-images.githubusercontent.com/14183168/34686795-6cc897f4-f4b5-11e7-8043-093e56c3c1c5.png)

---

If issues persists, please make an example repo and tell your browser version.

**Comment by jamesjryan** [comment]
@layershifter thanks for looking into this.

I can reproduce using Chrome, in incognito with no extensions enabled, Version 63.0.3239.132 (Official Build) (64-bit) on macOS High Sierra Version 10.13.2 (17C88).

Table renders correctly in Firefox version 57.0.

Repo:

https://jamesjohnryan@bitbucket.org/jamesjohnryan/semantic-ui-react-bug.git

**Comment by layershifter** [comment]
Thanks for repo. Yep, you've done same thing as me. I've tested under Chrome 63.0.3239.132 at Windows and Ubuntu, all works fine even in incognito.

You can try to inspect applied CSS styles to html elements and compare them with Firefox, possible you will find out the bug and will have reproducable example.

**Comment by jamesjryan** [comment]
Well - did a bit of digging - is indeed a Chrome bug - happens when you zoom out on a page. If you reset your zoom (`Ctrl/Cmd + 0`) it renders correctly.


Thanks to these guys for the info https://www.codecademy.com/en/forum_questions/53604b8a282ae39feb000470

Happy to keep this closed with this info.
