### ISSUE TITLE
Dropdown: incorrect selection when dynamically changing options

### ISSUE THREAD

**Issue by searene** [Semantic-Org/Semantic-UI-React#2410]
I want to change a DropdownItem's text dynamically after selecting it. However I ran into an issue here.

### Steps
1. Open [codesandbox](https://codesandbox.io/s/8xmx8mymk9)
2. Click on the Dropdown list
3. Select `beforeSelecting`
4. Click on the Dropdown list again
5. You can see that the text shown in the Dropdown list  is still `defaultOption`, rather than `afterSelecting`

### Expected Result
The text shown in step 5 should be `afterSelecting`.

### Actual Result
The text shown in step5 is `defaultOption`.

### Version
0.75.1

### Testcase
https://codesandbox.io/s/8xmx8mymk9

**Comment by layershifter** [comment]
`Dropdown` relies on `value` prop, keep it same, see [this pen](https://codesandbox.io/s/m730l17y1p). However, I don't see the described issue in your example, can you provide more details?

**Comment by searene** [comment]
Hi layershifter,

Here are more details.

Suppose the current selected item is **defaultOption**, what we see would be like this.

![correct](https://user-images.githubusercontent.com/3351317/34646654-c3b129ea-f3a8-11e7-9991-91d66f16659d.png)

That's correct, but if I click on **beforeSelecting**, what we see would be like this.

![incorrect](https://user-images.githubusercontent.com/3351317/34646660-ef544cd0-f3a8-11e7-9f9d-fbef5c76557e.png)

As you can see, **afterSelecting** should be in the title and should be in the grey background, but it's not, that's inconsistent, and that's the issue here.

**Comment by layershifter** [comment]
Thanks, now I see the problem 👍 Looks like similar to #2336
