### ISSUE TITLE
Item.Image has bad size when in mobile view

### ISSUE THREAD

**Issue by Rex90** [Semantic-Org/Semantic-UI-React#2411]
Here is a codepen of the issue with Item.Image

https://codepen.io/anon/pen/eyyOab?editors=0010

Just resize the viewer by moving the divide to the left to decrease the viewport size and you will see that the image stops honoring the "mini" size.

How i expect it to remain after resize:
![image](https://user-images.githubusercontent.com/6030955/34654389-c91bd3a4-f3f2-11e7-9fe7-f557e24f0a00.png)

How it behaves:
![image](https://user-images.githubusercontent.com/6030955/34654386-bd341272-f3f2-11e7-98e2-5fdebcb1d180.png)

### Expected Result
I believe the image should remain the same size regardless of the device. If anything it should get smaller when in mobile :)

### Testcase
https://codepen.io/anon/pen/eyyOab?editors=0010

**Comment by layershifter** [comment]
There is no bug, `Item` is designed to represent content:
> An item view presents large collections of site content for display

----

However, expected behaviour can be reached with another markup, [codesandbox](https://codesandbox.io/s/qx1n6l3k19).

**Comment by Rex90** [comment]
Hi @layersfter thanks for the response. I looked at the code you attached but the result is that the image is always above the text, whereas I need it to the left of the text like in the first screenshot.

Thanks

**Comment by Rex90** [comment]
I have ended up using Table.Cell without Item. Thanks @layershifter
