### ISSUE TITLE
Search is missing "defaultOpen" propTypes validation for auto controlled prop "open"

### ISSUE THREAD

**Issue by lellky** [Semantic-Org/Semantic-UI-React#2415]
Hello, I get a lot of propTypes validation errors in dev mode. What can I do to get rid of them?

### Steps
Use the search component

### Expected Result
No errors in the console

### Actual Result
A lot of errors in the console
<img width="1293" alt="screenshot 2018-01-08 16 19 59" src="https://user-images.githubusercontent.com/7119913/34677505-aa711588-f490-11e7-9892-3e75c544be3b.png">

### Version
0.74.2

**Comment by layershifter** [comment]
1. Update to latest version, we don't support unactual versions before 1.0.
2. Please make a repo with minimal config that reproduces this error. Looks like wrong configuration of bundler or a wrong usage of components.

**Comment by lellky** [comment]
Thanks! Will try that.
