### ISSUE TITLE
IE11 Tabindex not working when using Dropdown (Form.Select)

### ISSUE THREAD

**Issue by AlexTingkaer** [Semantic-Org/Semantic-UI-React#2419]
### Steps
1. Open internet explorer 11
2. Enter https://react.semantic-ui.com/modules/dropdown#dropdown-example-selection in address line, press enter
3. Mark some or all of the headline "Selection".
4. Press the TAB button to go to the Dropdown/Select element
5. Use keyboard arrows to select any option in the list
6. Press ENTER to select an option
7. Press TAB to go to next item in the tabindex order

### Expected Result
Expected to go to the next Dropdown or tabindex'able element

### Actual Result
The tab goes back to the first tabindex'able item on the page.

### Version
0.77.1

### Testcase
https://codesandbox.io/s/zqlpp9jk9m

Alternative:
https://codepen.io/anon/pen/pprXJX?editors=0011

**Comment by levithomason** [comment]
@layershifter has IE access to test this.

We should really get cross-browser testing setup.  Someone would be a hero if they implemented this. 💪

**Comment by andrewleith** [comment]
Anyone get anywhere with this?  I've been struggling to have the dropdowns behave with IE taborder but I am not getting anywhere.  Unfortunately for me this means a big fail for accessibility as we support IE11.

**Comment by andrewleith** [comment]
Out of sheer frustration I did the most counter-intuitive thing possible and somehow its working perfectly in IE11.  I am using Fomantic UI but hopefully this can help someone.  I commented out this block of code in the dropdown plugin:
```js
// prevents IE11 bug where menu receives focus even though `tabindex=-1`
if (document.activeElement.tagName.toLowerCase() !== 'input') {
  $(document.activeElement).blur();
}
```
IE11 tabbing is perfect, as is chrome (I didnt check any other browsers).

**Comment by SaraSalahAlDin** [comment]
@andrewleith  can you explain more where this code should be added .. I have the same problem.
