### ISSUE TITLE
Modal: allow React component in content property

### ISSUE THREAD

**Issue by AndrewPrifer** [Semantic-Org/Semantic-UI-React#2420]
Currently the modal/confirm component only renders strings properly as the content property. If I pass in a component, it is rendered, however it is no longer wrapped in
```html
<div class="content">...</div>
```
which results in no margins around the content. Would it be possible to correctly render React components too?

**Comment by layershifter** [comment]
Please fill issue template fully an add example on codesandbox.

**Comment by AndrewPrifer** [comment]
@layershifter The issue template didn't include an option for feature/enhancement requests IIRC. Technically it is not a bug, since the docs specify the type of the property as string. Should I file this as a bug with the assumption that components should be rendered correctly too?

**Comment by fspinnenhirn** [comment]
@andrewpeterprifer the trick to render a component as the modal's content using the shorthand `content` prop with the expected margins is to not just pass it directly, but to set it as a nested `content` attribute in an object, as shown below.

If you do the following, your component _**won't** render with the expected margins_ as the modal content:
```jsx
// renders MyComponent, but without margins
<Modal
  // ...
  content={<MyComponent />}
/>
```

This will properly render a content component using the modal shorthand:
```jsx
// renders just as Modal.Content would if MyComponent were its child
<Modal
  // ...
  content={{
    content: <MyComponent />
  }}
/>
