### ISSUE TITLE
Pagination addon missing on Semantic-UI-React version 0.77.2

### ISSUE THREAD

**Issue by buptlee** [Semantic-Org/Semantic-UI-React#2422]
### Steps
- import {Pagination} from 'semantic-ui-react';
- compile application
### Expected Result
Pagination addon is imported
### Actual Result
Failed to compile.
'semantic-ui-react' does not contain an export named 'Pagination'
### Version
0.77.2

**Comment by levithomason** [comment]
The component is included, there must be something else at play here:

https://codesandbox.io/s/2xpm2zzlnn

```jsx
import React from 'react'
import { render } from 'react-dom'
import { Pagination } from 'semantic-ui-react'

const App = () => <Pagination />

render(<App />, document.getElementById('root'))
```

![image](https://user-images.githubusercontent.com/5067638/34803166-9f59bba4-f626-11e7-813b-9219a8f7c641.png)

**Comment by buptlee** [comment]
I still have this issue, I take two screenshots of my project, one is the 'semantic-ui-react' module in my project, the second one is my 'package.json' file.
I ran 'npm install' and no Pagination added into 'semantic-ui-react' module. Is there any other reason why Pagination not coming with the module?

Thanks

![image](https://user-images.githubusercontent.com/4932927/34832729-b4898794-f6bb-11e7-997c-e208f0635874.png)
![image](https://user-images.githubusercontent.com/4932927/34832757-c21f2da0-f6bb-11e7-83cb-13464328fd4b.png)

**Comment by layershifter** [comment]
Remove your `node_modules` directory and make `npm install` again.

**Comment by levithomason** [comment]
@layershifter is correct.  Also, I would recommend using yarn if you're not already as it solves many of these issues with NPM.

Just to double verify, unpkg'd is a CDN that pulls from NPM.  Here, you can see the file is available on NPM:

https://unpkg.com/semantic-ui-react@0.77.2/dist/commonjs/addons/Pagination/Pagination.js
https://unpkg.com/semantic-ui-react@0.77.2/dist/es/addons/Pagination/Pagination.js

Best of luck!

**Comment by buptlee** [comment]
After I remove and rerun npm install, Pagination works. 
Thanks for the help.
