### ISSUE TITLE
Modal Blurring Dim

### ISSUE THREAD

**Issue by randichilyon** [Semantic-Org/Semantic-UI-React#2425]
I want to change the background-color of the modal dimmer with darker color, but I can't access the CSS, how to change it ?

**Comment by layershifter** [comment]
Use CSS and [Semantic UI theming](https://semantic-ui.com/usage/theming.html), Semantic UI React doesn't provide styling features now.

**Comment by randichilyon** [comment]
I tried to use CSS in the Modal className, but it won't affect the dim background, it only applied to the content box.
