### ISSUE TITLE
<Confirm /> Element Stuck in Very Fast Endless Open / Close Animation Loop

### ISSUE THREAD

**Issue by selected-pixel-jameson** [Semantic-Org/Semantic-UI-React#2427]
### Steps

I Added the <Confirm /> component to my application and implemented the necessary
handlers and states. 

### Expected Result
For the <Confirm /> component to appear on the screen as shown in the documentation

### Actual Result
The Confirm component enters the screen and appears to be stuck in an
endless open & close loop. I looked at the react debugger in chrome and the state is not toggling back and forth, but if I toggle it the <Confirm /> component loop will start and stop as described above. 

### Version
0.77.1

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by levithomason** [comment]
So we can debug and help, please provide a test case against the latest version.

**Comment by levithomason** [comment]
Note, all tests are passing and all doc examples are working: https://react.semantic-ui.com/addons/confirm.  It is likely something specific to your project.  Example, I've seen this happen when users load both bootstrap css and semantic ui css.

**Comment by selected-pixel-jameson** [comment]
Thanks Levi, I’ll try that.
