### ISSUE TITLE
onOpen callback does not fire when Modal is opened

### ISSUE THREAD

**Issue by danatemple** [Semantic-Org/Semantic-UI-React#2428]
### Steps
Look at the testcase on https://codesandbox.io/s/mmvx39qr0j Click the button to open the modal.
### Expected Result
callback function specified with onOpen prop should be called and log to console.
### Actual Result
Callback is not called
### Version
semantic-ui-react 0.75.1
### Testcase
https://codesandbox.io/s/mmvx39qr0j

**Comment by layershifter** [comment]
There is no bug, see #2423 for more details.
