### ISSUE TITLE
How to make a popup appear at mouse position?

### ISSUE THREAD

**Issue by githubaccount624** [Semantic-Org/Semantic-UI-React#2431]
For example, this popup: https://react.semantic-ui.com/modules/popup#popup-example-hide-on-scroll

When you click it, it goes at a certain position such as: 

    top lefttop rightbottom rightbottom leftright centerleft centertop centerbottom center

I'm trying to recreate context menu functionality, so I need it to appear at the clicked mouse position instead.

Is this possible?

**Comment by layershifter** [comment]
`Popup` has another usage, it's not possible and will be not possible in future.

**Comment by githubaccount624** [comment]
Are there any other ways to get a context menu? Or any reason why it's not supported?

https://github.com/Semantic-Org/Semantic-UI/issues/203

**Comment by layershifter** [comment]
Yes, should implement your own component that will wrap `Menu`. We will also accept PR for this add-on component.

**Comment by githubaccount624** [comment]
Oh, I don't really know how to do that. I'm still a noob when it comes to this stuff. Want to work on it together? Maybe you can give me some ideas or some place to start?
