### ISSUE TITLE
Export/Import SUI

### ISSUE THREAD

**Issue by ktmn** [Semantic-Org/Semantic-UI-React#2432]
Would it be possible to make the data in [SUI.js](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/SUI.js) file available for importing as such (or similar)

```
import { SUI } from 'semantic-ui-react';

console.log(SUI.COLORS);
// (13) ["red", "orange", "yellow", "olive", "green", "teal", "blue", "violet", "purple", "pink", "brown", "grey", "black"]
```

**Comment by layershifter** [comment]
No, it's private API and you should not rely on it. It will be removed from production builds in future.
