### ISSUE TITLE
How to expand the horizontal width size of Input ?

### ISSUE THREAD

**Issue by khanhtrannnn** [Semantic-Org/Semantic-UI-React#2435]
Hi all
I'm working with Reactjs project, and I use Semantic UI React to beautify the `Input`. However, it seems that `Input` is always showed in default size. How can I resize its width ?  

- I follow the instruction on [Semantic UI React Home page](https://react.semantic-ui.com/usage), I put this line of code to Html:
`<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.12/semantic.min.css"></link>`
- In js file I import:
 `import { Input } from 'semantic-ui-react';`
and render the input:
`<Input  value={this.state.firstName} onChange={this.handleInputFirstName}/>`

**Comment by keikeigd** [comment]
just add  `<Input
 value={this.state.firstName}
 onChange={this.handleInputFirstName} 
style={{ width: "500px" }}/>`
