### ISSUE TITLE
How to create a component that wraps a menu?

### ISSUE THREAD

**Issue by githubaccount624** [Semantic-Org/Semantic-UI-React#2436]
In response to this issue: https://github.com/Semantic-Org/Semantic-UI-React/issues/2431

and this one: https://github.com/Semantic-Org/Semantic-UI/issues/203

I'd like to create a context menu component. The suggested way was to make a component that wraps a Menu component.

I'm looking for some advice on how to go about this. Perhaps further details or elaboration so that I can begin?

**Comment by layershifter** [comment]
I've made an example how to pair [react-contextmenu](https://github.com/vkbansal/react-contextmenu) with SUIR, see [codesandbox](https://codesandbox.io/s/jv259mzkxy).
