### ISSUE TITLE
semantic-ui-react <Menu> component forces single page application to re-render each time i navigate to other pages

### ISSUE THREAD

**Issue by stramike** [Semantic-Org/Semantic-UI-React#2437]
The Menu re-renders each time I navigate through the pages. Can't figure out why it's happening. It's definitely not a problem with react-router. Rendering with simple Link tag (instead of Menu tag) does not re-render all the times.
### Steps
click on the menu items to change pages on the first sandbox listed below and then do the same on the second sandbox
### Expected Result
load the body component, not the whole page
### Actual Result
load the whole page
### Version
0.77.2 but it does the same with the version 0.75.1 in the sandbox

### Testcase
https://codesandbox.io/s/jllr496ywy
https://codesandbox.io/s/jn3l14n9zv

**Comment by layershifter** [comment]
https://stackoverflow.com/a/42086527/6488546

**Comment by stramike** [comment]
Sorry about that! My bad! Many thanks
