### ISSUE TITLE
Accordion, title in label. "Inline" within arrow icon.

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#2438]
I don't know if this is question is about CSS, I don't think. In this case, sorry.

### Steps

https://codesandbox.io/s/q305wzzw46

### Expected Result

Label "inline" within "arrow" icon.

### Actual Result

![image](https://user-images.githubusercontent.com/21275217/34986523-3244f7d6-fab8-11e7-96ad-5d010cd96242.png)

### Version
0.77.2

### Testcase
https://codesandbox.io/s/q305wzzw46

**Comment by layershifter** [comment]
This is a CSS issue and it can't be solved within SUIR.
