### ISSUE TITLE
Accordion, title link too long: max-width not on the link? With label or text.

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#2439]
I don't know if this is question is about CSS, I don't think. In this case, sorry.

### Expected Result

Link just on the label, not all the title line (mouse icon at least).

In the above screen I can click where is yellow painted.

**The problem is not only with label. Also with text only.**

### Actual Result

![image](https://user-images.githubusercontent.com/21275217/34987215-abd0c74a-faba-11e7-8dc7-5c07122d2a61.png)

### Version
0.77.2

### Testcase
https://codesandbox.io/s/p5vl9wp06q

**Comment by layershifter** [comment]
It's a valid behaviour, [SUI has same](https://semantic-ui.com/modules/accordion.html). If you need something other, you should modify CSS.

**Comment by ghost** [comment]
@layershifter can I insert `<br>` before every `<title>...</title>` in accordion?

**Comment by brianespinosa** [comment]
@johnunclesam adding a line break inside the title will not change the fact that `.title` is set as `display: block` in SUI css. They will always display to the full width of their container, which is the full accordion. And the title is what is being clicked to handle the active state.

If you want to change the click area to be something other than the full width container of `Accordion.Title` then you have to handle the active state of your accordion yourself. I threw together a quick codepen for you based on the first example of accordion in the docs. Note that there are two small inline CSS changes I added to change the cursor from the default SUI css. I'd recommend compiling your own CSS to get these changes (if you are using this UI everywhere for accordion) or adding a class to this accordion group with the custom styles (if this is something you are mixing with the default functionality/styles of accordion.

https://codesandbox.io/s/qvz9ppq56q
