### ISSUE TITLE
Accordion, activeIndex with and without "exclusive={false}". Works and doesn't.

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#2440]
### Steps

https://codesandbox.io/s/k2wlkoz5wr

### Expected Result

I need to have a "closeAll" button. But using `exclusive={false}`, because I need many line opened. It doesn't work.

### Actual Result

Just `exclusive={true}` works.

### Version
0.77.2

### Testcase
https://codesandbox.io/s/k2wlkoz5wr

**Comment by layershifter** [comment]
`exclusive={false}` required another state handling, see [codesandox](https://codesandbox.io/s/401lkvm09x).
