### ISSUE TITLE
Pagination cannot click inside Table.HeaderCell with definition option

### ISSUE THREAD

**Issue by iju707** [Semantic-Org/Semantic-UI-React#2441]
### Steps
1. make Table with _definition_ option. 
2. Add pagination inside HeaderCell
```javascript
<Table.Footer>
  <Table.Row>
    <Table.HeaderCell colSpan='5'>
      <Pagination floated='right' activePage={pageIndex + 1} totalPages={totalPage} onPageChange={this.onPageChange}/>
    </Table.HeaderCell>
  </Table.Row>
</Table.Footer>
```

### Expected Result
all button in pagination can be clicked and mouse pointer change to a cursor.

### Actual Result
Number in Pagination component cannot click.
but, after changing HeaderCell to Cell, it works.

### Version
- semantic-ui-react : 0.77.2
- semantic-ui-css : 2.2.12

### Testcase
https://codesandbox.io/s/vmjq0joyx3

**Comment by layershifter** [comment]
The are no bug, the `definition` prop adds `pointer-events: none;` on `th:first-child`:

![image](https://user-images.githubusercontent.com/14183168/35005487-296f6e4a-fafc-11e7-8e0e-2e2721095284.png)

--- 
See [this example](https://react.semantic-ui.com/collections/table#table-example-full-width), add the `fullWidth` prop to `Table.Footer` and everything will be fine.
