### ISSUE TITLE
Form.Radio onChange inconsistent with Form.Input

### ISSUE THREAD

**Issue by eldyvoon** [Semantic-Org/Semantic-UI-React#2442]
✔ BUGS → This form is required:

### Steps
Click on radio buttons and check the console
### Expected Result
onChange callback function should return the value as the input

### Actual Result
Got null for e.target.name and e.target.value
### Version
latest

### Codesandbox
https://codesandbox.io/s/nw1q806y60

**Comment by iju707** [comment]
maybe it will help you.
https://codesandbox.io/s/v3ywjx498y

**Comment by eldyvoon** [comment]
@iju707 thanks!
