### ISSUE TITLE
Responsive Grid not scaling up with window size?

### ISSUE THREAD

**Issue by mr-remington** [Semantic-Org/Semantic-UI-React#2451]
### Steps
I took the simple example of a responsive grid here:
https://react.semantic-ui.com/collections/grid#grid-example-container

Plugged it into a test app:
```
export class Test extends React.Component {
  render() {
    return (
      <Grid container columns={3}>
      <Grid.Column>
        <Image src='/assets/images/wireframe/image.png' />
      </Grid.Column>
      <Grid.Column>
        <Image src='/assets/images/wireframe/image.png' />
      </Grid.Column>
      <Grid.Column>
        <Image src='/assets/images/wireframe/image.png' />
      </Grid.Column>
    </Grid>
  )
```
### Expected Result
I would have expected the container to scale up as the Firefox window increased but it seems to hit a limit where it stops responding.

### Actual Result
See there: https://imgur.com/ZJdiXtF while 'root' shows as 1864 the grid container doesnt scale up to match it. 

Its entirely possible my expectation(I'm learning) is wrong but should it not scale the container and each column regardless how big I go?

I came across this with a different setup. Using a two grid column container. In the first using a sidebar with "<Grid.Column style={{ width: '260px'}}>" I noticed the second column did not scale up 

### Version
0.77.2

**Comment by layershifter** [comment]
Example's description:

> A container can be used alongside a grid to provide a responsive, fixed width container for wrapping the contents of a page.

You should remove `container` prop from `Grid` and everything will be fine.
