### ISSUE TITLE
Card: add centered prop to Card.Group

### ISSUE THREAD

**Issue by FIL1994** [Semantic-Org/Semantic-UI-React#2453]
Add centered prop to Card.Group

**Comment by brianespinosa** [comment]
Confirmed that `.ui.cards` in SUI does support the additional class of `.centered` in the CSS. We should add support for this in `Card.Group` with a boolean `centered` prop.

@FIL1994 for now, you can achieve this by adding a `className` of "centered" to your `Card.Group`.

**Comment by sudheerDev** [comment]
@brianespinosa can i give this a shot?.

**Comment by brianespinosa** [comment]
@sudheerDev absolutely! PRs are always welcome.

**Comment by sudheerDev** [comment]
@brianespinosa I did create a PR but not sure why coverage came down in visibility.js. Should I add an example for centred?.
