### ISSUE TITLE
Unable to pass custom props into Tab panes

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#2456]
Feature Request: Add ability to pass custom props into tab panes. For example: 

    const panes = [
        {menuItem: 'Tab1', render: (props) => (<Tab.Pane><MyComponent1 {...props.MyProp} /></Tab.Pane>)},
        {menuItem: 'Tab2', render: () => (<Tab.Pane><MyComponent2 /></Tab.Pane>)}
    ];

    <Tab panes={panes} {...otherProps}>

**Comment by brianespinosa** [comment]
@layershifter @levithomason is there any way to do this with the shorthand API like this, or is this something you can only currently do with the subcomponent API?

**Comment by brianespinosa** [comment]
Also @leantide you want to be careful about arrow functions in your render. It's going to cause a render for each child component. It can also make `shouldComponentUpdate()` return false positives.

**Comment by levithomason** [comment]
Assuming `otherProps.MyProp` exists, this works exactly as you've requested:

https://codesandbox.io/s/l2p3xjrp37

All props are passed to the `render` of each pane.
