### ISSUE TITLE
Docs: broken rerender on same name props' values

### ISSUE THREAD

**Issue by gitname** [Semantic-Org/Semantic-UI-React#2460]
*This comment was updated on January 30, 2018, to reflect **the more general issue** that included the behavior described in the original comment. You can see the original comment below the horizontal line.*

**Updated comment:**

Here is a description of the more general issue:

In the docs, when I visit the "Icon" page and then visit the "Popup" page, I see the `size` options from the former appear on the latter. For example, the option "massive" appears on the "Popup" page, where it does not belong.

This behavior is demonstrated in the following screencast:

![image](https://user-images.githubusercontent.com/7143133/35376765-58c28f5e-0161-11e8-869b-17a357dd7eff.gif)

---

**Original comment** (created on January 24, 2018):

### Steps

1. Instantiate a Popup with a `size` of "massive"
    ```jsx
    <Popup
      trigger={<Button icon='add' />}
      content='Add users to your feed'
      size='massive'
    />
    ```

### Expected Result

The Chrome JavaScript console displays no warnings.

### Actual Result

The Chrome JavaScript console displays the following warning:

![image](https://user-images.githubusercontent.com/7143133/35320225-ea053018-0097-11e8-8359-5295d63e3393.png)

```text
Warning: Failed prop type: Invalid prop `size` of value `massive` supplied to `Popup`, expected one of ["mini","tiny","small","large","huge"].
```

### Version

0.77.2

### Testcase

Here's a demo of the issue:
https://codesandbox.io/s/101o69mrz7

**Comment by brianespinosa** [comment]
@gitname the size of "massive" is not supported for the `Popup` component. The documentation does _not_ show "massive" as a valid enumerated value for `size` on a popup: https://react.semantic-ui.com/modules/popup

![image](https://user-images.githubusercontent.com/1161781/35349363-8f809daa-00ef-11e8-9a91-4a333dc17e68.png)

This is because that in SUI, there are no styles or class for that value on a popup, which can be seen here: https://semantic-ui.com/modules/popup.html#size

**Comment by gitname** [comment]
Thanks for addressing this. You are correct: the Popup documentation does not show "massive" as a valid value for its `size` prop.

:warning: **EDIT: Sometimes it *does*!** See next comment. :warning:

---

When I created this issue, I was reading what I thought was the Popup docs, and saw "massive" listed as a valid value for the `size` prop. I even linked to the Popup docs in the demo I created. Now, I think I had been unknowingly reading the docs for a different component, which would have been my mistake, indeed.

Lessons learned:
* Double-check the docs page I'm on
* Include a screenshot in the Issue description

Sorry I did not do those things this time. I'll do them next time.

**Comment by gitname** [comment]
**UPDATE:**

Sometimes it *does* show it!

![image](https://user-images.githubusercontent.com/7143133/35354799-192a775a-0100-11e8-9c7f-1b63dbc262fa.png)

![image](https://user-images.githubusercontent.com/7143133/35354839-37a986a8-0100-11e8-8b65-df2b39f5c76c.png)

*What in the world...?*

:confused:

---

I'm out of time for now, but I'll come back to this later and try to come up with steps by which someone can reproduce this Docs behavior.

**Comment by brianespinosa** [comment]
@gitname I will reopen this issue since it sounds like there may be an issue with the docs. Might be the way some data is getting reused in the views. Thanks for checking back to look at this and including screenshots.

**Comment by gitname** [comment]
@brianespinosa I managed to reproduce this "inconsistent docs" behavior again just now by doing the following:

1. Go to https://react.semantic-ui.com
2. In the left menu, click on "Icon"
3. Scroll down and see the presence of "massive" in the `size` list (as expected) :white_check_mark: 
4. In the left menu, click on "Popup"
5. Scroll down and see the presence of "massive" in the `size` list (not as expected) :fire: 

On the other hand, when I did the above steps in the following order `{1, 4, 5, 2, 3}`, I saw "massive" **missing** from the "Icon" `size` list! It's as though the set of valid values from the first component I select, is used again by the second component I select.

I'll be out again for a few hours, and will check this Issue this when I return.

**Comment by gitname** [comment]
Here's a screencast GIF in which I demonstrate the issue:

![2018-01-24_23-49-17](https://user-images.githubusercontent.com/7143133/35376765-58c28f5e-0161-11e8-869b-17a357dd7eff.gif)

The screencast also contains a clue (I think) as to what's going on: I happened to select the `size` values on the "Icon" page. When I navigated to the "Popup" page, ***its*** `size` values were selected, too! It's as though the web browser considers them to be the same DOM elements.

**Comment by gitname** [comment]
Here's a screencast GIF that can serve as evidence that the web browser does consider them to be the same DOM elements.

![2018-01-25_00-06-03](https://user-images.githubusercontent.com/7143133/35377349-a53cae12-0163-11e8-9960-055fffd737c2.gif)

In this 40-second screencast, I modify `element.style` of the "small" `<code>` element on the "Icon" page, and it (surprisingly) affects the "small" `<code>` element on the "Popup" page in the same way!

**Comment by layershifter** [comment]
I'm almost sure that problem is somewhere [there](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/Components/ComponentDoc/ComponentProp/ComponentPropEnum.js#L46), we use some HOCs that block rerenders, seems we have a problem there.

**Comment by gitname** [comment]
FYI: I still see the issue happening at https://react.semantic-ui.com/. That may be because, although you've fixed it in the code, the version of the code containing the fix hasn't been deployed to https://react.semantic-ui.com/ yet. I don't know whether that's the case.

**Comment by levithomason** [comment]
Please submit a new issue with a complete report.
