### ISSUE TITLE
Step and Step.Group element usage. How do I deactivate a completed step and move on(activate) to the next in the Step Group or even in a chain of Steps without a group?

### ISSUE THREAD

**Issue by VincentVerne** [Semantic-Org/Semantic-UI-React#2461]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes

✔ BUGS → This form is required:

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Please use [StackOverflow](https://stackoverflow.com/questions/tagged/semantic-ui-react) for usage questions.

**Comment by VincentVerne** [comment]
OK. Thanks
