### ISSUE TITLE
fix(Accordion): inverted not working properly

### ISSUE THREAD

**Issue by augustblack** [Semantic-Org/Semantic-UI-React#2466]
**Steps to Reproduce**
1. add inverted={true} to top-level <Accordion>

**Expected**
The Accordion should have its color inverted

**Result**
The Accordion does not have its color inverted.  When you set inverted={true} on an accordion panel, the backround does not invert, but the text color does.

**Comment by brianespinosa** [comment]
@augustblack This works as expected. The SUI styles for inverted on an accordion do not also change the `background-color` of the accordion. Only the `color`. If you want a dark background color you can wrap your `Accordion` component in a `Segment` component with an `inverted` prop. In fact... that is what the docs are showing on the SUI core docs: https://semantic-ui.com/modules/accordion.html#inverted
