### ISSUE TITLE
Menu.Item position="right" has no effect 

### ISSUE THREAD

**Issue by VincentVerne** [Semantic-Org/Semantic-UI-React#2470]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes

✔ BUGS → This form is required:

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by VincentVerne** [comment]
When using as={ConfirmLogout}, where ConfirmLogout is a Modal with Button as a trigger

**Comment by brianespinosa** [comment]
Please complete the full bug report form, including a codesandbox example.
