### ISSUE TITLE
Popup doesn't work correctly until it's clicked multiple times

### ISSUE THREAD

**Issue by kaiyoma** [Semantic-Org/Semantic-UI-React#2471]
### Steps
Implement the controlled popup as described here:

https://react.semantic-ui.com/modules/popup#popup-example-controlled

### Expected Result
The popup should display correctly when the trigger is clicked the first time or if `open={true}` initially. Also, the `open` prop should be documented here:

https://react.semantic-ui.com/modules/popup

### Actual Result
The trigger has to be clicked multiple times before the popup appears in the correct place. If `open={false}` initially, the trigger has to be clicked three times; if `open={true}`, the trigger has to be clicked two or four times.

Also, the `open` prop doesn't appear in the documentation.

### Version
0.77.2

### Testcase
This shows the problem when `open={true}` initially: https://codesandbox.io/s/20lm45zn00

Notice how the rendering of the popup is very wrong and stuck in the upper-right corner of the pane. If you click the link twice, then the popup appears where it should.

**Comment by kaiyoma** [comment]
Ah, I think I see the problem: I wasn't including the Semantic UI CSS, which apparently is necessary in this case for everything to work properly. If someone could verify that, that would be great.

There's still a minor issue with the `open` prop not being documented though.

**Comment by layershifter** [comment]
Duplicate #1065.
