### ISSUE TITLE
Popup: add prop to optionally find an "in viewport" position

### ISSUE THREAD

**Issue by vasilevich** [Semantic-Org/Semantic-UI-React#2472]
problem:
when I set the popup to a certain position,
https://react.semantic-ui.com/modules/popup
such as: 
`bottom left`
but the window is too small to allow bottom left direction,
the popup goes back to automatic position.

This should not happen! you should give an option to force a position direction,
the position is set with the intent to be enforced, not a suggestion,
sometimes the content inside the popup is too big, and the only way to ensure that the full content is  seen is to direct it to the bottom, because the web browser will add scrollers anyway.
please consider either enforcing the position, or adding a parameter to make it automatically.

### Steps

1. create popover on any page with a large amount of content, such as a form, or an image or just 20 lines of text for example.
2. set position `bottom left`
3. before you open the popup, resize the browser window to the button that opens the popup.
4. click the buttton that opens the popup.

### Expected Result
the popup opens as expected, towards bottom left, and the web browser adds scrollers anyway... to accomodate this effect.
### Actual Result
the popup opens to any direction which has space... usually top left, this is not supposed to happend,
it makes the setting "bottom left" not very useful.
### Version
0.71.5

please provide any hints, i can do a pull request if neccresary.

thank you!

**Comment by brianespinosa** [comment]
@vasilevich please complete the full issue report and include a codesandbox example

**Comment by Avivhdr** [comment]
@vasilevich 
I Fixed it in the following wrapper component. Semantic-ui-react's Popup component has a **_isStyleInViewport_** method .This method checks if the popup should be displayed in a different position, rather then the one it was passed to it in the _position_  prop, when there is not enough space for it in the current view port.
This wrapper component will overrides this method when passed a _**fixed**_ prop, causing the Popup to always open in it's giving _position_  prop.



The wrapper component:
```

/**
 *
 * PopupWrapper:
 *
 *
 * added 'fixed' prop:
 * will position the popup in it's original position,
 * regardless of the view port width/height.
 *
 */

import React from 'react';
import { Popup } from 'semantic-ui-react';
import PropTypes from 'prop-types';

class PopupWrapper extends React.Component {

  static propTypes = {
    fixed: PropTypes.bool,
  };

  constructor(props) {
    super(props);

    if (this.props.fixed) {
      Popup.prototype.isStyleInViewport = () => { };
    }
  }

  render() {

    const { fixed, ...popupProps } = this.props;

    return (
      <Popup {...popupProps}  />
    );
  }
}

export default PopupWrapper;

```

**Comment by vasilevich** [comment]
Thank you for your suggestion, I will try it out!

**Comment by levithomason** [comment]
I would accept a PR that added a prop such as `keepInViewport` so long as it defaulted to true to maintain compatibility.  I'm also open to better prop names.

**Comment by lalau** [comment]
I was looking for solution for the same thing. I thought it's been solved by the new `keepInView` prop. Then I found out it's been removed when `Popup` moved to use **popper.js**. To achieve the same effect I have to use popper's modifier by adding this prop:
```
      popperModifiers={{
        preventOverflow: { enabled: false },
        flip: { enabled: false },
      }}
```
Just want to share it here for anyone looking for the same thing.
