### ISSUE TITLE
Add support for react and react-dom 16.2.0

### ISSUE THREAD

**Issue by hisuwh** [Semantic-Org/Semantic-UI-React#2473]
### Steps
Updated my project dependencies of react and react-dom to 16.2.0 so that I could use Fragments. 

I realise Semantic-UI-React doesn't support this version.

Would be really good to have this for the aforementioned Fragments - which I need because semantic-ui has lot of direct descendant styling `>` which wrapping components in `div` tags breaks.

### Expected Result
It works

### Actual Result
Lots of errors like: 
`JSX element type 'Button' is not a constructor function for JSX elements.`

### Version
0.77.2

### Testcase
https://codesandbox.io/s/r7qq1m010q

**Comment by layershifter** [comment]
Latest version supports React 16.2, there are no any needed changes. Your codepen shows that everything works.

**Comment by hisuwh** [comment]
Well I'm getting the following errors with react and react-dom 16.2.0 and semantic-ui-react 0.77.2

![image](https://user-images.githubusercontent.com/4470351/35523509-ed4c9abc-0516-11e8-942a-a245aee34fc4.png)

**Comment by hisuwh** [comment]
Downgraded to react and react-dom 16.0.0 and it builds.
Please resolve this.

**Comment by layershifter** [comment]
Remove your `node_modules` and run install again, also check that you have `react-dom` in dependencies. This error has nothing mutual with SUIR.

**Comment by hisuwh** [comment]
I have done both these things

**Comment by brianespinosa** [comment]
@hisuwh to be clear, your codepen literally shows SUIR working with the latest 16.2 version of `react` and `react-dom`. I actually am using the latest version of these two libraries with SUIR in my current projects as well with no problems.

What package manager are you using? `npm` or `yarn`?

**Comment by hisuwh** [comment]
When I initially set that codepen up it wasn't working - I wouldn't have posted the issue if it had.

I'm using npm. I'm also using Typescript - don't know if that could be a factor (v2.6.2)

**Comment by brianespinosa** [comment]
@hisuwh Yeah... it is hard to say without seeing your webpack config too. It might be something in one of your loaders. I also would strongly encourage you to use `yarn` over `npm`. The reason I asked that is I experienced issues similar to this before I switched. Sometimes npm resolves packages in an odd way, even after deleting `/node_modules`. Once I switched to using `yarn` I have not had any issues like this.

**Comment by hisuwh** [comment]
So it seems deleting node_modules and package-lock.json and reinstalling worked - sorry for wasting everyones time.
I may look at yarn.  Thanks for the tip

**Comment by brianespinosa** [comment]
@hisuwh glad it worked. Basically it sounds as if all of your issues were `npm` related. Hopefully `yarn` works out for you in the future. There are a lot of benefits to it besides those outlined above.

**Comment by hisuwh** [comment]
Thanks.  @brianespinosa might have some convincing to do in my company to use yarn
