### ISSUE TITLE
Closable menu tabular / tab

### ISSUE THREAD

**Issue by PurwadiPw** [Semantic-Org/Semantic-UI-React#2484]
```
<Menu tabular>
 {
  menus.map((menu, index) => (
   <Menu.Item 
    key={index} 
    name={menu.name} 
    active={this.props.location.pathname === menu.path} 
    onClick={() => {this.props.handleOpenClick(menu)}} 
   >
    {menu.name}
    <Button onClick={() => {this.props.handleCloseClick(index)}}>X</Button>
   </Menu.Item>
  ))
 }
</Menu>
```

I want to create a dynamic tabular layout with closable feature by using `Menu` and `tabular` option. I put the `Button` component inside a `Menu.Item` and implement the onClick event. 
When the buton is clicked, it's also calling `handleOpenClick()` function on the `Menu.Item` component. I need to call the `handleCloseClick()` only.

Is there any suggestion ?
Sorry for my bad english

**Comment by levithomason** [comment]
Please use the provided Gitter and StackOverflow links for help requests.  The GitHub repo is focused strictly on bug fixes and feature development.
