### ISSUE TITLE
Using Custom Component as a Modal Trigger?

### ISSUE THREAD

**Issue by mayordwells** [Semantic-Org/Semantic-UI-React#2487]
I've used Sematic-UI-React in multiple projects and I can say that I've read the documentation multiple times and I've used most of its component. Only one problem I encounter all the time is with its Modal component. 
For example, I want to use a custom component as a Trigger, I checked the src code and the documents and all odds say this should work, but for some reason, it's not working 
Here's my code: 
I have a Card Component.
```
import React from 'react';
export default class TeachersCard extends React.Component {
  render() {
    return (
      <div className="card">
        <div className="image">
          <img src={this.props.imgSrc} />
        </div>
        <div className="content text-center">
          <a className="header">{this.props.header}</a>
          <h6 className="card-subtitle mb-2 text-muted"></h6>
          {this.props.location}
        </div>
      </div>
    );
  }
}
```

And then a Modal component where I want to use the teacher's card as a trigger
```
import React from 'react';
import { Modal, Header, Icon, Button } from 'semantic-ui-react'
import TeachersCard from './TeachersCard';
export default class TeachersModal extends React.Component {
  render() {
    return (
	    <Modal trigger={<TeachersCard imgSrc="/teacher-online_1.jpg" header="John Joe" location="Toronto, Canada"></TeachersCard>} closeIcon>
		    <Header icon='archive' content='Archive Old Messages' />
		    <Modal.Content>
		      <p>Your inbox is getting full, would you like us to enable automatic archiving of old messages?</p>
		    </Modal.Content>
		    <Modal.Actions>
		      <Button color='red'>
		        <Icon name='remove' /> No
		      </Button>
		      <Button color='green'>
		        <Icon name='checkmark' /> Yes
		      </Button>
		    </Modal.Actions>
		  </Modal>
    )
  }
}
```

And then I'm rendering it on the page like this:
```
import React from 'react';
import TeachersModal from './TeachersModal';
export default class TeachersSection extends React.Component {
  render() {
    return (
      <div className="container-fluid mt-5 box">
        <div className="mb-4 pt-3">
          <h1>Teachers Online</h1>
        </div>
        <div className="ui seven stackable cards">
          <TeachersModal />
          <TeachersModal />
          <TeachersModal />
          <TeachersModal />
          <TeachersModal />
          <TeachersModal />
          <TeachersModal />
        </div>
        <div className="text-center">
          <button className="huge ui inverted green button mt-5 mb-4 call-to-action-btn">
            View All Teachers
          </button>
        </div>
      </div>
    );
  }
}
```

The expected result is that when I click on the TeachersModal Component. It should render the modal as expected.

But the actual result is that I don't see an error in console and no modal is being rendered. Is it that it's not possible to use a custom component as a trigger?

I'm using the latest version of react-semantic-ui in this project.
### Testcase (My Testcase here)
https://codesandbox.io/s/ll67qjlj1z

Here's how it shows on my side
<img width="1173" alt="screen shot 2018-02-03 at 3 35 06 pm" src="https://user-images.githubusercontent.com/1370340/35767162-e065dee6-08f7-11e8-8fdb-185c5a925a91.png">

Maybe there's something I'm doing wrong, but I would appreciate your help in fixing this error. 
Thanks.

**Comment by levithomason** [comment]
Your custom component needs to spread unhandled props.  Triggers will be passed additional props so they can trigger the Modal.

https://codesandbox.io/s/n4kxojmx90

Note the use of `...rest` here:

```jsx
const TeachersCard = ({ header, imgSrc, location, ...rest }) => (
  <div className="card" {...rest} >
...
```

You also had several references to `this.props` in stateless components.  There is no `this.props` in functional components as the props are passed in as the first argument.
