### ISSUE TITLE
Dropdown: clicking outside the dropdown should not add new item to the list

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#2488]
### Steps
- Add a Semantic-UI-React dropdown component which includes both the 'search' and the 'allowAdditions' option. Implement the onAddItem event callback. 
- Click into the search box and type some unique text not already available in the dropdown, but don't hit enter.
- Click somewhere outside the dropdown

### Expected Result
No additional item is added to the dropdown list since neither the enter key was not pressed nor the 'Add' line entry was clicked.  

### Actual Result
An additional item was erroneously added to the dropdown list. 

### Version
semantic-ui-react@0.77.1

**Comment by levithomason** [comment]
Please provide a test case provided in the issue template.  We do not have enough time to create samples and debug all issues.  Also, please use the latest version, 0.77.2 at the time of writing.
