### ISSUE TITLE
Dropdown: Multiple repetitive line entries erroneously added to the dropdown list

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#2489]
### Steps
- Add a Semantic-UI-React dropdown component which includes both the 'search' and the 'allowAdditions' option. Implement the onAddItem event callback. 
- Click into the search box and type some unique text not already available in the dropdown, but don't hit enter.
- Using arrow keys, traverse the active cell up and down past the 'Add' line entry a few times.

### Expected Result
No additional item is added to the dropdown list since neither the enter key was not pressed nor the 'Add' line entry was clicked.  

### Actual Result
Multiple repetitive additional items were erroneously added to the dropdown list, one for each time the user navigated past the 'Add' line entry using the arrow keys. 

### Version
semantic-ui-react@0.77.1

**Comment by levithomason** [comment]
Please provide a working codesandbox example using the link in the issue template.  I apologize, we simply don't have the time to recreate all issues ourselves.
