### ISSUE TITLE
Dropdown: Clicking in and out of it after having selected an item automatically selects other

### ISSUE THREAD

**Issue by JulsRicketti** [Semantic-Org/Semantic-UI-React#2490]
https://react.semantic-ui.com/modules/dropdown

### Steps
1- Create a Dropdown with any variation of props
2- Fill in the options whichever way you'd like
3- Select an item from the Dropdown (Important! Bug does not happen if you don't make a selection first)
4- Open the Dropdown again, but this time, click out of it without selecting a new item

### Expected Result
Nothing to happen. The selected option stays the same and the Dropdown closes.

### Actual Result
Another option is randomly selected and component quickly blinks.

### Version
0.75.1

**Comment by levithomason** [comment]
I am unable to reproduce this.  Please use the latest version, 0.77.2, and provide a test case linked in the issue template.

![http://g.recordit.co/3BxF4iQzK9.gif](http://g.recordit.co/3BxF4iQzK9.gif)

**Comment by JulsRicketti** [comment]
It turned out that it did indeed go away whenever I updated to the latest version.

Thanks!
