### ISSUE TITLE
Form onSubmit should accept HTMLFormElement event

### ISSUE THREAD

**Issue by corydeppen** [Semantic-Org/Semantic-UI-React#2500]
It's not a bug, but rather a request to change the [TS definition](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/collections/Form/Form.d.ts#L38) for the `event` parameter for `onSubmit` from `React.FormEvent<HTMLElement>` to `React.FormEvent<HTMLFormElement>` in the `Form` component. This seems more appropriate and will allow it to handle events from other libraries like Formik without a compilation error. I don't mind submitting the PR to make this quick change if there is agreement.

**Comment by levithomason** [comment]
Agreed, thanks!
