### ISSUE TITLE
Progress: if progress is set to `value` and both value and total are set, display progress bar at the percentage of value/total

### ISSUE THREAD

**Issue by rachelslurs** [Semantic-Org/Semantic-UI-React#2502]
**Steps to Reproduce**
1. Render a `<Progress/>` component with these props
```
<Progress progress='value' value={35} total={50} />
```

**Expected**
The Progress bar should show it's 70% complete (percent value 35 divided by total 50). I want it to behave the same way `progress='ratio'` does, but without the `/{total}`

**Result**
The Progress bar sets it to 35% complete

**Testcase**
https://codepen.io/rachelslurs/pen/ZrpMYJ

**Comment by levithomason** [comment]
Fixed in https://github.com/Semantic-Org/Semantic-UI-React/pull/2503
