### ISSUE TITLE
Popup min-width doesn't work in IE11 and Edge

### ISSUE THREAD

**Issue by lafritay** [Semantic-Org/Semantic-UI-React#2508]
### Steps
Create a popup with contents that'll cause it to grow wider than it's default size

### Expected Result
The popup expands to the size of the content.

### Actual Result
It works on Chrome and Firefox.  It does not expand in IE11 or Edge.

### Version
0.77.1

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/5wnmm28xlk

Note: That sandbox won't even open in IE11.  I'd recommend viewing it in Edge.  

In Chrome you'll see:

![image](https://user-images.githubusercontent.com/438824/35952162-b93ebae2-0c4c-11e8-92d8-2775c788dbe8.png)

In Edge you'll see:

![image](https://user-images.githubusercontent.com/438824/35952168-c1956f2e-0c4c-11e8-8e74-6aeb0c1d6b4e.png)

**Comment by lafritay** [comment]
For my case, I was able to workaround this using wide='very', though I don't think that'll work for all scenarios.  Ultimately, this seems to be caused by the default max-width being set to 250px and the min-width styles not applying on IE or Edge.

**Comment by brianespinosa** [comment]
Thanks for the report, @lafritay. CSS related issues should be reported on the [core SUI project](https://github.com/Semantic-Org/Semantic-UI). Styles are not part of SUIR.
