### ISSUE TITLE
Sticky Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by owlyowl** [Semantic-Org/Semantic-UI-React#2509]
✔ BUGS → This form is required:

### Steps
When mutliple sticky's are on the page if their context element is hidden initially and then shown, as the sticky initialises  _this.triggerRef gets the context first pass.. then second pass it is set to null.. errors and then sets the context correctly again..

1. Render 2 responsives.
2. Add Stickies inside.
3. Responsives mount then unmount then mount as part of the initialisation to show/hide
3. Sticky blows up because of the unmounting responsive component which causes the ref on the parent div to be null.

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by brianespinosa** [comment]
Please complete the entire bug report form, including version number and codesandbox test case.
