### ISSUE TITLE
Create-react-app - how do I customize the theme without ejecting?

### ISSUE THREAD

**Issue by dilizarov** [Semantic-Org/Semantic-UI-React#2512]
I want to edit one property in Semantic-UI, and it is the shade of blue of it's blue. By using site.variables or something, I think it'll also effect the hover/focus views to appropriately use the new blue. I don't know how to do this in a create-react-app world. Ideally, I wouldn't have to eject from there and then handle the build myself.

**Comment by layershifter** [comment]
Without eject you can only override CSS, however it's a bad idea. For now, eject is the best solution for customized SUI, see #2371 for examples.

**Comment by hprobotic** [comment]
Hi guys, I have a examples with CRA, you guys don't need to eject CRA
https://github.com/hprobotic/semantic-ui-create-react-app-example
