### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by ryanpcmcquen** [Semantic-Org/Semantic-UI-React#2515]
I have searched the docs and previous issues and cannot find a browser compatibility table. What is the browser support? Is it documented?

**Comment by levithomason** [comment]
It is not documented.  However, we intend to be compatible with all browsers that React 15 is compatible with.  If you find a bug, please file it and let us know.  We cannot support browsers beyond what React itself supports as this library is built on React.

https://reactjs.org/docs/react-dom.html#browser-support

**Comment by ryanpcmcquen** [comment]
Cool, so IE9+.
