### ISSUE TITLE
Dropdown: Add debounce for search query

### ISSUE THREAD

**Issue by neerajhiretual** [Semantic-Org/Semantic-UI-React#2520]
**Steps to Reproduce**
1. Follow the [link](https://react.semantic-ui.com/modules/dropdown#dropdown-example-search-query)

**Expected**
The Dropdown should have option for deboncing on input.

**Result**
The Dropdown does not do this.

**Comment by brianespinosa** [comment]
Hello, @neerajhiretual you are referencing the docs does not have a debounce function on the `handleSearchChange()` functions. That is where the debounce function would exist in your production code, not in the Dropdown component itself. [Here's an example for you](https://stackoverflow.com/questions/23123138/perform-debounce-in-react-js). If you would like to add an additional example for how to add a debounce function to a dropdown with search functionality, PRs are welcome.

**Comment by neerajhiretual** [comment]
@brianespinosa  Thanks for the link but I know we can add debounce.
But what i meant was, debounce should be supported internally for drop-downs where options come from ajax. Having a simple debounce property with a millisec value would be much easier to use. Just a suggestion!

**Comment by brianespinosa** [comment]
@neerajhiretual the Dropdown example you linked to is not getting data from AJAX. The function you would create to get that data onSearchChange would be where you would want to place your debounce function.

There is no debounce in SUI or SUIR except on components that are adjusting to viewport size/position like modals or popups.

If you complete the full bug report form showing a codesandbox example of your issue, it will be easier to address your concerns.

**Comment by levithomason** [comment]
@neerajhiretual note, you can achieve this with a controlled Dropdown component.  You can pass your own `open` prop, `searchQuery`, `onSearchChange`, and `search` (function) props.  With these, you can fully control how the Dropdown opens, how the query is used, and how the search filters the list (or doesn't, but requests items from an API).  You could then use any debounce settings you like.

We don't want to add settings for every use case, but rather we add hooks for users to support any use case.
