### ISSUE TITLE
fix(Dropdown): searchQuery not visible 

### ISSUE THREAD

**Issue by egecetindag** [Semantic-Org/Semantic-UI-React#2527]
**Steps to Reproduce**
1. write sth to searchable dropdown for react on the website .

const DropdownExampleSearchDropdown = () => (
  <Dropdown
    button
    className='icon'
    floating
    labeled
    icon='world'
    options={languageOptions}
    search
    text='Select Language'
  />
)

**Expected**
Dropdown size must be the same and you should see the search query. But width of the dropdown input box gets smaller when you write something to it. 

**Result**
Dropdown size changes so you cannot see the search query
Just make dropdown width fixed or % to fix

**Comment by levithomason** [comment]
Hi, please complete the entire issue template.  We are eager to help but I am unable to understand the issue.
