### ISSUE TITLE
Feature Request : Add renderItem to List (and childs)

### ISSUE THREAD

**Issue by nicodmf** [Semantic-Org/Semantic-UI-React#2528]
Like react native use renderItem in  https://facebook.github.io/react-native/docs/virtualizedlist.html and dependents children, it will be a good idea to support this type of writing : 

```jsx
<List items={[{p1: "val1"}, {p2: "val2"}]} renderItem={(item, key)=>(<Component>...</Component>)}>
```

**Comment by levithomason** [comment]
Yep.  We currently use shorthand factories for this and handle the callback internally.  However, it would be very easy to expose that as a prop and include our current callbacks as the defaults.

This would be something we should implement library-wide for all shorthand on all components.

**Comment by levithomason** [comment]
I would like to add a `render*` prop to all components that accept an array of data.  Examples, Menu `renderItem`, Dropdown [renderItem](url), Breadcrumb `renderSection`, etc.
