### ISSUE TITLE
fix(Table): Responsive mode causes an extra line to appear in footer

### ISSUE THREAD

**Issue by blaytenshi** [Semantic-Org/Semantic-UI-React#2535]
**Steps to Reproduce**
Using the Standard Table Example (first example in Table Section).
Switch the browser to view the example in responsive mode in 'mobile' widths.
Table Footer shows a line cutting across buttons.

**Expected**
Table footer should NOT show a line cutting across buttons.

**Testcase**
If the docs show the issue, use: undefined

**Possible Cause?**
From experimenting, I've noticed that if I remove the float right on the component in the footer, the line disappears. It doesn't matter if i float left or float right, the line appears. Perhaps float is causing some issues here?

CodeSandbox Demonstrating the issue:
https://zwo7kl864l.codesandbox.io/

**Comment by levithomason** [comment]
This is a CSS issue and should be posted to https://github.com/Semantic-Org/Semantic-UI

However, a parent with floated children will collapse unless the parent has `overflow: hidden;` set.  A very simple workaround, for now, is to add this style to the cell containing the floated menu:

https://codesandbox.io/s/pkl2w8980m

```jsx
<Table.Cell colSpan="3" style={{ overflow: 'hidden' }}>
```
