### ISSUE TITLE
Icons will not show in Meteor 1.6

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#2539]
I am using semantic-ui-react 0.78.2 with Meteor 1.6

```
import {Button, Icon} from 'semantic-ui-react';
.....
<Button onClick={this.customFunction}>
     <Icon name='trash' />
</Button>
```

Icons are replaced with empty boxes.

The browser shows these messages:
```
Low network is detected. Fallback font will be used while loading: http://localhost:3000/themes/default/assets/fonts/icons.woff2

Failed to decode downloaded font: http://localhost:3000/themes/default/assets/fonts/icons.woff2

OTS parsing error: invalid version tag
```

I looked over the other issues and none of the given solutions work.

**Comment by layershifter** [comment]
This error isn't related to SUIR. It seems that `http://localhost:3000/themes/default/assets/fonts/icons.woff2` file is unaccessible.

**Comment by ghost** [comment]
Why would you that? The icons come from semantic-ui. I am using Meteor with React. So the only way to use Semantic is through Semantic-UI-React

**Comment by brianespinosa** [comment]
@gabimoncha the icons come from the CSS. It's a font file. The CSS and fonts are not part of this project. If a file is not accessible in your project you'll need to figure out where those fonts are actually located and then recompile your CSS to the appropriate location.

**Comment by ghost** [comment]
@brianespinosa @layershifter I discovered the problem. If you use Meteor with React is not enough just do have [Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React). You also need the [Semantic-UI-CSS](https://github.com/Semantic-Org/Semantic-UI-CSS) for the Icons to show or else it will show you empty squares and the error message shown in the initial issues post.
The icons show if you follow the Semantic-UI-Meteor instructions. I think you should include the installation instructions for Meteor 1.3+ of [documentation](https://github.com/Semantic-Org/Semantic-UI-Meteor) in yours. I can do it if you allow me.

**Comment by brianespinosa** [comment]
@gabimoncha you have to use the SUI CSS for EVERYTHING, not just the font. This is already included in our documentation under Usage: https://react.semantic-ui.com/usage#css

**Comment by ghost** [comment]
@brianespinosa, exactly! I tried that but it doesn't work. It shows the error with which I opened this issue. But if you install it as I described earlier you don't need to use `import 'semantic-ui-css/semantic.min.css';`
You just `import 'semantic-ui-react'`

**Comment by gjakab** [comment]
I have the same problem with meteor 1.6.1 despite installing and importing the required semantic-ui-css, semantic-ui-react npm packages.

**Comment by ghost** [comment]
@gjakab Revert to meteor 1.6. I encountered numerous problems with my packages when updating to 1.6.1
