### ISSUE TITLE
Dropdown autoFocus attribute does not work

### ISSUE THREAD

**Issue by martlaboloa** [Semantic-Org/Semantic-UI-React#2540]
**small FYI**: _There’s an autofocus HTML attribute that puts the focus into an element by default when a page loads._

### Steps... Expected Result... Actual Result:

used dropdown in very simple way, given **autoFocus** attribute true, but its not working, as I saw you guys use "input"  as a dropdown not "select"...  Maybe you did not thought about autofocus capabilities of your dropdown, anyway as you probably guessed this is a **feature request** or bug, depends how you look at it i guess, I want to know if you will be adding it at all and if you are **approximately when** can I expect it, or should I move on. It critical for me. ty
 
### Version
^0.77.1

### Testcase
https://codesandbox.io/s/pj7o0x2jz0

**Comment by brianespinosa** [comment]
@martlaboloa There is an example of how to do this in the docs and there is also an issue already opened for this with a link to that example as well as a working codepen example: https://github.com/Semantic-Org/Semantic-UI-React/issues/2108
