### ISSUE TITLE
Input throws error when used with custom input as input for Search

### ISSUE THREAD

**Issue by gregor-mueller** [Semantic-Org/Semantic-UI-React#2541]
### Steps
Have a Search component that has an Input component that itselft has some JSX as children as value for the input prop.

`render() {
  const customInput = (
    <Input
      placeholder='search'
    >
      <input />
      <span className='bar'/>
    </Input>
  );
  return (
    <Search input={customInput}/>
  );
}`
_(markup broken, see test case for better layout)_

I can't wrap the children (input and span) in e.g. a div or span and use the `input` prop on the search (which would prevent the error from being thrown) as this would destroy my DOM. Using an array to pass the children as props (without wrapped span or div) does not work either.
I guess another fix would be using [Fragments](https://reactjs.org/docs/fragments.html) but I don't have access to that right now.

### Expected Result
No Error should be thrown.

### Actual Result
The setup works but the Input Component throws the following error (yes, it is logged in console as error even though it says 'warning'):

> Warning: Failed prop type: Prop `input` in `Input` conflicts with props: `children`. They cannot be defined together, choose one or the other.

### Version
78.2

### Testcase
See example here:
https://codesandbox.io/s/3vj08x7pl6

**Comment by layershifter** [comment]
You should use only props API or only children.

```jsx
<Input placeholder='search' />
// or
<Input>
  <input placeholder='search' />
  <span className='bar' />
</Input>
```

**Comment by gregor-mueller** [comment]
@layershifter thanks for the quick response!
But how can I overwrite the input for the search then?
This is what I try to achieve (sans error): https://codesandbox.io/s/3vj08x7pl6

This is what it looks like, if I only use props (no children): https://codesandbox.io/s/722v98m7z0

Even with Fragments the layout is broken, if I use props only.
