### ISSUE TITLE
Grid columns attribute not being used in Column width calculations

### ISSUE THREAD

**Issue by jacknevitt** [Semantic-Org/Semantic-UI-React#2546]
### Steps
```js
<Grid columns={12}>
  <Grid.Column mobile={12} computer={8}>
  ...
  </Grid.Column>
</Grid>
```

### Expected Result
Grid column should be 12/12 width on mobile and 8/12 width on computer

### Actual Result
Grid Column is 12/16 width on mobile and 8/16 width on computer

### Version
0.77.2

**Comment by layershifter** [comment]
Duplicate, #1886.
