### ISSUE TITLE
Automatic upward for drop downs is not happening

### ISSUE THREAD

**Issue by danambrose** [Semantic-Org/Semantic-UI-React#2547]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes

✔ BUGS → This form is required:

### Steps
Can be demonstrated in the examples of the following links:

Correct:
https://semantic-ui.com/modules/dropdown#selection

Incorrect:
https://react.semantic-ui.com/modules/dropdown#selection

**Comment by layershifter** [comment]
Duplicate,  #720.
