### ISSUE TITLE
Unknown prop `aligned` on <div> tag

### ISSUE THREAD

**Issue by ShenAdrada** [Semantic-Org/Semantic-UI-React#2551]
version 78.2 doesn't seem to recognize 'aligned' prop in the Tab module. do you have any version that don't have this error?

![error aligned](https://user-images.githubusercontent.com/26157352/36465135-c05ba052-170e-11e8-95a6-e358f584309b.png)

**Comment by brianespinosa** [comment]
@ShenAdrada per the docs, the `Tab` component does not directly have an `aligned` prop. If you are trying to pass that prop to a menu, please see the `menu` prop in the `Tab` docs: https://react.semantic-ui.com/modules/tab

**Comment by ShenAdrada** [comment]
@brianespinosa  I think the error comes from the Tab.js in the tab module. there's an aligned variable there. I think the error is referring to that

![tab module](https://user-images.githubusercontent.com/26157352/36654566-89222eb0-1af8-11e8-8da5-2b785065ad34.png)
![aligned prop](https://user-images.githubusercontent.com/26157352/36654570-8d46fa2a-1af8-11e8-9e85-6b478dfbe4d3.png)

**Comment by brianespinosa** [comment]
@ShenAdrada Please complete the *entire* bug report and provide a codesandbox example of the code you are using to create this error.

**Comment by pestevez** [comment]
We are seeing the same issue here: https://github.com/facebook/facebook-instant-articles-rules-editor/blob/master/src/js/components/Preview.react.js
