### ISSUE TITLE
Multi modal scroll not working

### ISSUE THREAD

**Issue by cesarve77** [Semantic-Org/Semantic-UI-React#2553]
### Steps
Open 2 multi modal.

Is first is bigger than window the scroll works fine until you open and close de second modal. Stop working. Because body lost class '. scrolling'
is the second modal is bigger tan window the window scroll only works for the first modal.

### Expected Result
Scroll work in the actual modal

### Actual Result
Scroll works just on first modal, and when second modal is closed scroll stop to work

### Version
0.78.2

### Testcase

https://codesandbox.io/s/5z1nyj4zjk

**Comment by brianespinosa** [comment]
Hello @cesarve77. The below code is all I am seeing in your `MultiModal` component in your codesandbox example. Please update your example to show your issue so we can see what you are experiencing. I am guessing you just may not have saved what you were working on. 😢 

```
import React from 'react';

export default ({ name }) => <h1>Hello {name}!</h1>;
```

**Comment by cesarve77** [comment]
Sorry.
I updated the example, But now the problem is worst, the second modal is showing above the first one.

**Comment by levithomason** [comment]
@layershifter was this not to be resolved by the MountNode component #2407?

**Comment by layershifter** [comment]
@levithomason  yes, it should. As I see, it's duplicate #1157.

**Comment by levithomason** [comment]
I've confirmed this is fixed in the latest master.  I'll be cutting a release here shortly.
