### ISSUE TITLE
Duplicate key in dropdown if option text === description

### ISSUE THREAD

**Issue by aurbano** [Semantic-Org/Semantic-UI-React#2556]
### Steps

When the `text` and the `description` are the same in a dropdown item, a duplicate key warning will be thrown.

```jsx
const options = [
  {
    text: 'sample',
    value: 1,
    description: 'sample',
  }
];
return (
  <Select
      options={ options }
  />
);
```
I think the issue is with [factories.js:L91](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/factories.js#L91) because the key for `createShorthand` is taken from the value.

I haven't looked a lot into the internals of this, but since `createShorthand` takes an optional `key` I think this can be fixed by specifying a key on [DropdownItem.js:141](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/DropdownItem.js#L141) as:

```
key: `desc-${description}`,
```

### Expected Result

Render the options without warnings.

### Actual Result

The console will output:
```
Warning: Encountered two children with the same key.
```

And the description will actually show up **multiple times** (1 per render)

### Version
0.78.2

### Testcase
https://codesandbox.io/s/o9mw0myqn5

**Comment by brianespinosa** [comment]
@aurbano correct. You want to specify the key either in your initial `Menu.Item` object or by creating the key the way you are showing in your example.

```
const options = [
  {
    key: 0,
    text: 'sample',
    value: 1,
    description: 'sample',
  }
];
```

Or use whatever your application will use to make sure the keys are unique in your array.
