### ISSUE TITLE
Accordion: onTitleClick typings are incorrect

### ISSUE THREAD

**Issue by radix** [Semantic-Org/Semantic-UI-React#2557]
### Steps

Use Accordion's onTitleClick property according to the typings, which look like this

```typescript
onTitleClick?: (event: React.MouseEvent<HTMLDivElement>, index: number | number[]) => void;
```

### Expected Result

get a `number` or `number[]` as the second argument

### Actual Result

got an `object`

### Version
0.78.2

### Testcase
https://codesandbox.io/s/vjzyjjqr13

**Comment by GCrispino** [comment]
Can you update your codesandbox? It does not have any Accordion component on it

**Comment by radix** [comment]
Sorry, I guess I forgot to save the sandbox! I'll update the description.

**Comment by GCrispino** [comment]
Cool. I'm not too familiar with TypeScript, but it's weird that on AccordionAccordion.js, onTitleClick is documented this way: 
`
/**
     * Called when a panel title is clicked.
     *
     * @param {SyntheticEvent} event - React's original SyntheticEvent.
     * @param {object} data - All item props.
     */
`
This seems to be what's happening, as `data`'s type in your code example is an object with the element's information.

**Comment by layershifter** [comment]
Thanks for report, will be fixed by #2568.

**Comment by jednano** [comment]
@layershifter it looks like there are a good number of TypeScript errors with this project. Any talk of converting the source code to TypeScript and generating the type definitions instead, so they're never out of sync?

**Comment by layershifter** [comment]
This project will be never converted to TS as we have really huge codebase there. If you have issues with typings, fill free to open PR with fixes.
