### ISSUE TITLE
Modal not centered and sit out of the screen

### ISSUE THREAD

**Issue by omar-bz** [Semantic-Org/Semantic-UI-React#2558]
Hi, I dont know if this an issue but the modal examples are not working, a modal has a top margin -104px and not centered :
the code:
```
import React from 'react';
import { Button, Header, Image, Modal } from 'semantic-ui-react';
import 'semantic-ui-css/semantic.min.css';

const ModalModalExample = () => (
  <Modal trigger={<Button>Show Modal</Button>}>
    <Modal.Header>Select a Photo</Modal.Header>
    <Modal.Content image>
      <Image
        wrapped
        size="medium"
        src="/assets/images/avatar/large/rachel.png"
      />
      <Modal.Description>
        <Header>Default Profile Image</Header>
        <p>
          We've found the following gravatar image associated with your e-mail
          address.
        </p>
        <p>Is it okay to use this photo?</p>
      </Modal.Description>
    </Modal.Content>
  </Modal>
);

export default ModalModalExample;
```

the image:
![image](https://user-images.githubusercontent.com/20848841/36531505-682df712-17be-11e8-8969-8738fa85a9e1.png)

**Comment by siimots** [comment]
Duplicate #2549

**Comment by anztrax** [comment]
you can solve it with styling the Modal component. 

**style** : 
```

const inlineStyle = {
  modal : {
    marginTop: '0px !important',
    marginLeft: 'auto',
    marginRight: 'auto'
  }
};
```

**react component** : 
```
<Modal dimmer={dimmer}
             open={open}
             onClose={this.handleOnClose}
             style={inlineStyle.modal}>
```

hope that can help temporarily  😅

**Comment by bholcombe** [comment]
The below css worked for me. Using flexbox positioning on the .dimmer and overriding built-in properties on the modal itself:

`.dimmed.dimmable > .ui.animating.dimmer, .dimmed.dimmable > .ui.visible.dimmer, .ui.active.dimmer {
  display: flex;
  align-items: center;
  justify-content: center;
}
.ui.modal,
.ui.active.modal {
  margin: 0 auto!important;
  top: auto !important;
  left: auto !important;
  transform-origin: center !important;
  transition: all ease .5s;
}`

**Comment by ivanpochta** [comment]
@anztrax , i LOVE U!
Thank you very much!

**Comment by loopmode** [comment]
@anztrax suggestion didn't center the modal vertically for me.

Apparently, it's just a `.transition.visible {display: block!important}` that's causing the troubles. I prefer this workaround for now:

```
.ui.page.modals.transition.visible {
    display: flex !important;
}
```

update: meh. Doesn't work when you have a max-height for the modal content.

**Comment by rztiwari** [comment]
I too had similar issues besides had to position the modal on the center vertically. I had made the changes above mentioned by @anztrax. Also added the override to modal as below:

.ui.modal {
    margin-top: 0 !important;
}
Which allows the content to be place vertically centered with dynamic content as well
