### ISSUE TITLE
Example #3 is not running

### ISSUE THREAD

**Issue by progrookie** [Semantic-Org/Semantic-UI-React#2559]
Hello everyone,

I using the webpack-Example "3".
When I use the command "npm start" then the following error occured: 
_"Error: babel-plugin-direct-import: contains unknown keys { modules }"_

I have the start.js or other script not touched!

Can everyone help me?

many thanks in advance

Sven

**Comment by KajSzy** [comment]
Just edit .babelrc file:

`plugins : [
 "direct-import",
    [
      "module:semantic-ui-react",
      {
        "name": "semantic-ui-react",
        "indexFile": "semantic-ui-react/dist/es/index.js"
      }
    ]
]`

But sadly still got some problems:

`Module build failed: Error: Must export a default export when using ES6 modules`

**Comment by progrookie** [comment]
Thank you for your quick answer!

Exists an executable (small) example with
- React
- Semantic UI React
- WebPack (or Rollup ;))

Thanks a lot!

**Comment by layershifter** [comment]
Guys, sorry something went wrong there :crying_cat_face:

I've shipped some updates, now boilerplate should be fully working. Please check again :+1:

**Comment by KajSzy** [comment]
There is still missing "react-hot-loader" as devDep

**Comment by layershifter** [comment]
@KajSzy thanks, check #2567.
