### ISSUE TITLE
Stardust's dependency on Semantic UI

### ISSUE THREAD

**Issue by jhchill666** [Semantic-Org/Semantic-UI-React#256]
Having picked up your Stardust project, it's not immediately clear what sort of dependency - if any - it has on Sementic UI.

I can import the components into my project, but they're not styled.  Having looked through your repos, I see some also include `semantic-ui-css`, and some use script tags to pull in the legacy semantic ui css files.

I understand that Stardust is in an easy stage of development, but what is the recommended approach for setting up styling?  I'm sure it might help others get started, if these instructions were added to the README.

Really excited to be able to use a great framework like Semantic UI with React sans JQuery.  Fantastic work!

**Comment by Maxhodges** [comment]
we are using Meteor so we installed it the official way
https://github.com/Semantic-Org/Semantic-UI-Meteor

then we can enable/disable individual component CSS via custom.semantic.json

```
{
  "definitions": {
    "accordion": false,
    "ad": false,
    "api": false,
    "breadcrumb": false,
    "button": true,
    "card": false,
    "checkbox": false,
    "colorize": false,
    "comment": false,
    "container": false,
    "dimmer": false,
    "divider": true,
    "dropdown": true,
```

Then you should be able to use the classes

```
import React from 'react';
import PageHeader from './PageHeader.jsx';
import { Menu, MenuItem, Dropdown, Item, Header } from 'stardust';
export default class MainLayout extends React.Component {
  render() {
    return (
      <div>
        <PageHeader />
        <Menu className="ui secondary vertical menu">
...
```

**Comment by levithomason** [comment]
Thanks for the note.  I've addressed dependencies and usage in #257.  I will update the README with more instructions as well.

**Comment by jhchill666** [comment]
Thanks @levithomason .  Anything I can do to help push the transition forward please let me know

**Comment by levithomason** [comment]
Thanks @jamiehill.  I'm working on some documentation to help direct efforts.   In the meantime, you can take a look at the Label component as an example of where we are headed API wise.

If you would like to tackle any of the open issues for missing components (marked `enhancement` `help wanted`) I'd be glad to walk you through building them out.

Otherwise, I'll let you know when the docs are updated.
