### ISSUE TITLE
Dropdown value/defaultValue boolean

### ISSUE THREAD

**Issue by DennisKo** [Semantic-Org/Semantic-UI-React#2564]
### Steps
Have a Dropdown with following possible options for value/defaultValue:

```
const options = [
  { key: 1, text: 'Yes', value: true },
  { key: 2, text: 'No', value: false }
]
```
### Expected Result
It should show no warning.
### Actual Result
It shows a warning `Warning: Failed prop type: Invalid prop value supplied to Dropdown.`
### Version
0.78.2

### Testcase
https://codesandbox.io/s/9qoymkzqp4

**Comment by GCrispino** [comment]
As you can see [here](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L347), the type of `value` can either be a string, a number, or an array of one of these types.
I wouldn't know why boolean can't be a possible value for this prop, but there's probably a reason.

**Comment by DennisKo** [comment]
I saw this file and I googled a bit but could not find a valid reason for no boolean... Maybe anyone from the core team knows better?

**Comment by GCrispino** [comment]
I see... let’s wait for the maintainers, they should know something about it

**Comment by levithomason** [comment]
This is due to an old artifact, a hidden select element.  See #2572 for the fix.

Note, this is just a warning and can be safely ignored in your app for now.  We'll merge and ship the fix soon to rid the nuisance.

**Comment by DennisKo** [comment]
Sorry to comment on a closed issue and thanks for the quick fix but

> Note, this is just a warning and can be safely ignored in your app for now. We'll merge and ship the fix soon to rid the nuisance.

A member of the react core team and creator of CRA/Redux wants to move the community to a different approach: https://github.com/facebook/react/issues/10633

> In React we intentionally rely on warnings treated as errors by the user. In fact at Facebook we show a modal dialog for each warning and we may enable the same behaviour in the open source version in the future.
