### ISSUE TITLE
Accomodate mobx arrays

### ISSUE THREAD

**Issue by ghepesdoru** [Semantic-Org/Semantic-UI-React#2566]
### Steps
Dropdown value change using a computed property (getter and setter) in a mobx based project.

### Expected Result
The value should change.

### Actual Result
Dropdown throws following error: Dropdown `value` must be an array when `multiple` is set. Received type: `[object Object]`.

Mobx is wrapping all data sets/types/primitives in objects to be able to track changes. As such an array becomes an object that is not compatible with Array.isArray(), but it does expose the same methods with the same functionality.

Please relax the isNextValueArray = Array.isArray(nextProps.value) portion into something along the lines of: nextProps.value && nextProps.value.map to account for this use cases.

### Version
0.78.1

**Comment by layershifter** [comment]
I'm almost sure that we don't need to do this, @levithomason what you think?

**Comment by Android3000** [comment]
@ghepesdoru - Doesn't mobx recommend using ".slice()" on the array in these situations?

Check out the docs here: https://mobx.js.org/refguide/array.html

> Bear in mind however that Array.isArray(observable([])) will yield false, so whenever you need to pass an observable array to an external library, it is a good idea to create a shallow copy before passing it to other libraries or built-in functions (which is good practice anyway) by using array.slice(). In other words, Array.isArray(observable([]).slice()) will yield true.

**Comment by ghepesdoru** [comment]
@Android3000 Thank you for the time to link me in the good direction. I totally missed that point

In the view of the new findings, as it is being a solvable issue from state library side, this task can be closed.
This might be added to a FAQ section, as I don't expect to be the only one to miss that part of mobx.

Sorry for wasting everyone's time, and thank you 👍
