### ISSUE TITLE
CSS with stardust

### ISSUE THREAD

**Issue by Maxhodges** [Semantic-Org/Semantic-UI-React#257]
Hi I'm a bit confused about how to get started. Should install Semantic separately and use its classes?

i.e. before stardust

```
<div className="header">Text Size</div>
<i className="">Small</i>
```

after stardust

```
<Header>Text Size</Header>
<Item>Small</Item>
```

or do I still need the classes, like this?

```
<Menu className="ui secondary vertical menu">
```

**Comment by levithomason** [comment]
**Dependencies**

Right now, you need to include Semantic UI CSS and JS.  However, we are mid transition removing jQuery and Semantic UI JS.  The only dependency we'll soon have is Semantic UI CSS.  These should be loaded before your application.

**Classes**

Most components still use Semantic UI classes directly, however, the `ui` class and the component name class itself are automatically added.  The Menu should look like this:

``` diff
-<Menu className="ui secondary vertical menu">
+<Menu className="secondary vertical">
```

We're moving all components to a more declarative API to better facilitate rewriting the jQuery functionality.  You can see this new API decision in issue #208, and in use in the Label and Dropdown components.  The above Menu example will look like this:

``` jsx
<Menu secondary vertical>
```
