### ISSUE TITLE
React Semantic : why slide left transition is not available in <Transition> ? Any alternative to use custom animation in this?

### ISSUE THREAD

**Issue by jatinatgit** [Semantic-Org/Semantic-UI-React#2573]

**Comment by levithomason** [comment]
There is definitely a `slide left` transition in SUI core.  It appears we've simply missed it in the enum.

See PR.

**Comment by jatinatgit** [comment]
Thanks @levithomason for quikcly fixing the issue. I have one more question, Can we define separate Animation for mount and unmount in <Transition.Group>, if yes, how?

**Comment by brianespinosa** [comment]
@jatinatgit that is unfortunately not something the [Transition](https://react.semantic-ui.com/modules/transition) component currently supports.

Please open new reports for different bugs.
