### ISSUE TITLE
Grey vs. Gray

### ISSUE THREAD

**Issue by mcclowes** [Semantic-Org/Semantic-UI-React#2574]
I noticed the default colours include Grey, rather than Gray.

I'm British so it's nice to see (what I would call) the correct spelling of this colour, but as the spelling of the CSS default would be _gray_, I'm confused why this spelling isn't used. Obviously a minor issue, but I think the colours should be consistent with CSS spellings for clarity's sake.

Thoughts?

**Comment by levithomason** [comment]
Agreed, however, this is limited by the CSS which is not managed here.

See https://github.com/Semantic-Org/Semantic-UI/issues/4779.

**Comment by mcclowes** [comment]
Thanks for clarifying @levithomason

**Comment by brody2consult** [comment]
<https://github.com/Semantic-Org/Semantic-UI/issues/4779>
