### ISSUE TITLE
Dropdown with wrapSelection={false} - "too much recursion" error

### ISSUE THREAD

**Issue by Unsfer** [Semantic-Org/Semantic-UI-React#2577]
Got an error "too much recursion" in Dropdown with wrapSelection={false} when the first/last item is disabled and I move in that direction

**Comment by levithomason** [comment]
Please complete the full issue report.  I've tested this on the latest version and it is working.

https://react.semantic-ui.com/modules/dropdown#dropdown-example-wrap-selection-false

```jsx
import React from 'react'
import { Dropdown } from 'semantic-ui-react'

const options = [
  { key: 1, text: 'One', value: 1 },
  { key: 2, text: 'Two', value: 2 },
  { key: 3, text: 'Three', value: 3 },
  { key: 4, text: 'Four', value: 4, disabled: true },
]

const DropdownExampleWrapSelectionFalse = () => (
  <Dropdown search selection wrapSelection={false} options={options} placeholder='Choose an option' />
)

export default DropdownExampleWrapSelectionFalse
```

**Comment by Unsfer** [comment]
Did you move to the last item in your example?

I got this error in FF dev console, other browsers can react differently.

I think that this part of code in [**moveSelectionBy**](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L998) method is incorrect:

```
// if 'wrapSelection' is set to false and selection is after last or before first, it just does not change
if (!wrapSelection && (nextIndex > lastIndex || nextIndex < 0)) {
  nextIndex = startIndex
} else if (nextIndex > lastIndex) nextIndex = 0
else if (nextIndex < 0) nextIndex = lastIndex

if (options[nextIndex].disabled) {
  this.moveSelectionBy(offset, nextIndex)
  return
}
```

After the first loop it's got stuck when `nextIndex = startIndex` which is disabled

**Comment by Unsfer** [comment]
Chrome says `Uncaught RangeError: Maximum call stack size exceeded`
