### ISSUE TITLE
Several documentation sections seem to be broken.

### ISSUE THREAD

**Issue by esslamben** [Semantic-Org/Semantic-UI-React#2578]
### Steps
The following pages are displaying a blank page with the same error in console. 

- Loader
- Input
- Checkbox
- Mount Node
- Container
- Divider

`Error: Minified React error #152; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=152&args[]=p for the full message or use the non-minified dev environment for full errors and additional helpful warnings.` Not sure if this is the best place to report documentation specific errors but I thought it's best if I would make you aware.

### Expected Result
https://react.semantic-ui.com/elements/loader loads and displays loader section

### Actual Result
Empty page with error printed in console

### Version
0.78.3

**Comment by sabbiu** [comment]
Same goes with this: https://react.semantic-ui.com/elements/input

**Comment by hubertguillemain** [comment]
same for Loader and Checkbox, MountNode and probably a couple of others

**Comment by jacknevitt** [comment]
Also Container and Divider

**Comment by esslamben** [comment]
I will update the title to reflect the fact that it's not just the loader page and make a list based on the above.

**Comment by hubertguillemain** [comment]
in the meantime, does anyone know where to access older version of the docs ?

**Comment by esslamben** [comment]
@hubertguillemain you can actually look through the code and figure out implementation. I had to do this for loader example. https://github.com/Semantic-Org/Semantic-UI-React/tree/master/docs/app/Examples

**Comment by esslamben** [comment]
Thanks @layershifter

**Comment by layershifter** [comment]
I've fixed the problem and deployed a new build.

Thanks for reports :+1: Please check, possible you'll need to clear cache.
