### ISSUE TITLE
Search component category/results not displayed correctly

### ISSUE THREAD

**Issue by DennisKo** [Semantic-Org/Semantic-UI-React#2579]
### Steps
Have a Search component with custom result and category renderer. 

### Expected Result
It shows the search results with a white background and the category with a gray background.

### Actual Result
Both grey and some white space on the right.
### Version
ui-react: 0.78.3
ui-react-css: 2.3.0

**Comment by esslamben** [comment]
#2578 Let's keep this all on one issue. Probably worth closing this mate.

**Comment by layershifter** [comment]
Please fill issue template and add an example on codesandbox.
