### ISSUE TITLE
how to do pull request on docs?

### ISSUE THREAD

**Issue by Maxhodges** [Semantic-Org/Semantic-UI-React#258]
I'd like to contribute, but don't see how to do a pull request for this site

https://technologyadvice.github.io/stardust/#Menu

**Comment by levithomason** [comment]
Hi there, you can follow the [development](https://github.com/TechnologyAdvice/stardust#development) instructions in the README to start the project.  Once the project is running, you can edit the `docs/Examples` section to create docs.

The `docs/Examples/` directory follows the structure of the doc site menu, the same structure as semantic-ui.com.  To create the docs for the Menu:

Create a `docs/Examples/collections/Menu` directory.  I'd suggest copying `docs/Examples/collections/Message` and updating the names/paths to get started.
The directory structure follows the right menu at www.semantic-ui.com/collections/menu.html:

![image](https://cloud.githubusercontent.com/assets/5067638/16202652/7596965a-36cb-11e6-8491-295cb96fc292.png)

Given the above, the directory structure would look like this:

```
docs/
  Examples/
    collections/
      Menu/       # <-- this structure follows the SUI doc site
        Types/
        Content/
        States/
        Variations/
```

Each example is a single file, to create the example for "Pointing" under "Types":

```
docs/
  Examples/
    collections/
      Menu/
        Types/
          MenuPointingExample.js
```

This file should demonstrate the complete real world usage of a Pointing Menu, including import statements.  The exported class will be rendered on the doc site under the appropriate heading.  The file contents will also be displayed below the Menu example.  It might look something like this:

``` js
import React, { Component } from 'react'
import { Menu } from 'stardust'

export default class MenuPointingExample extends Component {
  render() {
    return (
      <Menu className='pointing'>
        <Menu.Item>Home<Menu.Item>
        <Menu.Item>Messages<Menu.Item>
        <Menu.Item>Friends<Menu.Item>
      </Message>
    )
  }
}
```

When you copy the Message examples as a starting point be sure to update all the file names and paths correctly.  You'll notice a file in each directory that imports all each example, gives it a title, a description, and orders them on the page.

Let me know if you have any issues getting started.  Thanks much!
