### ISSUE TITLE
Popover ignores "on" property if mouseEnterDelay is set

### ISSUE THREAD

**Issue by nfantone** [Semantic-Org/Semantic-UI-React#2583]
✔ BUGS → This form is required:

### Steps
1. Define a `<Popup>` component with a `mouseEnterDelay` property.
2. Set `on="hover"` so it is triggered **only on hover**.
3. Click on trigger element before `mouseEnterDelay` time expires.

### Expected Result
The `Popup` opens _only_ on hover, after `mouseEnterDelay` milliseconds, ignoring click events. It doesn't open if I click the trigger component.

### Actual Result
The `Popup` is opened.

![](https://user-images.githubusercontent.com/476069/36635507-17390bf2-19ae-11e8-8fcb-8d745b3a7711.gif)

### Version
0.78.3

### Testcase
[![Edit Semantic UI React](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j7xp1krz6v?autoresize=1&hidenavigation=1)

**Comment by levithomason** [comment]
When according to your screenshot, you'd need to leave the mouse on the button for 10 seconds before the popup would open.  In the CodeSandbox provided, the value was 2s.

When hover and leave the mouse over the button for 2s, it works as expected:

![http://g.recordit.co/l15GuEuDbK.gif](http://g.recordit.co/l15GuEuDbK.gif)

**Comment by nfantone** [comment]
@levithomason You misread the issue. The popup is being triggered _on click_, in addition to the hover event. Your explanation was a paraphrase of mine.

> **Expected Result**
> The Popup opens only on hover, after mouseEnterDelay milliseconds, **ignoring click events**.

Please, consider re-opening?

**Comment by nfantone** [comment]
@levithomason Ping?

**Comment by ecnaidar** [comment]
Still present in current version
Should only appear after 5s of hovering but shown immediately if clicked

https://codesandbox.io/s/lgonz

**Comment by nfantone** [comment]
Nice that after over a year and a half this is still closed and labelled as "invalid".

Thanks @ecnaidar for your follow up.
