### ISSUE TITLE
Modals Appear in the corner of screen after new update

### ISSUE THREAD

**Issue by morinx** [Semantic-Org/Semantic-UI-React#2584]
All modals appear in the top left corner of screen instead of center after upgrading from `0.78.2` to `0.78.3`

### Version
0.78.3

**Comment by morinx** [comment]
Closing since it's the CSS update issue
https://github.com/Semantic-Org/Semantic-UI-CSS/issues/40

**Comment by brianespinosa** [comment]
Duplicate of #2550
