### ISSUE TITLE
Search: category/results not displayed correctly

### ISSUE THREAD

**Issue by DennisKo** [Semantic-Org/Semantic-UI-React#2586]
### Steps
Have a Search component with custom result and category renderer.
### Expected Result
It shows the search results with a white background and the category with a gray background.
### Actual Result
Both grey and some white space on the right.
### Version
ui-react: 0.78.3
ui-react-css: 2.3.0

### Testcase
https://codesandbox.io/s/m5m6vv992j

**Comment by aboglioli** [comment]
I'm having the same problem.

**Comment by DennisKo** [comment]
Its happening in the docs as well: https://react.semantic-ui.com/modules/search#types-category-custom
