### ISSUE TITLE
Accordion not working as before

### ISSUE THREAD

**Issue by Coder-Sharon** [Semantic-Org/Semantic-UI-React#2591]
I've been developing an app that has relied on v0.71.4. Recently, I upgraded to v0.78.2 to take advantage of some of the latest features. A large part of my application relies on the Accordion component, and after the update, the accordions no longer work as expected. When clicking on the accordion title, accordion title no longer becomes active, and the accordion content isn't displayed. After some testing, this functionality seems to have stopped in v0.74.0. After reviewing the docs, I noticed that if the "active" prop is added to both the Accordion.Title and Accordion.Content, the functionality does work. However, it would be nice for this functionality to work out of the box. I'm not sure if this is a bug or a change in the desired functionality.

### Steps
Accordion 1 is an example of a basic Accordion which works in v0.71.4. Accordion 2 demonstrates how the title/content can be made active with the "active" prop. However, I would like to not have to pass this prop to each active accordion. 

v0.71.4 - Notice how Accordion 1 works out of the box. Accordion 2 with the active prop works as expected.
https://codesandbox.io/s/x2mmm8l4zp

v0.78.2 - Notice how Accordion 1 **does not** work out of the box. Accordion 2 with the active prop works as expected.
https://codesandbox.io/s/xv9w16jmno

### Expected Result

When clicking on an accordion title, I expect it to become active, and for the accordion content to be displayed. This used to be the resulting function of an accordion in v0.71.4.

### Actual Result

When clicking on an accordion title, it does not become active nor is the content displayed.

### Version
Working in: v0.71.4
Stopped working in: v0.74.0
Not working in:  v0.78.2

### Testcase
v0.71.4 - Notice how Accordion 1 works out of the box. Accordion 2 with the active prop works as expected.
https://codesandbox.io/s/x2mmm8l4zp

v0.78.2 - Notice how Accordion 1 **does not** work out of the box. Accordion 2 with the active prop works as expected.
https://codesandbox.io/s/xv9w16jmno

**Comment by layershifter** [comment]
There were breaking changes, see #1375 for details.

**Comment by Coder-Sharon** [comment]
@layershifter Thank you, I wanted to check if this was intended. It wasn't too difficult to convert my code over to using the panels prop, and all is working as before.

**Comment by brianespinosa** [comment]
@Coder-Sharon until we reach a full 1.0 release, you'll want to read the release notes for any changes in between your current version and the one you are moving to. We are technically not following true semver on our version numbers yet. We are shifted back one decimal.

![image](https://user-images.githubusercontent.com/1161781/36918075-7c204fb8-1e0d-11e8-8aa1-17a78c29ae6a.png)

I had to do the same `Accordion` refactor in a number of places in our project as well. Some refactors are faster than others so the release notes are pretty good about if there are breaking changes in each version or not so you can plan out the work.

https://github.com/Semantic-Org/Semantic-UI-React/blob/master/CHANGELOG.md

**Comment by Coder-Sharon** [comment]
@brianespinosa Thanks, I'll be sure to keep up to date with the release notes.

**Comment by dmolin** [comment]
Thanks for pointing that out @brianespinosa .
I fell into the same (small) issue with the accordion when upgrading from 0.72.0 to 0.78.2 (big leap, I know, so it was expected)  :smile: 

One heads up though: I don't seem able to find any reference to the breaking change of the Accordion in the changelog.  it seems to be an undocumented breaking change.

I was able to find it only by looking at the history of changes on the Accordion source code on GitHub.

**Comment by brianespinosa** [comment]
@dmolin you're right. This update was in 0.74.0. You can see it in the [Full Changelog link for 0.74.0](https://github.com/Semantic-Org/Semantic-UI-React/compare/v0.73.1...v0.74.0) but for some reason it was not included in the CHANGELOG.md. The file is auto generated. I'll open up a separate bug for that to make sure we know why it was not automatically included. Thanks for pointing that out.
