### ISSUE TITLE
is Semantic-ui-react support rtl ?

### ISSUE THREAD

**Issue by MAmin233** [Semantic-Org/Semantic-UI-React#2592]
i was using semantic-ui later and i know that it supports rtl languages... ( grub generate rtl semantic )
but i don't know that it is working for semantic ui react too or not ?

i searched in documentations but i couldn't find something helpful

**Comment by brianespinosa** [comment]
@MAmin233 the RTL support is in the CSS. If you compile your SUI core styles for RTL support, SUIR will work with them.
