### ISSUE TITLE
When running webpack in production semantic-ui-react doesn't wotk

### ISSUE THREAD

**Issue by Igor-Vuk** [Semantic-Org/Semantic-UI-React#2598]
I have two webpack configs. In both I use semantic-ui-react. The difference is one is for development and the other one is for production. When running the production one, inside my srcipt I run webpack -p 
In this case semantic-ui-react does not work. Styles are here but if for example I click on dropdown nothing happens. What is the problem when running webpack -p  (optimize-minimize) and how to fix this? I am using webpack 3.

Thank you

**Comment by layershifter** [comment]
Please make a minimal reproducable repo which we can clone and run build. At now, this issue doesn't contain any valid information.

Also, take a look on our webpack 3 example in this repo.

**Comment by Igor-Vuk** [comment]
It's a part of a bigger project so it will take some time to make some reproducable repo. The main thing I noticed is this -p flag when using webpack. It does optimize minimize using uglifyjsplugin and then semantic-ui-react stops working. If I remove -p flag it works normally again.

**Comment by layershifter** [comment]
There are no reported problems with the production mode of webpack, you can verify this with create-react-app. Possible, you're using babel plugins that can cause problems.
