### ISSUE TITLE
Dropdown Search onOpen fires 2 times when clicking on Icon

### ISSUE THREAD

**Issue by DennisKo** [Semantic-Org/Semantic-UI-React#2600]
### Steps
Create a Dropdown with search component. Add onOpen handler. Click on the arrow on the right to open it. 

### Expected Result
It fires once.
### Actual Result
It fires twice.
### Version
0.78.2

### Testcase
https://codesandbox.io/s/6nx916460r
click on right arrow to open - look in the console

**Comment by willb335** [comment]
This seems to be related to the search prop.  I'll look a bit deeper into it.  It seems to me that it may have something to do with this bit of code in componentDidUpdate
```js
  const openable = !search || (search && minCharacters === 1)

        debug('mouse is not down, opening')
        if (openOnFocus && openable) this.open()
```

**Comment by willb335** [comment]
Working on this at #2744

**Comment by DennisKo** [comment]
fixed in https://github.com/Semantic-Org/Semantic-UI-React/pull/2744
