### ISSUE TITLE
Auto generated CHANGELOG.md may be missing some PRs that are actually included in a tagged release

### ISSUE THREAD

**Issue by brianespinosa** [Semantic-Org/Semantic-UI-React#2602]
### Steps
1. Take a look at the [CHANGELOG.md for the 0.74.0 release](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/CHANGELOG.md#v0740-2017-09-24).
2. Look at the [Full Changelog link](https://github.com/Semantic-Org/Semantic-UI-React/compare/v0.73.1...v0.74.0) to see all PRs that were actually included in the release.

### Expected Result
We should have the `breaking(Accordion)` change from #1375 included in the CHANGELOG.md

### Actual Result
The breaking change from #1375 is not included in the CHANGELOG.md

### Version
0.74.0

I assume this may have actually been fixed already, in which case we can close this out. Otherwise... we probably want to keep an eye on this when shipping a new release, especially since this was a breaking change and should definitely be in the CHANGELOG.md. This was pointed out in #2591.

**Comment by levithomason** [comment]
I've identified the issue, PR coming.
