### ISSUE TITLE
build: upgrade to Babel 7

### ISSUE THREAD

**Issue by thetric** [Semantic-Org/Semantic-UI-React#2603]
Upgrade to babel 7, see https://github.com/Semantic-Org/Semantic-UI-React/pull/2596#pullrequestreview-100998473

**Comment by thetric** [comment]
Should be done after #2594 is merged (and #2597 too?)

**Comment by layershifter** [comment]
@thetric Yes, let's merge #2594 and then migrate to babel 7.

**Comment by layershifter** [comment]
#2594 was merged, we can start the upgrade :+1:
