### ISSUE TITLE
build: upgrade to webpack 4

### ISSUE THREAD

**Issue by thetric** [Semantic-Org/Semantic-UI-React#2605]
See https://github.com/Semantic-Org/Semantic-UI-React/pull/2596#pullrequestreview-100998473. As mentioned in the review `karma-webpack-with-fast-source-map` will cause problems because it only supports webpack 3

**Comment by brianespinosa** [comment]
I am going to go ahead and close this for housekeeping. There are still far too many dependencies out there that are still not ready to support Webpack 4. We can address this again at a later date when the overall webpack community has reached stable adoption. `create-react-app` is still only using Webpack 3 as well.
