### ISSUE TITLE
RFC: migrate docs to react-styleguidist

### ISSUE THREAD

**Issue by thetric** [Semantic-Org/Semantic-UI-React#2606]
Quote from [react-styleguidist](https://github.com/styleguidist/react-styleguidist):

> React Styleguidist is a component development environment with hot reloaded dev server and a living style guide that you can share with your team. It lists component `propTypes` and shows live, editable usage examples based on Markdown files.

React Styleguidist has some advantages over the current situation:
* no js/html boilerplate for the examples, only markdown + some code snippets
* the examples are full interactive, the code modifiable
* components don't need the `_meta` static field anymore, propType information is automatically extracted and displayed

A simple example can be found here: https://react-styleguidist.js.org/examples/basic/

React Styleguidist can be customized to use the semantic ui css, too.

**Comment by layershifter** [comment]
1. Current docs allow make them really responsive and add really complex examples, see `Icon`.
2. All examples are modifiable now, too.
3. `_meta` allows to group components by parent.
