### ISSUE TITLE
Responsive: wrong type of `width` in ResponsiveOnUpdateData

### ISSUE THREAD

**Issue by MJLHThomassen-Eurocom** [Semantic-Org/Semantic-UI-React#2608]
In Responsive.d.ts, the type of the width property in the ResponsiveOnUpdateData interface is "string" but this should be "number".

**Comment by layershifter** [comment]
Thanks for report :+1:

**Comment by MJLHThomassen-Eurocom** [comment]
Thanks for the quick fix!
