### ISSUE TITLE
Error when using CSS modules with Webpack

### ISSUE THREAD

**Issue by eyalch** [Semantic-Org/Semantic-UI-React#2609]
### Steps
1. `create-react-app .`
2. `yarn add semantic-ui-react semantic-ui-css`
3. Add `import 'semantic-ui-css/semantic.min.css'` to `index.js`
4. Add a , e.g `<Button />`, to check whether we can use components from `semantic-ui-react`

All good so far.

5. `yarn eject`
6. Add
```
modules: true,
localIdentName: '[name]__[local]__[hash:base64:5]'
```
to the options of the `css-loader` in the `config/webpack.config.dev.js`
### Expected Result
No errors.
### Actual Result
After `yarn start`:
> Failed to compile.
./node_modules/semantic-ui-css/semantic.min.css
Module not found: Can't resolve 'themes/default/assets/fonts/icons.eot' in '[MY_PROJECT_DIR]/node_modules/semantic-ui-css'

### Version
```
"semantic-ui-css": "^2.3.0",
"semantic-ui-react": "^0.78.3",
```

**Comment by layershifter** [comment]
StackOverflow is better place for usage questions. See [our example](https://github.com/Semantic-Org/Semantic-UI-React/tree/master/examples/webpack3) for working config.
