### ISSUE TITLE
Publishing latest versions to NPM

### ISSUE THREAD

**Issue by jaredhughes** [Semantic-Org/Semantic-UI-React#261]
Is there any opposition to keeping the latest version bumps published on NPM? I feel like anyone using this package should be aware of the possibility of breaking changes, but there are also new features available in unreleased versions (namely, inline dropdowns) that would be very helpful to have available via NPM.

I figure better to publish all tags and be able to revert in the event of a breaking change rather than not having the latest versions available at all (given the only alternative is to fork and configure installs from the repo).

By the way, thanks for all of the effort put into this so far – we at @contactually look forward to contributing as we're able.

**Comment by levithomason** [comment]
Agreed.  Though, apparently NPM will suddenly not allow me nor any other package owner to publish stardust.  This is strange and frustrating.

I'm getting in touch with their support to get it fixed.  As soon as I can publish the `0.14` I just pushed I will.

**Comment by jaredhughes** [comment]
Great, thanks!

**Comment by levithomason** [comment]
@jaredhughes 0.14 is now published.  Thanks.
