### ISSUE TITLE
Search: Warnings when passing custom props to resultRenderer

### ISSUE THREAD

**Issue by Ferezoz** [Semantic-Org/Semantic-UI-React#2610]
### Steps

1. Suppose i get from my server an array like this:
`items: Array<{ id: string, fooBar: string }>`

2. Then I use `results` to have the filtered `items` from my search, so they have the same types.

3. Then I pass `results` to Search like this:
```
<Search
    onResultSelect={this.handleResultSelect}
    onSearchChange={this.handleSearchChange}
    results={results}
    resultRenderer={this.resultRenderer}
/>
```

4. And I get two warnings saying:
    1. `Warning: Each child in an array or iterator should have a unique "key" prop.`
    2. `Warning: React does not recognize the "fooBar" prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase "foobar" instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

### Warning 1

To fix this, Instead of looping through the `items` array an renaming `id` to `key` or adding `key`, It would be great to pass the `key` to `resultRenderer` like this:
```
resultRenderer = (props) =>
    <div key={props.id}>
      ...
    </div>;
```

### Warning 2

The only way to fix this is to loop through the `items` array and make all `keys` lowercase. But to make this easier, instead of passing `props` as attributes, we could get an `index` from `resultRenderer` and then get the `item` of the specific iteration like this:
```
resultRenderer = (index) => {
    const { items } = this.state;

    return (
      <div key={items[index].id}>
        <Label content={items[index].fooBar} />
      </div>
    );
};
```

**Comment by layershifter** [comment]
Duplicate, #1141.
