### ISSUE TITLE
Button animated after loading dont return to visible label

### ISSUE THREAD

**Issue by lucasmathioni** [Semantic-Org/Semantic-UI-React#2611]
I'm using a button with animation and loading, when after setting the load to false, the label does not return to visible, keeping the label hidden active.
And for the button to come back with the active label again, I need to click somewhere so it returns to normal.

[Step 1](https://image.ibb.co/hEGhCn/label_visible.jpg)
[Step 2](https://image.ibb.co/b2aaXn/label_hidden.jpg)
[Step 3](https://image.ibb.co/eY0ndS/loading.jpg)
[Step 4](https://image.ibb.co/cCnYJS/after_loading.jpg)

```

import React, { Component } from 'react'
import { Button, Icon } from 'semantic-ui-react'

export default class TesteClass extends Component {
  constructor(props) {
    super(props)
    this.state = {
      loading: false
    }
  }
  
  handleOnClick = () => {
    this.setState({ loading: true })
    setTimeout(() => {
      this.setState({ loading: false })
    }, 2000)
  }
  
  render() {
    return (
      <Button loading={this.state.loading} animated primary fluid onClick={this.handleOnClick}>
      	<Button.Content visible>
          Avançar
        </Button.Content>
        <Button.Content hidden>
          <Icon name='right arrow' />
        </Button.Content>
      </Button>
    )
  }
}
```

I'm using:
Semantic UI React v0.78.3
React v16.2.0

**Comment by brianespinosa** [comment]
Please complete the full bug report, including a codesandbox example. There is literally no way to see how your component is getting into a loading state with what you have pasted here.

**Comment by lucasmathioni** [comment]
Sorry about that. I edited the description, containing a sample code. Can you reopen?

**Comment by brianespinosa** [comment]
Please create a working example using this codesandbox, which is included in the form for all new bug reports: https://codesandbox.io/s/2l3n74j9y
