### ISSUE TITLE
Modal closeOnDimmerClick behaviour not working as expected on Safari mobile

### ISSUE THREAD

**Issue by clodal** [Semantic-Org/Semantic-UI-React#2616]
### Steps
1. Open Safari on an iOS device with the version included below.
2. Go to: https://react.semantic-ui.com/maximize/modal-example-modal
3. Modal appears but cannot be closed when you tap on the dimmer.

### Expected Result
- Tapping on the dimmer should close the modal

### Actual Result
- Tapping on the dimmer does not close the modal

### Version
Semantic-ui-react: 0.78.3
Safari Mobile on iOS: 11.2.6

### Testcase
Just follow the steps above, no test case required. See screenshot attached:
![img_0270](https://user-images.githubusercontent.com/8684825/37134162-1c885a90-22d2-11e8-8fe5-a8ad32a5a6d1.PNG)

**Comment by layershifter** [comment]
Duplicate, see https://github.com/Semantic-Org/Semantic-UI-React/pull/1833#issuecomment-313713611.
