### ISSUE TITLE
Wrong Icon Name?

### ISSUE THREAD

**Issue by minotaurrr** [Semantic-Org/Semantic-UI-React#2617]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes

✔ BUGS → This form is required:

### Steps
I am trying to use the 'calendar' icon as displayed in the docs like this:
```
<Icon name='calendar' />
```
### Expected Result
![cal](https://user-images.githubusercontent.com/28755951/37136567-3a026d26-22f6-11e8-99b0-151f59b705d9.PNG)

### Actual Result
![capture](https://user-images.githubusercontent.com/28755951/37136568-406ddac4-22f6-11e8-9145-5f2882227be6.PNG)

### Version
2.3.0

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

Hey guys,

As explained above I'm trying to use the calendar icon (the one in the docs) but it keeps showing a different calendar icon and I'm not sure why.. any ideas?

**Comment by layershifter** [comment]
SUI 2.3 uses FontAwesome 5, see #2550.

**Comment by reddishtg** [comment]
Apologies if this is not the right place, but the react.semantic-ui.com website needs to be updated with this change.  It looks like the main semantic-ui site shows the current FontAwesome version, but not the react version.

**Comment by brianespinosa** [comment]
@reddishtg there is currently a note at the top of the README.md with this information. https://github.com/Semantic-Org/Semantic-UI-React/blob/master/README.md

There is a PR in progress which updates everything, including the docs site. #2657

**Comment by reddishtg** [comment]
Thanks.  You would think that would make it obvious to see.  I guess that's what I get for finding the website before the github repo.
