### ISSUE TITLE
Mount node on Portal components crashes when specified node inside the current component

### ISSUE THREAD

**Issue by haikyuu** [Semantic-Org/Semantic-UI-React#2619]
In the sandbox https://codesandbox.io/s/ly54m63vz7, there is a reproduction case and a hack to fix if encountered. 
The clean fix would be to use a function `getMountNode` ~~instead of~~ as well as   `mountNode` for these use cases. Note that this API is used (getPopupContainer) in https://github.com/react-component/trigger and in [Ant Design components](https://ant.design/components/tooltip/#API)
### Steps
Set `mountNode` of a Portal component to its parent
### Expected Result
the portal should mount on the specified `mountNode`
### Actual Result
Crashes `Cannot read property 'appendChild' of null`
### Version
0.75.1

**Comment by haikyuu** [comment]
Also, here is the base code for a PR
```diff
diff --git a/src/addons/Portal/Portal.js b/src/addons/Portal/Portal.js
index 07c4a6aa..38725ee3 100644
--- a/src/addons/Portal/Portal.js
+++ b/src/addons/Portal/Portal.js
@@ -70,6 +70,13 @@ class Portal extends Component {
     /** The node where the portal should mount. */
     mountNode: PropTypes.any,
 
+    /**
+     * Returns the node where the portal should mount on.
+     *
+     * @returns {} mount node.
+     */
+    getMountNode: PropTypes.func,
+
     /** Milliseconds to wait before opening on mouse over */
     mouseEnterDelay: PropTypes.number,
 
@@ -385,12 +392,22 @@ class Portal extends Component {
 
     const {
       eventPool,
-      mountNode = isBrowser() ? document.body : null,
       prepend,
+      getMountNode
     } = this.props
 
+    let mountNode
+    if (getMountNode) {
+      mountNode = isBrowser() ? getMountNode() : null
+    }else{
+      mountNode = this.props.mountNode || isBrowser() ? document.body : null
+    }
     this.rootNode = document.createElement('div')
 
+    if (!mountNode) {
+      // display an error !
+      return
+    }
     if (prepend) {
       mountNode.insertBefore(this.rootNode, mountNode.firstElementChild)
     } else {
```

**Comment by layershifter** [comment]
I'm almost sure that we don't need to fix this as it's an edge case. Possible @levithomason has another opinion.

**Comment by haikyuu** [comment]
I first wanted to make a PR, but now i think it's not worth it.
Thank you

**Comment by NullVoxPopuli** [comment]
changing the mount node is essential if the modal uses a context consumer.

currently, modals are all portaled outside of the context provider ancestry... :(

**Comment by haikyuu** [comment]
@NullVoxPopuli  we switched to using ant.design
It's orders of magnitudes better

**Comment by NullVoxPopuli** [comment]
it turns out I just needed to upgrade semantic-ui-react to 0.84
