### ISSUE TITLE
Update Divider to v1 API

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#262]
From the linked issue where this convo started:

> The Divider element is a pretty minimal component. That might be a good start. The docs are already in place for the Divider as well, so you'll have something to reference as you develop the API. You'll be looking to update src/elements/Divider/Divider.js and update docs at docs/app/Examples/elements/Divider.

The new API should look like this.  These examples follow the docs at http://semantic-ui.com/elements/divider.
## Types

**Divider**

``` js
<Divider />
```

``` html
<div class="ui divider"></div>
```

**Vertical Divider**

``` js
<Divider vertical />
```

``` html
<div class="ui vertical divider"></div>
```

**Horizontal Divider**

``` js
<Divider horizontal />
```

``` html
<div class="ui horizontal divider"></div>
```
## Variations

**Inverted**

``` js
<Divider inverted />
```

``` html
<div class="ui inverted divider"></div>
```

**Fitted**

``` js
<Divider fitted />
```

``` html
<div class="ui fitted divider"></div>
```

**Hidden**

``` js
<Divider hidden />
```

``` html
<div class="ui hidden divider"></div>
```

**Section**

``` js
<Divider section />
```

``` html
<div class="ui section divider"></div>
```

**Clearing**

``` js
<Divider clearing />
```

``` html
<div class="ui clearing divider"></div>
```

**Comment by levithomason** [comment]
Fixed in #268, big thanks!

**Comment by jhchill666** [comment]
I you want to spec up any of the other 'need helps' cc me and I can pick 
up in next couple of days

Levi Thomason wrote:

**Comment by levithomason** [comment]
@jamiehill I've created a list of components over at #269.  We'll use that to keep track of which components need update.  Thanks much.
