### ISSUE TITLE
Layouts: HomepageLayout in mobile menu automatically toggled when click somewhere

### ISSUE THREAD

**Issue by bexoss** [Semantic-Org/Semantic-UI-React#2625]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes

✔ BUGS → This form is required:

### Steps

Chrome Developer Menu => Mobile View => Access below url 
https://react.semantic-ui.com/layouts/homepage

### Expected Result

Menu has to toggled when burger clicked. 

### Actual Result

But, when you click anywhere in page, menu automatically toggled. 

### Version

Latest

**Comment by bexoss** [comment]
@layershifter I think the problem still left on example layout. https://react.semantic-ui.com/layouts/homepage

**Comment by brianespinosa** [comment]
@bexoss this update is not live yet. It will be deployed with the next release. You can keep an eye on the CHANGELOG for it.
