### ISSUE TITLE
Form.Group with Form.Radio with the same values

### ISSUE THREAD

**Issue by mowais-ac** [Semantic-Org/Semantic-UI-React#2626]
Hi, 

I really love the semantic UI React library

Can you please suggest me how can i use multiple Form.Group with Form.radio with the same value Yes and No

Thanks in advance.

**Comment by mowais-ac** [comment]
I just noticed a bug here, please see the attached GIF for reference, 

Yes is not selecting again
here is my code
<Form.Group inline>
    <label>Do you smoke?</label>
    <Form.Radio inline name={'smoke'} label={'Yes'} />
    <Form.Radio inline name={'smoke'} label={'No'} />
</Form.Group>


![radio-bug-semantic-ui-react](https://user-images.githubusercontent.com/33151104/37228394-ed48f9b4-23f9-11e8-8fe5-161cb1ebc94f.gif)

**Comment by layershifter** [comment]
Please use StackOverflow for questions. If there is a bug, please fully fill our issue template.

In provided code I see wrong usage of uncontrolled elements, see our examples in docs.
