### ISSUE TITLE
fix(Pagination): disable active pagination.item

### ISSUE THREAD

**Issue by brian-kilpatrick** [Semantic-Org/Semantic-UI-React#2627]
**Steps to Reproduce**
1. Do something
2. Do something else.

**Expected**
Pagination should disable the current active pagination.item so that additional clicks won't trigger additional method calls for the same content. 

**Result**
A check can be made in the handler but it would be good to have a visual representation, to denote there's no use in clicking on a page you are already on.

**Testcase**
undefined

**Comment by layershifter** [comment]
It's not correct to disable an active item for click, [see also Bootstrap](https://getbootstrap.com/docs/4.0/components/pagination/). However, `onPageChange` should not occured for already active item.

PR is coming.
