### ISSUE TITLE
fix(Dropdown): Search In-Menu (example with Filter Posts)

### ISSUE THREAD

**Issue by g-wozniak** [Semantic-Org/Semantic-UI-React#2629]
**Steps to Reproduce**
1. Click on "Filter Posts"
2. Attempt to type-in a search field.

**Expected**
It is possible to type a text which will be then filtered.

**Result**
The dropdown closes (slides out) unexpectedly.

Reproduced in Chrome 64.0.3282.186, Firefox 58.0.2

**Comment by brianespinosa** [comment]
@gregiolo please complete the entire bug report, which includes a minimum codesandbox example.
