### ISSUE TITLE
SharePoint:FormDigest freezes Grid.Column onClick

### ISSUE THREAD

**Issue by gillesgerlinger** [Semantic-Org/Semantic-UI-React#2631]
I am developing a Sharepoint 2013 web application. The application UI works fine without sharepoint but adding Sharepoint:FormDigest has a weird side effect that prevents a semantic-ui-react form to be opened twice... Any hint would be appreciated.

### Steps

Adding the following lines in index.html leads to the error described above.
```
    <form runat="server">
      <SharePoint:FormDigest ID="FormDigest1" runat="server"></SharePoint:FormDigest>
    </form>
```
The lines below opens a modal form. This opens on first click but when the form is closed (submitted or not) a second click does not trigger (no 'click' trace in the console).

```
                            <Grid.Column>
                                <div className="presentation" onClick={()=>{
                                    console.log('click');
                                    this.setState( {openModal: true, typeModal: 'share'} );
                                }}>
                                    <FaShareAlt size={45} className="icon" color='#474747'/>
                                    <h2>Share knowledge</h2>
                                </div>
                            </Grid.Column>
```

If I remove the SharePoint:FormDigest tag in the index.html file, everything works fine. I need the tag to be in the html file in order to update the Sharepoint lists the application manages...

I noticed also that the bug appears as soon as I select one of the 2 Form.Select elements below. If I do not use the Form.Select, then there is no bug. However, those fields are mandatory...

```
                            <Form.Group widths='equal'>
                                <Form.Select error={this.state.formError.includes('duration') ? (true) : (false)} value={duration} name="duration" onChange={this.handleFormChange} id='form-select-control-duration' required label='Duration' options={this.optionsDuration} placeholder='The approximative duration of the session' />
                                <Form.Select error={this.state.formError.includes('category') ? (true) : (false)} value={category} name="category" onChange={this.handleFormChange} id='form-select-control-category' required label='Category' options={this.optionsCategory} placeholder='Help people to find your post' />
                            </Form.Group>
```
The method handleFormChange is the same as for other Form.Input fields (which do not cause this bug).

### Expected Result

A second click on the Grid.Column element should trigger action.

### Actual Result

Nothing happens on subsequent clicks on the Grid.Column element

### Version
    "gd-sprest": "^3.5.5",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-icons": "^2.2.7",
    "react-promise": "^2.0.1",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.0.17",
    "react-scrollable-anchor": "^0.6.1",
    "semantic-ui-css": "^2.3.0",
    "semantic-ui-react": "^0.78.3"

**Comment by layershifter** [comment]
I don't see a problem there with SUIR, please make a reproducable example on [codesandbox](https://codesandbox.io/). Sorry, but we don't have time to debug your or 3d-party code.

**Comment by gillesgerlinger** [comment]
Understood, but I need Sharepoint to reproduce the bug...

**Comment by layershifter** [comment]
Possible, you can get an answer on StackOverflow as your report is very detailed :+1: But, I don't know anything about Sharepoint and can't give a correct answer.

**Comment by gillesgerlinger** [comment]
OK, thanks. I'll try StackOverflow then. It is a tricky bug since all is fine without Sharepoint...
