### ISSUE TITLE
Modal goes to the far corner of the top of the page after updating semantic ui

### ISSUE THREAD

**Issue by Dhul-Husni** [Semantic-Org/Semantic-UI-React#2638]
✔ BUGS →
### Steps
Create a semantic ui react modal
npm install "semantic-ui-css": "2.3.0", and "semantic-ui-react": "0.78.3",
### Expected Result
<img width="1440" alt="screen shot 2018-03-13 at 2 44 11 pm" src="https://user-images.githubusercontent.com/32780926/37340351-e58fcdd8-26ce-11e8-8f84-0aa78f4b9ce7.png">

### Actual Result
<img width="1440" alt="screen shot 2018-03-13 at 2 31 40 pm" src="https://user-images.githubusercontent.com/32780926/37340361-f01291dc-26ce-11e8-892a-15fc2d3cb87a.png">

### Version
0.78.3
I have now downgraded to "semantic-ui-css": "2.2.14", and "semantic-ui-react": "0.78.2", 
which fixes the issue for me
### Testcase
[Fork this repo and reproduce the bug by changing the version]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Duplicate #2550.
