### ISSUE TITLE
Form doesn't post Form.Input parameters on POST

### ISSUE THREAD

**Issue by aud** [Semantic-Org/Semantic-UI-React#2640]
### Steps

- Enter text in both fields
- Click Submit
- See only the username `Input` is included in the request.

```js
<Form action="/endpoint" method="POST">
  <Form.Group widths='equal'>
    <Form.Input fluid label='Name' placeholder='Name' />
    <Input type="text" name="username" placeholder='Username' />
  </Form.Group>

  <Form.Button>Submit</Form.Button>
</Form>
```

### Expected Result

I would expect the `Form.Input` to be included in the request.

### Actual Result

Only `Input` is included. Is `Form.Input` intended to be strictly a control prop?

### Version
0.75.1

### Testcase
https://codesandbox.io/s/3485743nzp

**Comment by layershifter** [comment]
Your inputs doesn't contain `name`, you should add them if you want form traditionally.

https://www.w3schools.com/tags/att_form_method.asp
