### ISSUE TITLE
fix(Embed): Placeholder should come after video ends

### ISSUE THREAD

**Issue by dgr8akki** [Semantic-Org/Semantic-UI-React#2643]
**Steps to Reproduce**
1. Create an ** Embed ** type component
2. In URL, just give any local video link

**Expected**
After the video ends, it should show placeholder again, ie it should come in the same state as it was in before video starts

**Comment by layershifter** [comment]
Vanilla SUI doesn't support this feature, so it's not a priority for the core team. However, we will accept PR that impliments this.
