### ISSUE TITLE
Unable to pass a component to 'as' prop of Menu.Item via a ternary operator

### ISSUE THREAD

**Issue by prashand** [Semantic-Org/Semantic-UI-React#2646]
### Steps

This is a really weird situation. I can pass a `Link` component from the react-router to the `as` prop of the Menu.Item directly, (line 27 of sandbox) but cannot do the same via a ternary operator. (line 30 of sandbox)

### Expected Result

Uncomment line 27, comment line 30 of the sandbox

### Actual Result

Comment line 27, Uncomment line 30 of the sandbox. Does not compile:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### Version

0.75.1

### Testcase

https://codesandbox.io/s/3140z61wz5

**Comment by layershifter** [comment]
```jsx
// Wrong as you pasted
as = {this.state.GITHUB_MENUITEM_ENABLED ? {Link} : null}
// i.e. it's a real object
as = {this.state.GITHUB_MENUITEM_ENABLED ? {Link: Link} : null}

// Correct
as = {this.state.GITHUB_MENUITEM_ENABLED ? Link : null}
```
