### ISSUE TITLE
Is it any easy way to create a form at center of the page (horizontally and vertically) ? Tried workaround and that worked. But not concrete solution.

### ISSUE THREAD

**Issue by riteshnus** [Semantic-Org/Semantic-UI-React#2648]
### Steps
<Grid verticalAlign="middle" centered style={{height: '100%'}}>
                    <Grid.Column style={{backgroundColor:'red'}}>
                        <h1> Center at page </h1>
                    </Grid.Column>
</Grid>

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by fracmak** [comment]
This is a question best served by stackoverflow

**Comment by riteshnus** [comment]
Could you refer any stackoverflow thread for this purpose?

**Comment by fracmak** [comment]
https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes

**Comment by brianespinosa** [comment]
@riteshnus I answered your question over on SO. Additionally, for anyone else who might land here, all of the same layout examples that appear on SUI are also replicated in our docs here for SUIR under [Layouts](https://react.semantic-ui.com/layouts).
