### ISSUE TITLE
fix(Menu): Invalid Fixed Menu Sample

### ISSUE THREAD

**Issue by nathan21x** [Semantic-Org/Semantic-UI-React#2649]
**Steps to Reproduce**
1. Searched for Fixed menu sample

**Expected**
The Menu should have a sample fixed menu react code

**Result**
The sample was "message" react code

**Comment by brianespinosa** [comment]
@nathan21x You may have missed the fixed menu example in the SUIR Layout area here: https://react.semantic-ui.com/layouts/fixed-menu
