### ISSUE TITLE
Button element with an Icon sends event object of Icon leading "Undefined" event.target.name

### ISSUE THREAD

**Issue by assumer** [Semantic-Org/Semantic-UI-React#2651]
### Steps
1. Create a page with Next Js & import semantic ui react elements like below.
```
import React, { Component } from "react";
import { Button, Icon } from "semantic-ui-react";

export default class MyMenu extends Component {
  constructor(props) {
    super(props);
    this.state = {};

    this.toggle = this.toggle.bind(this);
  }

  toggle(e) {
    const name = e.target.name;
    this.setState(prevState => {
      return { [name]: !prevState[name] };
    });

    console.log(this.state.name);
  }

  render() {
    const { activeItem } = this.state;

    return (
      <Button.Group>
        <Button
          name="home"
          onClick={e => this.toggle(e)}
          icon={<Icon name="heart" color={this.state.home ? "pink" : "grey"} />}
          content="Fav It"
        />
        <Button
          name="follow"
          onClick={e => this.toggle(e)}
          icon={
            <Icon name="feed" color={this.state.follow ? "yellow" : "grey"} />
          }
          content="Follow"
        />
      </Button.Group>
    );
  }
}

```

### Expected Result
The onClick prop in Button element with **toggle** callback should be called with the even object from the button itself only.
The event object (e) should contain e.target.name = 'home' for the first button.

### Actual Result
If the click is made over the provided icon in the button element then the event is being provided with the onClick callback coming from the Icon not the button.

That's why the event object (e) is containing e.target.name = undefined as no name is provided to the icon.

### Version
SemanticUiReact : 0.78.3
NextJs : 5.0.1
React : 16.2.0
NodeJs : 8.9.3
NPM : 5.5.1

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Use second argument of `onClick`, `data` will contain all props so you will can use `name` there.
