### ISSUE TITLE
Icons won't show in Vulcan@1.8.11

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#2662]
### Steps
`client/main.js`:
```
import 'semantic-ui-css/semantic.min.css';
```

`components/YourCreatedComponent.jsx`:
```
import React, { Component } from 'react';
import { Icon } from 'semantic-ui-react';
import { registerComponent, Components, withCurrentUser } from 'meteor/vulcan:core';

class Home extends Component {
    render() {
        return (
             ...
            <Icon name='eye'></Icon>
             ...
        )
    }
```

### Expected Result
Icon will show properly

### Actual Result
Icon is replaced by an empty square

### Version
```
  Vulcan: '1.8.11',
  npm: '5.7.1',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.1',
  openssl: '1.0.2m',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.47',
  zlib: '1.2.11' 
```

**Comment by brianespinosa** [comment]
@gabimoncha please create a codesandbox with a minimal reproducible case. You also do not mention what version of SUIR you are using in your report. 

If you are seeing any 404 errors in your console saying that the font is missing that is being called, that means the build process you are using is not including the font files.
