### ISSUE TITLE
Modal window mispositioned render

### ISSUE THREAD

**Issue by alpatovdanila** [Semantic-Org/Semantic-UI-React#2668]
### Steps
I have installed last versions of semantic-ui-react and semantic-ui-css 
and tried to display modal window as shown in official documentation

### Expected Result
Modal window positioned as in official demos

### Actual Result
Modal window rendering outside the viewport

### Version
semantic-ui-css: 2.3.1,
semantic-ui-react: 0.79.0

### Testcase
https://codesandbox.io/s/vq62nk9vq0

### Note
Problem does not appear on the original codesanbox https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Duplicate #2550.
