### ISSUE TITLE
fix(Form): <Form.Input as={Input}> causes warning "Invalid value for prop `control` on <div> tag."

### ISSUE THREAD

**Issue by lukas-zech-software** [Semantic-Org/Semantic-UI-React#2669]
**Steps to Reproduce**
Use `Form.Input` with property `as` set to `Input`

```jsx
<Form.Input as={Input} label='First name' placeholder='First name' />
```

**Expected**
The form should render without error or warning

**Result**
The Form renders and works as expected but this warning is printed in the console:
`
warning.js:33 Warning: Invalid value for prop `control` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior
    in div (created by Input)
    in Input (created by FormInput)
`

**Testcase**
https://s.codepen.io/lukas-zech-software/debug/PRpvjO/LQkExPJaJZWA

**Comment by brianespinosa** [comment]
@lukas-zech-software you don't need to define your `Form.Input` component `as={Input}`. Remove the `as` prop and you will be good. You're basically telling something that already renders as an `Input` to render as an `Input`.

**Comment by lukas-zech-software** [comment]
@brianespinosa 

The rendered output is quite different depending on `as={Input}` being used or not

The complete code I use is this:

```jsx
<Form.Input
          as={Input}
          key={'en'}
          error={this.props.error}
          // additional class name "field" is necessary to show error color when input is in error state
          className="field"
          fluid
          label={'en'}
          labelPosition={'right corner'}
          locale={'en'}
          defaultValue={value}
          style={{ paddingBottom: '5px' }}
          onChange={this.onInputChange}
          onBlur={this.props.onBlur}
        />
```
which renders this DOM:
![image](https://user-images.githubusercontent.com/10512593/37757647-030446ba-2dae-11e8-8fd9-46839e8c881d.png)

Without `as={Input}` this gets rendered:
![image](https://user-images.githubusercontent.com/10512593/37757772-63a4e93e-2dae-11e8-95c7-5eca3e7385b7.png)


As you can see the label now gets rendered as `<label>` instead of a `<div>` with `::after` content

**Comment by brianespinosa** [comment]
@lukas-zech-software the first markup is also not how SUI is expected in this case. You are creating a `Label` component versus a `<label>` tag. The bottom markup is correct (except you should not be passing a `className` since it's redundant, as you see in your markup).

1. Your codepen does not work because it's in debug mode. Removing that in the URL does not work.
2. I suspect you are trying to create an input with a label attached to the left or right side of the Input, instead of a label tag which would appear above the Input. If that's what you are trying to do, [please take a look at the Input docs where there are examples of how to pass a `label` prop which will render an attached Label instead](https://react.semantic-ui.com/elements/input#input-example-right-labeled-basic).

**Comment by lukas-zech-software** [comment]
So the thing is, you cannot use `<Form.Input />` when you want to have a `Label` on the input

You need to use `<Input />` instead and add the `field` class manually for it to behave correctly (eg. display error state)

```jsx
<Input
          key={'en'}
          error={this.props.error}
          // additional class name "field" is necessary to show error color when input is in error state
          className="field"
          fluid
          label={<Label>'en'</Label>}
          labelPosition={'right corner'}
          locale={'en'}
          defaultValue={val}
        />
```
The above renders the same as this
```jsx
<Form.Input
          as={Input}
          key={'en'}
          error={this.props.error}
          fluid
          label={<Label>'en'</Label>}
          labelPosition={'right corner'}
          locale={'en'}
          defaultValue={value}
         >
```

just without the warning

**Comment by brianespinosa** [comment]
@lukas-zech-software `<Form.Input>` is shorthand for doing this:

```
<Form.Field>
  <Input ...props />
</Form.Field>
```

**Comment by avinashjoshi** [comment]
I had a similar use-case with `DateInput` from https://github.com/arfedulov/semantic-ui-calendar-react which does not let me use `Input` explicitly. I did the following ti fix the warning and not having to use `as={Input}`:

```
<Form.Input
          key={'en'}
          className={'ui left corner labeled input'}
          error={this.props.error}
          fluid
          label={<Label size="mini" corner="right">'en'</Label>}
          labelPosition={'right corner'}
          locale={'en'}
          defaultValue={value}
         >
```

 _Added className, and changed label props_
