### ISSUE TITLE
UMD build expect React and ReactDOM to be global variables

### ISSUE THREAD

**Issue by KajSzy** [Semantic-Org/Semantic-UI-React#2670]
### Expected Result

UMD build won't assume React and ReactDOM as a global variables
Possible use with AMD and other moduels (commonjs)

### Version
0.78.3

According to Webpack doc:

> root: The library should be available as a global variable (e.g. via a script tag).
commonjs: The library should be available as a CommonJS module.
commonjs2: Similar to the above but where the export is module.exports.default.
amd: Similar to commonjs but using AMD module system.

Possible solution:
```
externals: {
        react: {
            root: 'React',
            commonjs2: 'react',
            commonjs: 'react',
            amd: 'react'
        },
        'react-dom': {
            root: 'ReactDOM',
            commonjs2: 'react-dom',
            commonjs: 'react-dom',
            amd: 'react-dom'
        }
    }
```

**Comment by KajSzy** [comment]
The whole scenario looks like this:

- I build (with webpack) a package where custom Semantic Theme and some custom components are defined.
- In webpack config React, ReactDOM and SemanticUIReact are declared as externals so they are not included in my project (thus package is much lighter)
- In another project where I use React, ReactDOM and SemanticUIReact my custom package with theme is imported, but I receive following error:
`Cannot read property 'Component' of undefined`
OR
`Cannot read property 'Label' of undefined`

So when I try to create some kind of "plugin" there is no way to exclude whole semantic-ui-react package from it.

Adding such externals to UMD package I hope will make it possible.

**Comment by brianespinosa** [comment]
@KajSzy this sounds like it is an issue with how you are trying to implement your build process and not something that we would be solving internally with SUIR. Without a working example showing exactly what is going on that illustrates a problem inherent in SUIR, I am going to go ahead and close this.
