### ISSUE TITLE
fix(Progress): Progress Inverted Indicating Label renders dark when percent > 0

### ISSUE THREAD

**Issue by mgandley** [Semantic-Org/Semantic-UI-React#2672]
**Steps to Reproduce**
1. Create a progress bar with the inverted and indicating properties, and percent 0.  Note that the label renders in white as expected.
2. Set the percent to any other value.  Note that the label changes color to the dark text color.

**Expected**
The progress bar should always render a white label when the inverted property is used.

**Result**
The progress bar renders the incorrect label color due to faulty CSS.

**Testcase**
https://codepen.io/anon/pen/jzwPjQ?editors=1111

**Comment by lubber-de** [comment]
Fixed by https://github.com/fomantic/Fomantic-UI/pull/412
Supposed to be included in the upcoming Fomantic-UI 2.7.2 Release
