### ISSUE TITLE
Please do proper changelogs and not an auto generated list of prs

### ISSUE THREAD

**Issue by ForsakenHarmony** [Semantic-Org/Semantic-UI-React#2675]
it's very hard to understand what's in it at a quick glance and just makes it seem like you really don't care, i.e. even this is better https://github.com/zeit/release

**Comment by levithomason** [comment]
I'm all for a real changelog.  A PR converting the current changelog to a proper one would be gladly accepted, especially converting the breaking change PRs.

We could do so by only going back a few versions with the new format.  We just need a pattern for people to follow.

**Comment by dylmye** [comment]
The project uses angular format, is it worth using [Conventional Changelog](https://github.com/conventional-changelog/conventional-changelog) in a hook or something similar? I'd like to contribute to this but I'm not sure how. Thanks :)
