### ISSUE TITLE
Firebox don't trigger onClick handler on icon in Button

### ISSUE THREAD

**Issue by grean** [Semantic-Org/Semantic-UI-React#2676]
Hi there,

Firefox problem only when we try to trigger an handler with onClick event attached to the icon in the button. It works fine in chrome or edge.

### Steps
click on icon in the button
### Expected Result
show the alert
### Actual Result
nothing happens with firefox
### Version
0.79.0

### Testcase
https://codesandbox.io/s/8nzj8z03lj

**Comment by fracmak** [comment]
move the onClick handler to the button instead of the icon. This isn't something we can control

**Comment by grean** [comment]
Are you sure ?
Because, this behaviour works fine on chrome and edge. In my app, i created two click events. One on the button and the other on the icon. The handler on the button is for the "selected" state and on the icon i trigger a modal for some information.
In firefox, the click on icon doesn't work.. any idea why this is the case ?

**Comment by fracmak** [comment]
According to the html5 spec for buttons

Content model:
Phrasing content, but there must be no interactive content descendant.

http://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element

Firefox is merely following the spec
