### ISSUE TITLE
<Input icon="search" type="search" /> produces two children with the same key "search"

### ISSUE THREAD

**Issue by dhnm** [Semantic-Org/Semantic-UI-React#2681]
### Steps
```
import { Input } from "semantic-ui-react";
<Input
            icon="search"
            type="search"
            id="myInput"
            value={this.state.myInput}
            onChange={e => this.setState({ [e.target.id]: e.target.value })}
/>
```

### Expected Result
Normal input – typing characters in the input will update state and the input's value will reflect that state.

### Actual Result
Two elements have the same key "search", probably the icon and input, resulting in duplication of the input element on each keystroke.

Workarounds: Use a different icon, use different input type, or remove this.seState.

Error in the browser console: `Warning: Encountered two children with the same key, `search`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`

### Version
0.79.0

**Comment by brianespinosa** [comment]
@rouxfeur For your edge case, as a workaround you can define your `icon` prop as a component as shown below. Additionally, you can also use the `Search` component that already defines the icon and type for the input.

```
    <Input icon={<Icon name="search" />} type="search" id="myInput" />
    // or
    <Search id="mySearch" />
```
