### ISSUE TITLE
fix(Container): on the website error: Container is not defined

### ISSUE THREAD

**Issue by Abusoss** [Semantic-Org/Semantic-UI-React#2684]
**Steps to Reproduce**
1. Go to https://react.semantic-ui.com/elements/container
2. Edit any exemples with the edit code widget(just a "Space" somewhere is enough)

**Expected**
Changes in the view

**Result**
error: 
"Container is not defined "

At the bottom of any example

**Testcase**
Not needed the probleme is on the the website.
Ps: no adblockers

**Comment by levithomason** [comment]
It seems the recent update to the regex for the code editor has broken things.  This comment at the top of the file is confusing the parser:

```jsx
/* eslint-disable max-len */
```

**Comment by levithomason** [comment]
See the change [here](https://github.com/Semantic-Org/Semantic-UI-React/pull/2481/files).  We need to update this to properly grab the body of the example.

**Comment by levithomason** [comment]
Fixed in #2706

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.80.0`.
