### ISSUE TITLE
Docs' example bug

### ISSUE THREAD

**Issue by syrepol** [Semantic-Org/Semantic-UI-React#2687]
Hey everyone, I just noticed a small bug at https://react.semantic-ui.com/elements/divider#divider-example-vertical
Look at dividers - they are stuck on the left side and hidden behind sidebar.

**Comment by hubertguillemain** [comment]
There is a comment on the SUI documentation:
https://semantic-ui.com/elements/divider.html

> "There is a known bug of vertical dividers after a W3C update. Please read #4342 for more information"

**Comment by brianespinosa** [comment]
Thanks @hubertguillemain 

Long-standing CSS issue in the way the spec is implemented.
