### ISSUE TITLE
fix(Icon): icons with "list" in name render incorrectly when used in children of a List component

### ISSUE THREAD

**Issue by SBIWebteam** [Semantic-Org/Semantic-UI-React#2688]
**Steps to Reproduce**
1. Render a List
2. Put a component in it with an Icon that has a name with the word "list" in it.

**Expected**
The Icon should have a margin and padding applied to it due to having the "icon" class

**Result**
The Icon has the margin and padding from the "icon" class overridden to it due to having a class called "list" and being a descendent of an element with the class "ui list"

**Testcase**
https://codepen.io/anon/pen/eMyJyY

**Comment by brianespinosa** [comment]
@SBIWebteam I am not able to get your codepen to open. It starts into an infinite load loop. Could you make an example of the issue you are experiencing in Codesandbox instead please? Here's a baseline you can start from: https://codesandbox.io/s/2l3n74j9y

**Comment by SBIWebteam** [comment]
Sure thing! Here's the same code: https://codesandbox.io/s/n8r7vvp8j

**Comment by brianespinosa** [comment]
@SBIWebteam thanks for taking the time to create that example.

You're actually rendering incorrect SUI markup when you render components that way. You are creating `Icon` components as direct children of `List` components. That is not how the styles are structured in the core SUI library. If you remove the `List` component you are wrapping with, you will be fine.

If you are trying to follow true semantics with the markup that is generated and you want these as  `<ul>` and `<li>` tags, you will have to do a few things manually. I have examples of both in this edited codesandbox: https://codesandbox.io/s/j304907x49

**Comment by SBIWebteam** [comment]
Thanks, that makes a lot of sense!
