### ISSUE TITLE
Update legacy component APIs to the v1 API

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#269]
Right now, many components still use className for all styling and behavior. Our v1 API, decided in #208, is more declarative. You can see it at play in the Divider, Label, and Dropdown components.  As well as any completed task below.

The [CONTRIBUTING.md](https://github.com/TechnologyAdvice/stardust/blob/master/CONTRIBUTING.md) guide details how to go about designing a component API.  The [Spec out the API](https://github.com/TechnologyAdvice/stardust/blob/master/CONTRIBUTING.md#spec-out-the-api) section is of primary importance. 

You can reference PR #262 as an example of how to upgrade a legacy component API to the v1 API.  Below are the remaining legacy components APIs.  Any PR to upgrade these components is much welcome.

**Collections**
- [x] ~~#351 Grid~~
- [x] ~~#382 Menu~~
- [x] ~~#451 Table~~

**Elements**
- [x] ~~#295 Button~~
- [x] ~~#277 Container~~
- [x] ~~#343 Icon~~
- [x] ~~#280 Image~~
- [x] ~~#281 Input~~
- [x] ~~#551 List~~
- [x] ~~#278 Header~~
- [x] ~~#287 Segment~~

~~**Modules**~~
- [x] ~~#379 Modal~~

~~**Views**~~
- [x] ~~#431 Item~~
- [x] ~~#334 Statistic~~

---

In addition to these component APIs, we're also removing jQuery and SUI JS from all components.  You can see that work in #247.

**Comment by layershifter** [comment]
I'll make PR for `<Menu>` soon, it's mine :gem:

**Comment by layershifter** [comment]
`Table` component hasn't own PR or issue, so I ask there.

---

It looks that `Table` can be stateless component, except one case, [sortable](http://semantic-ui.com/collections/table.html#sortable).

I think about making `Table.Sortable` that has state and allow it pass shorthands or only components `Table.Row`, `Table.Header`, etc. But, it is ugly. Any better ideas there?

**Comment by levithomason** [comment]
Moved here https://github.com/TechnologyAdvice/stardust/pull/451

**Comment by layershifter** [comment]
Unbelievable, it's almost done ✌️

**Comment by levithomason** [comment]
I know it!  Very crazy amount of work.  So proud to be a part of this community effort.  🎉

**Comment by jeffcarbs** [comment]
The closing of #551 checks the last box. Can we mark this issue as closed?

**Comment by levithomason** [comment]
Holy smokes, it is done! :tada:
