### ISSUE TITLE
Dropdown: should fire an onChange event when changing value property

### ISSUE THREAD

**Issue by heanzyzabala** [Semantic-Org/Semantic-UI-React#2692]
### Steps
- Create a selection dropdown with options
- Initialize a state and use that as the value of the value property of the dropdown
- Create an onItemChange method and set it in the onChange property of the dropdown

### Expected Result
The dropdown should initially select the 3rd item and should fire onItemChange event

### Actual Result
The dropdown selects the 3rd item but no onItemChange event was fired

### Version
0.77.2

### Testcase
https://codepen.io/zheanzy16/pen/BrYLBR

**Comment by layershifter** [comment]
It's not valid case at all as I see.

`Dropdown` selects defined value normally, `onChange` called when it should be called. See [controlled components](https://reactjs.org/docs/forms.html#controlled-components) for details.
