### ISSUE TITLE
Using iPad browser can't scroll on create / edit pop-up windows, should be able to scroll on ipad browser

### ISSUE THREAD

**Issue by ypxu87** [Semantic-Org/Semantic-UI-React#2699]
Using iPad browser can't scroll on create / edit pop-up windows, should be able to scroll on ipad browser

### Steps
1.touch 'Long Modal' button
2.try to scroll the window
### Expected Result
should scroll as expecte
### Actual Result
can not scroo
### Version
0.78.2

### Testcase
https://codesandbox.io/s/qqjwkzw256

###video
https://www.screencast.com/t/3h4QSBDdA

**Comment by levithomason** [comment]
~~Pretty sure this is Apple's fault, see https://github.com/Semantic-Org/Semantic-UI-React/pull/1833#issuecomment-313713611.  If not, as @brianespinosa said, this is working for others and may be project specific.~~

Just tried the codesandbox and this is working on my iPad mini.  Just sold my old iPad, so I have no other test devices.  If we're able to reproduce this in a local project or perhaps get some more info we can reopen and investigate.
