### ISSUE TITLE
[TransitionGroup] - Invalid prop `animation` of value `slide left`

### ISSUE THREAD

**Issue by lazdinst** [Semantic-Org/Semantic-UI-React#2702]
Still receiving `slide left` transition warning after updating to `0.79.1`

Issue https://github.com/Semantic-Org/Semantic-UI-React/issues/2573 says it was fixed in PR https://github.com/Semantic-Org/Semantic-UI-React/pull/2576 and `Released in semantic-ui-react@0.78.3.`

### Steps
`                <Transition visible={visible} animation='slide left' duration={500}>
                  <Segment>
                    Slide this segment in
                  </Segment>
                </Transition>
              </Segment.Group>
`
### Expected Result

animation slide left works and does not throw a warning.

### Actual Result
`index.js:2178 Warning: Failed prop type: Invalid prop `animation` of value `slide left` supplied to `Transition`, expected one of ["scale","fade","fade up","fade down","fade left","fade right","horizontal flip","vertical flip","drop","fly left","fly right","fly up","fly down","swing left","swing right","swing up","swing down","browse","browse right","slide down","slide up","slide right","jiggle","flash","shake","pulse","tada","bounce"].
    in Transition (at index.jsx:62)
    in EnvironmentSetup (created by Route)
    in Route (at RootRouter.jsx:52)
    in Switch (at RootRouter.jsx:24)
    in RootRouter (at App.jsx:67)
    in div (at App.jsx:65)
    in App (created by Connect(App))
    in Connect(App) (created by Route)
    in Route (created by withRouter(Connect(App)))
    in withRouter(Connect(App)) (at index.js:12)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (at index.js:11)
    in Provider (at index.js:10)
`
### Version
`"semantic-ui-react": "^0.79.1"`

### Testcase
https://codesandbox.io/s/93q1k4o1zy

**Comment by brianespinosa** [comment]
@lazdinst can you please complete the full report and create a working test case showing this issue. Your version says you are not on 0.79.3. I see the caret but there are sometimes issues where you are still not getting the latest version depending on if you are using `npm` or `yarn`

**Comment by lazdinst** [comment]
I am using `yarn` but in the past had been using `npm` to install dependencies.

I updated testcase with a sandbox, however, I can't seem to reproduce the result so it doesnt provide much visibility into the issue. I tried manually setting the version, in sandbox, to `0.79.3` per your comment; however, that version was not located; therefore I dropped it back down to `0.79.1` to get the sandbox to compile and serve the app.

I am guessing its specific to my local setup.

Not sure if this will help but here are the `yarn.lock` contents specific to semantic.

```
semantic-ui-react@^0.79.1:
  version "0.79.1"
  resolved "https://registry.yarnpkg.com/semantic-ui-react/-/semantic-ui-react-0.79.1.tgz#80bd0ccfb3b3c1184a1b1b3f6067ab1225aed5f0"
  dependencies:
    babel-runtime "^6.25.0"
    classnames "^2.2.5"
    fbjs "^0.8.16"
    lodash "^4.17.4"
    prop-types "^15.5.10"
```
I also verified that I am using in the `package.json` in node_modules/sematic-ui-react/package.json`

```
  "name": "semantic-ui-react",
  "version": "0.79.1",
  "description": "The official Semantic-UI-React integration.",
```


I ended up digging around in the modules folder and validate the contents of `SUI.js` containing the appropriate mapping to `slide left` and it being imported into the `Transistions.js` file.

```
export const DIRECTIONAL_TRANSITIONS = [
  'browse', 'browse right',
  'drop',
  'fade', 'fade up', 'fade down', 'fade left', 'fade right',
  'fly up', 'fly down', 'fly left', 'fly right',
  'horizontal flip', 'vertical flip',
  'scale',
  'slide up', 'slide down', 'slide left', 'slide right',
  'swing up', 'swing down', 'swing left', 'swing right',
]
export const STATIC_TRANSITIONS = ['jiggle', 'flash', 'shake', 'pulse', 'tada', 'bounce']
export const TRANSITIONS = [...DIRECTIONAL_TRANSITIONS, ...STATIC_TRANSITIONS]
```

**Comment by lazdinst** [comment]
So after double checking everything I blew away my `node_modules` directory and reinitiated a new install via `yarn` which resolved my issue.
