### ISSUE TITLE
Popup should have prop to close menu on click inside

### ISSUE THREAD

**Issue by jfeferman** [Semantic-Org/Semantic-UI-React#2703]
Under certain UX circumstances it might be desirable that a popup closes when the user clicks inside the popup (e.g. a popup with options that should be closed once an option is selected).

### Steps

Use:

```javascript
<Popup
  on="click"
/>
```

### Expected Result

Some prop that allows the popup to close when the user clicks inside it.

### Actual Result

There is no such prop.

### Version
0.79.1

### Workaround

To workaround this issue, it is necessary to control the popup visibility with state and override methods, as such:

```javascript
<Popup
  on="click"
  open={this.state.menuOpen}
  onOpen={() => this.handleMenuOpen()}
  onClick={() => this.handleMenuClose()}
  onClose={() => this.handleMenuClose()}
/>
```

**Comment by brianespinosa** [comment]
@jfeferman thanks for taking the time to open a report. Your workaround is actually how you would accomplish this. SUIR provides a framework for you as the developer to decide how to control your component state. What you are requesting is probably out of scope for this project.
