### ISSUE TITLE
Dropdown inside a menu does not close.

### ISSUE THREAD

**Issue by ditiem** [Semantic-Org/Semantic-UI-React#2705]
✔ BUGS → This form is required:

### Steps
Create a Dropdown inside the menu (you can edit one of the examples of https://react.semantic-ui.com/modules/dropdown  )

<Menu >
     <Dropdown item text='More' direction='right' fluid  selection options={getOptions(3)} />
 </Menu>

It fails when: !vertical AND direction is set

I suspect (I dont know how Semantic -UI works inside) this piece of CSS is making the problem:

.ui.menu:not(.vertical) .right.item, .ui.menu:not(.vertical) .right.menu {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    margin-left: auto!important;
}

The case it does not work is when the menu is shown / hidden by a dropbox. In this case the dropbox controls de "display"

### Expected Result
The Dropdown closes/open when clicking on it

### Actual Result
The Dropdonw always appears open

### Version
0.79.0 (it works on 0.78.0!)

### Testcase
https://codesandbox.io/s/3x980o243p

**Comment by ditiem** [comment]
@brianespinosa I do not get what you are saying. `direction` is there for a reason.

This is an example from the docs
( https://react.semantic-ui.com/modules/dropdown#dropdown-example-menu-direction )
```

<Menu>
      <Dropdown item simple text='Left menu' direction='right' options={options} />
      <Menu.Menu position='right'>
        <Dropdown **simple** item  text='Right menu' direction='right' options={options} />
      </Menu.Menu>
 </Menu>
```

If I remove the "simple" style because I want the menu to open by click rather than hover, the bug appears.

It was working perfectly on the previous version.

**Comment by ditiem** [comment]
@brianespinosa  Thanks for the explanation. I will survive with the Codesandbox example you did.

As a couple of notes:

1- Yes the fluid is intended. Reason is that the dropbox to not resize to the size of its children (that is what I expect from a dropbox vs a submenu), so I had to force the Menu.Menu to a certain size so when it opens it "makes sense" (otherwise the whole resize when selecting an option)

2- Yes, the selection was intended too. I was trying to do a toolbar. In a toolbar you may have buttons and dropdown, so I wanted them to be differentiated, as dropbox may appear empty and it was a long-white-space with an arrow at the end. I have had to make separated Menu with margins between them.

I think Semantic UI is mixing Menus, Dropdowns and "toolbars" concepts. Many simple things are very complicated or simply not possible.

Really thank you a lot for your help. I can keep going on now :)

**Comment by eclewlow** [comment]
This appears for me also.   Just as @ditiem mentioned, the CSS is overriding the `display` property, which causes the menu to appear and stay open.

@brianespinosa 
> the direction of the menu is automatically controlled in the CSS by SUI core styles

The menu appears cut off in my case (the CSS is not working correctly), so I have to specify `direction="left"`

My code
```javascript
<Menu>
    <Dropdown>...</Dropdown>
    <Menu.Menu position='right'>
        <Dropdown item direction='left'>
            <Dropdown.Menu>
                <Dropdown.Item content="Manage Users..."/>
            </Dropdown.Menu>
        </Dropdown>
    </Menu.Menu>
</Menu>
```

**Comment by ditiem** [comment]
@eclewlow It only works if you put it exactly in the way they are expecting (in previous versions it was more flexible).

For your case, the Dropdown item is missing a text prop. Also have to remove the direction='left'.

Try with this:

```
<Dropdown item text="More">
      <Dropdown.Menu>
          <Dropdown.Item content="Manage Users..." />
      </Dropdown.Menu>
</Dropdown>
```

**Comment by smogg** [comment]
I'm running into the same issue and I don't see it being addressed in this issue. I ended up fixing the problem by forcing visibility on the toggled element:

```styl
.item.dropdown

  .menu.left
    display none !important

    &.visible
      display: flex !important
```

**Comment by semireg** [comment]
Here's what I'm using:

```
.item.dropdown, .menu.left, .menu.right {
  display: none !important;
}

.item.dropdown, .menu.left.visible, .menu.right.visible {
  display: flex !important;
}
```

Praise the @smogg!

**Comment by alexboots** [comment]
Added a CSS fix to close it when clicking on the root menu icon (per above @smogg <3 )
But perhaps a separate issue ? it doesn't close when clicking outside of the menu on mobile. 

![2018-09-25 12 58 09](https://user-images.githubusercontent.com/896214/46029913-b228b200-c0c2-11e8-8af3-9e215cddba8c.gif)
