### ISSUE TITLE
RFC: Optimize Dropdown (and possibly List, Table) with react-virtualised

### ISSUE THREAD

**Issue by brianespinosa** [Semantic-Org/Semantic-UI-React#2709]
I am not sure if anyone else is aware of [`react-virtualized`](https://github.com/bvaughn/react-virtualized) but I think there are some of our components that would benefit significantly from implementing it.

I am not sure if there are opinions around this or if anyone else has experience using `react-virtualized` but I think it might be something worth exploring.

**Comment by levithomason** [comment]
We're using at work with success in perf, however, it has some difficulties from what I hear.  Specifically, they don't trigger item re-renders for nested props changes but ask to you create and toggle a top level prop on the item manually if you want to trigger a re-render for an item.

At any rate, yes I'd like to try it.  Closing in favor of https://github.com/Semantic-Org/Semantic-UI-React/issues/1674 which has more info, some perf analysis, and also my recommendation for `react-virtualized`.
