### ISSUE TITLE
fix(Dropdown): placeholder value changes on opening the dropdown without selecting a value

### ISSUE THREAD

**Issue by meghnaraju** [Semantic-Org/Semantic-UI-React#2714]
**Steps to Reproduce**
1. open the dropdown

**Expected**
Place holder value should remain intact until a value is selected

**Result**
Placeholder value changes to first option.

**Testcase**
<img width="1062" alt="screen shot 2018-04-11 at 5 25 20 pm" src="https://user-images.githubusercontent.com/30435690/38615185-61e5e2ba-3dad-11e8-8a5f-ebcc70743c47.png">

**Comment by JsGvDev** [comment]
I don't know if that case is a issue. Only happen when you have selection and it is not multiple or search. I solved that case to keep placeholder in this way.

`<Dropdown
        selectOnBlur={false}
        onChange={this.handleChange}
        placeholder="Select State ..."
        selection
        options={options}
        text={value || "Select State ..."}
      />`

it is only a example, you can manage in other way. You can check it from here. See [codepen](https://codesandbox.io/s/rjm28vv31o)

**Comment by levithomason** [comment]
This is, in fact, the intended behavior of the Dropdown.  See the original Dropdown here:

https://semantic-ui.com/modules/dropdown#search-selection

The placeholder is used to show a preview of the selected item's value or text attribute.

**Comment by reenan** [comment]
@levithomason This is not happening on the link you shared, and the behavior is different if we check on [React Semantic Dropdown](https://react.semantic-ui.com/modules/dropdown/) and [Semantic UI Dropdown](https://semantic-ui.com/modules/dropdown#search-selection).

On react the placeholder changes, on the other one not.

Also on react, if you open the dropdown and close it by clicking outside, without selecting any option, the first option will be automatically selected, which is pretty weird, given that if you open and click on the Dropdown itself (on the input field), then a value is not selected.

**Comment by whitebyte** [comment]
This behavior is indeed weird, please reopen
