### ISSUE TITLE
times icon not supported

### ISSUE THREAD

**Issue by dhilgarth** [Semantic-Org/Semantic-UI-React#2717]
### Steps
```
<Icon name="times"/>
```

### Expected Result
The [times](https://fontawesome.com/icons/times?style=solid) icon is rendered
### Actual Result
The times icon is not rendered and an error is logged to the console:
```
Warning: Failed prop type: Invalid prop `name` of value `times` supplied to `Icon`.

Instead of `times`, did you mean:
  - time
  - user times
  - vimeo

    in Icon (created by App)
    in App
```
### Version
0.79.1

### Testcase
https://codesandbox.io/s/z243y42jwx

**Comment by layershifter** [comment]
Duplicate #2550.
