### ISSUE TITLE
Documentation about Tab: declaring tab without use of array shortcut for define tabs

### ISSUE THREAD

**Issue by herbertpimentel** [Semantic-Org/Semantic-UI-React#2720]
I am sorry, I tryed hard to figure out how to write a basic tab without use of panes array. docs says it is a shortcut but i cant find anywhere how to declare them not using a shortcut, I was expecting something like:

```jsx
<Tab>
   <Tab.Pane>
       <Header>Tab One</Header>
        <div>
              .....
        </div>
   </Tab.Pane>
   <Tab.Pane>
       <Header>Tab Two</Header>
        <div>
              .....
        </div>
   </Tab.Pane>
</Tab>```


is it possible ? or It is only possible using the array ?

**Comment by tspanu** [comment]
I'm using https://github.com/reactjs/react-tabs. It allows you to create tabs in a much more intuitive and flexible way.
