### ISSUE TITLE
blinking Inputs fields in Form component

### ISSUE THREAD

**Issue by rafalradomski** [Semantic-Org/Semantic-UI-React#2723]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes

✔ BUGS → This form is required:

### Steps

Go to: https://react.semantic-ui.com/collections/form#form-example-subcomponent-control
Click: Textarea 

### Expected Result

No blinking Inputs fields above Textarea

### Actual Result

All Inputs fields above Textarea are blinking after the first click

### Version
0.79.1

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by levithomason** [comment]
Well, that is odd.  Thanks for the report...

Investigating here, do you by chance have grammarly installed?  When I disable that extension, it no longer blinks for me.

Going to close as it also does not happen in incognito mode.  This isn't the first time grammarly has broken a web page on me :)

**Comment by rafalradomski** [comment]
Ahhh yes it's Grammarly extension,you are right, it's not a bug it's a feature ;)
