### ISSUE TITLE
No way to pass Input label via Form.Input

### ISSUE THREAD

**Issue by wichert** [Semantic-Org/Semantic-UI-React#2727]
### Steps

I would like to create a form input field with an input label. This is currently a bit harder to do due the fact that both FormField and `Input` use a `label` property. This makes impossible to use FormInput and pass a label through to `Input`

### Expected Result

It would be convenient if there was a way to either specify extra control properties, for example:

```html
<Form.Input
  name="discount"
  label="Discount"
  controlProps={{label: '%', labelPosition: 'right'}}
/>
```

or to alias the input label prop:

```html
<Form.Input
  name="discount"
  label="Discount"
  inputLabel="%"
  labelPosition="right"
/>
```
 
The version is more generic and will work for all similar conflicts, so might be a better choice.

### Testcase
https://codesandbox.io/s/n7qrzk63l

**Comment by levithomason** [comment]
`Form.Input` is convenience for `<Form.Field><Input /></Form.Field>`:

```jsx
<Form.Field>
  <label>Discount</label>
  <Input name='discount' label='%' labelPosition='right' />
</Form.Field>
```

***

See https://react.semantic-ui.com/collections/form#form-example-subcomponent-control:

```jsx
<Form.Input label='Enter Password' type='password' />

// vs

<Form.Field>
  <label>Enter Password</label>
  <Input type='password' />
</Form.Field>
```

**Comment by montogeek** [comment]
@wichert Did you found a workaround for this?
I need to show the error popup when using `Form.Input` but also use the `label` prop.
