### ISSUE TITLE
Multiple Dropdown search

### ISSUE THREAD

**Issue by claudioviola** [Semantic-Org/Semantic-UI-React#2729]
Hi,
I'm using a dropdown with multiple and search features enabled.
Is it possible disabled or hide tags when the options are selected?
I would like that placeholders is always visibile.
thanks

**Comment by levithomason** [comment]
This is a support request.  GitHub is for bugs and features.  You'll get the best help using one of the dedicate outlets:

Docs - http://react.semantic-ui.com

Chat - https://gitter.im/Semantic-Org/Semantic-UI-React

SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes
