### ISSUE TITLE
Search dropdown doesn't work with JSX option text

### ISSUE THREAD

**Issue by ThiefMaster** [Semantic-Org/Semantic-UI-React#2730]
### Steps
Have a Search Dropdown that uses formatted content for an option

### Expected Result
Searching works 

### Actual Result
Searching doesn't work for elements that are not plain text

### Version
0.79.1

### Testcase
https://codesandbox.io/s/zk32l4zrm
(try searching for `Foo`)

---

According to the TypeScript definitions the `text` of the option is `SemanticShorthandContent` which is `React.ReactNode` so I'd expect it to work...

**Comment by levithomason** [comment]
You're looking for the `content` prop for the options.

>According to the TypeScript definitions the text of the option is SemanticShorthandContent which is React.ReactNode so I'd expect it to work...

Yes, but you are not passing a string.  You are passing a react element 😉 `text: <u>Foo</u>`.

### `item.text`

The `text` prop only accepts a string.  It is used when searching. Note the console errors thrown by the prop types checker.

### `item.content`

This allows you to control a dropdown item's rendered value in the dropdown menu.  This is separate from the text.  The text is used for search and is the value shown in the dropdown when the item is active.

https://react.semantic-ui.com/modules/dropdown#dropdown-example-item-content
