### ISSUE TITLE
Modal cannot be given "as".

### ISSUE THREAD

**Issue by jlVidal** [Semantic-Org/Semantic-UI-React#2731]
✔ BUGS → This form is required:

**FIX seems to be a "TODO" commented here:**

https://github.com/Semantic-Org/Semantic-UI-React/blob/7ac06c4a2dff912a64a7011a327b23f87cc91844/src/modules/Modal/Modal.js#L285

Steps
`<Modal defaultOpen={true}  as={(props) => <div {...props}  />} />`

Expected Result
Should work without throwing an error.

Actual Result
```
index.js:2178 Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `Modal`.
    in as (created by Modal)
```

Version
0.78.2
### Testcase
[Sample](https://codesandbox.io/s/5yq9mjw404)

**Comment by levithomason** [comment]
This is correct.  Let's keep #2306 as the main thread for this.  Closing as a duplicate.
