### ISSUE TITLE
Tab not display full item

### ISSUE THREAD

**Issue by trangtv04110** [Semantic-Org/Semantic-UI-React#2733]
Hi, I added Tab component with 10 panes

It displays ok on laptop, but not display full panes on mobile.

How can I make it responsive?

Code example:

import React from 'react'
import { Tab } from 'semantic-ui-react'

const panes = [
  { menuItem: 'Tab 1', render: () => <Tab.Pane>Tab 1 Content</Tab.Pane> },
  { menuItem: 'Tab 2', render: () => <Tab.Pane>Tab 2 Content</Tab.Pane> },
  { menuItem: 'Tab 3', render: () => <Tab.Pane>Tab 3 Content</Tab.Pane> },
  { menuItem: 'Tab 4', render: () => <Tab.Pane>Tab 4 Content</Tab.Pane> },
  { menuItem: 'Tab 5', render: () => <Tab.Pane>Tab 5 Content</Tab.Pane> },
  { menuItem: 'Tab 6', render: () => <Tab.Pane>Tab 6 Content</Tab.Pane> },
  { menuItem: 'Tab 7', render: () => <Tab.Pane>Tab 7 Content</Tab.Pane> },
  { menuItem: 'Tab 8', render: () => <Tab.Pane>Tab 8 Content</Tab.Pane> },
]

const TabExampleBasic = () => (
  <Tab panes={panes} />
)

export default TabExampleBasic

**Comment by levithomason** [comment]
Hi @trangtv04110, this is a support request.  GitHub is for bugs and features.  You'll get the best help using one of the dedicate outlets:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes
