### ISSUE TITLE
Not compatible with semantic-ui-css 2.3.1

### ISSUE THREAD

**Issue by ashokdey** [Semantic-Org/Semantic-UI-React#2736]
### Steps
- The ```semantic-ui-css``` v 2.3.1 is not compatible with current version of ```semantic-ui-react```
- Modal placing is not working
### Expected Result
![Login Modal](https://preview.ibb.co/nKcprx/Screenshot_from_2018_04_24_18_35_57.png)
### Actual Result
![Login Modal](https://preview.ibb.co/ig37dc/Screenshot_from_2018_04_24_18_20_26.png)
### Version
0.77.0

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Duplicate #2550.
