### ISSUE TITLE
Is it possible to have Form.Input with Input intself displayed as labeled?

### ISSUE THREAD

**Issue by ragrub** [Semantic-Org/Semantic-UI-React#2742]
I want to achieve something like this:

![image](https://user-images.githubusercontent.com/29981194/39291313-e67022ee-4932-11e8-83a4-98a29cfcf48e.png)

        <Form.Input
          required
          label={'Identifier'}
          name={identifier}
          inputLabel={'appl'} ???
        />

**Comment by levithomason** [comment]
Yes https://github.com/Semantic-Org/Semantic-UI-React/issues/2727
