### ISSUE TITLE
Nested Dropdown menu not showing correctly when hover others

### ISSUE THREAD

**Issue by tiagowippel** [Semantic-Org/Semantic-UI-React#2743]
### Steps

Just open one dropdown menu and hover another item of the main menu. (view the testcase)

### Expected Result

When submenu leaves hover, this should close...
See the "pointing" example https://semantic-ui.com/modules/dropdown.html

### Actual Result

![image](https://user-images.githubusercontent.com/12776397/39305283-e5f70134-4932-11e8-8a71-08cd49f3f78a.png)

### Version
0.79.1

### Testcase
https://codesandbox.io/s/l5rkz32wkm

**Comment by levithomason** [comment]
Note, we don't technically support this usage:


However, the `simple` prop is used to make a Dropdown open on hover (i.e. without JS, uses CSS):

```diff
-<Dropdown item text="Account Settings">
+<Dropdown item simple text="Account Settings">
```

Working demo: https://codesandbox.io/s/x7vrmjmyqz
Docs: https://react.semantic-ui.com/modules/dropdown#dropdown-example-simple
More docs (wrench icon): https://react.semantic-ui.com/collections/menu#menu-example-attached
