### ISSUE TITLE
Inverted Button Remains Active After Clicking

### ISSUE THREAD

**Issue by abbasyadollahi** [Semantic-Org/Semantic-UI-React#2745]
### Steps
I'm creating an inverted Button that can be active when clicked.

### Expected Result
When clicked, the button is toggled (and is filled in with the given color).
When clicked again, the button is untoggled (not active) and the color fill is white again (back to normal).

### Actual Result
When clicked again, the button is untoggled (not active) except the color fill remains there until I click somewhere on the screen.
I've pinpointed it to having to do with the inverted option as if I click an inverted button, the fill remains until I click elsewhere.

### Version
SUI react: ^0.78.3
SUI css: ^2.3.0

### Testcase
https://codesandbox.io/s/won9oz7mnk

**Comment by abbasyadollahi** [comment]
The button in the sandbox you provided still remains active even after clicking it though?
It acts in the same way as my example.

**Comment by levithomason** [comment]
Oops, wrong link 😊 Here's the correct one that shows inline styling to override the focus style.  Again, this is the **not** the recommended way to do this.  You should use theming.  I've only done it this way to illustrate the point that a button retains focus after click.  It is not active, it is focused:

https://codesandbox.io/s/nn029z425p

![http://g.recordit.co/AoT0eoGZZx.gif](http://g.recordit.co/AoT0eoGZZx.gif)

```css
.ui.inverted.orange.button:focus {
  box-shadow: inset 0 0 0 2px #ff7701, inset 0 0 0 4px white !important;
}
```

**Comment by yevreinov** [comment]
I don't think this can be considered as a theming issue. Un-inverted button behaves normally: when you release button it turns back to it's original unfilled state.

I can still see this issue with:
"semantic-ui-css": "^2.4.1",
"semantic-ui-react": "^0.88.2"
