### ISSUE TITLE
Button role="button" is not configurable

### ISSUE THREAD

**Issue by lnegi** [Semantic-Org/Semantic-UI-React#2751]
When i try to use a button as an anchor link using the "as" property `<Button as="a" role="link" ...>` the role of the generated anchor tag is still button.

in Button.js we see below code , may be role can also be accepted as a prop
` ref={this.handleRef}
        role='button'
        tabIndex={tabIndex}`

**Comment by levithomason** [comment]
Fixed in #2752

**Comment by lnegi** [comment]
Thanks @levithomason that was quite quick 👍
