### ISSUE TITLE
Support allowAdditions option for Dropdowns

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#276]
We're currently using this feature in one of our forms:

http://semantic-ui.com/modules/dropdown.html#tagging-and-user-additions

We cannot finish updating and removing previous hacks until we add support for this or rework the form to not rely on it.

**Comment by levithomason** [comment]
Our single use of this feature is no longer needed, we've opted to forgo it's development for now.

**Comment by dylankiss** [comment]
I need the allowAdditions functionality for our project and have added this on my fork of stardust. When I clean it up, I will make a PR such that you could take a look whether I took a good approach or not.

**Comment by levithomason** [comment]
@dylankiss I would be delighted to take a look. Feel free to open the PR now, we can collaborate on it there. I am traveling today but will be back tomorrow. Cheers!

**Comment by dylankiss** [comment]
@levithomason I opened a PR (https://github.com/TechnologyAdvice/stardust/pull/356) such that you can take a look. I still need to add tests when everything seems good.
