### ISSUE TITLE
Textarea Issue

### ISSUE THREAD

**Issue by jamalabo1** [Semantic-Org/Semantic-UI-React#2762]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes

✔ BUGS → This form is required:

### Steps
Enter text, 
hit enter and now thing happens
### Expected Result
Enter new line
### Actual Result
nothing.

### Version
0.79.1

### Testcase
[Fork, update, and replace this pen to show the bug]:

https://react.semantic-ui.com/addons/text-area#text-area-example-min-height

**Comment by levithomason** [comment]
Cannot reproduce.  Which browser are you using?

### Chrome

![http://g.recordit.co/6n8ocbgUhs.gif](http://g.recordit.co/6n8ocbgUhs.gif)

### FireFox

![http://g.recordit.co/F2fC2Qj6ov.gif](http://g.recordit.co/F2fC2Qj6ov.gif)

**Comment by levithomason** [comment]
![http://g.recordit.co/F2fC2Qj6ov.gif](http://g.recordit.co/F2fC2Qj6ov.gif)
