### ISSUE TITLE
Docs: missing changelog for last releases

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#2764]
@levithomason We don't have [CHANGELOG](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/CHANGELOG.md) for `0.79.1` and `0.80.0`. A I see, you [removed](https://github.com/Semantic-Org/Semantic-UI-React/commit/f6c319874a3d41bec7ebbed3e0ccf2fe1f296009) build step, but now we don't have changelog at all :crying_cat_face:

**Comment by levithomason** [comment]
Oh boy.  Fixing...

**Comment by levithomason** [comment]
Restored the scripts in d0eba9876418c187feb30527cd24e480667757bf and deployed the changelog in ed935f88360e47a150a8f4fc0ce05360a4200ce2.
