### ISSUE TITLE
[Dropdown][Search Selection] Ignore Hyphens when searching a string

### ISSUE THREAD

**Issue by miguelHx** [Semantic-Org/Semantic-UI-React#2780]
### Problem description
Dropdown search has an undesired behavior when searching options that have hyphens.

### What happens
For example, given the following code:
```js
const testOptions = [
  { key: 'United-States', value: 'United-States', text: 'United-States' },
  { key: 'firstname-lastname', value: 'firstname-lastname', text: 'firstname-lastname' },
];

<Dropdown
  selectOnNavigation={false}
  search
  selection
  options={testOptions}
/>
```

In the dropdown, when searching 'united' it works and all is fine.  However, when searching for 'unitedstates' or 'unitedst' there is no match.  My code depends on there being hyphens in the options array, so simply removing the hyphens from the provided options would not work for me.  Same thing for firstname-lastname.  Searching for 'firstname' or 'lastname' works, but not 'firstnamelastname'.  
This issue is not limited to Hyphens.  Replace the hyphen with a space and you get the same issue.  Same thing with commas.  Generally, any word delimiter.
[Link to CodePen](https://codepen.io/Flwy_h/pen/GdxorG)

### Proposed solution
I would like for there to be a dropdown match when the user searches for a joined version of an option separated by some delimiter.
We can make this feature optional via a prop called 'matchWithoutDelimiter' or something.

**Comment by levithomason** [comment]
Good news:

### Props

![image](https://user-images.githubusercontent.com/5067638/39933225-30f3adb6-54f7-11e8-8776-cb5f0a049472.png)

### Example
https://react.semantic-ui.com/modules/dropdown#dropdown-example-custom-search-function

>### Custom Search Function
>A dropdown allows you to provide your own search function.
