### ISSUE TITLE
falling to fix-position top navigation within Sidebar

### ISSUE THREAD

**Issue by dimasyankauskas** [Semantic-Org/Semantic-UI-React#2781]
HI Experts.
I was fighting this navigation dilemma for the last 2 days.  
how can I fix to the top mobile top navigation bar so it is not scroll out with content if i'm using side bar implementation?

Please help.
https://codesandbox.io/s/p3m6rkpl0q
mobile nav line: 73 -...

**Comment by levithomason** [comment]
This is a support request.  GitHub is best for bugs and features.  You'll receive better assistance using one of the dedicated support outlets:

Docs - http://react.semantic-ui.com

Chat - https://gitter.im/Semantic-Org/Semantic-UI-React

SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes
