### ISSUE TITLE
<Menu> stackable when to many Item in mobile

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#2797]
## Feature Request  
< Menu> stackable when to many <Menu.Item>  on mobile     

### Problem description  
When use < Menu> with stackable prop, If there are to many <Menu.Item> when on mobile,   
< Menu> will not collapse automatically like Bootstrap < Navbar>

**Comment by varunzxzx** [comment]
Yes, it is very much required.

**Comment by layershifter** [comment]
Please check out [HomepageLayout example](https://react.semantic-ui.com/layouts/homepage), SUI core doesn't offers such feature.

I'm not sure that core team has a priority for this request. The best way to open PR and contribute this thing :+1:
