### ISSUE TITLE
Checkbox - pass disabled attribute to child input

### ISSUE THREAD

**Issue by ofir-shapira-como** [Semantic-Org/Semantic-UI-React#2801]
There is an issue with the input element that is created by `<Checkbox>`.

When the `<Checkbox>` is disabled, the [input ](url)is not disabled and it allows to focus on the element.
See an example in: https://codesandbox.io/s/3x9rn7lo5

The proposed solution is to add _disabled_ attribute to the `input `in case the user asks the `<Checkbox>` to be _disabled_.

https://github.com/Semantic-Org/Semantic-UI-React/pull/2800

**Comment by layershifter** [comment]
Fixed in #2800.
