### ISSUE TITLE
Cant get back to select state after selection is made

### ISSUE THREAD

**Issue by sukrutha2312** [Semantic-Org/Semantic-UI-React#2809]
After the selection is made on the dropdown cant go back to select again and are forced to select something from the dropdown.

![semantic dropdown](https://user-images.githubusercontent.com/20109849/40230969-4c1747f2-5a91-11e8-9c59-8abc58682170.png)

**Comment by layershifter** [comment]
Use controlled components, you will can set value of `Dropdown` to `undefined`. In fact, it's a usage question, please use SO.
