### ISSUE TITLE
Dropdown for pagination

### ISSUE THREAD

**Issue by sukrutha2312** [Semantic-Org/Semantic-UI-React#2811]
Could you add a dropdown to jump to a particular page without range to be used for medium sized list. currently I can see an active slider. This will be an addition.

**Comment by layershifter** [comment]
The `Pagination` component was implemented by me. I and almost all users don't this feature, I've made a component with an focuces eye for the already existing.

The best way to get this opportunity is to implement yourself and share it via PR :+1:
