### ISSUE TITLE
Cannot find module "@babel/runtime/helpers/getPrototypeOf" in Babel 7

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#2812]
### Steps
A clear and concise description of steps to reproduce the problem.

Use @babel v7

### Expected Result
Should compile OK

### Actual Result
Cannot find module "@babel/runtime/helpers/getPrototypeOf

That module is missing in @babel7

**Comment by layershifter** [comment]
```bash
$ cat node_modules/@babel/runtime/helpers/getPrototypeOf.js | head -n 1
var _Object$getPrototypeOf = require("../core-js/object/get-prototype-of");
```

```
$ cat node_modules/@babel/runtime/package.json | grep version
  "version": "7.0.0-beta.46",
```

Can you please provide more details?

**Comment by tomitrescak** [comment]
@layershifter the package is required from `@babel/runtime/helpers/getPrototypeOf` not from "`./core-js/object/get-prototype-of` not sure what you mean by what you pasted.

**Comment by tomitrescak** [comment]
Message from webpack:

```
./node_modules/semantic-ui-react/dist/es/addons/Confirm/Confirm.js
Module not found: Can't resolve '@babel/runtime/helpers/getPrototypeOf' in '.../node_modules/semantic-ui-react/dist/es/addons/Confirm'
```

**Comment by layershifter** [comment]
File `getPrototypeOf.js` exists in `@babel/runtime@7.0.0-beta.46`, i.e. all okay.

**Comment by layershifter** [comment]
Please give more info of used versions, possible you need simply reinstall deps.

**Comment by tomitrescak** [comment]
@layershifter all good, 7.0.0-beta.42 missed it. Thanks, and sorry for wasting your time over solving betas :/

**Comment by nloding** [comment]
I am not sure what the end result of the conversation above was - but I am running into this issue. It may be related to create-react-app@next/react-script@next too. I opened an issue over there, but thought I'd reference it here: https://github.com/facebook/create-react-app/issues/4511

Any thoughts @layershifter ? @tomitrescak how you were using SUI, with CRA?

**Comment by tomitrescak** [comment]
@nloding that's exactly what it is. The create-react-app@next/react-script@next is using version `7.0.0-beta.42` which is missing the above function. Wait for the full release.

**Comment by nloding** [comment]
@tomitrescak unfortunately that is not the case. `7.0.0-beta.42` may be missing it (looks like beta.44 is also, which is actually what react-scripts@next references), but if you manually install `@babel/runtime@7.0.0-beta.47` you get the same compilation error.

```
❯ cat node_modules/@babel/runtime/helpers/getPrototypeOf.js | head -n 1
var _Object$getPrototypeOf = require("../core-js/object/get-prototype-of");

❯ cat node_modules/@babel/runtime/package.json | grep version
  "version": "7.0.0-beta.47",

❯ yarn start
...
./src/App.js
Module not found: Can't resolve '@babel/runtime/helpers/getPrototypeOf' in '/Users/nloding/code/oss/cra2-workspace-broken-ref/src'
```

**Comment by rjbergerud** [comment]
Does anyone have any suggestions on how to deal with this while continuing to use semantic-ui-react and react-script@next together?  I need to keep react-scripts@next for monorepo support.

**Comment by nloding** [comment]
@rjbergerud I don't have my code anymore, it was just temporary code I was messing with, but I believe the fix was to `nohoist` everything `babel/*`. However, the latest version of react-scripts (`react-scripts@2.0.0-next.a671462c`) uses `7.0.0-beta.46` which should have `getPrototypeOf` I think.

**Comment by venikx** [comment]
Hmm, I tried with (react-scripts@2.0.0-next.a671462c) but same issue?

**Comment by nloding** [comment]
@AnaRobynn https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/package.json#L24

If you look at your `node_modules` directory, is the right version installed? Are you using a monorepo/lerna, and if so, did you `nohoist` the right stuff?

**Comment by venikx** [comment]
I don't have a monorepo/lerna. So I don't need that. 

The first time I tried upgrading resulted in babel 7 beta release to be installled. But I think it was 50+. Second time I tried my tests broke, because it installed babel 6.

I just went home. I might be tired. Tomorrow is another day.

**Comment by eGroupTeam** [comment]
This issue is not been solved by use latest react-scripts@next. What happened actually?

**Comment by nloding** [comment]
@eGroupTeam `react-scripts@2.0.0-next.a671462c` uses `babel@7.0.0-beta.46` which has `getPrototypeOf`. Some previous betas of babel did not. Did you upgrade to those scripts and install all the dependencies? What version of babel is in your node_modules directory?
