### ISSUE TITLE
TypeError: null is not an object (evaluating 'e.rootNode.firstElementChild')

### ISSUE THREAD

**Issue by bramski** [Semantic-Org/Semantic-UI-React#2816]
## Bug Report
I got this error from our react app yesterday. I haven't seen any other occurences.  It's on a page which gathers data from a graphql endpoint and then renders an iframe from a url contained in the data.  I'm not sure where it failed as the stacktrace is not anywhere in our code, and it only happened once.

<img width="839" alt="screen shot 2018-05-20 at 10 06 21 am" src="https://user-images.githubusercontent.com/421781/40281354-94b69294-5c15-11e8-8a54-ade4ca4c09a7.png">

**Comment by layershifter** [comment]
I prefer to close issues with a repro case. If there will be a repro case, I will reopen it.
