### ISSUE TITLE
Warning: <a> cannot appear as a descendant of <a>

### ISSUE THREAD

**Issue by darky** [Semantic-Org/Semantic-UI-React#2825]
## Bug Report
```jsx
<Menu>
  <Menu.Item>
    <Menu.Header>Header</Menu.Header>
    <Menu.Menu>
      <Menu.Item>
        Child item
      </Menu.Item>
    </Menu.Menu>
  </Menu.Item>
</Menu>
```

generate:

```html
<div class='ui menu'>
  <a class='item'>
    <div class='header'>Header</div>
    <div class='menu'>
      <a class='item'>Child item</a>
    </div>
  </a>
</div>
```

Which cause warning on React 16:
`Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.`

### Expected Result
No warning

### Actual Result
Warning

### Version
0.78.3

**Comment by layershifter** [comment]
The JSX above will produce:

```html
<div class="ui menu">
  <div class="item">
    <div class="header">Header</div>
    <div class="menu">
      <div class="item">Child item</div>
    </div>
  </div>
</div>
```

---

A `Menu.Item` becomes the `a` tag automaticaly when you're passing `onClick` or `href` props. If you need this behaviour, just manually pass an `as` prop.

```jsx
<Menu.Item as='div' href='/foo' />
```
```html
<div href="/foo" class="item"></div>
```

**Comment by Neo-Ryo** [comment]
Nice bug report and nice debug response, thank u both!
