### ISSUE TITLE
Prerender docs on the server side

### ISSUE THREAD

**Issue by mxschmitt** [Semantic-Org/Semantic-UI-React#2826]
## Feature Request

Improve the SEO for Google etc. by adding a sitemap and a robots.txt

### Problem description

When we search e.g. for "semantic ui react label", no result for the react label will appear:

![image](https://user-images.githubusercontent.com/17984549/40470464-d7d8e966-5f33-11e8-9741-2acd3817b641.png)

### Proposed solution

- add a sitemap.xml
- add a robots.txt which refer to the sitemap

### MVP

Best way would be to not hard code the sitemap. So maybe we could generate the links?

I'm also not sure, if this repo is the correct place for such an issue. I haven't found the repository for the semantic ui react documentation page yet.

## Edit:

 I tried to find the URLs in Google by searching for `site:https://react.semantic-ui.com/elements/label`.
=> Google has indexed the result, so maybe just the SEO is very bad on these pages? idk

**Comment by layershifter** [comment]
I want to try move our docs to [Gatsby](https://github.com/gatsbyjs/gatsby), it looks like the best solution there.

**Comment by levithomason** [comment]
Prerendering would be great.
