### ISSUE TITLE
Menu item text sometimes malformed

### ISSUE THREAD

**Issue by alexpricedev** [Semantic-Org/Semantic-UI-React#2828]
### Steps
Create a menu with a menu item containing "ABCa" as the name prop

### Expected Result
The menu item to be rendered with the text "ABCa" 

### Actual Result
The menu item was rendered with the text "AB Ca"

### Version
`0.80.0`

### Testcase
https://codesandbox.io/s/nnzyr1x1m

**Comment by msrikanth508** [comment]
@alexpriceonline Thank you for reporting a bug. 

@levithomason I've verified codebase, we are converting given `Name` prop to **startCase**. `Menu.Item` component is accepting custom messages using Content prop, in this case, we should not do any alteration for `Name` prop. If user wants to render something different, he/she can always do with `Content` prop.

Please let me know your thoughts.

**Comment by layershifter** [comment]
Duplicate, see [1340#comment](https://github.com/Semantic-Org/Semantic-UI-React/issues/1340#issuecomment-280720627).
