### ISSUE TITLE
npm audit throws issue on mini match

### ISSUE THREAD

**Issue by simplegadget512** [Semantic-Org/Semantic-UI-React#2829]
## Bug Report

installing semantic UI causes npm audit to throw a high threat warning for minimatch

### Steps

npm install semantic-ui

### Expected Result

no warnings or issues

### Actual Result

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ semantic-ui                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ semantic-ui > gulp > vinyl-fs > glob-stream > glob >         │
│               │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/118                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

### Version

2.3.1

**Comment by layershifter** [comment]
This repo matches the `semantic-ui-react` package.
