### ISSUE TITLE
Button not rendering

### ISSUE THREAD

**Issue by johnrees** [Semantic-Org/Semantic-UI-React#2834]
## Bug Report

The newest release (0.80.1) seems to have broken `Button`

### Expected Result
`<Button>test</Button>` should render a Button

### Actual Result
`instance.render is not a function`

### Version
0.80.1

### Testcase

https://codesandbox.io/s/lpknn729pl

**Comment by cstrat** [comment]
This bug doesn't just impact `<Button />`.

Reports of it impacting: `<Accordion />`, `<Input />`, `<Label />`, `<List />` and `<Menu />` too.

In my project I am seeing this:

    Warning: Menu(...): No `render` method found on the returned component instance: you may have forgotten to define `render`.

**Comment by VaidotasSm** [comment]
I can confirm this, having same issue:
```
Warning: Button(...): No `render` method found on the returned component instance: you may have forgotten to define `render`.

Uncaught TypeError: instance.render is not a function
```

Reverting back to `0.79.1` resolved it. `0.80.0` seems to have same issue for me.

**Comment by cstrat** [comment]
`0.80.0` should work fine as that was what i was working on prior to this update.

**Comment by layershifter** [comment]
See [#2831#comment](https://github.com/Semantic-Org/Semantic-UI-React/issues/2831#issuecomment-391964493).
