### ISSUE TITLE
Warning: Icon(...): No `render` method

### ISSUE THREAD

**Issue by BlackScarx** [Semantic-Org/Semantic-UI-React#2835]
### Steps
Since the last update 0.80.1 I got error with Icon, Message, Menu and maybe another

No `render` method

When I'm back to 0.78.3 no error

```
<Header as='h2' icon>
    <Icon name='settings' />
        Account Settings
    <Header.Subheader>
        Manage your account settings and set e-mail preferences.
    </Header.Subheader>
</Header>
```

### Expected Result
![image](https://i.imgur.com/VScscEV.png)

### Actual Result
![image](https://i.imgur.com/SgjB2nU.png)

### Version
0.80.1

### Testcase
https://codesandbox.io/s/7wowvv7zpx

**Comment by Grmiade** [comment]
Same problem for Menu, Dropdown components ... and more I suppose :/

**Comment by BlackScarx** [comment]
Yes...

**Comment by eugene1g** [comment]
There is a problem with `@babel/runtime@7.0.0-beta.48`

A temporary fix is to force older version of `@babel/runtime` by adding this to your app `project.json`
```json
"resolutions": {
  "@babel/runtime": "7.0.0-beta.47"
}
```
Related #2831 and #2832

**Comment by layershifter** [comment]
Duplicate, see [#2831#comment](https://github.com/Semantic-Org/Semantic-UI-React/issues/2831#issuecomment-391964493).
