### ISSUE TITLE
Increment prop for Input[number]

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#2843]
## Feature Request
Customize increment for number input

### Problem description
I'm working with tiny numbers, it would be nice if the up/down arrows incremented just 0.00000001 at a time, instead of a whole number.

```
0.00000000
0.00000001
0.00000002
0.00000003
```

Instead of

```
0.00000000
1
2
3

```
This is built in to HTML with `<input type="number" step="0.00000001" value="0.00000000">`

**Comment by layershifter** [comment]
We bypass all unhandled props to the element.

### JSX
```jsx
<Input type="number" step="0.00000001" value="0.00000000" />
```
### Generated HTML
```html
<div class="ui input">
  <input type="number" step="0.00000001" value="0.00000000" />
</div>
```

If you want to have an autocontrolled `Input`, you should use the `defaultValue` prop:

```jsx
<Input type="number" step="0.00000001" defaultValue="0.00000000" />
```

**Comment by ghost** [comment]
Thanks for your help :)
