### ISSUE TITLE
[Modal] Dimmer click not available if the modal is controlled by a reducer 

### ISSUE THREAD

**Issue by devrlonardi** [Semantic-Org/Semantic-UI-React#2846]
## Case
If the modal is controlled by a reducer in a Redux approach, so not through the React component state but by a container, there's no prop from the Modal component to catch the dimmer click and manage it from the container actions.

### Feature
Would be nice to have a prop like "onDimmerClick" to manage the dimmer interaction externally.

### Version
0.80.2

### Testcase
https://codesandbox.io/s/0xml03jjzn

I can make a PR for this if you think is useful.

**Comment by layershifter** [comment]
We already have `onClose` callback, I've updated [codesandbox](https://codesandbox.io/s/lxjqk08vvl).
