### ISSUE TITLE
Dropdown component with big number of options

### ISSUE THREAD

**Issue by dergus** [Semantic-Org/Semantic-UI-React#2847]
I have an issue with `Dropdown` components performance when there are too many options(over 3K in my case). The thing is I don't need to show them all to user at once, just 10 would be enough but I wanna let user to search them all, I've tried to customize the component but failed.
So is it possible to show by default some default options but when user starts typing search in other array of options?

**Comment by guillaumep** [comment]
@dergus I have had the same issue with my app. I have resolved the issue by doing the following. I have a React component that wraps the dropdown, and does the following:

1. get the search input using the onSearchChange() callback, set it to local state;
2. in render(), filter the dropdown options using the search query, and keep at most 10 items.

Something like (its in TypeScript):

```
interface IMyDropDownState {
  searchQuery: string;
}

class MyDropDown extends React.PureComponent<IMyDropDownProps, IMyDropDownState> {
  public state = {
    searchQuery: '',
  };

  public render() {
    const filteredItems = filterDropDownItems(dropdownItems, this.state.searchQuery);
    return (
      <Dropdown
        options={filteredItems}
        onSearchChange={this.onSearchChange}
        value={chargeGroupCode}
       />
    );
  }

  private onSearchChange = (event: React.SyntheticEvent<HTMLElement>, data: DropdownProps) => {
    const { onSearchChange } = this.props;
    const searchQuery = data.searchQuery || '';
    this.setState({
      searchQuery,
    });
  }
}

const filterDropDownItems = (items: DropdownItemProps[], query: string) => {
  // ...
}
```

**Comment by layershifter** [comment]
@guillaumep thanks, it's a working solution, I've made something similar in my project.
