### ISSUE TITLE
Full screen doc examples result in 404

### ISSUE THREAD

**Issue by john-aws** [Semantic-Org/Semantic-UI-React#2848]
### Steps
- using Chrome on Windows 10
- visit https://react.semantic-ui.com/views/statistic
- navigate to any of the examples e.g. 'Statistics Group'
- hover over the example so that top-right buttons are visible
- click the 'Full Screen' button
- browser opens https://react.semantic-ui.com/maximize/types-group

### Expected Result
- a fuller example of the React component

### Actual Result
404
How about some good old Atari?

Chrome devtools shows:

Mixed Content: The page at 'https://react.semantic-ui.com/maximize/types-group' was loaded over HTTPS, but requested an insecure plugin resource 'http://www.pizn.com/swf/classic-asteroids.swf'. This request has been blocked; the content must be served over HTTPS.
VM1690 types-group:1 Mixed Content: The page at 'https://react.semantic-ui.com/maximize/types-group' was loaded over HTTPS, but requested an insecure plugin resource 'http://www.pizn.com/swf/1-space-invaders.swf'. This request has been blocked; the content must be served over HTTPS.

### Version
- current web documentation

**Comment by msrikanth508** [comment]
@john-aws Thanks for reporting, I'm on it.
