### ISSUE TITLE
When using Semantic v > 0.80* and Babel 7 beta - > breaks SSR

### ISSUE THREAD

**Issue by theCuriousOne** [Semantic-Org/Semantic-UI-React#2849]
### Steps
The steps are not straight forward. I use .net core react spa template for my app with server side rendering. rendering.

### Expected Result
Everything to work normally :)

### Actual Result
During the build process, I got an error saying inst.render() (not minified) in ReactPartialRenderer.js (from react-dom) is not a function. Unfortunately it took me 10 hours to figure out that the usage of the babel 7.beta in semantic broke the build. (I use babel-core 6.26.3)

### Version
tested with 0.80.0 it worked ok at first, but strangely, it happened on Friday (25.05) just when the new version was released (0.80.1), the build failed because change in dependencies in 0.80.0. p.s. I keep strict versions in package.json "0.80.0", so no idea how this happended. 

### Testcase
The SSR app works ok when reverted back to version 0.79.1. At the moment I don't have a straight and easy way to test it. Will try it with never versions and report/update the issue back.

**Comment by layershifter** [comment]
The latest version is `0.80.2`, it should work fine. See #2831.
