### ISSUE TITLE
semantic-ui react modal height extending to the height of a page

### ISSUE THREAD

**Issue by sookwei93** [Semantic-Org/Semantic-UI-React#2851]
```
<Modal size="tiny" open={this.state.modelOpen} onClose={this.close}>
    <Modal.Header>Error</Modal.Header>
    <Modal.Content>
           <p>There is an error!</p>
    </Modal.Content>
    <Modal.Actions>
          <Button
              positive
              icon="checkmark"
              labelPosition="right"
              content="OK"
          />
     </Modal.Actions>
</Modal>
```

<img width="1062" alt="screen shot 2018-05-30 at 6 00 50 pm" src="https://user-images.githubusercontent.com/11636254/40713790-6a66e8ce-6433-11e8-9068-676c6effd089.png">

Any idea how to resolve this?

Any help would be appreciated!

**Comment by layershifter** [comment]
Please add steps to reproduce and an example on codesandox. I will reopen issue when it will be filled fully. Also, please check that you're using SUI 2.2, #2550.
