### ISSUE TITLE
Unexpected type errors using future versions of typescript

### ISSUE THREAD

**Issue by traverse** [Semantic-Org/Semantic-UI-React#2856]
## Bug Report

Whilst testing out future typescript releases I ran into some type errors that weren't popping up before.

### Steps
Transpile a project using `typescript` and `semantic-ui-react`.

### Expected Result
Should transpile without problems.

### Actual Result
Receive type errors like the following:

```
ERROR in /Users/User/project/src/Component.tsx(2,10):
TS2305: Module '"/Users/User/project/node_modules/semantic-ui-react/dist/commonjs/index"' has no exported member 'Input'.
```

### Version
* `typescript@insiders` & `typescript@next`
* `semantic-ui-react@0.80.2`

### Testcase
I can't share the code but the issue is basically that typescript isn't finding the type definitions. This can be solved by adding `"types": "index.d.ts"` to the `package.json`.

**Comment by layershifter** [comment]
I used [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript) with `typescript@2.8.4`, then added `semantic-ui-react` and updated the `App`  component to use SUIR. Build and serve worked fine.

`typescript@2.9.1-insiders.20180525` and `typescript@3` don't work. When I added `"types": "index.d.ts",` to `package.json`, build was successfull. @traverse do you want to open a PR?

**Comment by traverse** [comment]
@layershifter I opened a PR, thanks for the quick response. 👍
