### ISSUE TITLE
Stick a container to the bottom aka "Where is the footer component ?"

### ISSUE THREAD

**Issue by AktasC** [Semantic-Org/Semantic-UI-React#2858]
Hello world,

So I've seen this question asked very often since 2014 and still no Footer component.
I expect you to yell "USE FLEXBOX AND [THIS LINK](https://github.com/philipwalton/solved-by-flexbox/blob/master/demos/sticky-footer.md) !" but that's not working for me.

So please, is there any way I can stick my custom Footer component to the damn bottom of my webpage ?
On a populated page it's not noticeable but on a 404 or "contact us" page it's sticking to the last component's border.

It would be awesome to finaly get rid of that problem, I've already tried applying a style but semantic just overrides it.

**Comment by layershifter** [comment]
I think that we don't need such add-on because it's too specific and can be implemented with basic CSS.

https://css-tricks.com/couple-takes-sticky-footer/

**Comment by annjawn** [comment]
It becomes a lot more tricky when using Grids in a component. Using a container with `100vh` or `100%` min height stretches the grid rows and messes up the layout. I am facing the same issue as @AktasC. things go wrong especially when there's not much content on the page, if we use traditional method the footer just sticks to the bottom of the last component (which is perhaps a Grid) and if we use the min-height `100vh` or `100%` Grid flexbox stretches and also stretches the content in it (even when the grid doesn't have `stretched` prop on the columns). I don't know how easy it is to achieve but the layout examples also suffer from this exact issue (just take out the filler contents and see what happens to the footer).
