### ISSUE TITLE
Reorder dropdown selections in multiple mode

### ISSUE THREAD

**Issue by LrsK** [Semantic-Org/Semantic-UI-React#2860]
### Problem description
When you have a Dropdown component that can have multiple selections, it would be nice to be able to reorder the selections after they have been selected.
https://codesandbox.io/s/v8ymm36wwy

### Proposed solution
One way to solve this would be to make the selections draggable so you can drop them to where you want them.

**Comment by layershifter** [comment]
We don't want to ship such complicated features in v1. I also think that this feature is overkill for `Dropdown` component, possible it can be implement as addon.

Feel free to submit PR for this feature.
