### ISSUE TITLE
TextArea font is incorrect

### ISSUE THREAD

**Issue by zholmes1** [Semantic-Org/Semantic-UI-React#2864]
## Bug Report
TextArea font falls back to sans serif.

### Steps
Put a `TextArea` or `Form.TextArea` anywhere in a component.

### Expected Result
Font consistent with the rest of the app.

### Actual Result
Font is default sans serif. 💣

### Version
0.80.2

**Comment by kierenj** [comment]
could I ask why this was closed? experiencing this same issue

**Comment by zholmes1** [comment]
Shouldn't be closed. It's still an issue. In every TextArea, I need to
manually set the font to my theme's font.

**Comment by layershifter** [comment]
`Textarea` works correctly only inside `Form`.
