### ISSUE TITLE
Weird looking docs

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI-React#2865]
### Problem description
What is this strange new "feature" in the docs - that I have to -hover- over a section to see normally the look of the component? Everything else is opaque-ed

### Proposed solution
Could you please revert to the old scheme? When everything was visible instantly - so I could scan for the needed component layout w\o having to hover over each and every variant availble?

**Comment by levithomason** [comment]
Agreed.  See #2866.
