### ISSUE TITLE
Module not found: Can't resolve '/node_modules/semantic-ui-react/dist/es/lib/eventStack'

### ISSUE THREAD

**Issue by pbechliv-zz** [Semantic-Org/Semantic-UI-React#2868]
### Steps
Using react-scripts start script

### Expected Result
It should compile succesfully

### Actual Result
I get the following compile error:
Failed to compile.

./node_modules/semantic-ui-react/dist/es/lib/eventStack/index.js
Module not found: Can't resolve './EventStack' in '/home/panos/myfolder/node_modules/semantic-ui-react/dist/es/lib/eventStack'

### Version
0.81.0

### Testcase
https://codesandbox.io/s/52ok1j4j3k

**Comment by mironal** [comment]
duplicate #2867
