### ISSUE TITLE
Why Grid need a margin-top: -1rem; style ?

### ISSUE THREAD

**Issue by hh54188** [Semantic-Org/Semantic-UI-React#2872]
I find Grid component have this style: 

```
.ui.grid {
    margin-top: -1rem;
    margin-bottom: -1rem;
    margin-left: -1rem;
    margin-right: -1rem;
}
```
The `margin-top: -1rem` style seems pull Grid out of the top screen, why do that ?

**Comment by layershifter** [comment]
Please address CSS related questions to the main repo: https://github.com/Semantic-Org/Semantic-UI
We're working on the CSS-in-JS solution, please follow: https://github.com/levithomason/stardust
