### ISSUE TITLE
Modal:  `dimmer={false}` stops the modal from opening

### ISSUE THREAD

**Issue by mihai-dinculescu** [Semantic-Org/Semantic-UI-React#2873]
### Steps
A Modal with `dimmer={false}`.

### Expected Result
The modal opens.

### Actual Result
The modal doesn't open. This can be observed in the docs.

### Version
0.81.1

### Testcase
https://react.semantic-ui.com/modules/modal#variations-dimmer
https://react.semantic-ui.com/modules/modal#types-multiple

**Comment by Xecutor** [comment]
It's actually opening. But it's at the bottom of the page, under all other content.

**Comment by layershifter** [comment]
As I see, a `Modal` component is not longer usable without a dimmer. Can anybode confirm this?

**Comment by mihai-dinculescu** [comment]
This is caused by Semantic CSS 2.3. Without a dimmer, it is no longer able to figure out the position of the modal.

Looking at https://github.com/Semantic-Org/Semantic-UI/releases, I've noticed:

> A Special Message about Flex Modals
> 
> There will be an update shortly to resolve issues related to flex modals when using multiple modals and detachable: false, in order to not hold up this release, we've decided to move forward without a fix.
> 
> A general solution will most likely require branching code for IE11 which will disable flex (as IE11 doesnt correctly implement the latest spec for absolute positioned flex containers).

**Comment by layershifter** [comment]
It seems, that need update the `Modal`s code, it doesn't accept `boolean`s now.
