### ISSUE TITLE
Modal: add `dimmer` shorthand

### ISSUE THREAD

**Issue by edvardsk** [Semantic-Org/Semantic-UI-React#2877]
## Feature Request
Modal portal class name option or any other possibility to style modals container.

### Problem description
Right now there is no possibility to style default `.modals` portal via modal component. It is a big limitation, that reduce flexibility of the modal usage. The only one way to do it right now - it is overriding `mountNode`. But it is unnecessary and redundant in most cases.

### Proposed solution
It will be great to have some prop in modal component, that will give possibility to add class to parent portal, something like `portalClassName`.

**Comment by layershifter** [comment]
In fact, this can be done with #1739. However, there wasn't many activity. Will be easier to implement after #2880 will be merged.
