### ISSUE TITLE
Font Awesome 5 adoption

### ISSUE THREAD

**Issue by Ne-Ne** [Semantic-Org/Semantic-UI-React#2878]
### Problem description
As a semantic ui user for react. I cannot use the latest font awesome v5 icons, including multiple font-weights.

### Proposed solution
Update to latest package to absorb all the new icons.

Looking at the SUI documentation this would require all the icon names to re-written or a change in strategy.

What are the opinions on this?

**Comment by layershifter** [comment]
https://react.semantic-ui.com/elements/icon

We use FontAwesome from `semantic-ui-react@0.81.0` that contains update to SUI 2.3. Please clarify your needs.

**Comment by Ne-Ne** [comment]
Sorry for the delay.

Initially I misread the docs. However now I do require the latest font awesome package.

**Comment by oleksandrkyselov** [comment]
It would be great to have the latest version of Font Awesome!  👍
