### ISSUE TITLE
Link labels to their corresponding fields

### ISSUE THREAD

**Issue by ThiefMaster** [Semantic-Org/Semantic-UI-React#2881]
### Problem description
Labels and form fields are not linked. This is not very good UX since generally clicking on the label should focus the form field it belongs to.

### Proposed solution
When using `<Form.Field>` the label should either surround the field's element (in that case linking is done automatically by the browser), which currently results in different margins between label and field, so probably not a good option, or a `for` attribute should be set to a random/unique ID that is also set as an ID on the field.

---

Of course it's already possible to do something like this manually, but it's quite messy since it involves using refs or keeping some external state (which IDs were already generated in case of incrementing instead of random IDs)

**Comment by layershifter** [comment]
I think that you are looking for [this example](https://react.semantic-ui.com/collections/form#shorthand-field-control-id). Random IDs a bad idea, see also #980 for more details.

**Comment by ThiefMaster** [comment]
That's already nice but doesn't help much when not using the shorthand (e.g. to show some more verbose description text for a field below it).

Also I still need to pick an ID that is globally unique, which generally results in components that can't be re-used more than once on the same page (even though reusing the same form twice is probably a rare case)

**Comment by layershifter** [comment]
I'm going to close this issue, my opinion is that we don't need to implement this in SUIR. Sometime ago, there was same discussion, #980.

Possible, @levithomason has another opinion.
