### ISSUE TITLE
Dropdown: multiple search selection dropdown won't close when clicking the search input for second time

### ISSUE THREAD

**Issue by GuyShaanan** [Semantic-Org/Semantic-UI-React#2887]
### Steps
1. Go to https://react.semantic-ui.com/modules/dropdown#types-multiple-search-selection
2. Click on the "State" placeholder to open the dropdown.
3. When opened, click again (once) on the "State" placeholder.

### Expected Result
When clicking outside of the dropdown, the dropdown should close.

### Actual Result
The dropdown doesn't close.
If you skip step (3) above, the dropdown closes as expected

### Version
0.81.1

**Comment by levithomason** [comment]
I was working on a related issue the other day and ran out of time.  I think we need to:

1. Completely remove the `handleClose` method in the Dropdown.
1. Move event sub/unsub calls `attachHandlersOn*` where `*` is the event or action.  Example, we have `attachHandlersOnOpen`, but not for close, focus, blur, etc.
1. Update sub/unsub calls to instead call the appropriate `attachHandlersOn*` method.

When I was testing this locally, removing `handleClose` and consolidating our sub/unsub calls seemed to resolve past and present open/close/focus/blur bugs.

Possibly related: #2744

**Comment by GuyShaanan** [comment]
Thanks.
I just wanted to point out another use-case (more common):
Instead of step (3) you can select an option and then remove it (by clicking its x). Same behavior.

Is there a manual workaround I can implement in JS?

**Comment by siarheipashkevich** [comment]
Hi, I've the same issue.

**Comment by krnkl** [comment]
>  just wanted to point out another use-case (more common):
Instead of step (3) you can select an option and then remove it (by clicking its x). Same behavior.

@GuyShaanan this was fixed in 0.82.2

Regarding what was initially described in bug report,  second click on "State" misses input element and input becomes not in focus anymore. 
Multiple search selection sets `width: 2.2em` for input element, so its easy to miss it.

**Comment by GuyShaanan** [comment]
@krnkl Can confirm it works in 0.82.2.
Thanks!

**Comment by layershifter** [comment]
Confirmed, works fine in the latest.
