### ISSUE TITLE
Modal error when open in Safari

### ISSUE THREAD

**Issue by namcoder** [Semantic-Org/Semantic-UI-React#2889]
Hi. I have tested in Chrome and Safari. In Chrome the Modal works fine but got error in Safari.
![screen shot 2018-06-07 at 4 55 40 pm](https://user-images.githubusercontent.com/8687083/41092838-fe65583a-6a73-11e8-86d5-ae3024bc9d96.png)

Error appear when the "open" attribute is true . I also tested in https://react.semantic-ui.com/modules/modal

Please take a look. Thank you

**Comment by layershifter** [comment]
Looks like duplicate of #2886.
