### ISSUE TITLE
Modal: scrolling issue with `top aligned`

### ISSUE THREAD

**Issue by ak1394** [Semantic-Org/Semantic-UI-React#2891]
### Steps

1. Go to [Top Aligned Modal demo](https://react.semantic-ui.com/modules/modal#types-top-aligned) and open modal by clicking on "Show Modal" button.

2. Start resizing browser window to a smaller size so that the window height is slightly less then a height of a modal.

3. Observe that its possible to resize window that is hides a lower part of a modal, and no scroll bars are displayed. This doesn't happen to modals without centered={false} setting.

### Expected Result

Vertical scrollbar should be displayed, when bottom of the modal is obscured.

### Actual Result

Scroll bar is not displayed, and its impossible to reveal obscured bottom part of the modal by scrolling.

### Version

0.81.1

**Comment by layershifter** [comment]
![image](https://user-images.githubusercontent.com/14183168/42511055-84485b38-8459-11e8-905e-00e61e9d12ce.png)

I am not able to reproduce. Please check again, if issue is reproduced, please add browser version. I will reopen, if will receive a valid follow up.

**Comment by ak1394** [comment]
Its Chrome v67.0.3396.99. I think in your case the window is a bit too small, if you slowly resize window by dragging it with the mouse, gradually increasing it's height, you should be able to observe the buggy behaviour. 

For example: small window, scroll bar appears:

![image](https://user-images.githubusercontent.com/148276/42511845-e64b5e70-844a-11e8-8abf-c7e5631e21e4.png)

Slightly taller window (but not tall enough to fit the contents), no scroll bar:

![image](https://user-images.githubusercontent.com/148276/42511882-fc78414a-844a-11e8-930c-67f0db265033.png)

**Comment by layershifter** [comment]
Thanks 👍 As I see that the issue has a same place as #2221, however I will reopen this issue.

**Comment by ak1394** [comment]
Thanks!
