### ISSUE TITLE
Modal closing is handled inconsistently

### ISSUE THREAD

**Issue by jscheel** [Semantic-Org/Semantic-UI-React#2892]
If you defines actions via shorthand, the modal will close automatically when the action buttons are clicked However, if you want to define rich content in the modal (instead of simple text via the text prop), you have to define the children, and cannot use the actions shorthand. This means you need to define the actions via the `Modal.Actions` component. However, actions defined this way do not automatically close the modal when clicked. This means you must create a controlled modal for any case where you want to define more than simple text content. I realize that I can send a component to the content prop, but that starts to get pretty messy.

**Reproducible test case**: https://codesandbox.io/s/20p1n92rjr

**Closes Automatically**
```
<Modal content="Close this?" actions={[{key: 'ok', content: 'Ok', positive: true}, {key: 'cancel content: 'Cancel positive: false}]} />
```

**Won't Close Automatically**
```
<Modal>
  <Modal.Content>
    Close this?
  </Modal.Content>
  <Modal.Actions actions={[{key: 'ok', content: 'Ok', positive: true}, {key: 'cancel', content: 'Cancel', positive: false}]}
</Modal>
```

Possible solution would be to pass a close callback into the data object that is passed to `onActionClick`.

Version 0.81.1

**Comment by layershifter** [comment]
You cannot use shorthand API and children API simultaneously in such manner. It's the expected behavior.

The shorthand API is powerful and allows complex markup:
```jsx
<Modal content={{ className: 'foo', content: <div>complex</div>, anotherProp: true }} />
```

**Comment by jscheel** [comment]
@layershifter I understand that mixing them is not good, but the issue still stands. The actual functional behavior is different between the shorthand and child api. Shorthand closes the modal automatically when clicking a button, child api does not. Instead, you _must_ control the modal open prop yourself currently.

**Comment by layershifter** [comment]
> Shorthand closes the modal automatically when clicking a button, child api does not.

You're describing the correct behavior.

We cannot handle everything, if you need something really complicated use children API and control your state manually. We also should rework `Modal` docs, they aren't clear and quite wrong :cry:
