### ISSUE TITLE
Input "type=number" returns a value of type string

### ISSUE THREAD

**Issue by jeemok** [Semantic-Org/Semantic-UI-React#2894]
### Steps
```
<Input type="number" onChange={(event, data) => console.log(data)} />
```

### Expected Result
`{ type: 'number', value: 3 }`

### Actual Result
`{ type: 'number', value: '3' }`

### Version
all

### Testcase
https://codesandbox.io/s/znkq9qr71m

**Comment by layershifter** [comment]
It's not a bug, native inputs returns value as string, too. I'm sure that we don't to fix this.

```jsx
<input type="number" onChange={(e) => console.log(e.target.value, typeof e.target.value)} />
```
