### ISSUE TITLE
Cannot get ref to Modal.

### ISSUE THREAD

**Issue by searene** [Semantic-Org/Semantic-UI-React#2895]
## Bug Report
Cannot get ref to `Modal` using `Ref`.

### Steps
Here is the sample code.

```jsx
class App extends Component {
  componentDidMount() {
    console.log(this.ref); // null
  }
  render() {
    return (
      <div>
        <Ref innerRef={(ref) => this.ref = ref}>
          <Modal open={true}>
            <div>
              This is App
            </div>
          </Modal>
        </Ref>
      </div>
    );
  }
}
```

### Expected Result
non-null ref should be printed on the console

### Actual Result
the console shows `null`

### Version
0.81.1

### Testcase
https://codesandbox.io/s/q9oyyrro44

**Comment by layershifter** [comment]
`Modal` is rendered with another API directly to `document.body`, so there is no bug.

The easiest way is a capture ref from child node of `Modal`:
```
<Modal open={true}>
  <div ref={yourRefHandler}>This is App</div>
</Modal>
```

**Comment by searene** [comment]
@layershifter Thanks for your reply. But your code doesn't work for me.

Here is my code: https://codesandbox.io/s/1ppjj7r8j

Also, what if it's a `Segment` instead of `div`? I cannot even use `ref` in this case.

```jsx
<Modal open={true}>
  <Segment>
    This is SimpleComponent
  </Segment>
</Modal>
```

**Comment by layershifter** [comment]
I've updated example: https://codesandbox.io/s/6xqo6mj0zw

---

You can't get ref in `componentDidMount()` because a `Modal` content will be mounted later.
