### ISSUE TITLE
Some icons are not appearing while others render normally

### ISSUE THREAD

**Issue by anasshad** [Semantic-Org/Semantic-UI-React#2898]
## Bug Report
Some icons are not appearing like the social icons facebook, twitter, linkedIn, etc. Among others, the pencil icon is also not rendering.

### Steps
A clear and concise description of steps to reproduce the problem.

### Expected Result
The icon should render

### Actual Result
Empty square renders 💣

### Version
0.79.1

**Comment by mihai-dinculescu** [comment]
When submitting bug reports it is highly recommended to provide a pen (by forking and updating https://codesandbox.io/s/2l3n74j9y).

I've just done that for you: https://codesandbox.io/s/llyvk617wl. As you can notice, the icons show up okay.

I suspect that you've upgraded to semantic-ui 2.3. semantic-ui-react started supporting semantic-ui 2.3 only with version 0.80. You can either **upgrade** semantic-ui-react, or **downgrade** semantic-ui.
