### ISSUE TITLE
Grey Inverted Button missing CSS color: '#767676'

### ISSUE THREAD

**Issue by hufftheweevil** [Semantic-Org/Semantic-UI-React#2899]
### Steps
Create a grey, inverted button.

### Expected Result
A white button with a grey outline and grey text.

### Actual Result
A white button with a grey outline, but white text

### Version
0.81.1

### Testcase
https://codesandbox.io/s/91zpq1076y

**Comment by layershifter** [comment]
As I remember it's required to have an `inverted` parent: https://codesandbox.io/s/mq195o96v8
However, it's better to create a CSS related issues in main repo: https://github.com/Semantic-Org/Semantic-UI
