### ISSUE TITLE
No exported members after Typescript upgrade to 2.9.1

### ISSUE THREAD

**Issue by Jefski14** [Semantic-Org/Semantic-UI-React#2903]
## Bug Report
There seems to bee a compatibility issue with the typescript definitions of semantic-ui-react 0.81.1 and typescript 2.9.1

### Steps
1. Use Typescript 2.9.1 in a semantic-ui-react project
2. Import a semantic component like usual
```import {Button, Icon} from 'semantic-ui-react' ```
### Expected Result
No errors like before

### Actual Result
```[ts] Module '"c:/path_to_project_folder/node_modules/semantic-ui-react/dist/commonjs/index"' has no exported member 'Icon'.```
Typescript Errors
### Version
Semantic-UI-React: 0.81.1
Typescript: 2.9.1
 VSCode: 1.24.0

###
I found this related issue on the typescript git: 
[https://github.com/Microsoft/vscode/issues/51343](url)

**Comment by layershifter** [comment]
This was fixed in `0.81.1` (#2856, #2857). Will check again.

**Comment by Jefski14** [comment]
Oh you're right. I forgot to restart vscode after upgrading semantic from 0.80.1 to 0.81.1 :see_no_evil:
Sorry for wasting your time on that.
