### ISSUE TITLE
Dropdowns misbehave when inside Popups

### ISSUE THREAD

**Issue by pferreir** [Semantic-Org/Semantic-UI-React#2905]
### Steps
1. Place a `<Dropdown />` inside a `<Popup />`, with a `<Button />` as trigger
2. Click the button (pop-up should open)
3. Click outside the pop-up (it should close itself)
4. Open the pop-up again
5. Open the dropdown
6. Click outside the pop-up

### Expected Result
The pop-up should close.

### Actual Result
The pop-up stays open. Only the dropdown closes. Clicking again outside will leave the pop-up open. The only way to close it is to click the button again.

### Version
0.81.1

### Testcase
https://codepen.io/anon/pen/QxvpNe

**Comment by milkersarac** [comment]
@pferreir I hit a similar bug. My popup had `on="click` prop which prevented popup to close when clicked outside if any dropdowns had been interacted. As a temporary solution I removed `on="click"` prop and made my popup hoverable by adding `hoverable={true}`.

**Comment by mic4ael** [comment]
I see the example from the issue is not working right now so here is a working one: https://codepen.io/anon/pen/vaBgrN And by the way, the first version in which the bug appears is: **0.81.0**

**Comment by mic4ael** [comment]
@milkers a possible solution to that would be to pass `eventPool`  e.g. set to `testing` as a property of the `Popup`. I am still to find if there is more to that (if there is an actual bug).

**Comment by mic4ael** [comment]
I think there is a bug which causes the appropriate handlers of the `Popup` to be overridden by the ones provided by `Dropdown` if they are not in separate event pools.
