### ISSUE TITLE
Dropdown grouped with a Button

### ISSUE THREAD

**Issue by RuslanPopchef** [Semantic-Org/Semantic-UI-React#2906]
I would like to group a Dropdown with a Button with an attachment between them.
I did read this issue : https://github.com/Semantic-Org/Semantic-UI/issues/2286

But I don't understand how can I make it work with `action` on `Input`.

Best result I have is this :

```jsx
<Input fluid action>
  <input style={{display: 'none'}} />
  <Dropdown selection fluid options={[{key: 1, value: 1, text:"test"}]} />
  <Button icon="save" />
</Input>
```

Which loses border-radius on the left side of the Dropdown but provides the correct attachement between a Dropdown and a Button.

Could someone please provide an example on how to have a dropdown grouped with a button inline ?

**Comment by layershifter** [comment]
Please use StackOverflow for usage questions. 

----

I've made an example below:

```jsx
import React from 'react'
import { Button, Dropdown, Label, Icon } from 'semantic-ui-react'

const options = [
  { key: 'edit', icon: 'edit', text: 'Edit Post', value: 'edit' },
  { key: 'delete', icon: 'delete', text: 'Remove Post', value: 'delete' },
  { key: 'hide', icon: 'hide', text: 'Hide Post', value: 'hide' },
]

const DropdownExampleFloating = () => (
  <Button as='div' labelPosition='left'>
    <Dropdown defaultValue='hide' options={options} selection className='label' />
    <Button>Search</Button>
  </Button>
)

export default DropdownExampleFloating
```
