### ISSUE TITLE
<Portal/> and new context API

### ISSUE THREAD

**Issue by kserjey** [Semantic-Org/Semantic-UI-React#2910]
### Steps
Just try to use new context API.
The problem is caused by using `unstable_renderSubtreeIntoContainer` function (facebook/react#12493).

### Expected Result
Access to context value.

### Actual Result
Context value is `undefined`.

### Version
0.81.1

### Testcase
https://codesandbox.io/s/3r9nkpk1z5

P.S. Can I help with this issue? I have no experience in contributing, but I'd really like to try...

**Comment by layershifter** [comment]
Thanks for the detailed report, will be fixed by #2880.

**Comment by kserjey** [comment]
Cool! :+1:
