### ISSUE TITLE
Getting "lint-staged requires at least version 6 of Node, please upgrade" with Node 10

### ISSUE THREAD

**Issue by zentuit** [Semantic-Org/Semantic-UI-React#2911]
I'm trying to commit some changes for a (possible) PR, but I can't commit due to the pre-commit script running `lint-staged` which gives me this error:

```
husky > npm run -s precommit (node v10.1.0)

lint-staged requires at least version 6 of Node, please upgrade

husky > pre-commit hook failed (add --no-verify to bypass)
```
I didn't want to do a `--no-verify` in case I'm missing something.

Is there something I should be doing after forking the project?

**Comment by layershifter** [comment]
Thanks, related to okonet/lint-staged#432, PR is comming.

**Comment by layershifter** [comment]
Please grab the latest changes from `master`, should work fine now.
