### ISSUE TITLE
Icon name 'credit card outline' outputs a warning

### ISSUE THREAD

**Issue by bruncs** [Semantic-Org/Semantic-UI-React#2915]
## Bug Report
I'm trying to use the 'credit card outline' icon and it displays correctly, but it outputs a warning message to the browser console.

![icon warning](https://user-images.githubusercontent.com/17730878/41401337-f5709ace-6f95-11e8-833c-82ea6a201e5f.PNG)

### Version
0.81.1

**Comment by layershifter** [comment]
Tested locally with SUIR `0.81.1` and SUI `2.3.1`, there is no warning. `credit card outline` is in [SUI.js](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.81.1/src/lib/SUI.js#L1208) definitions of matching version.

Please ensure that you're running SUIR `0.81.1`, i.e. try to reinstall deps with Yarn. If issue will still persist, please create a repro repo.
