### ISSUE TITLE
Modal Error: Attempted to assign to readonly property

### ISSUE THREAD

**Issue by xueyongg** [Semantic-Org/Semantic-UI-React#2917]
### Steps
Implement a modal component from Semantic-UI-React. 
Run it on localhost. 
Open that modal on your mobile phone. Iphone 6s was used.

### Expected Result

Modal.Content content should appear.

### Actual Result
The actual result that happened 💣

TypeError: Attempted to assign to readonly property. 
Error occurs in Portal.js line 297

_this.rootNode.style = style || ''; // when re-rendering, first remove listeners before re-adding them to the new node_

### Version
Added into the application through CDN:
<link
            href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.css"
            rel="stylesheet"
          />
2.3.1 

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

![screen shot 2018-06-15 at 1 23 01 am](https://user-images.githubusercontent.com/11015221/41427812-ad53cc20-703a-11e8-8467-709ca4bd3882.png)

**Comment by layershifter** [comment]
Duplicate #2886.

**Comment by nelsondaza** [comment]
Having the same issue in 0.81.1 and 0.81.0.
Rolling back to 0.80.2 fixes it.
