### ISSUE TITLE
Multiple Modal's Not Showing in Docs

### ISSUE THREAD

**Issue by amerryma** [Semantic-Org/Semantic-UI-React#2920]
### Steps
* Go to https://react.semantic-ui.com/modules/modal#types-multiple
* Attempt to open multiple modals using the buttons

### Expected Result
Should open multiple modals.

### Actual Result
The first modal pops up, but not the next one.

### Version
Semantic UI - 2.3.2
Semantic UI React - 0.81.1

**Comment by amerryma** [comment]
### Testcase
I did see it working here in my sandbox
https://codesandbox.io/s/mjk81v83lp

So I'm having trouble understanding why it is not working in the docs.

**Comment by layershifter** [comment]
Was fixed in #2882, but was not released yet. Thanks for detailed report 👍
