### ISSUE TITLE
Dropdown: do not close when clicked in succession

### ISSUE THREAD

**Issue by jamesjryan** [Semantic-Org/Semantic-UI-React#2921]
### Steps
Please see https://codesandbox.io/s/42063j6q39

1. Click Messages 1, click messages 2, click messages 1 again. Messages 2 Dropdown will be stuck open.
2. Change semantic-ui-react version to 0.80.2, repeat step 1, bug cannot be reproduced.
3. Change semantic-ui-react version back to 0.81.1, repeat step 1, bug can again be reproduced.

### Expected Result
Dropdown menus close when clicking on another.

### Actual Result
Open dropdown menu get stuck open on version 0.81.1

### Version
0.81.1 is definitely affected.
0.80.2 is not affected.

Please note - 0.81.0 doesn't seem to work in the sandbox - not sure if this version was ever released to npm. 

The regression is somewhere between 0.80.2 and 0.81.1 releases.

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/42063j6q39

**Comment by levithomason** [comment]
Note, we do not support auto controlled state when using `Dropdown.Menu` as a child.  You'll need to control your own state.

That said, I'll leave this issue open as there were a number of Dropdown issues related to the last release.

**Comment by karlludwigweise** [comment]
This problem also occurs, if you delete all values of a multiple Dropdown and then jump to the next one. (in 0.81.1)

**Comment by giancorzo** [comment]
The problem also happens in version 0.81.0

**Comment by layershifter** [comment]
Feel free to submit PR with fix 👍

**Comment by levithomason** [comment]
I've created a simplified example.  This one uses the supported `options` prop and does not involve a menu or pointing dropdowns.  The bug still exists with minimal dropdowns.

It seems every other dropdown that is clicked does not fire the close handler:

https://codesandbox.io/s/lrv3k0z3vm


![http://g.recordit.co/dwTvAo5mty.gif](http://g.recordit.co/dwTvAo5mty.gif)

There is probably a bug in the EventStack or we are stopping some event from propagating when the dropdown is clicked.

**Comment by msrikanth508** [comment]
I'm on it, will submit PR.

**Comment by mic4ael** [comment]
Checked locally and that one should be fixed by https://github.com/Semantic-Org/Semantic-UI-React/pull/2992
