### ISSUE TITLE
Unable to control <Icon> size when used within a <Step>

### ISSUE THREAD

**Issue by phillipncraig** [Semantic-Org/Semantic-UI-React#2922]
## Bug Report
Unable to control the size of an Icon when used within a Step, suspect the Step sizing is being assigned as default to the icon as well. 

Is it possible to have the Icon defined sizing override the Step set default when specified?

### Steps

                <Step.Group size='large'>
                  <Step>            
                    <Icon name='truck' size='mini' />
                    <Step.Content>
                      <Step.Title>Investment</Step.Title>
                    </Step.Content>
                  </Step>
                <Step.Group />

### Expected Result

Expect the Icon sizing to be 'mini'.

### Actual Result

Icon sizing is 'large' (suspect inherited as default from parent Step.Group class).

### Version
0.78.3

**Comment by levithomason** [comment]
This is currently a limitation of the CSS.  Changes to CSS should happen at https://github.com/Semantic-Org/Semantic-UI.
