### ISSUE TITLE
Modals not centered on screen

### ISSUE THREAD

**Issue by larrysharette** [Semantic-Org/Semantic-UI-React#2924]
## Bug Report
When using the default Modal settings, it appears in the top left side of the screen.

I was able to fix this by removing display: block!important; from .transition.visibility class in css.

### Steps
Just add a modal to a component

### Expected Result
The modal to be centered on the screen

### Actual Result
Top left of the screen and 

### Version
"semantic-ui-css": "^2.3.1",
"semantic-ui-react": "^0.79.1"

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by brianespinosa** [comment]
@larrysharette please update to the latest version of SUIR if you are going to use the 2.3.x version of the SUI CSS.

**Comment by larrysharette** [comment]
Fixed. Thank you
