### ISSUE TITLE
Regression - Modal with no dimmer placed at bottom of page on left side

### ISSUE THREAD

**Issue by bmoquist** [Semantic-Org/Semantic-UI-React#2927]
## Bug Report
Found while upgrading from 0.80.2 to 0.81.1 (and semantic-ui 2.3.2).

### Steps
1. Go to https://react.semantic-ui.com/modules/modal#variations-dimmer
2. Click on the 'None' variation in the Dimmer Variation section of the Modal docs.
3. The modal does not appear as expected. It is located at the very bottom of the page and left aligned.

### Expected Result
The modal should appear in a similar location as the modals that have their dimmers turned on. It should be centered and visible without the dimmer present.

### Actual Result
The modal is at the end of the page below the "This is the bottom" message and aligned to the left.

### Version
0.81.1 

### Testcase
https://react.semantic-ui.com/modules/modal#variations-dimmer

**Comment by layershifter** [comment]
Duplicate #2873, see #2882 for more details.
