### ISSUE TITLE
Raised Cards with OnClick appears blue

### ISSUE THREAD

**Issue by ericyoondotcom** [Semantic-Org/Semantic-UI-React#2930]
## Bug Report

On the docs, cards are structured as so:
```
<Card>
  <Card.Content>
    Card.Header, Card.Meta, Card.Description, etc
  <Card.Content>
</Card>
```
When a card has an onClick event and is not structured in the above format, the content turns blue (as it is rendered as an `a` tag).

### Steps
Refer to Testcase code.

### Expected Result
The cards should render as usual with no `a` tag formatting.

### Actual Result
Default link formatting was applied to the Card content, turning it blue.

### Version
0.81.1

### Testcase
https://81qq1n4mvl.codesandbox.io/

**Comment by layershifter** [comment]
In fact it's the required markup for correct display, that's why we changing the tag to `a`, [example](https://react.semantic-ui.com/views/card#content-link-card). However, you can easily override it 🔨 

```jsx
<Card href='#card-example-link-card'>Foo</Card>
<Card as='div' href='#card-example-link-card'>Foo</Card>
```

```html
<a class="ui card" href="#card-example-link-card">Foo</a>
<div class="ui card" href="#card-example-link-card">Foo</div>
```
