### ISSUE TITLE
Checkbox: Return key is not processed

### ISSUE THREAD

**Issue by soulman-is-good** [Semantic-Org/Semantic-UI-React#2931]
## Bug Report

Judging by https://semantic-ui.com/modules/checkbox.html
Checkbox should have possibility to toggle with <kbd>Space</kbd> **and** <kbd>Return</kbd> keys

### Steps
1) Open react demo page https://react.semantic-ui.com/modules/checkbox
2) Navigate to any semantic ui checkbox
3) Press <kbd>Return</kbd> key

### Expected Result
Tick toggled

### Actual Result
Nothing happens

### Version
0.81.1

### Testcase
on the demo page

**Comment by layershifter** [comment]
Thanks for detailed report, but it's a duplicate #2587, we have also PR there #2748.

Help is highly appreciated 🐱
