### ISSUE TITLE
Loader on Table.Tbody

### ISSUE THREAD

**Issue by supersnager** [Semantic-Org/Semantic-UI-React#2933]
Hi, 
is it possible to insert Loader to act as overlay only on Table.Tbody (not on entire table)?

**Comment by layershifter** [comment]
This hehaviour can be reached with `Dimmer`:
https://codesandbox.io/s/wopl0yw3r7

**Comment by nitzel** [comment]
If you put the `<Dimmer>` inside a `<Table.Cell>` instead of directly in a `<Table.Row>` the error goes away. To avoid an empty row at the top you could put the `<Dimmer>` inside a row with actual content.
https://codesandbox.io/s/8lkmjoop2j

This won't work with `<Table collapsing>` though :(
