### ISSUE TITLE
Popup content keeps rendering

### ISSUE THREAD

**Issue by honzajerabek** [Semantic-Org/Semantic-UI-React#2943]
### Steps

1. Place a `<Popup />`
2. `console.log` the render of the `Popup`'s content
3. Trigger the `Popup`
4. Watch console - infinite renders, while the `Popup` is triggered

### Expected Result
Render component only when it's required and necessary

### Actual Result
Infinite number of renders

### Version
0.81.1

### Testcase
https://codesandbox.io/s/8kxxwjm3ol

note - the forked `codesandbox` was originally 0.75.x which was working as expected. After I changed version to 0.81.1, the bug came up as described

**Comment by miroslavstastny** [comment]
Caused by https://github.com/Semantic-Org/Semantic-UI-React/pull/2775?

**Comment by honzajerabek** [comment]
Very likely so, `semantic-ui-react@80.0.0` still works, #2775 was released in `80.0.1` which doesn't
