### ISSUE TITLE
Segment disabled not passed to child dropdown

### ISSUE THREAD

**Issue by wondersteve** [Semantic-Org/Semantic-UI-React#2949]
## Bug Report
(may be similar to https://github.com/Semantic-Org/Semantic-UI-React/issues/2801 )

### Steps
Create a `<Segment disabled>` with `<Dropdown> `child

### Expected Result
The child is disabled

### Actual Result
The child is grayed-out, yet still interactable

### Version
0.81.1

### Testcase
https://codesandbox.io/s/j3701k54zw

**Comment by levithomason** [comment]
This won't be supported since we'd need to pass disabled down to all child components.  That would require using context.

The disabled style is applied to all children because of the cascading nature of CSS.  However, you'll need to pass the disabled prop to the Dropdown to disable it.

**Comment by levithomason** [comment]
This case is a little different than #2801.  In that case, the parent receiving the disabled prop wasn't correctly passing it to a child that it owned in its render function.
