### ISSUE TITLE
Reunion Island flag

### ISSUE THREAD

**Issue by lapwil** [Semantic-Org/Semantic-UI-React#2950]
## Bug Report
The Reunion Island Flag is wrong

### Steps
When trying to display the Reunion Island's flag the French one is displayed, but Guyana, Martinique, Guadeloupe have their own.

### Expected Result
The result that you expected.
![image](https://user-images.githubusercontent.com/10071994/41912216-561ea3f8-794f-11e8-8ad8-34136f230811.png)

### Actual Result
The actual result that happened 💣
![image](https://user-images.githubusercontent.com/10071994/41912228-60da5102-794f-11e8-9c7c-123df5913695.png)

### Version
0.81.2

**Comment by layershifter** [comment]
Please post this there: https://github.com/Semantic-Org/Semantic-UI
We use SUI's CSS now.
