### ISSUE TITLE
Form.Select under Form.Group ignores width parameter.

### ISSUE THREAD

**Issue by AltruXeno** [Semantic-Org/Semantic-UI-React#2951]
### Steps
I have text fields and a select field in a from, each part of a Form.Group that is expected to span the length of the form. Within the group there is also another Form.Field component that I'm simply using as a label. 

        <Form.Group inline style={{ margin: "0 0 .25em" }}>
          <Form.Field width={2} required label="Name" />
          <Form.Input
            width={14}
            name="name"
            value={name}
            onChange={this.handleTextChange}
            error={!!errors.name} />
        </Form.Group>
        <Form.Group inline style={{ margin: "0 0 .25em" }}>
          <Form.Field required width={2} label="Owner" />
          <Form.Select
            width={14}
            name="owner"
            options={this.ownerOptions}
            value={owner}
            onChange={this.handleSelectionChange}
            error={!!errors.owner} />
        </Form.Group>

### Expected Result
All fields should expand to the end of the form, or at the very least, they should all behave the same. If left outside of a From.Group, then the Form.Select component stretches. However, the Form.Group is needs for inline labels and to set the margin (setting margin of Form.Field doesn't propagate up to parent div when parsed into HTML, and thus has no effect).

### Actual Result
The text fields work as expected -- the labels take up a small portion of the form and the text fields expand to the end of the form. However, the select field does not expand. I found that when parsed into HTML the parent div does in fact span the field, but the the "listbox" div does not expand with its parent.

![form](https://user-images.githubusercontent.com/12501471/41931183-4ea48e98-794b-11e8-9139-95eafb53eaae.jpg)

### Version
0.80.2 && 0.81.2

**Comment by layershifter** [comment]
This problem is CSS related, please open issue in the main repo: https://github.com/Semantic-Org/Semantic-UI

However, it can be easily solved:
```jsx
<Form.Select style={{width: '100%'}} width={14} />
```
