### ISSUE TITLE
Modal hard fails in IE 11

### ISSUE THREAD

**Issue by mgandley** [Semantic-Org/Semantic-UI-React#2952]
### Steps
Create a Modal and set the open property to true.  Open using IE 11 (I'm specifically using 11.1088.15063.0 to reproduce).

### Expected Result
The modal opens.

### Actual Result
Hard crash.  TypeError: Assignment to read-only properties is not allowed in strict mode.

### Version
0.81.0

### Testcase
https://codesandbox.io/s/py44qm940

**Comment by mgandley** [comment]
I should note this is a new issue in v0.81.

**Comment by mgandley** [comment]
Looks like this is the portal bug in #2886.  Fixed by #2880.  Closing as duplicate.

**Comment by BartoszCoyote** [comment]
I still got this issue
