### ISSUE TITLE
Dropdown: triggers double onClose event when clicking the icon

### ISSUE THREAD

**Issue by gotjoshua** [Semantic-Org/Semantic-UI-React#2953]
## Bug Report
A dropdown ([like this one](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/src/examples/modules/Dropdown/Usage/DropdownExampleRemote.js)) with search, multiple, and selection will trigger the onClose event twice if i click the arrow icon to close, but only once if i click away from the dropdown.

### Steps
open dropdown, select an item, or 2 , or not.
close the dropdown by clicking on the arrow
notice console 

### Expected Result
only one call to onClose

### Actual Result
Double call to onClose 💣

### Version
0.81.2

### Testcase
[Fork, update, and replace this pen to show the bug]:
[Forked codesandbox:](https://codesandbox.io/s/wqqyrv5xjl)
https://codesandbox.io/s/wqqyrv5xjl

**Comment by layershifter** [comment]
A valid bug, thanks for report 👍
