### ISSUE TITLE
Semantic UI React raises warnings in StrictMode

### ISSUE THREAD

**Issue by johnnyreilly** [Semantic-Org/Semantic-UI-React#2955]
### Steps
Heya!  Well done for all your work on Semantic UI React!

You may already know (or not?) that [as of React 16.3 3 lifecycle methods have been deprecated](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#component-lifecycle-changes):

- `componentWillMount`
- `componentWillReceiveProps`
- `componentWillUpdate`

If you turn on [React's `StrictMode`](https://reactjs.org/docs/strict-mode.html) it warns you about usage of the deprecated APIs.  I just dropped it into my app to experiment and:

### Expected Result
I'd hope to see no warnings

### Actual Result
But I do see warnings 💣

```
warning.js:33 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in AppRaw (created by Route)
    in Route (created by withRouter(AppRaw))
    in withRouter(AppRaw)
    in Router
    in Provider
    in AppContainer

componentWillMount: Please update the following components to use componentDidMount instead: Route, Switch, t

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Menu, Route, Switch

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
printWarning @ warning.js:33
warning.js:33 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in AppRaw (created by Route)
    in Route (created by withRouter(AppRaw))
    in withRouter(AppRaw)
    in Router
    in Provider
    in AppContainer

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: DimmerInner

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

Some are React-Router specific - ([They know about this](https://github.com/ReactTraining/react-router/issues/6060)) but things like `Menu` and `DimmerInner` are Semantic UI React I believe.  There's probably others too - I'm not using all components.

### Version
0.81.1

### Testcase
Probably the best way to see this would be to add:

```
    <React.StrictMode>
    </React.StrictMode>
```

around the whole docs project.

Hope this helps - thanks for your hard work!

**Comment by layershifter** [comment]
Duplicate #2732.
