### ISSUE TITLE
can't use any component

### ISSUE THREAD

**Issue by bogdandevlpr** [Semantic-Org/Semantic-UI-React#296]
Throws this error: 
debug.js:12Uncaught Error: Cannot find module "debug"

**Comment by Maxhodges** [comment]
you have a repo we can use to reproduce the problem?

**Comment by levithomason** [comment]
Ditto to @Maxhodges 

Also, `debug` is listed in our `devDependencies`.  If you happen to be running npm install with `NODE_ENV=production` then you aren't getting the `debug` module.

Check your `node_modules` directory for `debug` with `npm ls debug`.

**Comment by levithomason** [comment]
OK, I have found the issue here. The short answer is to move the `debug` module to the dependencies, which I'll do.  In the meantime, you should `npm i debug` to get up and running.

**Comment by levithomason** [comment]
@abogdan0505 You should be able to `npm i stardust@latest -S` now.  `debug` is included as of `v0.16.2`.

**Comment by bogdandevlpr** [comment]
Yep. Works now.
