### ISSUE TITLE
Support onKeyPress in Checkbox.

### ISSUE THREAD

**Issue by keithyang** [Semantic-Org/Semantic-UI-React#2968]
## Feature Request
Support `onKeyPress` in `Checkbox`.

### Problem description
Currently, there is no way to customize the behavior when keypresses on a `Checkbox` occur. I would like to be able to use certain keys (e.g. space or enter) to toggle the `checked` state which is passed into the `Checkbox` element as a prop.

### Proposed solution
It would be nice to have `onKeyPress` as a prop to `Checkbox` that takes in a custom function for event handling.

### MVP
https://codesandbox.io/s/kwx4w31y0v

**Comment by levithomason** [comment]
Note, all unhandled props are passed through.  Just pass `onKeyPress` and it works just as you'd expect: https://codesandbox.io/s/o7l1jm02jq
