### ISSUE TITLE
Modal at the bottom

### ISSUE THREAD

**Issue by nobody220** [Semantic-Org/Semantic-UI-React#2969]
## Bug Report
Use the modal component.

### Steps
Use the modal component then open the modal.

### Expected Result
The modal must be centered.

### Actual Result
The modal is stuck at the bottom of the page.

### Version
0.81.3

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Update SUI CSS to 2.3, we require it from 0.81.0.
