### ISSUE TITLE
Modal and "magic" margin-top

### ISSUE THREAD

**Issue by n0n4m3x41** [Semantic-Org/Semantic-UI-React#2970]
### Steps
I have just copy and paste the modal example from the doc

### Expected Result
The modal should appear properly

### Actual Result
It automagically set margin-top to -304 💣

https://i.imgur.com/yB3MNVB.png
![image](https://user-images.githubusercontent.com/5268633/42168063-37cc90d4-7e10-11e8-89b2-6b41e3ee87d0.png)

**Comment by layershifter** [comment]
Please update to the latest SUI and SUIR.
