### ISSUE TITLE
Dropdown - LazyLoad does not ssem to work

### ISSUE THREAD

**Issue by hubertguillemain** [Semantic-Org/Semantic-UI-React#2975]
## Bug Report
As far as I understand, the new lazyLoad prop on the Dropdown (feat #1918 ) should only add the elements to the DOM when the Dropdown is actually opened. 
This is not the case 

### Steps

1. Go to https://react.semantic-ui.com/modules/dropdown#types-dropdown
2. Add the prop lazyLoad to the dropdown
3. Open Chrome dev tools, and inspect the closed dropdown element

### Expected Result
The dropdown children should be created in the DOM only when the dropdown is opened

### Actual Result
The dropdown children are present in the DOM even when the dropdown is closed
![screenshot_171](https://user-images.githubusercontent.com/30046324/42275646-41712dac-7f91-11e8-8ada-51fa0f9e7716.png)

### Version
0.81.3 (doc site)

**Comment by layershifter** [comment]
This option doesn't for the children API, use the shorthand API.
