### ISSUE TITLE
Incorrect version number in usage documentation

### ISSUE THREAD

**Issue by artemean** [Semantic-Org/Semantic-UI-React#2976]
When I go to [usage doc](https://react.semantic-ui.com/usage) I read

`Please ensure that you're using semantic-ui-react@0.82.0 or higher`

but the latest version for now is [0.81.3](https://github.com/Semantic-Org/Semantic-UI-React/releases)

Please fix or explain.

**Comment by layershifter** [comment]
Thanks, I made PR with correct versions. Changes were merged earlier than I expect 🐑 

Use [`0.81.2`](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.81.2/package.json#L14) and higher. Docs will be updated with next release.
