### ISSUE TITLE
Input: lang prop

### ISSUE THREAD

**Issue by foysalit** [Semantic-Org/Semantic-UI-React#2979]
## Feature Request
As of now, `<Input lang="fr"/>` will add `lang="fr"` on the wrapping div element instead of the input element itself. It would be great if we could set the lang prop to input elements for localization purposes.

### Proposed solution
I can implement the additional property and submit a PR if someone from the team can point me in the right direction. Will it work if I just add the `lang` prop in this file: https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/elements/Input/Input.d.ts ?

**Comment by layershifter** [comment]
We have special [htmlPropsUtils](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/htmlPropsUtils.js) for these case. We just need to add a new value there.

Feel free to open PR 👍
