### ISSUE TITLE
Disable debug logs

### ISSUE THREAD

**Issue by jimmyn** [Semantic-Org/Semantic-UI-React#298]
How I can disable debug logs?

**Comment by levithomason** [comment]
I've added [Debugger](https://github.com/TechnologyAdvice/stardust#debugger) to the README under Development.  Please let me know if those instructions are clear.  Thanks for the question.

**Comment by jaredhughes** [comment]
@levithomason This continuously resets the local storage value for `debug` in subsequent page loads:
https://github.com/TechnologyAdvice/stardust/blob/09547c45ccbf908cd0758b4de73908006dc25a73/src/utils/debug.js#L6

How about adding `localStorage.debug !== null` as a conditional to setting the Stardust value?

**Comment by levithomason** [comment]
Great point, update coming.

**Comment by levithomason** [comment]
@jaredhughes Pull master and give it a whirl.  Commit here: https://github.com/TechnologyAdvice/stardust/commit/8cad5a9c0538996418109cb4100695410217cc21

``` js
localStorage.debug = localStorage.debug || 'stardust:*'
```

**Comment by jaredhughes** [comment]
Yep, that should do it – thanks!

**Comment by levithomason** [comment]
😉
