### ISSUE TITLE
InputExampleRightCornerLabeled.js does not allow hex colors

### ISSUE THREAD

**Issue by lucasverra** [Semantic-Org/Semantic-UI-React#2980]
## Feature Request
use hex colors in `InputExampleRightCornerLabeled.js`
### Problem description
 I have an issue when wanting label to be #ff7675 color instead of "warning danger `red`"

### Proposed solution
make use of hex color pallete 

<img width="748" alt="image" src="https://user-images.githubusercontent.com/11323803/42319150-6c0a948e-8051-11e8-8aa7-bdb06a059754.png">

vs 

<img width="747" alt="image" src="https://user-images.githubusercontent.com/11323803/42319168-78055044-8051-11e8-9543-215ce78a4d37.png">

**Comment by layershifter** [comment]
Use `style` or follow our theming guide. We use predefined color palette from SUI.
