### ISSUE TITLE
Allow using custom key when rendering Search module results

### ISSUE THREAD

**Issue by tokict** [Semantic-Org/Semantic-UI-React#2981]
### Problem description

I am searching Github repos using the search module and it returns duplicate titles which is to be expected. Since the SearchResult uses `key={childKey || result.title}` for key when rendering, this causes duplicate key errors in react.

### Proposed solution
Allow using custom key definition i.e  `key={childKey || result.customKey || result.title}`

**Comment by layershifter** [comment]
I don't understand your proposal because you can use `childKey`, it's was designed to pass custom keys.
