### ISSUE TITLE
Expected @babel/runtime to be part of devDependencies

### ISSUE THREAD

**Issue by alexandrudanpop** [Semantic-Org/Semantic-UI-React#2987]
Could @babel/runtime be added as a dev dependency instead of a direct dependency?

**Comment by layershifter** [comment]
Please clarify why. I think that it's a production dependency.

https://babeljs.io/docs/en/babel-plugin-transform-runtime.html#installation
> and babel-runtime as a production dependency

**Comment by levithomason** [comment]
This needs to be a production dependency.  The transform changes inline helper code to require statements.  This way, not every file has to have helper functions.  It also means we then have a hard dependency on the module and the specific version of the module.

**Comment by wchargin** [comment]
My understanding is that if I add `semantic-ui-react` as a runtime
dependency to my project, then the resulting code will _not_ perform any
runtime Babel compilations of any kind. However, it will use some
modules from the `@babel/runtime` library, which effectively provides
helper functions. These are required at runtime.

Is this understanding correct?
