### ISSUE TITLE
Modal: inside modal is closing when clicking on contents

### ISSUE THREAD

**Issue by xumix** [Semantic-Org/Semantic-UI-React#2988]
### Steps
Upgraded from semantic-ui-react@0.81.1 to 0.82

### Expected Result
Clicking inside modal does nothing

### Actual Result
Modal is closed when clicking on any modal contents, 0.81.1 worked OK

### Version
 0.82

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by levithomason** [comment]
I cannot reproduce this on our docs which are running 0.82.0.  Tests are also passing.  Closing for now.  We will reopen if we can get a repro case.

https://react.semantic-ui.com/modules/modal#types-modal

**Comment by xumix** [comment]
I've found the repro, the issue is found if modal is opened inside other modal. It can be reproduced in docs
https://react.semantic-ui.com/modules/modal#types-multiple

**Comment by xumix** [comment]
@layershifter thanks!
