### ISSUE TITLE
Add additional params to a YouTube embed URL

### ISSUE THREAD

**Issue by d-leigh** [Semantic-Org/Semantic-UI-React#2994]
### Problem description
I'd like to hide the YouTube video title in the embed component by appending the showinfo=0 parameter to the URL. I've tried adding this property into the Embed object with both zero and a false boolean value, hoping it would be passed to the URL, but this didn't work.

### Proposed solution
Please, add the ability to pass in custom params to append to the URL in the Embed block, which would also allow the optional configuration of start (and end) time when applicable.

### Example JSX
```
<Embed
    color='white'
    hd={false}
    id='D86RtevtfrA'
    autoplay={true}
    brandedUI
    custom={{
      showinfo: false,
      start: 60,
      end: 95
    }}
    iframe={{
      allowFullScreen: true,
      style: {
        padding: 0,
      },
    }}
    placeholder={src}
    source='youtube'
  />
```

### Example URL
`<iframe width="560" height="315" src="https://www.youtube.com/embed/D86RtevtfrA?rel=0&showinfo=0&start=60&end=95" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>`

**Comment by layershifter** [comment]
You can use `Ember` with a custom source:

```jsx
  <Embed
    icon='right circle arrow'
    placeholder='/images/image-16by9.png'
    url='https://www.youtube.com/embed/D86RtevtfrA?rel=0&showinfo=0&start=60&end=95'
  />
```

https://react.semantic-ui.com/modules/embed#types-custom

I'm not sure that we should add vendor specific options.

**Comment by d-leigh** [comment]
Thank you for the quick response. I wasn't requesting vendor-specific options, but an optional key where the user can input fields to add to the URL that compiles to the arguments/queries appended to an embed URL as an advanced customization feature, which can be applied to any source, even the default/custom embed, where the URL could be a base URL and the custom object be additional parameters. This would make it easier to pass in dynamic properties without interpolation. It would be up to the end-user to confirm the validity of each property passed into the custom object. 

For my own purposes, I will go ahead and use the more manual method as proposed, but hope you do reconsider adding this feature as it would be very useful and provide easy customizability that surpasses most other libraries that support embedding.
