### ISSUE TITLE
Colored labels have text color === bg color

### ISSUE THREAD

**Issue by ThiefMaster** [Semantic-Org/Semantic-UI-React#2995]
Happens e.g. on https://semantic-ui.com/elements/label.html#pointing, but also in my app (semantic-ui-css 2.3.3)

![image](https://user-images.githubusercontent.com/179599/42518301-d3a54b8e-8461-11e8-936c-55a6cfa67daf.png)

**Comment by dmitrykrylov** [comment]
It's a problem in semantic-ui-css, seems they are going to fix it:
https://github.com/Semantic-Org/Semantic-UI/issues/6439

**Comment by ThiefMaster** [comment]
oops, I intended to report this in the semantic-ui repo and was actually surprised that there was no issue for it... but now I see that I was looking in the wrong repo ;x

**Comment by layershifter** [comment]
Closing, because issue should be fixed in the main repo.
