### ISSUE TITLE
Multiple Modals close all when click anywhere on second modal

### ISSUE THREAD

**Issue by Brickpsp** [Semantic-Org/Semantic-UI-React#3002]
click anywhere when open modal#2 will close both modal #1 and #2.

![ezgif com-resize](https://user-images.githubusercontent.com/10991648/42625244-793584b6-85f1-11e8-94f5-40bdc9a21db9.gif)

(test on semantic-ui 0.82.0)

**Comment by layershifter** [comment]
Duplicate, #2988.
