### ISSUE TITLE
Dropdown Text Prop

### ISSUE THREAD

**Issue by ecnaidar** [Semantic-Org/Semantic-UI-React#3003]
## Bug Report
Dropdown allows passing `text` prop that will be later rendered inside of your dropdown component.
In reality any react node is working because it is rendered as `{text}` internally but PropType checking errors since in expects `string`. 
It might be reasonable to relax PropTypes constraints since it working anyways but it will be slightly stupid because `text` name implies passing a string as opposed to `content`.

## Why am I even doing that if there is a `label` prop?
`label` prop overrides dropdown arrow icon and I want to have a clear indication that there is dropdown available and another icon at the same time:

<img width="140" alt="screen shot 2018-07-12 at 13 01 52" src="https://user-images.githubusercontent.com/10078339/42627338-64b94110-85d5-11e8-8672-7ddfce7a4fc3.png"> 

### Version
0.81.1

### Testcase
https://codesandbox.io/s/1v80o4ykr3

**Comment by levithomason** [comment]
https://react.semantic-ui.com/modules/dropdown#usage-trigger

![image](https://user-images.githubusercontent.com/5067638/42655348-b43e81c8-85d0-11e8-8d90-50b632ab6067.png)

**Comment by ecnaidar** [comment]
@levithomason Hoped I won't be that person who can't read. Thanks for link and sorry for disturbance.

**Comment by levithomason** [comment]
No worries, there are far too many examples on that page.  This isn't the first issue asking about this feature for `text` either :)

We need an improved discovery process in the docs.   Especially for large components, like Dropdown.  Users should be able to easily find what they need and right now, it is tough.

**Comment by ecnaidar** [comment]
@levithomason Depending on how documentation is generated potentially cheap improvement might be having a link next to prop that directs to example showcasing prop usage and the other way around.
