### ISSUE TITLE
Popup: closed on trigger blur even when portal content is focused

### ISSUE THREAD

**Issue by vlsergeyatsbt** [Semantic-Org/Semantic-UI-React#3005]
### Steps
* create popup with input as trigger (with on="focus") and second input as popup content
* click on input to show popup
* click on input in popup

### Expected Result
* second input focused, popup is still open

### Actual Result
* popup closed

### Version
* works correctly on 0.81.1, 0.81.3
* does not work correctly on 0.82.0

### Testcase
https://codesandbox.io/s/9yv949y13o

**Comment by vlsergeyatsbt** [comment]
I think i've found the source of problem. In version 0.82.0 there is no "rootNode" variable in portal component. Thus the following check always returns undefined:

`const didFocusPortal = _.invoke(this, 'rootNode.contains', e.relatedTarget)`

i think this check need to rewritten into

`const didFocusPortal = _.invoke(this, 'portalNode.contains', e.relatedTarget)`

this way it works for 0.82.0

**Comment by levithomason** [comment]
The proposed bug location appears correct.  Want to make a PR?
