### ISSUE TITLE
Popup: when multiple popups present, click on the other trigger doesn't close original popup

### ISSUE THREAD

**Issue by helgamir** [Semantic-Org/Semantic-UI-React#3006]
## Bug Report
This seems to be the same issue that was reported #1251 But it got back with new versions.

### Steps
Create several popups with a click trigger.
Click first trigger --> first popup opens, then click second trigger --> the second opens, but the first stays open.

### Expected Result
The first popup should be closed when the second trigger clicked.

### Actual Result
The first popup stays open.

### Version
0.82.0
### Testcase
https://codesandbox.io/s/3rx96jzjr6

**Comment by lucmerceron** [comment]
Hello guys,

First, thanks for your amazing work !
I think I found the bug, can I submit a PR ?

**Comment by lucmerceron** [comment]
[This line](https://github.com/lucmerceron/Semantic-UI-React/blob/master/src/lib/eventStack/EventTarget.js#L23) seems to be responsible. When adding the event to the second trigger, it is removing the targetHandler of the first one, hence removing its document listener (for a "click" in our case).
Is there a particular reason this is done this way ?

**Comment by layershifter** [comment]
Yep, it's hard to describe, but you can try to remove/move this line and check how it affects `sidebar` examples. The ideal solution, fix current bug and keep current behaviour of `Sidebar` examples. Not easy 🐱

**Comment by lucmerceron** [comment]
Do we have a need for sharing an eventStack between Components ?
If we have a unique eventStack's instance for each Component, it won't remove handlers of others.

**Comment by lucmerceron** [comment]
Indeed, it is harder to comprehend than expected.

From my investigation, removing and adding that handler on the second portal mount prevents the first one to receive the `click` event (the one that causes the second portal to mount).
A "naïve" analogy would be that removing & adding a `click` listener on a document `click` won't trigger the listener just added.

A lazy solution would be to avoid sharing an `EventStack` instance between every `Portal` components so the listeners management will not be mixed.
Sidebar, which actually suffers the same bug, could take advantage of that solution too.

[Example of the solution](https://github.com/lucmerceron/Semantic-UI-React/commit/1ae4cae74fa3129ab83c78b4701bafdead537f62)

**Comment by honzajerabek** [comment]
Hi there, good job investigating! I discovered this bug with `Dropdown` component - https://codesandbox.io/s/m5x3k8y10p which brought me here, will help if needed :)

**Comment by lucmerceron** [comment]
Hello guys, is there a plan / direction to solve this bug ? I could work on it if we agree on a solution.

**Comment by dmitrykrylov** [comment]
@lucmerceron I would be grateful if anybody could solve it

**Comment by layershifter** [comment]
@lucmerceron I'm currently busy with my paid work.

EventStack was moved to the [separate repo](https://github.com/layershifter/event-stack). The solution is reorder and change event subscribing, more details are there https://github.com/Semantic-Org/Semantic-UI-React/pull/3124#issuecomment-420039264. The help is much appricated.

It seems that we will have issues with `Sidebar`, but it's better to resolve the current problem.

**Comment by semireg** [comment]
I think I've been experiencing this bug in my app. The JSX looks something like:

```
      <Dropdown key="outlineKey" text="Outline" item closeOnBlur direction="left">
        <Dropdown.Menu>
          <Dropdown.Item
```

![dropdown](https://user-images.githubusercontent.com/1819762/45934851-aa092f00-bf69-11e8-85c2-cf146e2ef6f3.gif)

What I find interesting is that the first dropdown is closed OK. It's the second dropdown that doesn't close. But only if the second dropdown opening action caused another dropdown to close.

Perhaps this little tidbit will help with debugging. I can also test any solutions against my codebase to verify a fix. Good luck, this one doesn't seem easy!

**Comment by ivanjiang5628** [comment]
This issue is very critical to our application.

Can anyone help?

Thanks

**Comment by dmitrykrylov** [comment]
@ivanjiang5628 make popup controlled

**Comment by layershifter** [comment]
It's the high priority issue to me, I will work on it at the current week. The next release should contain the proper fix.

**Comment by ivanjiang5628** [comment]
> @ivanjiang5628 make popup controlled

@dmitriyshmatov  Thanks for replying

I can solve this problem by adding "force update" and "force update onChange function" states to the parent component and then passing them to the child components (Popups) as props, but it will significantly slow down the rendering speed of the application due to multiple renderings.

@layershifter Thank you
