### ISSUE TITLE
clicking anywhere with multiple opened modals closes all modals 

### ISSUE THREAD

**Issue by joostVanhoutte** [Semantic-Org/Semantic-UI-React#3010]
### Steps

- open a modal within  another modal
- clicking anywhere closes both modals 

### Expected Result
Only the outermost Modal should close.
### Actual Result
Both modals are closed when clicking anywhere. Pressing escape only closes the second Modal.

### Version
0.82.0

### Testcase
https://react.semantic-ui.com/modules/modal#types-multiple

**Comment by layershifter** [comment]
Duplicate #2988, fixed in #2989.
