### ISSUE TITLE
Search In Dropdown+Menu, Click Search Box Closes the Dropdown

### ISSUE THREAD

**Issue by GeorgeWL** [Semantic-Org/Semantic-UI-React#3011]
### Description
When the `Dropdown` component is used with a `Dropdown.Menu` that contains a `Input`, the input closes the Dropdown immediately on trying to click it.

This is exhibited in the documentation demo page: [Search Inside Dropdown Menu](https://react.semantic-ui.com/modules/dropdown#types-search-in-menu)

### Steps

1. Open the dropdown

1. Attempt to click into the Search Input Box within the Drop-down Menu

### Expected Result
You can type into the Search Box and it then filters the results based on this search

### Actual Result
Drop-down immediately closes, before you are able to type into the box.

Version
0.82.0

### Testcase
https://codesandbox.io/s/ljkn9k1oz

**Comment by layershifter** [comment]
Duplicate #1593.
