### ISSUE TITLE
Dropdown with inline/search doesn't adjust width properly when search query is entered

### ISSUE THREAD

**Issue by igozali** [Semantic-Org/Semantic-UI-React#3012]
### Steps
Using the Code Sandbox provided below, type some search query in the inlined Dropdown (e.g. 'one'). 

### Expected Result
The width of the dropdown should adjust automatically based on entered search query.

### Actual Result
The width of the dropdown is adjusted as if there was no text at all (0 width), and the dropdown icon sits on top of the search query text.

### Version
0.81.1

### Testcase
https://codesandbox.io/s/n0mn3vxwz0

**Comment by igozali** [comment]
Could this simply be fixed by setting `_text` in the code snippet linked below to `searchQuery` instead of `null`? Wondering what the drawbacks would be.

https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L1174

**Comment by layershifter** [comment]
I almost sure that it's not supported by SUI: https://semantic-ui.com/modules/dropdown.html

Can you please check? If this is not supported by SUI will not able to this there.

**Comment by igozali** [comment]
Hi @layershifter, thanks for the response. I was just wondering if you think this bug fix/new feature is worth pursuing in the main SUI repository, then?
