### ISSUE TITLE
Responsive should change layout when a window increases in size

### ISSUE THREAD

**Issue by ImranNZ** [Semantic-Org/Semantic-UI-React#3013]
### Steps

1.     Checkout homepage starter template
2.     Run template
3.     Resize from desktop width to a mobile width, i.e. show mobile menu and content.
4.     Resize back to a desktop width

### Expected Result
Responsive is expected to show the desktop content and menu.

### Actual Result
Responsive remains on the mobile content.

### Version
0.82.0

**Comment by ImranNZ** [comment]
Have tested in version 0.75.1 and Responsive is working correctly.

**Comment by layershifter** [comment]
Fixed in `master` and will be released soon, #2992.
