### ISSUE TITLE
Invalid property value for background-color on a basic colored label

### ISSUE THREAD

**Issue by lazazivkovic** [Semantic-Org/Semantic-UI-React#3017]
## Bug Report
Setting color on a basic Label produces background color to be set to the same color as text and the text inside the label becomes invisible. Value being set is `background-color: none #fff!important`, which is recognized as an `Invalid property value` for `background-color`.

### Steps
Use following component: 
`<Label basic color="red" pointing>Test text</Label>`

### Expected Result
Label is shown with white background and red outline, pointing up. Text is visible.

![basic label expected](https://user-images.githubusercontent.com/20232046/42823413-bf0c1212-89dd-11e8-9ec6-090f022a48ef.PNG)

### Actual Result
Label is shown with a red background. Text is not visible.

![basic label actual](https://user-images.githubusercontent.com/20232046/42823423-c5a3e21c-89dd-11e8-9db3-62183204ca9c.PNG)

![basic label invalid property](https://user-images.githubusercontent.com/20232046/42823441-ce66c234-89dd-11e8-9a60-5309ba0be309.PNG)

### Version
0.82.0

### Testcase
Could not reproduce using sandbox. Property is set accordingly (no *none* part).

![basic label sandbox property](https://user-images.githubusercontent.com/20232046/42823609-45e7823a-89de-11e8-835f-478b91cd0b9b.PNG)

**Comment by layershifter** [comment]
Duplicate #2995.
