### ISSUE TITLE
Icon 'star outline' should be 'star empty' in documentation

### ISSUE THREAD

**Issue by jsgphd** [Semantic-Org/Semantic-UI-React#3018]
### Steps
https://react.semantic-ui.com/elements/icon 
 'star outline' should be 'star empty'

### Expected Result
expected empty star

### Actual Result
got regular star with 'star outline'

### Version
0.82.0

**Comment by levithomason** [comment]
This appears to be working correctly with `start outline`.  Perhaps check which version of the CSS you have loaded?

![image](https://user-images.githubusercontent.com/5067638/43051329-22598d02-8dcd-11e8-9908-02ec430ca4d5.png)
