### ISSUE TITLE
Would love to contribute

### ISSUE THREAD

**Issue by joshuazmiller** [Semantic-Org/Semantic-UI-React#302]
I've been looking into this project and I would love to contribute. I'm new to GitHub (but not to Git, ES6, or React) so I'll just need a bit of direction as to where I can best apply my skills to help out on this project. If you can point me to a task or two, I'll try to help best I can. @levithomason

**Comment by levithomason** [comment]
Awesome, have you checked out the [How Can I Help](https://github.com/TechnologyAdvice/stardust#how-can-i-help) section in the README?  I'd start by looking at the components we're migrating to our v1 API.

You can look through the PRs linked in the issue tracking component API updates, #269, to get a feel for how we are going about things.  After that, and reading the the linked issues, choose a component on the list and start work.  We'll collaborate on the API from there as we've done on the other PRs you'll see.

Definitely hit me up (post an issue) if you have any problems or questions.

Cheers!

**Comment by levithomason** [comment]
@joshuazmiller I just merged CONTRIBUTING.md which covers more detail on writing components.  I realize you've already begun submitting PRs.  However, it may be worth reading through to further help you out.

**Comment by joshuazmiller** [comment]
Okay, great. Thanks!
