### ISSUE TITLE
More than one dropdown is opened at the same time

### ISSUE THREAD

**Issue by csilvacaio** [Semantic-Org/Semantic-UI-React#3026]
### Steps
You should have more than one dropdown in the page. 
1. click to open the first one;
2. click to open the second, the first one will close correctly;
3. click to open the first one again or any other dropdown, it will open but de second will not close.
4. After this, every new dropdown opened will keep others opened too.

### Expected Result
All the other dropdown components should be closed except the last one that I clicked.

### Actual Result
More than one dropdown is opened at the same time

### Version
0.82.0

### Testcase
https://codesandbox.io/s/5v6jvnlyq4

**Comment by layershifter** [comment]
A valid bug, but it was fixed in `semantic-ui-react@0.82.1`. Please check.

**Comment by csilvacaio** [comment]
Checked and it was fixed. Thank you!
