### ISSUE TITLE
Scrollable Results on Search Component 

### ISSUE THREAD

**Issue by Cheizr** [Semantic-Org/Semantic-UI-React#3028]
I'm displaying a large list of items when the user do a query in the Search Component, this is fine for Computer Users, but when it displays on mobile, the keyboard overlaps almost the whole list and can't be scrolled, so I wonder if there is a way to make it renderize a list that is scrollable.

I tried using CSS overflow: scroll; but it show a scroll in the SearchBar Component with the results within and it's completely unreadable.

I can show the code if it's needed

**Comment by layershifter** [comment]
I'm sure not that is actually a bug, please move this to StackOverflow where it can be clarified.

**Comment by Cheizr** [comment]
I didn't understand your message, "I'm not that is actually a bug", it's a bug?
