### ISSUE TITLE
Missing dependencies in package.json

### ISSUE THREAD

**Issue by joshuazmiller** [Semantic-Org/Semantic-UI-React#303]
I ran into 2 missing dependency errors when running 'npm start' for the first time. The project seems to require 'babel-register' and a package named 'history'. Once I installed those the errors disappeared. I recommend adding those to the package.json so that future users won't run into those errors. Thoughts?

**Comment by levithomason** [comment]
I just ran a fresh clone, install, start and all was well. The deps you listed definitely are missing, though.  My guess is you're on npm v2.x which does not flatten the install tree and we've been taking advantage of that.

I've pushed a fix to master just now, give that a go and let me know what happens.

**EDIT**

Closing for good house keeping, will reopen if there are persistent issues.

**Comment by joshuazmiller** [comment]
Okay great. Thanks for pointing out that I am still on NPM 2.15. I upgraded now. Either way, it's good house keeping in general.
