### ISSUE TITLE
Icon size is ignored when using "th large" icon

### ISSUE THREAD

**Issue by aurerua** [Semantic-Org/Semantic-UI-React#3031]
### Steps
Use:
`<Icon  size="mini" name='th large'/>`

### Expected Result
The icon size should reflect the size passed as the argument of `size`.

### Actual Result
The icon will be shown as a large icon.

### Version
0.81.3

### Testcase
https://codesandbox.io/s/z1y49jk4x

**Comment by layershifter** [comment]
A valid issue, but it should be create in the main repo: https://github.com/Semantic-Org/Semantic-UI
Because it caused by CSS classes colision.
