### ISSUE TITLE
Ribbon grey doesn't have the correct color

### ISSUE THREAD

**Issue by SBrendan** [Semantic-Org/Semantic-UI-React#3033]
### Problem description
 I have noticed that the grey colored ribbon inherits the brown color. You can view the color at this class ".ui.ribbon.label:after" on key "border-right-color: inherit".

### Proposed solution
You can replace the brown color by this color #a9a9a9

### MVP
https://codesandbox.io/s/v333v58193

**Comment by layershifter** [comment]
Please post CSS related issues in the main repo: https://github.com/Semantic-Org/Semantic-UI

**Comment by SBrendan** [comment]
OK sorry :)
