### ISSUE TITLE
[Modal] shorthand action onActionClick "will be ignored"

### ISSUE THREAD

**Issue by y0hami** [Semantic-Org/Semantic-UI-React#3034]
### Steps
- Create a modal using the shorthand
- Add an action with the `onActionClick` event from Modal.Actions
- Open the modal

### Expected Result
When clicking the action it should run the specified function.

### Actual Result
Throws an error in console `Warning: Unknown event handler property `onActionClick`. It will be ignored.`

### Version
0.81.1

### Testcase
https://codesandbox.io/s/m3y3n4y4oj

**Comment by layershifter** [comment]
`onActionClick` is designed to be used on `Modal`, in this case you should use `onClick`:
https://codesandbox.io/s/139v47w1lj
