### ISSUE TITLE
IE11 : Sidebar toggle functionality is not working.

### ISSUE THREAD

**Issue by akarshtg** [Semantic-Org/Semantic-UI-React#3036]
## Bug Report
The Side bar is not opening in IE11 (I think due to transform3d() > position:fixed) in react semantic ui home page(https://react.semantic-ui.com/modules/sidebar) itself when opened in IE11. Some are working in the same page but some are not working.

And while using the react semantic ui sidebar if we need to have fixed header and footer in the sidebar container it the workaround should be transform-origin for specific IE11 which is very hard to do for many elements (or) use position:relative which doesnot give the expected output as position:fixed.

**Comment by akarshtg** [comment]
Is there any update on this??

**Comment by Dimyas313** [comment]
Are there any updates on a fix/work around for this issue?

**Comment by layershifter** [comment]
![sidebar-ie11](https://user-images.githubusercontent.com/14183168/61647594-f6b6b700-acad-11e9-9e97-8ce766dab31b.gif)

Tested in IE11, works properly. Going to close for housekeeping, please update if I missed something.
