### ISSUE TITLE
Dropdown in sidebar conflicts with the sidebar when close 

### ISSUE THREAD

**Issue by lchrennew** [Semantic-Org/Semantic-UI-React#3039]
## Bug Report
Dropdown in sidebar conflicts with the sidebar when close 

### Steps
1. open the sidebar
2. click on the dropdown inside the sidebar
3. click anywhere to close the dropdown
4. click anywhere to close the sidebar

### Expected Result
the sidebar should be closed

### Actual Result
the sidebar cannot be closed, and the onHide method is not be invoked.

### Version
0.82.0

### Testcase
https://codesandbox.io/s/l2r183r3yl

**Comment by layershifter** [comment]
As I see, this was fixed in 0.82.1, can you please check?

**Comment by lchrennew** [comment]
This was fixed in 0.82.1, thanks!
