### ISSUE TITLE
Top fixed menu doesn't fixed inside a sidebar

### ISSUE THREAD

**Issue by lchrennew** [Semantic-Org/Semantic-UI-React#3040]
### Steps
open an sidebar and scroll it

### Expected Result
the top fixed menu in this sidebar should be fixed

### Actual Result
the menu is static

### Version
0.82.0

### Testcase
https://codesandbox.io/s/l2r183r3yl

**Comment by layershifter** [comment]
Please post CSS related issues in the main repo: https://github.com/Semantic-Org/Semantic-UI

However, I am not sure that the described behavior is supported.
