### ISSUE TITLE
Table.Cells merge when rendered as anchor tags

### ISSUE THREAD

**Issue by 867530-Nan** [Semantic-Org/Semantic-UI-React#3042]
When using a table, neighboring Table.Cells rendered as anchor tags data become one long strand, and the table headers slides over as many columns as consecutive "Table.Cell as 'a' tags"

Create a Table Row,
add a few Table.Cell's, 
create props "as='a'" for each, 
save file and see result. 

### Expected Result
I would think the table cells render individually, with the content of each simply an anchor tag. Additionally, Each cell is separated with standard table cell border.. 

### Actual Result
All consecutive Table.Cell's render their data in one long strand, each their own anchor, but the cell is now merged. Also, the table headers move down 1 column per consecutive table.cell rendered. 

### Version
0.82.0

https://codesandbox.io/s/lq6q25p37

**Comment by layershifter** [comment]
`Table.Cell` represents a `td` tag. When you passing `as='a'`, so generated markup will be invalid, BTW React claims about it:
```
Warning: validateDOMNesting(...): <a> cannot appear as a child of <tr>.
```
The are two options for you:
- `a` is a child of `Table.Cell`
- add `onClick` handler to `Table.Cell`

Check also this example, [Selectable Cell](http://react.semantic-ui.com/collections/table/#variations-selectable-cell).
