### ISSUE TITLE
Uncaught exception on IE 11 (Edge Compatibility)

### ISSUE THREAD

**Issue by rjb8682** [Semantic-Org/Semantic-UI-React#3043]
### Steps
Clone [this repo](https://github.com/rjb8682/test-react) (my own sample project):
* Note: I'm using yarn, but of course this should work with npm with minimal changes

**Run these steps**
1. Run `yarn install`
2. Run `yarn start`
3. Go to `localhost:8080`
4. Click button on webpage
5. Type in input box 

### Expected Result
No errors in console

### Actual Result
The following errors show in the console every time an event fires (mouse click, or keyboard press)

> SCRIPT5022: Exception thrown and not caught
> File: bundle.js, Line: 40029, Column: 3

When clicking the file that is shown in the error, it links to the _nonIterableSpread function from the `@babel-runtime`

### Version
Semantic UI React version: `0.82.1`
Internet Explorer update version: `11.0.70`

**Comment by levithomason** [comment]
I don't have a windows machine available during weekends to test this.  @layershifter any chance you could run a check here?

Not sure where the spread is, but it sounds like an easy fix was we can locate it.

**Comment by layershifter** [comment]
IE11 doesn't support some features of `Set` & `Map`, see #3124.
