### ISSUE TITLE
a closing sidebar causes react warning

### ISSUE THREAD

**Issue by lchrennew** [Semantic-Org/Semantic-UI-React#3045]
### Steps
1. Open sidebar, and click anywhere to close the sidebar.
2. Before the sidebar's closing animation ends, click the "unmount" button
3. Look at the console output, there's a warning

### Expected Result
No exception or warning is thrown

### Actual Result
There's a warning 💣
```
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```
### Version
0.82.1

### Testcase
https://codesandbox.io/s/zzq199oyl4

**Comment by layershifter** [comment]
Looks like a valid bug, will check it on the next week.

**Comment by karuncodes** [comment]
I opened the testcase in a separate window and there is no warning on sandbox  https://zzq199oyl4.codesandbox.io/

cc: @lchrennew @layershifter
