### ISSUE TITLE
I need Multiple Search Selection Dropdown support duplicated selection

### ISSUE THREAD

**Issue by lchrennew** [Semantic-Org/Semantic-UI-React#3046]
### Problem description
I have an issue when I use mutiple search selection dropdown to construct formulars.
e.g.:
options(text only): ["x", "y", "=", "+"]
I want to input: "x" "+" "y" "=" "y" "+" "x"

### Proposed solution
Because the options may be selected multiple times,  the multiple search selection dropdown should have a property `allowDupSelect` to allow duplicated select

**Comment by layershifter** [comment]
It's not a common use case, we will not implement this feature. Current `Dropdown` component is already overcomplicated.

You can modify available options `onChange` and new options with different values, but same texts.
