### ISSUE TITLE
[Dropdown]allow additional cause multiple search selection Dropdown duplicate new added items

### ISSUE THREAD

**Issue by lchrennew** [Semantic-Org/Semantic-UI-React#3047]
### Steps
1. Enter a new option "Test"
2. Enter "Test" again: there will be only one "Test" selected
3. Remove the selected "Test" option: there will be two "Test" options in the list
4. Select one out of the two "Test" option and then remove it: there will be three "Test" options.

### Expected Result
There will be only one "Test" option added

### Actual Result
Duplicated options are added and more and more and more....💣

### Version
0.82.1

### Testcase
https://codesandbox.io/s/9196qyo2jw

**Comment by rob9095** [comment]
I think this is more of an issue with the way the example is implemented, not the actual dropdown module itself. You can alter the `handleAddition` method so duplicates are not added.  Something else I noticed with this module, after removing a selected value, the search input loses focus. To get focus back to the search input you need to either click out of the dropdown and back in or add a new item/label from the list.

**Comment by layershifter** [comment]
Your `handleAddition` method should handle this, the easiest was is use lodash's `uniqBy([...newOption, options], 'value')`. You can also impliment more complicated logic.
