### ISSUE TITLE
List with horizontal prop has all the lines shifted on the right except the first one

### ISSUE THREAD

**Issue by a-coruble** [Semantic-Org/Semantic-UI-React#3048]
### Steps
Create a list with items that is long enough to get split in two or more lines : 
```
<List horizontal>
    <List.Item>Foo</List.Item>
    .....
        <List.Item>Foo</List.Item>
</List>
```

### Expected Result
![image](https://user-images.githubusercontent.com/22549509/43320204-f4cd38a0-91a7-11e8-897d-ed3b5f7eb858.png)

### Actual Result
![image](https://user-images.githubusercontent.com/22549509/43320233-0f5f18d2-91a8-11e8-8384-0bf418a59823.png)

### Version
0.76.0

**Comment by layershifter** [comment]
Please fill issue fully and add codesandbox example.
