### ISSUE TITLE
Failed prop type for icon 'large star'

### ISSUE THREAD

**Issue by gaui** [Semantic-Org/Semantic-UI-React#3049]
### Steps

I have a basic `Button`:

```
<Button basic className='someClass' icon='large star' />
```

It's always throwing the following warning:

```
Warning: Failed prop type: Invalid prop `name` of value `large star` supplied to `Icon`.
```

### Version
0.82.1

**Comment by ilanus** [comment]
could you provide sandbox? seems fine:
<img width="786" alt="screen shot 2018-07-29 at 02 15 11" src="https://user-images.githubusercontent.com/9677898/43361666-43d29aca-92d5-11e8-8e68-118e1b663d72.png">

**Comment by gaui** [comment]
@layershifter So to use a different size, I have to use the long version?

**Comment by layershifter** [comment]
An icon can have `name` and `size`, you should pass correct values to this props. Take a look on examples tab, http://react.semantic-ui.com/elements/icon/
