### ISSUE TITLE
Popup no longer updates when horizontalOffset changes

### ISSUE THREAD

**Issue by mic159** [Semantic-Org/Semantic-UI-React#3050]
## Bug Report

I just updated from 0.80.2 to 0.82.1.

Now when you change `horizontalOffset` in a Popup component, it will no longer re-calculate the style of the portal, it will only calculate once on mount of the portal.

I believe `setPopupStyle` needs to be called again when it detects a change in the `horizontalOffset` property.

### Steps

Have a component that updates the `horizontalOffset` while the popup is open, eg. when the mouse moves. (see testcase)

### Expected Result
When the mouse moves, the popup moves with the mouse.

### Actual Result
The popup only gets the position when you start hovering, and will not update.

### Version
0.82.1

### Testcase

Broken on `0.82.1`: https://codesandbox.io/s/23j0n0mkrp
Working on `0.81.1`: https://codesandbox.io/s/p7rj6z961x

**Comment by levithomason** [comment]
Hm, that is curious.  I have confirmed the provided broken example is properly setting a horizontal offset on state and that is also triggering re-renders where it is set.

Why it is not being applied needs more investigation.

Thanks for the superb report.

**Comment by pferreir** [comment]
Same issue here. I actually hit it just now.
