### ISSUE TITLE
Menu color prop does what exactly?

### ISSUE THREAD

**Issue by AnthonyGio** [Semantic-Org/Semantic-UI-React#3051]
I see Menu.item color prop changes the color of the item element, but the Menu color prop doesn't change the background color of the Menu. Am I misinterpreting something or is there another step to changing the background color of the menu without CSS to something other than white or inverted?

Thanks

**Comment by brianespinosa** [comment]
@AnthonyGio the `color` prop for the `<Menu>` component only changes the color of the menu, not the background color. If you combine the `inverted` and `color` props you can change the background color to one of the OOTB colors.
```
<Menu color='red' inverted />
```
You can try this and see the change live by editing the code example in the docs here: https://react.semantic-ui.com/collections/menu/#variations-colored-inverted
