### ISSUE TITLE
warning message on the console when using Icon tag name='images outline"

### ISSUE THREAD

**Issue by woosuk288** [Semantic-Org/Semantic-UI-React#3053]
### Steps

import React from 'react';
import { Button, Icon } from 'semantic-ui-react'

const PostPhotoButton = ({ basic = true }) => {
  console.log('PostPhotoButton')
  return (
    <Button basic={basic}>
      <Icon.Group size='huge' style={{ margin: '0px 0px 6px 0px' }}>
        <Icon name='images outline' />
        <Icon corner name='add' />
      </Icon.Group>
      <br />Photos
    </Button>
  );
};

export default PostPhotoButton;

### Expected Result
no warning message

### Actual Result

the icon is displayed normally. but warning message is...

Instead of `images outline`, did you mean:
  - file image outline
  - flag outline
  - imageWarning: Failed prop type: Invalid prop `name` of value `images outline` supplied to `Icon`.

### Version
0.80.2

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by enderortak** [comment]
Same for "arrows alternate horizontal"

**Comment by levithomason** [comment]
Fixed in #3092
