### ISSUE TITLE
Reopen issue #1668

### ISSUE THREAD

**Issue by jscheel** [Semantic-Org/Semantic-UI-React#3059]
Issue #1668 was closed automatically, even though it is clearly a problem with the proptype definition. Read to the end, and you will see that `right` should be a valid enum as the component does not render properly without it when using children.

**Comment by jscheel** [comment]
Possible that it's different because of an update to SUI?

**Comment by layershifter** [comment]
This issue was invalid and anyone doesn't read that SUI doesn't have definitions for `right`. To display correctly an icon with children API just pass the `icon` prop:

```jsx
<Input icon>
  <input className="custom" />
  <Icon name="calendar" />
</Input>
```
https://codesandbox.io/s/8k14k8rp30

**Comment by jscheel** [comment]
@layershifter Ok, so your latest reply on https://github.com/Semantic-Org/Semantic-UI-React/issues/1668#issuecomment-409877369 makes it much clearer. You have to keep the `icon` prop as a bool prop for it to work properly. Thanks!
