### ISSUE TITLE
can't read docs on small screen

### ISSUE THREAD

**Issue by SteveALee** [Semantic-Org/Semantic-UI-React#3060]
I looked at docs on my phone to find out what this is but is not responsive so I still don't know. :(

**Comment by layershifter** [comment]
Duplicate #2443.

Currently we don't have time to optimize docs for mobile devices, however it's somewhere in my personal priority list 🐱 

It's not a critical issue for us because SUIR and SUI are responsive, you can check layout examples. Also, we will accept PR that improves docs accessability.

**Comment by SteveALee** [comment]
NP, sorry  it's a duplicate.

**Comment by layershifter** [comment]
NP, feel free to submit PR that improves this 👍
