### ISSUE TITLE
Dropdown: doesn't close when selecting another dropdown

### ISSUE THREAD

**Issue by evollu** [Semantic-Org/Semantic-UI-React#3062]
### Steps
A clear and concise description of steps to reproduce the problem.

1. go to link https://react.semantic-ui.com/modules/dropdown/#usage-close-on-blur
2. select 1st drop down, select 2nd dropdown, select 1st dropdown again

### Expected Result
The result that you expected.
only one dropdown should open at a time

### Actual Result
The actual result that happened 💣
both dropdowns are open
<img width="513" alt="screen shot 2018-08-02 at 5 19 59 pm" src="https://user-images.githubusercontent.com/9213224/43611795-51dea72a-9678-11e8-8fb6-c29686e3e997.png">

### Version
0.82.1

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://react.semantic-ui.com/modules/dropdown/#usage-close-on-blur

**Comment by annjawn** [comment]
I can confirm that this is really an issue. I am encountering the same after using 3 dropdowns in a Header bar. It's really inconsistent. Sometime the menu closes when another one opens sometimes it doesn't.

![menu](https://user-images.githubusercontent.com/26977294/43665699-ec8e057e-9725-11e8-93ea-d5df178caf17.gif)

**Comment by layershifter** [comment]
@annjawn please make sure that you're using the latest version.

**Comment by layershifter** [comment]
The described issue comes from the `closeOnBlur` prop, I need to perform an additional checkes, it can be expected behaviour.

**Comment by annjawn** [comment]
I can confirm that this issue not only happens when using Subcomponent API `Dropdown.Menu` but also using shorthand with `options`. I just updated the module about an hour ago hoping for a fix but the issue persists. As a workaround I had to manage individual states using `open`, `onOpen`, and `onBlur` for each `<Dropdown>` component.

**Comment by levithomason** [comment]
This could be related to #3006.  Multiple popups have the same issue.  Perhaps this is an event handling problem in EventStack.

**Comment by crowdozer** [comment]
If it helps at all, the process is actually _very_ consistent, exact steps:
1. Open a dropdown
2. Open a new dropdown
3. Open any dropdown but the one from step 2 
4. The dropdown from step 2 is no longer being managed, repeat from step 2 with a new dropdown to open as many as you want 
5. Click the dropdowns that are unmanaged to manually close them, they work as intended until you do this to them again
(I'm using the terms managed and unmanaged solely to refer to them opening/closing automatically, I don't know exactly how it works behind the scenes.)

**Comment by evollu** [comment]
This issue has been stale for a while. Is anyone looking into it?

**Comment by levithomason** [comment]
Yes, I've been investigating on weekends as available.  There is a related issue with opening multiple popups.  There is something possibly awry in EventStack, or even Portal.  More eyes are very welcome.

**Comment by lucmerceron** [comment]
I did a small investigation and described it on [this issue](https://github.com/Semantic-Org/Semantic-UI-React/issues/3006).
I could work on a solution if someone could tell me the right direction to take.
