### ISSUE TITLE
Transition: Transition class names are not propagated for custom components

### ISSUE THREAD

**Issue by starrodkirby86** [Semantic-Org/Semantic-UI-React#3063]
### Steps
- Create a React component (e.g. `const Foo = () => <p/>`).
- Wrap a transition over the custom component (e.g. `<Transition><Foo /></Transition>`).

### Expected Result
I expected that the custom component would display the transition. For instance, if the custom component was an image or a whole page, and the transition was a left swing, my component should transition with that left swing.

### Actual Result
The custom component has absolutely no animation. The HTML elements indicate the custom component having no transition class names. The Transition component is expectedly cloning ``children`` and [adding the relevant class names](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Transition/Transition.js#L290). Despite these class names being visible in the React dev tools, they are nowhere to be seen in the final output.

Workarounds are possible – a couple of them are presented in the following testcase:
- Pass the `classNames` prop into the custom component and into its children.
- Wrap the custom component first with a primitive element (e.g. `<div />`) or a Semantic UI element.

I'll probably be wrapping the custom component with something like `<Segment basic />`, but it seems non-intuitive when applying a transition over literally any custom component and receiving no animation.

### Version
0.82.1

### Testcase
https://codesandbox.io/s/0oqlqnl45w

HTML for each of the three test components to indicate where the class transitions go:
```html
<div class="three column row">
    <div class="column"><img src="foo.png" class="ui small image">
        <p>Custom Component (no anim)</p>
    </div>
    <div class="column"><img src="foo.png" class="ui small image vertical flip visible transition">
        <p>Custom Component (class propagated)</p>
    </div>
    <div class="column">
        <div class="vertical flip visible transition"><img src="foo.png" class="ui small image"></div>
        <p>Custom Component (wrapped div)</p>
    </div>
</div>
```

React Dev Tool screenshot for the first test component. Note that the classNames *are* there, but are not appearing in the final HTML output:
![image](https://user-images.githubusercontent.com/9653765/43618976-66bcfc66-9680-11e8-8704-6e65ca41e8a3.png)

---

Cheers, love the library!

**Comment by layershifter** [comment]
Thanks for detailed report, however it's duplicate:
https://github.com/Semantic-Org/Semantic-UI-React/issues/1187#issuecomment-273988903
