### ISSUE TITLE
Drowdown gets stuck in electron

### ISSUE THREAD

**Issue by TheVedhaGuy** [Semantic-Org/Semantic-UI-React#3064]
### Steps
Create a dropdown in a react component in the electron app

### Expected Result
When the dropdown is clicked, it opens and lists a set of values. A value is then "selected" and the drop down is closed.

### Actual Result
When the drop down is clicked, it opens and lists a set of values. A value is "selected" and the text displays in the div of the dropdown and you CANNOT close the dropdown no matter what. It's like a static image that won't disappear.

![image](https://user-images.githubusercontent.com/14185832/43652519-775b64ac-9713-11e8-98e2-c893120e22d8.png)

### Version
0.82.0

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by brianespinosa** [comment]
@TheVedhaGuy Please provide a minimal working example of the code that is causing you this problem. I work on a very large scale application using SUIR and Electron so I know dropdowns do work there. My guess is there is something else going on here with the dropdown state that is not unique to Electron but I cannot look with you until you provide some code.

I'll reopen as soon as you provide a code example. 👍
