### ISSUE TITLE
Adding Additional Menu Colours

### ISSUE THREAD

**Issue by erinosher** [Semantic-Org/Semantic-UI-React#3066]
## Bug Report

Adding a custom colour results in errors because `SUI.colors` is static.

### Steps
A clear and concise description of steps to reproduce the problem.

1. Specify a new colour to use for the menu in `menu.variables`
2. Use that colour when implementing a menu

### Expected Result
No errors

### Actual Result
The following error in the console.
```
index.js:2178 Warning: Failed prop type: Invalid prop `color` of value `white` supplied to `Menu`, expected one of ["red","orange","yellow","olive","green","teal","blue","violet","purple","pink","brown","grey","black"].
    in Menu (created by DesktopContainer)
    in DesktopContainer (created by Connect(DesktopContainer))
    in Connect(DesktopContainer) (created by ResponsiveContainer)
    in div (created by ResponsiveContainer)
    in ResponsiveContainer (created by HomePage)
    in HomePage (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in App
    in AppContainer
    in Provider
```

### Version
0.78.2

### Testcase
https://codesandbox.io/s/5wlv08yqwl

### Additional Notes
The following is a workaround to avoid the error, but as pointed out in #2432 `SUI.js` is planned to removed from builds eventually.

Here is the workaround: https://codesandbox.io/s/ly997qm50l

**Comment by layershifter** [comment]
We use the predefined color palette from SUI, please use CSS for styling in this case.

**Comment by erinosher** [comment]
I'm fully aware, and I do use custom styles through semantic-ui-less. However, I'm referring the error output caused by the static enums in SUI.js
