### ISSUE TITLE
Compilation issue with docgenInfo.json (windows)

### ISSUE THREAD

**Issue by joshuazmiller** [Semantic-Org/Semantic-UI-React#307]
Sorry for bringing up another compilation issue. 

The file [docs/app/utils/getComponentDocInfo.js](https://github.com/TechnologyAdvice/stardust/blob/master/docs/app/utils/getComponentDocInfo.js) is returning `undefined` (checked via console.log) for `docPath` and `docGen` . It is supposed to get `docPath` by parsing the docgenInfo.json file that was generated by the build process on my Windows machine. (It seems to be looking for `_meta.name` which doesn't appear in the docgenInfo file). This doesn't appear to work. The result is that my app won't compile and I get the following 3 messages in my console:

> Warning: Failed propType: Required prop `docPath` was not specified in `ComponentDescription`. Check the render method of `ComponentDoc`.
> Warning: Failed propType: Required prop `docgen` was not specified in `ComponentDescription`. Check the render method of `ComponentDoc`.
> Uncaught TypeError: Cannot read property 'props' of undefined

Note: The last error is referring to line 21 in [ComponentDoc.js](https://github.com/TechnologyAdvice/stardust/blob/master/docs/app/Components/ComponentDoc/ComponentDoc.js):

> <ComponentProps props={doc.docgen.props} />

Here's the content of my auto-generated docgenInfo.json:
[docgenInfo.json.txt](https://github.com/TechnologyAdvice/stardust/files/336711/docgenInfo.json.txt)

**Comment by levithomason** [comment]
The content of your docgenInfo.json looks correct.  Though, it shouldn't be named `.txt`.  I assume you renamed this file?

What is the full path to the `docgenInfo.json` file on your machine?

**Comment by joshuazmiller** [comment]
Yes, I just copied the contents into a `.txt` file so I could include it here. The full path is `C:\Users\Joshua\Dropbox\GitHub\stardust\docs\app\docgenInfo.json`

**Comment by levithomason** [comment]
Since the file is present, and the the contents are correct, I cannot see any reason why the import would be undefined.  I am not a Windows user so I am unsure if that has anything to do with it.

This may be related to #304 which does have errors we can diagnose.  Let move this conversation about the undefined import to there as well.

**Comment by joshuazmiller** [comment]
This is resolved. Just the regex for Windows file paths was the issue as @davezuko mentioned in #304. Thanks!
