### ISSUE TITLE
Message component type definition is inconsistent and missing 'medium'. Propose to import and use common SemanticSIZES type

### ISSUE THREAD

**Issue by ltfschoen** [Semantic-Org/Semantic-UI-React#3071]
### Steps
A clear and concise description of steps to reproduce the problem.

I'm implementing a React component as follows:
```
import { BareProps, UnlockI18n } from './types';

import React from 'react';

import Message from 'semantic-ui-react/dist/commonjs/collections/Message/index';
import { SemanticSIZES } from 'semantic-ui-react/dist/commonjs/index';

type Props = BareProps & {
  error?: UnlockI18n | null,
  size?: SemanticSIZES | 'medium' // hack until PR accepted by semantic-ui-react
};

export default class Notification extends React.PureComponent<Props> {
  render () {
    const { error, size = 'tiny' } = this.props;

    if (!error) {
      return null;
    }

    const renderMessageBody = (error: UnlockI18n) => {
      return (
        <div>
          {/* <Message.Header>{error.key}</Message.Header> */}
          <p>{error.key}: <b>{error.value}</b></p>
        </div>
      );
    };

    return (
      <div className='ui--Notifications'>
        { error.key === 'error' ? <Message size={size} error>{ renderMessageBody(error) }</Message> : null }
        { error.key === 'warning' ? <Message size={size} negative>{ renderMessageBody(error) }</Message> : null }
      </div>
    );
  }
}
```

I'm having to manually add the available types and omit `'medium'` from the type definition of `size?: 'mini' | 'tiny' | 'small' | 'large' | 'big' | 'huge' | 'massive'`, when I'd rather it just be `size?: SemanticSIZES`, and have `| 'medium'` included.

The reason why I have to do this is because I'm importing from 'semantic-ui-react/dist/commonjs/index', which includes: `export type SemanticSIZES = 'mini' | 'tiny' | 'small' | 'medium' | 'large' | 'big' | 'huge' | 'massive';`, and then I'm passing that `size` type into the component `<Message size={size} ...`, whose type definition is in 'semantic-ui-react/dist/commonjs/collections/Message/Message.d.ts' as follows:
```
...
import {
  SemanticCOLORS,
  SemanticShorthandCollection,
  SemanticShorthandContent,
  SemanticShorthandItem
} from '../..';
...
export interface MessageProps {
...
  /** A message can have different sizes. */
  size?: 'mini' | 'tiny' | 'small' | 'large' | 'big' | 'huge' | 'massive';
```

Note how `'medium'` is missing??

Because of this, TypeScript TSLint gives me error:
```
ui-app/src/Notification.tsx:36:44 - error TS2326: Types of property 'size' are incompatible.
  Type '"medium"' is not assignable to type '"big" | "small" | "large" | "mini" | "tiny" | "huge" | "massive" | undefined'.

36         { error.key === 'error' ? <Message size={'medium'} error>{ renderMessageBody(error) }</Message> : null }

```

### Expected Result
The result that you expected.

**Proposed Solution:**

Update Message.d.ts as follows:

```
...
import {
  SemanticCOLORS,
  SemanticShorthandCollection,
  SemanticShorthandContent,
  SemanticShorthandItem,
  **SemanticSIZES**
} from '../..';
...
export interface MessageProps {
...
  /** A message can have different sizes. */
  size?: **SemanticSIZES**;
```

### Actual Result
The actual result that happened 💣

### Version
0.80.2

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Semantic UI doesn't support `medium` size, [reference](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/collections/message.less#L453). So, existing definition is correct. `Message` has medium size by default, in fact.

**Comment by ltfschoen** [comment]
@layershifter Could we possibly update semantic-ui-react/dist/commonjs/collections/Message/Message.d.ts so that exports a type `export type MessagePropsSize = 'mini' | 'tiny' | 'small' | 'large' | 'big' | 'huge' | 'massive';`, so that it becomes the following. It would also help us reuse the type in our projects instead of having to redeclare it.
```
...
import {
  SemanticCOLORS,
  SemanticShorthandCollection,
  SemanticShorthandContent,
  SemanticShorthandItem
} from '../..';
...
export type MessagePropsSize = 'mini' | 'tiny' | 'small' | 'large' | 'big' | 'huge' | 'massive';
...
export interface MessageProps {
...
  /** A message can have different sizes. */
  size?: MessagePropsSize;
```

**Comment by layershifter** [comment]
Yep, we can make do this. PR is coming! 🚤

**Comment by layershifter** [comment]
Will be included to the next release.
