### ISSUE TITLE
Using bool? field "fluid" returns a warning in <Card.Group> Component

### ISSUE THREAD

**Issue by CurlyMenace** [Semantic-Org/Semantic-UI-React#3076]
### Steps
I have created a simple <Card.Group fluid> component that accepts items from props.

### Expected Result
No problems since CardComponent interface accepts boolean? fluid

### Actual Result
Website works alright, but it returns a warning:

> "Warning: Received `true` for a non-boolean attribute `fluid`.
> 
> If you want to write it to the DOM, pass a string instead: fluid="true" or fluid={value.toString()}."
> 

### Version
0.82.2

**Comment by brianespinosa** [comment]
Hello @PatrykRyba. [If you take a look at the docs for `<Card>`](https://react.semantic-ui.com/views/card/), click the tab at the top for `<Card.Group>` and expand the props definitions. You will see that `fluid` is not a valid prop for `<Card.Group>`.

If you want a group of cards and to have the cards themselves be fluid you need to add the `fluid` prop directly onto your `<Card>` component.

**Comment by voyagebagage** [comment]
So what's the fix ? I had to rebuilt a project and now I have so many warnings of that kinds !

**Comment by brianespinosa** [comment]
@voyagebagage 

> If you want a group of cards and to have the cards themselves be fluid you need to add the fluid prop directly onto your <Card> component.
