### ISSUE TITLE
Run documentation Offline?

### ISSUE THREAD

**Issue by oleksandrkyselov** [Semantic-Org/Semantic-UI-React#3077]
Hello there, is this repository also intended to run the documentation at your own instance (offline)? I do not want to report a bug but seems that after installing dependencies I do `npm run start` and I open localhost:8080 but it's unaccesible.

It would be great for those that travel.

Thank you!

**Comment by lasley** [comment]
I was just able to fire up a local docs instance using the following steps:
1. Run `yarn` in the package root
1. `npm run start` also in package root
1. Docs viewable on http://localhost:3000, which should be indicated by console output:

```
=> [✓] App serving at http://localhost:3000
```
