### ISSUE TITLE
Publish a cdn that supports stack snippets 

### ISSUE THREAD

**Issue by sag1v** [Semantic-Org/Semantic-UI-React#3079]
Hi, sometimes when i want to help others with semantic-ui-react on stackoverflow i want to write a snippet using the built in stack snippets. 
This requires a umd / cdn version. but none of the cdn's out there are supported by stack snippets editor because of cors or other security issues.

It would be great if we had an official cdn for semantic-ui-react.

**Comment by layershifter** [comment]
Hi, we have a UMD build published on:
- cdnjs: https://cdnjs.com/libraries/semantic-ui-react
- unpkg: https://unpkg.com/semantic-ui-react@0.82.2/dist/umd/

----

See a working codepen: https://codepen.io/anon/pen/yqwyrm It uses latest versions of SUIR and React. You can also use our template for codesandbox: https://codesandbox.io/s/2l3n74j9y

**Comment by sag1v** [comment]
@layershifter Thanks for the quick replay.  
I know about these, but as i mentioned these and other versions i found are not supported within the [stack snippets](https://stackoverflow.blog/2014/09/16/introducing-runnable-javascript-css-and-html-code-snippets/) context.  

For example i get this error:  
![image](https://user-images.githubusercontent.com/9153149/44005098-3c42d12e-9e76-11e8-85d4-e8c7ad8953e0.png)

Or 
![image](https://user-images.githubusercontent.com/9153149/44005179-d6c9fe9c-9e77-11e8-9f25-f919016593cb.png)

**Comment by layershifter** [comment]
Oh, I see now. It's strange that we ship this part of code to production, I will investigate this tomorrow.

**Comment by layershifter** [comment]
I've recently merged. Previously checked resulting build, it works 🏴 Size was seriously reduced, too.

Will be shipped with the next release. Thanks for report 👍

**Comment by sag1v** [comment]
@layershifter Great news!
Did you test it on stackoverflow (inside stack snippets)?

**Comment by layershifter** [comment]
Nope, but the code that accessed `localStorage` was removed, so it should works.

You can test it locally, too:
```bash
# clone repo
yarn
yarn build:dist:umd
yarn serve --ssl dist/umd
```

The build will be accessible on:
`https://localhost:5000/semantic-ui-react.min.js`
