### ISSUE TITLE
Feature: Higher Order Component for Popups

### ISSUE THREAD

**Issue by iMerica** [Semantic-Org/Semantic-UI-React#3089]
Hey guys,

Loving this library. Thanks for working on it! 

## Feature Request
It would be great if we can write popups like this:

```jsx
<PopUp>
  <Form.Field .... />
</PopUp>
```

### Problem description
Popups work fine right now, but passing in that much JSX as props is a messy API.

### Proposed solution
Stage One:
Popups as a separate HOC.
Stage Two:
HOC Popups as the default API

### MVP
I'll post a branch once I get it working

**Comment by levithomason** [comment]
Duplciate #2552
