### ISSUE TITLE
Dropdown placeholder Invalid prop

### ISSUE THREAD

**Issue by preeeby** [Semantic-Org/Semantic-UI-React#3090]
Hi :-)

I want do have a dropdown with no text, just a <Icon or <Flag
![1](https://user-images.githubusercontent.com/24654358/44208177-f89ffe00-a15f-11e8-9b31-0f12fd145759.jpg)

When I click it, I get options with flag and text:
![2](https://user-images.githubusercontent.com/24654358/44208214-13727280-a160-11e8-83e9-ccc88173374c.jpg)

When I select Item it changes and all works good:
![3](https://user-images.githubusercontent.com/24654358/44208251-2edd7d80-a160-11e8-8b3f-491ffe2f9f47.jpg)

But in console I get:
![screenshot_2](https://user-images.githubusercontent.com/24654358/44208288-474d9800-a160-11e8-8506-6ef50e6abbfc.jpg)

I get the same when I use 'text='... ' same as now with 'placeholder='... The code is this:
![4](https://user-images.githubusercontent.com/24654358/44208388-7bc15400-a160-11e8-8842-a5b94b46c193.jpg)

How do I get just the icon as dropdown? I will need this option in other parts of the app also. And I don't mean this: 
![5](https://user-images.githubusercontent.com/24654358/44208552-f2f6e800-a160-11e8-838f-54378152d971.jpg)
Whem I add JSX in icon='... I get strange behavior when menu is opened, I get 2 icons at the same time:
![6](https://user-images.githubusercontent.com/24654358/44208612-22a5f000-a161-11e8-98b3-476ca9dce608.jpg)

Thanks

**Comment by levithomason** [comment]
You're looking for `trigger`:
http://react.semantic-ui.com/modules/dropdown/#usage-trigger
