### ISSUE TITLE
Local development reload issues

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#3095]
@layershifter I've noticed after the latest round of build changes that editing an example source file in watch mode does not work correctly.  The `exampleSources.json` gets rewritten with only a single example entry, so all the other examples are missing.  Perhaps you could take a look?

## Steps

1. `yarn start`
1. Navigate to /elements/button
1. See all examples are rendered and `exampleSources.json` includes all examples
1. Edit ButtonExampleButton.js
1. 🐞 There is no HMR or page reload
1. 🐞 `exampleSources.json` now looks like this:

    ```json
    {
      "elements/Button/Types/ButtonExampleButton": "import React from 'react'\nimport { Button } from 'semantic-ui-react'\n\nconst ButtonExampleButton = () => <Button>Click Here!</Button>\n\nexport default ButtonExampleButton\n"
    }
    ```
## Initial Load

![image](https://user-images.githubusercontent.com/5067638/44358737-b251e400-a46a-11e8-8dac-efaf3bcb268d.png)

## After editing ButtonExampleButton.js

![image](https://user-images.githubusercontent.com/5067638/44358919-399f5780-a46b-11e8-8ede-b04d3f4ea0fe.png)

**Comment by layershifter** [comment]
:boom: Will take a look tomorrow, @levithomason your reports are awesome :heart:
