### ISSUE TITLE
Modal: Scroll bar is "invisible" when using inverted dimmer

### ISSUE THREAD

**Issue by TheBurnerGuy** [Semantic-Org/Semantic-UI-React#3096]
### Steps
Open a modal with the prop 'dimmer' set to 'inverted'. Make the screen small enough so that the modal is scrollable.

### Expected Result
To be able to see the scrollbar on the dimmer. (e.g. a black/grey scrollbar)

### Actual Result
The scrollbar is white on a white dimmer, so it's invisible.

### Version
0.82.2

### Testcase
https://codesandbox.io/s/k2r1oqq4p7

**Comment by TheBurnerGuy** [comment]
It seems like it's only a google-chrome issue; I've tested it on firefox and the scrollbars appeared fine.

**Comment by brianespinosa** [comment]
@TheBurnerGuy all of the css is coming from the [`semantic-ui` repository](https://github.com/semantic-org/semantic-ui/). You'll need to open your issue there. This project only contains the React components that render SUI markup. That can technically be targeted with CSS, but we don't handle any of that here.
