### ISSUE TITLE
Button: Can only set one of `children` or `props.dangerouslySetInnerHTML`.

### ISSUE THREAD

**Issue by danbruegge** [Semantic-Org/Semantic-UI-React#3097]
### Steps
Set `dangerouslySetInnerHTML` to `Button`.

```jsx
<Button dangerouslySetInnerHTML={{ __html: "<i>Hello</i>" }} />
```

### Expected Result
`Button` will render correctly without error message.

### Actual Result
This error message:
```markdown
Can only set one of `children` or `props.dangerouslySetInnerHTML`.
```

### Version
0.82.2

### Testcase
https://codesandbox.io/s/ryn1omp5oo

**Comment by layershifter** [comment]
The reason of issue is rendering of multiple elements in `Button`.

I almost sure that we don't need to fix this, it's possible that @levithomason has another opition. As workarounds you can use:
- inner child
- [react-html-parser](https://www.npmjs.com/package/react-html-parser) (I recomend it)

See in action, https://codesandbox.io/s/m4w492q0py
