### ISSUE TITLE
Test with jest

### ISSUE THREAD

**Issue by InsideGH** [Semantic-Org/Semantic-UI-React#3100]
Hi all,

My testcases with an open Modal breaks when I step up react-semantic from version v.0.81.3 -> v.0.82.0.

**The test case:**

import React from 'react'
import renderer from 'react-test-renderer'
import Success from 'app/Success'

const showProps = {
  show: true,
  onClose: () => {}
}

test('renders open', () => {
  const component = renderer.create(<Success {...showProps}/>)
  let tree = component.toJSON()
  expect(tree).toMatchSnapshot()
})

**The error message (from inside react-test-renderer):**
TypeError: parentInstance.children.indexOf is not a function

Any tips on how to get around this or fix it is much appreciated.

Thanks Peter.

**Comment by layershifter** [comment]
In `0.82.0` we begin to use `React.createPortal` API. The described issue known and comes from `react-test-render`:

https://github.com/reactjs/react-modal/issues/553
https://github.com/mui-org/material-ui/issues/9243
https://github.com/facebook/react/issues/11565

As I see resolution was merged https://github.com/facebook/react/pull/12895 and will be shipped with `react@16.4.3` ✌️ You can check `16.4.3-alpha.0`, however I don't recomend to use it in production.

The best is wait for issue resolution I think. We have similar issue in docs, #3020 😭
