### ISSUE TITLE
Make sticky component fit into container?

### ISSUE THREAD

**Issue by oleksandrkyselov** [Semantic-Org/Semantic-UI-React#3102]
Hello!

I wonder how it's possible to implement [https://react.semantic-ui.com/modules/sticky/#types-adjacent-context](url) inside a container without overlapping it. 

I'm trying to implement the [https://codepen.io/othbert/pen/MOWBja](url) solution provided but in React.

Representation of the problem:

![image](https://user-images.githubusercontent.com/10980733/44484901-4e3c4500-a64f-11e8-9b76-5da7b9233328.png)

Thanks!

**Comment by layershifter** [comment]
Please use Stackoverflow for questions, we have a dedicated tag there: https://stackoverflow.com/questions/tagged/semantic-ui-react

If this issue is a bug report, please fill it fully.
