### ISSUE TITLE
Table sorting is case sensitive. Would be nice to be able to override somehow

### ISSUE THREAD

**Issue by hanshenrik** [Semantic-Org/Semantic-UI-React#3105]
### Problem description
`<Table sortable>` is case sensitive.

<img width="490" alt="screen shot 2018-08-24 at 16 01 17" src="https://user-images.githubusercontent.com/3757042/44588796-fcaeca00-a7b6-11e8-9c45-ee8f88772dbb.png">

### Proposed solution
1. Possible to pass some options tweaking the sorting algorithm, e.g. `<Table sortable={{ isCaseSensitive: false }}>`
2. Possible to override the sorting algorithm, e.g. `<Table sortable={values => mySortingAlgorithm(values)}>`

**Comment by layershifter** [comment]
Please check the example again, http://react.semantic-ui.com/collections/table/#variations-sortable

The `sortable` prop offers only styling, the sorting process is performed there:
```js
      this.setState({
        column: clickedColumn,
        data: _.sortBy(data, [clickedColumn]),
        direction: 'ascending',
      })
```

You can replace `_.sortBy` with your custom function.

**Comment by hanshenrik** [comment]
Wow, that's embarrassing 🙈 Thanks for the quick response!
