### ISSUE TITLE
Responsive: Not rendering correctly with SSR

### ISSUE THREAD

**Issue by teoraunio** [Semantic-Org/Semantic-UI-React#3110]
## Bug Report
I am trying to create a top bar which uses two Responsive elements to determine if it should render content for over or under 1000 pixel resolution. The app is using server side rendering.

The problem _(code below to understand the props and classes)_:
When the window size is over 1000 pixels, it will render a Responsive element that has `minWidth={1000}` as expected, but the first element inside the Responsive is actually from the other Responsive element with `maxWidth={1000}`

So what happens is:
1. The server renders the element with `maxWidth=1000` as `window` doesn't yet exist and the width is set to 0 inside the Responsive component.
2. Client re-renders it according to acquired window width and now chooses to use the Responsive element with `minWidth=1000`
3. The `<div>` element that should have class `desktop-content-1` has falsely class `mobile-content` that is defined inside the other `Responsive` element.

I am aware that this can be fixed by wrapping both Responsive elements in separate containers, but it means using unnecessary elements and it should at least be specified in the documentation.

### Steps
You need an app that uses Server Side Rendering with the following piece of code rendered to reproduce the problem:

```
<div className="top-bar">
  <Responsive minWidth={1000}>
    <div className="desktop-content-1" />
    <div className="desktop-content-2" />
  </Responsive>
  <Responsive maxWidth={1000}>
    <div className="mobile-content" />
  </Responsive>
</div>
```

### Expected Result
The width of the window is over 1000 pixels.

```
<div class="top-bar">
  <div>
    <div class="desktop-content-1" />
    <div class="desktop-content-2" />
  </div>
</div>
```

### Actual Result
The width of the window is over 1000 pixels.

```
<div class="top-bar">
  <div>
    <div class="mobile-content" />
    <div class="desktop-content-2" />
  </div>
</div>
```

### Version
0.77.1

**Comment by layershifter** [comment]
@teoraunio thanks for the detailed report!

1. Please update to latest version :cat: 
2. The latest version contains the [`getWidth`](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.82.3/src/addons/Responsive/Responsive.js#L50) prop, by default width will be always `0` for SSR. You can override it with this prop.
3. Use `fireOnMount` prop, it should solve your issue, because listeners are fired on `resize` & `scroll` by default.

```jsx
const getWidth = () => {
  if (isBrowser) return window.innerWidth
  return 1000
}

<div className="top-bar">
  <Responsive fireOnMount getWidth={getWidth} minWidth={1000}>
    <div className="desktop-content-1" />
    <div className="desktop-content-2" />
  </Responsive>
  <Responsive fireOnMount getWidth={getWidth} maxWidth={1000}>
    <div className="mobile-content" />
  </Responsive>
</div>
```

---

If issue will not be solved, just ping me and I will reopen it. Can you please also create an example repo with a preconfigured env, if it will persist?

**Comment by teoraunio** [comment]
@layershifter Thanks for your quick reply!

Unfortunately, this did not fix the issue. Now exactly the same is happening if the window width is less than 1000 pixels in the first render. 

So when the child div's className should be `mobile-content` it is `desktop-content-1` instead:

```
<div class="top-bar">
  <div>
    <div class="desktop-content-1">
      {/* correct mobile content inside */}
    </div>
  </div>
</div>
```
The content inside the div is correct, only the className is incorrect.

I am not able to create an example repo at the moment but I may look into it later on if necessary.

**Comment by layershifter** [comment]
Yes, please create a repo with a simple example.

**Comment by layershifter** [comment]
I've updated a message (fixed `getWidth()`).

I've checked all should work correct, waiting for a repro repo. Please keep it simple.

**Comment by layershifter** [comment]
Will reopen if we will receive a repro case.

**Comment by JustinTRoss** [comment]
This didn't work for me either. I'll try to get a repro repo over tomorrow.

**Comment by JustinTRoss** [comment]
Nvm. Replacing your `getWidth` with the following fixed it.

```
const isBrowser = () => typeof window !== 'undefined'
const getWidth = () => {
  if (isBrowser()) return window.innerWidth
  return Infinity
}
```
Thanks for the help!

**Comment by layershifter** [comment]
https://github.com/Semantic-Org/Semantic-UI-React/issues/3361#issuecomment-453202401

My comment there contains working solutions.
