### ISSUE TITLE
Error in production build when using webpack DLLPlugin, related to sideEffects setting

### ISSUE THREAD

**Issue by mhgamework** [Semantic-Org/Semantic-UI-React#3111]
## Bug Report
I recently upgraded to latest semantic-ui-react, and now webpack seems to not correctly bundle all semantic-ui-react chunks in production builds.

When i set sideEffects:false in vendor.js build, the problem goes away, so i think this is related to webpack treeshaking and the recent setting of "sideEffects" in semantic-ui-react

### Steps
I made a reproduction project, see below. Basically the steps are
 - Build a vendor.js that uses the DllPlugin to put semantic-ui-react in a separate bundle
 - Build the main.js that uses the dllplugin to reference vendor.js
 - Browse to the react app

### Expected Result
App should render

### Actual Result
App throws on loading webpack imports:

```
vendor.js:21 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (vendor.js:21)
    at Module.hasOwn (vendor.js:352)
    at __webpack_require__ (vendor.js:21)
    at Module.<anonymous> (vendor.js:2940)
    at __webpack_require__ (vendor.js:21)
    at Module.<anonymous> (vendor.js:18245)
    at __webpack_require__ (vendor.js:21)
    at Module.<anonymous> (vendor.js:18208)
    at __webpack_require__ (vendor.js:21)
    at Module.module.exports (vendor.js:26903)
```
### Version
0.82.2

### Testcase
Uploaded as zip as it is a custom build. [Sleek.WebSites.App.zip](https://github.com/Semantic-Org/Semantic-UI-React/files/2327409/Sleek.WebSites.App.zip)

- npm install
- npm run start => builds vendor.js, main.js, and serves
- Go to http://localhost:5000
- this fails with error

Workaround:
 - Stop serve
 - enable sideEffects:false in webpack.config.vendor.js
 - npm run start
 - Page now doesnt show error

**Comment by layershifter** [comment]
@mhgamework Thanks for the report, but it's a Webpack issue. I'm not enough familar with its internals, so please move it there.

---

Similar issues:
https://github.com/webpack/webpack/issues/7425
https://github.com/webpack/webpack/issues/7499#issuecomment-396831278

---

I've recently checked, without DllPlugin everything works fine.
