### ISSUE TITLE
Clicking inside nested modal causes both outer and inner modal to close

### ISSUE THREAD

**Issue by onoufriosm** [Semantic-Org/Semantic-UI-React#3113]
## Bug Report

Clicking inside nested modal causes both outer and inner modal to close

### Steps
1. Follow link https://codesandbox.io/s/8lmyv07pm8
2. Click 'Open outer modal'
3. Click 'Open inner modal'
4. Click anywhere inside the inner modal (But not the close button!)
5. See both modals close

If you change semantic-ui-react dependency to v0.81.3 everything works as expected (https://codesandbox.io/s/n40kovrym4)

### Expected Result
None of the modals close

### Actual Result
Both modals close

### Version
0.82.3

### Testcase
https://codesandbox.io/s/8lmyv07pm8

---------------------------------------------------------
It's possible that a different implementation of animated modal would solve this problem. If anyone has any working solution of animated modals and is willing to share it that would be very helpful!

**Comment by layershifter** [comment]
There are no issues with Modals: https://codesandbox.io/s/7j7xlk66o1

----

`TransitionablePortal` and `Modal` has different lifecycle ideas, it's not correct to mix them. I also don't have a solution from one side, from other side there are no issue that should be fixed.

`0.82.0` and higher use new API from React and differently handle clicks on Dimmer. I hope that we will have working transitions in future releases. Help there is highly appricated.

If someone has a temporiary workaround, please share it :+1:
