### ISSUE TITLE
Missing Flag South Sudan

### ISSUE THREAD

**Issue by yeahoffline** [Semantic-Org/Semantic-UI-React#3114]
## Feature Request
Missing Flag for South Sudan (dropdown country selector throws warning)

### Problem description
South Sudan: https://en.wikipedia.org/wiki/Flag_of_South_Sudan
ISO 3166 code: SS

**Comment by brianespinosa** [comment]
@yeahoffline all of the css and images for flags is coming from the [`semantic-ui` repository](https://github.com/semantic-org/semantic-ui/). You'll need to open your issue there. This project only contains the React components that render SUI markup.

**Comment by autohub7** [comment]
These countries are missing on the list: 
South Ossetia
South Sudan
Federated States of Micronesia
Somaliland
Abkhazia
Kosovo
Transnistria

Also, there are two Serbia with different countryCode in the example. 
  { name: 'Serbia', countryCode: 'cs' }
  { name: 'Serbia', countryCode: 'rs' }

**Comment by brianespinosa** [comment]
@autohub7 please see the comment directly above yours about the correct location on where to post requests for missing flags or countries. They are not contained in this repository.
