### ISSUE TITLE
Saint-Barthélemy flag missing

### ISSUE THREAD

**Issue by yeahoffline** [Semantic-Org/Semantic-UI-React#3115]
## Feature Request
https://en.wikipedia.org/wiki/Flag_and_coat_of_arms_of_Saint_Barth%C3%A9lemy

### Problem description
ISO 3166 code BL should be mapped to FR flag

**Comment by brianespinosa** [comment]
@yeahoffline all of the css and images for flags is coming from the [`semantic-ui` repository](https://github.com/semantic-org/semantic-ui/). You'll need to open your issue there. This project only contains the React components that render SUI markup.
