### ISSUE TITLE
Color attribute for Table.*

### ISSUE THREAD

**Issue by AmirHMousavi** [Semantic-Org/Semantic-UI-React#3117]
## Feature Request
Color attribute for Table.*
### Problem description
I found it needed when I was making a board game. a selectable Table.Cell, Table.Row makes it easy to handle events on a table, but coloring it was the only reason I had to search for other solution.

**Comment by layershifter** [comment]
We support colors for [Table](http://react.semantic-ui.com/collections/table/#variations-colors), most advanced features should be implemented in SUI core: https://github.com/Semantic-Org/Semantic-UI

**Comment by badunius** [comment]
No, you support colors for the _entire_ table, whereas color-coding single cell is limited to warning/positive/negative/active/disabled

**Comment by Miri-volo** [comment]
I know its an old issue but we use semantic at my work, i had the same problem with my table, i added this and it worked: 

`<Table.Cell style={{backgroundColor: "red"}}> some text </Table.Cell>`

also worked for coloring headers :

`<Table.HeaderCell style={{backgroundColor: "red"}}>header text</Table.HeaderCell>`
