### ISSUE TITLE
Avoid depending on entire lodash library

### ISSUE THREAD

**Issue by acarl005** [Semantic-Org/Semantic-UI-React#3119]
After gzip and minify, lodash is adding over 20kB to the JS bundle size, which is kind of heavy. Most of the methods being used in the source code (`_.invoke`, `_.isNil`, `_.each`, `_.map`) have native equivalents. Other functions without native equivalents can be required individually, allowing the bundler to easily eschew unused code.

```js
// const _ = require('lodash')
// _.difference(...)
// instead do this
const difference = require('lodash/difference')
```

Avoiding requiring the whole lodash library would reduce bundle sizes very nicely.

**Comment by layershifter** [comment]
Duplicate #830.
