### ISSUE TITLE
Checkbox component is not passing the input element into onChange event

### ISSUE THREAD

**Issue by xumix** [Semantic-Org/Semantic-UI-React#3120]
## Bug Report
`<Checkbox>` component is not passing the input element into onChange event

### Steps
A clear and concise description of steps to reproduce the problem.
```
<Form.Field 
control={Checkbox} label="Smth"
 checked={store.checked}
 onChange={e => 
//e.target <---- div
//e.currentTarget <---- label
}/>

```
### Expected Result
`e.currentTarget == input`

### Actual Result
```
e.target <---- div
e.currentTarget <---- label
```

### Version
0.82.2

**Comment by brianespinosa** [comment]
@xumix this is expected. Take a look at the docs for Checkbox and the onChange prop. SUIR passes the original React synthetic event, and data. A good example of this is https://react.semantic-ui.com/modules/checkbox/#types-radio-group
