### ISSUE TITLE
proposal: work around inconsistent SUI margin for close/delete buttons in <Label />

### ISSUE THREAD

**Issue by cdaringe** [Semantic-Org/Semantic-UI-React#3126]
### Problem description

- SUI and SUIR label buttons have (likely) unexpected margin when applying a floating `<Label />`

example:

```jsx
<Label color='red' floating onRemove={() => {}} />
```

yields:

![screen shot 2018-09-04 at 3 20 23 pm](https://user-images.githubusercontent.com/1003261/45061029-749eaf00-b057-11e8-8b76-09013f59b985.png)

see the extra margin in the red button in comparison to the blue button.  the `close`/`delete` button classes add ~0.5 em margin-left.

this is true for SUI as well.  applying the same resultant HTML on their site, it yields:

![screen shot 2018-09-04 at 3 26 38 pm](https://user-images.githubusercontent.com/1003261/45061049-8da76000-b057-11e8-9c56-b5e3d1a3ba61.png)

### Proposed solution

- on usage of the `onRemove` prop, squash the style to be `marginLeft: 0`

### Discussion

i have not yet filed a bug upstream in SUI.  something tells me they may desire this behavior for some other effect.

**Comment by layershifter** [comment]
@cdaringe it makes a sense, however we don't apply styles there. The best option will be open issue and PR in the main repo :+1:
