### ISSUE TITLE
Responsiveness not working for input with dropdown

### ISSUE THREAD

**Issue by vishveshcoder** [Semantic-Org/Semantic-UI-React#3127]
### Steps
There is a dropdown embedded in input type box. As values of dropdown are rather large instead of trying to squeeze them in multiple lines. It outflows from the screen.
  <Input
                            label={<Dropdown 
                                        direction='left'
                                        placeholder='Select Currency' 
                                        search 
                                        options={allCurrencies && this.currencyMap(allCurrencies, "-1")}
                                      
                                    />}
                            labelPosition='right'
                            direction='right'
                            placeholder='Your Deposit'
                            value = '100'
                        />
### Expected Result
Even on small screen big values should in dropdown should not overflow.
### Actual Result
It went outside the screen. With big values in dropdown options.
### Version
0.80.2

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/jp2nxzojw3
[semantic-ui-react.zip](https://github.com/Semantic-Org/Semantic-UI-React/files/2351658/semantic-ui-react.zip)

**Comment by layershifter** [comment]
Please create a minimal repro on codesandbox. Sorry, but we don't have time to debug your code.
