### ISSUE TITLE
Support Windows env var assignments

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#313]
Per #304, we do not support Windows env var assignments.  We should probably use [cross-env](https://www.npmjs.com/package/cross-env) for this.

``` sh
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Joshua\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.3
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE
npm ERR! stardust@0.16.4 prepublish: `NODE_ENV=production npm run build:dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stardust@0.16.4 prepublish script 'NODE_ENV=production npm run build:dist'.
```

**Comment by levithomason** [comment]
@davezuko also noted:

> @levithomason we will probably want to use better-npm-run or our own setup so that we can define environment variables in npm scripts. This is related to at least one of @joshuazmiller's errors. Windows uses set FOO=bar rather than FOO=bar, and this is mainly what better-npm-run takes care of.

**Comment by dvdzkwsk** [comment]
Linking https://github.com/TechnologyAdvice/stardust/issues/315

**Comment by joshuazmiller** [comment]
Linking #316 as my suggested fix
