### ISSUE TITLE
Modal inside a table flicker

### ISSUE THREAD

**Issue by zeagord** [Semantic-Org/Semantic-UI-React#3132]
When we use a modal inside a table, it starts flickering. It is related to the issue here #2563  and the code sample is there in this comment.
https://github.com/Semantic-Org/Semantic-UI-React/issues/2563#issuecomment-381619700
https://codesandbox.io/s/2zzrjk7qxp

**Comment by layershifter** [comment]
It's not clear what you mean, an example on codesandbox doesn't contain tables. I'm not able to reproduce it.

Please:
1) use latest versions of SUI and SUIR
2) fill our issue template fully
