### ISSUE TITLE
<Modal.Actions> with shortcut actions={[]} does not close the modal

### ISSUE THREAD

**Issue by xumix** [Semantic-Org/Semantic-UI-React#3136]
## Bug Report
`<Modal.Actions>` with shortcut actions={[]} does not close the modal

### Steps
```
<Modal trigger={<Button>Show Modal</Button>} closeIcon dimmer={"inverted"}>
    <Header icon='archive' content='Archive Old Messages' />
    <Modal.Content>
      <p>
        Your inbox is getting full, would you like us to enable automatic archiving of old messages?
      </p>
    </Modal.Content>
<Modal.Actions actions={["Close"]} />

  </Modal>
```

### Expected Result
Closed modal on button click

### Actual Result
the modal is not closed

### Version
v0.82.3

**Comment by brianespinosa** [comment]
@xumix please create a minimal example of the problem you are experiencing in a codepen or codesandbox. I can reopen the issue and take a look for you once you have an example.

This works when using `actions={["Close"]}` in the docs examples.

**Comment by layershifter** [comment]
Duplicate #2892.
