### ISSUE TITLE
menu bar is rounded at the corner, making it look like it doesnt cover the whole screen

### ISSUE THREAD

**Issue by AlbertMart32** [Semantic-Org/Semantic-UI-React#3137]
heres a picture that can better explain it

![screenshot from 2018-09-05 22-02-53](https://user-images.githubusercontent.com/29220820/45143608-9475c600-b170-11e8-865b-555a79e5d46d.png)

**Comment by layershifter** [comment]
Please use StackOverflow for usage questions: https://stackoverflow.com/questions/tagged/semantic-ui-react
