### ISSUE TITLE
Invalid prop `as` supplied to `MenuItem` when using a custom component.

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#3138]
## Bug Report

Hi, previously I could specify the "as" property to MenuItem as a custom component. This is a key functionality if I want to use custom Link components, such as those from React router or Reach Router.

### Version
0.82.3

### Testcase

Here you go (check out the console):

https://codesandbox.io/s/q71qy7kw6q

**Comment by layershifter** [comment]
Fixed in #3139.
