### ISSUE TITLE
Create Contributing Guidelines

### ISSUE THREAD

**Issue by dvdzkwsk** [Semantic-Org/Semantic-UI-React#314]
Many open source projects post [contributing guidelines](https://github.com/blog/1184-contributing-guidelines) that detail things like PR workflow, preferred commit message formatting, and more. Per the provided link, Github also informs users of its existence before they contribute to point them in the right direction. I think this would be a useful addition and could potentially reduce unnecessary correctional PR comments.

**Comment by levithomason** [comment]
👍 The first order of business for me on this front is to write "How to write a component".  I've just started this.  We can link it in a CONTRIBUTING.md.  I would love for someone to start this doc too.

**Comment by levithomason** [comment]
I'm on this, PR up shortly...
