### ISSUE TITLE
Conditional element attribute rendering

### ISSUE THREAD

**Issue by vlautac** [Semantic-Org/Semantic-UI-React#3147]
I'm trying to setup a conditional element rendering on an Input component but I don't success to do it.
I'd like to change the state of my Input to error when the validation on it fails like:
```
 <Input { this.state.isValid ?? error } id="message" type="text" placeholder="Write anything..." />
```
Unfortunately, I can not do it like that and need to change the way to render it using a conditional boolean state like below:
```
{ this.state.isValid
    ? <Input id="message" type="text" placeholder="Write anything..." />
    : <Input error id="message" type="text" placeholder="Write anything..." />
}
```
I don't want to duplicate the Input element.. Is there any other way to manage it?

**Comment by layershifter** [comment]
Please use StackOverflow for usage questions, we have a dedicated tag there: https://stackoverflow.com/questions/tagged/semantic-ui-react

----

This question is a generic for React, solutions:

```jsx
 <Input error={this.state.isValid} />
 <Input {... (this.state.isValid ? {} : { error: true}}) />
```
