### ISSUE TITLE
Search control gives console warning when it renders.

### ISSUE THREAD

**Issue by anuragsinghtomar** [Semantic-Org/Semantic-UI-React#3150]
### Steps
When the search control renders on page. It will give following warning on console.

Warning: Failed prop type: Prop `input` in `Search` conflicts with props: `children`. They cannot be defined together, choose one or the other.
    in Search (created by AutoSearchComponent)
    in AutoSearchComponent (created by AppHeaderComponent)
    in div (created by ModalDescription)
    in ModalDescription (created by AppHeaderComponent)
    in div (created by ModalContent)
    in ModalContent (created by AppHeaderComponent)
    in Transition (created by AppHeaderComponent)
    in div (created by Modal)
    in Ref (created by Modal)
    in div (created by Modal)
    in Ref (created by PortalInner)
    in PortalInner (created by Portal)
    in Portal (created by Modal)
    in Modal (created by AppHeaderComponent)
    in header (created by AppHeaderComponent)
    in div (created by AppHeaderComponent)
    in AppHeaderComponent (created by Connect(AppHeaderComponent))
    in Connect(AppHeaderComponent) (created by Route)
    in Route (created by withRouter(Connect(AppHeaderComponent)))
    in withRouter(Connect(AppHeaderComponent)) (created by PrimaryLayoutComponent)
    in div (created by PrimaryLayoutComponent)
    in PrimaryLayoutComponent (created by Connect(PrimaryLayoutComponent))
    in Connect(PrimaryLayoutComponent) (created by Route)
    in Route (created by AuthorizedRouteComponent)
    in AuthorizedRouteComponent (created by Connect(AuthorizedRouteComponent))
    in Connect(AuthorizedRouteComponent)
    in Switch
    in div
    in Router (created by BrowserRouter)
    in BrowserRouter
    in PersistGate
    in Provider

### Expected Result
Warning should not come on console

### Actual Result
Above said warning comes every time when it renders.

### Version
0.8.2.1

**Comment by layershifter** [comment]
Please make a minimal repro, the warning is correct because `Search` doesn't handle the `children` prop.

**Comment by layershifter** [comment]
I am going to close the issue, but will reopen if will have a repro on codesandbox. Ping me when it will be ready.
