### ISSUE TITLE
Message padding in accordion not right.

### ISSUE THREAD

**Issue by lery12** [Semantic-Org/Semantic-UI-React#3151]
### Steps
When i make a component like:
```
      <Accordion styled>
        <Accordion.Content active>

<!-- message 1 --->
          <Message content={ <p>here the content with to much padding</p> } />

<!-- message 2 --->
          <Message>
          here the content with the right padding.
          </Message>

        </Accordion.Content>
      </Accordion>
```

### Expected Result
Both messages have the same padding in the accordion.

### Actual Result
second messages has normal padding, while second has more padding.

### Version
https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.css
https://unpkg.com/semantic-ui-react/dist/umd/semantic-ui-react.min.js
See codepen.

### Testcase
https://codepen.io/lery/pen/GXdqRZ

**Comment by layershifter** [comment]
It's a valid CSS issue, please move it to the main repo: https://github.com/Semantic-Org/Semantic-UI

Styled `Accordion` applies styles to elements with `content` CSS class, it the same time `Message.Content` has it.

```jsx
<Message content={ <p>here the content with to much padding</p> } />
// is equal with
<Message>
  <Message.Content>
    <p>here the content with to much padding</p>
  </Message.Content>
</Message>
```
