### ISSUE TITLE
Dropdown item's option.value proptype should support PropType.object

### ISSUE THREAD

**Issue by mattdarveniza** [Semantic-Org/Semantic-UI-React#3153]
### Problem description
I've noticed that semantic-ui's dropdown and dropdown item components expect value to be either a boolean, number or string. I've read #1368 about this issue, where it was suggested there were problems with implementing this, a PR was created but never merged due to other issues with the changes that seem unrelated to this feature specifically as far as I can tell.

This previous issue just seemed to die without any resolution so I'm reopening here, as I believe this functionality is still desirable.

I've played with passing objects as the dropdown item value and aside from the propTypes warnings and duplicate key warnings (due to [Object object] stringification which is easily resolvable with custom keys) it works just fine for my case at least: onChange fires correctly with the correct value returning as an object.

From previous issues raised about this I'm unsure what the actual problem is that's preventing this from being supported?

I've seen suggestions for using JSON.stringify() or a lookup table for each item, but both of these seem like less than ideal workarounds compared to just passing in the desired object as a value when that's the output you want from onChange.

### Proposed solution
`Dropdown.Item.propTypes.value = PropTypes.oneOfType([PropTypes.number, PropTypes.string, PropTypes.bool, PropTypes.object)]`

Obvious drawbacks are: if there's a genuine reason why this will break functionality.

**Comment by layershifter** [comment]
It's an overcomplicated feature for the overcomplicated component (1395 lines in `Dropdown.js`). You can create a wrapper component that will support this because it will bring a ton of bugs.

I don't want even to try implement this feature. Possible, @levithomason has another opinion.

**Comment by mattdarveniza** [comment]
That's disappointing but understandable. For what it's worth I'm currently using it with objects and merely overriding the proptypes and it works well at least for my use case. You are right that it's a complex component that does a lot and has a lot of varying functionality, but it works fine in at least simple cases.

If there's no desire to pick this up I guess I'll just wrap the component ¯\_(ツ)_/¯. Thanks for the reply.
