### ISSUE TITLE
Dropdown: loses focus after a selection has been removed

### ISSUE THREAD

**Issue by Chrn** [Semantic-Org/Semantic-UI-React#3158]
## Bug Report
The dropdown loses focus after a selection has been removed. It is similar to this issue except it is on remove instead of select
https://github.com/Semantic-Org/Semantic-UI/issues/1253

### Steps
1. Expand the dropdown
2. Select an item
3. Remove the selected item
4. Try to search

### Expected Result
The search input box to be in focus

### Actual Result
The search input box loses focus and cannot search for another item

### Testcase
Can be reproduced on the dropdown found on the semantic react page
http://react.semantic-ui.com/maximize/dropdown-example-multiple-search-selection/

**Comment by extern-c** [comment]
@layershifter, can I work on this?

**Comment by hasen011** [comment]
Hi, just curious, any progress on this? Thanks!

**Comment by layershifter** [comment]
Was fixed in #3452.
