### ISSUE TITLE
Dropdown menu: direction left is not working inside a .dropdown.simple

### ISSUE THREAD

**Issue by romgrk** [Semantic-Org/Semantic-UI-React#3159]
### Steps
 - Create a left dropdown menu inside a simple dropdown menu
 - Try to open it

### Expected Result
The sub-menu opens left.

### Actual Result
The sub-menu open right.

### Version
2.2.12 & 2.3.3

### Testcase
http://jsfiddle.net/romgrk/6bazoxqu/4/

**Comment by brianespinosa** [comment]
@romgrk your jsfiddle does not contain Semantic UI React. It is only HTML and CSS. Did you just copy the rendered HTML from your project and paste there? We'll need to see your actual SUIR components and the props you have set on them to be able to take a look at this.

When you create a new JSFiddle with your actual components showing this issue we can reopen. If you need help, there is actually a Codesandbox template in our bug report form to get you started.
