### ISSUE TITLE
Dropdown: Accessible labels don't work for this element

### ISSUE THREAD

**Issue by cstrat** [Semantic-Org/Semantic-UI-React#3160]
### Steps
In the sandbox, I've copied the example code from the documentation on [accessible labels](https://react.semantic-ui.com/collections/form/#shorthand-field-control-id) and added a Dropdown.

### Expected Result
Expectation would be that the Dropdown gets focus when the label is clicked as with all other form fields.

### Actual Result
Clicking the label doesn't have an effect.

### Version
0.82.5

### Testcase
https://codesandbox.io/s/1o9yjrrq84

**Comment by cstrat** [comment]
I just noticed this [PR](https://github.com/Semantic-Org/Semantic-UI-React/pull/3149) - looks like this has already been raised and isn't seen as a bug.

**Comment by layershifter** [comment]
Yep, see #3157 for usage example.

**Comment by cstrat** [comment]
Thanks I will take a look, at the moment it looks as though it only works if you set the field as a `search` dropdown. Not just a normal dropdown, or am I mistaken?

**Comment by layershifter** [comment]
@cstrat yes, you're right. Checked your example again, I created [a sandbox](https://codesandbox.io/s/74yqw660x) with workaround.

Have no idea how this can be fixed in the core. The root of problem is a missing input in `Dropdown`. Feel to free to submit PR if you have a better idea 👍

**Comment by cstrat** [comment]
Oh wow thanks so much!
I didn't even think to try something like that.
It definitely isn't as simple as what I was hoping for but it gets the job done.

I've never submitted a PR before but I will take a look to see if I can find a way around it.
