### ISSUE TITLE
docs: does not work on iOS Safari

### ISSUE THREAD

**Issue by fracmak** [Semantic-Org/Semantic-UI-React#3163]
### Steps
Load http://react.semantic-ui.com/ on safari browser on an iPad or iPhone (confirmed in iOS11 or iOS12). The main page will load, but click on any component or navigate directly to said component page.

### Expected Result
Not a blank screen

### Actual Result
Blank screen

### Version
x.y.z

**Comment by achimkoellner** [comment]
Same Problem, homepage works, icons-page does not work:
http://react.semantic-ui.com/elements/icon/

**Comment by simpleigh** [comment]
👍 same for me on Edge 42.17134.1.0

**Comment by hgezim** [comment]
This is a huge showstopper. I have to fire up Firefox just to see docs.

**Comment by layershifter** [comment]
Hey, guys! Please check now, I deployed docs with fixed paths. Works like a charm in Edge.

The issue will be solved finally when @levithomason will enforce https in docs. Thanks for the reports to all :+1:
