### ISSUE TITLE
Table body with no data found or no data available

### ISSUE THREAD

**Issue by svenkatesh-nyros** [Semantic-Org/Semantic-UI-React#3170]
### Problem description
I am using the Table component with dynamic result of tbody.How to add a table row when there is no records in the tbody. Like showing "No Results Found! or No data found! in the table body.

### Proposed solution
May be need to add a prop value when tbody no value true or false to show the row.

**Comment by layershifter** [comment]
Thanks, however feature requests that require CSS should be moved into the main repo: https://github.com/Semantic-Org/Semantic-UI

----

However, you can reach similar behaviour.

![image](https://user-images.githubusercontent.com/14183168/45958205-81dc0780-c01f-11e8-9bd4-5fe2af20bf42.png)


```jsx
  <Table celled>
    <Table.Header>
      <Table.Row>
        <Table.HeaderCell>Header</Table.HeaderCell>
        <Table.HeaderCell>Header</Table.HeaderCell>
        <Table.HeaderCell>Header</Table.HeaderCell>
      </Table.Row>
    </Table.Header>

    <Table.Body>
      <Table.Row>
        <Table.Cell colSpan={3}>
          <Header as='h2' textAlign='center' icon>
            <Icon name='settings' />
            Account Settings
            <Header.Subheader>
              Manage your account settings and set e-mail preferences.
            </Header.Subheader>
          </Header>
        </Table.Cell>
      </Table.Row>
    </Table.Body>
  </Table>
```
