### ISSUE TITLE
Vertical divider example broken in documentation

### ISSUE THREAD

**Issue by sgarrity** [Semantic-Org/Semantic-UI-React#3176]
## Bug Report
The [vertical divider example](https://react.semantic-ui.com/elements/divider/#types-vertical) in the documentation is broken.

### Steps
1. Go to https://react.semantic-ui.com/elements/divider/#types-vertical
1. Look at the Vertical Divider example

### Expected Result
Expect to see the "AND" and "OR" dividers appear between the "Lorem ipsum…" columns.

### Actual Result
Actually see the "AND" and "OR" dividers squished up to the left of the other columns.

### Version
0.82.5

### Screenshot
<img width="736" alt="image" src="https://user-images.githubusercontent.com/58062/46181084-3ed99880-c29a-11e8-9b6e-81a3bd2284c6.png">

Perhaps this is related to this [note from the main Semantic UI documentation](https://semantic-ui.com/elements/divider.html#vertical-divider):
> Due to a change in W3C implementation of absolutely positioned elements in flex containers vertical dividers now currently only support 50/50 splits automatically, and only if not positioned as direct children of flex containers (like grid).

**Comment by sgarrity** [comment]
Looks like this may already be tracked in https://github.com/Semantic-Org/Semantic-UI/issues/4342

Apologies if this is a duplicate.

**Comment by jacobwicks** [comment]
If anyone else has this problem, you can get the vertical divider closer to the expected behavior by giving it a style tag:
`<Divider
  vertical
  style={{
    padding: 0,
    margin: 0,
  position: 'relative',
}}
/>`
