### ISSUE TITLE
Some of the icons from arrow icons are not displaying as expected. e.g 'arrows alternate',  'arrows alternate horizontal', 'expand arrows alternate'

### ISSUE THREAD

**Issue by nishav11** [Semantic-Org/Semantic-UI-React#3206]
### Steps
A clear and concise description of steps to reproduce the problem.

### Expected Result
The result that you expected.

### Actual Result
The actual result that happened 💣

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Icons works are expected in docs:
![image](https://user-images.githubusercontent.com/14183168/46720309-dbc40a80-cc78-11e8-88d6-17f7f227b495.png)

Please make sure that you're using matching SUI version:
> for SUI 2.2 use 0.80.2 and below
> for SUI 2.3 use 0.81.0 and higher
