### ISSUE TITLE
Bug in CSS

### ISSUE THREAD

**Issue by riflemanIm** [Semantic-Org/Semantic-UI-React#3207]
.ui.basic.red.label {
    background-color: none #fff!important;
    color: #db2828!important;
    border-color: #db2828!important;
}

As a result, the text in  "Label" is not visible

**Comment by layershifter** [comment]
These was fixed in SUI 2.4. The next release of SUIR will add new features from it, however feel free to use the latest version of SUI, it's fully compatible.

https://github.com/Semantic-Org/Semantic-UI/blob/master/RELEASE-NOTES.md
https://github.com/Semantic-Org/Semantic-UI/pull/6440

**Comment by riflemanIm** [comment]
Fix it  in REACT SUI, please
https://react.semantic-ui.com/elements/label/

**Comment by layershifter** [comment]
It was done in #3162, which bumps the version for docs.

However, you don't need to wait for release to get these fixes, just update SUI in your project.
