### ISSUE TITLE
cog icon works but throws a runtime error:

### ISSUE THREAD

**Issue by brendancol** [Semantic-Org/Semantic-UI-React#3208]
## Bug Report

When using:

```jsx
<Icon name='cog' />
```

The page renders just fine, but the following runtime error is thrown:

``
Warning: Failed prop type: Invalid prop `name` of value `cog` supplied to `Icon`.

Instead of `cog`, did you mean:
  - cogs
  - bug
  - car

    in Icon (at App.js:212)
    in App (created by Connect(App))
    in Connect(App) (at src/index.js:90)
    in Provider (at src/index.js:89)
```
### Version
```
"semantic-ui-css": "^2.3.1", 
"semantic-ui-react": "^0.80.0" 
```

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
`semantic-ui-css@2.3.1` and `semantic-ui-react@0.80.0` aren't compatible. The latest versions contains correct definitions, https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.82.5/src/lib/SUI.js#L731

Please make sure that you're using the latest version of SUI and SUIR, this information is mentioned in docs: http://react.semantic-ui.com/usage#css

```
"semantic-ui-css": "^2.4.0",
"semantic-ui-react": "^0.82.5",
```

**Comment by brendancol** [comment]
@layershifter thanks that solved it
