### ISSUE TITLE
Popup: doesn’t close on document click when the target is a different Popup's trigger

### ISSUE THREAD

**Issue by CoryDuncan** [Semantic-Org/Semantic-UI-React#3210]
### Steps
Render multiple `Popup` components that are triggered on click. Click one `Popup` trigger and then click a different `Popup` trigger.

### Expected Result
The existing `Popup` should close.

### Actual Result
The existing `Popup` does not close.

### Visual Aid
![popup-bug](https://user-images.githubusercontent.com/1120851/46827159-cae4c900-cd4c-11e8-952a-b68dee4dbf89.gif)

### Version
0.82.5 (but seems to have regressed in [0.81.0](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/CHANGELOG.md#v0810-2018-06-03))

### Testcase
https://codesandbox.io/s/rrnn0np6zq

**Comment by kangaechigai** [comment]
Here's the same testcase showing the expected result in v0.80.2:
https://codesandbox.io/s/olow2pprjz
![working](https://user-images.githubusercontent.com/826408/46835836-2cfcf880-cd64-11e8-9bd0-c1f15ecee605.gif)

**Comment by layershifter** [comment]
Duplicate #3006, the issue has been already fixed in `master` #3189 and waiting for release.

Thank you for awesome bug reports :+1:
