### ISSUE TITLE
Broke close icon positioning in Edge and IE on Modal component

### ISSUE THREAD

**Issue by billyjacobs2014** [Semantic-Org/Semantic-UI-React#3216]
## Bug Report
Close Icon is not in the correct location, especially in IE 11 and Edge
### Steps
Open IE 11 or Edge
Open https://react.semantic-ui.com/modules/modal/#variations-close-config
Click on Show Modal which is the last button. 

### Expected Result
To see the close button in the top right corner of the modal

### Actual Result
Close button is missing. 

### Version
0.82.5

### Testcase
You can observe it as described in Steps.

**Comment by layershifter** [comment]
Duplicate #3205, please update your SUI to latest.

https://github.com/Semantic-Org/Semantic-UI-React/issues/3205#issuecomment-429223878
