### ISSUE TITLE
Dimmer/Loaders don't work inside Modals in Safari

### ISSUE THREAD

**Issue by Togrias** [Semantic-Org/Semantic-UI-React#3217]
### Steps

From the Semantic-UI example page:

```
import React from 'react'
import { Button, Header, Image, Modal, Dimmer, Loader } from 'semantic-ui-react'

const ModalModalExample = () => (
  <Modal trigger={<Button>Show Modal</Button>}>
    <Modal.Header>Select a Photo</Modal.Header>
    <Modal.Content image>
      <Image wrapped size='medium' src='https://react.semantic-ui.com/images/avatar/large/rachel.png' />
      <Modal.Description>
        <Header>Default Profile Image</Header>
                  <Dimmer active inverted><Loader/></Dimmer>
        <p>We've found the following gravatar image associated with your e-mail address.</p>
        <p>Is it okay to use this photo?</p>
      </Modal.Description>
    </Modal.Content>
  </Modal>
)

export default ModalModalExample
```

### Expected Result
The loader should spin; the Dimmer should be restricted to the Modal. Try the above using a Chrome browser and it works fine.

### Actual Result
The loader doesn't spin; the Dimmer covers the entire page.

### Version
0.82.5

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
@Togrias all of the CSS is coming from the [Semantic-UI](https://github.com/semantic-org/semantic-ui/). You'll need to open your issue there.

This project only contains the React components that render SUI markup. That can technically be targeted with CSS, but we don't handle any of that here.
