### ISSUE TITLE
Icon.Group withing message does not display properly

### ISSUE THREAD

**Issue by jaworek** [Semantic-Org/Semantic-UI-React#3222]
### Steps
See codepen example.

### Expected Result
Icon group should fit in the message similarly to the single icon.

### Actual Result
Icon group does not fill properly in the Message component. Changing the size of group and icons within, does not allow to fix the problem.

### Version
0.82.5

### Testcase
https://codesandbox.io/s/6v6kyyq7rk

**Comment by layershifter** [comment]
@jaworek this a valid bug, nice catch. However, we can't solve CSS problems in this repo, please post the issue in the main repo: https://github.com/Semantic-Org/Semantic-UI

I made a workaround for you: https://codesandbox.io/s/vn0lxr9647 Needs more styling, but I think that you will understand the way.
