### ISSUE TITLE
Dropdown as Gatsby Link not working

### ISSUE THREAD

**Issue by jpeterson** [Semantic-Org/Semantic-UI-React#3224]
### Steps
Use this project with GatsbyJS, augmenting `Dropdown` as Gatsby's `Link`. It is possible this is an issue with Gatsby Link, not this project.
```js
import { Link } from 'gatsby'
import { Dropdown } from 'semantic-ui-react'
...

<Dropdown as={Link} to="/products" text="Products">
...
</Dropdown>
```

### Expected Result
`Dropdown` should render as a `Link` without any warnings or errors.

### Actual Result
Produces the following warning and doesn't navigate to routes without a page reload.

Warning:
```
Warning: GatsbyLink: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)
```

### Version
0.82.5

### Testcase
NOTE: I was unable to reproduce this using `@reach/router` (which Gatsby's `Link` is wrapping). Both codesandboxes are below.

Not working with `gatsby` (see console on page load):
https://codesandbox.io/s/818n63rm8j

Working as expected with `@reach/router`:
https://codesandbox.io/s/2wzyo0qvw0

**Comment by layershifter** [comment]
I'm not sure that it's real valid usage at all, it also breaks styling.

In the future releases we will forward ref by default, #2844. However, workaround can be done with `forwardRef` API:

```jsx
const ForwardedLink = React.forwardRef((props, ref) => (
  <Link {...props} innerRef={ref} />
));
```

Working Codesandbox: https://codesandbox.io/s/30oypqv2zp

**Comment by jpeterson** [comment]
Thanks for the workaround @layershifter! I think styling works as expected as long as you have the `item` and `simple` props on the Dropdown.

Working Codesandbox (with style): https://codesandbox.io/s/818n63rm8j
