### ISSUE TITLE
How to add associated label to semantic ui dropdown

### ISSUE THREAD

**Issue by ermkd** [Semantic-Org/Semantic-UI-React#3228]
I am using Semantic-UI with plan javascript while testing site auditing i am getting error input doesn't have associated label. On checking i found this is injected dynamic so how can i add associated label to dropdown menu.

**Comment by layershifter** [comment]
We use the issue tracker only for bugs, please use StackOverflow for usage questions:
https://stackoverflow.com/questions/tagged/semantic-ui-react
