### ISSUE TITLE
Popup does not work inside of higher order component

### ISSUE THREAD

**Issue by casperOne** [Semantic-Org/Semantic-UI-React#3231]
### Steps

When using a `Popup` in a higher-order-component, the popup does not render on hover (when `on='hover'`),

### Expected Result

Popup to appear on hover.

### Actual Result

No popup on hover.

### Version
0.83.0

### Testcase

https://codesandbox.io/s/lyq750k9jz

The first button uses `Popup` to display a popup when the containing element (in this case, a `Button`) is hovered over, and it does so.

The second button wraps a `Button` using a higher-order-component, and the `Button` renders fine, but the tooltip does not work.

**Comment by layershifter** [comment]
Hey, it's a known issue :crying_cat_face: Your components should spread rest props, https://github.com/Semantic-Org/Semantic-UI-React/issues/1187#issuecomment-273988903

I've fixed your codesandbox, works fine: https://codesandbox.io/s/7j0lwxqo86
