### ISSUE TITLE
Docs: incorrect link for Semantic UI CSS

### ISSUE THREAD

**Issue by kasu207** [Semantic-Org/Semantic-UI-React#3232]
### Steps
Hi there, I tried to directly link to version 2.4.0 with this snippet:
`<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.0/semantic.min.css"></link>`

### Expected Result
Working UI 

### Actual Result
404 page not found

I switched to a different version of semantic-ui (2.3.0)

**Comment by brianespinosa** [comment]
@kasu207 we do not run [cdnjs](https://cdnjs.com/). This repository is also not responsible for the CSS in the main repo for semantic-ui. If there is a new version of the CSS out that cdnjs does not yet host, you should open an issue with them.

**Comment by layershifter** [comment]
I will corrent a snippet tomorrow, http://react.semantic-ui.com/usage

Thanks for the report.

**Comment by brianespinosa** [comment]
OHHH! Sorry, I did not realize this also applied to our docs examples. Thanks @layershifter

**Comment by layershifter** [comment]
Deployed docs with the correct snippet :+1: 

![image](https://user-images.githubusercontent.com/14183168/47366647-cb834500-d6e6-11e8-82ab-70903504fc77.png)
