### ISSUE TITLE
Popup: hideOnScroll causes Dropdown to close

### ISSUE THREAD

**Issue by mic4ael** [Semantic-Org/Semantic-UI-React#3238]
### Steps
Create a `Dropdown` element within a `Popup`. Try to open the `Dropdown` and scroll down through
its options. `Popup` has to have the `hideOnScroll` prop set.

### Expected Result
I can successfully scroll through the `Dropdown` options.

### Actual Result
Scrolling causes `Dropdown` to close.

### Version
0.83.0

### Testcase
https://codesandbox.io/s/0q5x8pkw1w

**Comment by layershifter** [comment]
My position there is simple, we shouldn't manage such complicated things from the library side. You should use components in controlled mode to get the such behaviour.

Thanks for the well described issue.

**Comment by mic4ael** [comment]
I don't understand why you think like that especially taking into account that this worked perfectly fine on the version `0.82.5`.

**Comment by mic4ael** [comment]
Also what makes things worse, you can't actually click the scrollbar within a `Dropdown` component. Clicking it closes the whole `Popup` as well.

**Comment by mic4ael** [comment]
@levithomason Could you please give an opinion about this? This to me clearly looks like a bug.
