### ISSUE TITLE
Popup: hover behaviour unreliable

### ISSUE THREAD

**Issue by james-ff** [Semantic-Org/Semantic-UI-React#3239]
### Steps
In the Semantic UI & Semantic UI React examples, go to Popup and try the Flowing Example
- You should find that on SUI the Popup on hover closes only when your mouse leaves the bounds of the popup content, but on SUIR the popup content closes unpredictably, even when your mouse is within the popup content bounds.
- I am finding cases in my website where buttons and other interactable components are not able to be interacted with reliably when wrapped in a Popup.

SUI: https://semantic-ui.com/modules/popup.html
SUIR: https://react.semantic-ui.com/modules/popup/

### Expected Result
The Popup hover behaviour on SUIR should match SUI.

### Actual Result
The SUIR Popup on hover mode unreliably closes, even when the mouse is within the bounds of the popup content.

### Version
0.83.0

**Comment by layershifter** [comment]
> You should find that on SUI the Popup on hover closes only when your mouse leaves the bounds of the popup content, but on SUIR the popup content closes unpredictably, even when your mouse is within the popup content bounds.

I tested in Chrome and don't any difference, however SUI has transitions. Can you record a gif? Becuase your issue is not obvious to me.

> I am finding cases in my website where buttons and other interactable components are not able to be interacted with reliably when wrapped in a Popup.

It may be similar to https://github.com/Semantic-Org/Semantic-UI-React/issues/3231#issuecomment-432258707

**Comment by james-ff** [comment]
I'm using the latest non-beta version of Firefox:
- _I am not clicking in either of these recordings, just moving the cursor around_
- To clarify, in SUIR the popup closes unpredictably, but seems to be based on cursor movement
- Do you think that the transition is causing the disparity?

> **SUI:**
![SUI](https://user-images.githubusercontent.com/1874352/47439576-86bde380-d7a4-11e8-8e8a-81c4a14583ee.gif)

> **SUI React:**
![SUIR](https://user-images.githubusercontent.com/1874352/47439594-8de4f180-d7a4-11e8-9d02-e3f3e64a2897.gif)

**Comment by layershifter** [comment]
Now it's more clear, thanks.

**Comment by vanya2h** [comment]
+1. Have same issue!

**Comment by Fabianopb** [comment]
Hello! I've been a heavy user of SUIR for some time and I've been planning to start contributing to this repo.

I've investigated this issue and possibly found a solution, could submit a PR soon.
