### ISSUE TITLE
TextArea styling and functionality not working on any browser

### ISSUE THREAD

**Issue by Puspendert** [Semantic-Org/Semantic-UI-React#3242]
The styling of `TextArea` is not working
The style is same as the `HTML` default `textarea`

### Version
"semantic-ui-css": "^2.4.1",
"semantic-ui-react": "^0.83.0"

Code:
````import React, { Component } from "react"
import { Button, Modal, TextArea, Input } from "semantic-ui-react"
import "semantic-ui-css/semantic.min.css"

class App extends Component {
  render() {
    return (
      <Modal closeIcon trigger={<Button>Long Modal</Button>}>
        <Modal.Header>Test</Modal.Header>
        <Modal.Content>
          <Input type="text" />
          <TextArea autoHeight placeholder="Try adding multiple lines" />
        </Modal.Content>
        <Modal.Actions>
          <Button primary>Save /></Button>
        </Modal.Actions>
      </Modal>
    )
  }
}

export default App
````

Demo repository:
https://github.com/Puspendert/semantic-ui-react-test

![screen shot 2018-10-27 at 1 03 52 pm](https://user-images.githubusercontent.com/16055344/47601069-d260cf00-d9e8-11e8-987b-a18f814c6faf.png)

**Comment by Puspendert** [comment]
Adding `Form` did work.
Any specific reason to design this in such a way?

https://react.semantic-ui.com/addons/text-area/
`TextArea` is wrapped with `Form` in each example, but nowhere is written that it's compulsory to add.

**Comment by layershifter** [comment]
It's required markup by SUI CSS, styles applied for `.ui.form textarea`.
