### ISSUE TITLE
Sporadic warning on multi select dropdown values

### ISSUE THREAD

**Issue by lxm7** [Semantic-Org/Semantic-UI-React#3246]
### Steps
Select values from a multi select dropdown with component implemented with having `fluid, multiple, search, selection` props along with `value={field.value}`. Needs to be a controlled element. 

### Expected Result
No warning, I'm passing an  array, even for the first single value i.e. `["Live"]`

### Actual Result
Receive warning - `Dropdown 'value' must be an array when 'multiple' is set. Received type: [object Null]` This is happening sporadically and can't always recreate every time a value is selected.

### Version
Semantic-ui-react: 0.83.0 (previously had 0.79.)
React: 16.3.1
Next: 7.0.0

**Comment by layershifter** [comment]
Please pass correct values, there was similar discussion in https://github.com/Semantic-Org/Semantic-UI-React/pull/3193#issuecomment-427551740.
