### ISSUE TITLE
Dropdown: Dropdown menu does not close when multiple dropdowns are present.

### ISSUE THREAD

**Issue by dipakkb** [Semantic-Org/Semantic-UI-React#3247]
### Steps
Go to https://qv134ml1m4.codesandbox.io/
try opening Dropdown1, Dropdown2, Dropdown3, Dropdown4..
Notice that multiple dropdown menus are open.

### Expected Result
Currently opened dropdown should close when opening the another one.

### Actual Result
Multiple dropdowns are opened
![multi-dropdown-issue](https://user-images.githubusercontent.com/107630/47712501-40d2a680-dc0e-11e8-8424-5981b4c60ef9.png)

### Version
0.81.3

### Testcase
https://codesandbox.io/s/qv134ml1m4

**Comment by layershifter** [comment]
This was fixed in the lastest version, please update to `semantic-ui-react@0.83.0`.

https://codesandbox.io/s/z2vxmqoxjm

**Comment by dipakkb** [comment]
Thanks for looking into it. 
One query, we are using React 15 and semantic-ui-react 0.81.3 where we observed the issue.
Is the latest version 0.83.0 compatible with React 15?

**Comment by layershifter** [comment]
Nope, it requires React 16.
