### ISSUE TITLE
Popup: Automatically Close when moving cursor inside content of popup

### ISSUE THREAD

**Issue by MrDesjardins** [Semantic-Org/Semantic-UI-React#3249]
### Steps
1- Go in the doc: https://react.semantic-ui.com/modules/popup/
2- Go in the example "flowing"
3- Move your cursor from one button to the other.

### Expected Result
The popup to remain open allowing the user to select a button.

### Actual Result
When moving the cursor, the popup close.

### Version
0.83.0

**Comment by MrDesjardins** [comment]
I found that this is a dupe: https://github.com/Semantic-Org/Semantic-UI-React/issues/3239

I am rollbacking to a previous version.

**Comment by layershifter** [comment]
Duplicate #3239.
