### ISSUE TITLE
Docs: make the filter keyboard shortcut other than "/" (for international keyboards)

### ISSUE THREAD

**Issue by Obiwarn** [Semantic-Org/Semantic-UI-React#3251]
I search for components a lot.

With my German keyboard I cannot use the shortcut "/".

**Comment by levithomason** [comment]
The <kbd>/</kbd> is common for invoking the search in apps in the en-US locale.

### GitHub
![image](https://user-images.githubusercontent.com/5067638/48072934-75a4a780-e192-11e8-921e-70d976988767.png)

### YouTube
YouTube also focuses the search box when pressing <kbd>/</kbd>.
![http://g.recordit.co/XVHsRDEOmc.gif](http://g.recordit.co/XVHsRDEOmc.gif)

***
What is the common key for invoking search in your locale?  What does GitHub show in the search input for you?

**Comment by Obiwarn** [comment]
Just tested Github. They make "/" work as we type it on a German keyboard: Shift + 7

![image](https://user-images.githubusercontent.com/9539797/48076629-e32df380-e1e5-11e8-81ac-954fa014083d.png)

**Comment by levithomason** [comment]
I think I have a fix coming out.  See #3390.
