### ISSUE TITLE
Rating: RatingIcon has tabindex=0 when parent Rating component is disabled

### ISSUE THREAD

**Issue by AndrewLane** [Semantic-Org/Semantic-UI-React#3252]
### Steps
`<Rating rating={1} maxRating={5} disabled size="large" />`

### Expected Result
Since the parent `<Rating>` component is disabled, it doesn't make sense to be able to use the keyboard to focus the individual rating icons.

### Actual Result
The individual rating icons have tabindex=0 so they can be reached via the keyboard.

### Version
0.83.0

### Testcase
https://codesandbox.io/s/7kww573lvx

**Comment by AndrewLane** [comment]
Perhaps this code could be omitted if we're in the disabled case?
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Rating/RatingIcon.js#L97

**Comment by Fabianopb** [comment]
Sounds about right, I'd be happy to contribute to this issue.

**Comment by layershifter** [comment]
@Fabianopb Feel free to make a PR 👍

**Comment by Fabianopb** [comment]
PR created! :)

**Comment by AndrewLane** [comment]
Thank you!
