### ISSUE TITLE
Ref: support `createRef()` API

### ISSUE THREAD

**Issue by sabbiu** [Semantic-Org/Semantic-UI-React#3253]
This is my implementation, but it gives error. `innerRef is not a function. innerRef(findDOMNode(this))`

     function() {
        let el = useRef(null);
        return (
        <Ref innerRef={el}>
            <Table />
        </Ref>
        );
    }

**Comment by layershifter** [comment]
This a valid point, `Ref` component doesn't support `createRef()` API now.
