### ISSUE TITLE
Search Dropdown is closed after click into searchbar

### ISSUE THREAD

**Issue by JaLe29** [Semantic-Org/Semantic-UI-React#3256]
### Steps
Just open your example page - https://react.semantic-ui.com/modules/dropdown/#types-search-in-menu look for **Search In-Menu** dropdown section - open drop-down - click into the search bar.

Code from your example page:

```
  <Dropdown text='Filter Posts' icon='filter' floating labeled button className='icon'>
    <Dropdown.Menu>
      <Input icon='search' iconPosition='left' className='search' />
      <Dropdown.Divider />
      <Dropdown.Header icon='tags' content='Tag Label' />
      <Dropdown.Menu scrolling>
        {tagOptions.map(option => <Dropdown.Item key={option.value} {...option} />)}
      </Dropdown.Menu>
    </Dropdown.Menu>
  </Dropdown>
```

### Expected Result
Dropdown is opened and you can write into search bar

### Actual Result
Dropdown is closed

### Version
0.83.0

**Comment by layershifter** [comment]
Duplicate #1593.
