### ISSUE TITLE
Form.Select, Form.Dropdown doesn't accept defaultValue or value.

### ISSUE THREAD

**Issue by replaysMike** [Semantic-Org/Semantic-UI-React#3259]
Hey guys, I've been digging around for a solution to initially setting the value of a Form.Select (and also tried Form.Dropdown).

I tried what looked to be the previously supported `defaultValue` prop, and later suggestions to using the `value` prop. Neither work, throws an error `Failed prop type: Invalid prop 'value' supplied to 'Dropdown'.` thrown by `checkPropTypes`.

Is this react specific?

**Comment by replaysMike** [comment]
Hrm, works fine with Form.Dropdown, I must have missed something earlier. It's just Form.Select that doesn't seem to have this functionality, so I'll stop using it and switch to Form.Dropdown.

**Comment by layershifter** [comment]
Please fill our issue template fully, `Form.Select` is just an alias for `Form.Dropdown`.

Both components are working correctly: https://codesandbox.io/s/o9y4llrknz

**Comment by BenBrostoff** [comment]
For anyone else who runs into this issue, this is a result of passing an empty object to `value`.
