### ISSUE TITLE
Button: a11y as="button" role="button" is redundant

### ISSUE THREAD

**Issue by fracmak** [Semantic-Org/Semantic-UI-React#3262]
## Bug Report
According to aria/wcag spec, semantic html is preferred over roles, and redundant roles are discourages. This becomes evident when you run dom analysis tools like Axe. So the default behavior of the Button component should not place a role="button". Even if as="button" is added, the role should not appear. Only when as="...." is provided with something other than button should role="button" appear.

![image](https://user-images.githubusercontent.com/378178/48091635-4022ad00-e1d8-11e8-92d2-44f7b40429fc.png)

https://www.w3.org/TR/using-aria/#aria-does-nothing

### Expected Result
DOM structure should be as follows

```
<button class="ui button">Test</button>
```

### Actual Result
The actual result that happened 💣

```
<button class="ui button" role="button">Test</button>
```

### Version
0.83.0

### Testcase
https://codesandbox.io/s/ql6pw0306

**Comment by gauthierm** [comment]
Confirmed. We got our app audited and this was brought up by the folks who tested with screen reading software.

**Comment by layershifter** [comment]
Looks like a correct issue, thanks for the report!

**Comment by floppyvlaDISK** [comment]
Can I contribute to this one?

**Comment by layershifter** [comment]
Yes, feel free to open a PR :)
