### ISSUE TITLE
Pagination control changes size due to contents

### ISSUE THREAD

**Issue by JoelViney** [Semantic-Org/Semantic-UI-React#3265]
### Steps
1. Navigate to https://react.semantic-ui.com/addons/pagination/
2. Scroll down to the Options card
3. Put your cursor on the left edge of the '>' button
4. Click the '>' button a dozen times or so.

You should notice two things: 
a) The pagination controll will change in size.
b) Also if your cursor was far enough left on the '>' button the controll will resize until the cursor is over the '50' button.

### Expected Result
I would expect the pagination control not to change size as I use it.

### Actual Result
The pagination control changes size based on the contents of the buttons

### Version
0.82.5

### Testcase
A url link to an example is provided in the steps.

**Comment by layershifter** [comment]
I'm agree with this, but this issue should be solved on the SUI side because this issue is caused by styles.

You can easily workaround this case with custom styles:
```jsx
<Pagination pageItem={{ style: { minWidth: '4em' }}} />
```

Or with CSS:
```css
.ui.pagination.menu .item {
    min-width: 4em; /* <- you can change this value */
}
```
