### ISSUE TITLE
TypeError · Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by rokoroku** [Semantic-Org/Semantic-UI-React#3267]
## Bug Report
```
TypeError Cannot read property 'reduce' of undefined 
    node_modules/semantic-ui-react/dist/commonjs/lib/AutoControlledComponent.js:193 AutoControlledComponent
    node_modules/semantic-ui-react/dist/commonjs/addons/Portal/Portal.js:65 new t
    node_modules/react-dom/cjs/react-dom.production.min.js:174:470 Rg
    node_modules/react-dom/cjs/react-dom.production.min.js:202:15 xh
    node_modules/react-dom/cjs/react-dom.production.min.js:203:230 yh
    node_modules/react-dom/cjs/react-dom.production.min.js:212:213 Vh
    node_modules/react-dom/cjs/react-dom.production.min.js:211:276 Yh
    node_modules/react-dom/cjs/react-dom.production.min.js:211:112 Wh
    node_modules/react-dom/cjs/react-dom.production.min.js:209:243 Ah
    node_modules/react-dom/cjs/react-dom.production.min.js:207:315 og
```

### Steps
No idea yet (Maybe `<Portal/>` component?) 

### Version
- semantic-ui-react: 0.82.1
- react: 16.4.1

### Affected User Environments
- browserName: Chrome
- browserVersion: 40.0.2214
- locale: en-US
- os: Windows 7
- userAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.85 Safari/537.36

---

I found above error in our error monitoring tool.
Have no idea to repeat this issue yet, but hope this issue can be prevented by adding simple guard code here: 
https://github.com/Semantic-Org/Semantic-UI-React/blob/7da1dd029471f653bac513661d27ac5092ef523d/src/lib/AutoControlledComponent.js#L131-L149

**Comment by layershifter** [comment]
In development we're checking that `autoControlledProps` are defined: https://github.com/Semantic-Org/Semantic-UI-React/blob/7da1dd029471f653bac513661d27ac5092ef523d/src/lib/AutoControlledComponent.js#L80

Sorry, but without a repro case this issue doesn't make a sense. Please also check you aren't using `uglify-es`, it causes really weird bugs:
https://twitter.com/dan_abramov/status/1060216917493981184

**Comment by rokoroku** [comment]
Thanks, that might be the problem. 👍
