### ISSUE TITLE
Using semantic.min.js and semantic-ui-react.min.js on the same page

### ISSUE THREAD

**Issue by aktywnitu** [Semantic-Org/Semantic-UI-React#3268]
How to use semantic.min.js and semantic-ui-react.min.js on the same page?
For example I have problem with Dropdown component (react) (inline style for menu "display:block!important" is added by first library, but is not removed).
Have sombody some nice solution?

**Comment by layershifter** [comment]
We don't recommend to combine JS from Semantic UI and Semantic UI React.

We've done a lot of work to omit jQuery in Semantic UI React and are not responsible for any problems that will be caused by SUI JS.
