### ISSUE TITLE
using Dropdown with redux-form changes the values when onBlur fires

### ISSUE THREAD

**Issue by sorahn** [Semantic-Org/Semantic-UI-React#3273]
### Problem
I'm having an issue using the `Dropdown` component with `redux-form`.

I'm using `selectOnBlur={false}` and while it's not sending the change event anymore, the blur event has `e.target.value` (used [here](https://github.com/erikras/redux-form/blob/master/src/events/getValue.js#L18)) and that makes `redux-form` send a ` { payload: "" }` with the action, and it clears the field.

### Expected Result
onBlur from the dropdown does not update the value in redux-form when `selectOnBlur={false}`

### Actual Result
value gets erased on blur.

### Version
0.83.0

### Testcase
The sandbox shows the issue, and has repro steps for 2 related issues and the functions at the top of `index.js` and `Component.js` show how I've managed to fix it in userland.

https://codesandbox.io/s/3460487p06

**Comment by layershifter** [comment]
You need to use wrappers for `redux-form`, take a look on examples in our Prototypes: https://react.semantic-ui.com/prototypes

An event in `onBlur` doesn't contain the value, so you need to grab it from the second argument, something like this:
```js
onBlur={(e, { value }) => field.input.onBlur(value)}
```

https://codesandbox.io/s/jn0w4mxm5

**Comment by sorahn** [comment]
@layershifter when I set up that with my code, the value for 'onBlur' is missing.

```javascript
      <Form.Select
        value={field.input.value}
        options={fieldOptions}
        label={<label>{label}</label>}
        placeholder={field.placeholder}
        onChange={(e, data) => {
          console.log('onChange', data.value);
          field.input.onChange(data.value);
        }}
        onBlur={(e, data) => {
          console.log('onBlur', data.value);
          field.input.onBlur(data.value);
        }}
        selectOnBlur={false}
      />
```

<img width="380" alt="screenshot 2019-01-03 16 20 54" src="https://user-images.githubusercontent.com/588852/50645319-8fd0eb00-0f73-11e9-9c04-19d41e518cc0.png">

ideas?

**Comment by layershifter** [comment]
Nope 😢 

I double checked our sandbox, `onBlur()` works correctly: https://codesandbox.io/s/9445n90wkw
Can you create a minimal repro on Codesandbox on clonable repo on Github?

**Comment by sorahn** [comment]
Yeah I see what I can make.  I did notice that my version differs.  I'm on 0.81.3, and the sandbox has 0.84.  I will try that updating too.
