### ISSUE TITLE
Add dailymotion source to Embed

### ISSUE THREAD

**Issue by mrogelja** [Semantic-Org/Semantic-UI-React#3276]
## Feature Request

As Dailymotion remains a popular video sharing plateform, it would be nice to add and handle a `dailymotion` source to Embed component.

**Comment by layershifter** [comment]
It's a valid feature request, but we will not add it because the `Embed` module in SUI core supports only `youtube` and `vimeo`, https://github.com/Semantic-Org/UI-Embed/blob/master/embed.js#L633.
