### ISSUE TITLE
Select setting image with CRA

### ISSUE THREAD

**Issue by lsvargas** [Semantic-Org/Semantic-UI-React#3278]
Hi
I built my App using CRA and im having problems loading images to **Options** in the component **Select**. CRA is made so images are managed as imports and not as paths, and the component **Select** receives its images like this:
``` 
{ 
  text: 'Jenny Hess',
  value: 'Jenny Hess',
  image: { avatar: true, src: '/images/avatar/small/jenny.jpg' },
}
```
and I need to pass images as imports. Is there a way to make this happen?

**Comment by layershifter** [comment]
This question is not related to SUIR at all, please use Stackoverflow for questions.

```jsx
import jennyImg from './avatar/jenny.png'

const option = { 
  text: 'Jenny Hess',
  value: 'Jenny Hess',
  image: { avatar: true, src: jennyImg },
}
```
