### ISSUE TITLE
Package: build fails on 0.83.0 with Rollup

### ISSUE THREAD

**Issue by Codebreaker101** [Semantic-Org/Semantic-UI-React#3280]
### Steps
I upgraded the version of semantic from 0.82.3 to 0.83.0 and the build stopped working 

### Expected Result
For the project to build successfully

### Actual Result
The build stopped with an error 

<pre><font color="#34E2E2"><b>src/index.js</b></font><font color="#06989A"> → </font><font color="#34E2E2"><b>dist/index.js, dist/index.es.js</b></font><font color="#06989A">...</font>
<font color="#EF2929"><b>[!] Error: &apos;instance&apos; is not exported by node_modules/@semantic-ui-react/event-stack/lib/index.js</b></font>
<font color="#06989A">https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module</font>
node_modules/semantic-ui-react/dist/es/lib/eventStack/index.js (1:9)
<font color="#AAAAAA">1: import { instance } from &apos;@semantic-ui-react/event-stack&apos;;</font>
<font color="#AAAAAA">            ^</font>
<font color="#AAAAAA">2: export default instance;</font>

</pre>

### Version
0.83.0 
0.82.5

### Testcase
Building the package with 0.67.1 version of rollup

**Comment by layershifter** [comment]
A valid issue, should be solved in the [`event-stack`](https://github.com/layershifter/event-stack) package. Will be fixed soon.

Thanks for the report 👍
