### ISSUE TITLE
Missing 'Keybase' icon

### ISSUE THREAD

**Issue by rubberbandage** [Semantic-Org/Semantic-UI-React#3281]
## Feature Request
Add icon for 'Keybase', which is a free icon in FontAwesome 5.
https://fontawesome.com/icons?d=gallery&q=keybase&s=brands&m=free

### Problem description
I have an issue when attempting to use the keybase icon, where no icon is displayed.

```
import { Icon } from 'semantic-ui-react';
... 
render() {
    return (<Icon name="keybase" size='big' link/>)
}
... 
```

I have had a look through the following file, and I could not see 'keybase' listed either.
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/SUI.js

My current dependencies are:
```
"semantic-ui-react": "^0.83.0"
"react": "^16.6.0"
"react-dom": "^16.6.0"
```

### Comments
I'm unsure of the entire steps to add a new icon, whether it is just a one line change, or if there is other steps involved. 
It may be that 'keybase' wasn't included in v5.0.8 of Font Awesome when the port was completed.

Please and Thank you 🙇

**Comment by layershifter** [comment]
This icon is not present in SUI CSS (https://github.com/Semantic-Org/UI-Icon/blob/master/icon.css), so we can't use it there, see https://github.com/Semantic-Org/Semantic-UI/issues/6395
