### ISSUE TITLE
Docs: show HTML does not work for Search module

### ISSUE THREAD

**Issue by robert2s** [Semantic-Org/Semantic-UI-React#3283]
## Bug Report
Concerns the documentation of the Search module in https://react.semantic-ui.com/modules/search/

### Steps
On https://react.semantic-ui.com/modules/search/, click on _Show HTML_ for any of the examples of the Search module. 

### Expected Result
It normally shows the HTML code of the example.

### Actual Result
A blank page appears. On the console, the following information appears:
```
SyntaxError: Unexpected token (2:3)
  1 | <div class="ui grid"><div class="six wide column"><div class="ui search"><div class="ui icon input"><input type="text" value="" tabindex="0" class="prompt" autoComplete="off"/><i aria-hidden="true" class="search icon"></i></div><div class="results transition"><div class="message empty"><div class="header">No results found.</div></div></div></div></div><div class="ten wide column"><div class="ui segment"><div class="ui header">State</div><pre style="overflow-x:auto">{
> 2 |   &quot;isLoading&quot;: false,
    |   ^
  3 |   &quot;results&quot;: [],
  4 |   &quot;value&quot;: &quot;&quot;
  5 | }</pre><div class="ui header">Options</div><pre style="overflow-x:auto">[
    at t (parser-babylon.js:1)
```
and more.

### Version
0.83.0

### Testcase
https://react.semantic-ui.com/modules/search/

**Comment by layershifter** [comment]
Thanks for the report 👍  Feel free to submit a PR with a fix.
