### ISSUE TITLE
TypeScript - Dropdown component (use of shallowEqual)

### ISSUE THREAD

**Issue by pandemonic** [Semantic-Org/Semantic-UI-React#3284]
Hello, we are  getting compiling warnings in Typescript version 2.4.1 when using the Dropdown component.

./node_modules/semantic-ui-react/dist/es/lib/shallowEqual.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* <--ProjectFolder-->/node_modules/source-map-loader/index.js!/<--ProjectFolder-->/node_modules/semantic-ui-react/dist/es/lib/shallow**E**qual.js
    Used by 1 module(s), i. e.
    <--ProjectFolder-->/node_modules/source-map-loader/index.js!/<--ProjectFolder-->/node_modules/semantic-ui-react/dist/es/lib/index.js
* <--ProjectFolder-->/node_modules/source-map-loader/index.js!/<--ProjectFolder-->/node_modules/semantic-ui-react/dist/es/lib/shallow**e**qual.js
    Used by 2 module(s), i. e.
    <--ProjectFolder-->/node_modules/source-map-loader/index.js!/<--ProjectFolder-->/node_modules/semantic-ui-react/dist/es/lib/shallow**E**qual.js

**Comment by layershifter** [comment]
I think that this it's a bug with TS compiler, however we should use `shallowequal` directly, PR is coming.
