### ISSUE TITLE
update defaultValue for Dropdown doesn't affect UI.

### ISSUE THREAD

**Issue by darkengine** [Semantic-Org/Semantic-UI-React#3291]
## Bug Report
The defaultValue of our Dropdown is fetch from server. So we use setState() to update defaultValue when fetch done. However the UI doesn't change but the this.state already changed.

### Steps
1, initial a Dropdown.
2, Fetch value from server.
3, Call setState to update state for defaultValue.

### Expected Result
Selected option changed.

### Actual Result
Selected option not changed, still maintain the old defaultValue.

### Version
0.83.0

### Testcase
I use a button click event to emulate fetch from server:
```
import React, { Component } from 'react';
import { Dropdown, Button } from 'semantic-ui-react'
import logo from './logo.svg';
import './App.css';

const friendOptions = [
  {
    text: 'Stone Lam',
    value: '1'
  },{
    text: 'William Lee',
    value: '2'
  },{
    text: 'Jason John',
    value: '3'
  }
]

class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      selection: '2'
    }
    this.btnClick = this.btnClick.bind(this)
  }
  btnClick(event) {
    this.setState({selection: '1'})
    console.log('btnClick called')
  }
  componentDidMount() {
  }
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <Dropdown placeholder='Select Friend' defaultValue={this.state.selection} fluid selection options={friendOptions} />
          <Button primary onClick={this.btnClick}>Primary</Button>
        </header>
      </div>
    );
  }
}

export default App;
```

**Comment by layershifter** [comment]
`Dropdown` implements the idea of controlled and uncontrolled components and works as usual React's primitive components.

https://reactjs.org/docs/forms.html
https://reactjs.org/docs/uncontrolled-components.html

So, in your case you need to use `Dropdown` as a controlled component and use the `value` prop.
