### ISSUE TITLE
Select component should have 'selectedOptions' property

### ISSUE THREAD

**Issue by danydhondt** [Semantic-Org/Semantic-UI-React#3292]
### Problem description
In a Select (or similar) component, the prop 'options' holds an array of available options. Each option has a key, value and text property but can have other properties too.
An example: if we show users of a database, we map the user array to a new array which is compatible with the internal Select structure. The could be something like this:

`[{key: 1, value: 1, text: 'John Doe', user: {id: 1, firstName: 'John', lastName: 'Doe'}, ...]`

When we select a user in the Select component, the onChange handler is triggered like this:

```
onChange(event, {value}){
    //code here
}
```

If we want to retrieve the user object itself, we have to search in the options array because 'value' only holds a number in this case. It would be handy  if we could retrieve the original object itself!
Like now, we can filter the 'options' property which hold all options and filter on the 'value' property (or properties in case of multiple)

### Proposed solution
Solution is simple: just add the selected option (or options) to a new property of the Select component (and similar component like Dropdown).
The onChange function could look like this:

```
onChange(event, {value, selectedOption}){
    //in my example, selectedOption would be {key: 1, value: 1, text: 'John Doe', user: {id: 1, firstName: 'John', lastName: 'Doe'}
}
```

**Comment by layershifter** [comment]
We will not change this API.

Each option in `options` is a [shorthand](https://react.semantic-ui.com/#shorthand-props) for the `DropdownItem` component. This means that passed `user` prop will be passed to a `DropdownItem` and will cause warning. For now, it works because we have a [wrong usage](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.83.0/src/modules/Dropdown/Dropdown.js#L1304) of own API.

**Comment by danydhondt** [comment]
I don't think you understood what I wanted to say.
Let me try to explain better: when I select or delete an item in a multiple dropdown I get an object as 2nd parameter which looks like this:
![schermafbeelding 2018-11-27 om 08 13 07](https://user-images.githubusercontent.com/34274779/49064791-555d8b00-f21c-11e8-83e6-a2af6555b021.png)
As you can see, there is no way to determine which object of the options I selected. IMO, this is a real shortcoming in Dropdown. The moment I click on an item in the options, It is really very simple to add that object to the props object that is sent in the onChange handler

**Comment by ukor** [comment]
@danydhondt Any luck with this? Did you find a way to get the value that was selected?
