### ISSUE TITLE
Popup: Popup is positioned incorrectly when in controlled state

### ISSUE THREAD

**Issue by mic4ael** [Semantic-Org/Semantic-UI-React#3293]
## Bug Report

It seems to be a bit contrived and I might be missing something here.

### Steps
Create a "controlled" Popup based on some internal state.

### Expected Result
Popup is placed right next to the `trigger` element.

### Actual Result
Popup appears in the right top corner of the viewport.

### Version
0.83.0

### Testcase
https://codesandbox.io/s/zz97jxkjj3

**Comment by qooban** [comment]
@mic4ael Wouldn't it be better if you try sending `active` value to `open` prop in `render()` method:
```
    return (
      <Container>
        <Popup
          trigger={button}
          open={active}
          position="right center"
          content="Hello World from the Popup!"
        />
      </Container>
    );  
```
instead of returning different components depending on `active` value?

**Comment by mic4ael** [comment]
@qooban Yeah, definitely it would. That is why I mentioned that the example is a bit contrived. My usecase was that I didn't want to render `Popup` at all if it wasn't necessary. With `active={open}` the HTML element is already present in the DOM tree and I wanted to avoid that.

**Comment by layershifter** [comment]
@mic4ael as I see it's a duplicate of #2991, I'm correct? 

We have two PRs for this #3020 & #3029. I'm going to update them, polish and merge on this weekend.

**Comment by mic4ael** [comment]
@layershifter ohh, that is right. My bad, I should have looked for related issues a bit more diligently.
