### ISSUE TITLE
Search: does not trigger `onResultSelect` if custom open prop is supplied

### ISSUE THREAD

**Issue by jsve** [Semantic-Org/Semantic-UI-React#3298]
### Steps
Add a search component with a managed state for "open", and custom functions for onFocus, onBlur and onResultSelect. 

### Expected Result
Results appear when ```open = true```. ```value``` gets set to ```result.value``` when a result is either clicked or selected with arrow-keys and enter.

### Actual Result
clicking a result does not trigger "onResultSelect", hence value is not updated. 

When commenting out "open" it works as expected.

### Version
0.83.0

### Testcase
https://codepen.io/j_sve/pen/Rqybdd

**Comment by kohakukun** [comment]
I can take this one if possible

**Comment by layershifter** [comment]
Yep, feel free to open a PR

**Comment by danedavid** [comment]
@kohakukun If not still working, can I take this up?

**Comment by schevall** [comment]
I have the same problem as well, but unfortunately I have no time to put on this.
