### ISSUE TITLE
Lazy loading images

### ISSUE THREAD

**Issue by ktmn** [Semantic-Org/Semantic-UI-React#3305]
## Feature Request
I would like to lazy load images. Instead of `src` I would need to specify `data-src`.

Currently this prevents it:

https://github.com/Semantic-Org/Semantic-UI-React/blob/94711d39ac5abd7f0baf39f67c211924f3958dfe/src/lib/htmlPropsUtils.js#L83

For example if I have:

```js
<Image data-src='...' size='small' wrapped />
```

it would produce

```html
<div class='ui small image' data-src='...'>
  <img />
</div>
```

One way to support it would be to just add `data-src` to `htmlImageProps`. 

A more robust way would be to allow people to configure `htmlImageProps` - this would potentially allow better integration with different lazy loading libraries, such as [lazysizes](https://github.com/aFarkas/lazysizes) which can accept `data-srcset` and `data-sizes` as well. But it also requires the `lazyload` class on the `img` element, which opens up a another can of worms that would perhaps require a new attribute for Semantic UI React images - `<Image className='class-for-wrapper' imageClassName='lazyload' data-src='...' wrapped />` which could produce:

```html
<div class='ui small image class-for-wrapper'>
  <img data-src='...' class='lazyload' />
</div>
```

but merge the classes when there is no wrapper:

```html
<img class='ui small image class-for-wrapper lazyload' data-src='...' />
```

Is this sort of thing out of the scope of this library?

There is also lazy loading possible with the Semantic UI Visibility component if I'm not mistaken, so that could also be an alternative to implement.

Currently using document ready scripts to move around the attributes before triggering lazy loading, but it feels wrong to manipulate DOM elements like that.

**Comment by brianespinosa** [comment]
@ktmn 

> Is this sort of thing out of the scope of this library?

My initial guess is probably. Everyone's implementation details around lazy loading images and image optimization could be different. If that is all baked into the library we are forcing developers into one box.

Depending on how you plan on implementing lazy image loading, you could technically do this by making your own HOC that has all of that logic internally and passes the `src` to the `<Image />` component once the src has loaded.

**Comment by layershifter** [comment]
It's an edge case, I'm not sure that we should expose `htmlImageProps` as a prop. As you mentioned, our components in many cases are just markup. So, you can just create a custom component:

```jsx
const LazyImage = ({ src }) => (
  <div className='ui small image' data-src={src}>
    <img />
  </div>
)
```
