### ISSUE TITLE
ui grid css flex-direction as row confusing.

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#3309]
I'm trying semantic ui grid for layout purpose.
I notice that semantic define the .ui.grid as flex and use flex-direction row
now I don't understand why because grid in generally should be row > columns so the grid should be flex-direction column.
with that I can control on row level height with flex ratio

}

old
.ui.grid {
    display: flex;
    flex-direction: row;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    align-items: stretch;
    padding: 0;

new
.ui.grid {
    display: flex;
    flex-direction: column;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    align-items: stretch;
    padding: 0;

### Proposed solution
make the flex-direction in ui.grid as column by default.

**Comment by layershifter** [comment]
This repo only contains JS React components. Please post CSS issues on the main repo at https://github.com/Semantic-Org/Semantic-UI/issues.
