### ISSUE TITLE
Inverted colour doesn't work on horizontal segment groups

### ISSUE THREAD

**Issue by Scoombe** [Semantic-Org/Semantic-UI-React#3310]
### description
When you create a segment that is a horizontal segment group and add the inverted property. You cannot see the text and the background colour doesn't change. This works with groups it's only when you add the horizontal property to the segment group that it doesn't work.

### Steps
Create a segment group. 
Add the horizontal property.
add 2 segments.
Add some text in the segments
add the inverted property to one of the segments.

### Expected Result
You should have one segment with a black background and white text and one normal segment.

### Actual Result
The background colour is still white and the text can't be seen. 

### Version
0.83.0 / latest.

### Testcase
[![Edit Semantic UI React](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/31mymnjnz5)

**Comment by layershifter** [comment]
This is a valid issue, https://github.com/Semantic-Org/Semantic-UI/issues/3587

As workaround, you can apply `color` manually:

```jsx
<Segment.Group horizontal>
  <Segment color='black' inverted />
</Segment.Group>
```

![image](https://user-images.githubusercontent.com/14183168/49232519-c491d580-f3fc-11e8-88a2-b68b6d951659.png)
