### ISSUE TITLE
Accordion display bug

### ISSUE THREAD

**Issue by Zyxmn** [Semantic-Org/Semantic-UI-React#3311]
The accordion component renders the  first `accordion content` element on screen regardless of its `active` status value .
This happens when the accordion starts with a `accordion content ` element instead of a `accordion title` element.

I am trying to have two content elements per title and the structure looks something like this:
```
<Accordion>
  <Accordion.Content> "this always renders regardless what its active status is"
  <Accordion.Title> 
  <Accordion.Content> "behaves as expected" 
 
 <Accordion.Content> "behaves as expected"
  <Accordion.Title> 
  <Accordion.Content> "behaves as expected"
</Accordion> 
```

Only workaround I have right now is to start with a dummy `accordion title` element that is always `active = false` . Then everything renders as expected.

**Comment by layershifter** [comment]
It's unclear what you're trying to do, there is only one valid and working markup:

```jsx
<Accordion>
  <Accordion.Title />
  <Accordion.Content />

  <Accordion.Title />
  <Accordion.Content />
</Accordion>
```

`Accordion.Title` is the required part of markup:

![image](https://user-images.githubusercontent.com/14183168/49242098-78ea2680-f412-11e8-94c6-58c0ecb85b5d.png)

Please provide a codesandbox example.
