### ISSUE TITLE
Dropdown: closeOnChange is not working for customized options not children

### ISSUE THREAD

**Issue by ZhenWang-Jen** [Semantic-Org/Semantic-UI-React#3313]
### Steps
Use a Search Dropdown (https://react.semantic-ui.com/modules/dropdown/#types-search-dropdown) for 2 types of dropdowns.
One is a normal dropdown, another is with customized options of checkboxs not children props.

Click any option or checkbox, the value/checkbox works properly.

### Expected Result
The checkbox dropdown show keeps open on option change as the other normal dropdown.

### Actual Result
The closeOnChange={false} works well for my normal dropdown which keeps the menu open, but it doesn't work for the checkbox one 💣
No console error happens along the way. Just want to know how to keep the checkbox options open on change. 

### Version
^0.82.3

### Testcase
<img width="1049" alt="first" src="https://user-images.githubusercontent.com/28586492/49260759-403f5280-f3fc-11e8-9895-9853fed15c3e.png">
<img width="1049" alt="first" src="https://user-images.githubusercontent.com/28586492/49260761-46353380-f3fc-11e8-9352-9e6fb193e912.png">
<img width="1049" alt="first" src="https://user-images.githubusercontent.com/28586492/49260782-58af6d00-f3fc-11e8-9f51-5c1be1b45094.png">
<img width="1049" alt="first" src="https://user-images.githubusercontent.com/28586492/49260784-5a793080-f3fc-11e8-8cdf-78457f4bf0bb.png">

**Comment by layershifter** [comment]
Please add a minimal and clear repro case on codesandbox.

**Comment by layershifter** [comment]
Closing as I didn't receive any response. Will reopen after a feedback.

**Comment by nkemcels** [comment]
I had this same issue. Solved it by stopping the propagation of the click event on my custom item
