### ISSUE TITLE
Toggle knob sometimes hides behind track in modals in chrome

### ISSUE THREAD

**Issue by smassin** [Semantic-Org/Semantic-UI-React#3318]
## Bug Report
In modals specifically, sometimes the toggle knob hides behind the toggle track in chrome (on mac and on android, v70.0.3538.110 for both)
See screenshot: https://imgur.com/a/Gyd0ZDX
I did not see this problem perhaps a month or 2 ago. I'm almost thinking that it's a recent chrome browser change.
Other browsers, safari, edge, ff don't show this problem.
I tried a number of things to solve the issue but none worked consistently. However, embedding the contents of the model into the body had no issues. It has something to do with being in the modal itself.

### Steps
1. Go to the testcase sandbox in chrome.
2. Open the modal.
3. Scroll to the bottom.
4. Start toggling from bottom to top.
Usually closer to the top you will see some bad toggles.

### Expected Result
The knob should never hide behind the track.

### Actual Result
The knob hides behind the track.

### Version
Sandbox version. See testcase.

### Testcase
https://codesandbox.io/s/924875q9ko

**Comment by layershifter** [comment]
Looks life a similar problem, #3287.

**Comment by smassin** [comment]
Yes it does look similar but since the sandbox example didn't use the react components I figured there is a small chance it could have a different root problem.

It may actually be a browser bug after all. The main reason for submitting is that there could be some css or component hack to work around this bug. I also don't know what specifically about using a radio in a modal is causing this to happen.
