### ISSUE TITLE
Icons not loaded in meteor... 

### ISSUE THREAD

**Issue by pociej** [Semantic-Org/Semantic-UI-React#3321]
### Steps
Just `npm i semantic-ui-react` and `npm i semantic-ui-css`
### Expected Result
Rendered icons
### Actual Result
Square where icon should be rendered. Even in places like modal close. 
### Version
"semantic-ui-css": "^2.4.1",
"semantic-ui-react": "^0.83.0",

**Comment by layershifter** [comment]
Please make sure that you included CSS: https://react.semantic-ui.com/usage#css

**Comment by pociej** [comment]
@layershifter thx for quick reply, but of course i included. Without this i would see more glitches than not rendered icons :)

**Comment by layershifter** [comment]
Please create a minimal repro repo that can be cloned and quick started.
There can be an issue with your Webpack's setup.

**Comment by pociej** [comment]
@layershifter I forgot to add info in original description that im using Meteor. Maybe here is problem? Here is repo with reproduction : https://github.com/pociej/semantic-icons-problem. In meantime i will setup pure node example and check.

**Comment by layershifter** [comment]
I don't know anything about Meteor, but it seems that it's root issue:
https://github.com/Semantic-Org/Semantic-UI-CSS/issues/23
https://github.com/Semantic-Org/Semantic-UI-CSS/issues/38

**Comment by pociej** [comment]
@layershifter ok above are related a bit but its not the same and there is no solution of this issue. 
Don't you think that in such case closing issue with label `triage` isnt good? 
I will try to figure out whats going on but please reopen issue, because here is an issue.

**Comment by layershifter** [comment]
As I see this issue is not related to Semantic UI React at all. Because, it caused by Meteor and its problems with Semantic UI CSS. Am I correct? 😺 

I understand that you need a working solution, but I don't understand how it can be fixed there.

**Comment by pociej** [comment]
But look @layershifter that Meteor with it native engine ( Blaze) works with semantic UI, only react version fails on Icons, so i would say some fault might be here. Right? 
Should i move issue under SUICSS repo?

**Comment by layershifter** [comment]
> Should i move issue under SUICSS repo?

It seems that yes. It will be cool if you will find out the root issue and also post the solution there.

Just want to clarify again, Semantic UI React only generates markup, our package doesn't deals with CSS at all.

---

You can try to use `semantic-ui` and import CSS with:
```js
import 'semantic-ui/dist/semantic.css'
```
