### ISSUE TITLE
Transition: allow custom animations

### ISSUE THREAD

**Issue by crashtech** [Semantic-Org/Semantic-UI-React#3323]
## Feature Request
Semantic originally allows custom transitions to be created., but the React `Transition` component only allow the original transitions (especially for directional animations).

### Problem description
There is no way to define a custom transition animation on my CSS and use it as a directional transition on my React components.

### Proposed solution
Add `SUI.pushAnimation("jump")` and `SUI.pushDirectionalAnimation("reveal left")` allowing them to be used while defining a Transition.

The only problem with this solution might be the PropTypes check, which relies on a static array, which would have to change to a dynamic function to get the updated value.

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

**Comment by jongsue** [comment]
for custom animations
```javascript
<Transition animation={'jump'} />
```

for custom directional animations
```javascript
<Transition directional animation={'reveal left'} />
```

@layershifter What do you think about my idea?
