### ISSUE TITLE
Icon "linkedin alternate" is actually "linkedin alt".

### ISSUE THREAD

**Issue by hauke-d** [Semantic-Org/Semantic-UI-React#3333]
### Steps

Create an icon with `name="linkedin alternate"` and and icon with `name="linkedin alt"`.  The `linkedin alt` icon displays fine, but throws a prop type error and is not displayed in the docs. 

### Expected Result

![image](https://user-images.githubusercontent.com/15606289/49742625-2ffb6300-fc99-11e8-86fc-e57e098bca36.png)

### Actual Result

![image](https://user-images.githubusercontent.com/15606289/49742721-69cc6980-fc99-11e8-9b22-4f62a9402411.png)
(from the docs)

### Version
0.83.0

### Testcase
https://codesandbox.io/s/jn19m23339

**Comment by layershifter** [comment]
Thanks it's a valid report, however we're using names from SUI core. As you can see issue is present there:

![image](https://user-images.githubusercontent.com/14183168/49743628-db111a00-fca3-11e8-8c0d-46d03d33825c.png)
https://semantic-ui.com/elements/icon.html

And it should be fixed there, https://github.com/Semantic-Org/Semantic-UI. As temporary workaround you can just use:
```jsx
<Icon className="linkedin alt" />
```
