### ISSUE TITLE
when i use Popup trigger, the pre message and current message all show

### ISSUE THREAD

**Issue by oyosc** [Semantic-Org/Semantic-UI-React#3335]
State of component:
```
this.state = {
      pOM: props.pOM, // the return message of backend, as code is error
      isOpen: false
 }
<Popup open={this.state.isOpen} trigger={<Button className='btn-gre'>buy</Button>} on='click' content={this.state.pOM} hideOnScroll />
```
When i click the button of buy, it will send the request to server, and get the return message,Popup will show it. Assume the current message is A, and when i click the button of buy in next time, it returns B message, but the Popup of Component will show all of them, the correct result that i want is just show B. Now i use the setTimeout to avoid this, but not perfect. So please tell me the better solution,thx

**Comment by layershifter** [comment]
Please use StackOverflow for usage questions: https://stackoverflow.com/questions/tagged/semantic-ui-react
