### ISSUE TITLE
Popup rerenders and slowing page

### ISSUE THREAD

**Issue by DavidLozzi** [Semantic-Org/Semantic-UI-React#3338]
### Steps
I have Popup on our page, about ~80 times (20 database results, with 4 popups each). We have SEVERAL other Semantic UI components on the page as well, being repeated just as much.

When I interact with another control on the page, the page is sluggish, and exploring performance it shows the Popup control rerendering, always.

Here is the full render event when I click in a text box
![image](https://user-images.githubusercontent.com/3543383/49968204-1ead9300-fef3-11e8-923c-c119cfbb3247.png)

Zooming into the depths, I see only Popups, no other controls (except for the parents of course)
![image](https://user-images.githubusercontent.com/3543383/49968248-41d84280-fef3-11e8-9914-37e5049d8916.png)

We implemented Popup via our own component, using `memo`

```
import { memo } from 'react';
import { Popup } from 'semantic-ui-react';
import './Popup.scss';

export default memo(Popup);
```

And one example of the implentation

```
import Popup from 'components/Popup/Popup';
...
Card.Download = class CardDownload extends PureComponent {
  downloadFileHandler = () => {
...
  };

  render = () => {
    const {
      display
    } = this.props;

    return (
      display &&
      <div className="imgWrapper">
        <Popup
          trigger={<Image className="actionIcon" onClick={this.downloadFileHandler} src={downloadIcon} />}
          content="Download"
          position="bottom right"
          hideOnScroll
        />
      </div>
    );
  }
};
```

### Expected Result
Not to have Popup rerender completely.

### Actual Result
See images above

### Version
0.82.5

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by qyangdu** [comment]
have similar problem, Popup use a lot CPU time comparing to other controls.

**Comment by layershifter** [comment]
@DavidLozzi @qyangdu in `0.87.0` we switched to `Popper.JS` (see #3532), now `Popup` is more performant. Any style computations will be applied only to opened `Popup`, please check and provide the feedback.  

FYI: I tried it on `Icon` page, https://react.semantic-ui.com/elements/icon/ No rerenders 🗡

**Comment by qyangdu** [comment]
Yes the performance is much better, but it brings in the issue #3725.
