### ISSUE TITLE
Icon: `disabled` prop should disable `onClick` callback

### ISSUE THREAD

**Issue by spencer-brown** [Semantic-Org/Semantic-UI-React#3341]
## Bug Report

Based on past and open issues, it sounds like `onClick` callback execution has been updated to not fire when `disabled === true` for some but not all elements. I think `Icon`s should not execute `onClick` callbacks when `disabled === true` to maintain parity with other elements (eg `Button`) which have been updated to maintain parity with HTML.

### Steps
A clear and concise description of steps to reproduce the problem.

```jsx
import React from 'react'
import { Icon } from 'semantic-ui-react'

const IconExampleDisabled = () => <Icon disabled name='users' onClick={() => console.log('hi') }/>

export default IconExampleDisabled
```

Click the icon.

### Expected Result

When the icon is clicked, the `onClick` callback should not be called and "hi" should not be logged.

### Actual Result

When the icon is clicked, "hi" is logged.

### Version

0.82.3

### Testcase

https://codesandbox.io/s/2o4qo44vrn

**Comment by danielsyang** [comment]
Hello, can I work on this? It's going to be my first time contributing here :)

**Comment by layershifter** [comment]
Yes, feel free to create a new PR :+1: Take a look on `Button` and it's tests for a reference
