### ISSUE TITLE
List Item Icon Rotates Around Wrong Point when using Loading Spinner 

### ISSUE THREAD

**Issue by HieronymusLex** [Semantic-Org/Semantic-UI-React#3342]
### Steps
When using a Loading Icon as the floated icon for a List.Icon, the entire icon rotates around a fixed point rather outside the icon bounds, rather than rotating about it's own center. Sorry if that's not very clear but it should be obvious by looking at the codesandbox (link below).

I've tried it with both Icon and List.Icon components

### Expected Result
Icon animation looks natural and rotation origin point is icon's center

### Actual Result
Icon animation rotates around wrong point

### Version
0.84.0

### Testcase
https://codesandbox.io/s/98709pjw24

**Comment by layershifter** [comment]
This is a valid CSS bug and should reported to the main repo: https://github.com/Semantic-Org/Semantic-UI


Here is a temporary workaround for you:
```jsx
<i className="icon">
  <Icon name="spinner" loading style={{ marginRight: 0 }} />
</i>
```

![image](https://user-images.githubusercontent.com/14183168/50403171-1a139500-07a5-11e9-9a7d-722f4b88565a.png)
