### ISSUE TITLE
Checkbox: double call of `onClick` when event fired by mouse

### ISSUE THREAD

**Issue by Obiwarn** [Semantic-Org/Semantic-UI-React#3348]
e.g. use the example from the docs and change the Checkbox onChange to onClick:

```
import React, { Component } from 'react'
import { Button, Checkbox } from 'semantic-ui-react'

export default class CheckboxExampleRemoteControl extends Component {
  state = { checked: false }
  toggle = () => this.setState({ checked: !this.state.checked })

  render() {
    return (
      <div>
        <Button onClick={this.toggle}>Toggle it</Button>
        <Checkbox label='Check this box' onClick={this.toggle} checked={this.state.checked} />
      </div>
    )
  }
}
```

**Comment by layershifter** [comment]
We introduced some changes in #2748, and yes it comes from there. I used your code in sandbox, so we have reproduction:
https://codesandbox.io/s/l9n88k3y4q

The issue comes from a double called `onClick` handler when it's clicked with mouse. Should be fixed.

**Comment by Fabianopb** [comment]
@layershifter I'd be happy to contribute to this one!

**Comment by layershifter** [comment]
@Fabianopb you're welcome :+1:

**Comment by Fabianopb** [comment]
I've been investigating this story, which is related to #2587 and I'm wondering about the order that the events are called. Currently we have
```
handleMouseDown() --> handleMouseUp() --> handleChange() --> handleClick()
```

Shouldn't `handleClick()` be called before `handleChange()`? Ping @levithomason

**Comment by Fabianopb** [comment]
PR created! #3351

**Comment by levithomason** [comment]
Heads up, I've got some local work on this that I'm implementing.  I'll push later tonight or tomorrow and give an update on where it is.

**Comment by levithomason** [comment]
Sorry, both my MacBooks ended up going out for repairs.  Checking back on this now and will close it up.

**Comment by NullVoxPopuli** [comment]
has this been released? I'm on 0.84 and am witnessing double onClicks

**Comment by NullVoxPopuli** [comment]
when will that be released?

**Comment by levithomason** [comment]
Releasing today.
