### ISSUE TITLE
Dropdown: focus is lost after selection

### ISSUE THREAD

**Issue by sahilfullstack** [Semantic-Org/Semantic-UI-React#3349]
Drop-down looses focus when I select an item, can anyone please tell me how should I maintain focus.

**Comment by sahilfullstack** [comment]
yes please resolve my issue.

**Comment by layershifter** [comment]
As I see, it's duplicate of #3158. If I missed something, please fill issue template fully and ping me 🐱

**Comment by sahilfullstack** [comment]
My issue is similar to this issue. https://github.com/Semantic-Org/Semantic-UI/issues/1253.
But In React library i am facing this.

My problem is that Steps

1. Expand the dropdown (Dropdown is having focus)
2. Select an item (by click or mouse up/down)
3. Close the dropdown (by click or enter)

**Expected Result**
The dropdown to be in focus.

**Actual Result**
Dropdown looses focus. instead focus goes to the selected item in the dropdown list.

Can i do something to keep the focus to the the dropdown element ?
@layershifter can you give me a solution.

**Comment by SatishSharma1** [comment]
i am facing the same issue. please help

**Comment by layershifter** [comment]
Please provide codesandbox example, `Dropdown` has too many options and it's not obvious for what variant you're claiming.

**Comment by sahilfullstack** [comment]
@layershifter any update

**Comment by layershifter** [comment]
I will take a look when it will be possible. This is an open source project and the best possible resolution for the any issue is a contribution.

Linking  #1806.

**Comment by layershifter** [comment]
Marked this as bug, we should keep focus in this case. The native `select` has the same behavior.

**Comment by sahilfullstack** [comment]
@layershifter thanks.

**Comment by Fabianopb** [comment]
I can probably take a look on this one. I noticed that SUI's `Dropdown` also loses focus after selection.

**Comment by jongsue** [comment]
I only fixed Search Selection not All dropdowns because SUI’s Search Selection retains focus after selection.

Should we fix All dropdowns ? even though they have same behavior as SUI’s have

**Comment by layershifter** [comment]
> Should we fix All dropdowns ? even though they have same behavior as SUI’s have

Yes, please 👍  We should keep focus because native `<select>` does the same thing.
