### ISSUE TITLE
Where's the"new component" label? I am looking for the list of missing components.

### ISSUE THREAD

**Issue by aguyinmontreal** [Semantic-Org/Semantic-UI-React#3350]
## Bug Report
I'm looking for the list of missing components. README.md says the following; 

### [Missing Components](https://github.com/Semantic-Org/Semantic-UI-React/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+component%22)
We're seeking component parity with Semantic UI, plus some addons. There is an issue for every missing component, labeled [`new component`](https://github.com/Semantic-Org/Semantic-UI-React/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+component%22). Just comment on the issue you'd like to take.

However, there is no `new component` label in the open issues or even in the closed issues.

Thank you for your guidance

### Steps
README.md

### Version
current

### Testcase
no testcase

**Comment by layershifter** [comment]
Thanks for the ping there, in fact we have only one missing component, it's a `Shape`, #196. I restored a `new component` label on it.
