### ISSUE TITLE
Why aren't layout examples responsive when viewed on a mobile device?

### ISSUE THREAD

**Issue by jlei523** [Semantic-Org/Semantic-UI-React#3360]
I'm referring to these layout examples:
https://react.semantic-ui.com/layouts/homepage

When viewed on a shrunken desktop browser, it seems like elements behave responsively. However, when viewed on a mobile device, such as my Apple iPhone XR, the desktop version loads.

Why is this? How can I make the layouts responsive on mobile devices as well?

**Edit**: It seems like the issue is that I'm using Next.js with SUIR which does server rendering. The question is, how can I make responsive work with Next.js?

**Comment by El-Sy** [comment]
> Needed to add this to head:
> 
> ` <meta name="viewport" content="initial-scale=1.0, width=device-width" />`

I think even that is added in the head the error is still there

<img width="376" alt="Screenshot 2019-08-18 at 12 51 10 AM" src="https://user-images.githubusercontent.com/23375702/63214984-7bcca900-c152-11e9-9845-95ff9d4bcde3.png">

<img width="774" alt="Screenshot 2019-08-18 at 12 53 51 AM" src="https://user-images.githubusercontent.com/23375702/63215004-b0d8fb80-c152-11e9-90ca-f87aeaef9d69.png">

Taken from: 
https://react.semantic-ui.com/layouts/homepage/
