### ISSUE TITLE
Responsive: SSR is broken

### ISSUE THREAD

**Issue by jlei523** [Semantic-Org/Semantic-UI-React#3361]
**Stack:**
Latest versions of Next.js, React, Semanic UI React.

**Issue:**
When I attempt to render the the example layout from [here](https://react.semantic-ui.com/layouts/homepage) using Next.js, I get a warning that says `Expected server HTML to contain a matching <div> in [<div>.`]

I believe it's related to this issue https://github.com/Semantic-Org/Semantic-UI-React/issues/3110 which has something to do with the server not getting the browser size.

However, none of the solutions in that link worked for me. One requirement I have is that SSR cannot be turned off.

Here's the code I'm using: https://github.com/jlei523/semantic-ui-next

Minor note: I believe https://react.semantic-ui.com/layouts/homepage/ is also affected by this issue. Go to the URL and then refresh the page and you should see the styles get messed up. If you shrink the browser window and then shrink it back, it displays the elements correctly again.

Has anyone solved this problem already without turning SSR off? Also, does anyone have an example of how to do display mobile specific elements using SUIR without turning off SSR?

**Comment by layershifter** [comment]
In #3373 I added notes about SSR, the solution above is now in our docs ⭐️

**Comment by violabg** [comment]
I'm having the same problem.

I'm trying to implement the example at [https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/src/layouts/HomepageLayout.js](url)

it works with desktop size both client and SSR, but if you SSR on mobile size I'm getting

`Warning: Expected server HTML to contain a matching <a> in <div>.`

**Comment by layershifter** [comment]
Please take a look at codesandbox example, it contains the completely working solution.

**Comment by violabg** [comment]
thanks layershifter, I have tested your solution and it works on mobile and desktop, but not on Tablet.

when the user agent is iPad I get
`index.js:2178 Warning: Text content did not match. Server: "MobileContainer" Client: "DesktopContainer"`

**Comment by layershifter** [comment]
Feel free to add necessary changes to the code, it's an example.

**Comment by bexoss** [comment]
I don't understand the error occurred on SSR but how using `NoSSR` is can be a solution?

**Comment by bexoss** [comment]
Hope this bug should be fixed soon. Not a workaround.

**Comment by aendrew** [comment]
Agreed with @bexoss, suppressing hydration errors really isn't a workaround. Try using the responsive menu example with NextJS for another case...

**Comment by layershifter** [comment]
https://github.com/Semantic-Org/Semantic-UI-React/issues/4002#issuecomment-665000116

`Responsive` will be deprecated and removed. I will provide an upgrade guide.
