### ISSUE TITLE
myanmar flag is old

### ISSUE THREAD

**Issue by ukyiwin** [Semantic-Org/Semantic-UI-React#3364]
## Bug Report
old flag
https://en.wikipedia.org/wiki/Flag_of_Myanmar#/media/File:Flag_of_Myanmar_(1974%E2%80%932010).svg
![1024px-flag_of_myanmar_ 1974 2010 svg](https://user-images.githubusercontent.com/35300439/50738146-4399db00-11ff-11e9-983e-6ef53d4183e1.png)

New flag
https://en.wikipedia.org/wiki/Flag_of_Myanmar#/media/File:Flag_of_Myanmar.svg
![1024px-flag_of_myanmar svg](https://user-images.githubusercontent.com/35300439/50738132-2402b280-11ff-11e9-8a40-ce4181039fa7.png)

**Comment by layershifter** [comment]
Sorry, but we don't handle CSS issues there, you should move it to the main repo: https://github.com/Semantic-Org/Semantic-UI

BTW, it has been already tracked in the main repo: https://github.com/Semantic-Org/Semantic-UI/issues/5145
