### ISSUE TITLE
How can I change font of application

### ISSUE THREAD

**Issue by JaLe29** [Semantic-Org/Semantic-UI-React#3366]
How can I change font of application ?

When is font changed, icons not working,

I want to use Roboto like this:

```
	<style>
		@import url(http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300ita‌​lic,400italic,500,500italic,700,700italic,900italic,900);

		html,
		html * {
			font-family: 'Roboto', sans-serif;
		}

		body {
			font-family: 'Roboto', sans-serif;
			overflow: hidden;
		}
	</style>
```

It is possible? And how? Thank you for any help.

**Comment by layershifter** [comment]
The best way is to create a custom theme using theming tools:
http://learnsemantic.com/developing/customizing.html

How to with CRA: https://web.archive.org/web/20190610125521/http://nephewapps.com/2018/02/25/theming-semantic-ui-with-create-react-app/

**Comment by Puspendert** [comment]
http://nephewapps.com/2018/02/25/theming-semantic-ui-with-create-react-app/ is broken

**Comment by HawkeyePierce89** [comment]
@Puspendert https://web.archive.org/web/20190610125521/http://nephewapps.com/2018/02/25/theming-semantic-ui-with-create-react-app/

**Comment by Puspendert** [comment]
@HawkeyePierce89 My project is built using `yarn` so can't do `npm install`. Could you please have a look at https://stackoverflow.com/questions/59897067/theming-for-semantic-ui-react-working-with-npm-but-not-with-yarn.
Thanks

**Comment by juliemjacob** [comment]
> The best way is to create a custom theme using theming tools:
> http://learnsemantic.com/developing/customizing.html
> 
> How to with CRA: http://nephewapps.com/2018/02/25/theming-semantic-ui-with-create-react-app/
> I also going to create a customization guide with LESS package.

The app I am working on used create-react-app, and I need to update the site font. The link above doesn't work. Is there updated documentation?

**Comment by layershifter** [comment]
@juliemjacob it's available in WebArchive as @HawkeyePierce89 pointed out:
https://web.archive.org/web/20190610125521/http://nephewapps.com/2018/02/25/theming-semantic-ui-with-create-react-app/
