### ISSUE TITLE
Icon: `mail outline` icon is missing

### ISSUE THREAD

**Issue by amrbedair** [Semantic-Org/Semantic-UI-React#3368]
### Steps
<Icon name="mail outline" color="grey" size="large" />

### Expected Result
It is working fine 

### Actual Result
But I have this in console 
Warning: Failed prop type: Invalid prop `name` of value `mail outline` supplied to `Icon`.
### Version
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "0.84.0",

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Thanks for the report! As temporary workaround you can use:
```jsx
<Icon className='outline' name='mail' />
```

**Comment by amrbedair** [comment]
thanks @layershifter
