### ISSUE TITLE
Cannot browse documentation with IE11

### ISSUE THREAD

**Issue by guillaumep** [Semantic-Org/Semantic-UI-React#3369]
### Steps
* Open IE11
* Browse to https://react.semantic-ui.com/modules/modal/

### Expected Result
The documentation is displayed.

### Actual Result
The dev tools show an error:
`Object doesn't support property or method 'assign'`.

Error is in the `babel.min.js` file.

### Version
Documentation live as of January 9th, 2019.

**Comment by levithomason** [comment]
Hm, this is strange.  Babel polyfill should handling this.  Confirmed we are loading it:

![image](https://user-images.githubusercontent.com/5067638/51358599-c11fdf80-1a78-11e9-9bd6-b3a06b6a0c76.png)

@layershifter are you able to test this in IE11?

**Comment by levithomason** [comment]
Oh... if `babel.min.js` is using `Object.assign` then we need to load the Babel polyfill prior.  Currently, `babel.min.js` is loaded in the `head` while the `@babel-polyfill` is loaded in the `body` as the first import of the doc site entry `index.js`.

**Comment by guillaumep** [comment]
I'm sorry to report the issue still happens when browsing to the react.semantic-ui.com website.

![capture d ecran de 2019-01-30 10-10-22](https://user-images.githubusercontent.com/1195230/51990622-6bcfcf00-2477-11e9-8146-cca23ed0e077.png)

**Comment by layershifter** [comment]
Changes that fix it were not released yet ⌛️

**Comment by guillaumep** [comment]
@layershifter Oh, I see. I had wrongly thought the documentation was updated live, but it does make sense that it is released at the same time as the code.

Thanks, I'll properly wait for the release.
