### ISSUE TITLE
`Dropdown` `onChange` callback should only be called when the selected value changes

### ISSUE THREAD

**Issue by spencer-brown** [Semantic-Org/Semantic-UI-React#3370]
### Steps

* Create a `Dropdown` with `value` and `onChange` props.
* Click the `Dropdown` and then click outside of the value-displaying-box and dropdown list.

### Expected Result

The `onChange` callback should not be fired because I haven't selected a new value. This is how HTML's `select` behaves.

### Actual Result

The `onChange` callback is called even though the selected value has not changed.

### Version

0.82.3

### Testcase

https://codesandbox.io/s/5z379wy7ol

**Comment by husseyexplores** [comment]
You can pass `selectOnBlur={false}` as a prop to prevent this behavior.
I'm not sure if this intentional (i.e passing `selectOnBlur` explicitly). I can work on this if this needs to behave as expected. 
Edit: I personally think `selectOnBlur` should be `false` by default because that is the normal HTML Select element behavior.

**Comment by spencer-brown** [comment]
This is still an issue beyond the `blur` case btw - if you click the already-selected item in the dropdown list, the `onChange` callback is called. This too is different than HTML's behavior.

**Comment by levithomason** [comment]
Superb report, thanks much.  The current dropdown calls `onChange` on blur even if the value doesn't change, which is certainly not correct.  Here's an updated example comparing a native DOM select to the Dropdown:  https://codesandbox.io/s/43r9899x4

We need to update the Dropdown to behave just as the regular HTML select in this regard.

**Comment by zarend** [comment]
https://github.com/Semantic-Org/Semantic-UI-React/pull/3391

**Comment by spencer-brown** [comment]
@levithomason , how does @zarend 's PR look?

**Comment by spencer-brown** [comment]
thanks @zarend @levithomason & @layershifter !
