### ISSUE TITLE
Common issue with boolean properties in typings

### ISSUE THREAD

**Issue by aleffert** [Semantic-Org/Semantic-UI-React#3374]
## Bug Report
Various components have properties of type `boolean`, but have to actually be used as strings. As such, it's difficult to use the properties properly. For example the `success` and `failure` props on message are typed as booleans. However, they need to be the strings `true` or `false` to actually work. Typescript will reject attempts to do that directly so you basically can't use the properties without a clumsy workaround.

There are two obvious solutions to this problem:
1. Coerce booleans to strings in these cases
2. Change the typings to be `'true' | 'false'` instead of boolean.

Option 1 seems like it creates a nicer abstraction, but Option 2 doesn't require any behavior changes.

### Steps
```
<Message failure>Whatever</Message>
```

### Expected Result
No warning and a red message box.

### Actual Result
```
index.js:1446 Warning: Received `true` for a non-boolean attribute `failure`.

If you want to write it to the DOM, pass a string instead: failure="true" or failure={value.toString()}.
    in div (created by Message)
    in Message (at LoginForm.tsx:65)
...
```

And the box is not red.
### Version
0.84.0

### Testcase
This is not a runtime bug and the single line under Steps is sufficient.

### Workaround
You can do `<Message failure={'true' as any as boolean}>Whatever</Message>` but that is pretty awkward.

**Comment by aleffert** [comment]
Oh thanks. That worked. It does seem like in that case it should be removed from the typings file.

**Comment by layershifter** [comment]
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/collections/Message/Message.d.ts

Sorry, but it's not present there, we have tests that assert the match of typings and propTypes.
