### ISSUE TITLE
Multiple Dropdown max selected values

### ISSUE THREAD

**Issue by philmetzger** [Semantic-Org/Semantic-UI-React#3376]
How can i restrict the amount of items that can be selected in the multiple dropdown? I tried in the onChange function to first check you have less than X items selected and then not set the state, but it still selects the items.

**Comment by neenu-n** [comment]
Is this issue resolved?

**Comment by fazlulkarimweb** [comment]
I'm posting my workaround here. It's probably more short and simple.

At first, save the values in the state (preferably redux state) after every onChange. React state also would do fine. Then, make it disabled when a certain array length of the value is reached. 

```js
const districtData = ['Dhaka', 'Bagerhat', 'Bandarban', 
'Barguna', 'Barishal', 'Bhola']

const [districtValue, setDistrictValue] = useState();

<Dropdown
onChange={async (e, { name, value }) => {setDistrictValue(value)}}
options={districtData.map((currentValue, index) => {
    return {
    key: `${currentValue}`,
    value: `${currentValue}`,
    text: `${currentValue}`,
    disabled: districtValue.length > 2 ? true : false 
}
// Do other things here
// Max 3 values here, then options will be disabled. 
// Will be live again if any selected options are less than 3 here                

/>
```
