### ISSUE TITLE
semantic ui react website isn't opening

### ISSUE THREAD

**Issue by prakhyat-shrestha** [Semantic-Org/Semantic-UI-React#3381]
--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

* Gitter Community Chat: https://gitter.im/Semantic-Org/Semantic-UI-React
* StackOverflow: https://stackoverflow.com/questions/tagged/semantic-ui-react using the tag `semantic-ui-react`
* Also have a look at our docs: http://react.semantic-ui.com

**Comment by levithomason** [comment]
https://downforeveryoneorjustme.com/react.semantic-ui.com

![image](https://user-images.githubusercontent.com/5067638/51353796-74cba400-1a66-11e9-93fe-8a32e6753405.png)
