### ISSUE TITLE
Modal: not centered in IE11

### ISSUE THREAD

**Issue by BagEnd2End** [Semantic-Org/Semantic-UI-React#3388]
The modal component opens down and to the right on IE. It is centered on firefox and chrome. Additionally I can't open https://react.semantic-ui.com/modules/modal/ in IE to see if the issue is present on your website. I have not yet found a css workaround for this and I am not sure why this issue is only present in IE. Any help would be greatly appreciated.

**Comment by levithomason** [comment]
Tested in IE 18 - 15 on Windows 10 and this is working.  Which version of IE is this not working for?

**Comment by BagEnd2End** [comment]
Hi, Thankyou for getting back to me so quickly!
The modal component is not centered on IE 11.0.9600.18816 on Windows 7. I also can't access any of the documentation on IE except for the initial Introduction page. All of the links in the left hand menu render a blank page. If I open the console on the intro page (https://react.semantic-ui.com/) I get a console error: SCRIPT438: Object doesn't support property or method 'assign' 
![image](https://user-images.githubusercontent.com/28845265/51391340-d25fff00-1aff-11e9-8213-fb1028f04139.png)
If I click on any of the items in the sidebar, I get a Babel error in the console
![image](https://user-images.githubusercontent.com/28845265/51391423-06d3bb00-1b00-11e9-8c7d-427e3ff0a68d.png)

**Comment by BagEnd2End** [comment]
Update: I added style={{ position: 'static' }} to the modal component and it resolved this issue.

**Comment by oolleegg55** [comment]
I have the same issue on the modal page: https://react.semantic-ui.com/modules/modal/. This page has errors and shows nothing.
![annotation 2019-01-21 173230](https://user-images.githubusercontent.com/6362575/51477886-30604100-1da3-11e9-8d05-c0b4cf87cdd7.jpg)

UPD: It is related, I have seen this late. https://github.com/Semantic-Org/Semantic-UI-React/issues/3369

**Comment by m1010j** [comment]
I can confirm that this is an issue in IE 11.0.105:
![screen shot 2019-02-13 at 1 58 39 pm](https://user-images.githubusercontent.com/28028994/52736378-bd0fb080-2f97-11e9-864f-d2c4685d43ea.png)
Oddly, it's not an issue for the non-React package:
![screen shot 2019-02-13 at 1 59 02 pm](https://user-images.githubusercontent.com/28028994/52736430-d7e22500-2f97-11e9-9fcd-9f5cd07c028a.png)
As mentioned by @MariaBamundo, setting `position: static` fixes this. The parent dimmer aligns its children in the center, so we don't need `position: absolute`. Some initial cross-browser testing suggests that setting `position: static` doesn't break things in any browser. So it may make sense to just take out `position: absolute` from `.ui.modal`. This should probably be done in the semantic-ui package. I'll open an issue there.

**Comment by layershifter** [comment]
I provided a fix in #3679, please try it, feedback there is much appreciated 🙌
