### ISSUE TITLE
Accordion not working with custom react components

### ISSUE THREAD

**Issue by Anton0123** [Semantic-Org/Semantic-UI-React#3392]
### Steps
Create an Accordion and pass a render function to the panels prop. In the render function add a content object with "as" set to a custom made react component. 

### Expected Result
The accordion should operate as normal

### Actual Result
All the content is always displayed no matter if the panel is collapsed or open

### Version
0.84.0

### Testcase
https://codesandbox.io/s/pm92xkx5mx

**Comment by layershifter** [comment]
I updated your code to get it working correctly:
- https://codesandbox.io/s/8n73r599xj using `MessageList` as `content`
- https://codesandbox.io/s/0p8op5268p using spread of unhandled props (`className` was not applied)
