### ISSUE TITLE
Switch to FomanticUI ?

### ISSUE THREAD

**Issue by murbanowicz** [Semantic-Org/Semantic-UI-React#3397]
Shouldn't we switch over to use FomanticUI as SUI development stopped?

They are at 2.7, API is exactly the same so far, they are adding components (loaders, calendar(!)) etc. 
I think semantic-UI-react would really benefit from that?

https://github.com/fomantic/Fomantic-UI

**Comment by layershifter** [comment]
> SUI development stopped?

It's incorrect, where have you seen this? 🤔 

> API is exactly the same so far

Correctly, so you can switch to their CSS and get some important fixes. `semantic-ui-react` relies on SUI, `fomantic-ui-react` can exist and may be should, but I don't have plans to spend time on it now.

> https://react.semantic-ui.com/

Semantic UI React is the official React integration for Semantic UI.

---

/cc @levithomason

**Comment by murbanowicz** [comment]
> > SUI development stopped?
> 
> It's incorrect, where have you seen this? 

Over 700 open issues, over 100 PRs when many being closed without comments etc.
Last release 4 months ago.

It is really sad because SUI is really great but there is clear stagnation in the development, but with stagnation of SUI there will be stagnation of this great React lib

**Comment by GGAlanSmithee** [comment]
Seems like one goal of Fomantic-UI is to be merged back to SUI, from their README.md

> NOTE: Fomantic was created to continue active development of Semantic-UI and has the intent to be merged back into the master repository once active development can restart.

**Comment by murbanowicz** [comment]
@layershifter which features?
Recent releases of FUI fix many SUI issues. 
The key point FUI is in active development. SUI not. 
SUI React is such a great UI library for React that it is really bad to loose possibilities of improvements/new components because of stale of development of SUI core.

As @GGAlanSmithee mentioned - FUI was forked with intention to merge back into SUI if/when development becomes active again.

**Comment by layershifter** [comment]
https://fomantic-ui.com/introduction/new.html
All features from FUI 2.7 are not compatible with SUI. I mean that if we will introduce them they will not work with SUI. We have many issues to fix with existing components and I don't want to focus on new features before this.

It's OSS so I can't block you from forking to Fomantic UI React. Feel free to work on it :tada:

**Comment by rdsedmundo** [comment]
I really believe that this should be reconsidered. I definitely agree that a repository with 700+ issues and 100+ PRs opened, with the last commit on 21 Oct, shouldn't be considered maintained.

Look at this PR for example:
https://github.com/Semantic-Org/Semantic-UI/pull/6689

Although it was a false-positive, as there wasn't a security breach because the version that SUI is using is very old, if it was the case though we'd be still almost half a year later waiting to it to be reviewed and merged.

We all appreciate the work that you're doing here @layershifter @levithomason, but seriously what's the point of keep maintaining an integration for something that is abandoned?

**Comment by layershifter** [comment]
Please hear me, Fomantic UI has more features and it's not compatible with Semantic UI. I.e. we can't add `Slider` component from FUI because SUI doesn't have styles for it. If we will decide to switch to Fomantic UI it should be Fomantic UI React. Do you see the _issue_?

_I_ don't have time to work it on Fomantic UI React, sorry.

**Comment by y0hami** [comment]
I just want to add my 2 cents here.

Believe it or not I am all for keeping SUIR using SUI. @layershifter is right when he says that it would no longer be compatible if SUIR moved to FUI with the styles not being available etc when using SUI. As @layershifter has said he doesn't have time to maintain a FUI port and I think I can safely say no one on the SUIR team can either and I have said multiple times that we also over at FUI don't have the time to maintain a port also.

I do understand that this is a problem but for what it's worth SUIR will just need to say backed by SUI.

I do want to say that for FUI v3 we will be trying to address this issue as best we can but that won't be any time soon. So for anyone who wants to use FUI with React I would highly recommend coming over to the [FUI repo](https://github.com/fomantic/Fomantic-UI) to discuss this.

**Comment by layershifter** [comment]
Things changed, at least for me. Semantic UI is obviously dead the last release happened in 2018:
![image](https://user-images.githubusercontent.com/14183168/88811453-de2d8680-d1b6-11ea-8ca7-f2c3821fc7e7.png)

We will continue to maintain compatibility with Semantic UI and Fomantic UI via compat layer, see issues with [compat tag](https://github.com/Semantic-Org/Semantic-UI-React/issues?q=is%3Aissue+is%3Aopen+label%3A%22compat%3A+Fomantic+UI%22).

For now, I definitely recommend to switch to Fomantic UI. Our docs will be updated to have a notice about Fomantic UI.

/cc @hammy2899 @lubber-de

**Comment by bakeiro** [comment]
Hi! 🙋‍♂️ 
I would like to start a new project, using FUI and React, what's the status of the FUI compatibility? it's something ready to use? I can start a project with React and FUI or it's not ready yet??
thanks!
