### ISSUE TITLE
Error trying to run in webpack cannot resolve module 'utils/Meta'

### ISSUE THREAD

**Issue by tslater** [Semantic-Org/Semantic-UI-React#340]
I get the following error:

```
ERROR in ./~/stardust/dist/collections/Breadcrumb/Breadcrumb.js
Module not found: Error: Cannot resolve module 'utils/Meta' in /path/to/project/node_modules/stardust/dist/collections/Breadcrumb
 @ ./~/stardust/dist/collections/Breadcrumb/Breadcrumb.js 21:12-33
```

It is fixed when I make this change:

`var _Meta = require('utils/Meta');`   -->  `var _Meta = require('../../utils/Meta');`

Is that a proper fix?

**Comment by levithomason** [comment]
Indeed, though this should be made to the `src/collections/Breadcrumb/Breadcrumb.js` directory.

We use webpack resolve to resolve root paths for the doc site.  Somehow, this one slipped through into the library.  All library paths in `src` should be relative.

**Comment by levithomason** [comment]
Would you like make a PR?

**Comment by tslater** [comment]
I can try. I'll start working through the contributing guidelines.

**Comment by levithomason** [comment]
Thanks. In this case you can fork this repo, make a commit to Breadcrumb in `src` that updates the path, then open a PR against master.

**Comment by levithomason** [comment]
@tslater note @layershifter has submitted a pr ^

**Comment by tslater** [comment]
Opps. I guess I was too late on that one. Should I delete mine? It looks like there was a doc that needed updating too.
#342

**Comment by levithomason** [comment]
I merged both since they updated different parts.  Thanks!

**Comment by tslater** [comment]
Awesome. Glad I could help in some small way. Awesome work on the package!
