### ISSUE TITLE
Single Dropdown Select - showing label

### ISSUE THREAD

**Issue by tresdev** [Semantic-Org/Semantic-UI-React#3401]
### Problem description
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y
![124123](https://user-images.githubusercontent.com/17851573/51785219-c7f4d380-2197-11e9-8df0-24645e4c27a9.PNG)

I can't figure out how to put label or flag in the selected item. It just shows text value provided in the options props.

### Proposed solution
I want to put label in the selected item as in the dropdown item list.

For multiple selection, renderLabel prop can handle this problem, but for single-select, it is not. I might be able to create a custom dropdown, but I think it makes sense to have  something like renderLabel function, or any other way to show label or flag in the selected item also, not just items in the dropdown item list.

#852 seems to be related with this issue, but still I can't find out how to customize the selected item, except just to alternate the text to something else.

### MVP
https://codesandbox.io/s/5qq2nm7ol

**Comment by isaacs-gh** [comment]
Is this the same as: https://github.com/Semantic-Org/Semantic-UI-React/issues/3468 ?

**Comment by tresdev** [comment]
> Is this the same as: #3468 ?

@isaac-ipl Oh well. yeah. It seems like the same one.
