### ISSUE TITLE
Checkbox: no way to prevent to be focused

### ISSUE THREAD

**Issue by eltonio450** [Semantic-Org/Semantic-UI-React#3402]
## Bug Report

Hello :)

### Steps
With the current implementation, I cannot find a way to prevent a checkbox to be focused when clicked. I tried with e.preventDefault() and also by forcing the tabIndex to be "null", undefined, etc.

### Expected Result
There should be a way to prevent a checkbox to acquire the focus when clicked, for exemple using preventDefault. It would be closer to the input checkbox behaviour.

(For information: my use case is a focus problem with react-hotkeys)

### Actual Result
The checkbox is focused no matter what

### Version
0.84.0

### Testcase: 
Check the focused element in the consle
https://codesandbox.io/s/l97zrrpq87

Please let me know if I missed something

**Comment by layershifter** [comment]
In native `input[type=checkbox]` you can prevent focus in `onMouseDown` handler: https://codesandbox.io/s/semantic-ui-react-wq5ys

We should do the same thing in our component, fix is coming 🚀 
Sorry, for the late visit 😿
