### ISSUE TITLE
Portal: controlled portal is not closed on button click

### ISSUE THREAD

**Issue by xumix** [Semantic-Org/Semantic-UI-React#3408]
### Steps
https://react.semantic-ui.com/addons/portal/#types-controlled

1.  Click "Open portal"
2. Click  "Close portal"

### Expected Result
Portal closed

### Actual Result
Portal is not closed

### Version
0.84.0

### Testcase
Docs: https://react.semantic-ui.com/addons/portal/#types-controlled

**Comment by Fabianopb** [comment]
What's happening is that the click on the button is being listened as a click on the document, what sets the state as `false`, and right after that it listen for the click on the button, setting its state to `true`.

This is apparently a misuse in the docs. `Portal` should receive a `trigger` prop to control its state. The component's lifecycle checks if there's a click on the trigger, and in such case it cancels the document listener.

Here's a gif showing that:
![portal-trigger](https://user-images.githubusercontent.com/15076656/52296459-1c156a00-2987-11e9-8b47-f79558235e00.gif)

If that's correct, I can submit a PR fixing the docs.

**Comment by layershifter** [comment]
@Fabianopb feel free to submit PR 👍

**Comment by Fabianopb** [comment]
PR created!
