### ISSUE TITLE
The Icon component can't be used

### ISSUE THREAD

**Issue by chandaraly** [Semantic-Org/Semantic-UI-React#3409]
### Steps
A clear and concise description of steps to reproduce the problem.

### Expected Result
The result that you expected.

### Actual Result
The actual result that happened 💣

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Please fill issue template fully :octocat:
