### ISSUE TITLE
Placeholder not working

### ISSUE THREAD

**Issue by jonasdev** [Semantic-Org/Semantic-UI-React#3410]
## Bug Report
The placeholder component doesn't show anything. I can see the html tags in the dom, but I can also see, that the classes has no CSS at all

### Steps
`<Placeholder>
    <Placeholder.Line />
  </Placeholder>
`
### Expected Result
To create a placeholder line

### Actual Result
Nothing shown. No effect, other than it gets rendered in the dom. 

### Version
0.84.0

**Comment by layershifter** [comment]
https://codesandbox.io/s/5y7onnl524

Please make sure that you're using SUI >=2.4.0, it's mentioned in docs:
![image](https://user-images.githubusercontent.com/14183168/52135166-d9355880-264d-11e9-9d8d-ae7346dbec6f.png)
