### ISSUE TITLE
Option to attach dropdown menu to body

### ISSUE THREAD

**Issue by elmarcarillo** [Semantic-Org/Semantic-UI-React#3411]
### Problem description
We have a dropdown in a row of a scrollable table. Since the table has `overflow: hidden`, the dropdown gets truncated when opened. It would be nice to have an option to have the menu attach to the body to show the entire menu (Maybe in a Portal).

**Comment by layershifter** [comment]
1. This feature is not supported by SUI core: https://semantic-ui.com/modules/dropdown
2. BTW, according to ARIA practices `Dropdown` should be rendered inline: https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html

Sorry, but we will not implement this feature.
