### ISSUE TITLE
Incorrect hand icon being shown

### ISSUE THREAD

**Issue by armaandh** [Semantic-Org/Semantic-UI-React#3413]
### Steps
Create an icon with "hand point left" for the name, and you will see incorrectly a map pin. 

### Expected Result
Expect to see the icon for a hand pointing left.

### Actual Result
Actual result is the icon for a map pin. 

### Version
semantic-ui-react: "version": "0.84.0"
semantic-ui-react/event-stack: "version": "3.0.1"

**Comment by layershifter** [comment]
![image](https://user-images.githubusercontent.com/14183168/52227977-cde66500-28b9-11e9-86f1-a614e682f28e.png)

Please make sure that you're using the latest version of SUI, i.e. 2.4.2:
https://codesandbox.io/s/yvzv80mo2j
