### ISSUE TITLE
DimmerInner error on version above 0.83.0

### ISSUE THREAD

**Issue by rami-yohay-imedis** [Semantic-Org/Semantic-UI-React#3415]
Hi , 
I was using version 0.83.0 and updated to 0.85.0 via the npm
Now I get an error related to DimmerInner.

I`m running on windows 10.

This is the stack trace when the page loads ( it is the main page ): 

DimmerInner.js?9152:36 Uncaught TypeError: Object(...) is not a function
    at new DimmerInner (DimmerInner.js?9152:36)
    at constructClassInstance (react-dom.development.js?61bb:6355)
    at updateClassComponent (react-dom.development.js?61bb:7839)
    at beginWork (react-dom.development.js?61bb:8225)
    at performUnitOfWork (react-dom.development.js?61bb:10224)
    at workLoop (react-dom.development.js?61bb:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:581)
    at invokeGuardedCallback (react-dom.development.js?61bb:438)
    at renderRoot (react-dom.development.js?61bb:10366)
DimmerInner @ DimmerInner.js?9152:36
constructClassInstance @ react-dom.development.js?61bb:6355
updateClassComponent @ react-dom.development.js?61bb:7839
beginWork @ react-dom.development.js?61bb:8225
performUnitOfWork @ react-dom.development.js?61bb:10224
workLoop @ react-dom.development.js?61bb:10288
callCallback @ react-dom.development.js?61bb:542
invokeGuardedCallbackDev @ react-dom.development.js?61bb:581
invokeGuardedCallback @ react-dom.development.js?61bb:438
renderRoot @ react-dom.development.js?61bb:10366
performWorkOnRoot @ react-dom.development.js?61bb:11014
performWork @ react-dom.development.js?61bb:10967
requestWork @ react-dom.development.js?61bb:10878
scheduleWorkImpl @ react-dom.development.js?61bb:10732
scheduleWork @ react-dom.development.js?61bb:10689
enqueueSetState @ react-dom.development.js?61bb:6212
Component.setState @ react.development.js?72d0:237
update @ index.js?0a70:196
(anonymous) @ index.js?0a70:206
Promise.then (async)
componentWillMount @ index.js?0a70:205
callComponentWillMount @ react-dom.development.js?61bb:6370
mountClassInstance @ react-dom.development.js?61bb:6435
updateClassComponent @ react-dom.development.js?61bb:7840
beginWork @ react-dom.development.js?61bb:8225
performUnitOfWork @ react-dom.development.js?61bb:10224
workLoop @ react-dom.development.js?61bb:10288
callCallback @ react-dom.development.js?61bb:542
invokeGuardedCallbackDev @ react-dom.development.js?61bb:581
invokeGuardedCallback @ react-dom.development.js?61bb:438
renderRoot @ react-dom.development.js?61bb:10366
performWorkOnRoot @ react-dom.development.js?61bb:11014
performWork @ react-dom.development.js?61bb:10967
requestWork @ react-dom.development.js?61bb:10878
scheduleWorkImpl @ react-dom.development.js?61bb:10732
scheduleWork @ react-dom.development.js?61bb:10689
scheduleTopLevelUpdate @ react-dom.development.js?61bb:11193
updateContainer @ react-dom.development.js?61bb:11231
(anonymous) @ react-dom.development.js?61bb:15226
unbatchedUpdates @ react-dom.development.js?61bb:11102
renderSubtreeIntoContainer @ react-dom.development.js?61bb:15225
render @ react-dom.development.js?61bb:15290
render @ app.js?5606:69
(anonymous) @ app.js?5606:106
./app/app.js @ main.js:877
__webpack_require__ @ main.js:744
fn @ main.js:122
0 @ main.js:4036
__webpack_require__ @ main.js:744
(anonymous) @ main.js:864
(anonymous) @ main.js:867
react-dom.development.js?61bb:9747 The above error occurred in the <DimmerInner> component:
    in DimmerInner (created by Dimmer)
    in Dimmer (at index.js:79)
    in div (at index.js:6)
    in Block (at index.js:78)
    in LoginPage (created by InjectIntl(LoginPage))
    in InjectIntl(LoginPage) (created by Connect(InjectIntl(LoginPage)))
    in Connect(InjectIntl(LoginPage)) (at injectLogic.js:33)
    in withLogic(Connect(InjectIntl(LoginPage))) (at injectReducer.js:33)
    in withReducer(withLogic(Connect(InjectIntl(LoginPage)))) (created by LoadableComponent)
    in LoadableComponent (created by Route)
    in Route (at index.js:16)
    in Switch (at index.js:15)
    in div (at index.js:12)
    in Flex (at index.js:14)
    in App (at app.js:73)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (at app.js:72)
    in IntlProvider (at index.js:21)
    in LanguageProvider (created by Connect(LanguageProvider))
    in Connect(LanguageProvider) (at app.js:71)
    in Provider (at app.js:70)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js?61bb:9747
captureError @ react-dom.development.js?61bb:10540
renderRoot @ react-dom.development.js?61bb:10391
performWorkOnRoot @ react-dom.development.js?61bb:11014
performWork @ react-dom.development.js?61bb:10967
requestWork @ react-dom.development.js?61bb:10878
scheduleWorkImpl @ react-dom.development.js?61bb:10732
scheduleWork @ react-dom.development.js?61bb:10689
enqueueSetState @ react-dom.development.js?61bb:6212
Component.setState @ react.development.js?72d0:237
update @ index.js?0a70:196
(anonymous) @ index.js?0a70:206
Promise.then (async)
componentWillMount @ index.js?0a70:205
callComponentWillMount @ react-dom.development.js?61bb:6370
mountClassInstance @ react-dom.development.js?61bb:6435
updateClassComponent @ react-dom.development.js?61bb:7840
beginWork @ react-dom.development.js?61bb:8225
performUnitOfWork @ react-dom.development.js?61bb:10224
workLoop @ react-dom.development.js?61bb:10288
callCallback @ react-dom.development.js?61bb:542
invokeGuardedCallbackDev @ react-dom.development.js?61bb:581
invokeGuardedCallback @ react-dom.development.js?61bb:438
renderRoot @ react-dom.development.js?61bb:10366
performWorkOnRoot @ react-dom.development.js?61bb:11014
performWork @ react-dom.development.js?61bb:10967
requestWork @ react-dom.development.js?61bb:10878
scheduleWorkImpl @ react-dom.development.js?61bb:10732
scheduleWork @ react-dom.development.js?61bb:10689
scheduleTopLevelUpdate @ react-dom.development.js?61bb:11193
updateContainer @ react-dom.development.js?61bb:11231
(anonymous) @ react-dom.development.js?61bb:15226
unbatchedUpdates @ react-dom.development.js?61bb:11102
renderSubtreeIntoContainer @ react-dom.development.js?61bb:15225
render @ react-dom.development.js?61bb:15290
render @ app.js?5606:69
(anonymous) @ app.js?5606:106
./app/app.js @ main.js:877
__webpack_require__ @ main.js:744
fn @ main.js:122
0 @ main.js:4036
__webpack_require__ @ main.js:744
(anonymous) @ main.js:864
(anonymous) @ main.js:867
DimmerInner.js?9152:36 Uncaught (in promise) TypeError: Object(...) is not a function
    at new DimmerInner (DimmerInner.js?9152:36)
    at constructClassInstance (react-dom.development.js?61bb:6355)
    at updateClassComponent (react-dom.development.js?61bb:7839)
    at beginWork (react-dom.development.js?61bb:8225)
    at performUnitOfWork (react-dom.development.js?61bb:10224)
    at workLoop (react-dom.development.js?61bb:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:581)
    at invokeGuardedCallback (react-dom.development.js?61bb:438)
    at renderRoot (react-dom.development.js?61bb:10366)

**Comment by layershifter** [comment]
Please fill an issue template and add a minimal repro case. It's not clear how we can find the issue.

Ping me when it will be filled correctly.

**Comment by okloecker** [comment]
Since this report was closed without explanation, I'd like to add a hint for others in the same situation: this has happened to me as well with react 16.2.0, but a clean new app (create-react-app) with current 16.8.2 works ok. Forcing the app to use 16.2.0 showed this error again, so it must be an incompatibility between react and SUIR.
Steps:
`$ create-react-app suid-dimmer-loader && cd suid-dimmer-loader && npm i -S semantic-ui-react`
Modify src/App.js:
```import './App.css';

import { Dimmer, Loader } from 'semantic-ui-react';
import React, { Component } from 'react';

class App extends Component {
  render() {
    return (
       <Dimmer active>
          <Loader active size="massive">Logging out</Loader>
       </Dimmer>
    );
  }
}

export default App;
```
`$ npm start`

So I guess the solution is to update to the latest react and react-dom.

**Comment by layershifter** [comment]
The current version of SUIR requires React 16.3 at least, https://github.com/Semantic-Org/Semantic-UI-React/blob/master/package.json#L174
