### ISSUE TITLE
Dropdown: Received `true` for a non-boolean attribute `selection`

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#3416]
### Steps
A clear and concise description of steps to reproduce the problem.

Add a  `search: true` or `selection: true` to the dropdown component

One of the examples from your page:

```
import React from 'react'
import { Dropdown } from 'semantic-ui-react'

const countryOptions = [ { key: 'af', value: 'af', flag: 'af', text: 'Afghanistan' } ]

const DropdownExampleSearchSelection = () => (
  <Dropdown placeholder='Select Country' fluid search selection options={countryOptions} />
)

### Expected Result

No errors in the console.

### Actual Result

This in the console:

```
index.js:1 Warning: Received `true` for a non-boolean attribute `selection`.

If you want to write it to the DOM, pass a string instead: selection="true" or selection={value.toString()}.
    in div (created by Input)
    in Input (created by SelectComponent)
    in SelectComponent (created by FormView)
```

Looks like `search` and `selection` are making their way to Input

### Version
0.85.0

### Testcase

https://codesandbox.io/s/n5qknrzq6m

It's stuck on Transpiling modules for me, but you should have no issues to test this in your code.

**Comment by layershifter** [comment]
I tested yours and I've updated to latest versions: https://codesandbox.io/s/k0563wo8o

---

![image](https://user-images.githubusercontent.com/14183168/52401867-70296700-2acb-11e9-8f59-6a069c88a675.png)

----

```
in div (created by Input)
in Input (created by SelectComponent)
in SelectComponent (created by FormView)
```

`Input` component definitely not support `selection` prop.

**Comment by tomitrescak** [comment]
I'm not sure what is going on, this only happens when packed with a specific webpack instance. Ignore for now. I have a reproducible case, but only on one webpack instance, others seem to behave fine on the same code. Wonder of JS programming ...
