### ISSUE TITLE
TextArea with autoHeight doesn't shrink when lines deleted

### ISSUE THREAD

**Issue by mashabow** [Semantic-Org/Semantic-UI-React#3418]
### Step

1. Input multiple lines in a TextArea with `autoHeight`  // → TextArea's height grows to fit the lines
2. Delete some lines.

### Expected Result

TextArea's height shrinks to fit the remaining lines.

### Actual Result

TextArea's height doesn't change on deleting.

![feb-07-2019 18-40-45](https://user-images.githubusercontent.com/6268183/52402673-3e82c100-2b08-11e9-9ce6-5fda376fbcc8.gif)

### Version
0.85.0
Does not occcur in 0.84.0.

### Testcase
**https://codesandbox.io/s/qzn3nzwr1j 0.85.0**
https://codesandbox.io/s/104r4oy993 0.84.0 (correct)

**Comment by layershifter** [comment]
The issue comes from #3343.
