### ISSUE TITLE
Checkbox: become checked even when clicked using the right/middle mouse button

### ISSUE THREAD

**Issue by ThiefMaster** [Semantic-Org/Semantic-UI-React#3419]
### Steps
Click any checkbox on https://react.semantic-ui.com/modules/checkbox/ with the right or middle mouse button

### Expected Result
Nothing (except the browser's default action for that mouse button, i.e. opening the context menu / autoscrolling)

### Actual Result
The checkbox was toggled

---

This is quite annoying as someone who uses both middle-button autoscrolling and right-button-based mouse gestures a lot: I do not expect either of these actions to trigger actions on websites, and for the standard checkboxes in both the browser and the operating system (I think it's consistent across windows, linux, probably macos as well) only the left mouse button toggles the checkbox.

**Comment by layershifter** [comment]
Native `input` doesn't have this behavior, should be fixed:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

**Comment by harish-a** [comment]
@layershifter I can take this issue

**Comment by layershifter** [comment]
Sure :+1:
