### ISSUE TITLE
(feat): word count for TextArea

### ISSUE THREAD

**Issue by patrickmao1** [Semantic-Org/Semantic-UI-React#3424]
Input component has a lot of features come with it, but TextArea component still feels plain. Don't you think TextArea needs a bit of love too? It would be nice to include commonly used textarea features such as word count into the component so we don't need to reinvent it.

**Comment by layershifter** [comment]
As I understand you want something like [this](https://www.npmjs.com/package/react-textarea-count)?

Going to downvote this feature by two reasons:
- it's non common enough
- it will require additional styling that is out of SUIR scope as we don't provide CSS
