### ISSUE TITLE
Dropdown gives "Warning: Can't perform a React state update on an unmounted component."

### ISSUE THREAD

**Issue by therealgilles** [Semantic-Org/Semantic-UI-React#3426]
## Bug Report
I am getting the following warning from the Form.Dropdown component:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Dropdown (created by FormField)
    in div (created by FormField)
    in FormField (created by FormDropdown)
    in FormDropdown (at myComponent.js:335)
    in div (created by FormGroup)
    in FormGroup (at myComponent.js:319)
    in form (created by Form)
    in Form (at myComponent.js:318)
```

Here is how I use it:

```
                                              <Form.Dropdown
                                                width={8}
                                                className="select-user"
                                                deburr
                                                selection
                                                search
                                                clearable
                                                placeholder="Guest"
                                                options={usersOptions}
                                                defaultValue={usersDefaultValue}
                                                onChange={this.userDropdownChange}
                                                selectOnBlur={false}
                                                selectOnNavigation={false}
                                              />
```

I am doing as setState of my own variables in userDropdownChange. 

### Steps
The error only occurs when I hit the return key to select an item from the dropdown menu. If I use the mouse, I do not get the error.

### Expected Result
I am not expecting to get a React error.

### Actual Result
See error message above 💣

### Version
0.84.0

### Testcase
I am not able to provide a testcase yet. My attempts to reproduce do not show the error. Let me know if this was already fixed in 0.85.0 by any chance.

**Comment by layershifter** [comment]
Please provide an example on Codesandbox with repro steps and ping me then, I will reopen the issue.

**Comment by therealgilles** [comment]
I tried 0.85.0 and I got the same error. Now the interesting thing is that the problem does not happen with my production build (not sure if the React warnings are just disabled then). My test case does not show the problem still. Will get back if I can easily reproduce it.
