### ISSUE TITLE
parts of website (https://react.semantic-ui.com/) down

### ISSUE THREAD

**Issue by jasan-s** [Semantic-Org/Semantic-UI-React#3432]
### Steps
go to https://react.semantic-ui.com/modules/modal/ 
### Expected Result
show modal component docs 
### Actual Result
blank screen

browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

<img width="1138" alt="screen shot 2019-02-12 at 10 23 00 am" src="https://user-images.githubusercontent.com/13863953/52658574-45b32180-2eb0-11e9-9763-fd7abbcef2dc.png">

**Comment by layershifter** [comment]
Works fine for me, can you provide the console output?
And browser, too

**Comment by layershifter** [comment]
See the issue 👿 

We have the similar issue recently: https://github.com/stardust-ui/react/pull/857
It's a CDN issue, can you please try to hard reload the page and check that file https://cdn.jsdelivr.net/npm/@babel/standalone@7.1.0/babel.min.js is loaded fully?

**Comment by jasan-s** [comment]
tried hard reload and that https://cdn.jsdelivr.net/npm/@babel/standalone@7.1.0/babel.min.js is loaded.
issue remains

**Comment by layershifter** [comment]
Just to be sure, https://cdn.jsdelivr.net/npm/@babel/standalone@7.1.0/babel.min.js has the same ending?

![image](https://user-images.githubusercontent.com/14183168/52659221-81c4a180-2f05-11e9-8537-5eb3a794a5df.png)

**Comment by jasan-s** [comment]
no it ends  with this. 
<img width="1131" alt="screen shot 2019-02-12 at 10 37 38 am" src="https://user-images.githubusercontent.com/13863953/52659527-4947a800-2eb2-11e9-9b77-27b1401148ef.png">

**Comment by layershifter** [comment]
You're showing `babel-preset-env.min.js` while I need `babel.min.js` 🦅

**Comment by jasan-s** [comment]
sorry. here it is. 
<img width="1636" alt="screen shot 2019-02-12 at 10 40 20 am" src="https://user-images.githubusercontent.com/13863953/52659656-a5aac780-2eb2-11e9-8ec2-db846d5ba046.png">

**Comment by layershifter** [comment]
This code in the middle of file, it's a CDN issue, again 👎 
If it will not fixed tomorrow, please let us know. I wanted to ship some improvements, but these issue can force me to do them

**Comment by cvince** [comment]
:+1: I'm also experiencing issues too. 
![screen shot 2019-02-12 at 2 10 43 pm](https://user-images.githubusercontent.com/1720051/52661420-0399d800-2ed0-11e9-9e95-661745a69d69.png)

**Comment by MartinKolarik** [comment]
@jasan-s please check now (with a hard reload)

**Comment by jasan-s** [comment]
working now. closing.
