### ISSUE TITLE
Input: with size "tiny" is same as size "medium"

### ISSUE THREAD

**Issue by therealgilles** [Semantic-Org/Semantic-UI-React#3439]
## Bug Report
The support for the "tiny" size for the Input element seems to be missing.

### Steps
<Input size="tiny" placeholder="foo" />

### Expected Result
I would expect the size "tiny" to be bigger than "mini" and smaller than "medium".

### Actual Result
Instead "tiny" is the same as "medium". I believe the css is missing for this size.

### Version
0.85.0

### Testcase
Even your own test case in the documentation is missing the "tiny" size:
https://react.semantic-ui.com/elements/input/#variations-size

**Comment by lubber-de** [comment]
Good catch! Added the missing CSS to Fomantic-UI

**Comment by layershifter** [comment]
Nice catch, SUI hasn't support of `tiny` size on `Input`. Going to remove it from `propTypes`.

**Comment by therealgilles** [comment]
It's a bit odd that some sizes are not supported, isn't it? should I file a bug with SUI?

**Comment by layershifter** [comment]
> should I file a bug with SUI?

You can try, but SUI core has issues with development. You can try to fill it in: https://github.com/fomantic/Fomantic-UI/issues

**Comment by lubber-de** [comment]
@layershifter @therealgilles As mentioned above, it's already fixed in FUI (next release) and referenced to this issue 😉  by https://github.com/fomantic/Fomantic-UI/pull/492

**Comment by therealgilles** [comment]
I'm not sure what should be done here. If all development is going into fomantic (just getting acquainted with it right now), then the size could give. Otherwise, I don't know.

**Comment by layershifter** [comment]
> I'm not sure what should be done here.

I want to speak with Levi about this. FUI has too many bug fixes that consumers are need.
For current, we need to keep parity with SUI. May be we will come with another decision in near future.
