### ISSUE TITLE
Checkbox: no longer prevents default after updating to version 0.85.0

### ISSUE THREAD

**Issue by hasen011** [Semantic-Org/Semantic-UI-React#3440]
## Bug Report
Hi, we are using a Card component with a toggle Checkbox in its header. The Card component is also used as a link (from react-router-dom), so we need to prevent the link from firing when we click the toggle. Everything was working fine until we updated to version 0.85.0 from 0.83.0.

### Steps
Use a card component (as a link) with a checkbox in it and try preventing default when you click the checkbox to prevent the link from firing.

### Expected Result
Checkbox is checked without being redirected to the link.

### Actual Result
Prevent default doesn't work anymore so you are redirected to the link.

### Version
"semantic-ui": "^2.4.2"
"semantic-ui-react": "^0.85.0"

### Testcase
I created an example without a link which uses stopPropagation instead but the described behavior can still be observed if switched between the two versions. I wonder if this could be caused by this PR: https://github.com/Semantic-Org/Semantic-UI-React/pull/3351

https://codesandbox.io/s/0oxky24lyp

EDIT: Here is an example with a link: https://codesandbox.io/s/2zxzr1jw5p

Thanks for any help!

**Comment by layershifter** [comment]
Was fixed in #3435, the issue in 0.85.0 comes from #3351. We used there an event from `mouseup` instead `onclick`, it cause the described issue.
