### ISSUE TITLE
Semantic ui react docs not working properly

### ISSUE THREAD

**Issue by amitpatil321** [Semantic-Org/Semantic-UI-React#3441]
### Steps
When I visit https://react.semantic-ui.com/ webpage seems messed up, I tried incognito mode as well.

### Expected Result
It should look nice.

### Actual Result
I can see lot of js errors in console
Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
polyfill.min.js:1 Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
babel.min.js:1 Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
babel-preset-env.min.js:1 Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
faker.min.js:1 Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED

### Version
NA

![image](https://user-images.githubusercontent.com/3007471/52902969-45af7a80-323e-11e9-890a-b359d804504b.png)

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Looks like the same issue as in #3432. Please try to hard refresh the page and ensure that https://www.jsdelivr.com/ is available to you.
