### ISSUE TITLE
Button className not working

### ISSUE THREAD

**Issue by bitsmyth** [Semantic-Org/Semantic-UI-React#3442]
I want to give margins to the Button Component but it the styles from the `.css` does not apply.
But if I set the margins via **inline Style it **does**** apply.

```
      <Button
            className="myButton"
            size={"massive"}
            /* style={{
              marginLeft: "100px",
              marginRight: "100px"
            }} */
          >
            MY_BUTTON
      </Button>

.myButton {
  margin-left: 100px;
  margin-right: 100px;
}
´´´

**Comment by hasen011** [comment]
Try using !important in your myButton class.

**Comment by layershifter** [comment]
Please post usage questions on StackOverflow: https://stackoverflow.com/questions/tagged/semantic-ui-react
