### ISSUE TITLE
Modal: unexpectedly closes when using inline `as` prop

### ISSUE THREAD

**Issue by sorahn** [Semantic-Org/Semantic-UI-React#3443]
## Bug Report
if you have the `as` prop for a Modal as an inline function, once the component re-renders at least once, it loses its ability to track clicks that are inside the modal, and the triggers it to close.

### Steps
* Create a modal component.
* use an inline function for `as`
* do something to make the component re-render (click the button)
* click anywhere inside the modal

### Expected Result
Modal stays open

### Actual Result
Modal closes

### Version
0.85.0

### Testcase
https://codesandbox.io/s/918jowm18w

**Comment by layershifter** [comment]
It's a bug, the `RefFindNode` component should update refs on `didUpdate`:
```diff
+  componentDidUpdate() {
+    // eslint-disable-next-line react/no-find-dom-node
+    handleRef(this.props.innerRef, findDOMNode(this))
+  }
```

The main issue there that our existing code is not ready to handle this correctly, going to introduce a PR with switch to `createRef()` API everywhere inside the SUIR and then we will able to fix this issue, too.

**Comment by sorahn** [comment]
Sounds good.   The reason I had it inline was I was using other code generated inside the component, but I found out that the `Modal` component does pass all the props to that component, so I can do it by just adding a custom prop to `Modal` and then use that like example 2.

I'm actually rendering the modal as a `form` tag so that a `<Button type='submit'>` in the `ModalActions` can submit the form.

**Comment by sorahn** [comment]
@layershifter do added the 'help wanted' tag to this.  Do you want a PR? It sounded like from your comment that it would be largely irrelevant because you have a bigger fix in the works.

**Comment by layershifter** [comment]
@sorahn you're right, I'm working on it right now, for example #3448. Hope to finish this work on this week 👍
