### ISSUE TITLE
Corner label with button tag - icon not in the right place

### ISSUE THREAD

**Issue by moshfeu** [Semantic-Org/Semantic-UI-React#3462]
### Problem description
Sadly, I couldn't find a way to add corner label to `Card` so I used the html option as add the `class` names manually. The thing is that it's working well only on `a` tag while, I think, the most usage for label like this is `button` (like button like in the example). I know that I can use `a` tag as button but it's bad semantic.

https://codesandbox.io/s/3v5qowxxn5

### Proposed solution
Change the icon's css (use `absolute` position) so it will be no different regards the parent element type. 

### MVP
https://codesandbox.io/s/mmjm3xwrpp

**Comment by layershifter** [comment]
Your issue is correct and  workaround is fine, but we don't handle CSS questions there, please move them to the main repo: https://github.com/Semantic-Org/Semantic-UI

At this time it will be easier to get a fix in Fomantic UI: https://github.com/fomantic/Fomantic-UI

**Comment by layershifter** [comment]
With fixes in your MVP you can use components:
```jsx
<Label as='button' corner="right">
  <Icon name="save" />
</Label>
```

We provide only JS, so any styling issues can be resolved with CSS 🐈

**Comment by moshfeu** [comment]
Ok. Thanks! With the css it does the job.
