### ISSUE TITLE
Add link button style (non border)

### ISSUE THREAD

**Issue by moshfeu** [Semantic-Org/Semantic-UI-React#3463]
### Problem description
A link style button (non border, tertiary) can be useful. Just like  https://fomantic-ui.com/elements/button.html#tertiary.

### Proposed solution
Add this option, take `basic` style just drop the `box-shadow` prop.

### MVP
https://codesandbox.io/s/mj8l0nkv39

**Comment by layershifter** [comment]
You can use Fomantic UI with SUIR: https://codesandbox.io/s/qkql95ok5w

---

Sorry, but we don't handle CSS questions there, please move them to the main repo: https://github.com/Semantic-Org/Semantic-UI
