### ISSUE TITLE
Search: Why does using resultRenderer my data to have title and key fields?

### ISSUE THREAD

**Issue by kayqq** [Semantic-Org/Semantic-UI-React#3464]
I am trying to use a custom renderer in my Search component. I want to re-use my `uid` and `username` as key without having to reformat my `results` to include `title` and `key` fields. 

Is there a way to pass my `uid` as a key prop from my custom resultRenderer to `<SearchResult />` inside of `<Search />`?
Why does using resultRenderer require a title prop? Is there a way to override this or a way around it that doesnt require altering the data objects in the `results` array?

Custom renderer:
```
const resultRenderer = ({ uid, username }) => (
    <span key={uid} title={username}>
        {username}
    </span>
);
```

My Search component's settings
```
<Search
    onResultSelect={onResultSelect}
    onSearchChange={onSearchChange}
    results={results}
    resultRenderer={resultRenderer}
    value={searchTerm}
/>
```

Example results array:
```
results = [
    { 
        uid: "4735ce9132924caf8a5b17789b40f79c",
        username: "jimmy"
    }, 
    { 
        uid: "971029de22304eb38b22da5fc7757354",
        username: "bobby"
    }
]
```

**Comment by layershifter** [comment]
Duplicate #1141.
