### ISSUE TITLE
Dropdown with object as value throws warning

### ISSUE THREAD

**Issue by danydhondt** [Semantic-Org/Semantic-UI-React#3466]
The Dropdown `options` property accepts a single value or an array of values.
In most cases however, the 'dataprovider' of a dropdown would be an array of objects retrieved from a service.
Referencing a selected object in the dropdown is important. So I set the `value` property in the options to the object itself.
To see an example, here's a [codesandbox](https://codesandbox.io/s/8nm782o0m2).

As you can see, this works perfectly but two warnings will be thrown in the console:

    Warning: Failed prop type: Invalid prop `options[0].value` supplied to `Dropdown`. 
    in Dropdown`
    Warning: Failed prop type: Invalid prop `value` supplied to `DropdownItem`.
    in DropdownItem`

If passing object as value to the options property works without a problem, then the warning should be omitted.

**Comment by layershifter** [comment]
You should pass `value` as `string` it's a known limitation and there will be no changes in a short-term.

**Comment by danydhondt** [comment]
Has there been a discussion in the past on this topic? It's a very handy feature and it actually _works_

**Comment by layershifter** [comment]
You can search in our issues. actually it's works partially. There are many places in the `Dropdown` component where it uses `===` (deep equal) check on `value`s and will silently break the object compassion.

**Comment by kostaslamo** [comment]
It would be very helpful if we could pass `objects` as values instead of a `string` or `arrays` of `strings`. A common use case is when somebody changes the state on the `onChange` function and uses the value which is an `object` to update the state. If the value is a string, an id for example, you should make one more step, for e.x a lookup to an `array` of `objects` to find the `object` to update the state with.

**Comment by felipenmoura** [comment]
No updates on that yet?
This is very useful if you want to pass in some react component. I was trying to use icons (not from the package, but an svg) in the content and, although it works, it throws that annoying error.

**Comment by leebailey88** [comment]
Same issue here. The code works fine when passing a react component to Dropdown `text` property, but throws an annoying warning in the console. Should the warning be removed and the `text` prop be updated to be {object|string}?
