### ISSUE TITLE
input placeholder can copy

### ISSUE THREAD

**Issue by wlk1204** [Semantic-Org/Semantic-UI-React#3467]
click input, and leave mouse to another double click , placeholder`s word can copy

**Comment by layershifter** [comment]
It's not possible to copy `placeholder` in the native `input` element: https://www.w3schools.com/howto/howto_css_placeholder.asp

I don't see any reasons to implement this as the component's behavior. However, it can be done by `onFocus()/onBlur()` stuff, you can create a question on StackOverflow for this.
