### ISSUE TITLE
Can't acquire Input ref in Popup

### ISSUE THREAD

**Issue by Wyverex42** [Semantic-Org/Semantic-UI-React#3473]
## Bug Report
I have a simple problem: I want to auto-focus an Input that is contained in a Popup as soon as the Popup opens. I tried three different versions (see Testcases below).

### Steps

- Specifying the ref in the Input
- Wrapping the Input with a Ref
- getElementById

But in all of those cases, I cannot get a valid ref to the Input (or even get the Input by ID).
I'm not sure if this is a bug in semantic-ui-react or a usage issue.

### Expected Result
When the popup is opened, the contained Input is focused and the user can start typing

### Actual Result
The popup is opened but the Input is not focused.

### Version
0.85.0

### Testcase
Input ref
https://codesandbox.io/s/0m622w563n

Ref wrapper
https://codesandbox.io/s/84jq9q9678

getElementById
https://codesandbox.io/s/n76z0xq920

**Comment by layershifter** [comment]
You should use refs inside `useEffect()` and `did*` methods as refs are commited during the commit phase, this covered in: https://overreacted.io/react-as-a-ui-runtime/

BTW, you can also use functional refs: https://reactjs.org/docs/refs-and-the-dom.html#callback-refs
Working example: https://codesandbox.io/s/rj0o9y5o4m

**Comment by Wyverex42** [comment]
Thank you!

So to make sure I understood this completely:

The Input ref will only exist during the commit phase which implicitly means that it won't exist during any event handlers. But it does exist in did* methods.
Now in order to determine when the correct moment is to focus the input, we need to catch the state transition from closed to open. That's why we need to store this information in the component state, hence the onOpen and onClose handlers on the popup. 

What I'm not entirely sure about is why the `open={this.state.open}` is needed. The popup is still opened if I remove that property, only the focusing doesn't work, but I don't really understand why.
Would you mind elaborating on that?

Cheers

**Comment by layershifter** [comment]
I've updated CodeSandbox, https://codesandbox.io/s/rj0o9y5o4m
In this case `onMount()`/`onUnmount()` look more reasonable. It worked with `this.state.open` because it trigger additional render of `Popup.Content` and another commit phase.

**Comment by Wyverex42** [comment]
I see, this makes sense now. Thank you very much!
