### ISSUE TITLE
Trying to instantiate an instance of a component in each pane

### ISSUE THREAD

**Issue by wisdom-17** [Semantic-Org/Semantic-UI-React#3475]
### Steps
1) Create component which uses the Tab feature from Semantic UI. The render() method should be something like below (_Note that I'm instantiating an instance of the "Simple" component in each pane, therefore I have two instances of this component)_:
```
render() {
    const panes = [
        { 
            key: 1,
            menuItem: "Panel Data", 
            render: () => 
                <Tab.Pane attached={false}>
                    <Simple />
                </Tab.Pane>
        },
        { 
            key: 2,
            menuItem: "Geolocation Data", 
            render: () => 
                <Tab.Pane attached={false}>
                    <Simple />
                </Tab.Pane>
        }
    ]
    return (
        <Tab 
            menu={{ secondary: true, pointing: true }} 
            panes={panes} 
        />
        
    )
}
```
2) Simple component is like so:

```
export class Simple extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            test: []
        }

        this.handleTestButtonClick.bind(this)
    }

    handleTestButtonClick(randomValue){

        this.setState({test: [...this.state.test, randomValue] });
    }

    
    render() {
        console.log(this.state.test)
        return(
            <Button 
                onClick={(e) => this.handleTestButtonClick(uuid())}
            >   
            Test
        </Button>
        )
    }
}
```

3) Click on the 'Test' button in **each** pane. Click on this button and then have a look in the console at what is returned by the console.log() statement.

### Expected Result
One would expect the console.log() statement in the "Simple" component to show one element in an array (both of the elements would be different values)

### Actual Result
The output of the console.log suggests that this is not two instances of the "Simple" component but one instance - as the state is the same regardless of which pane the 'Test' button is clicked on.

### Version
"semantic-ui-react": "^0.83.0",

I initially created a [question for this on Stackoverflow](https://stackoverflow.com/questions/54942221/in-reactjs-is-component-state-tied-to-an-instance-of-the-component-or-is-it-tied?noredirect=1#comment96649965_54942221) before I deduced that the behaviour was only happening when putting the instances in Tab.Pane.

**Comment by layershifter** [comment]
https://react.semantic-ui.com/modules/tab/#types-basic

![image](https://user-images.githubusercontent.com/14183168/53739717-24d06180-3e9b-11e9-8f84-cb1a435b8722.png)
It seems that you're looking for this: https://react.semantic-ui.com/modules/tab/#types-basic-all

**Comment by wisdom-17** [comment]
Adding` renderActiveOnly={false} ` results in none of the panes beind rendered. Explicitly setting it true (as it is by default) results in the original behaviour ie state is changing in both instances

**Comment by layershifter** [comment]
> Adding`renderActiveOnly={false}` results in none of the panes beind rendered.

Markup is different in this case, check the code:

```jsx
const panes = [
  { menuItem: 'Tab 1', pane: 'Tab 1 Content' },
  { menuItem: 'Tab 2', pane: 'Tab 2 Content' },
  { menuItem: 'Tab 3', pane: 'Tab 3 Content' },
]

const TabExampleBasicAll = () => <Tab panes={panes} renderActiveOnly={false} />
```

**Comment by wisdom-17** [comment]
I changed my mark up to match the above and it resulted in expected behaviour;

```
render() {
    const panes = [
        { 
            key: 1,
            menuItem: "Panel Data", 
            pane: <Tab.Pane><Simple /></Tab.Pane>
        },
        { 
            key: 2,
            menuItem: "Geolocation Data", 
            pane: <Tab.Pane><Simple /></Tab.Pane>
        }
    ]
    return (
        <Tab 
            menu={{ secondary: true, pointing: true }} 
            panes={panes}
            renderActiveOnly={false} 
        />
        
    )
}
```

Many thanks for your help.

**Comment by wisdom-17** [comment]
This gives the expected outcome, however I am now getting the following message in the console:

 Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `Tab`.

I added a key prop to each object in my panes array but the message still appears. Where do I need to add the key prop?
