### ISSUE TITLE
Popup: doesn't reposition when changing its context

### ISSUE THREAD

**Issue by Wyverex42** [Semantic-Org/Semantic-UI-React#3478]
## Bug Report
I have a shared Popup that is meant to be used as a tooltip. I explicitly don't want to have a Popup associated with all items on my page that can have a tooltip because this creates a LOT of popups and hurts performance.
So my solution is to use global state via https://github.com/diegohaz/constate to share the ref of the DOM node where the Popup should be opened.
Sadly, positioning the popup via the `context` property doesn't work correctly in my use case.

### Steps
- Open https://codesandbox.io/s/vmm391vpv7
- Open the main popup
- Hover over any item
- A tooltip opens
- Hover over another item next to the first one
- The tooltip doesn't move
- Move the mouse to the border of the main popup so that the main popup stays open but the tooltip closes 
- Hover over another item in a different row or column
- The popup opens in a new position

### Expected Result
- When closing a popup and reassigning its `context`, the popup should be positioned at the updated context when it's opened the next time.
- The popup should point to the correct corner of its `context`

### Actual Result
- The popup doesn't move when being reopened. It only moves if it completely disappeared first.
- The popup doesn't point to the correct corner of its `context` DOM element

I suspect I could make it work if I could somehow wait until the popup is completely gone until reopening it again. I've tried several combinations of state logic but none has worked for me so far.
Even then it will probably still have issues with pointing at the correct corner.

### Version
0.85.0

### Testcase
https://codesandbox.io/s/vmm391vpv7

**Comment by layershifter** [comment]
Sorry, but we don't have time to debug your code. It looks crazy and I'm completely lost in it 🦏 
Can you please reopen issue with a **minimal** repro or update existing?

**Comment by Wyverex42** [comment]
Ok, I've now spent close to another two hours trying to compress this example even more. Luckily I could get rid of constate and the hack. Also, you don't even need to nest the popup. This is as short as it gets:
https://codesandbox.io/s/q83oky26xq

The issues are still visible.

I can't reopen the issue though since you already closed it and I'm no collaborator.

**Comment by layershifter** [comment]
Now it's clear to me, will try to find the root issue.
