### ISSUE TITLE
Dropdown code sandbox not working

### ISSUE THREAD

**Issue by mattnedrich** [Semantic-Org/Semantic-UI-React#3479]
### Steps
1. Visit https://react.semantic-ui.com/modules/dropdown/
2. Select "Code Sandbox" for the "Selection" or "Search Selection" variants

### Expected Result
It allows you to open a code sandbox for the dropdown component

### Actual Result
Progress indicator displayed and never finishes

**Comment by Fabianopb** [comment]
Just checked at the current master, bug confirmed, I'll take a look soon!

**Comment by layershifter** [comment]
It's caused by some internal imports like this:
```js
import { friendOptions } from '../common'
```

This code is not uploaded to CodeSandbox 🤔

**Comment by layershifter** [comment]
@Fabianopb I've updated some components in #3486, feel free to update `Search` component's docs 👍

**Comment by Fabianopb** [comment]
Sounds good, I'll work on that!

**Comment by Fabianopb** [comment]
#3486 and #3494 merged, should we close the issue?

**Comment by layershifter** [comment]
Removed some imports in #3511 (`ComponentExampleRenderSource.js`), @Fabianopb thanks for your work there 👍
