### ISSUE TITLE
Can't clear a clearable single-selection Dropdown using the keyboard

### ISSUE THREAD

**Issue by quiqueg** [Semantic-Org/Semantic-UI-React#3481]
## Bug Report
Semantic-UI-React v0.85.0 added the Dropdown `clearable` prop, allowing users to clear the value of a selection Dropdown by clicking the ✖️ button. This button can be pressed via mouse, but not via keyboard—which presents an accessibility issue.

### Steps
See https://codesandbox.io/s/7mr7p7zwy6, with:
```jsx
<Dropdown options={options} selection clearable />
```

1. Click the Dropdown. (=> a list of options is rendered)
2. Select an option by clicking or by pressing ENTER. (=> A clear ✖️ icon appears)

### Expected Result
The clear ✖️ button is interact-able via the keyboard.

### Actual Result
The clear ✖️ button is not interact-able via the keyboard.

### Version
0.85.0

### Testcase
https://codesandbox.io/s/7mr7p7zwy6

**Comment by layershifter** [comment]
Can you please refer to accessibility spec for this?

**Comment by layershifter** [comment]
Going to close this as I don't understand how it should work by a spec, please ping me with feedback.
