### ISSUE TITLE
Card react and image

### ISSUE THREAD

**Issue by mesh2356** [Semantic-Org/Semantic-UI-React#3483]
hello guys ,
im new to programming so please be patient . i want to use a new card in every item that i want to use.

i expected to have like this group of cards but it doesn't work 

![1](https://user-images.githubusercontent.com/48381770/54070906-5b74f600-4266-11e9-8e88-36dafea05004.PNG)

i used:
import React, { Component } from "react";
import factory from "../ethereum/factory";
import { Card, Button } from "semantic-ui-react";
import Layout from "../components/Layout";
import { Link } from "../routes";

class ItemIndex extends Component {
    static async getInitialProps() {
      const items = await factory.methods.getdeployeditems().call();
  
      return { items };
    }

  contactCards = () => {
    return this.props.items.map(address => (
      <Card fluid color="green" header={contract.address} />
    ));
  };
}

render();
return (
  <Layout>
    <div>
      <h3>available </h3>
      <Container>
        <br />
        <Card.Group>
          <Card fluid color="green" header="Option 1" />
          <Card fluid color="blue" header="Option 2" />
          <Card fluid color="red" header="Option 3" />
          {this.contactCards()}
        </Card.Group>
      </Container>
      <Link route="/items/new">
        <a>
          <Button
            floated="right"
            content="Add Room"
            icon="add circle"
            primary
          />
        </a>
      </Link>
      {this.renderItems()}
    </div>
  </Layout>
);

export default ItemIndex;

...................................................................
im using react , semantic ui and next.js 

the second issue that when i want to use an image where should i put the source , i mean the image path because i created a folder and copy the the path like 
Image src='/images/image.png' but i got an error message that the file is not found even that i tried 
Image src='http://localhost:3000/images/image.png'

........................................................
the third issue how can i use the image as input , i mean the user can upload image to website and after that i can used it to show

**Comment by layershifter** [comment]
Please use StackOverflow for usage questions, we use GitHub for tracking issues.
