### ISSUE TITLE
Example with Modal

### ISSUE THREAD

**Issue by alolis** [Semantic-Org/Semantic-UI-React#349]
Hello,

I am looking at the [documentation](https://technologyadvice.github.io/stardust/modules/modal) for Modal but It's not complete as it seems. Is it possible to have an example on how to properly use the Modal component?

Am I supposed to directly call the components `Modal.showModal()` or is there a better way?

Thank you for your time

**Comment by alolis** [comment]
Well, I figured out that the only way (I believe) is to use a `ref`

An example is the `Confirm` [addon](https://github.com/TechnologyAdvice/stardust/blob/a8351026c2a5de86c1cb307ea68658c14c12b441/src/addons/Confirm/Confirm.js) in case anyone is wondering.

**Comment by levithomason** [comment]
This is correct, the modal is currently setup to use a `ref` and the `showModal` / `hideModal` methods.  This will change soon as the Modal is scheduled to be updated to our v1 Component API, see https://github.com/TechnologyAdvice/stardust/issues/269.

Once that is complete, opening and closing the modal will be done via the [`active` prop](http://semantic-ui.com/modules/modal.html#active).  We may also provide an auto controlled version.  Cheers!
