### ISSUE TITLE
Problem with accordion and Tab in the same component

### ISSUE THREAD

**Issue by anuar-fullstack** [Semantic-Org/Semantic-UI-React#3491]
## Bug Report
Accordion and Tab inthe same component with one state which is activeIndex.
### Steps
i have accordion and Tab in the same component but in the documentation. they are both using activeIndex state. when i call create a separate activeIndex for my Tab. which I declare in the state "activeIndexNav" and change the activeIndex state to activeIndexNav in handleTabChange function.
### Expected Result
The result that you expected.

i expect that the tab will function properly whenever I click the Tab
### Actual Result
The actual result that happened 💣

I didn;t change the Tab content. when I click tab. 
### Version
x.y.z

### Testcase

https://codesandbox.io/s/2l3n74j9y
[semantic-ui-react.zip](https://github.com/Semantic-Org/Semantic-UI-React/files/2955350/semantic-ui-react.zip)

[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Please fill the issue template fully and add CodeSandbox example, I don't understand anything.
