### ISSUE TITLE
Tab grid props do not seem to take effect

### ISSUE THREAD

**Issue by alexerhardt** [Semantic-Org/Semantic-UI-React#3492]
### Steps
Trying to create a two-tab Tab component with each taking 50% width.
Creating a `Tab` component and passing the prop `grid={{ paneWidth: 16, tabWidth: 8 }` seems to have no effect.

### Expected Result
Each tab should have 50% width.

### Actual Result
Each tab is smaller than 50% width.

### Version
0.85.0

### Testcase
https://codesandbox.io/s/jj2m2480o9

**Comment by layershifter** [comment]
```jsx
<Tab menu={{ pointing: true, fluid: true, widths: 2 }} panes={panes} />
```
As `Tabs` are the simple combination of `Menu` and `Grid`/`Segment` components, you need to use correct shorthands, in this case for `Menu`. This will do exactly that you want :)

https://react.semantic-ui.com/collections/menu/#variations-evenly-divided
https://codesandbox.io/s/9o0nnqzz5y
