### ISSUE TITLE
Contributing to project

### ISSUE THREAD

**Issue by caphrim007** [Semantic-Org/Semantic-UI-React#350]
Hey folks,

I'd like to start contributing to the project, so I was going to start by working on documentation. I was reading the Contributing guide and using the Label component as an example.

I was curious, the Label has its doc block for props in the Label.propTypes format where-as (something like) the Table component does props inside of the component itself (and doesn't have doc block from what I could tell)

I was just wondering if the correct place for doc blocks in the Table example was in the static propTypes object or if there is a better place.

Thanks for all the hard work on this project!

**Comment by levithomason** [comment]
Hey thanks for the question. Yes, prop docs are generated from doc blocks on propTypes. It doesn't matter if propTypes are defined in a class, or on a function. Just as long as the prop has a doc block.

Stateless functional components will have the static property added after the function declaration whereas a class definition can include a `static` property within the class body itself. These are just javascript syntax differences. You'll see both in use in Stardust depending on the component. 

I'm on vacation this week so I may not respond as quick as usual. There is some more information on docs at the bottom of the contributing guide. You can also ping @davezuko and he can likely help you,  too. 

Cheers, see you next week!
