### ISSUE TITLE
Checkbox: `slider` is not clickable in the entire area

### ISSUE THREAD

**Issue by felixmosh** [Semantic-Org/Semantic-UI-React#3502]
## Bug Report
If you click in the space between the nub & the line it won't trigger the handler
### Steps
click in the are of the arrow 
![image](https://user-images.githubusercontent.com/9304194/54379390-f9672700-4691-11e9-9c31-7fc02318132e.png)

### Expected Result
It should allow click on the checkbox in that area.

### Actual Result
It not clicks there, therefore it is hard to click on the toggle.

### Version
0.86.0

### Testcase
It should work as the jQuery version that is clickable in that area.
Checkout how it works https://semantic-ui.com/modules/checkbox.html#fitted

**Comment by layershifter** [comment]
## With `label`

### SUI Slider

![sui-slider](https://user-images.githubusercontent.com/14183168/54455930-92b33d80-4765-11e9-8bd1-8cc7f4654670.gif)

### SUIR Slider

![suir-slider](https://user-images.githubusercontent.com/14183168/54455990-b5dded00-4765-11e9-9bf3-83561831fc84.gif)

Works fine ⭐️ 

---

## Without `label`

### SUI 👍 

![sui-slider-bug](https://user-images.githubusercontent.com/14183168/54456175-2e44ae00-4766-11e9-90e5-fca46bac3173.gif)

### SUIR 💣 

![suir-slider-bug](https://user-images.githubusercontent.com/14183168/54456168-2be25400-4766-11e9-8045-d45edec4a059.gif)

**Comment by wvha** [comment]
I'm not exactly sure what the "hidden" classname does besides negative z-index, but if you remove it from the input element, the slider becomes clickable in the entire area, however this makes the label text have the wrong cursor on hover

**Comment by felixmosh** [comment]
It is possible to fix with given a label `min-height` of `1rem`, the problem is that this change should be done in semantic-ui css, what is the best practice regarding scenarios such that?

**Comment by felixmosh** [comment]
Ping

**Comment by layershifter** [comment]
I think that issue is around #3435, we partially handle clicks on `label` while for `slider` we should handle them fully. It's an initial suggestion.

**Comment by felixmosh** [comment]
@layershifter the issue is that the label is with height of `0px`.
![image](https://user-images.githubusercontent.com/9304194/54921962-c6355b00-4f0f-11e9-9c11-752a8c5507b1.png)

Otherwise, if I add it a `min-height` it starts to work (with the hover effect) as expected.
![image](https://user-images.githubusercontent.com/9304194/54922117-2af0b580-4f10-11e9-8340-2ddba3b8f0fe.png)

![image](http://g.recordit.co/oIdXDshx1j.gif)

**Comment by felixmosh** [comment]
Should I add the min-height to the label in semantic-ui css, or I can add it to inline style of the component.

@layershifter WDYT?

**Comment by layershifter** [comment]
@felixmosh this should be fixed on our side, fix is coming in #3693.
