### ISSUE TITLE
Popup: position not kept if trigger element changes

### ISSUE THREAD

**Issue by jsmrcaga** [Semantic-Org/Semantic-UI-React#3505]
### Steps
1 - Render a popup with a button (better if inside a custom component)
2 - Set the `onOpen` handler to simulate the button onClick or directly onClick to add a label to that button (managing this.setState for example, hence the custom component)
3 - Click the button in order to add a label to it
4 - Close the popup (by making any other action)
5 - Open the popup again, it should be located in the upper left corner of the screen (top: 0, left: 0)

### Expected Result
The expected result was to see the Popup under or around the Trigger element

### Actual Result
Actual result: 2nd render of popup is on coordinates 0,0

### Version
v0.83.0

### Testcase
https://codesandbox.io/s/62m4v7j13w

### Guesses
I've taken a peek at the `<Portal>` element controlling the popup behaviour, as well as the `<RefXXX`> elements. Sadly I don't have the time to investigate further, but I'm guessing that since the trigger element is re-rendered somewhere along the line the reference is lost, and thus the calculated positions are (0,0)

**Comment by layershifter** [comment]
We will switch to `react-popper` soon, it will resolve a ton of positioning issues.

**Comment by jsmrcaga** [comment]
@layershifter thanks for the quick answer! 
Do you happen to have a timeline for this switch ? 

Thanks a lot for your work/time!

**Comment by layershifter** [comment]
I'm going to finish with it before 1 Apr, after it will be done I will push Levi to release it :)

**Comment by jsmrcaga** [comment]
@layershifter great news! Thanks again!
Should i close the issue then, or can we close it now?

**Comment by layershifter** [comment]
It will be closed automatically 😺

**Comment by jsmrcaga** [comment]
Loving it!
