### ISSUE TITLE
TransitionablePortal: add same options as Portal

### ISSUE THREAD

**Issue by nolawnchairs** [Semantic-Org/Semantic-UI-React#3506]
## Feature Request

I use `TransitionalPortal` for displaying notifications and progress views at the bottom right of the viewport. When I click around the application, it closes on document click, and escape. It would be nice to add permanence to this view, and completely control when and how it disappears.

In my example, I use this to show the upload progress of large files to a server, so the end user can navigate around the rest of the application (in this case an Electron application) while keeping this view visible until the upload is complete.

![transitionable](https://user-images.githubusercontent.com/224439/54473841-db273580-480f-11e9-889e-d603f9a51ca7.png)

    <TransitionablePortal open={videoUploadStore.showProgress} transition={{ animation, duration }}>
      ... stuff ...
    </TransitionablePortal>

When the document is clicked anywhere, the portal transitions out, then transitions back in again (because the `open` prop is bound to a value in my Mobx store). Ideally, nothing would happen until the value in the store changes explicitly.

The props API for `Portal` has options for `closeOnDocumentClick` and other `closeOn*` properties, could these be applied / extended from the main Portal component? In other words, make this component controlled?

**Comment by layershifter** [comment]
Actually, all unhandled props will be passed to `Portal` component:
```jsx
<TransitionablePortal closeOnDocumentClick={false} />
```

Please check [`Controlled example`](https://react.semantic-ui.com/addons/transitionable-portal/#types-controlled).
