### ISSUE TITLE
Using with react-pose

### ISSUE THREAD

**Issue by sreenathan-nair** [Semantic-Org/Semantic-UI-React#3507]
Hi,

I'm pretty new to the react world and loving using the semantic components in my work. Thank you for the awesome work!

I have a general question regarding using the semantic ui components with `react-pose` for animation purposes. Would appreciate any examples or guidance on how one would go about wrapping the semantic component using `posed` wrapper.

I tried wrapping a `List` component like so

 `const WrappedList = posed(List)` 

and subsequently using it in JSX 

`
<WrappedList>
    <List.Item>Test<List.Item/>
<WrappedList/>
`

which throws errors stating the requirement of `forwardRef` attribute on the wrapped component i.e `WrappedList`. 

Unfortunately I'm very new to react and js in general and am unsure how to proceed. If someone could point in the right direction that would be awesome.

Thank you very much.

**Comment by layershifter** [comment]
We decided to omit `ref` forwarding and rely on `Ref` component for now, so you need to use manually:

```jsx
const ButtonWithRef = React.forwardRef((props, innerRef) => (
  <Ref innerRef={innerRef}>
    <Button {...props} />
  </Ref>
));
```

I also prepared completely working example for you: https://codesandbox.io/s/9o65vv9rj4 🍻

**Comment by sreenathan-nair** [comment]
Thank you very much for taking the time, works perfectly!
