### ISSUE TITLE
Embed iframe properties

### ISSUE THREAD

**Issue by nikrasiya** [Semantic-Org/Semantic-UI-React#3509]
Hello 👋
I'm pretty new to the react world and loving using the semantic components in my work. Thank you for the awesome work! I have doubt with the Embed component.

`<Embed
          iframe={{
            allowFullScreen: true,
            style: {
              padding: 10
            },
            rel: 0,
            controls: 0
          }}
          autoplay={true}
          id={videoId}
          source="youtube"
        />`

I am not able to _**hide controls**_ when _controls is passed as a property_ in the iframe. 
Can I not pass this in the iframe?

**Comment by layershifter** [comment]
```jsx
  <Embed
    iframe={{
      allowFullScreen: true,
      style: {
        padding: 10,
      },
      src:
        '//www.youtube.com/embed/O6Xo21L0ybE?autohide=true&amp;amp;autoplay=true&amp;amp;color=%23444444&amp;amp;hq=true&amp;amp;jsapi=false&amp;amp;modestbranding=false&amp;amp;rel=1',
    }}
    placeholder='/images/image-16by9.png'
  />
```

`controls` is not part of `iframe` props, see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe). It's a part of [Youtube's API](https://developers.google.com/youtube/player_parameters?hl=en#controls), we don't support all options in `Embed` and we don't plan to do this. We need to pass `controls=0` to `src` prop.
