### ISSUE TITLE
Grid is not showing columns in a row

### ISSUE THREAD

**Issue by rades12340** [Semantic-Org/Semantic-UI-React#3510]
```
## Bug Report
import React, { Component } from "react";
import { Grid } from "semantic-ui-react";

class EventDashboard extends Component {
  render() {
    return (
      <Grid>
        <Grid.Column width={10}>
          <h1>Left Column</h1>
        </Grid.Column>
        <Grid.Column width={6}>
          <h1>Right Column</h1>
        </Grid.Column>
      </Grid>
    );
  }
}

export default EventDashboard;

```
### Expected Result
I expect to columns sit side by side, but in this case they sit one under other.

### Actual Result
The actual result that happened 💣

### Version
"semantic-ui-css": "2.2.14",
"semantic-ui-react": "^0.79.0"

**Comment by layershifter** [comment]
https://codesandbox.io/s/qk942195v4
Please provide a repro case, there are no such issues even in old releases.

**Comment by rades12340** [comment]
> https://codesandbox.io/s/qk942195v4
> Please provide a repro case, there are no such issues even in old releases.

I just realized that I needed that I should import 

> import "semantic-ui-css/semantic.min.css"; 

in root component;
