### ISSUE TITLE
Visibility: Checking if bottom is visible not functional inside of a Modal

### ISSUE THREAD

**Issue by blakehatch** [Semantic-Org/Semantic-UI-React#3513]
## Bug Report
Semantic-UI React Visibility does not seem to be functioning properly inside of modals.

<img width="700" alt="Screen Shot 2019-03-18 at 12 12 00 AM" src="https://user-images.githubusercontent.com/48665344/54506364-74d70b80-4912-11e9-8f4e-b3debfb4260d.png">

### Steps
Take any element with visibility and place it inside of a modal, the visibility should stop being functional.

### Expected Result
When the bottom of the page is scrolled to, visibility should recognize that and call a function accordingly.

### Actual Result
When the bottom of the page is scrolled down to in the modal, Visibility does not recognize this and visibility does not call any functions that it is supposed to at the bottom of the page.

**Comment by layershifter** [comment]
https://codesandbox.io/s/jnzw70v695

Please provide a complete repro steps with minimal repro case on CodeSandbox.
