### ISSUE TITLE
Dropdown: child's onclick firing dropdown's onclick

### ISSUE THREAD

**Issue by Pushkarang** [Semantic-Org/Semantic-UI-React#3517]
## Bug Report

I recently updated semanti-ui-react from 0.80.0 to 0.86.0. I noticed  dropdown's onclick is getting fired from child's onclick, which was not the happening in v0.80.0.

### Steps
version 0.80.0 https://codesandbox.io/s/2vmzr1ol3n
version 0.86.0 https://codesandbox.io/s/woljqm5rok

1. Click on openModal
2. Click on close
### Expected Result
Modal should close

### Actual Result
It's triggering onClick of dropdown

### Version
0.86.0

By adding event.stopPropagation() in dropdown's onClick handler we can close modal.

**Comment by layershifter** [comment]
This change was done in `semantic-ui-react@0.82.0`, see #2880 and #2755.

We started to use modern `createPortal()` API and it bubbles events, so solution with `stopPropagation()` is correct.
> This includes event bubbling. An event fired from inside a portal will propagate to ancestors in the containing React tree, even if those elements are not ancestors in the DOM tree.

https://reactjs.org/docs/portals.html#event-bubbling-through-portals
