### ISSUE TITLE
Attached tables their cells are not equal in relation to header

### ISSUE THREAD

**Issue by Codebreaker101** [Semantic-Org/Semantic-UI-React#3519]
## Bug Report

Simple bug(ish) report. 

When using attached tables their cells are not equal in relation to header. Although this is not a semantic-ui specific issue nor a React one, I'm wondering is there a semantic-ui-react solution
to this problem?

### Version
0.84.0

### Demo
https://codesandbox.io/s/0340no2y6w?fontsize=14

**Comment by layershifter** [comment]
As `Table` creates markup from usual HTML `table`, you can use `table-layout: fixed`: http://jsfiddle.net/RsAhk/

Please use StackOveflow for usage questions.
