### ISSUE TITLE
Sidebar prop closable is not documented

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#3520]
### Steps
1. Go to https://react.semantic-ui.com/modules/sidebar/
2. View props for Sidebar

### Expected Result
closeable prop is part of Sidebar documentation

### Actual Result
closeable prop is not part of Sidebar documentation

### Version
0.85.0

**Comment by layershifter** [comment]
`closable` prop is not supported by `Sidebar` 🤔 Please clarify what do you mean...

**Comment by ghost** [comment]
I had an issue on iOS when touching outside the sidebar to close it but the sidebar would not close.

I searched for a solution to this issue and stumbled upon this pull request where sidebar closable prop was implemented: [Pull 2845](https://github.com/Semantic-Org/Semantic-UI-React/pull/2845/commits/1e4d48123a9e297500cc0f077efb1cd7b03af72c) - That's when I noticed it was not in the documentation and submitted this ticket.

In the end I noticed in the PR that the closable prop was set to "on" by default so that was never the actual issue for me and perhaps the prop has been removed by now. But my issue was solved by adding css style cursor: pointer on the Pusher since this is a known iOS issue for click events.
