### ISSUE TITLE
Firefox Floating Dropdown Items Not Accessible 

### ISSUE THREAD

**Issue by deeplyfriedchicken** [Semantic-Org/Semantic-UI-React#3521]
### Steps
1. Open up Firefox - 60.6.0esr (64-bit)
1. Go to https://react.semantic-ui.com/modules/dropdown/#types-floating
1. Click on the arrow of the `floating button` example
1. Hover over any elements on floated dropdown

My coworker pointer out that none of the elements are clickable on the dropdown on Firefox. I apologize I don't have screen shots, but essentially the cursor doesn't change to the pointer like it should, and you cannot interact with those elements including click and hover.
### Expected Result
Be able to interact with the dropdown items

### Actual Result
Cannot interact with any of the elements in the dropdown. Clicking only closes the dropdown list without actually clicking on an item.

### Version
0.86.0

### Testcase
https://react.semantic-ui.com/modules/dropdown/#types-floating

**Comment by layershifter** [comment]
PR is ready, it's not issue with component, so you can just pick up these changes.
Thanks for the report 👍
