### ISSUE TITLE
Visibility: Visibility not functional inside of a Modal

### ISSUE THREAD

**Issue by blakehatch** [Semantic-Org/Semantic-UI-React#3526]
## Bug Report
Semantic-UI React Visibility does not seem to be functioning properly inside of modals.

### Steps
Take any element with visibility and place it inside of a modal, some calculations for visibility will not function properly, notable with bottomVisible/topVisible.

### Expected Result
When the bottom/top of the page is scrolled to, visibility should recognize that and adjust their respective booleans according

### Actual Result
The booleans don't adjust themselves in a logical manner when the visibility is placed inside of a modal, it is potentially focused on the screen behind the modal.

### Version
^0.82.5

### Testcase
https://codesandbox.io/embed/vy83jjwz20?fontsize=14

**Comment by LeoTheMighty** [comment]
Yeah I'm also having this issue with Visibility inside Modals... It seems when the view is in a Modal, the scroll doesn't trigger the Visibility at all except at the initialization.

**Comment by johnkeane475** [comment]
I believe this may be related to this PR that's just been merged to master:
https://github.com/Semantic-Org/Semantic-UI-React/pull/3400

**Comment by layershifter** [comment]
Created simplified version of CodeSandbox: https://codesandbox.io/s/semanticuireactexample-j217f
Behaves as expected, if I missed something please ping me.
