### ISSUE TITLE
Selected dropdown is not showing with image. 

### ISSUE THREAD

**Issue by parthipan15** [Semantic-Org/Semantic-UI-React#3530]
### Steps
I have semantic react image dropdown. I can see the images in the dropdown but when selecting the item. Selected Item display text but not showing the image. 

### Expected Result
Selected values should be displayed along with image.

### Actual Result
Selected Item display text but not showing the image. 

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Duplicate #1147, see the matching issue for workarounds
