### ISSUE TITLE
Right-Click context menu

### ISSUE THREAD

**Issue by orangecoding** [Semantic-Org/Semantic-UI-React#3534]
### Problem description
For some menu's it makes sense to be able to use the native right click. For instance we use the Menu component to provide a navigation tabbar. It would make sense to be able to use right click -> open in new tab for this.

**Comment by layershifter** [comment]
There are no plans to implement this as it can be easily reached by existing components: https://codesandbox.io/s/jvq3845nov

**Comment by vkolova** [comment]
Right-click trigger on the Popup element would be nice, as a way to implement context menus.
