### ISSUE TITLE
Page component re-renders while trying to implement a responsive layout

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#3537]
I've implemented an app that uses react-router and Semantic UI React.

A tiny excerpt of the code can be found in [this gist](https://gist.github.com/AntoniosProvidakis/66f0f03dd395e19fd61901baf359b952).

As you can see, I'm trying to mimic [this approach](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/src/layouts/HomepageLayout.js) (using Responsive component) in order to have a responsive layout (mobile vs. non-mobile)

When I visit the "/people" route the People component renders as normal, the API call (fetchPeople) is made and data flows into the component.

Now, if I start resizing the window and the mobile media query is matched, two things are going to happen:

1. DesktopContainer will not render its children
2. MobileContainer will render its children

Which means that the People component (which was a child of DesktopContainer) will unmount, and as MobileContainer is rendered, a new People component will render, leading to the API call to be made again, etc. Take a look
![Problem](https://user-images.githubusercontent.com/15313363/55165188-a0a98b00-5175-11e9-94f0-4fe527a50f13.gif)

As a fix to this problem, someone might propose to lift the state of People component up and keep it into App component. But, I'm pretty sure that in this particular use case that state of People component should be self-contained.

Are there any suggestions on how to work around this problem?

**Comment by layershifter** [comment]
It's how React works, it will remount children in this case.

You have two solutions:
- **(best)** move state to the upper level, so will not have state reset
- use something like [`react-sizes`](https://github.com/renatorib/react-sizes) to get `isMobile` as prop.

Please use StackOverflow for usage questions 📖
