### ISSUE TITLE
Modal: display position is error.

### ISSUE THREAD

**Issue by zhcxk1998** [Semantic-Org/Semantic-UI-React#3538]
### Steps
When I update the dependencies. I found the Modal position was error!

**Then I used the demo of official website. But I found the bug again!**

Here is my code: 
```javascript
import React, { Component } from 'react';
import { Modal, Header, Button } from 'semantic-ui-react';
import 'semantic-ui-css/semantic.min.css';

export default class ModalTest extends Component {
  constructor(props) {
    super(props);
    this.state = {

    };
  }

  render() {
    return (
      <Modal trigger={<Button>Show Modal</Button>} centered>
        <Modal.Header>Select a Photo</Modal.Header>
        <Modal.Content>
          <Modal.Description>
            <Header>Default Profile Image</Header>
            <p>emmmm, I am a student.</p>
          </Modal.Description>
        </Modal.Content>
      </Modal>
    );
  }
}
```

### Expected Result
I had hoped the Modal would be in the middle.

### Actual Result
It's position was error. It overflowed the screen.
![image](https://user-images.githubusercontent.com/34026641/55171166-d1f47c00-51b2-11e9-803b-3371d511fd6c.png)

### Version
`"semantic-ui-css": "^2.4.1",`
`"semantic-ui-react": "^0.77.2",`

**Comment by layershifter** [comment]
> `"semantic-ui-css": "^2.4.1",`
> `"semantic-ui-react": "^0.77.2",`

![image](https://user-images.githubusercontent.com/14183168/55172642-07817100-5183-11e9-8eb6-45a3d2bad850.png)

If you will still able to repro it, please provide a repro on CodeSandbox.
