### ISSUE TITLE
Popup not triggered by SUIR component like Form.Input with children

### ISSUE THREAD

**Issue by xReaven** [Semantic-Org/Semantic-UI-React#3541]
## Bug Report

Hey everyone, first of all, I wanted to say that I saw it is already a known issue.

See [here](https://github.com/Semantic-Org/Semantic-UI-React/issues/1902) or [there](https://github.com/Semantic-Org/Semantic-UI-React/issues/3231), both relating to this [solution](solution).

However, the few issues I saw about it, are about really custom and self components, not about SUIR components.
I understand the given solution, but here I was using Form.Input with children, and, i'm surely missing a point, but I can't see how I can make it works.

I am not really familiar with HOC, I think it's what I am doing to make here.
CustomPopup will receive any Form sub-component, maybe with the Form.Select it is more appropriate if we put some options than a Form.Input, but I think it is easily understandable too.

Therefore, I wanted to apologize if it is a "1 more duplicate", but I was in doubt about the nature of this "issue", just misunderstanding something, or actually a bug of Form.Input.

Thanks in advance, trying my best in english explanations :).

### Steps

Give SUIR Popup's trigger, a SUIR component with children.

### Expected Result

The Popup appears when hovering the trigger component.

### Actual Result

The Popup do not appears.

### Version

SUIR 0.84.0

### Testcase

A code example show more than my words : https://codesandbox.io/s/ly871x242m

**Comment by layershifter** [comment]
It's issue with custom input:`FormInput` is a wrapper around `FormField` and `Input` components, the `Input` component doesn't pass all required props to your `CustomInput`: https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.86.0/src/elements/Input/Input.js#L206

We don't plan to change something there, as workaround consider to use Shorthand API, I prepared examples for you: https://codesandbox.io/s/mm3122p848
