### ISSUE TITLE
Form.Input onChange unbearably slow

### ISSUE THREAD

**Issue by chasen-bettinger** [Semantic-Org/Semantic-UI-React#3543]
### Steps
A clear and concise description of steps to reproduce the problem.

```

  const [input, setInput] = useState("");

  const updateInput = (e, { value }) => {
    let newValue = false;
    if (value.length > 0) {
      newValue = value;
    }

    setInput(newValue);
  };


  <Form onSubmit={onSub} size={"small"}>
          <Form.Group widths="equal">
                <Form.Input
                    onChange={updateInput}
                    fluid
                    placeholder="First name"
                  />
                <Form.Input fluid placeholder="Last name" />
           </Form.Group>
</Form>

```

### Expected Result

Both inputs type fast and without delay.

### Actual Result

![gif of input being slow](https://i.imgur.com/Y3h7scx.gif)

### Version
0.85.0
"react": "^16.8.3",

### Testcase

https://codesandbox.io/s/9o7q8ylj44

It isn't showcased in the above sandbox, so there must be something wrong with how I've organized my code. I toggled the repaint feature of Chrome and the only thing being repainted is the input box. I am confused as to why I am experiencing performance issues. 

Getting an endless stream of these messages:

```
[Violation] 'input' handler took 278ms
[Violation] 'input' handler took 186ms
[Violation] 'input' handler took 169ms
[Violation] 'input' handler took 171ms
[Violation] 'input' handler took 155ms
[Violation] 'input' handler took 153ms
[Violation] 'input' handler took 169ms
[Violation] 'input' handler took 167ms
```

**Comment by layershifter** [comment]
> It isn't showcased in the above sandbox, so there must be something wrong with how I've organized my code.

It seems that it's the reason. Please check your code with React's profiling tools and come back with a repro case 🚀
