### ISSUE TITLE
Adding a custom number picker component inside each options of a dropdown : React+ Semantic UI React

### ISSUE THREAD

**Issue by vjr12** [Semantic-Org/Semantic-UI-React#3544]
**Adding a custom number picker component inside each options of a dropdown : React+ Semantic UI React**

I am having this situation where I have to embed custom number picker with each options of a dropdown . Not really finding out a way to achieve it.
I have added the snippets for custom number picker as well as the code for dropdown.

**Number Picker Code:
---------------------------**
import * as React from 'react';

interface IState{
  value :  number;
}

interface IProps {
  setValue(val: number) : void;
}

class NumberPicker extends React.Component<IProps, IState> {  
   constructor(props : any) {
     super(props);
     this.state= {
                 value: 0,
     }
   }

  doDecrement= () => {
    if (this.state.value < 1) {
    } else {
      this.setState({
        value: this.state.value - 1
      }, () => {
            this.props.setValue(this.state.value);
         });
    }    
   }

   doIncrement =() => 
   {
    this.setState({
      value: this.state.value + 1
     }, () => {
            this.props.setValue(this.state.value);
       });
   }

  handleChange = (e  : React.ChangeEvent<HTMLInputElement>) => {       
    let val = parseInt(e.target.value);        
    this.setState({value: val});    
  }

  render() {

    return (
      <div className="App">
          <button onClick={this.doDecrement} className="fa fa-minus fa-inverse fa-2x"></button>
          <input type="text" className="number" value={this.state.value} onChange={this.handleChange}></input>
          <button onClick={this.doIncrement} className="fa fa-plus fa-inverse fa-2x"></button>
          </div>
    );
  }
}
export default NumberPicker;

**Semantic UI Dropdown component
----------------------------------------------**
import Select from 'semantic-ui-react/dist/commonjs/addons/Select';    
import * as React from 'react';
const options = [
      { key: 1, text: 'A', value: 'a' },
      { key: 2, text: 'B', value: 'b' },
      { key: 3, text: 'C', value: 'c' },
      { key: 4, text: 'D', value: 'd' }
    ]

class CustomDropDown extends React.Component<{},{}> {
       render(){
         return(
                   < Select options={options}  />     //here i need to add custom number picker for each option
        )
      }
export default CustomDropDown;

Can someone help me out with this? Help would be appreciated.

**Comment by layershifter** [comment]
Please use StackOverflow for usage questions: https://stackoverflow.com/questions/tagged/semantic-ui-react
