### ISSUE TITLE
Option to remove transition (blinking) from placeholder

### ISSUE THREAD

**Issue by ryanewtaylor** [Semantic-Org/Semantic-UI-React#3546]
## Feature Request

Please consider adding an option to turn off the transition on Placeholder elements. I think it would be helpful if there were an non-animated variant. 

### Problem description

I have a scenario where I want to display a Placeholder within table cells. However, the table doesn't start to load until the user has performed an action. I would like the Placeholder's to not be animated at first (to help indicate the layout) and to be animated once the user has performed the load action.

### Proposed solution

Something like `<Placeholder inanimate>` perhaps?

**Comment by layershifter** [comment]
This feature is not support by SUI core, so it can not be implemented on our side because we don't handle CSS.

But, it can be easily done by custom styling:
```jsx
<Placeholder style={{ animationPlayState: "paused" }}>
```

https://codesandbox.io/s/x86w5r8jz
