### ISSUE TITLE
Where can I find source codes for the buttons on the bottom of page https://react.semantic-ui.com/layouts/fixed-menu

### ISSUE THREAD

**Issue by joeyUOFA** [Semantic-Org/Semantic-UI-React#3548]
Hi,

I want to use the similar layouts and sources buttons on the bottom of page https://react.semantic-ui.com/layouts/fixed-menu. However, I cannot find the source codes for it in the GitHub repository.
Can anyone help me with this?

Thanks
--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

* Gitter Community Chat: https://gitter.im/Semantic-Org/Semantic-UI-React
* StackOverflow: https://stackoverflow.com/questions/tagged/semantic-ui-react using the tag `semantic-ui-react`
* Also have a look at our docs: http://react.semantic-ui.com

**Comment by layershifter** [comment]
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/src/components/LayoutsLayout.js
