### ISSUE TITLE
Make disable property of Popup useful for a fundamental use case

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#3556]
I suggest one of the fundamental use case for the disable property of the Popup component is for the implementation of a hover time delay, for example, don't show the popup unless the user hovers over the trigger for a minimum threshold of time.

Easily implemented using onMouseEnter, onMouseLeave and a timer.

Unfortunately upon the timeout setting disable to false (to show the popup) the Popup component does not re-render, but rather requires the user to remove the mouse from the trigger and then re-hover over the trigger. Not only is this non-intuitive, but the mechanism should disable the popup and re-arm the timer un this scenario anyway, meaning the popup is never enabled.

Could the Popup component be upgraded to support re-rendering after the disabled property changes without requiring a change in the mouse position? Thank you.

**Comment by layershifter** [comment]
Hey,

> Easily implemented using onMouseEnter, onMouseLeave and a timer.

It's already supported via `mouseEnterDelay` & `mouseLeaveDelay` props. Please check them: https://codesandbox.io/s/j7jy7838r9?module=/example.js

For other stuff I think that you're looking for controlled usage: https://react.semantic-ui.com/modules/popup/#usage-controlled

Please correct me if I am wrong and provide real use cases 🙏
