### ISSUE TITLE
Icon: props "flipped" and "rotated" will not combine

### ISSUE THREAD

**Issue by michaeljohansen** [Semantic-Org/Semantic-UI-React#3557]
### Steps
Subject says it all. Make an Icon, rotate it, and then try to flip it either horizontally or vertically.

### Expected Result
Icon should respect both "rotated" and "flipped" props simultaneously.

### Actual Result
Icon did not respect both "rotated" and "flipped" props simultaneously.

### Version
semantic-ui-react 0.86.0
(also semantic-ui-css 2.3.3)

### Testcase
https://codesandbox.io/s/8ljwvk4qrl

**Comment by layershifter** [comment]
![image](https://user-images.githubusercontent.com/14183168/55710599-a4e66b80-59f3-11e9-8645-6b988a6639aa.png)

A valid issue, but it's on CSS side: https://github.com/Semantic-Org/Semantic-UI/issues/6460
Want to mention that it was fixed https://github.com/fomantic/Fomantic-UI 2.4.2
