### ISSUE TITLE
Custom theme is not working after running `gatbsy build` 

### ISSUE THREAD

**Issue by EvaSpessotto** [Semantic-Org/Semantic-UI-React#3558]
## Bug Report

Hello !
I'm newbie to Semantic UI and GatsbyJS and I have a bug with Semantic UI and Gatsby JS: when I run my app with `gatsby develop` all works fine but when I run `gatsby build` then `gatsby develop` my theme is partially used !

Almost all my custom fonts aren't working, same thing for `font-size` properties. Only default properties for fonts are used.

Also my orverrides properties for button, message and label are nor working, I don't understand why...

I've notice that if I put `!important` after the property I want it's working but i dont' think this is a good way to do it.

Also I can't disable the Google Font request for Lato even if I use `@importGoogleFonts: false;` in `site.variables`.

### Steps

- Add custom properties in `site.variables` (for example)
- Run `gatsby develop` (theme should be working great)
- Then run `gatsby build` and `gatsby serve` (theme souldn't working)

### Expected Result

Custom theme is working after running `gatsby build`

### Actual Result

Custom theme is not working after running `gatsby build`

### Version
0.85.0

### Testcase

This is my repo (on branch 'mvp' ): https://github.com/commit42/new-site-c42/tree/mvp

This is when my theme is working:
![theme](https://user-images.githubusercontent.com/39422372/55734567-10463280-5a20-11e9-8c20-893ae489db79.png)

And this is after run `gatsby build`:
![theme2](https://user-images.githubusercontent.com/39422372/55734590-1b00c780-5a20-11e9-9d0a-e795d280486b.png)

**Comment by layershifter** [comment]
Please use StackOverflow for usage questions ❔ 

Actually, your issue can be easily solved, you should include only `semantic-ui-css` or `semantic-ui-less`.

`gatsby-browser.js`
```diff
-require("semantic-ui-css/semantic.min.css")
```

`src/pages/index.js`
```diff
-import "semantic-ui-css/semantic.min.css"
```

![image](https://user-images.githubusercontent.com/14183168/55736356-d24f0b80-5a2b-11e9-8e8e-a8f41926f805.png)

**Comment by EvaSpessotto** [comment]
OK sorry, I didn't know !
The think is, I've actually done this and it doesn't work for me. I'll ask on StackOverflow, thank you !

**Comment by ZLevine** [comment]
> Please use StackOverflow for usage questions ❔
> 
> Actually, your issue can be easily solved, you should include only `semantic-ui-css` or `semantic-ui-less`.
> 
> `gatsby-browser.js`
> 
> ```diff
> -require("semantic-ui-css/semantic.min.css")
> ```
> 
> `src/pages/index.js`
> 
> ```diff
> -import "semantic-ui-css/semantic.min.css"
> ```
> 
> ![image](https://user-images.githubusercontent.com/14183168/55736356-d24f0b80-5a2b-11e9-8e8e-a8f41926f805.png)

Are you recommending adding the CSS/LESS to both `gatsby-browser` _and_ the component? If so, what's the purpose of this?
