### ISSUE TITLE
Corner icons with 'left' or 'right' in name take direction of corner position

### ISSUE THREAD

**Issue by KunstDerFuge** [Semantic-Org/Semantic-UI-React#3561]
### Steps
Make an icon group with a non-default corner position
`<Icon.Group>`
`  <Icon name='font' />`
`  <Icon corner='top right' name='arrow down' />`
`</Icon.Group>`

### Expected Result
Corner icon should be rendered as down-pointing arrow

### Actual Result
Arrow points left or right based on corner position

### Version
0.86.0

### Testcase
https://codesandbox.io/s/k938q18vy5

**Comment by layershifter** [comment]
It's a valid issue, but it comes from CSS and can't be handled on our side :(

It comes from `left`/`right` word from `corner`:
![image](https://user-images.githubusercontent.com/14183168/55871909-5fad6f80-5b94-11e9-8545-2772714a75ca.png)


### Workaround 
```jsx
 <style>
      {`
i#fixed.icon:before {
  content: "\\f063";
}
  `}
    </style>
    <Icon.Group size="huge">
      <Icon name="font" />
      <Icon corner="top left" name="arrow down" id="fixed" />
    </Icon.Group>
```
https://codesandbox.io/s/zxjo4076zp
