### ISSUE TITLE
Sticky component not compatible with Table component

### ISSUE THREAD

**Issue by kelyndm** [Semantic-Org/Semantic-UI-React#3563]
### Problem description
I need a way to make Table Headers always visible while scrolling through a fairly large table. Currently this issue pops up whenever you try and do it:
https://github.com/Semantic-Org/Semantic-UI/issues/6020
Another possible solution could be to have a Table prop that would make it scroll independent of the window.

### Proposed solution
I tried to use the as prop in the Sticky with Table.Header or Table.Row, but that didn't work because Sticky still puts a div inside of the Table in various places. I am not sure if it is possible, but I would think that we could some how have Sticky render inside of the prop, instead of having to create a div of its own?

### MVP
I will look into a solution on this, but so far I have been unable to make this work by using semantic ui classes alone. I am still a fairly new dev, but use this library quite a bit. I would love to try and help if anyone has any ideas of what to try, but I am at a loss right now.

**Comment by layershifter** [comment]
Sorry, but we don't plan to support `Sticky` for `Table` component. Actually I don't see any way how we can satisfy markup there 😭 

You can get fixed header with CSS in fact: https://codesandbox.io/s/rnzxo99kq
However, if you need complicated tables with many features consider to use something like: https://github.com/tannerlinsley/react-table
