### ISSUE TITLE
Scrolling dropdown only shows on every second click if positioned near bottom of page

### ISSUE THREAD

**Issue by cj-clifton** [Semantic-Org/Semantic-UI-React#3567]
## Bug Report
I have a nested dropdown with scrolling enabled. If the dropdown is position near the bottom of the page, the nested dropdown will only show on every second time it is clicked. If you scroll the page so that the dropdown is position in the middle of the page, it shows every time. 

### Steps
Follow the testcase

### Expected Result
The nested dropdown to show every time I click it.

### Actual Result
The actual result that happened 💣

### Version
0.86.0

### Testcase
https://codesandbox.io/s/n5m11pz904

**Comment by layershifter** [comment]
Your issue is valid, but we are not going to fix the stuff related to Children API in `Dropdown`. Sorry, it can sound controversial and at the same time we don't have any replacement for it 😭

But, I am going to focus on #889 in mid-term. However, I will accept a fix if it will not overcomplicate component's code.

**Comment by cj-clifton** [comment]
Thanks for the response @layershifter. I've replaced the scrolling prop with the following css and it now works as expected.  Might be helpful for someone in the future.
```
//JS

<Dropdown>
    <Dropdown.Menu>
        <Dropdown item className="scrollingDd">
            <Dropdown.Item/>
        </Dropdown>
     </Dropdown.Menu>
</Dropdown>

//CSS

.scrollingDd .menu {
    height:400px; 
    overflow-y:scroll;
}

```

**Comment by zheyujie** [comment]
I got the same issue and here's my workaround, if it helps:
```
<Dropdown text='Main'>
    <DropdownMenu as='menu'>
        <Dropdown text='Nested' pointing='left' scrolling as={Menu.Item}>
            <DropdownMenu>
                ...
            </DropdownMenu>
        </Dropdown>
    </DropdownMenu>
</Dropdown>
```
