### ISSUE TITLE
Unexpected warnings

### ISSUE THREAD

**Issue by Naggertooth** [Semantic-Org/Semantic-UI-React#3572]
## Bug Report
Hi guys, I see some warnings in my console

Please check proptypes or your dependencies's proptypes

And also it would be great if I could pass an array to value without Json stringify for avoid one more warning or disable this warning

![image](https://user-images.githubusercontent.com/24671211/56327936-510f1b80-6185-11e9-9e84-6d2fe30fe81f.png)

But the value i passed is 

![image](https://user-images.githubusercontent.com/24671211/56327979-78fe7f00-6185-11e9-97e8-e94c8b28b24f.png)

And don't know what is that `Failed prop type: Invalid prop `options[0].value` supplied to `Dropdown`.`

### Steps
A clear and concise description of steps to reproduce the problem.

```
import moment from 'moment'

const graphFormat = 'YYYY-MM-DD'

const graphTimes = [
    { key: 'День', text: 'День', value: [moment().subtract(1, 'days').format(graphFormat), moment().format(graphFormat)] },
    { key: 'Неделю', text: 'Неделю', value: [moment().subtract(7, 'days').format(graphFormat), moment().format(graphFormat)] },
    { key: 'Месяц', text: 'Месяц', value: [moment().subtract(1, 'months').format(graphFormat), moment().format(graphFormat)] },
    { key: 'Год', text: 'Год', value: [moment().subtract(1, 'years').format(graphFormat), moment().format(graphFormat)] },
]

export default {
    graphTimes,
}
``` 
my values
```
<Dropdown
                            onChange={(e, d) => setDateRange(d.value)}
                            value={JSON.stringify(dateRange)}
                            options={graphTimes}
                            selection
                        />
```
my component

### Expected Result
No warnings

### Actual Result
The actual result that happened 💣
warnings

### Version
x.y.z

### Testcase
no testcase

**Comment by layershifter** [comment]
`value` for Dropdown's option should be `string`, in your case it's an `array`.

See these issues and others:
#3460 
#3153

We don't plan to change something in short-term.

**Comment by Naggertooth** [comment]
> `value` for Dropdown's option should be `string`, in your case it's an `array`.
> 
> See these issues and others:
> #3460
> #3153
> 
> We don't plan to change something in short-term.

Oh nooo
Look more carefully please

In my case it is a `string`
And always will be a `string`
`value={JSON.stringify(dateRange)}`
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

https://github.com/Semantic-Org/Semantic-UI-React/issues/3572#issue-434534230

https://user-images.githubusercontent.com/24671211/56327979-78fe7f00-6185-11e9-97e8-e94c8b28b24f.png

And if it is not enought

![image](https://user-images.githubusercontent.com/24671211/56360550-abdc5d80-61ed-11e9-961d-2ed34b4aa5e4.png)


Now it is a string from the helper

And it just can not be an array in any react lifecycle stage

But I still get it 

![image](https://user-images.githubusercontent.com/24671211/56360554-b4349880-61ed-11e9-865e-88b2a9c7fdcb.png)

**Comment by Naggertooth** [comment]
@layershifter Please take a look again
You did not read the issue carefully enough

**Comment by layershifter** [comment]
Please use CodeSandbox instead of screenshots.
As I see `graphTimes` as `options` while `graphTimes[0].value` is `array`, correct? But, it should be `string`...

**Comment by Naggertooth** [comment]
Okay...
### Testcase

https://codesandbox.io/embed/92oo3xoy9y

**Comment by Naggertooth** [comment]
Okay...
@layershifter 

### Here is testcase

https://codesandbox.io/embed/92oo3xoy9y

**Comment by layershifter** [comment]
```js
console.log(Array.isArray(graphTimes[0].value)) // true :(
```

**Comment by Naggertooth** [comment]
Sorry
Guess miss something

**Comment by layershifter** [comment]
Nevermind, you're welcome 🐱 

I want to relax `propTypes` for `value`/`option.value`, but as I mentioned before it's not so easy 😭

**Comment by Naggertooth** [comment]
Yep
warnings happened because I passed array to the `options.value`
😭
