### ISSUE TITLE
Sidebar onHide not working on Ipad safari

### ISSUE THREAD

**Issue by andrewgura** [Semantic-Org/Semantic-UI-React#3576]
I'm using the Sidebar component and the onHide function does not work with Ipad, it is working on other browsers and android. This is the code I have which is practically the same as the example yet it wont untoggle when clicking off of the Sidebar

```
  state = { visible: false }

  toggleMenu(){
    this.setState({visible: !this.state.visible})
  }

        <Sidebar.Pushable as={Segment}>
          <Sidebar
            as={Menu}
            animation='overlay'
            icon='labeled'
            inverted
            onHide={() => { this.setState({ visible: false }) }}
            vertical
            visible={visible}
            width='thin'
          >
```

**Comment by layershifter** [comment]
Sorry, but I don't have environment to test it 😭 

I am almost sure that this issue is related to https://github.com/Semantic-Org/Semantic-UI-React/pull/1833#issuecomment-313713611, can you please check?

**Comment by splNovikov** [comment]
Hi! I have the same issue on iphone/safari.
Works, like a charm - when I add empty function to Sidebar.Pusher onClick - sidebar closes as it should. I haven't dig into it yet, but it may be helpful for somebody.

**Comment by splNovikov** [comment]
And yes, @layershifter , [comment](https://github.com/Semantic-Org/Semantic-UI-React/pull/1833#issuecomment-313713611) helps to fix it.

**Comment by brianespinosa** [comment]
> And yes, @layershifter , [comment](https://github.com/Semantic-Org/Semantic-UI-React/pull/1833#issuecomment-313713611) helps to fix it.

Closing as this comment addresses the issue.
