### ISSUE TITLE
Sidebar: doesn't animate close

### ISSUE THREAD

**Issue by ZM123** [Semantic-Org/Semantic-UI-React#3578]
### Steps
Set the visibility of a sidebar to false

### Expected Result
The sidebar should animate while closing, in a reverse of the animation it had while opening

### Actual Result
It closes automatically without any animation

### Version
0.86.0

### Testcase
https://react.semantic-ui.com/modules/sidebar/

Clicking "Hide Sidebar" in the first example in the above link from the docs seems to show the issue. However, I've noticed the animation works as expected in [this example](https://react.semantic-ui.com/modules/sidebar/#usage-target) when clicking in the target area (clicking Hide Sidebar closes without animation as before)

Edit: after further investigation the example above seems to be an issue only in Chrome, the behaviour works as expected in Safari and Firefox. However I have noticed the issue occurring in other instances in these browsers as well (can't find a quick way to reproduce it at the moment)

**Comment by jjavierdguezas** [comment]
Hi, any update about this? I just update to `v0.87.1` and it still happens (in my app and in the first example in the docs). @ZM123 did you find any workaround?

**Comment by ZM123** [comment]
@jjavierdguezas Haven't found a workaround yet, I've done some experimentation and noticed different instances where it works and doesn't work (for example, in the first example on the demo page if you close it before it fully opens it animates closed) but I'm no closer to figuring out what exactly is causing it or how to fix it

**Comment by jjavierdguezas** [comment]
@ZM123  yeah me neither, thanks anyway

**Comment by layershifter** [comment]
This issue was introduced in #2845, working on a fix.

**Comment by layershifter** [comment]
@jjavierdguezas @ZM123 folks, I have introduced a fix in #3684. Can you please check it? 🙏
