### ISSUE TITLE
Correct misspelled word on docs @ `Dropdown` component

### ISSUE THREAD

**Issue by ShawnYcx** [Semantic-Org/Semantic-UI-React#3579]
<img width="1236" alt="Screen Shot 2019-04-23 at 4 15 14 PM" src="https://user-images.githubusercontent.com/7292742/56616641-7bc4fe00-65e3-11e9-9544-06c3a7fa1944.png">

**Comment by layershifter** [comment]
Fixed in https://github.com/Semantic-Org/Semantic-UI-React/commit/2fcccbbb717ff7eb09035b3606f6d99d7d476c85. Thank you 👍
