### ISSUE TITLE
Dropdown component name prop

### ISSUE THREAD

**Issue by t2ca** [Semantic-Org/Semantic-UI-React#3580]
## Feature Request
Would it be possible to add the name prop just as in the Checkbox component?

`name |   | {string} | The HTML input name.`

### Problem description
Netlify forms requires html input name to work.

**Comment by layershifter** [comment]
We pass down unhandled props by default, so `<Dropdown name='bar'>` will result to `<div name="bar" class="ui dropdown" />`.

I want to mention that neither `Dropdown` nor `Select` doesn't render `select`/`option` markup, so can archive traditional form behavior only with hidden `input`s.

**Comment by t2ca** [comment]
> I want to mention that neither `Dropdown` nor `Select` doesn't render `select`/`option` markup,

Thank you very much, this is the reason for the issue I was having with netlify.

> so can archive traditional form behavior only with hidden `input`s.

Would you mind showing me a code example on how to do this?

Thank you for your time.

**Comment by layershifter** [comment]
Here is CodeSandbox for you: https://codesandbox.io/s/5wwz8xnw0n 👍

**Comment by t2ca** [comment]
Thank you, I really appreciate it. This has helped me tremendously!
