### ISSUE TITLE
Label in corner does not respect zoom

### ISSUE THREAD

**Issue by michaeljohansen** [Semantic-Org/Semantic-UI-React#3585]
## Bug Report
Label in the corner of an input field does not respect zoom level. Only happens when zooming out (cmd/ctrl + minus). See CodeSandbox. Or this image:
![image](https://user-images.githubusercontent.com/582580/56771150-2d1b8d80-67b6-11e9-9a82-fc32f713ecb0.png)

### Steps
1) Make input field
2) Add corner label
3) Zoom out (cmd/ctrl + minus)

### Expected Result
Zoomed label.

### Actual Result
Not zoomed label.

### Version
0.84.0

### Testcase
Minimal bug demo: https://codesandbox.io/s/myl6k0o2oj

**Comment by lubber-de** [comment]
I unfortunately cannot reproduce  🤔 Which browser/OS/DPI setting are you using?
![inputzoom](https://user-images.githubusercontent.com/18379884/56789941-72b27780-6803-11e9-9131-3b73a4e599ee.gif)

**Comment by michaeljohansen** [comment]
Chrome 74.0.3729.108
macOS 10.14.4
4K screen scaled down to 2560 x 1440

Here's a small clip showing what happens here when I do what you did in the GIF above. Note that zoom level is visible in the top right corner of the clip:
https://www.dropbox.com/s/iu02bapgsrfu6lr/SUI-React-issue-3585.mov?dl=0

**Comment by layershifter** [comment]
As I see, it's a CSS issue and cannot be solved on our side as we don't handle any styles there.

Please report it to the main repo https://github.com/Semantic-Org/Semantic-UI or to https://github.com/fomantic/Fomantic-UI.
