### ISSUE TITLE
Checkbox: Toggle label does not get disabled

### ISSUE THREAD

**Issue by NewColours** [Semantic-Org/Semantic-UI-React#3587]
### Steps
Add disabled class to a checkbox toggle layout.
Add an ID to the Input and link the label with `for`
As expected, toggle is disabled.

### Expected Result
Expected is that Label is also disabled

### Actual Result
Reality is that Label slides the Toggle to ON position, while it remains dimmed 💣

### Version
Semantic UI - 2.4.1
jquery@1.11.3_2
meteor@1.1.6
semantic:ui-css@2.0.7
underscore@1.0.3

### Testcase
 don;t know how to get the sameple workign with react, so it's here in jsFiddle:
https://jsfiddle.net/52c0qek6/7/

**Comment by layershifter** [comment]
Sorry, as I see your code is not using Semantic UI React (https://react.semantic-ui.com/modules/checkbox), please move your issue to the main repository.
