### ISSUE TITLE
Rollup has issues with RefForward

### ISSUE THREAD

**Issue by kschrader02** [Semantic-Org/Semantic-UI-React#3592]
### Steps
When using rollup it has issues with RefForward and fills in the children and innerRef with undefined, undefined[(undefined, undefined)] respectively, which causes the exported bundle to not work. The only difference we could find when compared against Ref and RefFindNode was that RefForward imports PropTypes like `import * as PropTypes from 'prop-types'` whereas Ref and RefFindNode use `import PropTypes from 'prop-types'`. 

### Expected Result
To be able to export code that uses semantic using rollup with no issues

### Actual Result
Exports RefForward with undefined props which brakes everything. It doesn't make sense that it has no issue with Ref and RefFindNode. So we think it has something to do with the way PropTypes is imported. 

### Version
0.86.0

**Comment by layershifter** [comment]
Thanks for a catch, was fixed in #3594 👍

**Comment by kschrader02** [comment]
Awesome, thanks!
