### ISSUE TITLE
Strange behavior on Dropdown Link item

### ISSUE THREAD

**Issue by Jean-PhilippeD** [Semantic-Org/Semantic-UI-React#3593]
## Bug Report
Using a Dropdown with options as Link, I get the error in a specific case : 

`Uncaught Invariant Violation: Unable to find node on an unmounted component`.

__Context :__
I use react-router-dom
I've built a Header with Menu component.
The first Menu.Item is a header with a Link to /
The second item is a Component I made which handle a Dropdown Menu with few options, each options is also a Link:

```
const options = [
        {
            "key": "users",
            "text": "User management",
            "to": "/administration/users/",
            "icon": "users",
            "as": Link
        },
        {
            "key": "mail",
            "text": "Mail management",
            "to": "/administration/mail/",
            "icon": "mail outline",
            "as": Link
        }
    ]
```

### Steps
1.When I'm on route "/" and I refresh the browser and try to click on one item from the dropdown menu, it fails with the error I've pasted upside.
2. If I refresh the browser, being on the route "/administration/users", I get the expected page.
3. Then If I click on the Header Item, I go to / as expected.
4. Then I can now navigate finely to /administration/* without errors.
5. If I refresh again from everywhere, the Dropdown Link Items fails again.

I tried to create a Menu.Item with one of the route in the Dropdown options, and I have no issue with it.

Each time I refresh my browser, the Dropdown Links does not work until I navigate first to a Link outside dropdown menu. 

### Expected Result
I should not have any errors in routing with Dropdown Item.

### Actual Result
As far I do not refresh the page, routing works, but if I refresh the browser, I need to go on / before moving onto routes accessible from dropdown items.

### Version
react-router-dom: 5.0.0
react: 16.8.6
semantic-ui: 2.4.2,
semantic-ui-react: 0.86.0

### Testcase
If needed, I'll try to make a testcase

**Comment by layershifter** [comment]
We don't have time to debug your code, please make a **minimal** repro case.

**Comment by Jean-PhilippeD** [comment]
I've made a sandbox but I can not reproduce my issue.

But while I was trying things, I found that when I removed the lazy load of route, it seems to fix the bug.. 
My whole stuff is inside a Suspsence and I load route like this :

`const Users = lazy(() => import('./routes/administration/Users'));`

And if I just impor it : 

`import Users from './routes/administration/Users';`

I have no more error...

**Comment by layershifter** [comment]
It looks like the same thing as in: https://github.com/Semantic-Org/Semantic-UI-React/issues/3562#issuecomment-481759850. As I understand the fix was not released yet: https://github.com/facebook/react/pull/15312

**Comment by Jean-PhilippeD** [comment]
Ok I thought this fix was released.
