### ISSUE TITLE
<Table.Cell> expands too wide if a URL with `%` HTML escape codes

### ISSUE THREAD

**Issue by faddah** [Semantic-Org/Semantic-UI-React#3595]
--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

* Gitter Community Chat: https://gitter.im/Semantic-Org/Semantic-UI-React
* StackOverflow: https://stackoverflow.com/questions/tagged/semantic-ui-react using the tag `semantic-ui-react`
* Also have a look at our docs: http://react.semantic-ui.com

I am not certain if this is a bug in semantic-ui-react's `<Table.Cell>` or just not understanding how to use it correctly, so I'm filing this here. I'll also post something on the [StackOverflow for `semantic-ui-react`](https://stackoverflow.com/questions/55961545/semantic-ui-react-table-cell-issue-with-html-escape-codes).

In the Table we've created on-line for logging issues in our products, the "Notes" style fields (in our case, "Opportunity," "Desired Outcome," etc.  Our code for the Table Cells, after setting it up with `<Table.Header>`'s and such, is this —

```JavaScript
...
<Table.Cell>
  <a href={"workflow/" + item.id}>{item.submitted_by}</a>
</Table.Cell>
<Table.Cell>
  <a href={"workflow/" + item.id}>{item.opportunity}</a>
</Table.Cell>
<Table.Cell>
  <a href={"workflow/" + item.id}>
    {moment(item.create_date).format("MM/DD/YYYY")}
  </a>
</Table.Cell>
...
```

However, if someone puts notes in the field that has a URL that might contain HTML escape characters that start with the `%` sign, such as `%2F` for `/` and `%20` for a space, etc., it causes the field to suddenly widen and stretch to the left, which then shoves all the other columns/fields that need to be screen off screen, as in the below.

![<Table.Cell> with HTML escape characters example](https://i.imgur.com/0ZoDlZT.png)

If you just have regular notes that are text or have a URL with *no* HMTL escape characters in it, the cell formats at just the width size you wish and looks fine, nothing gets pushed to the left off-screen, as in the image below, which is how we want all our "Notes" cells formatted.

![<Table.Cell> without any HTML escape characters example](https://i.imgur.com/9A3Q5g5.png)

I've gone through all your docs on `<Table>` and `<Table.Cell>` and tried to find some prop or such that would fix this situation and have not been able to find anything that will shrink the cell back down to its desired size if the user put in a URL with HTML escape characters. Is there any way to fix this on my end? Please advise. Thank you in advance for your attention to this.

**Comment by layershifter** [comment]
It's how `table`s work and it's not related to SUIR as I see. Please check existing options for cells alignment:
https://react.semantic-ui.com/collections/table/#variations-fixed
https://react.semantic-ui.com/collections/table/#variations-fixed-line
https://react.semantic-ui.com/collections/table/#variations-unstackable

If it will not help, please add CodeSandbox example, it will allow to see the problem.

**Comment by faddah** [comment]
Hello @layershifter - thank you. I also found, later, that the CSS `overflow-wrap: break-word;` for the table cell works also. Thank you for your response.
