### ISSUE TITLE
Add "Data" property to avoid unhandled props

### ISSUE THREAD

**Issue by JeromeDeLeon** [Semantic-Org/Semantic-UI-React#3596]
## Feature Request
Adding "data" property in every component that has event listener (if possible) like Button

### Problem description
The problem is that if I want to pass for example, other data to the button, I need to do this:

`<Button onClick={(e, props) => handleClick(e, props, otherData)} content="Click" />`

It will still work but it creates a different callback each time that button renders.
Another one is to pass that data as props:

`<Button {...otherData} onClick={this.handleClick} content="Click" />`

That will work too, but a warning in console saying the Reacts does not recognize some props especially if we pass a camelCase variable to it.

### Proposed solution
If possible, add "data" props to the and from there, we insert any external data that will pass to the event callback when triggered as props and will not be filtered as unhandled props and print it to the DOM as it is.
like so:
`<Button data={otherData}  onClick={this.handleClick} content="Click" />`

**Comment by layershifter** [comment]
I had an offline discussion with Levi and our answer is simple: if you want to change behavior please consider to use component composition.

```jsx
class ComposedButton extends React.Component {
  handleClick = (e, props) => {
    this.props.onClick(e, props, this.props.data)
  }

  render() {
    const { data, ...rest } = this.props

    return <Button {...rest} onClick={this.handleClick} />
  }
}
```
