### ISSUE TITLE
Having an issue using the Dropdown on a page.

### ISSUE THREAD

**Issue by Connorb271** [Semantic-Org/Semantic-UI-React#3599]
I'm getting an error of "TypeError: Object(...) is not a function" on "ClientApp/node_modules/semantic-ui-react/dist/es/modules/Dropdown/Dropdown.js line 81" when I try to create a new instance of the Semantic UI React dropdown in my react application. I have even copied the code over, only changing variable names, from a project that a colleague worked on, and neither of us can seem to determine the source of the error.

I have tried following the guides on semantics website to no avail. I have copied the code with the includes from a working and existing project.

```
handleSelectClub = (e, data) => {
        const club = this.state.clubList[data.value];

        this.setState({
            clubId: club.id,
            name: club.name
        });
    }
render() {
        var clubs;
        let selectClub = null;
        if (this.state.clubList.length > 0)
        {
            clubs = this.state.clubList.map((opt, i) => ({
                key: opt.id,
                text: opt.name,
                value: i
            }));
            selectClub =
                <div>
                    <div className="form-group">
                        <Dropdown placeholder='Search Clubs' search selection options={clubs} onChange={this.handleSelectClub} />
                    </div>
                </div>
        }
        return (
            <form className="club-add-form" onSubmit={this.handleSubmit}>
                <h1>Add a New Club</h1>
                {selectClub}
            </form>
        );
    }
```

**Comment by layershifter** [comment]
Please fill issue template fully and provide repro on Codesandbox.
