### ISSUE TITLE
The documentation is lagging

### ISSUE THREAD

**Issue by mfaheemakhtar** [Semantic-Org/Semantic-UI-React#3605]
### Steps
A clear and concise description of steps to reproduce the problem.

Just visit the doc?

### Expected Result
The result that you expected.

> Should not lag.
> Should be smooth.

### Actual Result
The actual result that happened 💣

Lagging too much and very annoying. 

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Can you please provide more clarification? What do you mean?

Actually, recent updates made it more faster, I tested it even with throttling.

**Comment by mfaheemakhtar** [comment]
@layershifter, never mind.

Looks like my AdBlocker is interfering with the docs. The thread gets blocked (100% usage) and causes lag. The more I refresh the more lag, I've.

Anyway, I've whitelisted the docs and works well now.

![image](https://user-images.githubusercontent.com/17894982/57578310-1ad26c80-74a3-11e9-9d81-f4538fa89cb1.png)
