### ISSUE TITLE
Sticky Sidebar inside Sidebar.Pushable

### ISSUE THREAD

**Issue by panagiotappl** [Semantic-Org/Semantic-UI-React#3606]
## Bug Report
I am trying to create a pushable sidebar that sticks to the top of the page once the user scrolls past it. This is similar to the issue https://github.com/Semantic-Org/Semantic-UI-React/issues/2897 however the provided fix does not seem to work as expected. I have provided an example below, under 'testcase'.

### Steps
Have a Sticky element inside a Sidebar.Pushable element.

### Expected Result
The sidebar should be sticky and follow the page as it scrolls down.

### Actual Result
The sidebar is static and does not move at all with the https://github.com/Semantic-Org/Semantic-UI-React/issues/2897 fix. Without the fix, the sidebar is not sticky.

### Version
^0.84.0

### Testcase
https://codesandbox.io/s/9j8kr8lm9o

Please let me know if you need more information. Thanks!

**Comment by layershifter** [comment]
We are not going to fix this as it's related to components' CSS 😿 As proposed in #2897 we added a warning about this issue to docs.

**Comment by karmaniverous** [comment]
[This gist](https://gist.github.com/karmaniverous/1f6174ccf54e6f1ca346f6cf2e8f9ad5) illustrates what appears to be a complete solution to the problem. It's easy to implement and should adapt well to most implementations.
