### ISSUE TITLE
Add typings for typescript

### ISSUE THREAD

**Issue by hlehmann** [Semantic-Org/Semantic-UI-React#361]
Is there a way to add typings for typescript or is it already available ?

**Comment by levithomason** [comment]
We do not currently have typescript typings.  I would accept PRs adding typings.

I'm not a typescript expert, but I know @davezuko has been dabbling.  Any PRs should focus on components that have been updated to the v1 API first, see #269.  The others will have heavy API refactoring.

I'm not a typescript user, but it seems like using something like https://github.com/typings/typings should be an end goal.  Where the typings are separated and available as a standalone package.  We could start them here though and port them when done.

**Comment by dvdzkwsk** [comment]
I believe with TS2.0 typings can/should be provided directly through the npm package. Regardless, it would be great to make typings available, so I will give it a shot when time allows.

**Comment by levithomason** [comment]
Awesome, I'll leave this open for that PR then.

**Comment by dylankiss** [comment]
We also use TypeScript for our project, so it would be great to have this available. I'm now writing the type definitions myself for the parts that we use. I might make a PR when I have some more available (currently only Dropdown, Input, Form and Button).

**Comment by dvdzkwsk** [comment]
I'll also keep plugging away at pushing @levithomason to consider converting the project to TS ;). A standalone definition will, of course, come first, but it's arguably something worth discussing.

**Comment by dvdzkwsk** [comment]
@dylankiss if you'd like to post your fork or open a PR, that would give us a single place to pool our contributions toward a typedef. If not, I can create one when I get some free time.

**Comment by dylankiss** [comment]
@davezuko I'll try to look into it this weekend. Clean it up a little and create a separate branch on my fork. It would indeed be cool to convert the project to TypeScript, but I guess that's definitely not a priority for now ;)

**Comment by levithomason** [comment]
There is no push back from me regarding typings or converting the project to TS.  I'll merge PRs for any solid work in this area.  It is however at the complete bottom of my personal priorities:

### First
1. Update components to v1 APIs, see #269
2. Remove remaining jQuery, see #247
3. Port repo to Semantic-UI-React, see #243 

### Then
1. Complete missing doc site examples
2. Solve transitions, see #200 
3. Doc site updates/refactors: Introduction page, tabbed layout (props, examples), live editor(s) / playground
4. Final brush through components

### Finally (no order)
- Add missing components
- Typescript, enhancements and stuff?

**Comment by dvdzkwsk** [comment]
@hlehmann and @dylankiss, I just created a repo for Stardust typings. Not close to complete, but gives us a place to pool contributions should you guys be interested in helping. https://github.com/TechnologyAdvice/typings-stardust.

**Comment by levithomason** [comment]
Very glad to see this 😸

**Comment by levithomason** [comment]
Closing this issue in favor of using the new repo for continued issues/PRs.

**Comment by jrmyio** [comment]
I guess https://github.com/TechnologyAdvice/typings-stardust has to be updated ?

**Comment by levithomason** [comment]
We'll accept PRs on the typings repo, though, folks have been avoiding that while there is API churn.  Once the API churn is settled, we'll move the typings into this repo.

**Comment by levithomason** [comment]
Refer to #674 for the current work.
