### ISSUE TITLE
Cannot set autocomplete on search component

### ISSUE THREAD

**Issue by hisuwh** [Semantic-Org/Semantic-UI-React#3611]
## Bug Report

I want to be able to override the value of the `autocomplete` attribute on the search component.  I am unable to do so as this is hard coded here:

https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Search/Search.js#L529

Whilst `autocomplete="off"` seems like a sensible value this does not work in chrome as it is simply ignored (see here: https://stackoverflow.com/questions/12374442/chrome-ignores-autocomplete-off)

A solution that seems to work is setting `autocomplete="new-password"` which I have verified by setting this in chrome dev tools.

### Steps
Pass autocomplete to the Search component:

```ts
<Search
    autocomplete="new-password"
/>
```

### Expected Result
The rendered input respects the autocomplete value provided:
```html
<input type="text" tabindex="0" class="prompt" autocomplete="new-password" value>
```

### Actual Result
Prop is ignored:
```html
<input type="text" tabindex="0" class="prompt" autocomplete="off" value>
```

### Version
0.87.1

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/z79vd?fontsize=14

**Comment by layershifter** [comment]
This is partially covered in docs: https://react.semantic-ui.com/modules/search/#variations-input

Not obvious, but works:
```jsx
<Search
  input={{ // pass props to Input component
    input: { autoComplete: 'on' } // pass props to <input /> in Input component
  }}
/>
```

**Comment by hisuwh** [comment]
You're right its not obvious.  I tried this:
```jsx
<Search
    input={{ autoComplete: "on" }}
/>
```

Can confirm your suggestion works though. Perhaps the docs should be updated

**Comment by renemagiclog** [comment]
esto me funciono a mi, exito ¡¡¡¡¡¡!!!!! 
onFocus={(e) => {
                              e.target.setAttribute("autocomplete", "nope");
                            }}
