### ISSUE TITLE
Taiwan is not a Country

### ISSUE THREAD

**Issue by MBtea** [Semantic-Org/Semantic-UI-React#3612]
### Steps
A clear and concise description of steps to reproduce the problem.

### Expected Result
The result that you expected.

### Actual Result
The actual result that happened 💣

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
We use Semantic UI CSS to get values (https://semantic-ui.com/elements/flag.html), once it will be updated we will make same changes. There are similar discussion: https://github.com/Semantic-Org/Semantic-UI/issues/4849

You can create this issue in the main repo.
