### ISSUE TITLE
Map Marker icon shows something else

### ISSUE THREAD

**Issue by sohaibfarooqi** [Semantic-Org/Semantic-UI-React#3613]
### Steps
Map marker and Map marker alternate icon doesn't render properly. 
Infact they renders to `map` icon. Please see the attached codepen for demo.

### Expected Result
It should render `map marker` icon.

### Actual Result
It rendered `map` icon.

### Version
0.87.1

### Testcase
[Codepen Demo](https://codepen.io/sohaibfarooqi/pen/zQdLLq)

**Comment by layershifter** [comment]
Your Codepen uses outdated version of SUI CSS, same code with SUI 2.3: https://codepen.io/anon/pen/BewyEN

> Themes from Semantic UI >=2.3.x require Semantic UI React >=0.81.0.
https://react.semantic-ui.com/usage
