### ISSUE TITLE
Popup: positioning glitch when using negative vertical offset

### ISSUE THREAD

**Issue by rijk** [Semantic-Org/Semantic-UI-React#3615]
## Bug Report
Implementing the new Popper `offset` parameter (#3532), something weird happens:

(first is without offset, then with offset):

![tooltip offset issue short](https://user-images.githubusercontent.com/159500/58249143-5b14d300-7d5e-11e9-957b-f40fc2920459.gif)

### Steps
A Popup configured with

```
position="bottom center"
offset="0, -4"
```

(near the top of the page, that could have something to do with it).

### Expected Result
Tooltip appears shifted up, but still in the same orientation (bottom center).

### Actual Result
Orientation changes to top, making it very glitchy.

### Version
0.87.1

### Testcase
https://codesandbox.io/s/semantic-ui-react-2m6rb

As a workaround I tried to use the `positionFixed` parameter, but it doesn't appear to be passed to Popper.

**Comment by rijk** [comment]
Might be related to [this](https://popper.js.org/popper-documentation.html#modifiers..offset):

> NB: If you desire to apply offsets to your poppers in a way that may make them overlap with their reference element, unfortunately, you will have to disable the flip modifier. You can read more on this at this issue.

**Comment by layershifter** [comment]
Good catch, we should expose `modifiers` from `Popper.JS` 👍

**Comment by TomDemulierChevret** [comment]
Any update on this ?

The 0.87.0 broke a lot of our popup that used this mecanism to render the content closer to the trigger.

**Comment by layershifter** [comment]
@TomDemulierChevret @rijk please take a look on #3654. Craziness is stopped with `pinned: true`:

![popup-pinned-fix](https://user-images.githubusercontent.com/14183168/59213866-24401900-8bb6-11e9-8044-8f1dc5d12faf.gif)

I also exposed Popper's `modifiers` as `popperModifiers`.

**Comment by TomDemulierChevret** [comment]
Perfect.

Do you know when the next release including this fix will be available ?

**Comment by layershifter** [comment]
I am plan to have it on this week.
