### ISSUE TITLE
Test case code sandbox not up to date

### ISSUE THREAD

**Issue by rijk** [Semantic-Org/Semantic-UI-React#3616]
Small FYI: the provided sandbox @ https://codesandbox.io/s/2l3n74j9y doesn't point to the latest version of semantic-ui-react. This got me when I tried to demonstrate an issue with Popper.js, it might cause confusion in the future as well (people reporting issues that have already been fixed for instance).

**Comment by layershifter** [comment]
@rijk thanks for pointing to this, now it uses `latest` so it will use the latest SUIR 🐱 

https://codesandbox.io/s/2l3n74j9y
