### ISSUE TITLE
Docs: login example from official website is not laid out as expected

### ISSUE THREAD

**Issue by zhuxh529** [Semantic-Org/Semantic-UI-React#3620]
## Bug Report
Looks like the login example from official website is not laid out as expected(Its not vertically centered on my Chrome, Safari and firefox)

### Steps
https://react.semantic-ui.com/layouts/login

### Expected Result
vertically center

### Actual Result
put top 

### Version
on website

<img width="1432" alt="Screen Shot 2019-05-24 at 11 42 45 PM" src="https://user-images.githubusercontent.com/5363160/58340325-2730cf00-7e7e-11e9-9a06-7ef85cb70596.png">

**Comment by ashvini-maurya** [comment]
I have created a PR for this  [issue](https://github.com/Semantic-Org/Semantic-UI-React/pull/3623)

**Comment by zhuxh529** [comment]
Thank you!
