### ISSUE TITLE
Dropdown: add `closeOnEscape` prop

### ISSUE THREAD

**Issue by gencer** [Semantic-Org/Semantic-UI-React#3622]
### Steps
1. Add `closeOnBlur={false}` to dropdown
2. press `ESC`.

### Expected Result
Clicking outside and pressing `ESC` should not close the dropdown. I want my dropdown stay open. The reason is, I put some elements in dropdown and it has its own keybindings. `ESC` is one of them and when I press `ESC` on that element, dropdown closes completely.

### Actual Result
Click works. `ESC` closes dropdown no matter of what.

### Version
0.87.1

### Testcase
See "Close on blur stays open" example in SemanticUI-React website.

### Related

See here: https://github.com/Semantic-Org/Semantic-UI-React/issues/1995

**Comment by layershifter** [comment]
We have `closeOnEscape` in `Portal`, `Popup` & `Modal`, we should have it also there 🤔

**Comment by gencer** [comment]
```
        <Dropdown
          closeOnBlur={false}
          closeOnEscape={false}
          selectOnBlur={false}
          closeOnChange={false}
          trigger={trigger}
          icon={null}>
          <Dropdown.Menu className={'left'}>
              ...
          </Dropdown.Menu>
        </Dropdown>
```

Which has `closeOnEscape` and `closeOnBlur` and still closes.

**Comment by gencer** [comment]
Ah, yes, we should have that for Dropdown too.

BTW, Is there any workaround for this until this prop added to Dropdown? Any suggestions?

/cc @layershifter
