### ISSUE TITLE
React-semantic-ui not working on codepen

### ISSUE THREAD

**Issue by mohamudolow** [Semantic-Org/Semantic-UI-React#3624]
return (
    <Segment>
          <Grid columns={2}>
              <Grid.Column>
                Individual Total Without Tip:
              </Grid.Column>
            <Grid.Column>
              {individualTotalWithOutTip}
            </Grid.Column>
          </Grid>
      
      <Grid columns={2}>
              <Grid.Column>
                Individual Total With Tip:
            </Grid.Column>
            <Grid.Column>
              {individualTotalWithTip}
            </Grid.Column>
          </Grid>
      
      <Grid columns={2}>
              <Grid.Column>
                Total Tip Amount:
            </Grid.Column>
            <Grid.Column>
              {Math.floor((individualTotalWithTip-individualTotalWithOutTip) * props.numOfPeople * 100)/100}
            </Grid.Column>
          </Grid>
      
      <Grid columns={2}>
              <Grid.Column>
                Tip Per Person:
            </Grid.Column>
            <Grid.Column>
              {Math.floor((individualTotalWithTip-individualTotalWithOutTip) * 100)/100}
            </Grid.Column>
          </Grid>
      
        </Segment>
      );

I am beginner developer trying to use react-semantic-ui on codepen and it is not working. I don't really what I am doing wrong but I have the cdn linked. Please help me resolve this. I am stuck. Thanks.

here is the  codepen project: https://codepen.io/mohamudolow/pen/oRLewe

**Comment by layershifter** [comment]
Consider to use CodeSandbox, it supports required syntax.

Codepen has no proper support of `import`/`require`, used destruction: https://codepen.io/anon/pen/PveXxm

```diff
-import { Button, Divider, Form, Grid, Segment } from 'semantic-ui-react';
+const { Button, Divider, Form, Grid, Segment } = semanticUIReact
```
