### ISSUE TITLE
Buttons and ButtonGroups: floated='right' makes buttons to take no veritcal space

### ISSUE THREAD

**Issue by thedeadferryman** [Semantic-Org/Semantic-UI-React#3627]
Buttons and ButtonGroups are working incorrectly with `floated={'right'}` prop ([screenshot](https://www.dropbox.com/s/lfyb3ax12f72c92/buttons-broken.png?raw=1)), source code:
```javascript
<Segment>
	<Button floated={'right'}>
		Sample
	</Button>
</Segment>
```

**Comment by layershifter** [comment]
You need to use `<Divider clearing />` in this case: 

```jsx
  <Segment>
    <Button floated={'right'}>Sample</Button>
    <Divider clearing hidden />
  </Segment>
```

https://react.semantic-ui.com/elements/divider/#variations-clearing
https://codesandbox.io/s/ybgbx?module=/example.js

**Comment by thedeadferryman** [comment]
Not a code issue, I agree, but I think that it needs to be noticed in docs somewhere arount floating buttons, 'cause my solution was to add not floated hidden button near floated one :) Anyway, thanks for anwer.
