### ISSUE TITLE
can't use blob url in Image ? someone can help me?

### ISSUE THREAD

**Issue by bluesealjs** [Semantic-Org/Semantic-UI-React#3628]
## Bug Report
I just can't use blob url as src in Image. < Image src={this.state.blobUrl} >
### Steps
A clear and concise description of steps to reproduce the problem.

### Expected Result
The result that you expected.
https://react.semantic-ui.com/elements/image/#states-hidden

### Actual Result
The actual result that happened 💣
<Image src={this.state.blobUrl} />

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Please use StackOverflow for usage questions, `Image` component behaves like a usual `img` in React.

It seems that you are looking for something like this: 
https://stackoverflow.com/a/43966226/6488546
