### ISSUE TITLE
Double minus in css (insede calc)

### ISSUE THREAD

**Issue by taime** [Semantic-Org/Semantic-UI-React#3629]
## Bug Report

There are double minus in css file (**--1px**)

### Steps
Download https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.css

### Expected Result
```
 .ui.attached.steps {
   width: calc(100% + (1px * 2)) !important;
   margin: 0em -1px 0;
   max-width: calc(100% + (1px * 2));
   border-radius: 0.28571429rem 0.28571429rem 0em 0em;
 }
```

### Actual Result
```
 .ui.attached.steps {
   width: calc(100% + 2px) !important;
   margin: 0em -1px 0;
   max-width: calc(100% + 2px);
   border-radius: 0.28571429rem 0.28571429rem 0em 0em;
 }
```

### Version
2.4.2

There are also some places with double minus like here (**--1px**)
I really think this is mistake. It it's not, please tell me what does it mean ?

**Comment by layershifter** [comment]
We don't handle CSS there, it's a repo for React bindings. Feel free to open an issue in the main repo: https://github.com/Semantic-Org/Semantic-UI
