### ISSUE TITLE
Input and TextArea ref change was a major breaking change

### ISSUE THREAD

**Issue by jscheel** [Semantic-Org/Semantic-UI-React#3631]
https://github.com/Semantic-Org/Semantic-UI-React/pull/3453 is a breaking change. If you relied on callback refs before, any ref you have is now broken.

**Comment by layershifter** [comment]
Can you please clarify?

`TextArea` component uses `Ref` component to get refs, so it doesn't matter which element will be passed. Single case that I see where it can be broken `<Input input={{ as: CustomComponent }} />`. Am I right?

**Comment by jscheel** [comment]
Here's a small, contained example:

```
export function disableLastPass(input) {
  const ref = input && input.inputRef && input.inputRef.current
  if (ref) {
    ref.setAttribute('data-lpignore', 'true')
  }
}
```

I may just be using this wrong, but it inputRef has changed for me.

**Comment by layershifter** [comment]
Please provide whole use case (but it keep it minimal), it seems that I see the wrong usage... Why you need to use refs there at all?

```js
<Input
  ref={input => { input.inputRef /* don't do this, it a private API 💣  */ }} 
/>
```

**Comment by layershifter** [comment]
Closing for housekeeping, will reopen on a reply.

**Comment by jscheel** [comment]
Sorry, been all over the place. I think it's because you need to get to the actual input element, not a ref to the component.

**Comment by layershifter** [comment]
Can you please provide the usecase? As I see `data-lpignore` can be passed via props:

```jsx
<Input input={{ 'data-lpignore': someCondition ? true : undefined }}
```
