### ISSUE TITLE
Website: layouts page layout broken

### ISSUE THREAD

**Issue by kristapsstrals** [Semantic-Org/Semantic-UI-React#3633]
## Bug Report

When I visit [https://react.semantic-ui.com/](https://react.semantic-ui.com/) and navigate to [https://react.semantic-ui.com/layouts/](https://react.semantic-ui.com/layouts/) using the link in the sidemenu, everything is fine.

However, if I visit [https://react.semantic-ui.com/layouts/](https://react.semantic-ui.com/layouts/) directly, the layout of the page is broken.

### Steps

Visit [https://react.semantic-ui.com/layouts/](https://react.semantic-ui.com/layouts/) directly in the browser. Tested with Opera and Edge (don't have Chrome installed atm, but Opera is chromium based and should have a similar rendering experience)

### Expected Result
![image](https://user-images.githubusercontent.com/26419290/58684605-75176c80-8381-11e9-80ea-64350c84caac.png)

### Actual Result
![image](https://user-images.githubusercontent.com/26419290/58684623-7fd20180-8381-11e9-8177-e9c38f7a42c5.png)

### Version
N.A.

### Testcase
N.A.

**Comment by ubaidisaev** [comment]
Working well when running locally. Still working on it.

**Comment by mcmxcdev** [comment]
I can confirm that the page layout is also broken on Chrome & Firefox on Ubuntu 19.04 in production, but when running it locally it works.

**Comment by layershifter** [comment]
In production we are using static generation, can be reproduced locally with `build:docs:staging`.

**Comment by layershifter** [comment]
Was able to debug it, will be fixed in #3652.
