### ISSUE TITLE
TextArea throws errors in the console when adding line breaks

### ISSUE THREAD

**Issue by Fabianopb** [Semantic-Org/Semantic-UI-React#3634]
## Bug Report
`TextArea` throws unexpected errors when adding line breaks.

### Steps
Type any text in a `TextArea` and hit return/enter to add line breaks.

### Expected Result
Line breaks are added without exceptions.

### Actual Result
Line breaks are added, but the console throws errors:
![image](https://user-images.githubusercontent.com/15076656/58690386-16a6ba00-8392-11e9-8452-13668595789f.png)

### Version
0.87.1

### Testcase
Simply go to https://react.semantic-ui.com/addons/text-area/ type anything and try to add line breaks.

**Comment by layershifter** [comment]
`onloadwff.js` is a third party extension...

**Comment by Fabianopb** [comment]
Yep, taking a further look that's caused due to LastPass plugin being active. If you don't think that's something we should keep track here then I'm ok to close the issue!
