### ISSUE TITLE
reactjs + semantic ui search + array graphql

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#3636]
I want to search the items in the searchResults array with reactjs. I'm using graphql in the background.
**How do I search for searchResults?**
**searchResults: [  ]**

`
import React,  { Component } from 'react'
import { Card, Image, Button, Icon, Grid, Search, Label } from "semantic-ui-react";

import { Query } from "react-apollo";

import { GET_USER_CUSTOMERS_ALL } from "../queries/user.mutations";
import { Link } from "react-router-dom";

class CustomerList  extends Component  {
  constructor(props) {
    super(props);

    this.state = {
      searchResults: [  ],

      value: "",
      isLoading: false,
    };

    //this.handleSearchChange = this.handleSearchChange.bind(this);
    this.handleResultSelect = this.handleResultSelect.bind(this);
  }

  handleSearchChange = (e, { value }) => {
    this.setState({ isLoading: true, value });
    this.setState({ isLoading: false, value: value });
  };
  //handleResultSelect = (e, { result }) => this.setState({ value: result.c_name });
  resultRenderer = ({ _id , c_name}) => <Label key={_id} content={c_name} />;

  render() {
    const { isLoading, value, searchResults } = this.state;
    return(
        <div style={{paddingTop:60}}>

          <ul>
            <Search
              loading={isLoading}
              value={value}
              results={searchResults}
              //onSearchChange={this.handleSearchChange.bind(this)}
              onSearchChange={ this.handleSearchChange.bind(this) }
              //onResultSelect={ this.handleResultSelect }
             // resultRenderer={this.resultRenderer}
            />
          </ul>

          <ul>
            <Grid stackable columns={6}>
              <Query
                query={GET_USER_CUSTOMERS_ALL}
                variables={{
                  createdBy: this.props.session.activeUser._id
                }}>
                {({ loading, data } ) => {

                  if (loading) return "Loading";

                  const { getUserCustomersAll } = data;

                  this.state.searchResults = data;
                  //console.log(searchResults);

                  return getUserCustomersAll.map(customer =>
                    <Grid.Column key={customer._id}>
                      <Card>
                        <Card.Content>
                          <Image floated='right' size='mini' src='/images/avatar/large/steve.jpg' />
                          <Card.Header>{ customer.c_name } { customer.c_surname }</Card.Header>
                          <Card.Meta>Tc: { customer.c_tc }</Card.Meta>
                          <Card.Meta>Doğum Tarihi: { customer.c_birth }</Card.Meta>
                          <Card.Meta>Gsm: { customer.c_phone }</Card.Meta>
                          <Card.Meta>Gsm 2: { customer.c_phone2 }</Card.Meta>
                          <Card.Description>Açıklama: { customer.c_desc } </Card.Description>
                        </Card.Content>
                        <Card.Content extra>
                          <div className='ui two buttons'>
                            <Button basic color='green'>
                              <Link to={`/customerinfo/${customer._id}`}> <h4> {customer.c_name} kartını aç  <Icon name='arrow circle right' />  </h4> </Link>
                            </Button>
                          </div>
                        </Card.Content>
                      </Card>
                    </Grid.Column>
                  )
                }}
              </Query>
            </Grid>
          </ul>

        </div>
        );
    }
}
export default (CustomerList)
`

**Comment by layershifter** [comment]
Please use StackOverflow for usage questions.
