### ISSUE TITLE
Popup: expose reference for react-popper instance

### ISSUE THREAD

**Issue by rokoroku** [Semantic-Org/Semantic-UI-React#3639]
### Problem description
I want to recalculate `Popup` position when the size of content is changing.
However, it seems like there's no easy way to achieve this without having popper instance.

https://github.com/FezVrasta/react-popper/issues/274

### Proposed solution
- simple way: Just add reference prop for `<Popper />` element to the `PopupProps`
- complex way: Add feature to recalculate popup position to the `Popup` element.

**Comment by layershifter** [comment]
I don't want to expose it with renderProps because it will be not aligned with existing API. Rather it can be `positionDependencies` that is an array:
```jsx
const myDataFromServer = [...]

return <Popup positionDependencies=[myDataFromServer.length] />
// or
return <Popup positionDependencies=[myDataFromServer.queryId, isFetched] />
```

It's aligned with `dependencies` idea in React hooks. What do you think? 🤔

**Comment by rokoroku** [comment]
Yay, hook-like dependency prop! What a great idea!

**Comment by layershifter** [comment]
@rokoroku can you take a look on #3657 and provide some feedback? 🐱
