### ISSUE TITLE
Transition portal child unmounting on hide even when unmountOnHide prop is set false

### ISSUE THREAD

**Issue by krajasekhar** [Semantic-Org/Semantic-UI-React#3640]
## Bug Report
Transition Portal is unmounting when it is hidden. Tried passing the prop unmountOnHide for transition object which is taking all the transition props but couldn't make it work.

### Steps
Transition portal with the child as a stateful component. Can pass prop as `transition={{unmountOnHide: false}}`
Please check the given test case.

### Expected Result
Child component not to be unmount when the portal is closed.

### Actual Result
It is unmounting.

### Version
0.87.1

### Testcase
(https://codesandbox.io/s/portalunmountissue-jghtb)

**Comment by layershifter** [comment]
@krajasekhar this was done intentionally by design as `Transition` is wrapped with `Portal` which always unmount its children. For your usage it makes sense to combine `Portal` & `Transition` instead:

```tsx
<Portal onClose={() => setVisible(false)} open>
  <Transition visible={visible}>
    <Child />
  </Transition>
</Portal>
```

https://codesandbox.io/s/portal-unmount-issue-forked-sb2ot
