### ISSUE TITLE
Docs: performance problems in docs for Select

### ISSUE THREAD

**Issue by sholladay** [Semantic-Org/Semantic-UI-React#3643]
### Steps

1. Visit the docs for `<Select>` at https://react.semantic-ui.com/addons/select/
2. Click the "Try it" button to open the code editor
3. Type some characters into the code editor

### Expected Result

Smooth performance with a reasonable frame rate.

### Actual Result

The code editor is very sluggish. It takes about two seconds for the editor to respond to my keyboard input.

To solve it, I tried using the code editor to limit the number of countries used in the example and it seemed to help. I added `.slice(0, 10)` to `faker.definitions.address.country`. That makes the example a bit strange, so it's not an ideal solution, but hopefully it provides a hint for where the problem is. I am not sure why it helps in a noticeable way, because even without slicing, there are only 244 countries in that list. So there must be some kind of very expensive operation happening on the whole list.

### Version

0.87.1

### Testcase

None

**Comment by layershifter** [comment]
Thanks for the feedback, it's much appreciated 👍 
Will be fixed by #3651.
