### ISSUE TITLE
Opening modal from dropdown item behaves strangely

### ISSUE THREAD

**Issue by ThiefMaster** [Semantic-Org/Semantic-UI-React#3644]
### Steps
- Open a modal from a dropdown menu item
- Click inside the modal

### Expected Result
The dropdown opens

### Actual Result
The dropdown stays closed

### Version
0.87.1

### Testcase
https://codesandbox.io/s/semantic-ui-react-jn8c2

---

While it only looks like a minor annoyance, it's problematic when there's e.g. a form inside the modal, because now pressing enter in a form field will also trigger the modal, and only the second time you press it ends up being handled by the form.

**Comment by layershifter** [comment]
Duplicate #3174?

**Comment by ThiefMaster** [comment]
Seems at least related. `onClick={e => e.stopPropagation()}` on my `<Modal>` avoids the issue but it's incredibly ugly (now suddenly my actual component that creates the Modal needs to know that it's going to be opened from within a dropdown!)

**Comment by layershifter** [comment]
Agree with you, closing as duplicated of #3174.
As issue is the same.
