### ISSUE TITLE
Doc: "Get Started" guide on using custom themes is outdated and misleading

### ISSUE THREAD

**Issue by zmwangx** [Semantic-Org/Semantic-UI-React#3645]
On https://react.semantic-ui.com/usage, under the "Custom Theme" tab of the "Theme" section, the recommendation is

> The Semantic UI package installs a Gulp build tool that will walk you through creating a custom theme within your project. Install this as a dev dependency:
>
>     $ yarn add semantic-ui --dev
> 
> After building a theme with Gulp, include the minified CSS file in your index.js file:
>
>     import '../semantic/dist/semantic.min.css
>
> Detailed documentation on Semantic UI theming is provided here and in our Theming guide.

Unfortunately, `semantic-ui` is stuck on Gulp 3 and incompatible with Node 12 (https://github.com/Semantic-Org/Semantic-UI/issues/6818). This sent me on a wild goose chase that ended nowhere; then I checked the Theming guide which is based on `semantic-ui-less` and works without a problem.

So, the `semantic-ui` mention is misleading and kinda does this project a disservice. Would you please update that section? Thanks.

**Comment by layershifter** [comment]
Thank you for feedback, I will update this section in #3652.
