### ISSUE TITLE
Dashboard for admin panel

### ISSUE THREAD

**Issue by zpi12lmm** [Semantic-Org/Semantic-UI-React#3646]
### Problem description
When creating a control panel for the admin, it is impossible to organize in harmony of all components.

### Proposed solution
I propose to do the following, to create a "Dashboard" component that will sensibly and responsively insert all the other components that will be needed for the administration panel.
I can prepare a layout for what the Dashboard should be if you make this component.

**Comment by layershifter** [comment]
We are not going to introduce this as a part of framework, it will be impossible to satisfy all needs. May be as layout example or a prototype, but it should extremely good implementation.
