### ISSUE TITLE
Why can't you copy the code?

### ISSUE THREAD

**Issue by bugtype** [Semantic-Org/Semantic-UI-React#3650]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/24269591/59141535-a92a0780-89e9-11e9-89f6-aeca1b486fa4.png">

it is empty when pasted. codes in other examples are not copied either.
However, it works well if you copy it elsewhere.

os: mac mojave 10.14.3
browser: Chrome Version 74.0.3729.169 (Official Build) (64-bit)

oh.. safari is works!! but i want to use chrome...

**Comment by layershifter** [comment]
Sounds quite strange, will ask folks with MacOS try it tomorrow...

**Comment by bugtype** [comment]
Well... it's working right now. I think it is my computer problem. I am sorry.
