### ISSUE TITLE
Icon size in Dropdown

### ISSUE THREAD

**Issue by DaveSweeton** [Semantic-Org/Semantic-UI-React#3653]
I'm trying to create a dropdown with a large icon. My markup works, but is generating a warning.

### Steps
<Dropdown floating icon="user circle large">
	<Dropdown.Menu>
		<Dropdown.Item text='Example' />
	</Dropdown.Menu>
</Dropdown>

### Expected Result
Renders a large icon with no warnings.

### Actual Result
I get a large icon, but also a console warning:

Warning: Failed prop type: Invalid prop `name` of value `user circle large` supplied to `Icon`.

Instead of `user circle large`, did you mean:
  - user circle
  - pause circle
  - circle

    in Icon (created by Dropdown)
...

### Version
0.86.0

### Testcase
https://hgf6v.codesandbox.io/

**Comment by layershifter** [comment]
You should use `size` prop, see `Examples` on https://react.semantic-ui.com/elements/icon/

```jsx
icon={{ name: 'user', size: 'large' }}
```

**Comment by DaveSweeton** [comment]
Perfect, thank you! My documentation search failed to find that option.
