### ISSUE TITLE
Semantic UI React nested Dropdown.Menu scrolling does not work

### ISSUE THREAD

**Issue by joeyUOFA** [Semantic-Org/Semantic-UI-React#3655]
https://stackoverflow.com/questions/56533179/semantic-ui-react-nested-dropdown-menu-scrolling-does-not-work

**Comment by layershifter** [comment]
Children API is not supported properly in `Dropdown` and we are going to remove it at all for `Dropdown`. We also not going to invest time to fix it, however we don't have much progress with #1724.

I will accept PR with a fix if it's an issue with SUIR.

Broken circle 😭
