### ISSUE TITLE
Dropdowns close when embedded Input becomes the focus

### ISSUE THREAD

**Issue by AdamBCo** [Semantic-Org/Semantic-UI-React#3661]
## Steps

Dropdowns are closing when an embedded Input becomes the focus. This issue is visible on the website in the following example code:

https://codesandbox.io/s/mj215rmnvx?module=/example.js

## Expected Result
You should be able to enter text into the Input without the Dropdown closing.

Version
0.87.1

**Comment by layershifter** [comment]
We are going to drop support of Children API in `Dropdown` because we can't properly handle such situations.

#### Workaround

```jsx
onClick={e => e.stopPropagation()} // on Input
```

https://codesandbox.io/s/semantic-ui-react-example-fr6u3
