### ISSUE TITLE
Icon size not changing

### ISSUE THREAD

**Issue by trevpry** [Semantic-Org/Semantic-UI-React#3663]
I am using the <Icon> element successfully, with all props, except I am unable to change the size. 
`<Icon color='teal' name='home' size='massive'/>`
shows the same size as 
`<Icon color='teal' name='home' size='tiny'/>`

If I change any of the other props, such as color or flipped, it works with no problem. Please help me figure out how to get the size to change.

**Comment by layershifter** [comment]
Please provide a repro, it works on CodeSandbox:
https://codesandbox.io/s/semantic-ui-react-example-01878

**Comment by layershifter** [comment]
Closing for housekeeping, ping me with repro if it is still relevant.
