### ISSUE TITLE
Editable tables

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI-React#3664]
## Feature Request
I'd like to have Editable tables in SUIR. Is that on the roadmap? Or since vanilla SUI doesn't have that feature, SUIR will not either?

**Comment by layershifter** [comment]
Nope, there are no plans for it 😿 It's not supported by SUI core and even in Fomantic, so I can't be done on our side. I tried to use `react-table` multiple times and was satisfied with results:

https://github.com/tannerlinsley/react-table/tree/v6#codesandbox-examples

But it required a custom styling 💣

**Comment by avalanche1** [comment]
Ah, sad.
I know of `react-table`, but was hoping for out of the box solution with SUI styles..
