### ISSUE TITLE
Popup is not positioned properly inside Modal when Modal's size changes.

### ISSUE THREAD

**Issue by ivanjiang5628** [Semantic-Org/Semantic-UI-React#3665]
### Steps

I have a popup triggered by an input box within the modal.

When the Modal is rendered for the first time, the Popup is well-positioned.

But when I open an accordion (which is also in the Modal)

the popup will not follow the updated position.

![image](https://user-images.githubusercontent.com/24568041/59535814-c017a080-8ea6-11e9-8933-d8deebafe9a6.png)

![image](https://user-images.githubusercontent.com/24568041/59535819-c6a61800-8ea6-11e9-8f84-d8d42e60c116.png)

### Expected Result
The pop-up window should follow the input box to its new position

### Actual Result
The popup window does not follow the updated location.

### Version
latest

### Testcase

codesandbox link:

https://codesandbox.io/s/semantic-ui-react-example-4d3ns

**Comment by layershifter** [comment]
It's done for performance reasons in PopperJS, in recent release there is an access to `scheduleUpdate()` via `popperDependencies`: 
https://react.semantic-ui.com/modules/popup/#usage-popper-dependencies

I have updated your CodeSandbox: https://codesandbox.io/s/semantic-ui-react-example-r1pmb
```diff
+popperDependencies={[activeIndex]}
```

**Comment by ivanjiang5628** [comment]
@layershifter Thanks for the quick reply ...... I should update to latest version to use this prop. Thanks
