### ISSUE TITLE
Remove border from tag

### ISSUE THREAD

**Issue by roy1210** [Semantic-Org/Semantic-UI-React#3666]
Hi,
This is Roy.
Sorry to bother you, I'd like to know how to remove a border from [Tab](https://react.semantic-ui.com/modules/tab/#types-basic)

I tried to make a class and did " border: none; " in CSS but not working.
Please help to advise how to solve, Thank you!
<img width="1394" alt="190615 Screenshot" src="https://user-images.githubusercontent.com/42575132/59547966-481aaa80-8f7a-11e9-9138-d37667bfa09b.png">

<img width="1382" alt="190615 (2) Screenshot" src="https://user-images.githubusercontent.com/42575132/59548061-c6c41780-8f7b-11e9-8ba8-43f6405dee9d.png">

CodeSandBox: 
https://codesandbox.io/s/my-portfolio-mjewd

**Comment by layershifter** [comment]
Your CSS selector can be not enough to override other rules, try `!important`. However, in this case it will be more correct to use `<Tab.Pane as='div'>` that will render `div` instead of `Segment`.

Sorry, we don't have time to debug your code, please use StackOveflow for usage questions.

**Comment by roy1210** [comment]
It's fixed after add !important. Thank you.
