### ISSUE TITLE
The Form Input's label with "inline" prop will not follow the Input error color

### ISSUE THREAD

**Issue by ivanjiang5628** [Semantic-Org/Semantic-UI-React#3671]
### Steps
When the "Error" prop is set to true, the label of the "Inline" form input will not change to the "Error" color, but to the "Fluid" color.

### Expected Result
Should change to the "error" color when "error" prop is set to true.

### Actual Result
Results of what actually happened 💣
![image](https://user-images.githubusercontent.com/24568041/59642853-813e5080-911b-11e9-8ca9-ce0d2483bfc9.png)

### Version
0.87.2

### Testcase

https://codesandbox.io/s/semantic-ui-react-example-m8ywr

**Comment by layershifter** [comment]
![image](https://user-images.githubusercontent.com/14183168/59717760-f5aae980-9218-11e9-9223-dbac7c780945.png)

It's sad, but it's a CSS issue which can't be fixed on our side 😭  I created a matching issue in FUI (it can be fixed soon 😀 ): https://github.com/fomantic/Fomantic-UI/issues/818 

At least, it can be resolved with this workaround:
```css
.ui.form .field.inline.error > label { color: #9f3a38; }
```
```jsx
<style>{`.ui.form .field.inline.error > label { color: #9f3a38; }`}</style>
```

https://codesandbox.io/s/semantic-ui-react-example-xdve4

**Comment by ivanjiang5628** [comment]
@layershifter Thanks for the quick reply.
