### ISSUE TITLE
create-app-react (typo)

### ISSUE THREAD

**Issue by oscarwong67** [Semantic-Org/Semantic-UI-React#3673]
## Bug Report
"Get Started" page says "create-app-react" instead of "create-react-app"

### Steps
A clear and concise description of steps to reproduce the problem.
Visit https://react.semantic-ui.com/usage, and scroll down to "Bundling" and select "Create React App".

### Expected Result
The result that you expected.
"Semantic UI React is fully compatible with create-react-app and works out the box. Setup of custom theme is covered in Theming guide."

### Actual Result
The actual result that happened 💣
Semantic UI React is fully compatible with create-app-react and works out the box. Setup of custom theme is covered in Theming guide.

### Version
N/A

### Testcase
N/A

**Comment by layershifter** [comment]
Thank you for reporting, fixed in https://github.com/Semantic-Org/Semantic-UI-React/commit/6375f898a3c47687cc32f1d6ad4f7e02a0678147 and will be published with next release 👍
