### ISSUE TITLE
support for tree-shaking and reducing bundle size

### ISSUE THREAD

**Issue by Avi98** [Semantic-Org/Semantic-UI-React#3675]
### Problem description
Adding support for tree shaking in create-react-app without adding external packages like react-rewired. IMHO this optimization technique should be supported out of the box like other UI libraries are doing for example [Material UI](https://material-ui.com/guides/minimizing-bundle-size/#how-to-reduce-the-bundle-size)

### Proposed solution
Path imports should be used to avoid importing the unused modules.
For example: 

```javascript
import { Grid } from 'semantic-ui-react'
```
Above will import the whole module.

```javascript
import  Grid  from 'semantic-ui-react/grid'
```
Only grid will be imported form module when built is create.

**Comment by layershifter** [comment]
Support of tree-shaking is done on the bundler side, Create React App uses Webpack and it supported there.

> Above will import the whole module.

If you will try to analyze your bundle you will see that you're wrong.
https://facebook.github.io/create-react-app/docs/analyzing-the-bundle-size

![image](https://user-images.githubusercontent.com/14183168/59716766-ec208200-9216-11e9-9e50-9389de1f0eb2.png)

And even covered in our docs:

![image](https://user-images.githubusercontent.com/14183168/59716894-1e31e400-9217-11e9-9df9-1a54a9e5026d.png)

So you don't need to spend your time on cherry-picking.
