### ISSUE TITLE
Search module theming (prompt class)

### ISSUE THREAD

**Issue by nicolasayala** [Semantic-Org/Semantic-UI-React#3676]
## Bug Report
I can't theme the search module (prompt part) :
```css
/* src/semantic-ui/site/modules/search.variables */

@promptBackground: @red;
```

### React jsx
 The jsx used for the search component is the one from the [react semantic ui doc.](https://react.semantic-ui.com/modules/search/#types-category-custom)

### Expected Result
The search bar prompt background should be red

### Fix ?

css doesn't apply cause the css rule isn't right

```diff
/* # node_modules/semantic-ui-less/definitions/modules/search.less */

- .ui.search > .prompt {
+ .ui.search .prompt {  /* .prompt isn't directly under .ui.search (see html) */
  [...]
  background: @promptBackground;
  [...]
}

.ui.search .prompt { /* Already done here */
  border-radius: @promptBorderRadius;
}
```

html search module structure
```html
<div class="ui search">
  <div class="ui input">
    <div class="prompt">
  <div class="results">
```

### Version
    semantic-ui-react: ^0.87.2
    semantic-ui-less: 2.4.1

**Comment by layershifter** [comment]
Sorry, but we can't handle CSS problems there. You can report them to the main repo: https://github.com/Semantic-Org/Semantic-UI

Or also to folks in FUI: https://github.com/fomantic/fomantic-ui/
