### ISSUE TITLE
Dynamically create checkboxes and add change handlers for the same : Semantic-ui-react + React

### ISSUE THREAD

**Issue by vjr12** [Semantic-Org/Semantic-UI-React#3681]
I am trying to create dynamic checkboxes using semantic-ui-react I have object of the following structure. I want the checkbox value should get applied to the particular object in this array. I am unable to do it with the change handler provided below. Can someone help me with this?

Seems like change handler is not working

Sandbox: https://codesandbox.io/s/suspicious-pine-r5dpi

**Comment by layershifter** [comment]
Please use StackOverflow for usage questions: https://stackoverflow.com/questions/tagged/semantic-ui-react

However, as I see, you should take `checked` from the second param, see controlled example: https://react.semantic-ui.com/modules/checkbox/#usage-remote-control
