### ISSUE TITLE
How to get the key of an item when it's being clicked?

### ISSUE THREAD

**Issue by zbeedatm** [Semantic-Org/Semantic-UI-React#3686]
I'm trying to implement a nested accordion, but not populating it completly when loading the component... populating only level 1, and by demand when the user click on one item I want to populate it's inner accordion.

In order to get the clicked item text I used:
` handleOnItemTitleClicked(e, lvl) {
        console.log("======>", e.currentTarget.textContent);
    }`

`elementsLevel1.forEach(function(item) {
            lvl1Items.push(
                {key: item.Name, title: item.Name, content: ''}
            )
        });`

` <Accordion defaultActiveIndex={0} panels={lvl1Items} styled onTitleClick={this.handleOnItemTitleClicked.bind(this)} />`

When building the accordion I used keys, so how can I get the key of an item after it was clicked and not the text content?

**Comment by layershifter** [comment]
https://react.semantic-ui.com/modules/accordion/#usage-active-index

Please check controlled usage example, it shows how to use `onTitleClick` prop and get `index` from it. Then you can use it just like this: `lvl1Items[index]`.

Please use StackOverflow for usage questions: https://stackoverflow.com/questions/tagged/semantic-ui-react
