### ISSUE TITLE
Search: fullTextSearch?

### ISSUE THREAD

**Issue by dchen71** [Semantic-Org/Semantic-UI-React#3690]
### Problem description
Essentially, I have about 30000 genes which many overlapping substrings with fuzzy matching. It doesn't look like the *fullTextSearch* prop has been ported yet to the react package but it sounds like it would solve my issue. Is anyone still working on this feature?

**Comment by layershifter** [comment]
Nope, and I am not sure that we actually need it. If you need to have fuzzy-search I recommend to use Fuse.js: https://fusejs.io/ It will allow to match multiple keys, set limits, etc.

I made a CodeSandbox to show how it can be combined:
https://codesandbox.io/s/semantic-ui-react-example-qqn5z
