### ISSUE TITLE
Ref doesn't properly render with Enzyme.

### ISSUE THREAD

**Issue by andrewplummer** [Semantic-Org/Semantic-UI-React#3694]
## Bug Report

It seems that the `Ref` HOC doesn't play well with Enzyme. Using `shallow` will result in a warning and `render` or `mount` will throw an error.

### Steps

```js
import React from 'react';
import { configure, shallow, render, mount } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import { Ref, Container } from 'semantic-ui-react';

configure({ adapter: new Adapter() });

function Foo() {
  const ref = React.createRef();
  return (
    <Ref innerRef={ref}>
      <Container>Content</Container>
    </Ref>
  );
}

describe('foo', () => {
  it('blahblah', () => {
    const wrapper = shallow(<Foo />);
  });
});
```

### Expected Result
Element should properly be wrapped/rendered/mounted.

### Actual Result
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
### Version
0.87.3

**Comment by layershifter** [comment]
https://codesandbox.io/s/dank-sunset-qz4cp

What version of Enzyme you're using? Can you please provide a repro?

![image](https://user-images.githubusercontent.com/14183168/60981475-b4e55280-a336-11e9-9f3a-d19488eb62db.png)

![image](https://user-images.githubusercontent.com/14183168/60981450-a860fa00-a336-11e9-931c-e3de2d246652.png)

We testing all our components with Enzyme and will be really strange to have such issue.

**Comment by andrewplummer** [comment]
Apologies! I had confirmed several times and this was not working and now it's working great! I may have unintentionally upgraded some libs or something in the meantime. At any rate I've switched to using the `Ref` HOC and everything works as intended! Thank you!
