### ISSUE TITLE
Using Dropdown with formik

### ISSUE THREAD

**Issue by LawrenShin** [Semantic-Org/Semantic-UI-React#3695]
Passing formik's handleChange to onChange prop of Dropdown causes this warning - 
Formik called `handleChange`, but you forgot to pass an `id` or `name` attribute to your input:
    <span class="text">TT / 35-80 / 65-20</span>
    Formik cannot determine which value to update. For more info see

**Comment by layershifter** [comment]
I believe that this issue should be helpful: https://github.com/jaredpalmer/formik/issues/148#issuecomment-335259213

Please use StackOveflow for usage questions: https://stackoverflow.com/questions/tagged/semantic-ui-react
