### ISSUE TITLE
How to navigate pressing <enter> on a SearchResult rendered as Link?

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#3697]
I've managed to render SearchResult (of [Search](https://react.semantic-ui.com/modules/search/) component) as Link ([react-router-dom](https://reacttraining.com/react-router/web/api/Link)) which obviously has a "to" prop.

If I click on a search result, it works as expected: the browser changes to the URL specified by "to" prop.

But, If I navigate between the search results with up and down arrows and then press enter on one of them, router navigation doesn't work.

Any thoughts on that? Any solutions?

**Comment by layershifter** [comment]
Please provide a **minimal** repro.

**Comment by ghost** [comment]
@layershifter 

Here you go: https://codesandbox.io/s/semantic-ui-react-issues-3697-yvtt6

**Comment by ghost** [comment]
@layershifter Hey there, any change you took a look on the issue?

**Comment by layershifter** [comment]
Hey, sorry for a delay in answer.

Accessibility should be done manually: https://github.com/ReactTraining/react-router/issues/6600 :(

I updated your CodeSandbox: https://codesandbox.io/s/semantic-ui-react-issues-3697-9r7u3
Key things: 
- `useLocation()` hook to navigate
- usage of `onResultSelect()`

It's everything that you need:
```jsx
onResultSelect={(e, data) => {
  navigate(data.result.to);
}}
```
