### ISSUE TITLE
Using <Confirm /> in a .map loop will not work as expected

### ISSUE THREAD

**Issue by titivermeesch** [Semantic-Org/Semantic-UI-React#3698]
### Steps
I wrote this render function : 
`render() {
    return (
      <div className='custom-modal'>
        <Link to='/c' onClick={this.hideFader}>
          <Icon name='close' className='close-button' size='big' />
        </Link>

        <h1>Your contributions</h1>
        {this.props.requests.map(d => {
          return (
            <div className='chat-thread' key={uuidv1()}>
              <Link to={`/c/contribution/${d.id}`}>
                <div>
                  <h2>{d.title}</h2>
                  <p>{d.description}</p>
                  <p>ID: {d.id}</p>
                </div>
              </Link>
              <div>
                <Icon
                  name='close'
                  className='request-delete'
                  onClick={this.show}
                  size='big'
                />
                <Confirm
                  open={this.state.open}
                  content={`Are you sure you want to delete this request? All the information including the chat linked to this request will be deleted!`}
                  onCancel={this.handleCancel}
                  onConfirm={this.handleConfirm(d.id)}
                  size={'mini'}
                />
              </div>
            </div>
          )
        })}
      </div>
    )
  }`
handleConfirm() just console log the passed id.

### Expected Result
This should create a bunch of confirms with different id's passed into it. So I have id's from 1 to 5, and there should be 5 functions, handleConfirm(1), handleConfirm(2),...

### Actual Result
Don't matter on which Icon I click, it will always return the last id (in this case 5).
I logged the id out of `<Confirm /> ` and that works, but inside the confirm itself it don't work.

### Version
Latest with ES6 import.

**Comment by layershifter** [comment]
Please provide a repro case. I don't think that this issue is related to Semantic UI React.

**Comment by tadivenkat** [comment]
I could reproduce this problem too. This is a valid issue.

**Comment by jonnyfluckey** [comment]
Also can confirm this issue is accurate. I could not for the life of me figure out how the wrong value was getting passed in my map. I removed the Confirm and ran the function directly, and it worked as intended

**Comment by mariowr2** [comment]
Same issue, Confirm inside `map` does not behave correctly.

**Comment by titivermeesch** [comment]
Well, nice to see my one year old issue is still relevant, @layershifter maybe consider opening this again?

**Comment by layershifter** [comment]
I will reopen it once there will be a repro on Codesandbox. Currently I don't see that the issue is valid 🤨

**Comment by layershifter** [comment]
I created a CodeSandbox and I can't repro it there:
https://codesandbox.io/s/semantic-ui-example-dinew?file=/example.js

For usage questions please use StackOverflow, for bugs please fill our issue template fully and include a repro on CodeSandbox.
