### ISSUE TITLE
Shorthand for quick tooltips

### ISSUE THREAD

**Issue by Obiwarn** [Semantic-Org/Semantic-UI-React#3699]
## Feature Request

I use Popups a lot. And it is quite verbose to wrap it around my components like this:

` <Popup content='My Tooltip!' trigger={<Button icon='add' />} />`

How about a shorthand for all Semantic Elements like e.g. "popup"?

`<Button popup={'My Tooltip!'} icon='add/>`

**Comment by layershifter** [comment]
Duplicate for #2552 🐰
