### ISSUE TITLE
Dropdown (multiple) search box does not grow with input

### ISSUE THREAD

**Issue by dylankiss** [Semantic-Org/Semantic-UI-React#370]
Currently when you have a multi select dropdown, the search box does not expand when you start typing in it.

![multi-select-search-bug](https://cloud.githubusercontent.com/assets/5985577/17405922/b1fe8184-5a61-11e6-9a56-6aed6e160555.gif)

In Semantic UI, the `width` style property is set on the DOM element itself when the content of the search box changes. We could take a similar approach here?

**Comment by levithomason** [comment]
We had pushed this minor issue off previously.  Time to fix it! See #371.

**Comment by levithomason** [comment]
Fixed and released in `v0.27.7`.
