### ISSUE TITLE
as prop not working with styled components v4 

### ISSUE THREAD

**Issue by sergeushenecz** [Semantic-Org/Semantic-UI-React#3703]
Hello everyone. I've updated styled components from 3 to 4 version.And my code don't work.Because in the v4 added "as prop" and it conflicting with your "as prop"

```
export const StyledHeader = styled(Header)`
  display: inline-block;
  margin-bottom: 0!important;
`;
<StyledHeader as="h3" content={"test"} />
```

It's will render 
`<h3 content="test"></h3>` 
but  it to need render 
`<h3>test</h3>`

Can you help me?

**Comment by layershifter** [comment]
https://www.styled-components.com/docs/api#forwardedas-prop

You should use `forwardedAs`:

```jsx
import { Header } from "semantic-ui-react";
import styled from "styled-components";

const StyledMyHeading = styled(Header)`
  font-size: ${props => (props.small ? 28 : 36)}px;
`;

<StyledMyHeading forwardedAs="h2" content="Bar" small />
```

https://codesandbox.io/s/styled-components-4-5qp0h

**Comment by sergeushenecz** [comment]
@layershifter Thanks
