### ISSUE TITLE
(Form.)Input does not support color type

### ISSUE THREAD

**Issue by HunteRoi** [Semantic-Org/Semantic-UI-React#3708]
### Steps
1) Use an Input
2) Define this input's type as `type='color'`
3) Appreciate the rendering

### Expected Result
A colored square

### Actual Result
A tiny colored line which is so tiny that you cannot even say what color it is.

### Notes
I have tried to apply a specific class to modify the input's height (at least to make it a square you know) but I could not make it work through the React Semantic UI `Input` component. The `className` attribute is applied to the top ancestor of the Input (in my case, the \<div class="field"\>), thus not the \<input\> itself.
Involved project can be found at the following repository : <https://github.com/oSoc19/opt-horison>.

### Version
0.87.3

### Testcase
```javascript
import React from 'react'
import { Input } from 'semantic-ui-react'

const InputExampleInput = () => <Input type='color' />

export default InputExampleInput
```
![image](https://user-images.githubusercontent.com/32441291/61302073-75f74700-a7e5-11e9-9f04-534f0671bcac.png)

**Comment by layershifter** [comment]
This is a CSS issue and can't be handled on our side. As workaround:
```jsx
<Input type='color' value='#cccccc' input={{ style: { height: 38, padding: 0 } }} />
```

And with in `Form`:
```jsx
  <Form>
    <Form.Input placeholder='Your name' />
    <Form.Input
      type='color'
      value='#cccccc'
      input={{ style: { height: 38, padding: 0 } }}
    />
  </Form>
```

 I created an issue in Fomantic UI to track it: https://github.com/fomantic/Fomantic-UI/issues/881

Thanks for the report 👍
