### ISSUE TITLE
How can i custom Semantic-UI theme with next.js ?

### ISSUE THREAD

**Issue by sessionboy** [Semantic-Org/Semantic-UI-React#3709]

**Comment by layershifter** [comment]
Please use StackOveflow for usage questions. It's not related to React implementation actually 🤔 

I believe that it should work with [next-less](https://github.com/zeit/next-plugins/tree/master/packages/next-less), see also: https://github.com/zeit/next.js/issues/3340

**Comment by jieliu218** [comment]
@sessionboy 

https://annacoding.com/article/6FndBILqMD16Bp7w95WJrd/How-to-customize-the-Semantic-UI-React-theme-in-Next.js-Part-1

https://annacoding.com/article/2Mdrahk2d6LZfGv1UL19Ml/How-to-customize-the-Semantic-UI-React-theme-in-Next.js-Part-2
