### ISSUE TITLE
Table with props definition and color behaves badly

### ISSUE THREAD

**Issue by xReaven** [Semantic-Org/Semantic-UI-React#3710]
## Bug Report

Hey everyone,

Today I tried to use the Table component with the definition props and color props, but it is not behaving as I excepted.
I am 99% convinced it is not your will, therefore, hello there :)

You can reproduce on your online documentation, otherwise there's codesandbox link bellow.

### Steps

- Import Table from the semantic-ui-react package
- Render it with property definition and color to any color, let's say color='red'
- That's it

### Expected Result

Sweet Table with red top border

### Actual Result

Slobbery Table, the border starts in nowhere

### Version

SUIR 0.87.3

### Testcase

A code example show more than my words : https://codesandbox.io/embed/table-behaves-badly-hdcsh

**Comment by layershifter** [comment]
Great and valid report, but we don't handle CSS and can't fix it on our side. Created an issue in FUI: https://github.com/fomantic/Fomantic-UI/issues/883

Probably folks will propose a proper workaround there 🐱
