### ISSUE TITLE
ref to Button component

### ISSUE THREAD

**Issue by Martinnord** [Semantic-Org/Semantic-UI-React#3717]
### Problem description
I used the `Sidebar` component today and wanted to restrict where you can close it. Meaning that I only want to able to **close** the sidebar with a button within it.

I managed to make this work with React's `useRef` hook. But when I wanted to use a Semantic `Button` and add the `ref` prop to it, it wouldn't close anymore. 

I made a small Codesandbox where you can see this in action: https://codesandbox.io/s/semantic-ui-react-e8nij

### Proposed solution
I really don't have a _solid_ solution to this, but rather a tiny request to have this added to the `Button` component. I'm sure you have thought about this before, so there might be some drawbacks on having this. I'm not too sure. 

But I'd be happy to add this feature myself.

Thanks for the cool library!

**Comment by layershifter** [comment]
@Martinnord it seems that you complicating implementation, you don't need to have a separate listeners at all. Please check CodeSandbox:
https://codesandbox.io/s/semantic-ui-react-kucmw

Please also check examples, they can be helpful:
https://react.semantic-ui.com/modules/sidebar/#usage-callback
https://react.semantic-ui.com/modules/sidebar/#usage-target

****

If you will still need `ref`, you can use `Ref` component:
```jsx
<Ref innerRef={buttonRef}>
  <Button />
</Ref>
```

https://react.semantic-ui.com/addons/ref/
