### ISSUE TITLE
Update Font Awesome icons to v.5.9

### ISSUE THREAD

**Issue by snydercoder** [Semantic-Org/Semantic-UI-React#3724]
### Problem description
There are many new icons that would be nice to use with Semantic UI React.

### Proposed solution
Import the latest 5.9 icons

**Comment by fracmak** [comment]
This is only the react implementation of semantic ui. The css comes from the mainline repo. There’s an issue there tracking the upgrade. 

https://github.com/Semantic-Org/Semantic-UI/issues/6395
