### ISSUE TITLE
Grid contents positioned off left side of page

### ISSUE THREAD

**Issue by gbob81** [Semantic-Org/Semantic-UI-React#3726]
## Bug Report
I'm running into an issue where the contents of a Grid are positioned off the left side of the page.

### Steps
Render the following code somewhere in your project (note: in my case it was not within another Grid):

```
        <Grid>
            <Grid.Row>
                <div>Fluby-floo!</div>
            </Grid.Row>

            <Grid.Row>
                <div>Foo!</div>
            </Grid.Row>

            <Grid.Row>
                <div>Bar!</div>
            </Grid.Row>
        </Grid>
```

Here is the HTML that was generated as a result:

```
<div class="ui grid">
	<div class="row">
		<div>Fluby-floo!</div>
	</div>

	<div class="row">
		<div>Foo!</div>
	</div>

	<div class="row">
		<div>Bar!</div>
	</div>
</div>
```
### Expected Result
The text in the Grid above should be positioned to the right of, or at least flush with the left hand side of the page.

### Actual Result
Everything looks good so far, but when I look at the results in the browser, this is what I see (note: the left hand side of the screenshot is the left hand side of the browser window):

![image](https://user-images.githubusercontent.com/28653580/62302569-96134100-b448-11e9-8b81-a948d64e6654.png)

I see the same result in Chrome 75.0.3770.100, Firefox 60.8.0esr, and IE 11.0.9600.19399.

### Version
From my package.json file:

```
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^0.87.3"
```

### Testcase
[Example of the bug](https://codesandbox.io/embed/semantic-ui-react-7vnx6)

**Comment by layershifter** [comment]
@gbob81 you missed one important thing 🐱 

```diff
-<div>Fluby-floo!</div>
+<Grid.Column>Fluby-floo!</Grid.Column>
```

You need to always have `Grid` => `Grid.Column` or `Grid` =>`Grid.Row` => `Grid.Column` structure.

**Comment by gbob81** [comment]
That's helpful to know, thank you!  It would be helpful if this key detail were included (and called out specifically) in the docs.  I love all the examples, but I think they could use some front-matter that tells you important info like this.
