### ISSUE TITLE
Progress bar inverted doesn`t work

### ISSUE THREAD

**Issue by zcaalock** [Semantic-Org/Semantic-UI-React#3728]
### Steps
Progress percent={80}  indicating inverted/

### Expected Result
it should invert colors, red at 100% , green at ~0%

### Actual Result
inverted prop removes gray background

### Version
0.87.3

**Comment by layershifter** [comment]
`Progress` with `inverted` should be used with inverted background, please check original examples: https://react.semantic-ui.com/modules/progress/#variations-inverted

***

```jsx
  <Segment inverted>
    <Progress percent={0} inverted indicating />
  </Segment>
```

![image](https://user-images.githubusercontent.com/14183168/63425430-cda25700-c410-11e9-9bfd-34557c1358d9.png)

***

```jsx
  <Segment inverted>
    <Progress percent={20} inverted indicating />
  </Segment>
```
![image](https://user-images.githubusercontent.com/14183168/63425448-d8f58280-c410-11e9-9f17-65a2f3bbbd43.png)

***

```jsx
  <Segment inverted>
    <Progress percent={80} inverted indicating />
  </Segment>
```

![image](https://user-images.githubusercontent.com/14183168/63425481-edd21600-c410-11e9-9770-d74a76a6a572.png)

***

Did I miss something?
