### ISSUE TITLE
Unable to resolve module `semantic-ui-css/semantic.css

### ISSUE THREAD

**Issue by samuelgoldenbaum** [Semantic-Org/Semantic-UI-React#3738]
## Bug Report
Following exact steps to install and import results in failure to resolve module. 

### Steps
Attempt to install semantic-ui-css by following setup instructions and adding the relevant import statement:

`yarn add semantic-ui-css`

`import 'semantic-ui-css/semantic.min.css'`

### Expected Result
Installed and available

### Actual Result
`Unable to resolve module `semantic-ui-css/semantic.css` from `/Users/dude/Documents/myapp/app/index.js`: Module `semantic-ui-css/semantic.css` does not exist in the Haste module map`

### Version
semantic-ui-react@0.87.3

**Comment by layershifter** [comment]
What bundler are you using? Webpack? Is `css-loader` configured properly?

Please provide a repo with a minimal repro and will try to help. However, this issue is not related to SUIR at all.

**Comment by samuelgoldenbaum** [comment]
@layershifter thanks for the reply. I have simply created a new React Native app as per React docs and then followed Semantic UI steps to add the default theme. I am not customizing any themes at this stage.
[repo](https://github.com/samuelgoldenbaum/rsui )

**Comment by manemmao** [comment]
same error in Create React App with latest update package tag

**Comment by manemao** [comment]
same error in Create React App with latest update package tag. before update haven't any error.

`./src/index.js 
Module not found: Can't resolve 'semantic-ui-css/semantic.css' in 'C:\...' Compiling... Failed to compile.`

**Comment by layershifter** [comment]
@manemmao it seems that you forgot to install `semantic-ui-css` package, try to run `yarn add semantic-ui-css` and then run your app again.

**Comment by layershifter** [comment]
@samuelgoldenbaum Thanks for your reply. As I know you can't use SUIR with React Native, https://github.com/Semantic-Org/Semantic-UI-React/issues/790#issuecomment-258333177. That's root issue, styles are also incompatible 😢 

Please correct me if I am wrong.

**Comment by manemao** [comment]
@layershifter no i didnt forgot. it was working right before update. not stable version, latest one. i downgrade back to 2.4.1 and it works well again.

**Comment by layershifter** [comment]
But `2.4.1` is the latest for `semantic-ui-css`:
![image](https://user-images.githubusercontent.com/14183168/63425578-283bb300-c411-11e9-883e-489d82b5bf06.png)

**Comment by levitomer** [comment]
Status? (Still reproducing)

**Comment by layershifter** [comment]
@levitomer this is 99% related to your tooling. Please provide more details.

**Comment by Profnird** [comment]
facing same Ishh :( semantic-ui-css thing messing up my react app and i still want to use it. 
I am using webpack react/electronjs

**Comment by Profnird** [comment]
Well I found a way around it :) 
I linked the semantic. <link rel="stylesheet" href="./node_modules/semantic-ui-css/semantic.min.css"> in index.html
then called import { Button } from 'semantic-ui-react'; in my component :) well it might not be the best way since its better to use CDN if the app is hosted on a server if locally like me using it along side electron then you can use my method or dowload the semantic-ui separately then use the link:href
