### ISSUE TITLE
Input clear button does not work in Microsoft Edge

### ISSUE THREAD

**Issue by joeyUOFA** [Semantic-Org/Semantic-UI-React#3739]
Hi,

I have explained the issue in https://stackoverflow.com/questions/57297498/input-clear-button-does-not-work-in-microsoft-edge. It is caused by the popup in semantic ui react. How can I use popup for form input?

Thanks

**Comment by layershifter** [comment]
Sorry, but we don't have time to debug your code. Can you please provide a minimal repro on CodeSandbox with a repro steps? I.e., please fully fill the issue template.

**Comment by joeyUOFA** [comment]
> Sorry, but we don't have time to debug your code. Can you please provide a minimal repro on CodeSandbox with a repro steps? I.e., please fully fill the issue template.

Thanks for your reply. 

This is a sample project to demo the issue: https://codesandbox.io/s/redux-form-field-level-validation-zedcu?fontsize=14

In Edge, the input has a clear button, but it cannot clear the input after clicked.

**Comment by layershifter** [comment]
As was mentioned on StackOverflow, it's an Edge bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17584515/ There are no change events when this clearing button is pressed and actual value is captured in `onBlur()`.

### Why it happens with `Popup`?

By default `Popup` will be visible on `hover` and `click` so once you will hover it by mouse, it will become visible and will rerender its trigger, in this case `trigger` 👎 

![ITmObGYdNM](https://user-images.githubusercontent.com/14183168/62646922-adbe5e00-b94f-11e9-9458-5ea7f7bf2b00.gif)

### How to solve?

I am not going to fix it, it's a browser bug 🐞 Possible fixes depend on which behavior you expect...

#### Option 1: Show `Popup` on `focus`

```jsx
<Popup on='focus' />
```

In this case `Popup` will be rendered on `focus` and will hide on `blur`.
![ITmObGYdNM](https://user-images.githubusercontent.com/14183168/62647048-f83fda80-b94f-11e9-95a3-c16859798914.gif)

### Option 2: use `context` prop

Place `Popup` as sibling to `Form.Field` and use `context` prop with controlled mode: https://react.semantic-ui.com/modules/popup/#usage-context-controlled

```tsx
  const ref = React.useRef();

  return (
    <>
      <Popup open={touched} context={ref}>
        <div />
      </Popup>
      <Ref innerRef={ref}>
        <Form.Input {...input} />
      </Ref>
    </>
  );
```
![ITmObGYdNM](https://user-images.githubusercontent.com/14183168/62647396-bc594500-b950-11e9-86ef-755b8bb9bdd8.gif)

https://codesandbox.io/s/redux-form-field-level-validation-kik0u

---

Hope that it will help ⛑
