### ISSUE TITLE
Dropdown - AllowAdditions: Is it possible to show the additonal field at the end of the list

### ISSUE THREAD

**Issue by zheyujie** [Semantic-Org/Semantic-UI-React#3746]
https://react.semantic-ui.com/modules/dropdown/#usage-allow-additions

For the AllowAdditions feature, is it possible to have the "Add abc" field shown at the end of the dropdown items?
Currently, if I type something, for example "abc", the following fields will be show:

-Add abc
-abcdef

Is it possible to show the "Add abc" field at the bottom like this:

-abcdef
-Add abc

Thanks

**Comment by zheyujie** [comment]
OK I found this in the Dropdown code:

  /** Position of the `Add: ...` option in the dropdown list ('top' or 'bottom'). */
  additionPosition?: 'top' | 'bottom'

I will try it later and see how it goes

**Comment by layershifter** [comment]
Yep, it's possible:

```diff
  handleAddition = (e, { value }) => {
    this.setState(prevState => ({
-      options: [{ text: value, value }, ...prevState.options],
+      options: [...prevState.options, { text: value, value }],
    }))
  }
```
