### ISSUE TITLE
Search: Issues when getting input element ref

### ISSUE THREAD

**Issue by noinkling** [Semantic-Org/Semantic-UI-React#3750]
It's unclear what the expected way to get a ref to a `Search` component's `<input>` element is. The methods I've been able to make work are a little less than ideal for various reasons.

### Use Case
I have a `Search` component that stays mounted permanently at the top of my page. In the `onResultSelect` callback I trigger route changes (using react-router), however the search input retains focus. That behaviour might be desirable in some cases, but in this case I would like to unfocus the input when this happens, which means getting a handle on the DOM element so I can call `.blur()` on it.

### Actual Result
These are the methods I've been able to make work.

1. **Nested shorthand props:**

    ```jsx
    // In class body
    inputRef = React.createRef()

    // In render
    <Search
      ...
      input={{
        input: { ref: this.inputRef }
      }}
    />
    ```
    Problem: The `<input>` element loses the props that `Search` sets, the ones found here:

    https://github.com/Semantic-Org/Semantic-UI-React/blob/dd66e920a845c199ad2cc05ddec38293a235ec20/src/modules/Search/Search.js#L531

    This is because the linked code doesn't account for the possibility of having to merge the nested shorthand props, instead the object I provide just overwrites them. Of course I could manually add those props myself, but that seems hacky/brittle. Should this be considered a bug? 

2. **Undocumented property on `Input` component:**

    ```jsx
    // In class body
    inputcomponentRef = React.createRef()

    handleResultSelect = (e, { result }) => {
      ...
      this.inputComponentRef.current.inputRef.current.blur()
    }

    // In render()
    <Search
      ...
      input={{ ref: this.inputComponentRef }}
    />
    ```

    Problem: Since it's undocumented, it shouldn't be relied on. See #1980.

    Actually the `Input` component provides a (documented) `.focus()` method directly, presumably to make this sort of thing easier. Since that's the case, maybe its `.blur()` counterpart deserves to be added too? But I feel like that's a slippery slope that just skirts around the issue.

3. **Function shorthand + `Ref` component:**

    ```jsx
    // In class body
    wrapperDivRef = React.createRef()

    handleResultSelect = (e, { result }) => {
      ...
      this.wrapperDivRef.current.querySelector('input.prompt').blur()
    }

    // In render()
    <Search
      ...
      input={(Input, inputProps) => (
        <Ref innerRef={this.wrapperDivRef}>
          <Input {...inputProps} />
        </Ref>
      )}
    />
    ```

    This would be nicer if the `.querySelector()` call could be avoided, but the markup requires the wrapper div. Also this uses `ReactDOM.findDOMNode()` under the hood, which is deprecated. It also seems like this might have slight performance implications? I realize I can extract the function to stop a new one being created on every render and maintain referential consistency, but there's still the overhead of the HOC if nothing else.

    Probably still the best option currently.

### Expected Result
I get a reference to the `<input>` element in a 'clean'/user-friendly manner.

### Version
0.87.3

**Comment by layershifter** [comment]
The first solution is the best. It seems that shorthand in `Search` should be fixed to work properly.

**Comment by noinkling** [comment]
@layershifter PR submitted.
