### ISSUE TITLE
Include old dropdown value in onChange data

### ISSUE THREAD

**Issue by sluramod** [Semantic-Org/Semantic-UI-React#3753]
### Problem description
when onChange() callback is invoked, value property of the data is overridden by the new value, and there is no way to access old value in the callback

### Proposed solution
Include new property 'oldValue' in onChange() callback data

**Comment by layershifter** [comment]
You can create an own wrapper for `Dropdown` to archive this.
We are not going to have this functionality as there is nothing similar in native controls.
