### ISSUE TITLE
Table Row borders are not appearing.

### ISSUE THREAD

**Issue by BagEnd2End** [Semantic-Org/Semantic-UI-React#3756]
### Use Case: 
I am trying to create a react table. In this case a one with the prop basic="very" however even if I remove this prop there are no dividers between table rows.

`<Table basic="very">

        <Table.Header>

          <Table.Row>

            <Table.HeaderCell>Header</Table.HeaderCell>

          </Table.Row>

        </Table.Header>

        <Table.Body>

          <Table.Row>

            <Table.Cell>Content</Table.Cell>

          </Table.Row>

          <Table.Row>

            <Table.Cell>Content</Table.Cell>

          </Table.Row>

        </Table.Body>

      </Table>`

### Actual Result: 
There are no dividers between the table rows

![image](https://user-images.githubusercontent.com/28845265/63445980-66cc7000-c407-11e9-87d1-300a39c29479.png)

### Version:
^0.83.0

**Comment by layershifter** [comment]
Please fill the issue template fully and don't use screenshots to share code.

As I see, markup is not fully defined:

```jsx
  <Table basic='very'>
    <Table.Body>
      <Table.Row>
        <Table.Cell>John</Table.Cell>
      </Table.Row>
      <Table.Row>
        <Table.Cell>Jill</Table.Cell> /* Table.Cell is required */
      </Table.Row>
    </Table.Body>
  </Table>
```

**Comment by layershifter** [comment]
Are they visible there?
https://react.semantic-ui.com/maximize/table-example-very-basic/

**Comment by BagEnd2End** [comment]
They are

**Comment by layershifter** [comment]
So, it means that it's an issue on your side 🤔 

Please provide a minimal repro on CodeSandbox, you can use this one as reference:
https://codesandbox.io/s/rmx8v67724?module=/example.js So I will be able to clarify the issue, however it's definitely a CSS problem.

**Comment by layershifter** [comment]
We don't have a repro, closing for housekeeping.
