### ISSUE TITLE
Label disappears when adding ribbon='right' attribute 

### ISSUE THREAD

**Issue by marcio-codes** [Semantic-Org/Semantic-UI-React#3759]
As the title states, when you add ribbon='right' this will cause the label to disappear. Only works if you leave it as ribbon, without adding 'right'.

My dependencies:
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-scripts": "3.1.1",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^0.87.3"

**Comment by layershifter** [comment]
```jsx
    <Label ribbon>
      <Icon name='mail' /> 23
    </Label>
    <Divider clearing />
    <Label ribbon='right'>
      <Icon name='mail' /> 23
    </Label>
```

![image](https://user-images.githubusercontent.com/14183168/63599745-7f34ba00-c5c2-11e9-8aca-fd7a58e813d8.png)

***
However, `ribbon` is quite buggy feature in SUI CSS 😢 Can you please make a repro and provide it there, so I can to transfer the issue to FUI: https://github.com/fomantic/fomantic-ui/issues. Or you can do it by yourself.

**Comment by marcio-codes** [comment]
Nope, not working for me:

<img width="511" alt="Screen Shot 2019-08-23 at 10 32 42 AM" src="https://user-images.githubusercontent.com/1448245/63600346-65c74a00-c591-11e9-88fd-c8c2cdc9f50f.png">

**Comment by layershifter** [comment]
We don't have a repro, closing for housekeeping.
