### ISSUE TITLE
shallowequal.js filepath errors when upgrading to 0.88.0

### ISSUE THREAD

**Issue by AdventureBeard** [Semantic-Org/Semantic-UI-React#3770]
I'm upgrading from 0.81.1 to 0.88.0 and I'm getting this when I try to start my dev server:

```
./node_modules/semantic-ui-react/dist/commonjs/modules/Search/Search.js
Cannot find file: 'shallowequal.js' does not match the corresponding name on disk: './node_modules/semantic-ui-react/dist/commonjs/lib/shallowEqual.js'.
```

I don't see any mention of this issue online, so I imagine my dependencies are donked up somehow. Any tips? Modifying the file names to get rid of this error leads to a rabbithole of shallowequal related bugs, and of course is not a sustainable solution anyhow.

**Comment by layershifter** [comment]
Try to remove your `node_modules` and install dependencies again, then please ensure that you're running `0.88.0` as there are no such lines:

![image](https://user-images.githubusercontent.com/14183168/64104579-c5cda580-cd74-11e9-9b6b-67a4dd12f0a6.png)
https://cdn.jsdelivr.net/npm/semantic-ui-react@0.88.0/dist/commonjs/modules/Search/Search.js
