### ISSUE TITLE
Docs: Missing descriptions for Table props

### ISSUE THREAD

**Issue by fxOne** [Semantic-Org/Semantic-UI-React#3773]
### Problem description
The example [Structured](https://react.semantic-ui.com/collections/table/#types-structured) shows the parameter `rowSpan` and `colSpan` which are missing in the props documentation for `Table.HeaderCell` and `Table.Cell`.

### Proposed solution
If it is ok I would create a pull request with the added properties.

**Comment by layershifter** [comment]
We don't document HTML props (like `rowSpan`, `colSpan`) as all of them are passed down, it;s covered in our docs, see: https://react.semantic-ui.com/augmentation#unhandled-props-dom-attributes
