### ISSUE TITLE
Check boxes do not work with React Hooks. 

### ISSUE THREAD

**Issue by mazer-rakham** [Semantic-Org/Semantic-UI-React#3777]
Values, name, everything always returns undefined when using built in Component. Using same props in regular <input type='checkbox' works fine.

**Comment by mazer-rakham** [comment]
The code sandbox will not replicate it as the custom styling is not being applied. You only get undefined on Semantic's checkbox when the CSS is applied for semantic

**Comment by mazer-rakham** [comment]
There i got it working.
https://codesandbox.io/embed/react-codesandbox-n03no

**Comment by mazer-rakham** [comment]
If you remove the CSS it works fine, I have not checked if it needs to be in a controlled component but the semantic documents do not state that you need to.

**Comment by layershifter** [comment]
Use `data` from the second param, it has everything that you need:
https://codesandbox.io/s/react-codesandbox-c42sq

**Comment by mazer-rakham** [comment]
Ahh is that something I overlooked in the docs?

**Comment by mazer-rakham** [comment]
It was prob just be being dumb this morning honestly. Thanks!

**Comment by mazer-rakham** [comment]
Niiiiice, thank you for your time!
