### ISSUE TITLE
Serverside rendering broken since 0.88

### ISSUE THREAD

**Issue by GGAlanSmithee** [Semantic-Org/Semantic-UI-React#3778]
## Bug Report

Upgrading to 0.88 from 0.87.3 breaks SSR in a dotnet core React SPA

### Steps
1. Update to 0.88
2. Run the application

### Expected Result
For the application to be server-side rendered

### Actual Result

A lot of warnings regarding undefined (imports?) from SUIR

```js
Warning: Failed prop type: Container: prop type `as` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
          in Container
          in MainLayout
          in Context.Provider
          in Router
          in StaticRouter
          in Context.Provider
          in Provider
```

### Version
0.88.0

### Testcase
there is no simple replication of this, but i litteraly did nothing but to update the dep.

**Comment by GGAlanSmithee** [comment]
@layershifter thanks for your answer. I am using npm, not yarn but I will try to get proptypes updated. A bit weird though because I am not using prop-types directly, so it must be a fault in npms version resolving. Or are you saying that I am required to include this as a packge in order to use SUIR?

**Comment by GGAlanSmithee** [comment]
will close this since there's nothing actionable to do, thanks again @layershifter

**Comment by layershifter** [comment]
> Or are you saying that I am required to include this as a packge in order to use SUIR?

In your case you have an older version than SUIR requires that's it fails. Actually, you should have warning about it.

**Comment by GGAlanSmithee** [comment]
@layershifter yeah there seems to be something weird going on, as it wasn't even resolved by explicitly adding it in `packages.json`. Will investigate and report back if I find the cause of it.
