### ISSUE TITLE
Popup incorrectly shown after click dropdown menu item

### ISSUE THREAD

**Issue by peperoni321** [Semantic-Org/Semantic-UI-React#3779]
### Bug Report
**Steps**
    
1. Create dropdown menu with item which triggers popup message on click
2. Open dropdown list and click on this item 

**Expected Result**

I expect popup will be displayed correctly at the position of dropdown menu item as it was in 0.81.1 (currently I'm using this version which is the most stable)

**Actual Result**

Popup position is incorrect and being shown mostly in the top right corner or even is not visible at all.

**Version**

0.88.0

**Testcase**

`import React from 'react'`
`import { Dropdown, Menu, Popup } from 'semantic-ui-react'`

`const DropdownExamplePointing = () => (`
`    <Dropdown text='Shopping' pointing className='link item'>`
`      <Dropdown.Menu>`
`              <Dropdown.Item>Shirts</Dropdown.Item>`
`              <Popup content='Add users to your feed' on="click" trigger={<Dropdown.Item>Jeans</Dropdown.Item>} />`
`              <Dropdown.Item>Shoes</Dropdown.Item>`
`      </Dropdown.Menu>`
`    </Dropdown>`
`)`

`export default DropdownExamplePointing`

**Comment by layershifter** [comment]
`Dropdown` with Children API is not the best friend 😭 

Can you try this one? Is it working for you?
https://codesandbox.io/s/semantic-ui-example-n99fj
