### ISSUE TITLE
Config: support i18n

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#378]
Hi, I was wondering if you would consider having internationalisation Support out of the box? In my version of semanticui-react, i have approached it that i am passing translation function to the semanticui-react and then this function is called for any string. By default this function returns the original string. 

It makes the code very nicely readable. And less cluttered.

Since with this approach you know the list of elements and their possible internationalisable properties, I even wrote a simple extractor, that extracts all i18n strings to a JSON file for processing.

I would love to switch to your lib, maintaining a separate one makes no sense.

**Comment by levithomason** [comment]
I think i18n makes good sense.  I have some questions and ideas but it would be helpful to see some code for this.  Could you point me to where this is used in your project for reference? Or, you could open a PR here and we can hash out the details there instead.

**Comment by levithomason** [comment]
bump @tomitrescak

**Comment by tomitrescak** [comment]
Sorry @levithomason I'm having quite busy days. I experimented with several approaches, including generating specific `i18n-capale` components. But the easiest and most functional solution was following:
1. Create a config point for your library, a simple exported object would do:
   
   ``` js
   export default {
     translate: (key) => key; // default translate function returns the key itself
   }
   ```
2. Each place, where component is rendering text is replaced by calling of this function. For example:
   
   ``` js
   import config from '../config';
   <Button text={config.i18n(text)} />
   ```

Yes, this requires modification in almost all components. Many times when component is rendering "children" I leave it as it is, so all i18n strings need to be specified via text props.

With this approach you leave complete freedom to choose i18n library on the user.
From the user perspective you only need to configure what to use to translate your strings (MessageFormat ...). Following is an example of a custom translate function.

``` js
import config from 'stardust';

let transStrings = { ... };

config.i18n = (key) => return transStrings(key); // you can be much more explicit here
```

In my translate function I allow overriding of translation by prefixing ! to display non translated value, I also allow translation parameters to support plurals and more. Or you just use message format and make sure you specify parameters to it as it needs.

Does this sound ok?

[EDIT] for the purposes of i18n I have added a `<Text text="value" />` element, which displays translated string.

**Comment by levithomason** [comment]
I like the config idea.  I was hoping to see something like this.  We may have more configuration options later as well.  I would accept a PR that added a config object with an `i18n` key.

> In my translate function I allow overriding of translation by prefixing ! to display non translated value, I also allow translation parameters to support plurals and more. Or you just use message format and make sure you specify parameters to it as it needs.

I don't quite follow this part, though I think hashing it out on a PR would be best.

> [EDIT] for the purposes of i18n I have added a <Text text="value" /> element, which displays translated string.

I don't want to add a component to Stardust for this as it requires returning a another node.  The extra node will likely break some CSS layouts.  I'd prefer the example you've shown here:

``` jsx
import config from '../config';
<Button text={config.i18n(text)} />
```

Nearly every one of our components is configurable through props.  So, this should work great as well.

**Comment by tomitrescak** [comment]
@levithomason how should we proceed? 

Check out my repo and mainly: https://github.com/tomitrescak/semanticui-react/blob/master/src/config/config.tsx

This repo will become obsolete once you guys are finished, but I have all components done in react (e.g. Button)

https://github.com/tomitrescak/semanticui-react/blob/master/src/components/button_view.tsx

``` js
import * as React from "react";
import * as css from "classnames";
import config from "../config/config";

export interface IButtonProps {
  classes?: string;
  text?: string;
  basic?: boolean;
  color?: "primary" | "secondary" | "success" | "failure" | "blue" | "red" | "olive" | "orange" | "yellow" | "green" | "teal" | "blue" | "violet" | "pink" | "purple" | "brown" | "grey" | "black";
  inverted?: boolean;
  compact?: boolean;
  icon?: string;
  labeled?: "left" | "right" | boolean;
  floated?: "left" | "right";
  loading?: boolean;
  size?: "mini" | "tiny" | "small" | "medium" | "large" | "huge" | "massive";
  circular?: boolean;
  toggle?: "active" | "inactive";
  fluid?: boolean;
  disabled?: boolean;
  attached?: "left" | "right";
  active?: boolean;
  onClick?: Function;
  url?: string;
  children?: any;
  target?: string;
  step?: string;
  style?: any;
}

export const Button = ({
    text, classes, color, inverted, floated, target,
    icon, labeled, loading, size, circular, toggle, step, style,
    fluid, disabled, attached, basic, active, compact, onClick, url, children
  }: IButtonProps) => {

    const el = url ? config.linkElement : "button";
    return React.createElement(el, {
      target: target,
      step: step,
      style,
      className: css("ui", classes, size, attached,
        labeled,
        {
          "labeled": labeled,
        },
        floated,
        {
          "floated": floated
        },
        {
          "compact": compact,
          "active": active,
          "attached": attached,
          "inverted": inverted,
          "icon": icon,
          "loading": loading,
          "circular": circular,
          "toggle": toggle,
          "fluid": fluid,
          "disabled": disabled,
          "basic": basic,
        },
        toggle,
        color, "button"),
        onClick: onClick,
        href: url,
        to: url,
      },
      icon ? <i className={css(icon, "icon")}></i> : null,
      text && config.i18n(text),
      children
    );
  };

export default Button;
```

It's in typescript, but as a result I get al the nice intellisense.

**Comment by levithomason** [comment]
How about a PR adding a `config` module to `src/lib`?  It would be nice to to export a function to set the config.  This way we can validate the user's config options.  The only option we'll accept right now is an `i18n` function.  We can then do as you've done here and begin wrapping our strings literals and component props with it.  How's this sound?

As a side note, you also might be interested in the typescript work is being taken up at https://github.com/TechnologyAdvice/typings-stardust, see #361 for more information on how that came to be.

**Comment by tomitrescak** [comment]
@levithomason I'll do that as soon as possible.

One other thing you should consider is the option to render anchor elements either a classic anchors or user defined type. This is utterly important when using stuff like React router that needs "Link" element, or Ember or Angular that also use their own stuff for page navigation.

**Comment by levithomason** [comment]
True. Right now we use an anchor element when there is an href or onClick prop.  We used to provide a `link` prop, mirroring the SUI feature.  Some components still do this.

On my bucket list is to allow a `tagName` prop on all components that would allow you to set the tagName for any component.  This might also be called `elementType` since it can be either an HTML tagName or ReactClass.  This would allow you to specify a string or pass another component to render as.

**Comment by levithomason** [comment]
BTW, I'd accept a PR for this as well!

**Comment by levithomason** [comment]
Closing this for housekeeping, I'm still open for PRs on this effort should any be submitted.
