### ISSUE TITLE
Feat(Modal): add sort of "onDimmerClick" props

### ISSUE THREAD

**Issue by xReaven** [Semantic-Org/Semantic-UI-React#3781]
## Feature Request
Hello there (General kenobi ?),
First of all, you guys are doing a really great jobs on SUIR and I do not often see thanks in issues, so, yeah, I wanted to thanks you ! 

### Problem description
Long story short, I am using SUIR@0.87.3.
Something is blocking me with the Modal. Actually, I would like to distinguish two close handlers; the dimmer click and the close icon click.

Indeed, I want to implement a confirmation message like "You really want to leave this modal ?" on the dimmer click.
Where the close icon is pretty small, the user have to really want it to close the modal, the dimmer is kind of different to me, users could accidentally click it. (You already fixed the onMouseUp event that made leave the Modal not so long ago, thanks again !). And I would avoid that missclick.

Moreover, the closeIcon accepts a node, so dev's can already add their handler if needed.
There is no way to do it with the dimmer.

### Proposed solution

Basically, I would only need a callback at this place, before the return, something like :

```javascript
if (
      !closeOnDimmerClick ||
      doesNodeContainClick(this.ref.current, currentDocumentMouseDownEvent) ||
      doesNodeContainClick(this.ref.current, e)
    )
     /*
      * New code here, and as I do not really know the functions above,
      * I would add condition like "if we clicked on the dimmer part",
      * even if I guess it is the purpose of those functions.
      */
      _.invoke(this.props,'onDimmerClick', e, this.props);
      return
```

This way, I could control my Modal as I want.

Otherwise, just add the callback on the div in the render, where handleDimmerClick would only call the handler. Note that it would require closeOnDimmerClick to false, obviously : 

```javascript
    <div className={dimmerClasses} ref={this.dimmerRef} onClick={this.handleDimmerClick}>
```

I absolutely don't know what kind bad side effect it might have. To me, none.

Waiting for your feedback,
Have a great day :)

**Comment by layershifter** [comment]
Hey, thanks ❤️ 

***

Under #1739 I did some progress that might help you, you will be able to do:

```jsx
<Modal
  dimmer={{ className: 'foo', onClick: () => console.log('DIMMER CLICK') }}
/>
```

**Comment by xReaven** [comment]
Perfect, so this topic has no longer useful, you may close it.
Just for my information, do you nearly know when it will be released ?

**Comment by layershifter** [comment]
Hope that on next week, I have plan to hack this thing during this week.
