### ISSUE TITLE
Search: Clicking category closes search results

### ISSUE THREAD

**Issue by stevecrozz** [Semantic-Org/Semantic-UI-React#3782]
### Steps
Using Search with categories renders categories that, when clicked, close the search results.

### Expected Result
Clicking on a category should not close the search results.

### Actual Result
Clicking on a category does close the search results.

### Version
0.88.1

![screencast-react semantic-ui com-2019 09 11-12_02_19](https://user-images.githubusercontent.com/133328/64726992-ac231100-d48c-11e9-855f-3e780f29da4c.gif)

**Comment by brianespinosa** [comment]
This is consistent with [Semantic UI implementation of search and categories](https://semantic-ui.com/modules/search.html#category).
