### ISSUE TITLE
The docs (https://react.semantic-ui.com) cause excessive CPU usage in Chrome

### ISSUE THREAD

**Issue by charliematters** [Semantic-Org/Semantic-UI-React#3784]
### Steps
Use Chrome to open the documentation pages for any component which contains examples

### Expected Result
Chrome should not use more CPU than with other similar sites

### Actual Result
According to Chrome's dev tools, the Rendering task "Recalculate Styles" runs continuously. 
After a few moments my laptops fan kicks in and the laptop turns into a heater

### Version
0.88.1

### Screenshot
![image](https://user-images.githubusercontent.com/7063124/64792368-39d82c80-d571-11e9-884e-5a1fd50295f8.png)

**Comment by dwsg15net** [comment]
I have the same problem. Does a lot of renderings and my app goes very slowly.

Any suggestions to resolve this problem?
