### ISSUE TITLE
Adding a Popup to every Label of a Multiple Search Selection

### ISSUE THREAD

**Issue by popemann** [Semantic-Org/Semantic-UI-React#3787]
## Bug Report
I was trying to add a popup for the selected options in a Multiple Search by using the `renderLabel` property of Dropdown. It works fine, except some warnings in browser's console.

### Steps
 My code:
```
const UsersDropdown = ({handleChange, options, onLabelClick}) => {

  const renderLabel = (item, index, defaultLabelProps) => {
    const {active, as, key, onRemove, value} = defaultLabelProps;
    return (
      <Popup
        trigger={
        <Label
        content={item.text}
        active={active}
        as={as}
        key={key}
        onRemove={onRemove}
        value={value}
        />
      }
      >
        <div> Some Content</div>
      </Popup>
    )
  };

  return (
    <Dropdown
      placeholder='Participants'
      name='participants'
      fluid
      multiple
      search
      selection
      options={options}
      onLabelClick={onLabelClick}
      onChange={handleChange}
      renderLabel={renderLabel}
    />
  )
};
```

### Expected Result
It actually works like it's supposed to, except the warnings.

### Actual Result
The first and only first time I try to hover (or click if the pop-up is triggered by a click) over a label inside the dropdown, I get the warnings below, but otherwise, everything works fine. If the popup is not triggered, the warnings won't appear.

<img width="827" alt="Screenshot 2019-09-16 at 18 54 04" src="https://user-images.githubusercontent.com/43407683/64974085-d32a7a00-d8b4-11e9-9542-d52d3ccfa0f6.png">

### Version
^0.88.0

This is my first time posting an issue on github, sorry if I didn't respect some rules or templates, or if I wasn't explicit enough. Thanks!

**Comment by brianespinosa** [comment]
Please ask usage questions on Stackoverflow. We use these issues for tracking bugs.
