### ISSUE TITLE
Menu labels cause sub-menus and items to mis-align

### ISSUE THREAD

**Issue by k-vosswinkel** [Semantic-Org/Semantic-UI-React#3788]
## Bug Report
When using a label on a menu and attaching it to the top of the menu, only the first child of the menu re-sizes its height appropriately. All other children fill the entire height, causing mis-alignment of text, etc...

### Steps
Create a menu with a label and several items or sub-menus e.g.:
```
<Menu inverted attached size="large" className={cx( 'menu' )}>
	<Label attached="top" color="yellow" />
	<Menu.Item name="Home" as={Link} to="/home" />
	<Menu.Item name="Edit" as={Link} to="/edit" />
	<Menu.Menu position="right">
		<Menu.Item name="Logout" onClick={onClick} />
		<Menu.Item name="Reset" onClick={onClick} />
	</Menu.Menu>
</Menu>
```

### Expected Result
A label with menu items aligned under it

### Actual Result
The actual result that happened 💣
The first menu item is aligned correctly and the others are not
<img width="1663" alt="Screen Shot 2019-09-20 at 12 03 10 PM" src="https://user-images.githubusercontent.com/17109714/65341574-ac16c580-db9e-11e9-8c79-22257c03506b.png">

### Version
0.88.1

### Testcase
https://codesandbox.io/embed/semantic-ui-react-856i7

**Comment by Tamiira** [comment]
Hey there :)
It seems like the first menu item (or the first item after the label in general) is somehow treated as first child of the label, thats why only the first item is aligned correctly
![semanticuireact_menu+label](https://user-images.githubusercontent.com/57072200/67639466-349c2a80-f8f0-11e9-9c66-d757bb5eb9ed.PNG)

**Workaround**
You can put your menu items into a container to align them correctly:
https://codesandbox.io/embed/semantic-ui-react-dg01i

![semanticuireact_menu+label_alignedcorrectly](https://user-images.githubusercontent.com/57072200/67639540-226ebc00-f8f1-11e9-93ca-4b5284508aac.PNG)

**Comment by k-vosswinkel** [comment]
Thanks @Tamiira - the workaround is definitely helpful, I just wanted to flag because it seems like we should be able to have more than one child in a menu based off the docs.

**Comment by brianespinosa** [comment]
Hi @k-vosswinkel!

`Label` is technically a valid child of `Menu` when using the subcomponent API. The CSS in Semantic-UI does not know how to deal with that markup.

I am making a guess on what you are trying to achieve from your Codesandbox... but this would be something better achieved by just defining a style directly to the menu to get that top strip of color instead. I forked your example to show this. https://codesandbox.io/s/semantic-ui-react-yhvhq
