### ISSUE TITLE
Reduce bundle size (Gatsby)

### ISSUE THREAD

**Issue by dankarimov** [Semantic-Org/Semantic-UI-React#3796]
## Bug Report
Hi! I'm using SUIR with Gatsby. My gatsby build has semantics components and comments all over the place. In js files, css and index.html. How to strip not needed components(tree shaking)? Should I use webpack, babel? Not quite sure how though. Thank you.

### Expected Result
Reduced bundle size

### Actual Result
![bundle analyze](https://user-images.githubusercontent.com/22293432/65708332-28823a80-e0b0-11e9-83cf-da199f65ae6c.jpg)

**Comment by kscoulter** [comment]
I'm also interested in this answer. @dankarimov did you ever figure this out?

**Comment by dankarimov** [comment]
> I'm also interested in this answer. @dankarimov did you ever figure this out?

Hi! Webpack does tree shaking for javascript by default, if you use ES2015 module syntax (import/export). And for css, I just made a local copy of semantic styles and removed all unused css rules. You can do it with tools like PurgeCSS or by hand. Hope that helps!
