### ISSUE TITLE
Dropdown: Wrong value shown as initial placeholder after search

### ISSUE THREAD

**Issue by ThiefMaster** [Semantic-Org/Semantic-UI-React#3797]
### Steps
- Select an option, e.g. "Belgium". When opening the dropdown again, the placeholder shows that option and it's marked as active. :heavy_check_mark: 
- Now search for another option, e.g. "Australia". Select it or any other option.

### Expected Result
When opening the dropdown again, the placeholder should show the selected option.

### Actual Result
When opening the dropdown again, the placeholder shows the first option from the list. :bomb:

The `value` is correct though.

This bug apparently only happens when you have a controlled component. The Dropdown search example from the docs did not show this issue until I made it a controlled component.

### Version
0.88.1

### Testcase
https://codesandbox.io/s/semantic-ui-example-giqse

**Comment by brianespinosa** [comment]
This issue is not present in SUIR v1.0.0 

Closing as resolved.
