### ISSUE TITLE
handle Popup with ref

### ISSUE THREAD

**Issue by yuritoledo** [Semantic-Org/Semantic-UI-React#3800]
## Feature Request
Support to handle Popup component with ref prop.

### Problem description
Improve DX

### Proposed solution
Something like:
```javascript
const ref = useRef(null)

onClick = () => {
 ref.current.handleOpen()
}

{...}

<Popup
   on='click'
   closeOnDocumentClick
   closeOnPortalMouseLeave
   closeOnTriggerBlur
   ref={ref}
   content={<h1>AE</h1>}
/>
```

**Comment by layershifter** [comment]
You can use `Popup` in controlled mode via `open` prop:

```
const [open, setOpen] = React.useState(false)

const onClick = () => {
  setOpen(true)
}

return <Popup open={open} />
```

So I don't see any reasons to support this type of usage.

**Comment by yuritoledo** [comment]
If I use Popup in controlled state, I lose the following props:
```js
 closeOnDocumentClick
   closeOnPortalMouseLeave
   closeOnTriggerBlur
```

**Comment by layershifter** [comment]
```tsx
const [open, setOpen] = React.useState(false)

const onClick = () => {
  setOpen(true)
}

return <Popup open={open} onClose={() => setOpen(false)} />
```

@yuritoledo you can use `onClose`/`onOpen` callbacks, this should work properly 🐱

**Comment by yuritoledo** [comment]
@layershifter nop.

If popup is controlled, all the `closeOn*` props stop working

tks

**Comment by layershifter** [comment]
Are you sure? Here is an example: https://react.semantic-ui.com/modules/popup/#usage-controlled

Please provide a CodeSandbox with a repro.

**Comment by yuritoledo** [comment]
https://codesandbox.io/s/semantic-ui-example-t2hq5

Yup, i'm sure!

**Comment by layershifter** [comment]
But you don't have there `onClose` handler 😦

**Comment by yuritoledo** [comment]
hmm now everything makes sense :open_mouth:
It works!

Thank you for your patience.
