### ISSUE TITLE
SideBar text align left

### ISSUE THREAD

**Issue by marcopicasso** [Semantic-Org/Semantic-UI-React#3802]
Hi all, i've this two components: 

//Main.jsx

`<Sidebar.Pushable>
          <SideNav
            visible={this.state.visible}
            onHide={() => this.handleOnHide()}
          >
            <FavList
              dataf={this.state.dataf}
              onClick={e => this.handleDeleteFavorite(e)}
            />
          </SideNav>
        <Sidebar.Pusher >
          {/* AppBar */}
          <AppBar onClick={() => this.handleVisibility()} />
          {/* End AppBar */}
          <Grid centered >
            <Segment basic loading={this.state.isLoading} className="segment">
              <MainGrid
                data={this.state.data}
                isLoading={this.state.loading}
                onClick={e => this.handleAddFavorite(e)}
              />
            </Segment>
          </Grid>
        </Sidebar.Pusher>
      </Sidebar.Pushable>`

and 

//Sidebar.jsx

`   <Sidebar
      as={Menu}
      animation="overlay"
      icon="labeled"
      inverted={false}
      vertical
      onHide={() => props.onHide()}
      visible={props.visible}
      width="wide"
      className="sideNav"
    >
      <Menu.Item>
        <Icon name="heart" />
      </Menu.Item>
      {props.children}
    </Sidebar>`

How can i align menu item text left on SideBar component?

**Comment by JfrA** [comment]
No solution for this?
