### ISSUE TITLE
<Popup /> doesn't work if trigger is an imported component

### ISSUE THREAD

**Issue by jscottchapman** [Semantic-Org/Semantic-UI-React#3803]
## Bug Report
<Popup /> doesn't work if trigger is an imported component
### Steps
Create a component.  Import it into a file. Use it as a trigger for the Popup.

### Expected Result
It would trigger the Popup

### Actual Result
It doesn't trigger the Popup

### Version
0.88.1

### Testcase
https://codesandbox.io/embed/gallant-paper-qku43

**Comment by layershifter** [comment]
Duplicate, https://github.com/Semantic-Org/Semantic-UI-React/issues/1902#issuecomment-318444250
