### ISSUE TITLE
Form.Checkbox has wrong style for error label

### ISSUE THREAD

**Issue by jankaifer** [Semantic-Org/Semantic-UI-React#3804]
## Bug Report
Form.Checkbox has weird error label

### Steps
insert `error={['upps']}` into Form.Checkbox props.

### Expected Result
The label should be below the checkbox

### Actual Result
It is nex to the checkbox

### Version
0.88.1

### Testcase
https://codesandbox.io/embed/semantic-ui-bug-minimal-working-example-ss58h

**Comment by Englund0110** [comment]
Example here https://codesandbox.io/embed/semantic-ui-bug-minimal-working-example-ff2wp

**Comment by stephanrotolante** [comment]
@Englund0110 I think setting the check box's display to 'block' will fix this. Depending on what the value of the position property is, will change where error message div will be places in the DOM. If position set to above, then it will be placed afterwards the form element. If set to below, then it will be placed before the form element. Tested it locally and it seems to work,  but with that being said the arrow doesn't point directly on the check box.

**Comment by samrae7** [comment]
Following with what @stephanrotolante is saying, if I set `display: block` on the error label then I can get the error message displaying above. However the pointer doesn't point to the checkbox.

<img width="428" alt="Screenshot 2019-10-19 at 10 54 13" src="https://user-images.githubusercontent.com/4126146/67143117-d58b4580-f25f-11e9-81bc-b0a169124c6c.png">

Should be a fairly easy fix to get it displaying above without fixing the position of the arrow but do we even want that? ( I can't imagine anyone wanting it to display like this)

Do we want to try and fix the pointer at the same time? We would need to know if the field is a checkbox and then apply styling to the error based on that. That's do-able I guess. I just can't imagine much call for that layout either.

Or alternatively leave as is and add a note to the docs here: https://react.semantic-ui.com/collections/form/#states-field-error-label specifying that `pointing: above` and `pointing: below` don't work for checkbox (and presumably radio button)?

**Comment by brianespinosa** [comment]
Hi @JanKaifer 

CSS is not contained in this project. All styles come from the upstream semantic-ui project. These are only React components that render the markup and classnames that work with SUI.

I went to take a look at how a Label works with a Checkbox and we are indeed consistent to how a label would be rendered with SUI as far as the markup is concerned. That being said... you could always compile your own SUI styles from the main project and use them in your project if you do not agree with the styles and display. The CSS in that project is completely themeable. 

There is also the `style` prop that can be applied to individual components if the changes needed are minor.
