### ISSUE TITLE
Dropdown.Search calls clearSearchQuery() on enter key but not on value change

### ISSUE THREAD

**Issue by Shooshte** [Semantic-Org/Semantic-UI-React#3805]
### Problem description
When using the `Dropdown` Component with Search the possibility to search and press enter, or move with arrow keys and press enter exists.

When you select a dropdown item using the keyboard enter key, the search query clears (not suggesting and auto selecting the previously selected item when changing the option again.

When you select a dropdown item using mouse (clicking on an item in the dropdown), the search query is set to the selected item - the Dropdown will suggest the previously selected item when opened the next time and auto select it on blur if another option is not chosen.

I feel this is inconsistent behaviour between two selection types.

### Proposed solution
Either clear the search query every time when a item is chosen, or never clear the search query.

**Comment by brianespinosa** [comment]
Please create a reproducible test case using the supplied Codesandbox link at the bottom of the bug report template.

Closing this report until a reproducible case is provided.
