### ISSUE TITLE
Search: How to make Search autofocus?

### ISSUE THREAD

**Issue by LazyChun** [Semantic-Org/Semantic-UI-React#3808]
I want a autofocus  in Search . How to do it?

**Comment by honzajerabek** [comment]
You can pass custom `Input` component props object to the `Search`'s `input` prop -

https://codesandbox.io/s/semantic-ui-example-96ymq

**Comment by hydrosquall** [comment]
Thanks @honzajerabek , that worked perfectly! I now have that running on https://covidcommitment.org/ .

**Comment by layershifter** [comment]
@honzajerabek shared a proper solution, thanks 👍
