### ISSUE TITLE
'ghost' bottom-border when Divider horizontal used

### ISSUE THREAD

**Issue by edant92** [Semantic-Org/Semantic-UI-React#3809]
## Bug Report

A 'ghost' bottom-border appears when using `Divider` component with horizontal property and containing text:

### Steps

The following component is used.

```
...
<Divider horizontal>or</Divider>
...
```

### Expected Result

![divider_correct](https://user-images.githubusercontent.com/6187226/66741103-012fb980-ee75-11e9-94ee-c4505aa38829.png)

### Actual Result 💣

![divider_broken](https://user-images.githubusercontent.com/6187226/66741116-07259a80-ee75-11e9-95dd-a9f38243a6ac.png)

### Version
```
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^0.88.1",
```
Tested in Firefox and Chrome on Ubuntu.

This can be fixed by adding ```style={{borderBottom: 0}}``` to the component.

**Comment by brianespinosa** [comment]
Please create a reproducible test case using the supplied Codesandbox link at the bottom of the bug report template.

Closing this report until a reproducible case is provided.
