### ISSUE TITLE
Console warnings about renaming of componentWillReceiveProps

### ISSUE THREAD

**Issue by rammanoj** [Semantic-Org/Semantic-UI-React#3811]
I receive the following warning when I use the library for one of my local projects.
![image](https://user-images.githubusercontent.com/21082378/66821036-5f38cb80-ef5f-11e9-9dc9-ba04d9dbacf6.png)

The react library is warning about the usage of ```componentWillReceiveProps``` in components ```Menu```, ```Portal``` and ```Transition```. I guess the method need a replacement right ?

**Comment by layershifter** [comment]
Short-term fix was released in `0.88.0`, so please update. Long-term will be done under #2732.
