### ISSUE TITLE
iPad: unable to delete some characters using backspace on semantic search control while page scroll in iPad

### ISSUE THREAD

**Issue by deepakkamra** [Semantic-Org/Semantic-UI-React#3813]
## Bug Report
iPad: unable to delete some characters using backspace on semantic search control while page scroll in iPad
### Steps
**A clear and concise description of steps to reproduce the problem.**

Create a page with React semantic Grid and Grid Column structure and make the page scroll by applying height or some css (overflow:scroll).
Place some search control with set minCharacters =3 in above page.
Type something while page load, it's working.
Now scroll the page and try to type 8-10 characters  in search control.
Now use backspace and start deleting the characters but when 2 characters (minCharacters ie. 3-1) remains it is now unable to delete the characters.
### Expected Result
Using back space we should be able to delete all the characters and there should not be any lagging while typing

### Actual Result
Now unable to delete the last 2 characters. [ minCharacters defined in this case is 3 and one character less is 2 and it unable to delete the last 2 characters] 💣

### Version
"semantic-ui-react": "0.82.1",
"react": "16.4.1"

**Comment by brianespinosa** [comment]
Please create a reproducible test case using the supplied Codesandbox link at the bottom of the bug report template.

Closing this report until a reproducible case is provided.
