### ISSUE TITLE
Docs warning against npm, still relevant?

### ISSUE THREAD

**Issue by chrisbrainerd** [Semantic-Org/Semantic-UI-React#3815]
There's a line in the contributing docs:

> Note, we use yarn because npm has unfortunately become unreliable. Get it here.

Is there any reason to keep this here? https://github.com/Semantic-Org/Semantic-UI-React/pull/2081 is the PR from when it was added - seems like the only gripe was over lockfiles which are plenty standard and stable these days.

**Comment by layershifter** [comment]
#3816 was merged, closing.
