### ISSUE TITLE
React/Dropdown/Trigger. Click on any dropdown item makes every item styled with font-weight 700 and background color like if all  items selected at the same time.

### ISSUE THREAD

**Issue by bpgusar1** [Semantic-Org/Semantic-UI-React#3820]
### Steps
Just open Dropdown/Trigger in semantic ui react and click on any dropdown item.

### Expected Result
Click on any item make only that item styled.

### Actual Result
Click on any dropdown item makes every item styled with font-weight 700 and background color like if all  items selected at the same time.

### Version
0.88.1

### Screenshots
![image](https://user-images.githubusercontent.com/4145328/67683632-bea4cb80-f9a2-11e9-9e5f-190e2ed346d2.png)

**Comment by brianespinosa** [comment]
Please create a reproducible test case using the supplied Codesandbox link at the bottom of the bug report template.

Closing this report until a reproducible case is provided.
