### ISSUE TITLE
"clipboard check" icon not displaying the same icon as in documentation

### ISSUE THREAD

**Issue by aadhivive** [Semantic-Org/Semantic-UI-React#3823]
## Bug Report
Unable to display the icon as documented. The icon named "clipboard check".

### Steps
1. Add name "clipboard check" to Icon.

### Expected Result
![Screen Shot 2019-10-29 at 11 59 14 AM](https://user-images.githubusercontent.com/1645590/67785427-8ef9d000-fa43-11e9-8913-93ef385a38ec.png)

### Actual Result
![Screen Shot 2019-10-29 at 11 57 28 AM](https://user-images.githubusercontent.com/1645590/67785447-9620de00-fa43-11e9-848d-b73955e4fdac.png)

### Version
0.88.1

**Comment by SandipNirmal** [comment]
Can you provide the exact steps to reproduce? I tried it, it works fine. Please check https://codesandbox.io/s/semantic-ui-example-0e87e.

**Comment by brianespinosa** [comment]
Closing pending reproduction steps as this is validated working by @SandipNirmal
