### ISSUE TITLE
[theming] reduce webpack compile time during developing

### ISSUE THREAD

**Issue by DerekHung** [Semantic-Org/Semantic-UI-React#3826]
Hi Guys, Is there any way to reduce webpack building .less file time?
I followed this article to create my own theme: https://gitter.im/Semantic-Org/Semantic-UI-React
However, every time I modified the .less file it would cause 3~5 minutes rebuild time.
Unfortunately I couldn't use the article's method like: include only component you used. 
Because I use almost all of components.

**Comment by brianespinosa** [comment]
Hi @DerekHung!

None of the LESS files are contained in this library. We only handle the React bindings that render SUI markup. The styles are in either the main SUI project, or related projects under Semantic-Org. If you are looking for **_only_** the LESS files, you may want to ask in the proper repository. https://github.com/Semantic-Org/Semantic-UI-LESS
or 
https://github.com/Semantic-Org/Semantic-UI
