### ISSUE TITLE
Margin b/w "unstackable" group and standard group gets disturbed in mobile screen view

### ISSUE THREAD

**Issue by Puspendert** [Semantic-Org/Semantic-UI-React#3827]
https://react.semantic-ui.com/collections/form/#group-variations-unstackable-group

If `Form` has two groups, one `unstackable` and another standard, then If the screen width is reduced, then the margin between two groups gets very decreased and the borders of each group touch each other. No test code is required since this can be tested from the documentation link provided above.

![Screen Shot 2019-10-31 at 1 40 23 PM](https://user-images.githubusercontent.com/16055344/67929746-0f573700-fbe4-11e9-9a54-5db8afe2e58b.png)

**Comment by brianespinosa** [comment]
Hi @Puspendert!

This does actually appear like a real issue. However... this is an issue in the CSS itself. The markup rendered in SUIR is actually correct. I just checked to be sure. A fix to the CSS is needed, which would need to happen in the [main SUI project here](https://github.com/Semantic-Org/Semantic-UI).

You could resolve this manually by adding the following CSS class to your project:
```
.ui.form .unstackable.fields {
  margin-bottom: 1em;
}
```
