### ISSUE TITLE
Add a guide on how to setup Semantic-UI-React for use in Next.js Application

### ISSUE THREAD

**Issue by trm217** [Semantic-Org/Semantic-UI-React#3828]
### Problem description
While there is a guide on how to set it up in your react application, the guide isn't working on a Next.js Application, due to the different project-structure.

### Proposed solution
Please add a new guide on how to set Semantic-UI-react up for a Next.js application (custom themeing would also be highly appreciated)

**Comment by brianespinosa** [comment]
@trm217 This is a great suggestion. Triaged into good first issue and help wanted. Feel free to open a PR to add this.

**Comment by klee214** [comment]
It seems like no one is working on this, I think I can try!

**Comment by trm217** [comment]
@brianespinosa I am not sure if this would bring such a great benefit after all. The only thing that really differs between installing this in a normal React project and inside a Next.js project is fairly slim. The only thing that could be added, is that inside a Next.js application, the CSS import would have to be done in either _document.js or _app.js. Same goes for Gatsby, where the CSS could either be imported inside the gatsby-browser.js or a default layout component. With this I close the issue. If you believe that this should be included in the docs, please reopen the issue and @ me. I can then add it if you want to.
