### ISSUE TITLE
Keep item in option list in Semantic UI multiple select dropdown after selection

### ISSUE THREAD

**Issue by gangwar1** [Semantic-Org/Semantic-UI-React#3829]
Hi Team,
How can we persist item in option list after selecting the item from options?
Currently the item remove from option list after selecting that item.
I using this multi select drop down with react js 
docs: https://react.semantic-ui.com/modules/dropdown/

Please see below example
https://codesandbox.io/embed/semantic-ui-react-example-xghj2

version details: 
"react": "16.4.1",
"semantic-ui-react": "0.82.1",
---

* Gitter Community Chat: https://gitter.im/Semantic-Org/Semantic-UI-React
* StackOverflow: https://stackoverflow.com/questions/tagged/semantic-ui-react using the tag `semantic-ui-react`
* Also have a look at our docs: http://react.semantic-ui.com

**Comment by Danoctum** [comment]
Have you already found a solution to this? Running into the same problem right now.

**Comment by brianespinosa** [comment]
As far as I can tell from the codesandbox link, when items are selected from both dropdown examples, they stay in the dropdown once selected. The example has "latest" set for all packages, so this might have been an issue but is no longer present in v1.0.0. Closing as resolved based on the provided test case. 

Please comment back with specific reproduction steps if you feel this is still present.
