### ISSUE TITLE
Dropdown: `search` & `selection` allows disabled options to be selected

### ISSUE THREAD

**Issue by camsjams** [Semantic-Org/Semantic-UI-React#3833]
### Steps

1. Create a searchable dropdown, see: [codesandbox](https://codesandbox.io/s/semantic-ui-example-yqlkk)
2. Within the options, mark one as `disabled`
3. Search in the field such that only the disabled item is displayed (in my example above, type the letters `Be` to filter to `Belgium`)
4. Blur the field with a mouse click

### Expected Result
Nothing is selected

### Actual Result
The disabled item is selected in the field

### Version
0.88.1 (also occurs on 0.80.2 where originally discovered)

### Testcase
https://codesandbox.io/s/semantic-ui-example-yqlkk

## Additional Information
This is not necessarily a bug if the developer disables `selectOnBlur`, like so:
```javascript
 <Dropdown
    placeholder="Select Country"
    fluid
    search
    selection
    selectOnBlur={false}
    options={countryOptions}
  />
```

The results of disabling select on blur can be found on this [codesandbox](https://codesandbox.io/s/semantic-ui-example-79ep2)

**Comment by brianespinosa** [comment]
Confirmed that this is reproducible when searching. Triaging to `needs engineering` for now. Thank you for the note on the workaround.

**Comment by tiangueu-cesar** [comment]
I will work on this
