### ISSUE TITLE
CRA - Craco - Custom theme (variables override) is not getting applied

### ISSUE THREAD

**Issue by Vivek205** [Semantic-Org/Semantic-UI-React#3839]
## Bug Report
Custom variables override in `semantic-ui/site/globals/site.variables` is not getting applied in the application
### Steps
A clear and concise description of steps to reproduce the problem.
1. Bootstrap a CRA application.
2. setup Semantic-UI theming using craco.
3. update craco.config and theme.config.
4. override any variable in the semantic-ui . eg. @primaryColor or @red

### Expected Result
The result that you expected.
The custom color should get applied to the application
### Actual Result
The actual result that happened 💣
I'm getting the default styles.

**Comment by layershifter** [comment]
I bootstrapped a sample project recently and followed guide (https://react.semantic-ui.com/theming) step by step. Try to recreate project, it seems that you missed one of steps 🤔 

***

![image](https://user-images.githubusercontent.com/14183168/69261121-4dcb8a80-0bc1-11ea-91e8-94a1fb982faa.png)


```less
@primaryColor: orange;
@pageBackground: red;
```

**Comment by kieransasse** [comment]
@Vivek205 Did you find a solution to your problem? I am having the same issue and am not sure where I went wrong.
