### ISSUE TITLE
Can dropdown be active ? 

### ISSUE THREAD

**Issue by FareedR** [Semantic-Org/Semantic-UI-React#3841]
How can I active dropdown tab , **NOT** dropdown item 
Below example is from official semantic ui
https://codesandbox.io/s/9jcs6?module=/example.js

**Comment by danydhondt** [comment]
yes. With the `open` property. 
`<Dropdown open>`

**Comment by brianespinosa** [comment]
Thanks for the answer @danydhondt

**Comment by FareedR** [comment]
what i meant is active " Display Options " , not its sub item .  
@danydhondt @brianespinosa

**Comment by brianespinosa** [comment]
@FareedR what do you mean by "active"? There is no active prop on a Dropdown. Are you talking about the styles that come with an active menu item? The `open` prop will give you those styles when the `Dropdown` is `open`.

![image](https://user-images.githubusercontent.com/1161781/69351072-531bea00-0c40-11ea-8b65-7ad41e812f21.png)

**Comment by FareedR** [comment]
@brianespinosa ya i talking about the styles . thank you for clarified it .
