### ISSUE TITLE
Show DropDown tags below the DropDown text field, with style

### ISSUE THREAD

**Issue by vdegrandpre** [Semantic-Org/Semantic-UI-React#3842]
## Feature Request

Selected items tags to be shown below the dropdown text field / list.

### Problem description

We need to be able to change the appearance of the selected items in a multi-select dropdown. Instead of having the tags shown IN the textbox we need to show them BELOW, and with some custom style. 

### Proposed solution

Here is a screenshot of what we want to do with the DropDowns : https://images-publiques.s3.amazonaws.com/Capture+d%E2%80%99%C3%A9cran+de+2019-11-19+11-19-06.png

### MVP

What is the way of getting there (?) and if a development is needed, we can achieve it, but we'd need then to know to process to contribute back.

**Comment by brianespinosa** [comment]
@vdegrandpre the current implementation of multi select dropdowns that your screenshot shows is in alignment with how our [parent Semantic UI project has implemented a multi select](https://semantic-ui.com/modules/dropdown.html#multiple-selection). You might be able to achieve the look of what your propose with custom CSS, but that is outside of the scope of this project.

If you feel that the way multi select currently works is incorrect, you could open an issue in the parent Semantic UI repository.
