### ISSUE TITLE
 Invalid argument supplied to oneOfType.

### ISSUE THREAD

**Issue by ivannnnnnnnnn** [Semantic-Org/Semantic-UI-React#3845]
## Bug Report
Warnings 
Warning: Invalid argument supplied to oneOfType. Expected an array of check functions, but received undefined at index 1. index.js:1375
    e index.js:1375
    printWarning factoryWithTypeCheckers.js:26
    createUnionTypeChecker factoryWithTypeCheckers.js:396
    itemShorthand customPropTypes.js:296
    checkPropTypes checkPropTypes.js:62
    React 2
    render UserMeetingsPage.js:59
    React 15
    js index.js:32

When using any component from semantic.

```
"dependencies": {
    "@nivo/bar": "^0.59.2",
    "axios": "^0.19.0",
    "chart.js": "^2.8.0",
    "chartjs-plugin-datalabels": "^0.7.0",
    "mobx": "^5.14.2",
    "mobx-react": "^6.1.4",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "react": "^16.10.2",
    "react-chartjs-2": "^2.8.0",
    "react-dom": "^16.10.2",
    "react-infinite-scroller": "^1.2.4",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.2.0",
    "react-semantic-ui-range": "^0.7.0",
    "semantic-ui-calendar-react": "^0.15.3",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^0.88.1"
  },
```
![изображение](https://user-images.githubusercontent.com/58053056/69381457-789b0900-0cbd-11ea-9b9e-0db483ae4539.png)

**Comment by layershifter** [comment]
It's definitely late, but can you please provide more details or a repro as it's impossible from this description and the stacktrace get a component that causes an issue. Closing for now.
