### ISSUE TITLE
overflow-x of child component is not detected in responsive navbar

### ISSUE THREAD

**Issue by AmirHMousavi** [Semantic-Org/Semantic-UI-React#3849]
Forking the code example of @layershifter  for [responsive (collapsing) navbar](https://codesandbox.io/s/325y47xk36)  I have created [another codesandbox](https://codesandbox.io/s/semantic-ui-react-responsive-navbar-ryrbi?fontsize=14&hidenavigation=1&theme=dark) with a wide table as a child component.

The `minWidth` provided to `Responsive` is `1000px` . The table itself using the `Table` component,  which collapses at a specific resolution (_I assume it is `Responsive.onlyMobile`_) but between these resolutions (_The resolution that navbar collapses till the Table itself collapses_ ), the table has its max shrink and does not shrink anymore and overflow. But as the `Sidebar.Pusher` is shrinking the overflow-x of the table component is not detected therefore any horizontal scrollbar appears to scroll the table.

I could not find any solution to show the browser scrollbar appear when the table overflows.
Is my architecture totally wrong or something I am missing? 

Going through StackOverflow questions and some code samples did not help me.

Any help is highly appreciated.

**Comment by brianespinosa** [comment]
@AmirHMousavi did this question get posted on Stackoverflow? Questions about customizing styling should be posted there and have the best chance for getting help. We use issues on Github for tracking bugs or feature requests. All issues pertaining to styling are almost always going to be out of the scope of this project unless they have to do with incorrect classname resolutions based on props. If you did not ask this question there, I encourage you to post one there. Others may have similar questions and you could help them with your post and getting an answer there.
