### ISSUE TITLE
Input componest is not passing down the JSX attribute inputMode.

### ISSUE THREAD

**Issue by HcDuller** [Semantic-Org/Semantic-UI-React#3850]
## Feature Request
  Implement inputMode on Input Component
### Problem description
I have a input component that needs to be typed as text, but is limited to receive only numbers and a specific set of symbols, I can manage all this very well so far but when a user (mobile) clicks to edit this input the alphabetical keyboard pops up.
I've tried adding patterns, didn't work.

### Proposed solution
  Simplest solution I've came with is to make this component accept a prop just like props.type (as it already does), so it can pass down this attribute to 

### MVP
First time I try this kind of stuff, but i think you might get the idea.
https://github.com/Semantic-Org/Semantic-UI-React/compare/master...HcDuller:patch-1

**Comment by layershifter** [comment]
This is already supported:

```jsx
<Input inputMode="numeric" placeholder="Search..." />
```

Will produce:

```html
<div class="ui input">
  <input type="text" inputmode="numeric" placeholder="Search..." />
</div>
```

---

Oops, support was added in https://github.com/Semantic-Org/Semantic-UI-React/pull/3916 and released in `semantic-ui-react@1.0.0`.
