### ISSUE TITLE
Add "england" prop support to the Flag component

### ISSUE THREAD

**Issue by willwebberley** [Semantic-Org/Semantic-UI-React#3851]
### Problem description

The `.england` class (and alias) is supported for Flag components in the [default Semantic UI theme CSS](https://github.com/Semantic-Org/Semantic-UI-CSS/blob/fc9f8bd7e4f5934756ec60c0423f77d1c7be7c6f/components/flag.css#L303), but is [not exported](https://github.com/Semantic-Org/Semantic-UI-React/blob/72c45080e4f20b531fda2e3e430e384083d6766b/src/elements/Flag/Flag.js#L12) as a name from the `Flag` module.

As a result, the component `<Flag name='england' />` correctly renders the flag, but an "Invalid prop" warning is shown in the console.

### Proposed solution

I propose adding the strings `england` and `gb eng` to the `names` array in [Flag.js](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/elements/Flag/Flag.js) to align the allowed values with the default CSS theme.

### MVP

https://codesandbox.io/s/semantic-ui-react-fbtm4

**Comment by layershifter** [comment]
Good call, will be fixed in #3996 👍
