### ISSUE TITLE
Console errors when I use custom icon name

### ISSUE THREAD

**Issue by DavidAcPosada** [Semantic-Org/Semantic-UI-React#3863]
### Hi guys! 
My problem is simple. I tried use the Icon component with custom names of my icons library, I import my css file with my icon classes and for use of the next way: 

`<Icon name='mv-noty' /> `

But in the console show next error message:

> ```
> Warning: Failed prop type: Invalid prop `name` of value `mv-noty` supplied to `Icon`.
> 
> Instead of `mv-noty`, did you mean:
>   - magnet
>   - magnify
>   - money
> ```

How I can has for resolve this issue?

**Comment by layershifter** [comment]
@DavidAcPosada it's covered in our FAQ section in README, https://github.com/Semantic-Org/Semantic-UI-React#faq

Simply use `<Icon className='mv-noty' />` as it does the same.
