### ISSUE TITLE
Sidebar gives proptype error 

### ISSUE THREAD

**Issue by GGAlanSmithee** [Semantic-Org/Semantic-UI-React#3864]
### Steps
Render a `Sidebar` component, see testcase

### Expected Result
No warnings / errors

### Actual Result
`Warning: Failed prop type: Element is not defined`

### Version
0.88.2

### Testcase
```ts
<Sidebar
    as={Menu}
    inverted
    animation={'overlay'}
    icon={'labeled'}
    vertical
    width={'wide'}
    style={{ background: '#B8254E' }}>
    Content
</Sidebar>
```

**Comment by visakadivines** [comment]
Am encountering the same issue...

**Comment by rlloyd2001** [comment]
Also encountering the same issue.

**Comment by kumarryogeshh** [comment]
Facing same warning.

**Comment by bailinhe** [comment]
Facing same warning.

**Comment by kid-three** [comment]
Same warning

` <Sidebar
      as={Menu}
      animation="overlay"
      onHide={onHide}
      vertical
      visible={isVisible}
      width="wide"
      inverted
      borderless
      className="plr_small"
    >`

**Comment by jaybe78** [comment]
+1 same warning

**Comment by karad** [comment]
+1 same warning

```jsx
<Sidebar
    as={SideBarComponent}
    animation="overlay"
    icon="labeled"
    inverted
    onHide={() => this.setVisible(false)}
    vertical
    visible={this.state.visible}
    width="thin"
>
```

`SideBarComponent` is StyledComponents.

```js
import styled from 'styled-components';

const SideBarComponent = styled.div`
  background-color: #000;
  color: #fff;
`;
```

**Comment by UnsolvedCypher** [comment]
This appears to be caused by the following line in `node_modules/semantic-ui-react/dist/commonjs/modules/Sidebar/Sidebar.js`:

`target: _propTypes["default"].oneOfType([_lib.customPropTypes.domNode, _lib.customPropTypes.refObject]),`

I don't have enough experience with this library to understand what's going on here, but you can comment out this line to silence the warning (obviously not a long-term solution though).

**Comment by NicholasG04** [comment]
Just want to add a +1 to this ongoing issue.

**Comment by walid-farhani** [comment]
Just want to add a +1 to this ongoing issue.

**Comment by vachi** [comment]
Just want to add a +1 to this ongoing issue.

**Comment by brianespinosa** [comment]
Locking this topic from people piling on with +1 comments that do not help resolve anything. If anyone wants to submit a PR to resolve the issue, that would be more helpful than copy pasting a message piling on.

cc @levithomason for visibility in case anyone decides to submit a PR.
