### ISSUE TITLE
Dropdown does not auto-close when inside react-beautiful-dnd

### ISSUE THREAD

**Issue by doguh** [Semantic-Org/Semantic-UI-React#3868]
## Bug Report

Hi there,

I'm not sure if this issue belongs here or at react-beautiful-dnd, but here we go:

I have an issue with Dropdown component not closing itself after chosing an option when put inside react-beautiful-dnd.

### Steps
Create a simple Dropdown like this: `<Dropdown selection options={options} />`

When chosing an option from the select menu, the dropdown automatically closes itself.

But now place the Dropdown component inside a Draggable component (from the react-beautiful-dnd library), and now the Dropdown isn't closed automatically after chosing an option.

You have to click a second time (on another option, or outside the Dropdown) to close it.

### Expected Result
The dropdown should close automatically when clicking an option.

### Actual Result
The dropdown does not close automatically after clicking an option for the first time.

### Version
0.88.2

### Testcase
https://codesandbox.io/s/semantic-ui-react-l813n

**Comment by saaucorp** [comment]
Hey @doguh 
Just add `closeOnChange={true}` to you Dropdown.

`<Dropdown selection options={options} closeOnChange={true} />`

**Comment by doguh** [comment]
Hi @saaucorp , thank you for your answer, but `closeOnChange={true}` does not resolve the problem.

I've added it to the codesandbox above and the Dropdown still doesn't close until a second click.

Also I believe the default value for closeOnChange is true?

I found that if I add `search` prop to the Dropdown, it will now work as expected because `react-beautiful-dnd` disable drag and drop on interactive elements. Maybe this has something to do with react-beautiful-dnd default preventing some events?

**Comment by layershifter** [comment]
@doguh it's extremely hard to find a root reason there, I suggest to open an issue in React DnD repo to find a proper workaround.

What happens? On item click `Dropdown` closes and then it gets focus back and opens again 😨 

https://github.com/Semantic-Org/Semantic-UI-React/blob/40903c29a0592a6cb7060e68a107eeb1446ae84b/src/modules/Dropdown/Dropdown.js#L149-L156

The focus management is definitely done on React DnD side. To workaround it temporary you can use the `openOnFocus=false`: https://codesandbox.io/s/semantic-ui-react-forked-z22g7?file=/index.js. With it works perfectly.

If this is an issue on our side it will be great to get a repro without third party libraries, in this case it will be definitely easier to find it and fix.

Going to close the issue for now for housekeeping. Sorry for the delay in a reply.
