### ISSUE TITLE
onPressEnter event on inputs

### ISSUE THREAD

**Issue by Menci** [Semantic-Org/Semantic-UI-React#3871]
### Problem description
`antd` and `rc-input-number` supports `onPressEnter` on inputs, it makes handling "move focus to next input on enter" easy.

### Proposed solution
Just like this: https://github.com/react-component/input-number/blob/master/src/index.js#L247

If you like I can send a PR :)

**Comment by brianespinosa** [comment]
Hi @Menci thank you for the feature request!

I think this is probably [outside of the scope of the SUIR project at this time](https://github.com/Semantic-Org/Semantic-UI-React/issues/3885#issuecomment-603537041).
