### ISSUE TITLE
CSS File is too Big

### ISSUE THREAD

**Issue by shtengel** [Semantic-Org/Semantic-UI-React#3873]
Hi, i started using Semantic a while ago and its very good i like it, but i have performance problem on loading my ReactJS App.
when i use profilers and check sizes of files most of them always show semantic-ui.min.css as a problem, its 600KB and actually it's big.

i tried looking online for solutions but couldn't find suitable one on how to reduce the size of that css ,
is there a way to import only the css for the Compononets im using ?
or to strip unused css ? (im using Webpack 4)

Thanks!

**Comment by jmcrthrs** [comment]
You can define which components you use when building Semantic UI: https://semantic-ui.com/introduction/build-tools.html#semanticjson

Note this is not part of semantic-ui-react, but semantic-ui: https://semantic-ui.com/
