### ISSUE TITLE
Accessing data and displaying in a dropdown

### ISSUE THREAD

**Issue by newmluser** [Semantic-Org/Semantic-UI-React#3874]
I have data as :

> 
> Rooms.
> Rooms   : {"_id":{"$oid":"46746766474664"},"RoomID":{"$numberInt":"1"},"RoomDesc":"1st Floor"}
> 

I am trying to access and show them in a dropdown.

while mount I am doing this operation.

> 
> mongodb.db("TestDB")
>             .collection("Rooms")
>             .find({}, { limit: 1000 })
>             .asArray()
>             .then(rooms => {
>                 this.setState({ rooms });
>             });

and in searable dropdown,
```

   <Dropdown
                                placeholder='Select Rooms'
                                fluid
                                search
                                selection
                                options={this.state.rooms.RoomID}
                                //value={RoomID}
                            />
```
Its always returning Null no entries. How can I access this data ? should I use Map (or) any other suggestion. Is there a way we can build on console.

From mongodb prompt all results looks Good.
*

**Comment by brianespinosa** [comment]
Please ask this question on Stackoverflow. We use these issues to track bugs. Someone with knowledge of your implementation details will be better suited to give you a helpful answer.
