### ISSUE TITLE
"Module not found" error when enabling custom theming with CRA

### ISSUE THREAD

**Issue by ErwanDL** [Semantic-Org/Semantic-UI-React#3875]
## Bug Report
I followed the steps [from the official documentation](https://react.semantic-ui.com/theming/) to enable custom theming with Create React App, but React will not compile properly because of an unresolved dependency with semantic-ui-less (see actual error message below).

### Steps
Create a CRA, install semantic-ui-react, and then follow the steps to [to enable theming](https://react.semantic-ui.com/theming/) from the official doc, section "Theming with Create React App".

### Expected Result
A semantic-ui/ folder is added under src/ and the React app should still compile, and custom theming should be enabled.

### Actual Result
The semantic-ui/ folder was correctly added under src/, but when trying to compile the development server, the following error message was output :

```
./node_modules/semantic-ui-less/semantic.less (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-8-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--6-oneOf-8-3!./node_modules/semantic-ui-less/semantic.less)

Module not found: Can't resolve './themes/themes/default/assets/fonts/brand-icons.eot' in '/Users/erwan/Documents/Asperteam/asperteam-app/front/node_modules/semantic-ui-less'
```

The './themes/themes/default...' path seems really odd to me and obviously doesn't exist in _node_modules/semantic-ui-less/_, shouldn't it be './themes/default...' ?

### Version
React v.16.12.0
Semantic-ui-react v.0.88.2
Semantic-ui-less v.2.4.1

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by mnvx** [comment]
As I see there is similar problem: #3659
@ErwanDL Did you fix it?

**Comment by mnvx** [comment]
Hm.. I just had return `semantic-ui-css` into package.json again. It helped me.

**Comment by ErwanDL** [comment]
@mnvx sorry for the delay, I actually never managed to fix it and as I was in a rush, decided to use Material-UI instead for my project :/

**Comment by wise-introvert** [comment]
@mnvx, by "adding" you mean you installed `semantic-ui-css` as a dependency? If so, did you import it anywhere in the application?

**Comment by mnvx** [comment]
> @mnvx, by "adding" you mean you installed `semantic-ui-css` as a dependency? If so, did you import it anywhere in the application?

Sorry, it was so long ago, I dont remember.
