### ISSUE TITLE
No option for click through on Rail.

### ISSUE THREAD

**Issue by ftier-tech** [Semantic-Org/Semantic-UI-React#3877]
I'm using a Rail and noticed that any of my buttons "behind" the rail are not clickable.  I was curious if there was some sort of property that could be added or maybe explain to me if I'm doing things wrong so that the buttons on the side where my rail is attached can receive the event.

Thank you!

**Comment by brianespinosa** [comment]
@ftier-tech there is no prop that will implement click events being passed through any SUIR components. Technically the css property `pointer-events: none;` would make all pointer events pass through the element they are applied on. That might not have the effect you want as it will apply to ALL pointer events. If there are any user interactions inside of your component, none of them will work anymore.

Custom styling is outside of the scope of this project... so if you do decide to implement that CSS property and you have further questions on how to fix any problems that arise, please post those to Stackoverflow.
