### ISSUE TITLE
TextArea can't add icon inside

### ISSUE THREAD

**Issue by avillarubia** [Semantic-Org/Semantic-UI-React#3879]
Good day, 
today I found a bug I guess?
or
I this the way textarea should not have icons inside?

## Bug Report
TextArea can't add icon inside

### Steps
I use Form.Fields inside Form
```
            <Form.Field
                id='assignees'
                name='assignees'
                control={TextArea}
                icon='users'
                iconPosition='left'
            />
```

### Expected Result
Icon inside the textarea

### Actual Result
No icon inside text area

### Version
    "react": "^16.8.6",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^0.88.2",

**Comment by brianespinosa** [comment]
Hi @avillarubia! It does not look like this is something Semantic UI supports. At least I cannot find an example of it. Semantic UI React is just a library of React components with compatible markup for styles from Semantic UI. If a pattern is not supported in that library, then we currently have no way of making that happen here.

If you can find an example of support for what you are expecting in the Semantic UI docs, please reply here with a link back to it and we can reopen this issue for you.

**Comment by avillarubia** [comment]
Hello there @brianespinosa , thank you for the response. I am expecting that **TextArea** can also have like this

![image](https://user-images.githubusercontent.com/37901895/72074059-2b85fb80-332c-11ea-861d-2b6e92853cb8.png)

like an Input

**Comment by brianespinosa** [comment]
Hi @avillarubia, I should have been more clear with what I was saying. Thank you for finding an image showing what you are looking for on an input. What I actually mean is if you are able to find an example on the [main Semantic UI docs](https://semantic-ui.com/) that shows a textarea actually using an icon on it the way you would expect, please share a link to that. Apologies for any time you spent finding that image.

Showing how the icon on an input just shows us what we already know is already supported.

**Comment by avillarubia** [comment]
@brianespinosa good day, I guess they have not yet included (if they have a plan to include) this little feature. As you can see [here ](https://react.semantic-ui.com/addons/text-area/#usage-rows), showing all props we can't see icon property for this.
