### ISSUE TITLE
Transition not working with custom components

### ISSUE THREAD

**Issue by Puspendert** [Semantic-Org/Semantic-UI-React#3882]
## Bug Report
`Transition` is not working when the child is a React component of my project. Is does work with HTML elements e.g `div`, `span` etc.

### Steps
Suppose I am having a component `Test` and I want to animation it using `Transition`, it never gets animated.
```
<Transition
          animation="slide right"
          visible={this.state.show2}
          unmountOnHide
 >
     <Test />
</Transition>

const Test = () => {
  return <div>I am here to test Transition on Component</div>;
};
```
Where as animation does work if the child is a HTML element.
```
<Transition animation="slide right" visible={this.state.show1}>
      <div>I am here to test Transition One</div>
</Transition>
```

### Version
Latest

### Testcase
https://codesandbox.io/s/nifty-mccarthy-upxe8

**Comment by neutraali** [comment]
Can confirm as not working for custom components. A relatively serious oversight for our usage.

**Comment by Assadbintahir** [comment]
You need to wrap your custom component in `<Container>`. That works.

```Javascript
import React from "react";
import "./styles.css";
import { Button, Transition, Container } from "semantic-ui-react";

const Test = props => <div>I am here to test Transition on Component</div>;

export default class App extends React.Component {
  state = {
    show1: false,
    show2: false
  };
  render() {
    return (
      <div className="App">
        <Button
          onClick={() =>
            this.setState(prevState => ({ show1: !prevState.show1 }))
          }
          content="Show one"
        />
        <Transition animation="slide right" visible={this.state.show1}>
          <div>I am here to test Transition One</div>
        </Transition>

        {/* Test Component transition */}
        <Button
          onClick={() =>
            this.setState(prevState => ({ show2: !prevState.show2 }))
          }
          content="Show two"
        />
        <Transition animation="slide right" visible={this.state.show2}>
          <Container>
            <Test />
          </Container>
        </Transition>
      </div>
    );
  }
}

```

**Comment by Puspendert** [comment]
It does work with a cost of disturbed CSS 😞. `Container` has `margin-left: 1rem !important` which sets it to `14px` from the border.
Closing as Transition is working now. Just need some hacks over CSS. Thanks

**Comment by Ferezoz** [comment]
This is still not working for me, it shows and hides the component but it doesn't gets animated.

**Comment by Puspendert** [comment]
@ferezoz  plz upload your code here.

**Comment by kjolson12** [comment]
> You need to wrap your custom component in `<Container>`. That works.
> 
> ```js
> import React from "react";
> import "./styles.css";
> import { Button, Transition, Container } from "semantic-ui-react";
> 
> const Test = props => <div>I am here to test Transition on Component</div>;
> 
> export default class App extends React.Component {
>   state = {
>     show1: false,
>     show2: false
>   };
>   render() {
>     return (
>       <div className="App">
>         <Button
>           onClick={() =>
>             this.setState(prevState => ({ show1: !prevState.show1 }))
>           }
>           content="Show one"
>         />
>         <Transition animation="slide right" visible={this.state.show1}>
>           <div>I am here to test Transition One</div>
>         </Transition>
> 
>         {/* Test Component transition */}
>         <Button
>           onClick={() =>
>             this.setState(prevState => ({ show2: !prevState.show2 }))
>           }
>           content="Show two"
>         />
>         <Transition animation="slide right" visible={this.state.show2}>
>           <Container>
>             <Test />
>           </Container>
>         </Transition>
>       </div>
>     );
>   }
> }
> ```

this worked for me

**Comment by layershifter** [comment]
It's the same issue as https://github.com/Semantic-Org/Semantic-UI-React/issues/1187. `Transition` provides some props when clones children, so it's required to spread props:

```jsx
const Test = props => <div {...props}>I am here to test Transition on Component</div>;
```
