### ISSUE TITLE
Doesn't appear you can change icon size/color in dropdown menu?

### ISSUE THREAD

**Issue by ElixirMike** [Semantic-Org/Semantic-UI-React#3883]
I'm using options array to define a list of options for dropdown and using the "icon" property to specify an icon. However, is there a way to allow me to change either the size and/or the color of the icon that is used?

I don't see any obvious way? Any work arounds?

NM...figured it out..

**Comment by yuyoux** [comment]
```
<Dropdown
                    value={"Language"}
                    floating
                    inline
                    options={lans}
                    icon='triangle down'
>
```

add  icon='triangle down' 

or change CSS

```
.dropdown.icon::before {
  color: $UI_main_color;
}
```

**Comment by brianespinosa** [comment]
@ElixirMike the `icon` prop not only accepts a string... it can also accept a component. So you could pass in an `<Icon />` component with all of the props you want on it. OR... even easier would be to pass a shorthand object. This object will create an `<Icon />` component with all of the props mapped to it that are passed down.

![image](https://user-images.githubusercontent.com/1161781/88832185-4b282880-d185-11ea-889b-48918aca740c.png)
