### ISSUE TITLE
Component: Select and Dropdown - cannot get second value

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#3886]
## Bug Report
Create a <Select> or <Dropdown> use an Options 
Example:
```
<Dropdown
          onChange={unitSearch}
          value={selectedUnit}
          options={unitOptions}
        />

const cityOptions= [
  { id: 1, value: 1, name: "New York" },
  { id: 2, value: 2,, label: "Washington" },
  { id: 3, value: 3", label: "Seattle" },
];

const unitSearch = (event, data) => {
    const { name, value, text } = data || event.target;
    console.log("name", name);
    console.log("value", value);
  };

```
### Expected Result
Expect to get name and value.

### Actual Result
Only returns value and name is undefined 💣

**Comment by Assadbintahir** [comment]
@stephyswe 
When using short hand props, Options should be defined with objects of following format.
`{key: ,value: ,text: }`

Please see [this](https://codesandbox.io/s/15cey?module=/example.js) snippet to see how short hand props are supposed to be used.

You will only get `value` at root level inside `onChange` function. You can use that value to find the selected option from `options` array.

Also, specifically for your example, your `onChange` should be like this.

```Javascript
const unitSearch = (event, { value, options } ) => {
  const selectedOption = options.find(elem => elem.value === value);
  const { value: selectedValue, label } = selectedOption;
  console.log(selectedValue, label);
};
```
