### ISSUE TITLE
Hex color codes for multi dropdown

### ISSUE THREAD

**Issue by NLSVTN** [Semantic-Org/Semantic-UI-React#3889]
### Problem description
It seems that you support only several colors that should be named by their regular names in the _multi_ type dropdown:

https://react.semantic-ui.com/elements/label/#variations-colored

Also asked the question on _stackoverflow_:

https://stackoverflow.com/questions/59864548/color-each-selected-dropdown-item-in-react-semantic-ui

However, it is very much needed for me to have _**hex**_ codes color support here. I can't use color translators obviously because there is a very limited number of the color names allowed (if there was a plenty at least, it may have worked out)

### Proposed solution
...

**Comment by brianespinosa** [comment]
@NLSVTN the enumerated color values are not passed directly as named values into CSS. The named values represent available color values that correspond to classnames in the generated CSS that comes from the parent Semantic UI project. Additionally, the build tools for that project allow customization of those colors to any hex, rgb, rgba color you might want.

You can see these color classnames in action if you define a color, you will see a class added with that name, and there will be a corresponding hex color defined for that class.

If you need a different hex color for one of those classes, you could either compile your own CSS theme using the SUI build tools in the parent project, or you could write your own, separate CSS that is more specific. This styling is not handled in the scope of the SUIR project.

**Comment by ony19161** [comment]
@NLSVTN, found a solution for the problem you are having, go to the link
https://stackoverflow.com/questions/59864548/color-each-selected-dropdown-item-in-react-semantic-ui/68651427#68651427
