### ISSUE TITLE
Table with overflow scrolling does not extend 100% parent width

### ISSUE THREAD

**Issue by lucksp** [Semantic-Org/Semantic-UI-React#3890]
## Bug Report
I have requirements to build a table which allows for horizontal & vertical scrolling, rather than making the window itself scroll.

When I create the table without scrolling, the full width & height fills out OK.

When I update the CSS such that there is `display: auto` and have a wide window the table does not fill the parent width.

This issue repeats itself on all tables requiring overflow scrolling of the table.

Is it related to the `tbody {display: table-row-group;}` or `thead {display: table-header-group; }` ??

### Steps
- Create a table with data that will allow for overflowing along X & Y axis.
- add style to the `<Table style={{
            overflow: 'auto',
            display: 'inline-block',
            maxHeight: 'inherit',
          }} />....</Table>`

### Expected Result
- The table width matches the parent.

### Actual Result
- The table content does not expand to 100% width.
- SEE FULL RENDERED SANDBOX: https://smer5.csb.app/
<img width="1397" alt="Semantic UI React Table Bug - CodeSandbox 2020-01-29 14-00-59" src="https://user-images.githubusercontent.com/15162169/73397104-fbcd7200-429f-11ea-9c02-203c68db41f0.png">

- I have tried updating to `width: inherit !important` or `width: 100% !important` but with no change.

### Version
0.88.2

### Testcase
https://codesandbox.io/s/semantic-ui-react-table-bug-smer5

**Comment by brianespinosa** [comment]
@lucksp this is because you are rendering your table inside of a SUIR `<Container />` component. A container has max-width styles associated with it. If you do not want your table to be constrained to the width of a `<Container />` component, render your table outside of that component.
