### ISSUE TITLE
Some Pagination's props should be boolean

### ISSUE THREAD

**Issue by Genarito** [Semantic-Org/Semantic-UI-React#3895]
### Problem description
Some Pagination Component's props like:

- ellipsisItem
- firstItem
- lastItem
- prevItem
- nextItem

Are for abling/disabling features, I think they should be boolean and not `undefined/null` values. Also It could add the possibility of some [React sugar sintax](https://es.reactjs.org/docs/jsx-in-depth.html#props-default-to-true). The definition of the component would be:

```
<Pagination
    ellipsisItem
    prevItem={this.isOnFirstItem()}
    nextItem
/>
```

Which I think It's more readable and clean.

### Proposed solution
Change `undefined` to `true` and `null` to `false`. If you want I could add the changes and make a PR.

Thanks in advance and sorry about my English

**Comment by brianespinosa** [comment]
@Genarito this is a consistent pattern in SUIR for composability. These props are explicitly not boolean. You can pass a React node and render a component directly from that node. You can pass an object and use the SUIR shorthand API which will map that object to child components and props, etc. If these props become boolean, they remove a significant portion of functionality that SUIR provides.

**Comment by Genarito** [comment]
I didn't know! Thanks for the clarification

**Comment by brianespinosa** [comment]
You're welcome! It's a big library with a lot of functionality.
