### ISSUE TITLE
Popup: Context menu Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by andriyboychenko** [Semantic-Org/Semantic-UI-React#3896]
### Steps
We migrated from to version 0.85.0 to 0.88.2 and our context menu stopped working.
Here is how the context menu is implemented: https://codesandbox.io/s/semantic-ui-react-f1k0i

In order to reproduce, please switch the semantic-ui version from 0.85.0 to 0.88.2

### Expected Result
Open a pop-up window when doing right-click on the table header

### Actual Result
JavaScript error
`Uncaught (in promise) TypeError: Cannot read property 'left' of undefined`

### Version
0.88.2

### Testcase
https://codesandbox.io/s/semantic-ui-react-f1k0i

**Comment by camsjams** [comment]
@andriyboychenko This appears to be an issue when the item ref is not easily accessible by Popper, most [commonly when the trigger is wrapped in a styled-component](https://stackoverflow.com/questions/59554870/error-cannot-read-property-left-of-undefined-in-react-semantic-ui-popup-with-s/61106558#61106558).

In your case you might also be able to pass the ref thru to the popup in order for it to work correctly.

**Comment by layershifter** [comment]
That's an interesting use case, I modified CodeSandbox to show how this can be implemented: https://codesandbox.io/s/semantic-ui-react-hui71?file=/index.js

---

With `createRectFromEvent()` you can create a rect for a reference element that can be used by `Popup` and will be passed to `context` prop:

```jsx
<Popup
  context={{
    getBoundingClientRect: () => contextMenuPosition
  }}
/>
```

```jsx
function createRectFromEvent(e) {
  const left = e.clientX;
  const top = e.clientY;
  const right = left + 1;
  const bottom = top + 1;

  return {
    left,
    top,
    right,
    bottom,

    height: 0,
    width: 0
  };
}
```

---

The outcome from this issue will be:
- create a docs example to show how this can be done
- `Popup` component should not throw errors

**Comment by layershifter** [comment]
FYI: in #4026 I merged an example for a context menu, let me if it works for you...
