### ISSUE TITLE
Progress Bar Not Working

### ISSUE THREAD

**Issue by charutiwari04** [Semantic-Org/Semantic-UI-React#3899]
I am using Progress in one of my projects. It is not showing progress bar at all, whereas Label and progress in percentage is shown. While inspecting the element, I can see 
`<div class="bar" style="width=25%"`
but do not see anything on the page. When I apply the styles to .bar class then that style is shown. Need help in that.

**Comment by mattberg88** [comment]
can i see your code for the progress bar?

**Comment by layershifter** [comment]
Please provide a repro on Codesandbox 🙏 
Closing for now.
