### ISSUE TITLE
Enter key handler for Search?

### ISSUE THREAD

**Issue by dw-ll** [Semantic-Org/Semantic-UI-React#3903]
Is there a feature/prop that handles or triggers handleResultSelect with the current input value for the Search module when the enter/return key is pressed? I dove into the code and found selectItemOnEnter and could not figure out how to utilize it.

**Comment by brianespinosa** [comment]
I believe this is a duplicate of #3994 which should be resolved by a recently merged PR.

**Comment by SiOuz** [comment]
Its not on official documentation, but you can do that (you inherit it from base component) :
Works fine for me, with typescript.
```
  onKeyPress={(event: React.KeyboardEvent) => {
    console.log(event.key);
  }}
```
