### ISSUE TITLE
Support CSS Modules

### ISSUE THREAD

**Issue by webciter** [Semantic-Org/Semantic-UI-React#3909]
### Problem description
Semantic UI React does not allow for CSS Modules, allowing CSS Modules encapsulates the style sheets automatically into the head of the page. Without CSS Modules, class name obfuscation is not possible. Obfuscation can be achieved with projects like [laravel-mix-react-css-modules](https://github.com/leinelissen/laravel-mix-react-css-modules). Obfuscation makes automation more difficult. Thus protecting your investment.

### Proposed solution
create a new repo "Semantic-UI-React-CSS-Modules", then progressively switch to CSS Modules.

**Comment by layershifter** [comment]
We don't support CSS implementation in this repo. I suggest to ping folks in https://github.com/fomantic/Fomantic-UI about this, but i don't that it will ever happen.
