### ISSUE TITLE
Dropdown inside Table gets cut by Table border.

### ISSUE THREAD

**Issue by Kumagor0** [Semantic-Org/Semantic-UI-React#3911]
## Bug Report
I need to make horizontally scrollable table that cointains a dropdown in one of its cells.

### Steps
Create table with dropdown in one of its cells, wrap it in a container with a fixed width and overflow-x: auto (or add those attributes to the table itself). Click dropdown.

### Expected Result
Dropdown options are displayed even if they don't fit within table or its container, just the way they behave if table isn't horizontally scrollable (this is also how html select tag behaves).

### Actual Result
Dropdown options get cut by the table border.

### Version
0.88.2

### Testcase
https://codesandbox.io/s/semantic-ui-react-00j85

**Comment by brianespinosa** [comment]
@Kumagor0 the clipping of the dropdown is not due to the default Semantic UI css. It is because you are adding a clipping overflow style to a div that wraps the table. That style will clip everything inside of that div, regardless of if it comes from Semantic UI React or not.
