### ISSUE TITLE
Wrong position of Popup component

### ISSUE THREAD

**Issue by saramorillon** [Semantic-Org/Semantic-UI-React#3917]
### Steps
- Open the documentation page of the Popup component, section "Position"
- Or reproduce the example given in the document in your own project

### Expected Result
The position of the different popups should be correct.

### Actual Result
The position of the **top left** and **top right** one hand, and on the other hand **bottom left** and **bottom right** popups are reverted.

### Version
0.88.2

### Testcase
https://react.semantic-ui.com/modules/popup/#variations-position

### Screenshots

![image](https://user-images.githubusercontent.com/4224278/77584734-9da9bd80-6ee3-11ea-96bb-33f42f31a616.png)

----

![image](https://user-images.githubusercontent.com/4224278/77584761-a7332580-6ee3-11ea-8bcf-c5102bdfd17d.png)

**Comment by brianespinosa** [comment]
@saramorillon taking a look at the way the position class names are implemented and [how they correspond to Semantic UI](https://semantic-ui.com/modules/popup.html#positioning), the positioning is indeed consistent. We rely on the parent SUI project as our source of truth on functionality.
