### ISSUE TITLE
Scrollbar Component

### ISSUE THREAD

**Issue by Stunext** [Semantic-Org/Semantic-UI-React#3918]
## Feature Request

Can you add a scrollbars component like in modal "Scrolling Content" example:

https://react.semantic-ui.com/modules/modal/

**Comment by brianespinosa** [comment]
@Stunext those styled scrollbars are coming from CSS. The CSS that provides that is in the Semantic UI parent project. They are not specifically any sort of DOM nodes or components that could be packaged up and provided.

Additionally... the scope of this project is to provide react bindings for the CSS classnames and styles that come from that parent SUI project.

**Comment by layershifter** [comment]
@brianespinosa is right, styles are coming from CSS. The easiest usage example: https://codesandbox.io/s/quirky-sea-2cchk?file=/example.js

**Comment by Stunext** [comment]
Thanks!
