### ISSUE TITLE
Input: Limiting Numbers

### ISSUE THREAD

**Issue by evg1n** [Semantic-Org/Semantic-UI-React#3926]
## Feature Request
Adding an option to limit number type input.
### Problem description
As per HTML specification for `<input>` tag it parses input to return a valid floating number, including e, E (exponent) [HTML specs](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#floating-point-numbers). In order to sanitize user's input, developers have to implement their own sanitization functions. To see extended discussion see this [thread](https://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in)

### Proposed solution
Adding a prop to prevent exponent symbol would address the issue.
For example: `<Input type={"number"} noExp={true}/>`
I have not yet implemented a tested solution for this.
I see no drawbacks.

Sorry if I missed this was already an issue, but I could not find any.

Thanks!

**Comment by layershifter** [comment]
@evg1n I don't think that this feature is too generic and widely required to be implemented in UI library. For example, Material UI doesn't have it: https://material-ui.com/api/text-field/

The linked thread contains enough solutions to be implemented in your codebase.
