### ISSUE TITLE
Broken example in codesandbox.io for Ribbon Label Type example

### ISSUE THREAD

**Issue by gregfenton** [Semantic-Org/Semantic-UI-React#3927]
### Steps

1. Go to documentation for [Ribbon type labels](https://react.semantic-ui.com/elements/label/#types-ribbon)
1. Click the CodeSandbox link in the top-right corner of the examples segment
1. When the checkmark appears, click it to be taken to CodeSandbox
1. When CodeSandbox loads, notice that the URLs for the <Image> tags have doubled the URL prefix so they are: `<Image src='https://react.semantic-ui.comhttps://react.semantic-ui.com/images/wireframe/paragraph.png' />`
_(NOTE: the double `https://` prefix, making the image source URL invalid)_

### Expected Result
CodeSandbox opens with a working example.

### Actual Result
CodeSandbox opens with broken images.

### Version
Currently published docs on 2020/04/06.

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by JayeshJanyani** [comment]
Hi @gregfenton, did you report a bug for the same. 
If it is not closed, Please share the bug number.

**Comment by gregfenton** [comment]
This was my bug report.

**Comment by layershifter** [comment]
@gregfenton thanks for reporting. I also noticed the same issue 🐛

Fixed in #4010 and will be deployed with the next SUIR version.
