### ISSUE TITLE
Popup: is not rendered when trigger is React.Fragment

### ISSUE THREAD

**Issue by sergii-van** [Semantic-Org/Semantic-UI-React#3928]
### Steps
Popup does not appear when the trigger component is `React.Fragment` (`<>`)

### Expected Result
Popup should be displayed

### Actual Result
Popup does not render

### Version
0.88.2

### Testcase
https://codesandbox.io/s/little-sunset-j0lsf

**Comment by layershifter** [comment]
@sergii-van thanks for reporting, I merged #3998 recently to add meaningful errors. It's impossible to use `React.Fragment` as we `React.cloneElement()` to add props to a passed element to the `trigger` prop.


I also reopened #1187 to consider a better approach than `React.createElement()`.
