### ISSUE TITLE
implement sidebar in react ^16.13.1

### ISSUE THREAD

**Issue by dulangaheshan** [Semantic-Org/Semantic-UI-React#3929]
I tried to implement Dimmed sidebar component as mentioned in [this example](https://react.semantic-ui.com/modules/sidebar/#examples-multiple)

as the example code i installed `@stardust-ui/docs-components` npm package

after i run the react app it shows `Module not found: Can't resolve 'prettier/parser-babylon'` error
so i tried to find solution or npm package to solve that issue i can't find it 

### Version
`"semantic-ui-css": "^2.4.1",`
`"semantic-ui-react": "^0.88.2",`
`"@stardust-ui/docs-components": "^0.40.0",`
`"react": "^16.13.1",`
`"react-dom": "^16.13.1",`

**Comment by wendulem** [comment]
Same thing for me.

**Comment by wendulem** [comment]
I changed prettier/parser-babylon into parser-babel (since that's what's in the prettier directory) but to no avail.

**Comment by tomtom87** [comment]
got the same problem here

**Comment by layershifter** [comment]
I updated examples in #3988 to avoid usage of knobs and replaced them with `React.useState()` calls. As there is no longer dependency on `@stardust-ui/docs-components` you should not have such issues.
