### ISSUE TITLE
Is there any multilevel drill able select/dropdown available?

### ISSUE THREAD

**Issue by debotos** [Semantic-Org/Semantic-UI-React#3930]
I need a multi-level drill able dropdown/select.
If I select one level it will show the nested level.
At the left side of the dropdown/select input, there will be a button/icon to go back(go to previous level)
At the right side of the dropdown/select input, there will be a button/icon to reset level(go to top-level)

If there is noting like that, can anyone suggest any similar kind of react.js component?

Thanks.

**Comment by debotos** [comment]
I composed some UI element and built what I am looking for - https://codesandbox.io/s/multi-level-select-nebbq
Although it would be better if any premade thing exists.

**Comment by brianespinosa** [comment]
Thanks for posting your own follow up answer with an example of some components you used. Closing since we use issues here to track bugs.
