### ISSUE TITLE
<Menu.Item> does not render the name properly.

### ISSUE THREAD

**Issue by cHAuHaNz** [Semantic-Org/Semantic-UI-React#3934]
### Steps
Make a new menu and put some alphanumerical or special characters in the name prop.
It adds black spaces around the number converting next character into UPPERCASE and also omits the special characters and makes the character very next to the symbol in UPPERCASE.

Example:-
```
<Menu>
  <Menu.Item name="Xpl0iter's Name"/>
</Menu>
```
### Expected Result
![image](https://user-images.githubusercontent.com/41383761/79079467-e5767480-7d2c-11ea-8568-adfe426db5a1.png)
![image](https://user-images.githubusercontent.com/41383761/79079479-ff17bc00-7d2c-11ea-8f5e-1218f57a3114.png)

### Actual Result
![image](https://user-images.githubusercontent.com/41383761/79079447-caa40000-7d2c-11ea-9b6b-de882cb0ab81.png)
![image](https://user-images.githubusercontent.com/41383761/79079475-ef987300-7d2c-11ea-9339-fd7e9362919e.png)

### Version
0.88.2

### Testcase
https://codesandbox.io/s/react-semantic-ui-bug-evp20

**Comment by theBstar** [comment]
This issue is raising due to `.startCase` from  [lodash](https://github.com/lodash/lodash/issues/3383) . It is being used in the component. [Here is the exact place in the code. ](https://github.com/Semantic-Org/Semantic-UI-React/blob/2dbab6bec372f3013d4c18448c2600c9d531e378/src/collections/Menu/MenuItem.js#L126).

**Comment by layershifter** [comment]
`name` is unique identifier on item, to provide content please `content` or `children`:

```jsx
    <Menu>
      <Menu.Item content="Ex4mp1e 1" />
      <Menu.Item>Som3 c#4arcter</Menu.Item>
    </Menu>
```

https://github.com/Semantic-Org/Semantic-UI-React/issues/1340#issuecomment-280720627
