### ISSUE TITLE
Back/Forward not working in Semantic Tab with Router

### ISSUE THREAD

**Issue by weignerg** [Semantic-Org/Semantic-UI-React#3935]
There was a previous question asked and an answer provided regarding setting up Routing and Tabs.

The code that was provided had an issue with back/forward navigation

I am wondering if someone else might be able to help understand why the router is not working when back/forward buttons are pressed.

Here is the previous issue/question.
https://github.com/Semantic-Org/Semantic-UI-React/issues/3719

Here is the sample code that has the issue with navigation: https://codesandbox.io/s/react-example-qxb2k

Any help understanding is greatly appreciated.

Thank you,

**Comment by weignerg** [comment]
Does it have something to do with the default active index that is selected from available menuItems? It appears that when this changes, the menuItem information is changing, but the render is not actually rendered...?

**Comment by weignerg** [comment]
I figured out a way to make it work.

Check it out!

https://codesandbox.io/s/react-example-5jtuo?file=/index.js

**Comment by weignerg** [comment]
Unless you can or want to manage the activeIndex for the tabs, set it to -1, or multiple tabs in the menu will stay active when navigating backward and forward.

**Comment by petrosrodinos** [comment]
Any way to achive this using nextjs?
