### ISSUE TITLE
Form.Select (Dropdown) opening behind dimmer

### ISSUE THREAD

**Issue by rafaels-dev** [Semantic-Org/Semantic-UI-React#3940]
## Bug Report
I'm using a dropdown menu positioned above a segment in the page. When the page is loading and showing using Dimmer, the DropDown menu open behind the dimmer. 

### Steps
1. Create a component
2. In the component, put `Field.Select` above `Segment` with active `Dimmer`
3. Open the `Field.Select`

### Expected Result
Users would be able to select any item of Dropdown when Dimmer is active.

### Actual Result
Items of dropdown menu is appearing behind of Dimmer, blocking user's interaction.

### Version
semantic-ui-react 0.88.2
semantic-ui-css 2.4.1

### Testcase
https://codesandbox.io/s/semantic-ui-react-dropdown-behind-dimmer-h55hd?file=/index.js

**Comment by lubber-de** [comment]
Use `simple dimmer` in that particular case. Otherwise you have to adjust the dropdowns z-index to 1001 manually
https://codesandbox.io/s/semantic-ui-react-dropdown-behind-dimmer-lm4dd?file=/index.js

**Comment by rafaels-dev** [comment]
Thank you @lubber-de. I put `<Form.Select style={{ zIndex: 1001 }} />` and worked fine. 
`<Dimmer simple ... >` also is a good suggestion.
