### ISSUE TITLE
Custom radio group

### ISSUE THREAD

**Issue by BrianMwas** [Semantic-Org/Semantic-UI-React#3941]
### Steps
I have tried making the radio group act like a button by styling the label with divs inside it. I did this to achieve a feature like pricing options where the user can select their preferred pricing

### Expected Result
The radio does not click or gets checked with the CSS I use but when I use it the way it is it does not bring any problems

### Actual Result
The radio group can't style into a button

### Version
Latest version as of april

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by brianespinosa** [comment]
Customizing styling is not part of this project. Please ask this question on Stackoverflow and include an example of what you tried.
