### ISSUE TITLE
semantic UI react 0.88.2 Menu & Button

### ISSUE THREAD

**Issue by AliTakrar** [Semantic-Org/Semantic-UI-React#3942]
"semantic-ui-react": "^0.88.2" has this warning with Menu & Button
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

Move data fetching code or side effects to componentDidUpdate.
If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
Please update the following components: Menu

index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of RefFindNode which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
in button (created by Button)
in RefFindNode (created by Ref)
in Ref (created by Button)
in Button (at NavBar.tsx:17)
in div (created by MenuItem)
in MenuItem (at NavBar.tsx:16)
in div (created by Container)
in Container (at NavBar.tsx:10)
in div (created by Menu)
in Menu (at NavBar.tsx:9)
in NavBar (at App.tsx:35)
in div (at App.tsx:34)
in App (at src/index.tsx:9)
in StrictMode (at src/index.tsx:8)

**Comment by tekrarCo** [comment]
its bug

**Comment by tekrarCo** [comment]
its a bug

**Comment by AliTakrar** [comment]
i just install latest version and then all the warning goes away , at the moment i was use "semantic-ui-react": "^0.88.2" and after i install like this:  npm i semantic-ui-react@latest  
package.json didn`t change at all but all the warning goes away

**Comment by BrandonBoone** [comment]
Also getting this issue on v1.0.0

**Comment by layershifter** [comment]
> Warning: Using UNSAFE_componentWillReceiveProps

This was solved

>  Warning: findDOMNode is deprecated in StrictMode

This will be solved later in #3915.
