### ISSUE TITLE
Invalid hook call error if component using hook is inside tab pane

### ISSUE THREAD

**Issue by JanMP** [Semantic-Org/Semantic-UI-React#3943]
## Bug Report
If you put a component containing a react hook into a tab pane you get the dreaded Invalid hook call error.

### Steps
see Testcase

### Expected Result
The component renders fine even if it's in a Tab Pane

### Actual Result
It doesn't

### Version
0.88.2
### Testcase
https://codesandbox.io/s/semantic-ui-react-z0387?file=/index.js

**Comment by melikesofta** [comment]
same issue happening to me when using components with hooks inside `Popup` and `Modal` content

**Comment by layershifter** [comment]
Hey @JanMP, `render()` is just a function that may call something, it's antipattern to have React hooks inside such functions.

However, this can be easily solved: https://codesandbox.io/s/semantic-ui-react-nlohi

```diff
  const panes = [
    {
      menuItem: "Blow up",
-     render: FineOutsideTab,
+      render: () => <FineOutsideTab />
    }
  ];
```

**Comment by layershifter** [comment]
@melikesofta please provide a CodeSandbox with a repro for `Popup`/`Modal`. It's not expected...

**Comment by melikesofta** [comment]
@layershifter my issue was that I was using a local module along with my project; both had semantic-ui-react in requirements and prob react instances were clashing. changed semantic as a peer dependency in the module and issue is resolved.

**Comment by shuieryin** [comment]
> @layershifter my issue was that I was using a local module along with my project; both had semantic-ui-react in requirements and prob react instances were clashing. changed semantic as a peer dependency in the module and issue is resolved.

I got the same problem on local development, I have another repo as shared components with semantic-ui-react as peer dependency, when doing `npm link` <the shared components repo>, it throws the same error only when interacting with the components containing the Confirm/Modal/Popup components

I'm not able to provide the code sandbox example because it only happens when you do `npm link` the shared components repo that uses semantic-ui-react, it's working perfectly fine using the packed version.

Now I can only make one line of code change in the shared components repo, transpile the changed files, and copy and paste to the working repo node_modules for local development, very tedious and frustrating..

**Comment by shuieryin** [comment]
semantics components comes after DataTable.
```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (index.ccd93c2a653ab86f8a40.js:81026)
    at Object.useRef (index.ccd93c2a653ab86f8a40.js:81065)
    at ModalDimmer (index.ccd93c2a653ab86f8a40.js:116972)
    at renderWithHooks (index.ccd93c2a653ab86f8a40.js:106328)
    at mountIndeterminateComponent (index.ccd93c2a653ab86f8a40.js:109007)
    at beginWork (index.ccd93c2a653ab86f8a40.js:110121)
    at HTMLUnknownElement.callCallback (index.ccd93c2a653ab86f8a40.js:91713)
    at Object.invokeGuardedCallbackDev (index.ccd93c2a653ab86f8a40.js:91762)
    at invokeGuardedCallback (index.ccd93c2a653ab86f8a40.js:91817)
    at beginWork$1 (index.ccd93c2a653ab86f8a40.js:114728)
index.ccd93c2a653ab86f8a40.js:111052 The above error occurred in the <ModalDimmer> component:
    in ModalDimmer
    in RefFindNode
    in Ref
    in RefFindNode
    in Ref
    in PortalInner
    in Portal
    in Modal
    in Confirm
    in tbody
    in TableBody
    in table
    in Table
    in div
    in InfiniteScroll
    in div
    in Segment
    in div
    in DataTable
    in div
    in t
    in Page
    in t
    in component
    in Route
    in div
    in div
    in Router
    in Window
    in Application
```
