### ISSUE TITLE
Allow action buttons on left and right of inputs

### ISSUE THREAD

**Issue by aviemet** [Semantic-Org/Semantic-UI-React#3944]
## Feature Request
I would like to be able to add an action button to bot the left and the right of a single input

### Problem description
Currently, we can either leave the `actionPosition` attribute blank for a right aligned action button, or set it to 'left' for a left aligned action button. I would like to have a button on either side with the rounded corners of the button and input elements adjusting accordingly.

### Proposed solution
Perhaps another value to allowed enum on `actionPosition` called 'both' could allow for the correct styles to be applied. Perhaps allowing both 'left' and 'right', with 'right' as an assumed default value, using classes to apply the correct styles.

**Comment by layershifter** [comment]
It's not supported in Semantic UI/Fomantic UI itself, so we can't simply add it to Semantic UI React as we don't own CSS files 😨 

I opened an issue in Fomantic UI, let's see how it will go, https://github.com/fomantic/Fomantic-UI/issues/1609.
