### ISSUE TITLE
Twitter icon is not visible in Chrome 81 and 80

### ISSUE THREAD

**Issue by sjuchno** [Semantic-Org/Semantic-UI-React#3945]
### Steps
Open this code pen in Chrome 81 (latest).
It works in Edge and Opera.
https://codesandbox.io/s/semantic-ui-react-b2vkj
Only twitter icon is not visible.

### Expected Result
All icons should be visible.

### Actual Result
Twitter icon is not visible. Other icons are visible.

### Version
0.88.2

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/semantic-ui-react-b2vkj

**Comment by akkisagiraju** [comment]
I checked the code sandbox URL on Chrome 81. The icon is visible to me. Can you try it again?

<img width="1920" alt="Screenshot 2020-05-18 at 20 50 40" src="https://user-images.githubusercontent.com/7601150/82230446-5a9b2200-9949-11ea-9238-cd1c60039c50.png">

**Comment by sjuchno** [comment]
This is caused by AdBlock. When I turned it off the icon is visible again.
