### ISSUE TITLE
Popup hideOnScroll when pasting in form

### ISSUE THREAD

**Issue by RobbeKeters** [Semantic-Org/Semantic-UI-React#3949]
Hi, 

Recently something strange happened in our code. We use the Semantic React Popup in our text editor so users are able to add an image to their text. We want to hide this popup when they scroll down in the page, so `hideOnScroll` is added to the component. 
Now since the latest Chrome update (83.0.4103.61), whenever we paste a link in the 'src' field, the popup triggers a close. After looking into this further, I saw that the paste-event is now registered as a 'scroll'-event... 

This is likely Google's fault, but I wanted to make sure people new about this via this way.

**Comment by brianespinosa** [comment]
Please create a reproducible test case using the supplied Codesandbox link at the bottom of the bug report template.

Closing this report until a reproducible case is provided.
