### ISSUE TITLE
Bulleted list doesn't render properly in packaged apps

### ISSUE THREAD

**Issue by yarhamjohn** [Semantic-Org/Semantic-UI-React#3951]
### Steps
Add a bulleted list to a React application (`<List bulleted><List.Item /></List>`).

### Expected Result
Expect to see a bulleted list:
![image](https://user-images.githubusercontent.com/7828988/83242155-d55b0d00-a193-11ea-9ffd-a92a376c46ce.png)

### Actual Result
This works for apps in development. It does not work once the app is packaged. The packaged app shows: 
![image](https://user-images.githubusercontent.com/7828988/83242225-f1f74500-a193-11ea-87ab-7738294885e4.png)

In production I can see this in the console:
![image](https://user-images.githubusercontent.com/7828988/83244032-b447eb80-a196-11ea-8f5e-b07eae1cfdcb.png)

but in development it looks like this:
![image](https://user-images.githubusercontent.com/7828988/83244170-e1949980-a196-11ea-8f1a-545c57048860.png)

### Version
0.88.2

### Testcase
n/a this is a bug with a packaged app vs a development app

**Comment by brianespinosa** [comment]
@yarhamjohn those CSS files are not included in this project. Those come from the parent Semantic UI project. SUIR does not do any kind of processing to the CSS files you are using. It only applies SUI class names.

If there are inconsistencies in the CSS you are seeing, it is likely that your build tooling is modifying your CSS in some way. Usually your build system has configuration options to enable source maps that could help you locate where those compiled files are coming from.
