### ISSUE TITLE
How to Prevent Purgecss From Removing SUIR Component Stylings?

### ISSUE THREAD

**Issue by ShawnYcx** [Semantic-Org/Semantic-UI-React#3954]
Hi, I'm using Craco with SUIR for theming, amplify ui css, and custom css in my App. I'm trying to integrate postcss and purgecss to reduce the bundle size of stylesheets but doing that removes all the component stylings from SUIR. Is there a way to prevent that and if i'm not asking at the right place, could someone point me to the right direction?

Here's my `craco.config.js`
```javascript
const purgecss = require("@fullhuman/postcss-purgecss")({
  content: [
    "./src/**/*.html",
    "./src/**/*.tsx",
    "./src/**/*.ts",
    "./public/index.html",
    "node_modules/@aws-amplify/ui/dist/style.css"
  ],
  whitelist: ['node_modules/@semantic-ui-react/craco-less'],
  defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
});

module.exports = {
  style: {
    postcss: {
      plugins: [...(process.env.NODE_ENV === "production" ? [purgecss] : [])],
    },
  },

  plugins: [{ plugin: require("@semantic-ui-react/craco-less") }],
};

```

Thanks!

**Comment by brianespinosa** [comment]
Hi @ShawnYcx 

This question is better asked on Stackoverflow as this really has to do with your build system. Additionally, the CSS is not part of this project.

Webpack configs can be tricky on their own. Using a package for setting up overrides on top of create-react-app carry their own level of complexity.
