### ISSUE TITLE
Cannot test the Modal with react-testing-library and jsdom

### ISSUE THREAD

**Issue by silviubogan** [Semantic-Org/Semantic-UI-React#3959]
### Steps
1. Open [https://codesandbox.io/s/semantic-ui-react-8etbr?file=/index.test.js](https://codesandbox.io/s/semantic-ui-react-8etbr?file=/index.test.js)
2. Select the index.test.js file on the left sidebar
3. Select the Tests tab on the right and press the play all button

### Expected Result
The resulting HTML printed in the Console section at the bottom of the Tests tab contains the contents of the Modal

### Actual Result
In the Console section at the bottom of the Tests tab an empty string is displayed

### Version
0.88.2

### Testcase
https://codesandbox.io/s/semantic-ui-react-8etbr?file=/index.test.js

**Comment by layershifter** [comment]
It's not an of `Modal` component itself.

`Modal` uses `ReactDOM.createPortal()` to render its content to a `document.body` and it seems that there are issues in `react-testing-library` (https://github.com/testing-library/react-testing-library/issues/62). I checked the issue at it seems that there is no resolution for this case. 

At least I check and selectors like `getByText()` work (https://codesandbox.io/s/semantic-ui-react-0oume?file=/index.test.js) as expected.

Please let us know if you will find a proper solution.

**Comment by elkwood** [comment]
The solution of adding `{container: document.body }` as a render option worked for me.
