### ISSUE TITLE
https://twitter.com/login

### ISSUE THREAD

**Issue by azazeyt** [Semantic-Org/Semantic-UI-React#3962]
### Problem description
A clear and concise description of what the problem is. Ex. I have an issue when [...]

### Proposed solution
A clear and concise description of what you want to happen. Add any considered drawbacks.

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
IDK what this means. Please open an issue with properly filled description if it's a case...
