### ISSUE TITLE
Form onSubmit handler omits Select component's value

### ISSUE THREAD

**Issue by evg1n** [Semantic-Org/Semantic-UI-React#3963]
### Steps
When I submit the form, I cannot access the value of `<Form.Select/>`

Please check [codesandbox](https://codesandbox.io/s/react-semantic-ui-form-submit-bug-xrd5f) below.

[Official Example Link](https://react.semantic-ui.com/collections/form/#shorthand-subcomponent-control)

### Expected Result
Below is what I want to achieve.
Check HTMLFormControlsCollection[2], there is a `<select/>` node.
<img width="793" alt="Ekran Resmi 2020-06-13 22 10 09" src="https://user-images.githubusercontent.com/10906736/84577179-b29b3c00-adc2-11ea-99aa-deb48ab82010.png">

### Actual Result
You can see the expected result includes a `HTML Node <select/>` but console output omits `<Form.Select/>` or `<Dropdown selection />` or `<Select/>`. There is no `<select/> `node to be seen.
<img width="1047" alt="Ekran Resmi 2020-06-13 21 51 55" src="https://user-images.githubusercontent.com/10906736/84577151-7536ae80-adc2-11ea-87dd-b53e2e497f19.png">

### Version
[v0.88.2](https://github.com/Semantic-Org/Semantic-UI-React/tree/v0.88.2)

### Testcase
[codesandbox](https://codesandbox.io/s/react-semantic-ui-form-submit-bug-xrd5f)

**Comment by tiangueu-cesar** [comment]
l'll work on this

**Comment by evg1n** [comment]
Thank you @tiangueu-cesar! Sorry for the laaaaaaaaaaate response but glad to see this is resolved.
