### ISSUE TITLE
Tab image/ icon underneath the text

### ISSUE THREAD

**Issue by mygurukool** [Semantic-Org/Semantic-UI-React#3969]
I know Semantic tabs have icon along with the text, but Im looking for a solution with tab image/ icon is underneath tab text, like 
![image](https://user-images.githubusercontent.com/66110311/85630554-23204380-b674-11ea-863b-d2865d3ed55f.png).

is this possible with out of the box, or using custom css ? 

Thanks
--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

* Gitter Community Chat: https://gitter.im/Semantic-Org/Semantic-UI-React
* StackOverflow: https://stackoverflow.com/questions/tagged/semantic-ui-react using the tag `semantic-ui-react`
* Also have a look at our docs: http://react.semantic-ui.com

**Comment by brianespinosa** [comment]
@mygurukool that is not something that the default CSS from Semantic UI does. It would require either compiling your own custom SUI theme using the CSS build tools from the parent repository, or adding your own custom CSS that has a higher specificity than the default styles.

For help trying to customize for your use case, I recommend posting a question on Stackoverflow under the [semantic-ui-react](https://stackoverflow.com/questions/tagged/semantic-ui-react) tag.
