### ISSUE TITLE
Dropdown: fix search type issues

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#397]
### Search Width

The search input resizes on search change.  The search selection multiple dropdown type resizes OK.  The search selection type resizes, but not wide enough.
### Text

When focused, the current value should be shown as the placeholder.  This way, it is greyed out and clear to the user that they can type.  This is also how it works in SUI.  Currently, it remains solid black as if it is the value of the input.

**Comment by dylankiss** [comment]
@levithomason I guess the problem here is that in `handleSearchChange` in `Dropdown.js` you are doing:

```
  handleSearchChange = (e) => {
    ...
    const newQuery = e.target.value
    ...
    // resize the search input, temporarily show the sizer so we can measure it
    let searchWidth
    if (newQuery) {
      const sizer = findDOMNode(this.refs.sizer)
      sizer.style.display = 'inline'
      searchWidth = Math.ceil(sizer.getBoundingClientRect().width)
      sizer.style.removeProperty('display')
    }

    this.setState({
      selectedIndex: 0,
      searchQuery: newQuery,
      searchWidth,
    })
  }
```

However, the new value will be put in that sizer on the next render cycle. So the width will always be the width of the previous search value.

A fix could be to handle this in `componentDidUpdate` and check the searchQuery change there. Drawback is that it adds another render cycle. What are your thoughts on this?

**Comment by levithomason** [comment]
I had suspected this, thanks for finding it.  We just need to set the sizer text to the new query before measuring it.  This can be done with vanilla JS, no extra render needed:

``` diff
  handleSearchChange = (e) => {
    ...
    const newQuery = e.target.value
    ...
    // resize the search input, temporarily show the sizer so we can measure it
    let searchWidth
    if (newQuery) {
      const sizer = findDOMNode(this.refs.sizer)
+     sizer. textContent = newQuery
      sizer.style.display = 'inline'
      searchWidth = Math.ceil(sizer.getBoundingClientRect().width)
      sizer.style.removeProperty('display')
    }

    this.setState({
      selectedIndex: 0,
      searchQuery: newQuery,
      searchWidth,
    })
  }
```

In fact, we should be able to remove the sizer searchQuery text in the sizer render function after having added it in the change handler.

``` diff
  renderSearchSizer = () => {
    const { search } = this.props
-    const { searchQuery } = this.state

-    return !search ? null : <span className='sizer' ref='sizer'>{searchQuery}</span>
+    return !search ? null : <span className='sizer' ref='sizer' />
  }
```
