### ISSUE TITLE
use button warning

### ISSUE THREAD

**Issue by MohsenEs** [Semantic-Org/Semantic-UI-React#3971]
How can I use the button warning feature?
example 
positive = success
negative = danger 
warning ?

**Comment by layershifter** [comment]
There is no support for such state in Semantic UI/Fomantic UI. The closest state that I see is `color=orange`:

![image](https://user-images.githubusercontent.com/14183168/85984710-da58e980-b9e9-11ea-96fc-ac4b05f043ab.png)


```jsx
<Button color='orange' content='Warning' icon='warning' />
```
