### ISSUE TITLE
Are there plans for another release?

### ISSUE THREAD

**Issue by UnsolvedCypher** [Semantic-Org/Semantic-UI-React#3972]
I just wanted to check if there were plans for a release sometime soon. The last one was seven months ago and there have been many changes since then that I would love to take advantage of!

**Comment by brianespinosa** [comment]
@UnsolvedCypher there have only been some new PRs merged in the last week with some updates. I am sure @levithomason will be shipping another update but I do not know what else we will want to include in the release specifically. If you are subscribed to the repo for releases, you'll get a notice when something new goes out.

**Comment by layershifter** [comment]
@UnsolvedCypher Once I will complete #3919 there will be a release to get rid of there warnings.

**Comment by layershifter** [comment]
`semantic-ui-react@1.0.0` was released 🎉
