### ISSUE TITLE
Popup is stuck and not disappearing

### ISSUE THREAD

**Issue by dczii** [Semantic-Org/Semantic-UI-React#3975]
### Steps
1. Hover thru the group of disabled buttons
2. Popup should show upon `onHover`
3. Popup should close upon `onBlur`

### Expected Result
Popup should disappear upon `onBlur` from the container

### Actual Result
Popup got stuck unless you click anywhere

### Version
0.88.2

### Testcase
[Fork, update, and replace this pen to show the bug]:
[codesandbox link](https://codesandbox.io/s/semantic-ui-react-phc06?file=/index.js)

**Comment by layershifter** [comment]
It's a React issue: https://github.com/facebook/react/issues/4251 😭 

***

Workaround is too add a wrapping `div`, https://codesandbox.io/s/semantic-ui-react-o8884

**Comment by dczii** [comment]
> It's a React issue: [facebook/react#4251](https://github.com/facebook/react/issues/4251) 😭
> 
> Workaround is too add a wrapping `div`, https://codesandbox.io/s/semantic-ui-react-o8884

still happens when you hover in the disabled button 😭

**Comment by dczii** [comment]
Tried a workaround by adding a layer on top. Not a good way to do this. but this is the only way to solve it
```
<div
  style={{
  position: "absolute",
  top: 0,
   left: 0
}}
          />
```

**Comment by layershifter** [comment]
Closing this as a workaround exists and it's not an issue in the library itself.
