### ISSUE TITLE
Cannot find module: 'lodash/fp/memoize'

### ISSUE THREAD

**Issue by jjavierdguezas** [Semantic-Org/Semantic-UI-React#3979]
## Bug Report
Hi, thanks for this amazing project
I have a CRA app where I use `"semantic-ui-react": "0.88.1"` I have all my packages version fixed and no `package-lock.json`
Everything was working fine for almost a year, now suddenly the Devops pipeline is broken doing `npm run build`
```sell
$ npm run build

Creating an optimized production build...
Failed to compile.

.\node_modules\semantic-ui-react\dist\es\lib\customPropTypes.js
Cannot find module: 'lodash/fp/memoize'. Make sure this package is installed.

You can install this package by running: npm install lodash/fp/memoize.

```

this is suspicious
![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/13673443/86913220-9c14a600-c11e-11ea-8f88-1a8f6ded3b1f.png)

maybe you should fix versions too
![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/13673443/86913222-9cad3c80-c11e-11ea-8ced-da763318b8a5.png)

### Expected Result
A working project shouldn't break between two `npm run build` without changing something

### Actual Result
The `npm run build` doesn't finish successfully

### Version
0.88.1

**Comment by elias-garcia** [comment]
Same error here...

**Comment by jjavierdguezas** [comment]
for tracking https://github.com/lodash/lodash/issues/4843

**Comment by adifaidz** [comment]
its lodash, they fixed it on v4.17.17. Its working now

**Comment by jjavierdguezas** [comment]
@adifaidz  I dont see any change in lodash repo or npm page, did you tested it?

**Comment by jjavierdguezas** [comment]
I can confirm it is working now (although I dont see any changes in repo nor npm page, maybe cache? )
see the new version here: https://www.npmjs.com/package/lodash/v/4.17.17

closing the issue
