### ISSUE TITLE
Pop-up position not showing as set

### ISSUE THREAD

**Issue by stuthib** [Semantic-Org/Semantic-UI-React#3987]
Bug Report
### Popup position is always left center even when position is set

Steps
<Popup
                trigger={
                  <Input fluid size="large" icon loading={props.isLoading}>
                    <Icon name="search" />
                    <input
                      autoComplete="off"
                      ref={props.saveInputRef}
                      type="text"
                      name="searchUsers"
                      placeholder="Search instruments…"
                      onChange={a => props.search(a.target.value)}
                    />
                  </Input>
                }
                content="Search for a ticker symbol or company name."
                on="focus"
                **position="right center"**
/>
### Expected Result
Popup should show up to the right center of the input and the arrow should point to the left towards the input

### Actual Result
It is on top of the input and arrow points to the right

### Version
0.88.2

**Comment by brianespinosa** [comment]
Please create a reproducible testcase using the supplied codesandbox link at the bottom of the bug report template. 

Closing for now until a reproducible case is provided.
