### ISSUE TITLE
Grid 'device visibility' sizes missing "small screen" size, between tablet and large screen. 

### ISSUE THREAD

**Issue by DeeeeLAN** [Semantic-Org/Semantic-UI-React#3991]
I want to be able to have a specific grid arrangement show up in each screen size, and this one is missing.

**Comment by layershifter** [comment]
Hey, we don't support CSS implementation under this repo, however I created a feature request in Fomantic UI repo: https://github.com/fomantic/Fomantic-UI/issues/1599. If it will be implemented, it will become a part of SUIR.

Closing for now.

**Comment by DeeeeLAN** [comment]
Thanks!
