### ISSUE TITLE
Add sponsor button

### ISSUE THREAD

**Issue by sholladay** [Semantic-Org/Semantic-UI-React#4007]
Hi. If you think that financial contributions would be useful to help push this project forward, would you consider enabling GitHub Sponsors or links to donate?

I use SUIR in production and think it's a very important part of our stack. It helps us be productive every day and I realize that a lot of hard work goes into it. I also realize that there are some difficult unsolved problems here - working with the CSS side of the library has been painful for me, for example, and I know there have been plans to upgrade those parts. I'd like to contribute to these efforts but I don't have much spare time, so it would be great if donating were an option.

**Comment by brianespinosa** [comment]
@sholladay I like the thought... but I suspect that this might not help much, or certainly not enough.

I think @layershifter has [recently weighed in on current bandwidth concerns](https://github.com/Semantic-Org/Semantic-UI-React/issues/3397#issuecomment-665693388).

@levithomason I do not believe has extra time resources to direct here either. Not sure if he would like to weigh in. I at least triaged this to RFC.

**Comment by levithomason** [comment]
This is something I've considered for a while.  I've talked to Jack about it extensively as well, sustainable open source development.

In terms of my continued contributions and maintenance, sponsorship would certainly help.  I think in an ideal utopia, open source developers could just develop all day every day for the benefit of the world wide community and not be bound by the interests of a specific entity (like a day job 😅).

In the absence of 100% full-time open source focus powered by full-time salaries for those devs, I think a good compromise is part-time focus with part-time funding.

I'll take a look at the sponsors and see what it entails.

**Comment by levithomason** [comment]
GitHub's new sponsor features look pretty interesting.  I joined the waitlist and was accepted immediately.  It looks like we'll need to do some thinking and planning on setting up tiers and writing descriptions and what not.  I'll talk to @layershifter and @jlukic about this as well and see what they think as well.

While this is really great and I expect it to transform the open source community over time, I still think it will need to enable open source developers to nearly full time on projects in order to make them successful.  One half of this equation is funding but the other half is time.  Currently, day jobs consume nearly all the available time open source developers have to work on their projects.

In either case, thanks much for this post and looking forward to seeing what we can do with these new tools.

**Comment by sholladay** [comment]
Glad to hear that you're in favor of this. I agree with all of your points - open source sustainability won't happen over night. But this is a major new tool to help the cause. And if it could make even a small difference, I'd still like to contribute.

I think it's plausible for the project to get, say, one hundred sponsors over the next year. The repo has 11k+ stars and a fair amount of engagement from what I can tell. Maybe that would let you take a sabbatical at some point and focus on some of those hard problems before going back to E Corp. 😄

**Comment by levithomason** [comment]
Strangely enough, I've never considered the sabbatical approach. That would be fantastic. We could target X amount of sponsors and Y list of issues/features and then schedule it for a given span of time.  I could see this working out well.  Thanks for the idea.

@layershifter what would you think of this?

**Comment by layershifter** [comment]
> Strangely enough, I've never considered the sabbatical approach. That would be fantastic. We could target X amount of sponsors and Y list of issues/features and then schedule it for a given span of time. I could see this working out well. Thanks for the idea.
> 
> @layershifter what would you think of this?

@levithomason This could work, but as have not ever seen much interest in this.

Closing this for housekeeping...
