### ISSUE TITLE
Support to change Icon in Dropdown Component

### ISSUE THREAD

**Issue by brsanthu** [Semantic-Org/Semantic-UI-React#401]
The DropDown component docs says there is icon prop but specifying as no effect. Looking at the [code](https://github.com/TechnologyAdvice/stardust/blob/master/src/modules/Dropdown/Dropdown.js#L847) it looks like dropdown icon is hardcoded. Changing this to use the icon prop, if specified else default dropdown would be really helpful.

I'm looking to use this component to render More Options menu with three vertical dots.

**Comment by levithomason** [comment]
Indeed, it looks like that should be:

``` diff
-<Icon name={'dropdown'} />
+{createIcon(icon)}
```

I think it should default to `dropdown` rather than being hard coded, which was an error.

Would you like to make a PR?

**Comment by levithomason** [comment]
It looks like this needs more thought.  There is a Dropdown `icon` type: http://semantic-ui.com/modules/dropdown.html#icon

In that type, the Dropdown can take on the classes `labeled icon button`.  In which case the button needs an icon name.

It looks like this is what intended by the `icon` prop currently on the Dropdown.  Though, I'd like to hash over some proposed API examples of how we will support both the Dropdown icon, and the Button icon before making updates.

**Comment by brsanthu** [comment]
Good point. I'm little confused with all the possible combinations of dropdown and popup in Semantic. Don't get me wrong, it is great and has lots of power but it is a challenge in framework like React, where we try to define an API.

To solve this problem now to be able to customize, may be adding a new prop `dropdownIcon` with default value of `dropdown` would solve this problem.

On similar topic (may be this should be a new issue, if so please let me know), is it possible to attach a menu (meaning traditional menu with options, with support for nested options) to any item? If so, then we can just create a icon and attach that menu? May be something like this? 

```
<Menu>
    <Button>
    <Menu.Option.Group>
        <Menu.Option text="New"/>
        <Menu.Option text="Edit"/>
        <Menu.Option text="Delete"/>
        <Menu.Option text="More Options">
            <Menu.Option.Group>
                  <Menu.Option text="Clone"/>
                  <Menu.Option text="Save As"/>
            </Menu.Option.Group>
        </Menu.Option>
    </Menu.Option.Group>
</Menu>
```

or

```
<Menu>
    <Icon>
    <Menu.Option.Group>
    ...
    </Menu.Option.Group>
</Menu>
```

**Comment by levithomason** [comment]
Thanks for the suggestions, I'll try them out when I get some time and report back here.  I'm currently working on Forms over at #400.

## Preliminary Findings

Here is what I gathered yesterday that helped to clarify some things for me:
- There is only ever one icon
- Dropdowns can appear as other components like a _Button_ or a _Menu Item_
- The icon is either a Dropdown icon, Button icon, or Menu Item icon but only one at a time

---

![image](https://cloud.githubusercontent.com/assets/5067638/17745560/1bf44318-6461-11e6-8c03-5e768982108a.png)

![image](https://cloud.githubusercontent.com/assets/5067638/17745386/757ce800-6460-11e6-8f1a-e5d0fa06df2c.png)

![image](https://cloud.githubusercontent.com/assets/5067638/17745403/80ecd402-6460-11e6-832b-45211128a25b.png)

![image](https://cloud.githubusercontent.com/assets/5067638/17745416/89256bfc-6460-11e6-837c-a7621f6a330f.png)

![image](https://cloud.githubusercontent.com/assets/5067638/17745436/96ddf3d6-6460-11e6-8923-0f32e288e5a6.png)

![image](https://cloud.githubusercontent.com/assets/5067638/17745538/014bbbe0-6461-11e6-9c7b-26b0d94144ad.png)

![image](https://cloud.githubusercontent.com/assets/5067638/17745446/9ef17886-6460-11e6-86da-56c7b665f014.png)

![image](https://cloud.githubusercontent.com/assets/5067638/17745527/ee4a9bec-6460-11e6-9737-fea130ab9ae1.png)

![image](https://cloud.githubusercontent.com/assets/5067638/17745534/f44a8d5e-6460-11e6-8f01-01b19d957a8c.png)

## Brainstorming Solutions

Given the above, we may be able to use a single `icon` prop after all.  It would just be applied to as either a Dropdown, Button, or Menu Item icon.

Our offline work going on with Forms may introduce a pattern that is helpful to Dropdowns as well.  We may allow either component augmentation or specialized subcomponents in `Form.Field`s.  This will facilitate our shorthand props API for Forms.  Here are some of the ideas we are playing with:

``` jsx
<Form.Field control='input' type='password' label='Enter password:' />

<Form.Field control={Checkbox} label='I agree to the terms and conditions' />
// or
<Form.Checkbox label='I agree to the terms and conditions' />
```

``` html
<div class="field">
  <label>Enter password:</label>
  <input type='password' />
</div>

<div class="field">
  <Checkbox label='I agree to the terms and conditions' />
</div>
```

There is also a need library wide to explicitly set the element type for a component.  Example, you may want to render a `<Segment />` as an HTML `<section />`.  We are considering a library wide standardized prop such as:

``` jsx
<Segment />
<Segment elementType='section' />
```

``` html
<div class="ui segment"></div>
<section class="ui segment"></section>
```

## Applying it to the Dropdown

All of these ideas are ways of augmenting components.  I have not thought this idea through at all, but it seems like we might support something along the lines of:

``` jsx
<Dropdown icon='filter' options={...} />
<Dropdown.Button labeled icon='settings' options={...} />
<Dropdown.Item icon='dropdown' options={...} />

// or

<Dropdown icon='filter' options={...} />
<Button elementType={Dropdown} labeled icon='settings' options={...} />
<Menu.Item elementType={Dropdown} icon='dropdown' options={...} />
```

The top group `Dropdown.Item` is already taken, so we'd have to solve the name conflict.  

The latter group I think makes more sense.  Consider the Button, all the props are regular button props (labeled, icon, etc) then the extra props (options) are passed to the `Dropdown`.  This would result in a SUI dropdown being rendered with all the props/classes of both the Button and Dropdown.

As I write this, I'm thinking it might help users better understand the augmentation if we use the prop name `as`:

``` jsx
<Button as={Dropdown} labeled icon='settings' options={...} />
<Menu.Item as={Dropdown} icon='dropdown' options={...} />

// or

<Dropdown as={Button} labeled icon='settings' options={...} />
<Dropdown as={Menu.Item} icon='dropdown' options={...} />
```

**Comment by levithomason** [comment]
I'll make a PR to fix the `icon` prop for now, we'll tackle these other features as a separate issue.

**Comment by levithomason** [comment]
See #402 for the fix PR closing this issue. See #403 for continued discussion regarding augmentation and other Dropdown types.

**Comment by levithomason** [comment]
Merged and released in `v0.34.3`, let me know if there are any other issues.

**Comment by brsanthu** [comment]
I just tried and it works great. Thank you for the quick fix.

**Comment by levithomason** [comment]
No problem, thanks for the report and suggestions!

**Comment by annjawn** [comment]
It looks like the `icon` prop has a static hard coded size, is there a way to specify the `icon` size for `Dropdown` as we would do for the `Icon` component?
