### ISSUE TITLE
Dropdown: `search` prop has invalid typings

### ISSUE THREAD

**Issue by charliematters** [Semantic-Org/Semantic-UI-React#4013]
### Steps
Use a dropdown with a default search prop

### Expected Result
That it uses the default search function

### Actual Result
```
Type 'true | ((options: DropdownItemProps[], value: string) => boolean | DropdownItemProps[])' is not assignable to type '(options: DropdownItemProps[], value: string) => boolean | DropdownItemProps[]'.
  Type 'true' is not assignable to type '(options: DropdownItemProps[], value: string) => boolean | DropdownItemProps[]'.ts(2322)
```

### Version
1.1.0

### Testcase
[Before](https://github.com/Semantic-Org/Semantic-UI-React/blob/33b5d5a860d3e27008d498841c282bb8880f8008/src/modules/Dropdown/Dropdown.d.ts):
```
search?: boolean | ((options: DropdownItemProps[], value: string) => DropdownItemProps[])
```

[After](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.d.ts):
```
search?: (options: DropdownItemProps[], value: string) => DropdownItemProps[] | boolean
```

The new type means that you can provide a function, but that function has to return an array of options, or a boolean. Previously, you could provide a boolean (e.g. `<Dropdown search />`) or alternatively a function

**Comment by layershifter** [comment]
@charliematters great report 👍  Would you like to create a PR to fix it?

**Comment by charliematters** [comment]
I will have a go after work!

**Comment by charliematters** [comment]
I raised the PR but it failed at the first hurdle because I forgot to add a label, ad now I can't update it 🤦‍♂️

Anyway, it's there - let me know if it needs updating

**Comment by layershifter** [comment]
> I raised the PR but it failed at the first hurdle because I forgot to add a label, ad now I can't update it 🤦‍♂️

@charliematters no worries, only maintainers can manage labels as we are using them to generate changelogs.
