### ISSUE TITLE
Dropdown "search" property in incorrectly typed

### ISSUE THREAD

**Issue by xumix** [Semantic-Org/Semantic-UI-React#4015]
This commit breaks the typings:
https://github.com/Semantic-Org/Semantic-UI-React/commit/f138b1554659d0a17ac3312f0ab5ecc2b632d50d.

since at the same time in the source it has this propType:
`search: PropTypes.oneOfType([PropTypes.bool, PropTypes.func])`
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js

Worked before: `<Dropdown search/>`, now does not;

How is it actually supposed to be used?

**Comment by layershifter** [comment]
Duplicate of #4013. Was fixed in #4014. Not released yet.

**Comment by xumix** [comment]
Thanks!

**Comment by layershifter** [comment]
@xumix published in `1.1.1`: https://github.com/Semantic-Org/Semantic-UI-React/releases/tag/v1.1.1
