### ISSUE TITLE
Popup: invalid typings for `on` property

### ISSUE THREAD

**Issue by daigof** [Semantic-Org/Semantic-UI-React#4016]
### Steps
Use Popup component and try to use the `on` property as array
` <Popup on={['hover', 'click']}`

It throws TS error: `Type '"hover"' is not assignable to type '"focus"'`

Issue may be with prop declaration:  
```
/** Events triggering the popup. */
on?: 'hover' | 'click' | 'focus' | 'hover' | 'click' | 'focus'[]
```

### Expected Result
Expect to use array form of prop with all permitted values

### Actual Result
Only can use an array of ['focus'] and not any other

### Version
1.1.1

**Comment by layershifter** [comment]
Thanks for reporting 👍 It's the same as #4013 i.e. typings issue 😿 

---

`src/modules/Popup/Popup.d.ts`

```diff
  /** Events triggering the popup. */
-  on?: 'hover' | 'click' | 'focus' | 'hover' | 'click' | 'focus'[]
+  on?: 'hover' | 'click' | 'focus' | ('hover' | 'click' | 'focus')[]
```

And the same for `Visibility`:

`src/behaviors/Visibility/Visibility.d.ts`

```diff
  /**
   * Value that context should be adjusted in pixels. Useful for making content appear below content fixed to the
   * page.
   */
-  offset?: number | string | number | string[]
+  offset?: number | string | (number | string)[]
```


Would you like to a submit a PR to fix the issue? 😺

**Comment by daigof** [comment]
sure will do...

PR opened: https://github.com/Semantic-Org/Semantic-UI-React/pull/4019
