### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by idr4n** [Semantic-Org/Semantic-UI-React#4020]
## Bug Report

I saw this issue being reported before #3810, and it is now closed. However. I'm getting exactly the same warning in an app created with `npx create-react-app`. It also seems like [reactjs/rfcs#97](https://github.com/reactjs/rfcs/pull/97) has been already merged.

**Comment by layershifter** [comment]
Thanks for reporting 👍 

https://github.com/reactjs/rfcs/pull/97 was not merged, it was abandoned. So the only way it to use `React.forwardRef()` everywhere, we are tracking this under #3819.

**Comment by ANAS-AAMMARI** [comment]
> Thanks for reporting 👍
> 
> [reactjs/rfcs#97](https://github.com/reactjs/rfcs/pull/97) was not merged, it was abandoned. So the only way it to use `React.forwardRef()` everywhere, we are tracking this under #3819.

doesn't work for me
