### ISSUE TITLE
Dropdown "defaultValue" typings are incorrect

### ISSUE THREAD

**Issue by xumix** [Semantic-Org/Semantic-UI-React#4022]
### Bug Report
Dropdown "defaultValue" typings are incorrect
Because of this there is no way to preselect multiple string or number values

### Steps
Open Dropdown.d.ts, find `defaultValue` definition

### Expected Result
`defaultValue?: string | number | boolean | number[] | string[] | boolean[]`

### Actual Result
`defaultValue?: string | number | boolean | number | string | boolean[]`

### Version
v. 1.1.1

**Comment by layershifter** [comment]
Thanks for reporting, but this is a duplicate #4017, the fix was not released yet.

**Comment by xumix** [comment]
*sigh
Thanks, will look into closed bugs next time
