### ISSUE TITLE
Fixed Navbar on Mobile View

### ISSUE THREAD

**Issue by jon424** [Semantic-Org/Semantic-UI-React#4025]
Nice template. What would be the best way to go about having fixed position on the navbar in mobile view?

template repo: https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/src/layouts/HomepageLayout.js

**Comment by layershifter** [comment]
@jon424 you can use a `fixed` variation of `Menu` (https://react.semantic-ui.com/collections/menu/#variations-fixed) or combination of `Sticky`/`Visibility` components.

Please consider to use StackOverflow and the tag [`semantic-ui-react`](https://stackoverflow.com/questions/tagged/semantic-ui-react) to raise usage questions. We are using Github issues only to track bugs & features requests.

**Comment by jon424** [comment]
Thanks, this post helped me solve my issue: https://stackoverflow.com/questions/46059637/semantic-ui-react-fixed-sidebar
