### ISSUE TITLE
1.2.0 is missing in CHANGELOG

### ISSUE THREAD

**Issue by swrobel** [Semantic-Org/Semantic-UI-React#4033]

**Comment by layershifter** [comment]
@swrobel thanks for mentioning this 👍 

The changelog generation process is not automated yet. I usually generate them on next day after the release as releases are done by Levi in late evenings for me 🌃 

https://github.com/Semantic-Org/Semantic-UI-React/blob/master/CHANGELOG.md#v120-2020-08-12
https://github.com/Semantic-Org/Semantic-UI-React/releases/tag/v1.2.0
