### ISSUE TITLE
Implement Select All in multiselect dropdown

### ISSUE THREAD

**Issue by chandra-exp** [Semantic-Org/Semantic-UI-React#4038]
Currently from the docs, i do not find an option to select all the items from multi select dropdown. There is an option to clear all however need an option to Select all. WIll this be included or how to implement it? Currently Im developing a react application based on hooks

**Comment by chandra-exp** [comment]
Hi,
I am getting a warning when I use the value prop for my Dropdown multiple selection. I have updated semantic-react-ui to the latest version 1.2 even then I get this and the multiple selection dropdown does not respond:-
Warning: Failed prop type: Invalid prop `value` supplied to `Dropdown`.

**Comment by layershifter** [comment]
@chandra-exp we use Github issues only to track bugs and feature requests. Please raise your question on StackOverflow, we have a dedicated tag there https://stackoverflow.com/tags/semantic-ui-react 😸 Closing for now.

---

`Warning: Failed prop type: Invalid prop value supplied to Dropdown.`

Can you please share a minimal example on CodeSandbox for this?
