### ISSUE TITLE
Support Input component to rendering children

### ISSUE THREAD

**Issue by brsanthu** [Semantic-Org/Semantic-UI-React#404]
The Input component doesn't allow any children to be placed in the div that surrounds it. If we want to extend the input component (in this case, I want to show number of chars typed so far as a span with in the Input component div so I can target sibling selector for input:focus).

If we can allow children just before [closing div](https://github.com/TechnologyAdvice/stardust/blob/master/src/elements/Input/Input.js#L66) would be nice.

**Comment by levithomason** [comment]
The input is a legacy component currently undergoing a complete overhaul to meet our v1 API spec and support all types.  See #281 for that work.  You can see all remaining legacy components in #269.

If you could, please post your use case on that issue so that we can discuss how to support it.

**Comment by brsanthu** [comment]
Thanks, will take a look.

**Comment by levithomason** [comment]
Thanks, to clarify I meant to ask if you could post your use case on the PR updating the input, #281.  Cheers!
