### ISSUE TITLE
Dropdown will close when the search input is focused

### ISSUE THREAD

**Issue by lc-soft** [Semantic-Org/Semantic-UI-React#4045]
### Steps

![Peek 2020-08-25 20-04](https://user-images.githubusercontent.com/1730073/91172134-42882b00-e70e-11ea-9234-4081591818ed.gif)

### Expected Result

Dropdown should open.

### Actual Result

Dropdown closed.

### Version

0.88.2

### Testcase

- https://codesandbox.io/s/vj3f6?module=/example.js
- https://react.semantic-ui.com/modules/dropdown/#types-search-in-menu

**Comment by brianespinosa** [comment]
@lc-soft please update to the latest version. I think this has been resolved there. If still present, reply back and we can reopen.

**Comment by lc-soft** [comment]
> @lc-soft please update to the latest version. I think this has been resolved there. If still present, reply back and we can reopen.

@brianespinosa  It is not resolved, have you followed the steps of gif animation in the Dropdown document page to reproduce this bug? 
https://react.semantic-ui.com/modules/dropdown/#types-search-in-menu

This bug can be reproduced on Chrome and FireFox browsers, I suggest you upload a gif animation to prove that this bug has been fixed.

**Environment:**

OS: Ubuntu 18.04.3 LTS
Chrome 78.0.3904.108 
FireFox 76.0.1

**Comment by layershifter** [comment]
Thanks for the detailed description and filling the issue. This is a duplicate https://github.com/Semantic-Org/Semantic-UI-React/issues/1593#issuecomment-295010142

---

To solve it please use `.stopPropagation()` on `Input`: https://codesandbox.io/s/thirsty-https-bneim?file=/example.js

```tsx
<Input
  icon="search"
  iconPosition="left"
  className="search"
  onClick={e => e.stopPropagation()}
/>
```

**Comment by brianespinosa** [comment]
> @brianespinosa It is not resolved, have you followed the steps of gif animation in the Dropdown document page to reproduce this bug?

@lc-soft nope. We get a LOT of reports on this repository. If we see someone reports an issue from an old version, it is common we will ask for testing again with the latest version first. In the limited time some of us dedicate to open source work, we don't have time to chase down issues on old versions. If it turns out something is still present on the current version, we are always ready to reopen a reported issue, as noted above.
