### ISSUE TITLE
Dropdown text no longer has a `<div class="text">` wrapper if text is an element

### ISSUE THREAD

**Issue by Menci** [Semantic-Org/Semantic-UI-React#4046]
### Steps
1. Create a `Dropdown` and let a item's text be a `<span>`.
2. Select this item.

### Expected Result
The `<span>` should be wrapped by a `<div class="text">`. Just like the previous versions.

### Actual Result
The `<span>` no longer has the wrapper.

This cause my CSS selectors stop working.

### Version
v1.2.1 (Maybe since https://github.com/Semantic-Org/Semantic-UI-React/commit/a2de6cd0e2a68c47ce90b2bf6383572179957c99).

### Testcase
https://codesandbox.io/s/semantic-ui-react-forked-9cxcn?file=/index.js

**Comment by Menci** [comment]
@reefman001

**Comment by layershifter** [comment]
@Menci please update the CodeSandbox to show the issue

**Comment by layershifter** [comment]
I added a repro, https://codesandbox.io/s/musing-sky-3tkdr?file=/example.js
Confirmed bug, will work on a fix. Thanks for reporting 👍

**Comment by Menci** [comment]
Oh I edited and forked, maybe I forgot to "save" the CodeSandbox. Thanks.

**Comment by layershifter** [comment]
@Menci can you please check #4047?

**Comment by Menci** [comment]
I think it's fixed in that PR. Thanks.

**Comment by layershifter** [comment]
Fixed in `semantic-ui-react@1.3.0` 🚢
