### ISSUE TITLE
Have any backTop button can use?

### ISSUE THREAD

**Issue by roberrrrt** [Semantic-Org/Semantic-UI-React#4051]
Hi!
I want to ask if there are any backTop button that can be used？
if there is not can add one?
Thanks you :)))

**Comment by layershifter** [comment]
```jsx
<Button onClick={() => window.scrollTo(0, 0)} />
```

I don't know your use case, but it the simplest thing. Please consider to use StackOverflow for usage questions, we use Github issues only for bugs and feature requests.
