### ISSUE TITLE
Please add github style progress bar

### ISSUE THREAD

**Issue by naveedh27** [Semantic-Org/Semantic-UI-React#4053]
### Problem description
Please add github style progress bar like having multiple text and progress for each. It will be useful incase of having multiple parallel jobs.

![image](https://user-images.githubusercontent.com/8142298/91640882-65804b00-ea3e-11ea-86ce-b217b7fc20bf.png)

**Comment by brianespinosa** [comment]
@naveedh27 thank you for your report.

This project is actually just the React bindings for Semantic UI. We do not create UI components that do not exist in the parent Semantic UI project. You are welcome to open a feature request on the parent repository.
