### ISSUE TITLE
Module parse failed: Unexpected character '@' (11:0)

### ISSUE THREAD

**Issue by Zikoel** [Semantic-Org/Semantic-UI-React#4054]
### Steps
I follow the steps described on the docs:
1. Add the two modules with yarn `yarn add semantic-ui-react semantic-ui-css`
2. Add the css on the app entry file `import 'semantic-ui-css/semantic.min.css'`

### Expected Result
I expect to see semantic ui css applied

### Actual Result
Webpack give me this error:
```
ERROR in ./node_modules/semantic-ui-css/semantic.min.css 11:0
    Module parse failed: Unexpected character '@' (11:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    |  *
    |  */
    > @import url('https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin');
    | /*!
    |  * # Semantic UI 2.4.0 - Reset
     @ ./src/gui/renderer.tsx 13:0-39
```

### Version
"semantic-ui-css": "^2.4.1"
"semantic-ui-react": "^1.2.1"
"webpack": "^4.43.0"

**Comment by brianespinosa** [comment]
@Zikoel this issue has nothing to do with Semantic UI React. It looks like you are trying to process a CSS file with Webpack and do not have the correct loader configured in your `webpack.config.js`. I'd recommend taking a look at your loader rules and see if you have something set up. I'd recommend asking your question on Stackoverflow with a `webpack` tag and including your config file.

Closing since this is not an issue with this library.

**Comment by adwhit** [comment]
While it is true that this error is not to do with `semantic-ui`, it is exactly the error you will get if you already have a webpack build and then follow the instructions to add `semantic-ui-react` as described at https://react.semantic-ui.com/usage. So it might be worth adding a note to the docs.

**Comment by brianespinosa** [comment]
> it is exactly the error you will get if you already have a webpack build and then follow the instructions to add `semantic-ui-react`

The issue does not come from adding `semantic-ui-react`. The issue comes from adding CSS, not part of this repo, and not having your webpack config properly configured yet for handling CSS. This is basic usage for CSS in webpack. Again... there is no CSS in this repo.
