### ISSUE TITLE
sidebar on iphone  isn't working as expected

### ISSUE THREAD

**Issue by moumnimohamed** [Semantic-Org/Semantic-UI-React#4055]
##  i add  filter component to side bar, it work well on all devices . juste on iphone i have this issue

 
![Image from iOS (1)](https://user-images.githubusercontent.com/21304554/92100642-f4d98580-edd3-11ea-91e6-5797bae07438.png)

**Comment by layershifter** [comment]
Please fill the issue template for a bug report and create a repro case. Thanks.
