### ISSUE TITLE
Dropdown generate errors in console

### ISSUE THREAD

**Issue by rafalradomski** [Semantic-Org/Semantic-UI-React#4064]
## Bug Report

![errror](https://user-images.githubusercontent.com/8066536/93330844-54de1c00-f817-11ea-9f5d-07cca68870b9.png)

### Steps
Just use the Dropdown component with the latest version of **Semantic-UI-React** with the latest **react-dom:  16.13.1**

### Expected Result
no errors

### Actual Result
3 warnings in the console

### Version
1.2.1

### Testcase
none

**Comment by layershifter** [comment]
There is no `UNSAFE_*` methods in our code anywhere, they were removed in `1.0.0`.
For `findDOMNode` - it's a real warning, however it's only in `StrictMode`, we have an issue for tracking it #3819.
