### ISSUE TITLE
Fixed table header in case of  x-axis scrollable tables.

### ISSUE THREAD

**Issue by Pa1sathvik** [Semantic-Org/Semantic-UI-React#4067]
## Feature Request

I am using semantic react UI tables , but it doesn't have feature to keep table headers fixed  so that in case  of scrollable i can see the headers with respective to columns / rows data. Requesting to provide fixed table headers in react semantic tables

### Problem description

I am using semantic react UI tables , but it doesn't have feature to keep table headers fixed  so that in case  of scrollable i can see the headers with respective to columns / rows data.

### Proposed solution

When ever scroll is happening ,  i want table headers to be fixed so that we can check which data belongs to what header.

**Comment by brianespinosa** [comment]
Hi @Pa1sathvik 

That is something which could be achieved with CSS sticky customizing on your own. This is not something that the parent Semantic UI Project does, which is our source of truth in this particular project. No styles are contained in Semantic UI React.

Note that you cannot use `sticky` on `<thead>` or `<tr>` tags but you _can_ use it on a `<th>` or `<td>` tag. If you do this on your table header cells, you should get a sticky header:

```
<Table.HeaderCell style={{position: 'sticky', top: 0}}>
```

I believe Safari may still need a vendor prefix for `sticky` so you may want to look into that.

**Comment by Pa1sathvik** [comment]
I have applied the same but still i dont see sticky header in tables in semantic ui.  Do u have any demo example on codesandbox or codepen?

**Comment by brianespinosa** [comment]
@Pa1sathvik you can try this in any of the [Table examples](https://react.semantic-ui.com/collections/table/#types-pagination) in the docs and it works.

**Comment by Pa1sathvik** [comment]
I have added the  style={{position: 'sticky', top: 0}} as you suggested but i can see the hidden content when i keep mouse on the fixed header. same thing with columns also . Content has to be hidden , but i can see it when mouse is on fixed headers / columns.

**Comment by Pa1sathvik** [comment]
Yeah @brianespinosa it worked. Thanks.
