### ISSUE TITLE
White Icon Color

### ISSUE THREAD

**Issue by telubato** [Semantic-Org/Semantic-UI-React#4070]
Hi,

Seems that it´s missing color "white" in Icon

![image](https://user-images.githubusercontent.com/25345398/94206497-772e0480-febd-11ea-95f0-2c2832ece6dc.png)

Can you please add it?
Thank you.

**Comment by layershifter** [comment]
@telubato `white` color is not supported in Semantic UI itself: https://semantic-ui.com/elements/icon.html#/definition

You have two options:
- custom styles
- `inverted`

```tsx
  <div style={{ background: "black", width: 100, height: 50 }}>
    <Icon name="users" inverted />
    <Icon name="users" style={{ color: "white" }} />
  </div>
```

https://codesandbox.io/s/kind-meitner-1vbdx?file=/example.js
