### ISSUE TITLE
[Flag] - There are 2 hidden flags

### ISSUE THREAD

**Issue by rubenprodev** [Semantic-Org/Semantic-UI-React#4077]
## Bug Report
I've post the problem [here](https://github.com/Semantic-Org/Semantic-UI/issues/6926) several time ago.

### Steps

1. Go to https://semantic-ui.com/elements/flag.html
2. Go to Types and see the full flag list.
3. If you count, you get 245 flags.

### Expected Result
We must have the same exact number of flags in the flags.png sprite, which is used for the component (https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/themes/default/assets/images/flags.png)

### Actual Result
Instead, we got 2 more. One of these are the Catalan (Catalonia), which you can see appearing under the Canadian flag (1st col, 36th row). I can't spot the last one.

**Comment by layershifter** [comment]
@rubenpro until it's fixed in upstream i.e. Semantic UI/Fomantic UI there is no sense to fix on our side: if user will try to use these additional values there will no matching CSS for it 🤔 

To workaround it you can always specify it via `className`:

```jsx
<Flag className="cat" />
```

This will produce:

```html
<i class="ae flag"></i>
```

**Comment by rubenprodev** [comment]
> @rubenpro until it's fixed in upstream i.e. Semantic UI/Fomantic UI there is no sense to fix on our side: if user will try to use these additional values there will no matching CSS for it 
> 
> To workaround it you can always specify it via `className`:
> 
> ```js-jsx
> <Flag className="cat" />
> ```
> 
> This will produce:
> 
> ```
> <i class="ae flag"></i>
> ```

This will produce `<i class="flag cat"></i>` instead. But I get the idea. You can't fix it until they already fix it. Thanks
