### ISSUE TITLE
TypeScript - TextArea onChange should provide ChangeEvent event

### ISSUE THREAD

**Issue by foooomio** [Semantic-Org/Semantic-UI-React#4078]
### Steps
1. Use TextArea or Form.TextArea.
2. Pass `(e) => setText(e.target.value)` to its onChange.
3. Get a TypeScript error.

https://github.com/Semantic-Org/Semantic-UI-React/blob/9399332b3930a07ff1874bf1d94b7c8a17e30ca6/src/addons/TextArea/TextArea.d.ts#L17

I think `React.ChangeEvent` is suitable for `onChange`, but `React.FormEvent` is used.

Note: `<textarea onChange={(e) => setText(e.target.value)} />` works well.

### Expected Result
Get no TypeScript errors.

### Actual Result
```tsx
error TS2339: Property 'value' does not exist on type 'EventTarget'.

<Form.TextArea value={text} onChange={(e) => setText(e.target.value)} />
                                                              ~~~~~
```

### Version
1.3.0

### Testcase
https://codesandbox.io/s/semantic-ui-react-textarea-typescript-8wyqz

**Comment by foooomio** [comment]
FYI, `React.ChangeEvent` is used for Input.

https://github.com/Semantic-Org/Semantic-UI-React/blob/9399332b3930a07ff1874bf1d94b7c8a17e30ca6/src/elements/Input/Input.d.ts#L65

**Comment by layershifter** [comment]
@foooomio yep, it should be `ChangeEvent`. Would you like to submit a PR?

BTW, the recommended way is:

```jsx
<Form.TextArea value={text} onChange={(e, data) => setText(data.value)} />
```

**Comment by foooomio** [comment]
I'm new to Semantic UI React, so I didn't know the way!

I'll submit a PR later.
