### ISSUE TITLE
feat(Progress): Progress Bar color

### ISSUE THREAD

**Issue by sebastien-fournier-software-engineer** [Semantic-Org/Semantic-UI-React#4080]
### Problem description
I'm using Progress with React and I want to change the color of the Progress bar to a custom one.
First, when I want a custom color like #74D425, it does not take it into account.
I've checked the code in [Progress.js](https://github.com/Semantic-Org/Semantic-UI-React/blob/aff25ee6d3bbb2c383c9d9a0d62b05a9166e2712/src/modules/Progress/Progress.js#L137) and we have:
` color: PropTypes.oneOf(SUI.COLORS),` which constrains the choice of colors. 
I've tried to remove this typechecking, also tried to use a CSS color code, but it seems the **[cx](https://github.com/Semantic-Org/Semantic-UI-React/blob/aff25ee6d3bbb2c383c9d9a0d62b05a9166e2712/src/modules/Progress/Progress.js#L87)** method used in the **render** of the .js file does not take it. 

### Current Result
The following `<Progress color='red' />` only works with colors like here below: 

```
COLORS = [
  'red',
  'orange',
  'yellow',
  'olive',
  'green',
  'teal',
  'blue',
  'violet',
  'purple',
  'pink',
  'brown',
  'grey',
  'black',
]
```

### Expected solution
`<Progress color=' #74D425' /> ` with **color** being a [CSS color code](https://www.w3schools.com/cssref/css_colors.asp).

**Comment by layershifter** [comment]
We will not implement this feature as for `Progress` it's definitely a single value however for other components that implement `color` can have more complicated CSS rules.

---

I suggest to use CSS om this case to perform overrides:

```css
.ui.progress.my-progress .bar {
  background-color: magenta;
}
.ui.progress.indicating.my-progress .bar {
  background-color: magenta;
} /* only if you're using indicating */
```

```jsx
<Progress className="my-progress" percent={50} />
```

An example on CodeSandbox: https://codesandbox.io/s/sharp-turing-xgd4p?file=/example.js
