### ISSUE TITLE
Resizable columns in Table

### ISSUE THREAD

**Issue by orangecoding** [Semantic-Org/Semantic-UI-React#4081]
### Problem description
I'd like to be able to resize columns like shown here. https://www.brainbell.com/javascript/making-resizable-table-js.html
I'm. not sure if this is already implemented and I just missed it.

**Comment by orangecoding** [comment]
Thanks for not even commenting.

**Comment by brianespinosa** [comment]
![ok](https://media.giphy.com/media/5nzvEcRyntHnW/giphy.gif)
