### ISSUE TITLE
Table: Sorting not working as expected

### ISSUE THREAD

**Issue by Mental1993** [Semantic-Org/Semantic-UI-React#4086]
## Bug Report
Sorting in table does not work as expected
### Steps
I copy and pasted the code from https://react.semantic-ui.com/collections/table/#variations-sortable. Sorting works fine the first time you sort for example name column or when you change column. But the second time you try to sort, it doesn't work

### Expected Result
Sorting should be working, like the example in the docs

### Actual Result
Sorting stops working after the first time.

### Version
2.0.0

### Proposal for fix
Maybe the reducer doesn't like the fact that it's state is manipulated directly (`state.data.reverse()`), so i tried to solve it by
1) using the lodash method for sorting and clone ` data: _.reverse(_.clone(state.data))`
2) without the use of lodash `data: state.data.slice().reverse()`
Both ways seemed to work.

**Comment by tundealuko** [comment]
> ## Bug Report
> Sorting in table does not work as expected
> 
> ### Steps
> I copy and pasted the code from https://react.semantic-ui.com/collections/table/#variations-sortable. Sorting works fine the first time you sort for example name column or when you change column. But the second time you try to sort, it doesn't work
> 
> ### Expected Result
> Sorting should be working, like the example in the docs
> 
> ### Actual Result
> Sorting stops working after the first time.
> 
> ### Version
> 2.0.0
> 
> ### Proposal for fix
> Maybe the reducer doesn't like the fact that it's state is manipulated directly (`state.data.reverse()`), so i tried to solve it by
> 
> 1. using the lodash method for sorting and clone ` data: _.reverse(_.clone(state.data))`
> 2. without the use of lodash `data: state.data.slice().reverse()`
>    Both ways seemed to work.

I have the same problem, and this seems to work for me.

**Comment by layershifter** [comment]
@Mental1993 I don't see the issue in our docs but you're correct: `.reverse()` [mutates an array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse). I like the approach with `.slice()`, would you like to submit a PR?

**Comment by iamsriranga** [comment]
@layershifter, Hey can I work on this.

**Comment by Mental1993** [comment]
@layershifter Will do;)
