### ISSUE TITLE
Uncaught TypeError: predicate is not a function

### ISSUE THREAD

**Issue by Kirsten1996** [Semantic-Org/Semantic-UI-React#4087]
Hi I'm struggling with an error that I've never seen before, I've used this library a couple of times in the exact same way I'm trying to use it now. 

I'm trying to implement a dropdown, here's my code:

<Field
  component={InputSelect}
  name={'qualification_type_id'}
  placeholder={'Qualification'}
  autoComplete="off"
  options={qualifications.map(item => {
    return { text: item.title, value: item.id };
  })}
/>

This is my InputSelect component:

import React from 'react';
import PropTypes from 'prop-types';
import './InputSelect.scss';
import { Dropdown } from 'semantic-ui-react';

const InputSelect = props => {
  const { field, options, form, placeholder } = props;

  return (
    <div
      className={`input-select ${field.value !== '' ? 'content' : ''} ${
        form.errors[field.name] && form.touched[field.name] ? 'error' : ''
      }`}
    >
      <label className={field.value !== '' ? 'content' : ''}>
        {placeholder}
      </label>
      <Dropdown
        onChange={(e, { value }) => form.setFieldValue(field.name, value)}
        name={field.name}
        options={options}
        placeholder={placeholder}
        selection
        search
        fluid
        value={field.value}
      />
    </div>
  );
};

InputSelect.propTypes = {
  field: PropTypes.object,
  children: PropTypes.node,
  form: PropTypes.object,
  placeholder: PropTypes.string,
  options: PropTypes.array,
  submitOnChange: PropTypes.bool,
};

InputSelect.defaultProps = {
  options: [],
};

export default InputSelect;

I get this error 'Uncaught TypeError: predicate is not a function' which I've never seen before, because like I said I've used the exact same code on previous projects. I noticed the minute I take the options out it renders correctly with no issues but the minute I put it back it throughs this error. Please help if anyone has ran into this issue before

I'm using verion 1.0.0 and have also tried 2.0.0 and still no help

* Gitter Community Chat: https://gitter.im/Semantic-Org/Semantic-UI-React
* StackOverflow: https://stackoverflow.com/questions/tagged/semantic-ui-react using the tag `semantic-ui-react`
* Also have a look at our docs: http://react.semantic-ui.com

**Comment by layershifter** [comment]
Closing for housekeeping, will reopen once we will have a repro case.
