### ISSUE TITLE
Button - Labeled Icon - Darken background rotates with icon

### ISSUE THREAD

**Issue by flppv** [Semantic-Org/Semantic-UI-React#4088]
## Bug Report
![image](https://user-images.githubusercontent.com/6984143/95883470-a41a5c80-0d83-11eb-907a-1c4a6607f70c.png)

### Steps
Create a Button with Labeled Icon, and make Labeled Icon rotating with `loading` prop:

```
<Button
  labelPosition="right"
  size="huge"
  icon
>
  Test
  <Icon name="circle notch" loading />
</Button>
```

### Expected Result
I expect background to stay static and only Icon content to be rotated

### Actual Result
Background rotates together with Icon

### Version
2.0.0

### Testcase

https://codesandbox.io/s/elated-framework-kgepn?file=/src/App.js

**Comment by flppv** [comment]
I think I can fix it by myself a bit later tonight, just want to get a confirmation it is considered as a bug, not a feature. 
IMO, need to move rotate animation from `<i>` element to it's child `:before`

**Comment by brianespinosa** [comment]
@flppv Looks like this is definitely an issue... but the CSS that is targeting these elements is not part of SUIR. You can open an issue in the parent SUI project for this. Or you can write some global CSS that overrides those defaults to move it.

**Comment by lubber-de** [comment]
FYI: This is fixed in [Fomantic-UI](https://github.com/fomantic/Fomantic-UI) since 2.7.2
