### ISSUE TITLE
Dropdown with search property inside an inverted Segment has wrong text color in input.search element

### ISSUE THREAD

**Issue by mgstauffer** [Semantic-Org/Semantic-UI-React#4090]
### Steps
Create a `Dropdown` with `search` property within a `Segment` with `inverted `property

```
    <Segment inverted>
      <Dropdown search placeholder="inverted segment" />
    </Segment>

```

### Expected Result
The search box text should have the same inverted color as the dropdown label. 

### Actual Result
The search box does not have the inverted color and is generally unreadable. 
![image](https://user-images.githubusercontent.com/381051/96046436-7d226000-0e41-11eb-9134-6c5700c95356.png)

I can fix it with a hard-coded color with this in my css file

```
.ui.search.dropdown>input.search {
    color: white;
}
```

### Version
2.0.0
1.3.1

### Testcase
https://codesandbox.io/s/semantic-ui-react-forked-62hu2?file=/index.js

**Comment by brianespinosa** [comment]
Hi @mgstauffer !

Unfortunately this is a CSS only issue. This same problem happens on SUI if you combine classes in the same way, so SUIR is accurate in terms of how we are combining classes.

No CSS exists in this repository. I'd recommend seeing if an issue is already opened for this in the parent SUI project and if not, reporting there. Your suggested solution of adding some more CSS to resolve does work and is probably the best solution for now.. Or someone could extend their theme and compile their own CSS with this update if they were using those build tools.

**Comment by mgstauffer** [comment]
That makes sense, I didn't think of that. Thanks, I'll look at the SUI repo.
