### ISSUE TITLE
value in Progress bar has too long percision

### ISSUE THREAD

**Issue by ofirzBM** [Semantic-Org/Semantic-UI-React#4095]
### Steps
A clear and concise description of steps to reproduce the problem.
Pass a value like 0.1*0.2, or for example this snippet from the "Try it" section:
```
import React from 'react'
import { Progress } from 'semantic-ui-react'

const ProgressExampleProgressPercent = () => {
  const x = parseFloat((0.3 * 0.3).toFixed(3));
  return (
    <div>
      <span>{x/5}</span>
  <Progress value={x} total='5' progress='percent' />
  
    </div>
)}

export default ProgressExampleProgressPercent
```

### Expected Result
value should be 0.018 (displayed as as in the <span/>)

### Actual Result
The actual result that happened 💣
1.7999999999999998%

### Version
2.0.0

**Comment by brianespinosa** [comment]
Hello @ofirzBM , 

I am not sure we want to be making these kinds of decisions for people. We do not know everyone's use case for these components. Someone may want to display in that way and we could break the way they are expecting these components to work.

@layershifter @levithomason thoughts?

**Comment by ofirzBM** [comment]
Found to solution...

I used precision attribute
