### ISSUE TITLE
Form.Field input to have the same label format options as Input

### ISSUE THREAD

**Issue by MattSom** [Semantic-Org/Semantic-UI-React#4096]
### Form.Field input to have the same label format options as Input
Using the
```
<Input label='text'/>
```
gives you an input with greyed label section at the left side (by default) of the input field.

But using the 
```
<Form.Field
    control={Input}
    label='text'
 />
```
only gives you the label at the top of the input field, pretty much unconfigurable without complex native CSS.

### Proposed solution
There are multiple different label options for the Input component, but these configurations are not present doing the Form.Field abstraction. Some additional options for the control property would be welcomed to make this available.

**Comment by layershifter** [comment]
`Form.Field` & `Input` have different kinds of `label`, however it's possible to combine them:

![image](https://user-images.githubusercontent.com/14183168/97575394-f0ed6c80-19ec-11eb-8515-c5dec2aec73f.png)

```jsx
<Form>
  <Form.Field>
    <label>User Input</label>
    <Input label="This is a label" labelPosition="right" />
  </Form.Field>
</Form>
```

I don't see the easy way to combine these behaviors without huge breaking changes as both of them are called `label`. As there is a way how to archive this I don't see reasons to perform changes there.
