### ISSUE TITLE
after installing the library with npm react gives me "prototype pollution" vulnerability.

### ISSUE THREAD

**Issue by sparrowV** [Semantic-Org/Semantic-UI-React#4099]
## Bug Report
Greetings,
I followed your instruction on the website and install the library with ``` npm install semantic-ui-react semantic-ui-css```,
but after the installation it give me "prototype pollution" vulnerability. message.

![semantic](https://user-images.githubusercontent.com/29176362/98021081-4bd3f900-1e1d-11eb-94cd-6669d704819d.PNG)

I ran ```npm audit fix``` but it did not solve the problem. What am I supposed to do?

### Steps
run ``` npm install semantic-ui-react semantic-ui-css```

### Expected Result
no vulnerabilities 

### Actual Result
1 vulnerability found

### Version
latest with with npm install

**Comment by layershifter** [comment]
Sorry, but I don't any relationship there to `semantic-ui-react`, `object-path` is not even our dependency.

**Comment by sparrowV** [comment]
@layershifter  ok I will fix that by myself. By the way where can I see component api?(what props component have, etc) . I'm looking smth like this https://material-ui.com/api/accordion/ .

**Comment by layershifter** [comment]
@sparrowV on each component's page there is a toggle to show props:

![image](https://user-images.githubusercontent.com/14183168/98134066-a5d8cb00-1ebe-11eb-94f7-c7a9738baa36.png)

---

Closing as unrelated to our repo.
