### ISSUE TITLE
Sidebar behavior unexpected

### ISSUE THREAD

**Issue by MohamedAlhoony** [Semantic-Org/Semantic-UI-React#4100]
The sidebar gets scrolled out of view when the pusher content is long and doesn't stick to the top of the page.

this is my code

`  return (
        <Sidebar.Pushable as={Segment}>
            <Sidebar
                as={Menu}
                style={{ position: 'sticky' }}
                animation="push"
                icon="labeled"
                inverted
                onHide={() => setVisible(false)}
                vertical
                visible={visible}
                width="thin"
            >
                <Menu.Item as="a">
                    <Icon name="home" />
                    Home
                </Menu.Item>
                <Menu.Item as="a">
                    <Icon name="gamepad" />
                    Games
                </Menu.Item>
                <Menu.Item as="a">
                    <Icon name="camera" />
                    Channels
                </Menu.Item>
            </Sidebar>
            <Sidebar.Pusher>
                <Segment basic>
                    <Header as="h3">Application Content</Header>
                    <Image src="/images/wireframe/paragraph.png" />
                </Segment>
            </Sidebar.Pusher>
        </Sidebar.Pushable>
    )`

**Comment by layershifter** [comment]
Please fill the issue template fully and provide a repro on CodeSandbox.
