### ISSUE TITLE
Hoverable popup closes when mouse moves from popup to trigger

### ISSUE THREAD

**Issue by staniel359** [Semantic-Org/Semantic-UI-React#4101]
### Steps
1. Mouse moves to trigger -> Popup shows
2. Mouse moves to popup -> Popup stays (as it's hoverable)
3. Mouse moves back to trigger -> Popup closes :(

### Expected Result
Hoverable popup is shown if either trigger of popup is hovered.
(Mouse can move from trigger to popup and popup stays open).

### Actual result
Hoverable popup closes when mouse moves from popup to trigger.

### Version
2.0.1

### Testcase
https://codesandbox.io/s/semantic-ui-react-forked-jmvu7?file=/index.js

**Comment by hippo-m** [comment]
Has this problem been solved?
