### ISSUE TITLE
Popup: Wrong Popup placement in IE11

### ISSUE THREAD

**Issue by jschmolling** [Semantic-Org/Semantic-UI-React#4104]
## Bug Report
The popup placement in IE11 seems to be slightly broken.
 
### Steps
1. Navigate to https://react.semantic-ui.com/modules/popup/
2. Hover over any Popup example

### Expected Result
![grafik](https://user-images.githubusercontent.com/50832426/98577377-267f3900-22bc-11eb-88f5-95124a5c3068.png)

### Actual Result
- Popup width and position is wrong
![grafik](https://user-images.githubusercontent.com/50832426/98581557-f3d83f00-22c1-11eb-9a0c-e37d12710861.png)

### Version
Tested with Browserstack: 
Windows 10
Internet Explorer  11.1.17134.0
Semantic UI React 2.0.1
Semantic UI 2.4

### Testcase
https://codesandbox.io/s/semantic-ui-react-hover-example-5qbyu?file=/index.html (Although codesandbox doesn't work with ie11)
I also tested SUIR v1.3.1 and SUI 2.4 which seems to be fine.

**Comment by brianespinosa** [comment]
@jschmolling we do not release patches for old versions of SUIR. If this issue is present in 2.0.1 but is resolved in 2.4, please update to the latest version.

**Comment by layershifter** [comment]
> @jschmolling we do not release patches for old versions of SUIR. If this issue is present in 2.0.1 but is resolved in 2.4, please update to the latest version.

It's about SUIR 😕 The latest release of SUIR is 2.0.1.

I was able to repro it in IE11:
![image](https://user-images.githubusercontent.com/14183168/98707493-6576c280-2380-11eb-930d-cf2686a4c7e8.png)

**Comment by jschmolling** [comment]
I also tested https://semantic-ui.com/modules/popup.html (SUI 2.4) which seems to be fine

**Comment by pentla** [comment]
I also faced to this problem.
This reason seems to be react-popper's bug in Internet Exploer.
Link: https://github.com/popperjs/popper-core/issues/1159

This problem fixed Oct 30, but its newest version is not included in react-popper.
https://github.com/popperjs/react-popper/blob/master/yarn.lock

**Comment by bidy** [comment]
Can this be fixed? Or is there some workaround?

**Comment by brianespinosa** [comment]
It probably will not be fixed. Microsoft is even dropping support for IE11 on all of their online Office and Teams services on August 17, 2021.

**Comment by layershifter** [comment]
> It probably will not be fixed. Microsoft is even dropping support for IE11 on all of their online Office and Teams services on August 17, 2021.

It won't be fixed. v3 will drop IE11 support.
