### ISSUE TITLE
https://react.semantic-ui.com/  is NOT WORKING

### ISSUE THREAD

**Issue by ilanah** [Semantic-Org/Semantic-UI-React#4105]
## Bug Report
The page doesn't succeed to load external resources such as css and js files !

### Steps
A clear and concise description of steps to reproduce the problem.

### Expected Result
The result that you expected.

### Actual Result
The actual result that happened 💣

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Please provide more details, it's working for me and my colleagues.
