### ISSUE TITLE
Portal Memory Leak - Any portal opened remains in memory

### ISSUE THREAD

**Issue by Niallith** [Semantic-Org/Semantic-UI-React#4106]
## Bug Report
Memory Leak with any component using Portal (Popup, Modal, etc...)

### Steps

- With Chrome
- Go to the most basic Portal example
- https://codesandbox.io/s/u3j3w?module=/example.js
- Open the browser link
- https://u3j3w.csb.app/
- Perform an Allocation instrumentation on timeline

![image](https://user-images.githubusercontent.com/1246918/98789884-3bb2af80-2403-11eb-9b14-4c96c97104f3.png)

- Hit Open/Close Portal many times
- Do a Collect garbage then stop recording

![image](https://user-images.githubusercontent.com/1246918/98790023-64d34000-2403-11eb-9591-13a6b5c8cf68.png)

### Expected Result
Should not still have trace of all the portals opened during the record

### Actual Result
Seems like all the portals previously opened remain in memory

### Version
2.0.1

### Testcase
https://codesandbox.io/s/u3j3w?module=/example.js

**Comment by layershifter** [comment]
Thanks for reporting, but I haven't seen anything related to SUIR in snapshots, there is also no detached elements.

Few insights from our previous memory investigations:
- use production builds with unminified symbols, for example `react-scripts build --profile` as CodeSandbox can have own leaks
- press multiple times on garbage collector 👍 

I captured two snapshots:
![image](https://user-images.githubusercontent.com/14183168/98806229-28124380-2419-11eb-9314-fdc1a794e1fe.png)
![image](https://user-images.githubusercontent.com/14183168/98806267-33656f00-2419-11eb-8843-7ba81db5c24e.png)

The single difference that I can see, it's growing amount of `HTML*Element`. The single visible reference that I can find points to React internals and `FiberNode` (it can be visible on unminified builds):

![image](https://user-images.githubusercontent.com/14183168/98806375-64de3a80-2419-11eb-9191-a0fc9008149f.png)

This looks related to https://github.com/facebook/react/issues/16087 (see https://github.com/facebook/react/issues/16087#issuecomment-697954681) and a missing cleanup of FIbers https://github.com/facebook/react/pull/18690. We also met this issue in [Fluent UI](https://github.com/microsoft/fluentui).

--- 

Please correct me if I am wrong or missed something 🤔

**Comment by Niallith** [comment]
Probably sure it's not related to semantic-react. It's strange you can't reproduce though 😢 

I did more test with a production build, just using the PortalExamplePortal  from semantic-react documentation
https://react.semantic-ui.com/addons/portal/#types-portal

I took those snapshots after opening/closing 30 Portal and I did hit collect garbage many times before 😄 
![image](https://user-images.githubusercontent.com/1246918/98810220-2a779c00-241f-11eb-959f-06b587e0fee0.png)

I did a record performance/memory also:
Opening/closing Portals about 20 times, garbage collect, did this 3 times and got this result:
![image](https://user-images.githubusercontent.com/1246918/98810717-e933bc00-241f-11eb-94dd-3aa11051c342.png)

**Comment by Niallith** [comment]
For example, I reproduce the same thing on Totoro (popup rating example), which create a Portal too.
If you hover/leave many times, the memory uses keep increasing in chrome (shift+escape)
![image](https://user-images.githubusercontent.com/1246918/98812821-762c4480-2423-11eb-960a-25f1a4d7b882.png)

When recording performance:
![image](https://user-images.githubusercontent.com/1246918/98813016-d327fa80-2423-11eb-9d83-03e48488985e.png)

**Comment by Niallith** [comment]
Well, never mind,  I don't think my tests are relevant. At some points, React seems to clear those nodes.
