### ISSUE TITLE
Nested Table inherits property e.g. selectable

### ISSUE THREAD

**Issue by iftcoach** [Semantic-Org/Semantic-UI-React#4107]
### Steps
I created a nested table **inside** a table with the prop _selectable_ in the **outside** table only.
I tried `<Table selectable="false">` as **inside** table but no change.

### Expected Result
I expected **inside** a standard table without any properties.

### Actual Result
The **inside** table will inherit the props of the **outside** table.

### Version
2.0.1

### Testcase
https://codesandbox.io/s/semantic-ui-react-forked-qwq59?file=/index.js

**Comment by layershifter** [comment]
@iftcoach unfortunately it's related to CSS nesting as `selectable` adds `selectable` class...

I have not found any way to do without CSS overrides on an inner table 😥 Sorry, but I don't see a way how we can fix in components itself...
