### ISSUE TITLE
Input Component: autocomplete attribute added to container div, not the input html

### ISSUE THREAD

**Issue by mattgreenfield** [Semantic-Org/Semantic-UI-React#4108]
## Expected Behaviour
`<Input autocomplete="off" placeholder='Search...' />` should result in the following HTML:
`<input type="text" autocomplete="off" placeholder='Search...' />`

## Actual Behaviour
`autocomplete="off"` is added to the container div element, not the input

## Repo Link
https://codesandbox.io/s/f3jzm?module=/example.js
This is the example from the official docs

**Comment by layershifter** [comment]
Capital "C" `autoComplete`. This is mentioned in the React documentation:

https://facebook.github.io/react/docs/tags-and-attributes.html

**Comment by mattgreenfield** [comment]
ah, thanks @layershifter. Is there any way I can update the codesandbox to fix this? There is a typo in 'search' too - `placeholder='Seach...'`

**Comment by layershifter** [comment]
@mattgreenfield You can just perform your update and then save:
![image](https://user-images.githubusercontent.com/14183168/98946565-5153d200-24f4-11eb-991a-d74508094946.png)

---

Or this typo/autocomplete issue is present in our docs?

**Comment by mattgreenfield** [comment]
I've got to be honest, I can't find where I found the link in the docs. But that codesandbox example is yours, not a fork created by me, Using 'save' as per your screenshot creates a fork.
Unless I'm just confused!
Thanks again,
