### ISSUE TITLE
Ratings have a black border when clicked

### ISSUE THREAD

**Issue by mcbergsma** [Semantic-Org/Semantic-UI-React#4113]
### Steps
On the docs, if you click on one of the rating stars (first for example) it shows a black outline until you click elsewhere on the page.
https://react.semantic-ui.com/modules/rating/
This only happens in React, not on the semantic or fomantic docs.

### Expected Result
No border

### Actual Result
Has border

### Version
2.0.1

**Comment by layershifter** [comment]
@mcbergsma these borders are `outline` that are default for Chromium based browsers, it indicates focus position for keyboard users and is important part of accessibility, there are more details: https://hiddedevries.nl/en/blog/2019-06-06-indicating-focus-to-improve-accessibility.

_Why it is not happening in SUI/FUI docs?_ HTML in snippets does not care about accessibility.

---

I don't recommend to do this, but you can remove `outline` via CSS (I would rather customize it via `:focus-visible`):

```css
.ui.rating .icon { outline: 0 }
```

https://codesandbox.io/s/semantic-ui-example-forked-0fht8?file=/example.js:124-155
