### ISSUE TITLE
Form components

### ISSUE THREAD

**Issue by pranayrangne** [Semantic-Org/Semantic-UI-React#4125]
Hello, 
I am working In Semantic UI from past 1 year, its nice and userfriendly but there are some changes i think its need to be implement 
1. First is with Input Field I would like to suggest you that please add Datepicker in this, Right now i am using react-datepicker from react-datepicker lib but when i implement it with semantic UI the datepicker component gets shortern than the other input fields tried alot of things but unable to get the desired result.
2. Multiple Selections its good to have multiple selection Dropdown, but when we want to add more than 5-6+ items in multiple select the input width gets increases, its okay but we can make something like multiple select lib, i mean insteading of showing items name we can show how many items are selected example :**Item1, item2,item3** to **3 items** selected, and show which item is selected when we click on that input field, 
3.AutoComplete currently we are using search as you type in autocomplete when we type on searchChangeEvent api gets call and we get the desired value which is good for Creating new from, but at the time of update the field its not able to display the name which we have already added it from backend. and wants to update it. could you tell me how to implement this kind of functionality.

This are the issues and challenges i am facing while using Semantic UI. I hope you will make some imporvement regarding this

**Comment by brianespinosa** [comment]
@pranayrangne for your item 1, that is a duplicate request of #908

For item 2, that would really be something to address at the parent project of Semantic UI. Styling is done on that project. These are just the React bindings.
