### ISSUE TITLE
Types definiton for textarea

### ISSUE THREAD

**Issue by Dacker15** [Semantic-Org/Semantic-UI-React#4126]
## Feature Request
When working with Typescript and textarea, I'm not able to access to `HTMLTextAreaElement` directly
### Problem description
To access to `HTMLTextAreaElement`, I have to put the following code
```
//@ts-ignore
editorRef.current?.ref?.current
```
If not, Typescript give me the following error:
```
TS2551: Property 'ref' does not exist on type 'TextArea'. Did you mean 'refs'?
```

### Proposed solution
Update the type definition for `TextArea` class

**Comment by layershifter** [comment]
Please don't access private properties of class components, that's why they are not present in types definitions. You will be also can be affected by changes that will not be considered as breaking. Before #3819 will be solved and refs will be supported natively please use `Ref` component:

```tsx
<Ref innerRef={textRef}> // use ref from there
  <TextArea placeholder='Tell us more' />
</Ref>
```
