### ISSUE TITLE
clearable props not showing cross icon

### ISSUE THREAD

**Issue by sanju-developer** [Semantic-Org/Semantic-UI-React#4128]
Hello, I'm using latest version of react-semantic ui.
Dropdown component with "clearable" props not showing me cross icon to clear.
Please help :(

code look somewhat like this 
```
                           <Dropdown
                            clearable
                            search
                            selection
                            disabled={isLabReportApiLoading}
                            wrapSelection={false}
                            options={labReportConstants}
                            placeholder='Select Status'
                            onChange={selectStatusHandler}
                            selectOnBlur={false}
                            selectOnNavigation={false}
                            value={apiParamsOfLabReport.status}
                         />
```

This is my options = [
    {key: 'status1', text: 'In Process', value: 2 },
    {key: 'status2', text: 'holla mundo', value: 6 }
]

**Comment by layershifter** [comment]
It might be related to version or Semantic UI CSS, please check that it's the latest i.e. `semantic-ui@2.4.2`, `semantic-ui-less@2.4.2` or `semantic-ui-css@2.4.2`.

Otherwise, please create a repro on CodeSandbox.

**Comment by baskin** [comment]
Hi @layershifter , It seems semantic-ui-less@2.4.2 or even semantic-ui-css@2.4.2 is not available yet. I'm working with the latest (semantic-ui-less@2.4.1) where the css fix is not available

**Comment by baskin** [comment]
Please ignore the previous comment.  It is working with the latest version semantic-ui-less@2.4.1. Apologies.

**Comment by layershifter** [comment]
Closing for housekeeping. If the issue still exists, please provide more details.
