### ISSUE TITLE
CardGroup does not compile correctly with Webpack

### ISSUE THREAD

**Issue by hubertkuoch** [Semantic-Org/Semantic-UI-React#4130]
### Steps
```sh
import { CardGroup } from 'semantic-ui-react'

export function DummyList(props: Props) {
    const {items} = props
    
    return (
        <CardGroup itemsPerRow={2} stackable={true}>
            {list.map((item) => (
                <Item {...item} key={item.id} />
            ))}
        </CardGroup>
    )
}
```

### Expected Result
CardGroup should compile and be equivalent to importing Card and use <Card.Group/> component

### Actual Result
```sh
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
```

### Version
2.0.1

**Comment by layershifter** [comment]
With which version of Webpack this happens?

**Comment by hubertkuoch** [comment]
I am currently using Webpack ^5.10.0

**Comment by layershifter** [comment]
@Hubiwan sorry for the late reply, I tried to compile this snippet with Webpack 5.10.0 & 5.13.0 and it works. Can you please create an example repo with a repro?

**Comment by layershifter** [comment]
Closing for housekeeping, feel free to provide a repro and I will reopen 🐱

**Comment by ngxCoder** [comment]
The solution is

You should use `Card.Group` instead of `CardGroup`

source [https://github.com/Semantic-Org/Semantic-UI-React/issues/4214](https://github.com/Semantic-Org/Semantic-UI-React/issues/4214)
