### ISSUE TITLE
A less-loader configuration that allows to set less variables using query params in import statements

### ISSUE THREAD

**Issue by skolmer** [Semantic-Org/Semantic-UI-React#4134]
### Problem description
We want to pass variables to our theme.config by using url query params in the less import statement (`import 'semantic-ui-less/semantic.less?theme=github';`).

### Proposed solution
We came up with this solution that could be an addition to the current documentation (or maybe added to the craco plugin?) because it would allow you to do dynamic theming using webpack's lazy loading feature.

The following `less-loader` configuration injects every query param of your import statements into the less file (eg. `import 'semantic-ui-less/semantic.less?theme=github';` will add the variable `@theme:'github';` to the less file on buildtime.
```js
const CracoLessPlugin = require("craco-less");

module.exports = {
  plugins: [{
    plugin: CracoLessPlugin,
    options: {
      lessLoaderOptions: {
        additionalData: (content, loaderContext) => {
          const { resourceQuery } = loaderContext;
          const searchParams = new URLSearchParams(resourceQuery);
          const lessParams = Array.from(searchParams).map((param) => `@${param[0]}:'${param[1]}';`).join('');
          if (lessParams) {
            return lessParams + content;
          }

          return content;
        }
      }
    }
  }]
};
```
### Usage
With the above configuration you can use the full power of webpack by just creating JS modules for every theme that can be loaded (eg. `./src/themes/github.js`) with the following content:
```js
import 'semantic-ui-less/semantic.less?theme=github';
```

and lazy load it in your main module before rendering the page:
```js
// calling http://localhost?theme=github will load the specific theme before rendering the page
const urlParams = new URLSearchParams(window.location.search);
const theme = urlParams.get('theme') || 'default';

import(`./themes/${theme}.js`).then(render).catch(console.error);

const render = () => {
  // theme is now loaded. render your app...  
}
```

You could also use these query params to dynamically load specific site directories based on the passed value (`import 'semantic-ui-less/semantic.less?custom_theme=dark';`)

```less
/* Path to site override folder */
@siteFolder  : '../../src/semantic-ui/@{custom_theme}/site';
```

**Comment by layershifter** [comment]
@skolmer to be honest, I will try to do something similar. Does it work for you? 🐱

**Comment by skolmer** [comment]
> 
> 
> @skolmer to be honest, I will try to do something similar. Does it work for you? 🐱

Not sure if I can follow. Does it mean you are working on a solution to build multiple themes in a webpack based project? 
We are currently using the solution posted above to be able to build a dark and a light theme that can be switched at runtime. It's working great for us, so I thought it might be worth sharing. 😎

**Comment by layershifter** [comment]
> Not sure if I can follow. Does it mean you are working on a solution to build multiple themes in a webpack based project?

I mean that if I will have the same requirement, I will do a similar setup 🐱 

> We are currently using the solution posted above to be able to build a dark and a light theme that can be switched at runtime. It's working great for us, so I thought it might be worth sharing. 😎

It worth a post on [dev.to](https://dev.to/) 👍  Closing this for housekeeping, but please post a link to a post if you will create it 😃
