### ISSUE TITLE
Why not make the select topic complete and better?

### ISSUE THREAD

**Issue by Gosiy** [Semantic-Org/Semantic-UI-React#4135]
It ' s  for long  to me  since last  use;  I 'm so surprised for seeing  the version  of Semantic-UI  for React;  But i have a little disappointed , it seams not complete ; Because  i want to use it  develop some single project; Why not make the select topic complete and better?

**Comment by layershifter** [comment]
Sorry, is it a feature request? Please form it properly in this case.
