### ISSUE TITLE
Pre selected item for basic dropdown.

### ISSUE THREAD

**Issue by dionkas** [Semantic-Org/Semantic-UI-React#4136]
I am building a very basic (clearable dropdown list, not multi-select). And it seems there isn't a way to load the dropdown with a preselected, for example based on state.

**Comment by layershifter** [comment]
I think that you're looking for the `defaultValue` prop:

```jsx
  <Dropdown
    defaultValue="Christian"
    placeholder="Select Friend"
    fluid
    selection
    options={friendOptions}
  />
```


https://codesandbox.io/s/semantic-ui-example-forked-p1ji0?file=/example.js

**Comment by dionkas** [comment]
Great! thank you.
This was more clear how defaultValue is used
