### ISSUE TITLE
Dimmer will cause element of background disappear when background's style is fixed.

### ISSUE THREAD

**Issue by Shawnfoto** [Semantic-Org/Semantic-UI-React#4139]
## Bug Report
Dimmer will cause element of background disappear when background's style is fixed.

### Steps
Just click Dimmer on official website.

### Expected Result
It suppose to show on my background. 

### Actual Result
Element of background disappear

### Version
2.0.2

### Testcase
[Fork, update, and replace this pen to show the bug]:
[https://react.semantic-ui.com/modules/modal/](url)

**Comment by layershifter** [comment]
Please include an example on CodeSandbox and repro steps. It's not clear what is happening 💭

**Comment by layershifter** [comment]
Closing for housekeeping 🏠
