### ISSUE TITLE
Adding Transition outside the Message changes look of the elements

### ISSUE THREAD

**Issue by g-wozniak** [Semantic-Org/Semantic-UI-React#4140]
### Steps
When executing the following code:
 ```
<Transition visible={!termsAccepted} animation="scale" duration={750}>
   <Message
      icon="inbox"
      visible={!termsAccepted}
      header="Test"
      content="You must accept the Terms of Service and Privacy Policy before the next step"
   />
</Transition>
```

### Expected Result
Message component appearance isn't changed. Should look like [in the documentation](https://react.semantic-ui.com/collections/message/#types-icon-prop).

### Actual Result
Icons, content and header are getting centered due to the fact that `transition` class in `ui icon visible message scale visible transition` adds:
```
display: block !important;
visibility: visible !important;
```
when visible.
💣

### Version
2.4.2 (CSS) 2.0.2 React

**Comment by layershifter** [comment]
I don't think that we can anyhow solve it on our side 😭 The easiest workaround that I can propose is to wrap `Message` with an additional `div`:

```tsx
<Transition visible={visible} animation="scale" duration={500}>
  <div>
    <Message
      icon="inbox"
      header="Test"
      content="You must accept the Terms of Service and Privacy Policy before the next step"
    />
  </div>
</Transition>
```

https://codesandbox.io/s/semantic-ui-example-forked-lsdb2?file=/example.js
