### ISSUE TITLE
Search and Dropdown max-width

### ISSUE THREAD

**Issue by Fave-K** [Semantic-Org/Semantic-UI-React#4147]
## Bug Report
Hi guys. I can't get the Search and Dropdown component to extend past a certain width.
 
### Steps
A clear and concise description of steps to reproduce the problem.
I've noticed that using inputs inside your Form component will have them occupy the max width of their component but for these two components they will stick to about 200 px. I've tried styling them myself but I get unexpected results. For example, the Search component will resemble an input but on styling will get more border radius and can't be increased in width only size.

### Expected Result
The result that you expected.
Is there a way for me to increase the widths of these two components as I actually like using them. The fluid prop on the inputs and buttons is actually nice and it would be actually be really nice if you could incorporate it into these two components.

### Actual Result
The actual result that happened 💣
My Form will have unequal input sizes and on small screens I get unexpected results.

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by brianespinosa** [comment]
@Fave-K have you looked at the `fluid` prop?

**Comment by Fave-K** [comment]
Thank you. This only worked for the dropdown though. The Search component still won't extend its full width but I know that it's only the input that's not responding as the result renderer occupies the entire width.
