### ISSUE TITLE
Allow passing props to <input /> component

### ISSUE THREAD

**Issue by aminpaks** [Semantic-Org/Semantic-UI-React#4152]
Hi guys,

There are cases that we wanna pass some props to the `input` DOM element for example adding some `data` attributes.
Would you be open to a PR that we implement a simple prop such as `inputProps` and pass that to the real input element?

Right now this is not possible as all the props are passed down to the container and not the `input` element.

**Comment by brianespinosa** [comment]
@aminpaks this is already possible... it is just not as straightforward as passing props directly. You can place the `<input />` DOM element inside of the component as a child and then place any of your attributes you want on that element directly. I threw a codepen example of this for you. https://codesandbox.io/s/semantic-ui-react-forked-k8c7o?file=/index.js

There is also an example of this in the docs for placing the element as a child, but I do not know if it specifically shows that you can do this to also attach params.

**Comment by aminpaks** [comment]
@brianespinosa Is this documented somewhere?

**Comment by brianespinosa** [comment]
@aminpaks yes https://react.semantic-ui.com/elements/input/#variations-icon-child

Maybe you missed it because it looks like it is labeled incorrectly as passing an icon child instead of passing an input child. 🤦🏽

**Comment by aminpaks** [comment]
> Maybe you missed it because it looks like it is labeled incorrectly as passing an icon child instead of passing an input child. 🤦🏽

Yeah it's not obvious at first. Maybe we should mention it specifically.

**Comment by brianespinosa** [comment]
I am sure we would accept a PR updating the anchor link and text in that section.

**Comment by aminpaks** [comment]
@brianespinosa Would you help me identify the issue in the pipeline? #4153
