### ISSUE TITLE
Can you add a hover color change 

### ISSUE THREAD

**Issue by MDmubarak786** [Semantic-Org/Semantic-UI-React#4154]
##hover color
### Problem description
hover color change

**Comment by hardikshah197** [comment]
Hey there, Shall I work on this issue? Might I know how to fix this thing out...I'm taking up my name for this one.

**Comment by brianespinosa** [comment]
@MDmubarak786 I am unsure what is being reported here. We do not have any CSS in this repository. Styling is not currently a function of what is done with SUIR. These are only React bindings that output the expected markup and class names for Semantic UI React styles, which are contained in their repository. Any customizing of styles are not in scope for this repo.
