### ISSUE TITLE
Broken assets at: https://react.semantic-ui.com/

### ISSUE THREAD

**Issue by cybercoder** [Semantic-Org/Semantic-UI-React#4155]
Broken assets at: https://react.semantic-ui.com/
The page won't show correctly. Seems broken CDN links.

**Comment by layershifter** [comment]
![image](https://user-images.githubusercontent.com/14183168/107942744-fa92e400-6f8b-11eb-8863-60172de726bd.png)

Works fine for me, can please provide more details?

---

> Seems broken CDN links.

We are using JSDelivr and CDNjs. Can you please check what assets are broken?

**Comment by cybercoder** [comment]
![Screen Shot 2021-02-26 at 19 24 54](https://user-images.githubusercontent.com/437872/109323171-69175200-7868-11eb-83bc-1ffbb6ef18bd.png)
I did change network and try multiple proxies and tunnels.

**Comment by jimaek** [comment]
Please send the HTTP headers for the failed requests.
Also please ping cdn.jsdelivr.net and let me know of the IP.

Thanks

**Comment by cybercoder** [comment]
Oh it is my fault, i did change my hosts file to block this CDN months ago, and i did forget.
Sorry!
