### ISSUE TITLE
Icon property color can accept hex value

### ISSUE THREAD

**Issue by SiOuz** [Semantic-Org/Semantic-UI-React#4158]
## Feature Request
Icon property color can accept hex value, or add a new property like colorHex.

### Problem description
Yes we can change value for color green for example, 
but in some case we want multiple shade of green, 
and this the enum color is not possible to have multiple value for one color.

### Proposed solution
Icon property color can accept hex value, or add a new property like colorHex.

**Comment by layershifter** [comment]
The idea of `color` prop is to include colors that are defined by a theme and aligned with other components, for one time usage you can tweak it directly via `style` attribute:

```jsx
<Icon name="certificate" style={{ color: "#a333c8" }} />
```

https://codesandbox.io/s/semantic-ui-example-forked-75hjx?file=/example.js:110-166
