### ISSUE TITLE
Questions regarding the future of SUIR

### ISSUE THREAD

**Issue by slouchymunchkin** [Semantic-Org/Semantic-UI-React#4163]
Hello,

Apologies for putting this here, but I couldn’t find any information related to this inquiry so I thought this would be the best place ask.

Our company is using SUIR for several of our clients and we would really appreciate some kind of update or announcement regarding the future of SUIR, as the direction of SUIR could affect our projects.

- Will SUIR development continue and in what capacity? Is there a roadmap for what to expect?
- How will SUIR move forward with regards to semantic ui css/fomantic ui css?
- Will you perhaps open up for sponsorships?

**Comment by brianespinosa** [comment]
@levithomason do you want to chime in here?

I know there was hope that Fluent would have a SUI theme at some point. I assume that is enough of a major version change that this package is in maintenance mode.

@layershifter has been shipping some maintenance updates and we have had a couple major version bumps. I do not know if the idea is to keep this maintained and ready for React 18.

**Comment by levithomason** [comment]
>Will SUIR development continue and in what capacity? Is there a roadmap for what to expect?

Yes, it will continue as periodic releases with fixes and minor improvements. There is not a roadmap for this work as it is not major. When we find time, we may hop over and make some fixes/updates and cut a new release.

>How will SUIR move forward with regards to semantic ui css/fomantic ui css?

We keep in contact with them from time to time. Originally, their hope was to merge back into Semantic. That sentiment seems to be maintained in their latest comments regarding their next major. However, I've also seen sentiment about rebranding Fomantic and permanently forking off in an incompatible way.

>Will you perhaps open up for sponsorships?

I would love to accept sponsorships, however, the truth is there isn't enough potential income for us to leave our day jobs for this project :(

>@levithomason do you want to chime in here?
>
>I know there was hope that Fluent would have a SUI theme at some point. I assume that is enough of a major version change that this package is in maintenance mode.

I would agree. Fluent may be able to have a Semantic theme once it becomes stable, however, that is not currently a level priority for Fluent.

**Comment by simian-loco** [comment]
@levithomason  I am sorry if this is a bad question; but what would be the migration cost for moving from SemanticUI to FluentUI. They both provide React components no? Are the APIs similar enough where there could be a reasonably small cost for a medium-sized project (~70k sloc) to migrate over to fluent ui? What would be the major issues regarding this?
