### ISSUE TITLE
Dropdown: Event Typings are Incorrect

### ISSUE THREAD

**Issue by aboyce** [Semantic-Org/Semantic-UI-React#4165]
## Bug Report
The typing for the Dropdown `onClick` event is a `KeyboardEvent` rather than a `MouseEvent`.

https://github.com/Semantic-Org/Semantic-UI-React/blob/ff703557a3090ea281cb7a263bc486a978fbabdd/src/modules/Dropdown/Dropdown.d.ts#L154

It also looks as though `onBlur` and `onFocus` should be `FocusEvent`s?

https://github.com/Semantic-Org/Semantic-UI-React/blob/ff703557a3090ea281cb7a263bc486a978fbabdd/src/modules/Dropdown/Dropdown.d.ts#L138

https://github.com/Semantic-Org/Semantic-UI-React/blob/ff703557a3090ea281cb7a263bc486a978fbabdd/src/modules/Dropdown/Dropdown.d.ts#L170

### Steps
Use any Dropdown and add a typed `onClick` handler.

### Expected Result
The `onClick` event is typed as a `MouseEvent`.

### Actual Result
The `onClick` event is typed as a `KeyboardEvent`.

### Version
2.0.3

### Testcase
https://codesandbox.io/s/semantic-ui-react-forked-pmkh6

**Comment by layershifter** [comment]
Was fixed in [`semantic-ui-react@2.0.4`](https://github.com/Semantic-Org/Semantic-UI-React/releases/tag/v2.0.4).
