### ISSUE TITLE
The <Icon> show as color box on production.

### ISSUE THREAD

**Issue by huiman** [Semantic-Org/Semantic-UI-React#4171]
The Icon show color rectangle box on production.

production::

![image](https://user-images.githubusercontent.com/3445884/111102515-d9b7b180-857e-11eb-8c7f-853bfdfab291.png)

dev::
![image](https://user-images.githubusercontent.com/3445884/111102552-f18f3580-857e-11eb-9ac4-be039b0f34f4.png)

**Comment by layershifter** [comment]
Please provide a repro repository that can be cloned (please include steps to reproduce the issue). This looks like an issue with fonts assets, but it's hard to say without a repro.

**Comment by huiman** [comment]
this is the function::

const LGStatistic = (props) => {
  useEffect(() => {
    return () => {};
  }, []);
  const { count } = props;
  return props.Loading ? (
    <Loader active inline />
  ) : (
    <Statistic.Group className={props.size ? props.size : ""}>
      <Statistic>
        <Statistic.Value>{count.all}</Statistic.Value>
        <Statistic.Label>MEMBERs</Statistic.Label>
      </Statistic>
      <Statistic>
        <Statistic.Value>
          {/* <Icon name="question circle outline" /> */}
          {count.visitor}
        </Statistic.Value>
        <Statistic.Label>ผู้สนใจ</Statistic.Label>
      </Statistic>
      <Statistic>
        <Statistic.Value>
          <Icon name="user outline" color="green" size="mini" />
          {count.newbeliever}
        </Statistic.Value>
        <Statistic.Label>ผู้เชื่อใหม่</Statistic.Label>
      </Statistic>
      <Statistic>
        <Statistic.Value>
          {count.believer}
        </Statistic.Value>
        <Statistic.Label>ผู้เชื่อ</Statistic.Label>
      </Statistic>
      <Statistic>
        <Statistic.Value>
          {count.shepherd}
        </Statistic.Value>
        <Statistic.Label>พี่เลี้ยง</Statistic.Label>
      </Statistic>
      <Statistic>
        <Statistic.Value>
          <Icon name="fire" color="red" size="mini" />
          {count.member}
        </Statistic.Value>
        <Statistic.Label>สมาชิก</Statistic.Label>
      </Statistic>
    </Statistic.Group>
  );
};

**Comment by huiman** [comment]
> Please provide a repro repository that can be cloned (please include steps to reproduce the issue). This looks like an issue with fonts assets, but it's hard to say without a repro.

@layershifter, Thank you for enlighten me, I have fixed it.
