### ISSUE TITLE
A letter can be typed into <Input type="number"/>

### ISSUE THREAD

**Issue by hieundx** [Semantic-Org/Semantic-UI-React#4179]
## Bug Report
A letter can be typed into `<Form.Input type="number"/>`

### Steps
1. Create a `<Form>`
2. Add a `<Form.Input type="number"/>`
3. Try to type a letter into the input form

### Expected Result
Should not be possible

#### Brave, Chrome 
Letter 'e' can be typed into the form 💣
All other letters meet the expected result
#### Firefox 
Any letter can be typed into the form

### Version
2.0.3

### Testcase
https://codesandbox.io/s/wizardly-tree-xfpt7?file=/src/App.js

**Comment by layershifter** [comment]
Unfortunately, it's not a SUIR problem, I modified CodeSandbox to include a native element and it behaves in the same way: https://codesandbox.io/s/modern-worker-i9fvm

---

> The number input can accept floating-point numbers, including negative symbols and the "e" or "E" character (where the exponent is the number after the e or E).

https://stackoverflow.com/a/31706796/6488546
