### ISSUE TITLE
Input: fluid property doesn't work with Flexbox

### ISSUE THREAD

**Issue by ghzeni** [Semantic-Org/Semantic-UI-React#4186]
**## Bug Report**

**### Steps**
Insert a Search component with the 'fluid' property and add display: flex to it's CSS
 
**### Expected Result**
The input becomes as big as its container.

**### Actual Result**
The input becomes a small box.

**### Version**
2.0.3

**### Testcase**
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/semantic-ui-react-forked-jzbub
![issue](https://user-images.githubusercontent.com/15947263/113564850-6be03200-95e0-11eb-9431-ca3d623ab151.png)

**Comment by brianespinosa** [comment]
@Cheddargt that is how flexbox works. You are placing your Input inside of a `display: flex` container. If you want the child element to expand to the size of the container, you need to set the `flex-grow` property on that element. `flex` as a prop is not intended to be displaying the input as a direct child of another element flex container. If you take a look at the CSS, `flex` changes the Input to `display: flex`.

[I updated your example](https://codesandbox.io/s/semantic-ui-react-forked-flr5j?file=/index.js) showing you that if you set the `flex-grow` to `1` the element displays as you would expect. You do not even need to set the `flex` prop.

What you are doing in your example is not really how the markup for those elements are intended to be used so the props and styles are not necessarily going to work as you would expect.

**Comment by ghzeni** [comment]
> 
> 
> @Cheddargt that is how flexbox works. You are placing your Input inside of a `display: flex` container. If you want the child element to expand to the size of the container, you need to set the `flex-grow` property on that element. `flex` as a prop is not intended to be displaying the input as a direct child of another element flex container. If you take a look at the CSS, `flex` changes the Input to `display: flex`.
> 
> [I updated your example](https://codesandbox.io/s/semantic-ui-react-forked-flr5j?file=/index.js) showing you that if you set the `flex-grow` to `1` the element displays as you would expect. You do not even need to set the `flex` prop.
> 
> What you are doing in your example is not really how the markup for those elements are intended to be used so the props and styles are not necessarily going to work as you would expect.

Oh, my bad! I tried everything but absolutely forgot about `flex-grow` :(

But wait, so why does Dropdown expand naturally? Does it have `flex-grow: 1` pre-set?

**Comment by brianespinosa** [comment]
> But wait, so why does Dropdown expand naturally? Does it have flex-grow: 1 pre-set?

@Cheddargt The .fluid class also has `width: 100%` on it, which will also work in place of `flex-grow` in this particular scenario.

```
.ui.fluid.dropdown {
    display: block;
    width: 100%;
    min-width: 0;
}
```
