### ISSUE TITLE
Right side width

### ISSUE THREAD

**Issue by kyleturco** [Semantic-Org/Semantic-UI-React#42]
The right side (content not left menu) doesn't have a responsive width. Below 1400px or so, the content goes out of the right side of the browser. It should respond to window size.

**Comment by levithomason** [comment]
This was intentional as the PropTypes do not fit on a table that small.  I'm open to better suggestions than limiting width though.  One thing might be using a `<Table />` for the props and allowing it to be responsive.

**Comment by kyleturco** [comment]
That sounds fine. The main issue I'm seeing is for the UI elements I'm adding they extend awkwardly off the side. (see screenshot) A width would at least allow them to wrap. We could also add a width limit for just the ui examples I would think.
![screen shot 2015-10-09 at 2 45 30 pm](https://cloud.githubusercontent.com/assets/6728034/10403873/868463ac-6e94-11e5-9354-2ae9c9c03900.png)

**Comment by kyleturco** [comment]
This has been addressed by removing flex. It will be in my feature/button-examples PR
