### ISSUE TITLE
Warning when closing Modal "Can't perform a React state update on an unmounted component."

### ISSUE THREAD

**Issue by d4kris** [Semantic-Org/Semantic-UI-React#4200]
## Bug Report
My first attempt at using a Modal was to have a state variable indicating if the modal was open, and only render the Modal when open was true.  This worked fine for closing the modal with the closeIcon, but gave me a warning when I clicked outside the modal to close it. 

After some testing I changed my code to always render the Modal and set the open property to my open state variable. 
I suggest explaining this in the documentation (or fixing the cause of the warning). 

### Steps
Render modal depending on state.
Click outside the open modal, or use escape to close it.

### Expected Result
Modal should close without errors in console.

### Actual Result
Modal is closed with this error in the console:
"Warning: Can't perform a React state update on an unmounted component."
Two errors when using escape to close.

### Version
2.0.3

### Testcase
https://codesandbox.io/s/semantic-ui-example-forked-yt0xt

**Comment by layershifter** [comment]
@d4kris thanks it's definitely not expected to have a warning from React, #4259 will fix it 🙋‍♂️

**Comment by layershifter** [comment]
Was fixed in [`semantic-ui-react@2.0.4`](https://github.com/Semantic-Org/Semantic-UI-React/releases/tag/v2.0.4).
