### ISSUE TITLE
Possible to use local package in development and CDN in production?

### ISSUE THREAD

**Issue by jghaines** [Semantic-Org/Semantic-UI-React#4212]
The Get Started instructions give two installation options:

1. Package Manager
2. CDN (no bundler)

Is there any way to use the Package Manager for local (offline) development and the CDN for other (production) environments?

**Comment by layershifter** [comment]
@jghaines yes, it's possible, but I don't recommend doing this nowadays.

It will improve load performance due missing tree-shaking and a fact that CDN cache is not shared anymore (https://www.jefftk.com/p/shared-cache-is-going-away). It also could create hard to catch bugs.

---

However, if you using Webpack it should be pretty simple to do. Modify:

#### `index.ejs` or `index.html` to include CDN build

```html
<%if (__PROD__) {%>
<script src="CDN_URL.js"></script>
<%}%>
```

#### `webpack.config.js`

```js
module.exports = {
  // ---
  externals: {
    ...(process.env.NODE_ENV === "production" && {
      "semantic-ui-react": "semanticUIReact"
    })
  }
  // ---
};
```
