### ISSUE TITLE
Multiple Search Selection using with backend

### ISSUE THREAD

**Issue by kbsenay** [Semantic-Org/Semantic-UI-React#4217]
Hi,
I am studying in a development project. I use Multiple Search Selection for a city list. But I receive cities from backend. When I use it, I can get cities, but they cannot be selected or sticked on top. 
![Photo](https://user-images.githubusercontent.com/77517479/122652163-08c55c80-d146-11eb-8c82-4cb1315ce48a.jpg)

[https://github.com/kbsenay/ProjectHRMSFrontend-React/blob/master/src/layouts/SideBar.jsx](url)

**Comment by layershifter** [comment]
@kbsenay I suggest to post your question to StackOverflow using "semantic-ui-react" tag, in issues we track only bugs and enhancements.
