### ISSUE TITLE
Modal gets closed as you click on it when it's rendered from a popup

### ISSUE THREAD

**Issue by hashmatmuqbil** [Semantic-Org/Semantic-UI-React#4222]
### Steps
I have a link inside a popup to open a modal with form but as I click on modal form to fill out the input the modal gets closed. No matter where I click on the modal it gets closed

### Expected Result
The result that you expected.

### Actual Result
The actual result that happened 💣

### Version
 "semantic-ui-css": "2.4.1",
    "semantic-ui-react": "2.0.3",
### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by brianespinosa** [comment]
@hashmatmuqbil please complete the entire bug report. We need a minimal working code example to see what is happening.

Closing but will reopen if a code example is provided.
