### ISSUE TITLE
Modal window gets opened in the component everytime when Enter key is pressed

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#4226]
## Bug Report
I have two functional components on a page.One of them is a form with textfields and another one is a modal component which is getting opened once a button is clicked on the form.Every time when I type something in the text field and press Enter key,modal window gets opened.
### Steps

Create a component with a form and textfields
Create a button on the form which opens a modal window
Every time the text is entered in the input fields on the form and  the Enter key is pressed, the modal window is getting opened

### Expected Result
The modal window should not open on the every click of the enter key on the form.Instead It should open only once the user actually clicks on the button 

### Actual Result
Every time when the enter key is pressed on the form once the user enters some input in the fields, button gets triggered and modal window opens

(I found a solution to this issue to use `event.currentTarget.blur();`  once the Enter key is pressed because for some reason once the modal is closed,the focus remains on the button, but I believe this should be fixed somehow if possible)
### Version
2.0.3

**Comment by brianespinosa** [comment]
@kirkhla please complete the entire bug report form and include a working code example that shows the issue. We need that in order to see what is going on. 

Closing but will reopen with a working code reproduction.
