### ISSUE TITLE
Kosovo flag 🇽🇰 is not included on the list of flags

### ISSUE THREAD

**Issue by deniskola** [Semantic-Org/Semantic-UI-React#4229]
Kosovo flag should be included

**Comment by layershifter** [comment]
@deniskola sorry, but we don't maintain CSS in this repo. This issue already exists in the main repo, https://github.com/Semantic-Org/Semantic-UI/issues/6996.

**Comment by ivangomes** [comment]
@layershifter quick question: is Semantic-UI the main repo ( CSS) or Fomantic-UI. Because all the missing flags are included there.

**Comment by layershifter** [comment]
@ivangomes as this repo is still in SUI org => it's Semantic-UI... Probably, there should be a fork for Fomantic UI => Fomantic UI React.

**Comment by ivangomes** [comment]
@layershifter Thank you for replying back to me. No fork for UI => Fomantic UI React. Unfortunately
