### ISSUE TITLE
Doc: CI deploys a broken doc site build

### ISSUE THREAD

**Issue by padsbanger** [Semantic-Org/Semantic-UI-React#423]
Hello,

Today when I have visited: http://technologyadvice.github.io/stardust/

I get:

`app.eb3d830….js:23:  Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.`

**Comment by levithomason** [comment]
Indeed, fixing.

**Comment by levithomason** [comment]
It's up now.  Unfortunately, I can't see what went wrong here.  It runs locally and the CI logs appear OK.  Thanks for the report.

**Comment by levithomason** [comment]
This is a confirmed recurring issue with CI.  Every deploy seems to break the doc site.  Local deployments work. So, reopening until the CI issue is resolved.

**Comment by levithomason** [comment]
The dependency update recently merged was at fault.  `history` v3 is not compatible with the `react-router`.  Rolling this back fixed all issues.

**Comment by padsbanger** [comment]
Thank you :)
