### ISSUE TITLE
Bug: Doc website prevents the use of cmd + c

### ISSUE THREAD

**Issue by besh** [Semantic-Org/Semantic-UI-React#425]
When attempting to do `cmd + c` to copy code snippets (or anything) focus is set to the search bar. This is because of https://github.com/TechnologyAdvice/stardust/blob/master/docs/app/Components/Sidebar/Sidebar.js#L38. A catch is needed to prevent focus from firing when `cmd` (and likely `ctrl`) keycodes are captured.

For now, right-clicking and selecting "copy" still works though! 

I attempted to fix this but after cloning, npm installing, and running `npm start`, nothing shows up on `localhost:8080` for me. I'll revisit if I get a chance. I may have done something stupid on setup. There's a lot of npm scripts and maybe others have to be run before I can dev on the doc site but that wasn't immediately apparent to me. If someone wants to point out what I did incorrectly, I would be happy to fix this bug!

**Comment by levithomason** [comment]
Should deploy in ~5m, thanks for the report!

**Comment by levithomason** [comment]
Deployed, though affected by #423.  So there may be intermittent doc site availability for the time being.

**Comment by besh** [comment]
Super fast response! Thanks for the fix.
