### ISSUE TITLE
Disable menu item (tabs)

### ISSUE THREAD

**Issue by basickarl** [Semantic-Org/Semantic-UI-React#4272]
Hello!

Feature request: To be able to disable and remove hovering/clickable on a tab menu item (not the pane, the pane shouldn't be able to be shown since you can't click on the menu item). 

Something like the following
```
<Menu.Item disabled={true}>
```

If there is already a way to do this then how?

**Comment by layershifter** [comment]
@basickarl do you mean something like this?

![image](https://user-images.githubusercontent.com/14183168/128164365-c6d11ec2-59d9-4f1b-965d-30c9c3460244.png)

```tsx
import React from 'react'
import { Tab } from 'semantic-ui-react'

const panes = [
  { menuItem: 'Tab 1', render: () => <Tab.Pane>Tab 1 Content</Tab.Pane> },
  { menuItem: { content: 'Tab 2', disabled: true }, render: () => <Tab.Pane>Tab 2 Content</Tab.Pane> },
]

const TabExampleBasic = () => <Tab panes={panes} />

export default TabExampleBasic
```

https://codesandbox.io/s/ky7xw?module=/example.js

**Comment by basickarl** [comment]
Yes exactly!
