### ISSUE TITLE
`Tab` component, `menuItem` requirement to accept jsx, currently only strings can be used

### ISSUE THREAD

**Issue by Teut2711** [Semantic-Org/Semantic-UI-React#4274]
### Problem description
I am dynamically adding tabs. I need the functionality of delete. I need to put a  (X) button with the string so that I can remove tabs. Current my content area has a button to do so.

Here's what I'm making. Just click Add Test button , fill the name and click OK, tab will be appended to the right.
https://codesandbox.io/s/upbeat-bas-pb0t2?file=/src/components/PatientProfileForm.js

  
### Proposed solution
A clear and concise description of what you want to happen. Add any considered drawbacks.

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:

**Comment by layershifter** [comment]
@Teut2711 it's already possible, as `menuItem` is a [shorthand property](https://react.semantic-ui.com/shorthand-props) 😉

![image](https://user-images.githubusercontent.com/14183168/128633548-7a5aa9e5-35ed-43dc-8255-3e4e60fe0f1a.png)


```jsx
      menuItem: {
        content: (
          <div
            style={{
              alignItems: "center",
              display: "grid",
              gridTemplateColumns: "1fr auto"
            }}
          >
            <div>{testList[testID].text}</div>
            <Button color="red" compact size="mini">
              X
            </Button>
          </div>
        )
      },
```

https://codesandbox.io/s/small-leaf-jy7ru?file=/src/components/Main.js:1639-2025

**Comment by Teut2711** [comment]
Thanks for the help!

**Comment by Teut2711** [comment]
Can you help with this issue too, please?
```
       <Tab menu={{ fluid: true, vertical: true, tabular: true }}
              panes={details}
              activeIndex={currentTabIndex}
              onTabChange={handleTabChange} />
            <Tab menu={{ fluid: true, vertical: true, tabular: true }}
              panes={allTests}
              
              onTabChange={handleTabChange} />
```
I need [this](https://react.semantic-ui.com/collections/menu/#content-header-vertical) kind of a menu rather than the current one where the first set of fields would be for the Patient Profile heading, after a small gap the Test List heading and the tests corresponding to that have to be there. How can I have such a list without the complicacy of playing with the first and the last items of each sub-menu, i.e., checking if it's the first element and put the header there using what you told above. And I need a search box too like in one of the menu so that user can filter out test? Multiple tab menus broke everything.

**Comment by Teut2711** [comment]
> 
> 
> Can you help with this issue too, please?
> 
> ```
>        <Tab menu={{ fluid: true, vertical: true, tabular: true }}
>               panes={details}
>               activeIndex={currentTabIndex}
>               onTabChange={handleTabChange} />
>             <Tab menu={{ fluid: true, vertical: true, tabular: true }}
>               panes={allTests}
>               
>               onTabChange={handleTabChange} />
> ```
> 
> I need [this](https://react.semantic-ui.com/collections/menu/#content-header-vertical) kind of a menu rather than the current one where the first set of fields would be for the Patient Profile heading, after a small gap the Test List heading and the tests corresponding to that have to be there. How can I have such a list without the complicacy of playing with the first and the last items of each sub-menu, i.e., checking if it's the first element and put the header there using what you told above. And I need a search box too like in one of the menu so that user can filter out test? Multiple tab menus broke everything.

`
  const menuItems = [
    { menuItem: { header: true, content: <Header as="h3">Patient Profile</Header>, active: false } },
    details, ...allTests]
`

Did it, sorry took a while to understand the shorthand prop.
