### ISSUE TITLE
Shorthand prop usage for menuItem in Tab component

### ISSUE THREAD

**Issue by Teut2711** [Semantic-Org/Semantic-UI-React#4276]
### Problem description
I refactored my code but after spitting I'm stuck at the `panels` of Tab component since they are javascript objects and not jsx.

### Proposed solution
A clear and concise description of what you want to happen. Add any considered drawbacks.

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

I already asked this on IRC and discord(Reactiflux) and stackoverflow. 
 
https://stackoverflow.com/questions/68715355/typeerror-testslist-is-not-iterable

https://codesandbox.io/s/sparkling-forest-c75gg?file=/src/components/SideBar/TestsMenu.js

**Comment by brianespinosa** [comment]
@Teut2711 the first answer on your StackOverflow question is the correct answer.

**Comment by Teut2711** [comment]
It's not if you read my Edit and see the image which I posted in the comments of the first answer. You can also try adding tests in my codesandbox and the tests do not get added to the sidebar because the TestsMenu is [{menuItem:"", render():=>{}},  a function ]. Thus the Tests header gets shown but not the tests because of that since the TestsList returned a function. I tried [TestsHeader, TestsList()] which gave another error.
