### ISSUE TITLE
Error Building Docs

### ISSUE THREAD

**Issue by oscarmed** [Semantic-Org/Semantic-UI-React#4281]
I cloned the repo and ran `npm install` which should have downloaded all dependencies.

I got an error from running `npm run build:docs`

> Error: Cannot find module 'react-static/node_modules/uglifyjs-webpack-plugin'

I then ran `npm install react-static`

Running `npm run build:docs` again gives this error

> Error: Chunk.entrypoints: Use Chunks.addGroup instead

**Comment by layershifter** [comment]
Can you please try the same with `yarn` v1?

**Comment by oscarmed** [comment]
That worked. Thanks!

**Comment by layershifter** [comment]
Closing then 😀
