### ISSUE TITLE
react-semantic ui site is not reachable

### ISSUE THREAD

**Issue by RamCharanTejaPolu** [Semantic-Org/Semantic-UI-React#4285]
I was referring react semantic ui control to develop my app in react js later have been facing issue accessing react semantic ui site 

![image](https://user-images.githubusercontent.com/50401480/132708276-31bcb25a-ef1c-4adc-a6e2-719ee15c55e4.png)

**Comment by imi56** [comment]
I'm wondering how can a popular website like this be down for so many days? Strange!

**Comment by layershifter** [comment]
It seems that it's caused by Cloudflare issues in India:
https://community.cloudflare.com/t/website-blocked-for-some-users-in-india/300620

Unfortunately, I don't know how it could be fixed 😐

**Comment by callmekatootie** [comment]
@layershifter Would this help - https://community.cloudflare.com/t/website-blocked-for-some-users-in-india/300620/5

**Comment by layershifter** [comment]
FYI: I pinged @levithomason about this problem

**Comment by levithomason** [comment]
I'm working on this with Jack, I don't have CloudFlare rights unfortunately.

**Comment by levithomason** [comment]
This should be resolved now. Can someone confirm? @RamCharanTejaPolu

**Comment by RamCharanTejaPolu** [comment]
> This should be resolved now. Can someone confirm? @RamCharanTejaPolu

@levithomason able to access the react-semantic site now , Thanks.

**Comment by levithomason** [comment]
Fantastic! Thanks all for the report and investigation.
