### ISSUE TITLE
Adding multiple property on Dropdown modifies CSS behavior

### ISSUE THREAD

**Issue by NLSVTN** [Semantic-Org/Semantic-UI-React#4293]
Hi, 

I noticed a weird behavior for **Form.Dropdown**. When we add **multiple** property on it, the vertical positioning of the field changes and I can't figure out how to reposition it back to normal since no **CSS** works after that. The issue is described in this **_stackoverflow_** thread that I created (look at the very end of the question):

https://stackoverflow.com/questions/69466435/align-item-vertically-with-semantic-ui-react

From my understanding **multiple** property should not modify dropdown positioning relative to other fields on the page because its rather a behavioral property, so I think its a bug.

**Comment by brianespinosa** [comment]
I created a codesandbox example to show the solution to your issue, which is a small tweak to the initial CSS. Technically a bug that misses the inline use case for Form with a label and multi select in the parent SUI project CSS files. With that little change, everything works as expected.

Closing this issue as a question with the answer on SO.
