### ISSUE TITLE
Table is breaking on large column number

### ISSUE THREAD

**Issue by FERViborg** [Semantic-Org/Semantic-UI-React#4300]
### Steps
If you put to many columns (16 in the https://react.semantic-ui.com/collections/table/#types-pagination) in table it will break layout.

### Expected Result
The expected behavior would be for table to reformat as it reforms when the table becomes to small.
![image](https://user-images.githubusercontent.com/25280296/140506610-80f730fc-ff0e-4a0e-887c-68db9898f993.png)

### Actual Result
Table broke the layout and was bigger then its container.
![image](https://user-images.githubusercontent.com/25280296/140506624-cf6c17df-f2ce-4c13-ab01-4bb1b93e4cb5.png)

### Version
v2.0.4 (2021-09-23)

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by brianespinosa** [comment]
@FERViborg the table is not breaking. Overflow scrolling styles are not included in the table. In the example, you have extended the table outside of the width of the parent container. If you want to be able to scroll to the header elements outside of the parent, you will need to add a scrolling container.
