### ISSUE TITLE
Popup with hideOnScroll option hides on a scroll from inside the Popup

### ISSUE THREAD

**Issue by oskarwrobel** [Semantic-Org/Semantic-UI-React#4305]
### Steps
Create a Popup with `hideOnScroll` option and custom content with an inner scroll inside. Try to scroll popup content, popup will hide.

### Expected Result
Popup should remain visible when the scroll comes from inside the Popup. I think there is no point to hide the popup in this case.

### Actual Result
Popup hides when scroll comes from inside the popup

### Version
2.0.4

### Testcase
https://codesandbox.io/s/semantic-ui-react-popup-hides-on-inner-scroll-jdtmw

https://user-images.githubusercontent.com/1057056/145740145-54366c2e-51dc-4083-bf9e-776d5c8c1427.mp4

**Comment by oskarwrobel** [comment]
👋 If you confirm it's a bug I would love to prepare a pull request with a fix.

**Comment by selvarathinamvignesh** [comment]
@oskarwrobel Do you have temp fix?

**Comment by layershifter** [comment]
@oskarwrobel Yes, this looks a bug. PRs are welcomed.

**Comment by oskarwrobel** [comment]
@selvarathinamvignesh here is my temp fix: https://codesandbox.io/s/react-semantic-popup-with-inner-scroll-xne3v?file=/src/Popup.tsx
Instead of using `hideOnScroll` prop I created a wrapper where I implemented my own scroll listener.

@layershifter  I'll create a PR.
