### ISSUE TITLE
dropdown controlled undefined input

### ISSUE THREAD

**Issue by vkryman** [Semantic-Org/Semantic-UI-React#4312]
### Problem description
The controlled dropdown continues to show previous selection when the value gets an undefined value.
<dropdown ... value={this.props...undefined}... />

### Proposed solution
If somehow the controlled value == undefined then the dropdown should reset its previous choice.

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

**Comment by brianespinosa** [comment]
Hi @vkryman 

Please complete the full bug report to include a working reproduction of the issue you are facing. Closing for now but we can reopen if we get a working example of the reported issue.

**Comment by layershifter** [comment]
> ### Problem description
> The controlled dropdown continues to show previous selection when the value gets an undefined value. <dropdown ... value={this.props...undefined}... />

It's default React's behaviour for native controls, too:
https://codesandbox.io/s/delicate-haze-m5dxg?file=/src/App.js

If you want to reset value please use `null` or another value.
