### ISSUE TITLE
How to change Search module class

### ISSUE THREAD

**Issue by ormissia** [Semantic-Org/Semantic-UI-React#4314]
I am learning react with semantic UI, I have a question about custom search module css.

<details>

![image](https://user-images.githubusercontent.com/55517494/147427538-00782d72-46eb-4acc-b5ac-85154269024c.png)

</details>

I want to change input css like this:

<details>

![image](https://user-images.githubusercontent.com/55517494/147427613-4b665e65-8ff2-46b8-afcb-254658e633cc.png)

</details>

But I dont known how to setting in react js.

This class setting is not working correctly.

```js
return(
    <Search
        class='ui focus'
        className='ui focus'
        onSearchChange={handleSearchChange}
    />
)
```

## version:
- "react": "^17.0.2",
- "react-dom": "^17.0.2",
- "react-router-dom": "^6.2.1",
- "react-scripts": "5.0.0",
- "semantic-ui-css": "^2.4.1",
- "semantic-ui-react": "^2.0.4",

**Comment by layershifter** [comment]
@ormissia you can use `input` shorthand on `Search` to reach the proper slot:

```tsx
<Search
  input={{
    input: { className: "ui input" },
    icon: "search",
    iconPosition: "left"
  }}
/>
```

![image](https://user-images.githubusercontent.com/14183168/148035671-7ba84fb2-376e-4c02-b5f2-0369578e6e52.png)

----

https://react.semantic-ui.com/modules/search/#variations-aligned
