### ISSUE TITLE
Dropdown Item's onClick doesn't trigger Dropdown's selection

### ISSUE THREAD

**Issue by nathanhannig** [Semantic-Org/Semantic-UI-React#4315]
### Steps
Creating an Item (option) with an onClick property doesn't trigger the onChange event of the Dropdown when the Item is clicked.

### Expected Result
The onClick should run and then the event should propagate to the parent to execute the onChange event

### Actual Result
Only the Item's onClick executes, the Dropdown's onChange does not execute.

### Version
2.0.3

### Testcase
"Aland Islands" Item of the Dropdown has an onClick property, when the Item is selected it executes the onClick; but doesn't set it as the Dropdowns value.

The other Items without an onClick allow the Item to be selected and close the menu.

https://codesandbox.io/s/semantic-ui-example-forked-clt0r?file=/example.js

**Comment by layershifter** [comment]
This definitely a bug, fix is coming 🚀
