### ISSUE TITLE
Can't set `type="button"` when using `Button` with a `label`.

### ISSUE THREAD

**Issue by ThiefMaster** [Semantic-Org/Semantic-UI-React#4318]
### Steps
Create a `Button` component with a `label` and `type="button"`

### Expected Result
The `<button />` element should have `type="button"`

### Actual Result
The attribute is set on the div around it where it's useless, so the button's onClick is triggered when pressing enter in some form field that submits the form (default type for a button is submit)

### Version
2.0.4

### Testcase
https://codesandbox.io/s/semantic-ui-react-forked-jx0wi

**Comment by ThiefMaster** [comment]
Thanks for the quick fix!

**Comment by layershifter** [comment]
@ThiefMaster the next release should happen on this/next week. If you're in rush I suggest to use [`patch-package`](https://www.npmjs.com/package/patch-package) 🐱
