### ISSUE TITLE
Popup opening and immediately disappearing 

### ISSUE THREAD

**Issue by deastman** [Semantic-Org/Semantic-UI-React#4325]
## Bug Report
This bug pertains to the Popup module. This bug was observed by a member of my team. 

### Steps
Approach the Popup trigger element with the mouse very slowly from the direction that the Popup appears. For example, if the Popup opens on the bottom, approach the trigger element very slowly from the bottom. When the mouse hits the edge of the trigger element, the Popup appears and then immediately disappears.

### Expected Result
 The Popup appears and remains open.

### Actual Result
The Popup appears and then immediately disappears.

### Version
2.0.3 (but this same behavior can be observed on the Popup examples in the docs: [popup example](https://react.semantic-ui.com/modules/popup/#types-popup)

### Testcase
[Bug]:
https://codesandbox.io/s/semantic-ui-react-forked-k2y87?file=/index.js

https://user-images.githubusercontent.com/2328582/150805144-7f129d37-51ed-48b1-b3e5-8d9c18c629ba.mov

**Comment by layershifter** [comment]
Sorry, but I don't see any regression there. Even compared to `0.88.2`, https://codesandbox.io/s/semantic-ui-example-forked-gk4du. It's a default behavior.

To delay it from closing you can increase `mouseLeaveDelay`:

```jsx
<Popup
  content="Add users to your feed"
  trigger={<Button icon="add" />}
  mouseLeaveDelay={2000}
/>
```

Or configure behavior via `on` prop:

```jsx
<Popup
  trigger={
    <Button color="red" icon="flask" content="Activate doomsday device" />
  }
  content={<Button color="green" content="Confirm the launch" />}
  on="click"
  position="top right"
/>
```

https://react.semantic-ui.com/modules/popup/#usage-actions

---

You always can use controlled mode to configure desired behavior: https://react.semantic-ui.com/modules/popup/#usage-controlled

**Comment by layershifter** [comment]
Closing as there is no reply from an author.
