### ISSUE TITLE
Documentation includes zero information on how to extract a value from one of your components

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#4326]
I do not believe it is too much to ask to have the literal documentation include the 2 lines of code it should require to get a value from your components. A toggle is completely useless if you cannot figure out how to get a value out of it.

**Comment by ghost** [comment]
Also, y'all're *assholes* for making every single element slightly transparent just so that developer side CSS cannot override it being light mode without using !important, and even then sometimes not.
Dark mode is basic functionality, light mode being trendy be *damned*.

**Comment by brianespinosa** [comment]
@ChristopherJTrent 
![](https://media.giphy.com/media/5nzvEcRyntHnW/giphy.gif)
