### ISSUE TITLE
Dropdown Filter inconsistence 

### ISSUE THREAD

**Issue by gpltaylor** [Semantic-Org/Semantic-UI-React#4333]
Version: 2.1.1

Expected: Dropdown to filter using "Starts with"
Actual: Dropdown filters using "wild card"

Expected
![image](https://user-images.githubusercontent.com/3308167/153750671-b16ae22c-0814-43c0-af80-77703c55c063.png)

Actual
![image](https://user-images.githubusercontent.com/3308167/153750693-cc3b49ed-9fc6-4931-a0d5-764bee75cc45.png)

**Comment by layershifter** [comment]
Compared to Semantic UI the search behavior is indeed different. However, changing/aligning it now means huge breaking changes. To customize search behavior you can use custom search function: https://react.semantic-ui.com/modules/dropdown/#usage-custom-search-function

Here is the snippet that implements "starts with" option:

```jsx
function customSearch(options, searchQuery) {
  return options.filter((option) =>
    option.text.toLowerCase().startsWith(searchQuery.toLowerCase())
  );
}

const DropdownExampleSearchSelection = () => (
  <Dropdown
    placeholder="Select Country"
    search={customSearch}
    fluid
    selection
    options={countryOptions}
  />
);
```

https://codesandbox.io/s/semantic-ui-example-forked-6868h?file=/example.js:1482-1818
