### ISSUE TITLE
Can't resolve 'clsx' in semantic-ui-react

### ISSUE THREAD

**Issue by polskyDev** [Semantic-Org/Semantic-UI-React#4335]
```
ERROR in ./node_modules/semantic-ui-react/dist/es/elements/Header/HeaderContent.js 2:0-22
Module not found: Error: Can't resolve 'clsx' in 'C:\repo\app-p\node_modules\semantic-ui-react\dist\es\elements\Header'
 @ ./node_modules/semantic-ui-react/dist/es/index.js 107:0-61 108:0-43
 @ ./src/App.tsx 18:0-51 71:47-53 74:37-43
 @ ./src/index.tsx 10:0-24 19:38-41 26:29-34:3 26:2-34:4 27:18-42
```

I tried remove yarn.lock and node_modules :(

**Comment by layershifter** [comment]
Hey, this looks like an issue with your setup as `clsx` is declared in `dependencies` of the package properly:

https://github.com/Semantic-Org/Semantic-UI-React/blob/0e8a00e975ac44b6a4d18d974c971fc209757f64/package.json#L75

Please provide a repro repo so we could take a look.
