### ISSUE TITLE
Docs: Generation issue of docgenInfo.json on Windows

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#434]
There are build error of docs on Windows.

![image](https://cloud.githubusercontent.com/assets/14183168/17939977/a04b9948-6a35-11e6-9293-03ff466eaf29.png)

As @levithomason  decided [there](https://github.com/TechnologyAdvice/stardust/pull/382#issuecomment-242136417), generated `docgenInfo.json` uses only unix-like path delimiter (`/`) while Windows requires `\`.

Extracted from #382.

**Comment by levithomason** [comment]
I've got a branch going against this issue.

**Comment by layershifter** [comment]
![image](https://cloud.githubusercontent.com/assets/14183168/17978584/720e5992-6aff-11e6-874e-dfb841ee1739.png)

I reopened issue, seems not fixed.

**Comment by levithomason** [comment]
Can you try this in `ComponentDescription.js` @ line 16?

``` diff
-const pathSepRegEx = new RegExp(__PATH_SEP__, 'g')
+const pathSepRegEx = new RegExp(_.escapeRegExp(__PATH_SEP__), 'g')
```

**Comment by layershifter** [comment]
It works :+1:
