### ISSUE TITLE
Semantic UI cannot be used as a JSX component

### ISSUE THREAD

**Issue by JT3nnis** [Semantic-Org/Semantic-UI-React#4351]
Hi!

### Steps
**What is my issue:**
Unfortunately as of yesterday all of our builds are failing because of an issue with Semantic Components throwing a TS2786 error. 

The error reads:
'Button' cannot be used as a JSX component.
  Its instance type 'Button' is not a valid JSX element.
  
I can recreate this error with any Semantic UI component.

I have abstracted out our entire codebase to simply render App and the error still persists.
import React from "react";
import { Button } from "semantic-ui-react";

const App = () => {
  return (
    <React.Fragment>
      <Button></Button>
    </React.Fragment>
  );
};

**What I've tried**
Upgrading all npm libraries in the project
Upgrading individually react, typescript, and semantic-ui

**Additional Notes**
An old compiled node_modules folder will still not throw any errors, but for because in our build step we run npm install before running npm build, these errors seems to persist in a recent update to one of these packages.

### Expected Result
No Typescript error thrown when importing and using a Semantic UI Component

### Actual Result
'Button' cannot be used as a JSX component.
  Its instance type 'Button' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("C:/Work/portal-app/ClientApp/node_modules/@types/hoist-non-react-statics/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.ts(2786)

### Version
2.0.1

I've also tried 2.1.2

### Testcase
Create a simple react app and install typescript and semantic UI.

Any assistance would be helpful. Thanks!

**Comment by layershifter** [comment]
Please provide a repro on CodeSandbox or a repo to clone.

**Comment by JT3nnis** [comment]
Had to upgrade node to latest version (16.14.2) and any dependent packages. Solved. Thanks.

**Comment by Kutalia** [comment]
In my case I actually had to downgrade @types/react to 17.0.39 to match my React 17 version.
