### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#4354]
- [ ] Allow in `peerDependencies`
  - [ ] to our package
  - [ ] to dependencies
    - [ ] https://github.com/microsoft/fluentui/pull/22542
    - [ ] https://github.com/floating-ui/react-popper/pull/440
- [x] #4352
- [x] #4350

**Comment by orangecoding** [comment]
There are some issues throughout the semantic codebase, see
 https://github.com/facebook/react/issues/24391

**Comment by layershifter** [comment]
> There are some issues throughout the semantic codebase, see [facebook/react#24391](https://github.com/facebook/react/issues/24391)

Can you please provide a repro case/fill an issue for this? From a linked issue I don't see an exact problem with SUIR.

**Comment by VicFrolov** [comment]
Is there any estimate for react 18 support?

**Comment by layershifter** [comment]
Released in `semantic-ui-react@2.1.3`.
