### ISSUE TITLE
Modal: Support showing Close (X) Icon

### ISSUE THREAD

**Issue by brsanthu** [Semantic-Org/Semantic-UI-React#436]
It would be nice if we can specify a prop to show close (x) icon on the top right corner, which would close the model and fires onClose or onHide.

**Comment by levithomason** [comment]
I'd merge a PR for this.  It should be very easy since we already have close listeners setup.  We'd just need to include an icon prop and add the close handler.  Probably default the icon to `close` but allow it to be configured via props.

**Comment by brsanthu** [comment]
@levithomason you are so fast :)

What you say makes sense. I will try to take a look and create a PR.

**Comment by levithomason** [comment]
I hate waiting :/  So, I hate making ppl wait 🎉
