### ISSUE TITLE
pointer-events should be set to none when element is loading

### ISSUE THREAD

**Issue by therealgilles** [Semantic-Org/Semantic-UI-React#4365]
### Problem description
When an element (button for instance) is in loading state, its pointer-events should be set to none to avoid interactions.

### Proposed solution
See https://github.com/Semantic-Org/Semantic-UI/issues/1744.
I don't think this has been implemented in Semantic-UI-React.

**Comment by brianespinosa** [comment]
Hi @therealgilles 

The `loading` prop merely renders a compatible class to pick up styles from Semantic UI, all of which are outside of this React project. If the CSS you are using has been compiled with `pointer-events: none;` for `.ui.button.loading` then you will get what you are looking for. There are many ways to set up the styles, or even theme/build your own.

We are not setting the `pointer-events: none;` style manually to the button in the React bindings, nor are they doing so in the parent SUI project. This is just CSS and class names, all of which are out of scope for these React bindings.

**Comment by therealgilles** [comment]
Thanks for your response @brianespinosa and for pointing that out. I should have read more carefully. I am using the default theme but was not seeing the pointer-events: none behavior as I was expecting. It will look into it further. Closing.
