### ISSUE TITLE
TypeScript version 4.8.4 Tprops error

### ISSUE THREAD

**Issue by timduffin** [Semantic-Org/Semantic-UI-React#4391]
## Bug Report
Type fails build with `typescript@4.8.4`.

Opened a pr here https://github.com/Semantic-Org/Semantic-UI-React/pull/4390

### Steps
`npm / yarn / pnpm build`

### Expected Result
`built`

### Actual Result
```
73 export type SemanticShorthandCollection<TProps> = SemanticShorthandItem<TProps>[]
                                               ~~~~~~
    This type parameter might need an `extends Record<string, any>` constraint.
```

### Version
semantic-ui-react@2.1.3

**Comment by layershifter** [comment]
Fixed by #4390
