### ISSUE TITLE
[Button] should not throw findDOMNode warning in browser

### ISSUE THREAD

**Issue by codewizard-dt** [Semantic-Org/Semantic-UI-React#4396]
### Steps
- Be using React ^18 in StrictMode
- Add Button component to a page
- Open Dev Tools and look at console

### Expected Result
There should be no warnings

### Actual Result
There is a big red warning
```
react-dom.development.js:86 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of RefFindNode which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at button
    at RefFindNode (http://localhost:3000/static/js/bundle.js:2245:35)
    at Ref (http://localhost:3000/static/js/bundle.js:2186:24)
    at Button (http://localhost:3000/static/js/bundle.js:66088:29)
```

### Version
Semantic-UI-React 2.1.3
React ^18.2

**Comment by yveslange** [comment]
Same issue for multiple other components (Dimmer, ...)

**Comment by layershifter** [comment]
Please try the latest beta i.e. `semantic-ui-react@3.0.0-beta.0`, it does not use `findDOMNode` anymore.

**Comment by yveslange** [comment]
Using `3.0.0-beta.0` with `semantic-ui-css@^2.5.0` fixed the issue. Thanks @layershifter

**Comment by achimkoellner** [comment]
@layershifter when will v3 be considered stable?

**Comment by layershifter** [comment]
@achimkoellner once issues from #4409 will be resolved.

---

Closing this as the problem is resolved in the latest beta.
