### ISSUE TITLE
Dropdown Items mis-alligned with the menu. 

### ISSUE THREAD

**Issue by arjitacharya1994** [Semantic-Org/Semantic-UI-React#4422]
Even in the [documentation](https://react.semantic-ui.com/modules/dropdown/), the dropdown items seem to be misaligned. 

PFA- 
![image](https://user-images.githubusercontent.com/42516146/224923868-3727429e-a309-476a-83c4-c32bd27727aa.png)

As investigated, the potential reason behind this is the below styles (scss equivalent)

```
.ui.selection.dropdown {
  .menu {
    min-width: calc(100% + 2px) 
    width: calc(100% + 2px) 
  }
}
```

Can someone share the reason for this styling and the impact if I modify it locally. 

Thanks!

**Comment by levithomason** [comment]
Not seeing this in SUIR v2.1.4 using Chrome Version 113.0.5672.126:

<img width="721" alt="image" src="https://github.com/Semantic-Org/Semantic-UI-React/assets/5067638/ac548b64-7058-4d7c-8e0a-986cad79624d">

If your issue is persisting, please note the version of SUIR and your browser.
