### ISSUE TITLE
semantic ui react dimmer warning finddomnode is deprecated in strictmode

### ISSUE THREAD

**Issue by PTAHume** [Semantic-Org/Semantic-UI-React#4438]
When I use Dimmer from semantic-ui-react I get this warning:

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of RefFindNode which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

But as I see the problem with Dimmer was resolved years before: [link](https://github.com/Semantic-Org/Semantic-UI-React/issues/2732).

So what's the root of warring and how to avoid it (except to stop using strict mode)?

```
import React from "react";
import { Dimmer } from "semantic-ui-react";

const App = () => (
  <React.StrictMode>
    <Dimmer>Hey</Dimmer>
  </React.StrictMode>
);
export default App;
```

Example:
React 18.2.0, Semantic-ui-react 2.1.4 Link to codesandbox.io](https://codesandbox.io/s/dimmer-in-strictmode-react-18-2-0-forked-9jn3jn)

I am not the only one who has had this issue either : https://stackoverflow.com/questions/75694953/semant

**Comment by layershifter** [comment]
Please try to use v3-beta (https://react.semantic-ui.com/migration-guide), it supports native ref forwarding.

**Comment by PTAHume** [comment]
thank you thats way better :)
