### ISSUE TITLE
`Popup` component is acting mega weird after `3.0.0`

### ISSUE THREAD

**Issue by dimitur2204** [Semantic-Org/Semantic-UI-React#4442]
## Bug Report
When there are multiple `Popup` component on one page they seem to somehow share `refs` (I haven't looked at code - just assuming). And when you hover over they start popping up left and right.

### Steps
1. Go to [https://react.semantic-ui.com/elements/icon/](https://react.semantic-ui.com/elements/icon/)
2. Start hovering over the icons rapidly
3. See how the tooltips start popping up everywhere, stop closing etc.

### Expected Result
Well for them to work properly :D

### Actual Result
![image](https://github.com/Semantic-Org/Semantic-UI-React/assets/61479393/20dff780-ec89-4449-af29-d2c46f02a907)

### Version
3.0.0-beta-1

**Comment by layershifter** [comment]
Fixed in #4445.
