### ISSUE TITLE
How to use jQuery from the window instead of Stardust's?

### ISSUE THREAD

**Issue by xxRockOnxx** [Semantic-Org/Semantic-UI-React#445]
I have stuffs that depends partially on jQuery and React. Stardust's jQuery overwrites the one from the window like what the error from the console is saying. How do I manually disable it and use the one from the window?

**Comment by levithomason** [comment]
If you're using webpack, then you may be able to override Stardust's jQuery via externals or aliases.  Stardust just `require('jquery')`.  We currently do not provide a way to do this.  This is because jQuery will be removed very soon, the final PR for that is here #400.
