### ISSUE TITLE
bug: Popup is always hidden on scroll

### ISSUE THREAD

**Issue by kaelhem** [Semantic-Org/Semantic-UI-React#4476]
## Bug Report
It seems not possible now to keep a popup opened during page scroll. 

### Steps
Go on https://react.semantic-ui.com/modules/popup/#usage-default-open and observe that the popup is hidden during page scroll.

![bloggif_66069abfe616a](https://github.com/Semantic-Org/Semantic-UI-React/assets/1114181/716a70f6-5c14-4196-ab7a-3e2767991fe0)

### Expected Result
The popup should respect the `open` property.

### Actual Result
The popup is hidden during page scroll, even with `hideOnScroll={false}`.

### Version
This bug affect all versions 3 (3.0.0-beta0, 3.0.0-beta1, 3.0.0-beta2) but not version 2 (I tried 2.1.4 and 2.1.5).

**Comment by jjylha** [comment]
Yes, hideOnScroll does not work as expected in SUI-R version 3. The popup is always hidden by default on scroll and setting hideOnScroll={false} has no effect.

On mobile screens popups with tall content that overflow the screen area become inaccessible. Any time you try to scroll to see the whole popup content the popup will be closed. Trying to control popup via open property does not help but the popup is always force closed.

**Comment by jjylha** [comment]
Created this with a sandbox to better explain the issue: https://github.com/Semantic-Org/Semantic-UI-React/issues/4483

**Comment by layershifter** [comment]
Fixed in #4490. I will trigger a release later this week.

**Comment by amarls2** [comment]
Hi! Just checking in — is there an update on the release that includes fix #4490?
