### ISSUE TITLE
Standardize childKey and shorthand props

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#449]
It seems, that [here](https://github.com/TechnologyAdvice/stardust/blob/master/src/views/Card/CardGroup.js#L30) is bug.

``` jsx
const content = !items ? children : items.map(item => {
  const key = item.key || [item.header, item.description].join('-')
  return <Card key={key} {...item} />
})
```
- `key` prop will be always overwritten with `item` contents;
- component uses `key` prop instead of `childKey`.

It can be rewritten as:

```
if(!children) {
  return <ElementType {...rest} className={classes}>{children}</ElementType>
}

const content = items.map(item => {
  const {childKey, ...itemProps} = item
  const finalKey = childKey || [item.header, item.description].join('-')

  return <Card {...item} key={childKey} />
})
```
- `key` cannot be `number`, I think we need allow this:

``` jsx
childKey: PropTypes.oneOfType([
  PropTypes.number,
  PropTypes.string,
]),
```

---

Also, I think there is problem with keys in all the components and current solution with `childKey` is little evil.

**Comment by levithomason** [comment]
> key prop will be always overwritten with item contents;

It is only overridden if it exists, but the assignment already assigns it if exists.  So, if there is no `key` the header/description is used, if there is a `key` then that is used.

``` js
const key = item.key || ...
```

> component uses key prop instead of childKey.

Agreed, we should update this.

> It can be rewritten as:

For clarity and consistency, it should have likely been written:

Did you mean `if (children)` instead of `if (!children)`?  Otherwise, it will render the markup that uses children when there are no children.

Also, `items.map()` will fail if there are not items and no children.  Suggest using `_.map(items)` which handles the maybe case and always returns an array.

> key cannot be number, I think we need allow this:

Why not?  Index can be passed which is a number.  Also, if a user is using some kind of numerical id key mechanism, we would want to allow that.  Let me know if there is a bug in doing so or some documentation I am not aware of on this.

> Also, I think there is problem with keys in all the components and current solution with childKey is little evil.

I'd like to hear the evil parts.  If you have any suggestions, those would be great as well!

**Comment by layershifter** [comment]
> Did you mean if (children) instead of if (!children)?
> Suggest using _.map(items) which handles the maybe case and always returns an array.

`!items`, so, it will not fail :smile: 

> Why not?

And therefore it is necessary to fix it [there](https://github.com/TechnologyAdvice/stardust/blob/master/src/views/Card/CardGroup.js#L69), [there](https://github.com/TechnologyAdvice/stardust/blob/c27471566f2c6723fe95635e7231973290ee33a4/src/views/Feed/Feed.js#L78) and [there](https://github.com/TechnologyAdvice/stardust/blob/c27471566f2c6723fe95635e7231973290ee33a4/src/views/Statistic/StatisticGroup.js#L71).

> I'd like to hear the evil parts.

We create an index from shorthand properties, so we can't them as nodes. In future will be be able to do that:

``` jsx
const items = [
  {header: <div>Header</div>}
]

<Component items={items} />
```

**Comment by levithomason** [comment]
> `!items`, so, it will not fail 😄

I mean if the user does not pass an `items` prop nor a `children` prop then `items.map` will be invoked while `items` is `undefined`.  Resulting in `undefined.map()` which will throw: `Uncaught TypeError: Cannot read property 'map' of undefined`.  Whereas, `_.map(undefined)` will simply return an empty array.

> And therefore it is necessary to fix it there, there and there.

Indeed, we should consider `customPropTypes.childKey` or similar.

> We create an index from shorthand properties, so we can't them as nodes. In future will be be able to do that:

I'm not sure we will support passing nodes as shorthand props.  I think it is better to use sub components in you need to use nodes.

However, if we did support passing nodes, then we would have to simply require a `childKey` if the shorthand prop is a node:

``` jsx
const items = [
  { header: <div>Header</div>, childKey: 'a-header-key' }
]

<Component items={items} />
```

``` jsx
Component.propTypes = {
  childKey: customPropTypes.every([
    customPropTypes.childKey,                   // optional childKey
    customPropTypes.givenProps(
      { header: propTypes.node.isRequired },    // if header passes this PropType
      customPropTypes.childKey.isRequired       // childKey is required
    )
  ])
}
```

If we chose do this, we may bundle the `giveProps` feature into `customPropTypes.childKey()` so we can require the `childKey` if certain props are given:

``` jsx
childKey: customPropTypes.every([
  customPropTypes.childKey({            // optional childKey
    header: propTypes.node.isRequired,  // require childKey if header passes propType
  }),
])
```

**Comment by layershifter** [comment]
> I'm not sure we will support passing nodes as shorthand props.

I think it's better to leave this, but it would be good to keep in mind for future.

> Indeed, we should consider customPropTypes.childKey or similar.

Looks pretty, I'm also thinking about `customPropTypes.shorthand` for [this](https://github.com/TechnologyAdvice/stardust/blob/c27471566f2c6723fe95635e7231973290ee33a4/src/views/Statistic/Statistic.js#L102).

**Comment by levithomason** [comment]
> I think it's better to leave this, but it would be good to keep in mind for future.

Agreed.

> Looks pretty, I'm also thinking about customPropTypes.shorthand for this.

Also agreed.  How about we update this issue then to standardize:
1. add `customPropTypes.childKey()`
2. add `customPropTypes.shorthand`
3. implement in all components that use shorthand and/or child `key` props

?

**Comment by layershifter** [comment]
1. Add `commontest` for `customPropTypes.shorthand`.

``` jsx
describe('description prop', () => {
    it('renders CardDescription component', () => {
      const text = faker.hacker.phrase()

      shallow(<CardContent description={text} />)
        .should.contain(<CardDescription content={text} />)
    })
  })
```

``` js
common.propIsShorthand(CardContent, 'description', CardDescription)
```

---

I think we need PR for this :smiley_cat:

**Comment by levithomason** [comment]
Great call, we can add that test and assume the text is rendered in the sub component for now.  I really like that :D

**Comment by levithomason** [comment]
PR coming

**Comment by levithomason** [comment]
See https://github.com/TechnologyAdvice/stardust/pull/452

**Comment by layershifter** [comment]
With the merge of #618 this work is done. Closing.
