### ISSUE TITLE
MenuItem is rendered as active link with React 15.3.1

### ISSUE THREAD

**Issue by chuan137** [Semantic-Org/Semantic-UI-React#460]
Could be this React version not supported yet? I have created a simple page with the following App code

```
import React, { Component } from 'react'
import { Button, Menu } from 'stardust'

export default class TryStardust extends Component {
  render() {
    return (
      <div>
        <Menu>
          <Menu.Item>ABC</Menu.Item>
        </Menu>
        <Button>Hello</Button>
      </div>
    )
  }
}
```

Add the generated code is 

```
<div data-reactroot="">
  <div class="ui menu">
    <a class="active item">
      <!-- react-text: 4 -->ABC<!-- /react-text -->
    </a>
  </div>
  <button type="button" class="ui button">Hello</button>
</div>
```

**Comment by levithomason** [comment]
We support React 15.x.  The doc site is also a React app using 15.x.

However, the Menu is a legacy component undergoing a complete overhaul, see #382.  Unfortunately, the old (currently published) behavior automatically made the first item active if no other item was active.  Thankfully, there is no such non-sense in the revamped Menu component.
