### ISSUE TITLE
Dropdown: support an array of string|element options

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#470]
Currently, the Dropdown takes an array of plain objects via the `options` prop.  These objects are used to create the `<Dropdown.Item />` children.  Each object is spread as props on each item:

``` js
// Dropdown.js renderItems()

return _.map(options, (opt, i) => (
  <DropdownItem
    key={`${opt.value}-${i}`}
    active={isActive(opt.value)}
    onClick={this.handleItemClick}
    selected={selectedIndex === i}
    onMouseDown={e => e.preventDefault()}
    {...opt}
  />
))
```

We should also accept an array of strings or elements.  An array of strings would be used as the item text and value.  Whereas, an array of elements would be cloned.

We created `src/factories` for this exact purpose.  They handle mapping a primitive value to props, spreading props objects, and cloning elements while merging className and spreading props.  We should then use `createFactory` to create a `createDropdownItem` factory, see `src/factories/index.js`.  We would then use the `createDropdownItem` factory in place of the `_.map()` callback used above.

**Comment by mikesparr** [comment]
The docs state that `Dropdown.Item` onClick event is supposed to trigger `func(event, value, text)` but I see the `text` value as undefined and only ever see value.  Is this incomplete or part of this request to enhance `Dropdown`?  (I was trying to get the name and value of selected item but only ever get the value)

```
    handleItemClick = (e, value, text) => {
    console.log(value);
    console.log(text);
        } // displays value but text is `undefined`


        <Dropdown 
                trigger={<Icon name='settings'/>} 
                pointing='top right' 
                icon={null}>
          <Dropdown.Menu>
              <Dropdown.Item text='View' name='view' value={key} onClick={this.handleItemClick} />
              <Dropdown.Item text='Delete' name='delete' value={key} onClick={this.handleItemClick} />
          </Dropdown.Menu>
        </Dropdown>
```

**Comment by levithomason** [comment]
@mikesparr Thanks, the docs are wrong and the method needs updated.  See #805 for the fix.  We'll pass all props back in place of `value`.

**Comment by levithomason** [comment]
Closing this for housekeeping. Per my notes in the PR, I'm not sure this work is worth it. The gains are minor and the repercussions are major.  We've also not had hardly any community interest here.
