### ISSUE TITLE
Import or Html Load ?

### ISSUE THREAD

**Issue by cristiandley** [Semantic-Org/Semantic-UI-React#472]
By default semantic seems to dont load the css, so i have two ways to solve this, one is using html link and in the other hand importing/requiring semantic (**im building an example using meteor-react-apollostack**)

_This Works!_

``` html
<link href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.css" rel="stylesheet">
```

_This will throw and error_:

```
import ('semantic-ui-css/semantic'); 
```

How do you load your css ?

**Comment by levithomason** [comment]
The Stardust docs just use a cdnjs link tag in the head with the version number injected from the installed node module version.  Some of our apps use Webpack [sass-loader](https://github.com/jtangelder/sass-loader) + [css-loader](https://github.com/webpack/css-loader) + [style-loader](https://github.com/webpack/style-loader) to compile sass and inject a style tag.  We load css differently in different apps.

Though I'm not a Meteor user, I know it has it's own package system and paradigms.  There is also [Semantic-UI-Meteor](https://github.com/Semantic-Org/Semantic-UI-Meteor) which you may be interested in.

**Comment by cristiandley** [comment]
I just wanted to implement it without atmosphere (meteor package manager) and use NPM purely (that is supported) .

I will stick to the html head loading.

Thanks!

**Comment by levithomason** [comment]
Long term, v2, v3, I'm interested in trying to bring more styling/theming into this library.  I've got a few ideas and experiments going.  There has also been interest expressed for this as in #366.
