### ISSUE TITLE
Modal always logging ?

### ISSUE THREAD

**Issue by cristiandley** [Semantic-Org/Semantic-UI-React#483]
It is correct to have the modal always logging everything ?

like:

``` bash
browser.js:112 stardust:modal handleDimmerClick() +1s
browser.js:112 stardust:modal onHide() +0ms
browser.js:112 stardust:modal componentDidUpdate() +6ms
browser.js:112 stardust:modal modal changed to hidden +1ms
browser.js:112 stardust:modal handleHide() +0ms
```

I dont know if its a feature or just a issue :confused: . Thanks !

**Comment by levithomason** [comment]
You can control what the debugger logs, see README.md

https://github.com/TechnologyAdvice/stardust#debugger

**Comment by cristiandley** [comment]
Oh, i feel a fool. I didnt see that section. Thanks!

**Comment by levithomason** [comment]
No worries
