### ISSUE TITLE
fix(Label): add missing Detail sub component

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#488]
All components with [component parts](http://semantic-ui.com/introduction/glossary.html#project-terminology) should have a corresponding sub component for that part.  Additionally, every part should have a shorthand configuration prop.  Example, Card has a `meta` "part".  Therefore:

``` jsx
<Card meta='More info here' />

<Card>
  <Card.Meta>More info here</Card.Meta>
</Card>
```

The only part a Label has is the [Detail](http://semantic-ui.com/elements/label.html#detail), therefore:

``` jsx
<Label detail='Friend' />

<Label>
  <Label.Detail>More info here</Label.Detail>
</Label>
```

Shorthand is already supported, however, we are missing the sub component.

**Comment by jeffcarbs** [comment]
`Label` also has props for some additional detail props:
- detailAs
- onDetailClick

Should those continue to be supported?

This brings up a broader question about being able to more fully customize subcomponents via shorthand props. A thought that comes to mind is being able to pass either:
- a string to be used for text/content for the subcomponent
- an object to be spread as props to the subcomponent

For example:

``` js
// Proptypes
detail: PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.shape(LabelDetail.propTypes),
])

// Rendering
renderDetail () {
  const { detail } = this.props

  if (!detail) return

  return _.isObject(detail)
    ? <LabelDetail {...detail} />
    : <LabelDetail content={detail} />
}
```

Thoughts?

**Comment by levithomason** [comment]
> Should those continue to be supported?

`detailAs` - No, instead you can pass a props object `detail={{ as: 'a', content: 'Friend' }}`
`onDetailClick` - No, instead you would `detail={{ onClick: handleDetailClick }}` or sub components.

> This brings up a broader question about being able to more fully customize subcomponents via shorthand props.

Yep, this and more is already supported by the [`Factory` returned by `createFactory`](https://github.com/TechnologyAdvice/stardust/blob/master/src/factories/createFactory.js#L29).  It handles a primitive value mapped to a prop, a props object, or an element which is cloned.  In all cases, the className is also merged for you.  Additionally, you can pass extra props when you `createFoo(...)`.

The issue here is that not all shorthand props are using a factory created by `createFactory()`.  Some are simply passing the value as is.  The discussion and work on standardizing shorthand propTypes, factories, and tests is here https://github.com/TechnologyAdvice/stardust/pull/452.

**Comment by layershifter** [comment]
Working there.
