### ISSUE TITLE
Dropdown: <Dropdown.Item as={'a'} /> with href does not function appropriately

### ISSUE THREAD

**Issue by jeffcarbs** [Semantic-Org/Semantic-UI-React#493]
Going to post some thoughts below, but for context here's the actual issue I'm experiencing:

``` js
import React from 'react'
import { Dropdown, Icon } from 'stardust'

const stopDomEvent = (e) => {
  e.preventDefault()
  e.stopPropagation()
  e.nativeEvent.stopImmediatePropagation()
}

const itemProps = {
  as: 'a',
  href: '/something',
  onClick: (e) => {
    stopDomEvent(e)
    console.log('clicked!', e)
  }
}

const DropdownTriggerExample = () => (
  <Dropdown>
    <Dropdown.Menu>
      <Dropdown.Item disabled>
        Signed in as <strong>Bob Smith</strong>
      </Dropdown.Item>
      <Dropdown.Divider />
      <Dropdown.Item {...itemProps}>Your Profile</Dropdown.Item>
      <Dropdown.Item {...itemProps}>Your Stars</Dropdown.Item>
      <Dropdown.Item {...itemProps}>Explore</Dropdown.Item>
      <Dropdown.Item {...itemProps}>Integrations</Dropdown.Item>
      <Dropdown.Item {...itemProps}>Help</Dropdown.Item>
      <Dropdown.Divider />
      <Dropdown.Item {...itemProps}>Settings</Dropdown.Item>
      <Dropdown.Item {...itemProps}>Sign Out</Dropdown.Item>
    </Dropdown.Menu>
  </Dropdown>
)

export default DropdownTriggerExample
```

The `onClick` is never fired, here's the console output: 

```
stardust:dropdown handleBlur() +2s
stardust:dropdown render() +1ms
stardust:dropdown props +1ms Object {trigger: Object, children: Object, icon: "dropdown", additionLabel: "Add:", noResultsMessage: "No results found."…}
stardust:dropdown state +1ms Object {value: "", searchQuery: "", selectedIndex: -1, focus: false, open: true…}
stardust:dropdown renderHiddenInput() +1ms
stardust:dropdown name:      undefined +1ms
stardust:dropdown selection: undefined +0ms
stardust:dropdown value:      +1ms
stardust:dropdown renderLabels() +1ms
stardust:dropdown componentDidUpdate() +1ms
stardust:dropdown changed state: +1ms Object {focus: true}
stardust:dropdown close() +0ms
stardust:dropdown dropdown is not yet closed +1ms
stardust:dropdown render() +1ms
stardust:dropdown props +0ms Object {trigger: Object, children: Object, icon: "dropdown", additionLabel: "Add:", noResultsMessage: "No results found."…}
stardust:dropdown state +1ms Object {value: "", searchQuery: "", selectedIndex: -1, focus: false, open: false…}
stardust:dropdown renderHiddenInput() +1ms
stardust:dropdown name:      undefined +0ms
stardust:dropdown selection: undefined +1ms
stardust:dropdown value:      +1ms
stardust:dropdown renderLabels() +0ms
stardust:dropdown componentDidUpdate() +4ms
stardust:dropdown changed state: +1ms Object {open: true, dropdownClasses: "active visible", menuClasses: "visible"}
stardust:dropdown close() +1ms
stardust:dropdown dropdown is already closed +0ms
```

Removing the `href` attribute, it works. Here's the output:

```
clicked! Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, _dispatchListeners: Array[2], _dispatchInstances: Array[2], nativeEvent: MouseEvent…}
```

Pretty sure it was introduced via related to this PR: https://github.com/TechnologyAdvice/stardust/pull/467

I kinda think I know what's happening here and why that PR works in other cases...

When you click on a regular item, or an anchor without an href, focus leaves the `Dropdown` onMouseDown of some other element, **non-focusable** (the key part) element. That PR prevents the default of the `onMouseDown` on a dropdown item, which prevents the blur. In fact, after clicking an item the menu closes from the handleClick callback and calling `document.activeElement` shows that the dropdown still has focus.

My hunch is that by adding an `href` to the `a` tag, you make it focusable. So the blur doesn't come from the `onMouseDown` but instead by the fact that the `Dropdown.Item` is now focused. Rolling back this one change (https://github.com/TechnologyAdvice/stardust/pull/467/files#diff-609214949026e594dbfd98481664c928R283), clicking an item with an href, and inspecting the `document.activeElement` shows that the `a` is in fact focused.

Somewhat wider gripe: The dropdown element (and now search, which was based on dropdown) is doing some event manipulation within click handlers to prevent the dropdown from closing. e.g. 

``` js
  handleItemClick = (e, value) => {
    // ...

    // prevent toggle() in handleClick()
    e.stopPropagation()
    // prevent closeOnDocumentClick() if multiple or item is disabled
    if (multiple || item.disabled) {
      e.nativeEvent.stopImmediatePropagation()
    }

    // ...
```

Thoughts on keeping a ref to the dropdown itself and just preventing things like `closeOnDocumentClick` via something like (which is actually already done in `<Modal>`):

``` js
if (this.refs.self.contains(e.target)) return
```

For the blur event, all browsers but FireFox support a property called `relatedTarget` which is the node that focus was moved to, so in the `handleBlur` we could have something like:

``` js
if (this.refs.self.contains(e.relatedTarget)) return
```

I can experiment with a PR to see what unforeseen issues this would create. Just wanted to get your thoughts first to see if this is wildly off base.

**Comment by jeffcarbs** [comment]
Ok, I think the `.contains` approach is a non-starter. In many cases, by the time the top-level event handler (e.g. `closeOnDocumentClick`) is called the DOM has already changed:
- When then menu is set to hidden it's removed from the DOM entirely.
- When multi-select `Dropdown.Items` are selected they're removed from the menu.

The one in `handleBlur` actually works, so that could still be a solution for the `href` issue.

This issue is actually pretty pervasive as is prevents using _any_ focusable element within the dropdown itself. I just realized a few other quirks that I couldn't explain but were actually manifestions of this:
- Using a `<button>` as a `trigger`. I'm guessing clicking on the button focuses it, then clicking on an item blurs the button which bubbles to the `Dropdown`.
- Using a `<button>` within a menu item (e.g. notifications -> mark-as-read)

**Comment by levithomason** [comment]
Yuck.  This is precisely what the original TODO item was for.  The ordering of events and methods to attempt to capture them make this a difficult issue.  I'd almost rather roll back the closeOnBlur changes for now instead.

Then, I'd like to add some tests for the cases you've raise with focusable elements.  I think these are 100% valid.

Finally, if we did re-add focus/blur functionality, it seems we should use the ref approach and do it in a timeout or animation frame so as to let the original set of events finish propagating.  Not excited about that, but it is my first thought.  Again, I'd rather just not have close on focus than a hack or a bug.

Thoughts?

**Comment by jeffcarbs** [comment]
That works for me. The "close on blur" functionality is really only relevant for tabbing, since a click will still close it:
- outside the menu via the `closeOnDocumentClick` or a selection
- inside the menu via `handleItemClick`
- on the "trigger" portion via `handleClick`

And since `focus` doesn't open the menu I think the tab-to-close is less necessary.

**Comment by levithomason** [comment]
Looking into this now, may result in a rollback.
