### ISSUE TITLE
Dropdown open drawer goes under modal container

### ISSUE THREAD

**Issue by brsanthu** [Semantic-Org/Semantic-UI-React#497]
When I add a dropdown inside a modal, the open drawer panel goes under the modal content area and hence part is getting hidden. I think the Dropdown open panel should come over modal container area and modal container height should not increase.

![combobox-modal-overlap](https://cloud.githubusercontent.com/assets/842964/18482759/599b2eda-7996-11e6-9211-ed5022952a9b.png)

Can you please give me a hint where to fix this? If so, I can raise a PR.

**Comment by levithomason** [comment]
This is a core CSS issue related to z-index values.  Stardust only provides the JavaScript functionality that generates valid SUI markup.

Suggest looking for existing issues on the main repo, and if one is not yet open, consider opening one there.  It would either be a [new Dropdown bug](https://github.com/Semantic-Org/Semantic-UI/issues/new?title=[Dropdown]%20-%20Your%20Bug%20Name&body=**Steps%20to%20Reproduce**%0A1.%20Do%20something%0A2.%20Do%20something%20else.%0A3.%20Do%20one%20last%20thing.%0A%0A**Expected**%0AThe%20Dropdown%20should%20do%20this%0A%0A**Result**%0AThe%20Dropdown%20does%20not%20do%20this%0A%0A**Testcase**%0A%28fork%20this%20to%20get%20started%29%0Ahttp://jsfiddle.net/rduvhn8u/1/), or [new Modal bug](https://github.com/Semantic-Org/Semantic-UI/issues/new?title=[Modal]%20-%20Your%20Bug%20Name&body=**Steps%20to%20Reproduce**%0A1.%20Do%20something%0A2.%20Do%20something%20else.%0A3.%20Do%20one%20last%20thing.%0A%0A**Expected**%0AThe%20Modal%20should%20do%20this%0A%0A**Result**%0AThe%20Modal%20does%20not%20do%20this%0A%0A**Testcase**%0A%28fork%20this%20to%20get%20started%29%0Ahttp://jsfiddle.net/rduvhn8u/1/) depending on how you see it.

**Comment by brsanthu** [comment]
Thanks. Will try to understand the issue and correct in the styles. Otherwise, will open issue in main repo.

**Comment by dkwin** [comment]
@brsanthu 

This has been closed but I was wondering if there was a fix for this issue?

I'm seeing the same for a table component I'm working on.

![overlaycelldropdown](https://cloud.githubusercontent.com/assets/3934306/20404215/f935e23c-acd1-11e6-8e08-994af0c3bb45.gif)

Left side is a semantic ui dropdown and right side is a native dropdown.  Notice that the right dropdown does not clip.

**Comment by levithomason** [comment]
My guess is that it is a `z-index` issue on the dropdown menu.  Have you tried something like this for verifying?

``` scss
.ui.dropdown .menu {
  z-index: 999999 !important;
}
```

**Comment by dkwin** [comment]
@levithomason 

Yeah, I've tried to mess around the z index and no luck.    You mentioned I would open this issue up with semantic-ui-css repo?

**Comment by levithomason** [comment]
You'd want to open it up here: https://github.com/Semantic-Org/Semantic-UI

**Comment by levithomason** [comment]
I suppose then it must be an `overflow: hidden` issue on the Modal content then.  Also, we have an issue to "open dropdowns to the side the with most space", #720, which may also solve this problem since the Dropdown would actually open upward in that case.

I wonder if that is how SUI core is handling this use case?

**Comment by dkwin** [comment]
I'm actually trying to use the dropdown within a table cell (parent) with a fixed height.    I'll try to play around with the css and get it to work.  I'll post back for everybody else once I've resolved this or a path to move forward.

**Comment by mdo5004** [comment]
@dkwin Did you ever solve this? I'm also using a dropdown within a table cell with a fixed height.

**Comment by aindong** [comment]
@dkwin can you share the solution that you did? Thank you so much I'm also using this on a table cell

**Comment by qooban** [comment]
Looks like still not solved in the core: https://github.com/Semantic-Org/Semantic-UI/issues/1340 , but maybe [solution from this comment](https://github.com/Semantic-Org/Semantic-UI/issues/1340#issuecomment-378977803) help in some cases.

**Comment by replaysMike** [comment]
one solution is to make sure you're not using `scrolling` on `Modal.Content` and setting `overflow: revert` or `overflow: initial` on the Modal.

**Comment by pedroara** [comment]
> one solution is to make sure you're not using `scrolling` on `Modal.Content` and setting `overflow: revert` or `overflow: initial` on the Modal.

Works for me!
