### ISSUE TITLE
feat(Accordion): ability to open multiple items

### ISSUE THREAD

**Issue by brsanthu** [Semantic-Org/Semantic-UI-React#499]
Can we support opening multiple content panels at a time?

**Comment by levithomason** [comment]
I would merge a PR for that.  SUI core calls this `exclusive`.  In our case it might look like:

``` jsx
<Accordion exclusive={false} />
```

**Comment by brsanthu** [comment]
Can you please give some pointers on where to fix this?

**Comment by levithomason** [comment]
It would be in modifying `src/modules/Accordion/Accordion.js`.  It currently accepts a single `activeIndex` value.  That index is the index of the currently open panel.  It would need to accept an array of indices.  Then, every index in the array would correspond to an open panel.

**Comment by levithomason** [comment]
Fixed in https://github.com/Semantic-Org/Semantic-UI-React/pull/988
