### ISSUE TITLE
Problem with adding UI component to react-boilerplate project

### ISSUE THREAD

**Issue by kfrajtak** [Semantic-Org/Semantic-UI-React#507]
When I try to import Semantic UI component to a project seeded with [react-boilerplate](https://github.com/mxstbr/react-boilerplate)

```
import { Icon } from 'stardust';
```

I am getting following error (actually two errors, one as listed, the other one with `net` module). 

```
ERROR in ./~/debug/node.js
Module not found: Error: Can't resolve 'fs' in 'react-boilerplate\node_modules\debug'
 @ ./~/debug/node.js 170:16-30
 @ ./~/stardust/dist/lib/debug.js
 @ ./~/stardust/dist/lib/index.js
 @ ./~/stardust/dist/elements/Button/Button.js
 @ ./~/stardust/dist/elements/index.js
 @ ./~/stardust/dist/addons/Confirm/Confirm.js
 @ ./~/stardust/dist/addons/index.js
 @ ./~/stardust/dist/index.js
 @ ./app/containers/HomePage/index.js
 @ ./app/routes.js
 @ ./app/app.js
 @ multi main
```

I don't think this is an issue in your code, but I don't know how to debug it since webpack is a black box to me and I don't know why `fs` module is required in the browser. And also the chunks are not debuggable as well.

Also when the web is running, the error message is also displayed in browser window
![image](https://cloud.githubusercontent.com/assets/1510452/18610957/fd916e5e-7d2a-11e6-8ee4-ffc831d0d430.png). 

But when the server is restarted `Not found` message is displayed in the browser window.
## Steps to reproduce
- git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git
- cd react-boilerplate
- npm run setup
- npm install stardust --save-dev
- edit app\containers\HomePage\index.js, add 
  `import { Icon } from 'stardust';`

Any help will be appreciated, thank you.

Karel

PS: this was also reported to [react-boilerplate](https://github.com/mxstbr/react-boilerplate/issues/999)

**Comment by kfrajtak** [comment]
I had another look at it and after hacking the NPM module debug node.js file it works now. Which is strange since browser debug is referencing the node debug file (also the `fs` and `net` should have ringed the bell at the beginning).

**Comment by levithomason** [comment]
It looks like an error with `debug`, though likely due to the webpack configuration preventing that module from loading `fs` correctly.  Glad to you got it to work.  Closing as this is out of scope for this project.

**Comment by xiamx** [comment]
@kfrajtak I also encountered similar issue, and had to employ the same "fix".
