### ISSUE TITLE
RFC: Abstract base component to handle similarities b/w Dropdown and Search (and possibly Select as a unique component)

### ISSUE THREAD

**Issue by jeffcarbs** [Semantic-Org/Semantic-UI-React#509]
### Background

When building the `Search` component (#424) I wound up using the `Dropdown` as a guide because it was very similar. User interacts with an element (in the case of `Search`, the search input) and a menu opens which you can page through using arrow keys and select an option. Things like handling focus, blur, clickaway, etc were already handled in `Dropdown` so I mostly copy/pasted the relevant implementations.
#### Search vs Dropdown/Select

There are a lot of similarities between these two elements, but I think they fall into two overlapping-but-different chunks of functionality:
- Floating menu that appears based on some user interaction (focus/blur/click/typing)
- List of options that you can page through via arrow up/down and select

These components have a basic structure of:

```
<wrapping element>
  <some content />
  <menu (hidden/visible depending on state/props) />
</wrapping element>

// Search
<Search>
  <Input />
  <Results />
</Search>

// Dropdown
<Dropdown>
  <Trigger />
  <Menu />
</Dropdown>

// Select
<Select>
  <Text (hidden input, labels, search, search sizer, text) />
  <Menu />
</Select>
```

It might be possible to have an abstract component that each of components wrapped.
- The abstract component would be responsible for maintaining the open/focus states and could be configured to open/close based on subset of interactions (focus, blur, etc) via props.
- The wrapping component would pass the "content" and "menu" as props for the underlying component to render.
#### Dropdown vs Select

In addition to similarities with search, I think the `Dropdown` currently has a two very different use-cases that are both built into the single component (I mentioned this on a previous thread):
- Take the place of a select element and have a "value".
- A hidden menu that's shown after clicking a "trigger" element.

I know SUI only has the one `Dropdown` component, but if you look at the SUI examples page you can see that there are TONS of variations. I think it would make these components simpler if we were able to break the two use-cases apart. There's already a `Select` component in this repo but it's just a light wrapper that adds one prop to `Dropdown`.

If we were to pull these apart, we could have:
- `Dropdown`
  - Takes a list of options and renders them
  - Keeps state for: "open", "focus", "selectedIndex" (for arrowing up/down)
  - No inherent notion of "value" - "active" could be passed as a prop on the relevant option.
- `Select`
  - Wrapper around `Dropdown`.
  - Passes the hidden input, search box, text, as the "trigger"
  - Handles filtering of options.
  - Keeps "value" state

---

These ideas aren't quite fully baked but I just wanted to open this up and get some thoughts.

As I mentioned, the `Dropdown` component in SUI can get pretty complex. I think the best way to enable this library to do everything SUI can do is the reduce some of the complexity of the underlying components. Here's an example of a variation I'm looking to use in my app which I don't believe is possible as it stands today (see search in-menu: http://semantic-ui.com/modules/dropdown.html#search-in-menu):

``` jsx
<Dropdown icon='filter' text='Filter Posts'>
  <Dropdown.Menu>
    <Dropdown.Header icon='tags' content='Tag Label' />
    <Dropdown.Divider />
    <Input icon='search' placeholder="Search tags />
    <Dropdown.Menu />
      <Dropdown.Item />
    </Dropdown.Menu>
  </Dropdown.Menu>
</Dropdown>
```

**Comment by levithomason** [comment]
Thanks much for starting this!

**Comment by levithomason** [comment]
Agree completely.  When I get some free brain cycles, I'll give this due attention.  LMK if you start any experiments in the meantime.
