### ISSUE TITLE
feat(Dropdown): add `openOnFocus` and `closeOnBlur`

### ISSUE THREAD

**Issue by njnash** [Semantic-Org/Semantic-UI-React#517]
Right now it seems as though the content you can add to a Dropdown Module is a Header, and then a list of items. Is it possible to support other types of content, such as a Form?

**Comment by levithomason** [comment]
Can you provide some example code and expected output?  Then I can help guide you here.

**Comment by njnash** [comment]
Here is an example:

``` js
<Dropdown trigger={trigger} pointing='top right' icon={null}>
   <Dropdown.Menu>
     <Form>
       <Header>
          New
       </Header>
     <Form.Field>
        <label>Name</label>
        <input placeholder='enter name' />
     </Form.Field>
     <Form.Select label='Select from drop down' options={List} placeholder='select one...' />
     <Button className="basic">Cancel</Button>
     <Button className="basic">Submit</Button>
     </Form>
  </Dropdown.Menu>
</Dropdown>
```

I expected that the form inside the dropdown would be functional. However when I go to type in the Form Field or use the Form Select the dropdown disappears and I cannot use the form.

**Comment by levithomason** [comment]
I believe in this case you are looking for the functionality of a Popup (see #193, not implemented yet) rather than a Dropdown.  A Popup is meant to show additional info over a page.  A Dropdown is meant to allow a user to select a value from a series of options, hence the Dropdown.Menu.

Here's an example Popup that would work well for your case:

![http://g.recordit.co/1aSlDjwIix.gif](http://g.recordit.co/1aSlDjwIix.gif)

What we might be able to do in the meantime is provide two Dropdown props I've been wanting to add, `closeOnBlur` and `openOnFocus`.  If these were available, you could use the Dropdown as a workaround for now by setting `closeOnBlur={false}`.

I'd accept a PR that added these two props.

**Comment by levithomason** [comment]
I've update this issue to request those props be added.  This should support your use case temporarily while waiting for the Popup.  It would be fantastic if you could contribute either to the Dropdown, or ideally, the Popup.

**Comment by njnash** [comment]
Great, thank you so much for the detailed response! It looks like the Popup component is exactly what I want. Any guess on the timeframe for that?

**Comment by levithomason** [comment]
See the issue comments for details.

**Comment by njnash** [comment]
Hey, so I worked on putting in those two props we talked about, however I do not think that was the quick fix I was looking for. I am still encountering the problem of if I have a Dropdown without the Dropdown.Menu tag inside, it will simply render the contents of the dropdown before the button instead of having it actually 'drop down'. Do you know of any work arounds for that? If not, I'll wait for the Popup to be implemented instead.

**Comment by levithomason** [comment]
Unfortunately, I don't have bandwidth to solve this ATM.  I would review a PR if submitted though.  Otherwise, the Popup is likely the best bet whenever it is completed.

**Comment by typehorror** [comment]
@njnash Popup was released with the support for `hoverable` for `on='hover'` behavior and simply `on='click'` which I believe should address your initial need. http://react.semantic-ui.com/modules/popup

@levithomason I think we can close that one 🎉

**Comment by levithomason** [comment]
Thanks for updating us @debrice.  I'll leave this issue open as I'd like to still add the noted props to the Dropdown.

**Comment by tarang9211** [comment]
@levithomason you think I could help out here?

**Comment by levithomason** [comment]
Absolutely, we just need boolean props for these. Then, wrap the current ooen/close logic in a check for each respective prop. 

Apologies for the vague answer here, on mobile. One the PR is up, I'll help out more.
