### ISSUE TITLE
refactor(sub components): export at the top level

### ISSUE THREAD

**Issue by nicolo-paganin** [Semantic-Org/Semantic-UI-React#519]
The module is not working with the optimization module Babel [transform-react-inline-elements](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-inline-elements).

The reasn is this one [https://github.com/thejameskyle/babel-react-optimize/issues/19](https://github.com/thejameskyle/babel-react-optimize/issues/19). 

In order to get it working you have to import directly the submodule. For example for the  Menu component

`import Menu, {MenuItem, MenuMenu, MenuHeader} from 'stardust/dist/collections/Menu/Menu'`

This is not working in this moment becase the submodules are not exported.

The proposed modification is to export also the submodules like this (dist/collections.Menu/Menu.js:182):

`
Menu._meta = _meta;

Menu.autoControlledProps = ['activeIndex'];
exports.Header = Menu.Header = _MenuHeader2.default;
exports.Item = Menu.Item = _MenuItem2.default;
exports.Menu = Menu.Menu = _MenuMenu2.default;
exports.default = Menu;
`

Thanks

**Comment by levithomason** [comment]
I'd accept a PR for exporting sub components.  Should be rather easy, just add them to each `index.js` file in src/\* folder.

There may be some automated testing considerations to update that I'm not seeing.

**Comment by levithomason** [comment]
Released in `stardust@0.47.1`, cheers!
