### ISSUE TITLE
use SVG for icons

### ISSUE THREAD

**Issue by salzhrani** [Semantic-Org/Semantic-UI-React#531]
## Description

I think it is better to use `svg` sprites for icons instead of of web fonts. it has many advantages discussed on a number of blog posts, plus it is more semantic.

**Comment by levithomason** [comment]
This library provides no CSS.  Please open an issue on https://github.com/Semantic-Org/Semantic-UI.  Note, this issue was already opened as well: https://github.com/Semantic-Org/Semantic-UI/issues/1240
