### ISSUE TITLE
Unexpected token `:`  in webpack

### ISSUE THREAD

**Issue by akashshinde** [Semantic-Org/Semantic-UI-React#532]
I am using `@0.45.3 version`

When I am trying to `import stardust`

![screen shot 2016-09-23 at 8 57 15 pm](https://cloud.githubusercontent.com/assets/3337902/18791435/5662c09c-81d0-11e6-85b7-c0e68fe32adb.png)

**Comment by levithomason** [comment]
The stack says that error is in `reactBoilerplateDeps.dll.js:4200`.  Suggest opening an issue there.

**Comment by levithomason** [comment]
Other's have been having issues with react-boilerplate and `debug` which may be of help to you as well: https://github.com/TechnologyAdvice/stardust/issues/507
