### ISSUE TITLE
Nested dropdown/menu does not expand on hover

### ISSUE THREAD

**Issue by parisholley** [Semantic-Org/Semantic-UI-React#533]
## Steps to Reproduce

Check out the "Attached" example for dropdown in documentation
## Expected Behavior

"New" menu should expand and show additional options on hover
## Actual Behavior

Nothing opens
## Version

Stardust: master
Browser: Chrome
OS: Mac
## Test Case

Documentation

**Comment by levithomason** [comment]
Though we do not currently support nested Dropdown menus, please provide a link for the test case.  Without a test case, there isn't a clear path for a developer to work on it.  Thanks much.

**Comment by parisholley** [comment]
The test case is the documentation: "attached.js"

**Comment by levithomason** [comment]
Sorry, I'll need more specificity please.  There is no "Attached" Dropdown example on our doc site for the Dropdown: http://technologyadvice.github.io/stardust/modules/dropdown

The only two files named `Attached.js` are:

![image](https://cloud.githubusercontent.com/assets/5067638/18799572/28f80718-818d-11e6-9b95-a7bcdd0072fd.png)

Perhaps you are referring to the Semantic-UI main repo?

**Comment by parisholley** [comment]
https://github.com/TechnologyAdvice/stardust/blob/master/docs/app/Examples/collections/Menu/Types/Attached.js

**Comment by levithomason** [comment]
Got it, thanks!

**Comment by levithomason** [comment]
I believe this is an issue with the `createIcon` factory.  It is returning empty icons.  There is a similar issue with the regular Dropdown example's DropdownItem's:

http://technologyadvice.github.io/stardust/modules/dropdown#dropdown

I'll start on this now, thanks again for the report.

**Comment by parisholley** [comment]
Not sure it is related, I don't see anywhere where hover events are wired up. I am about to submit a pull in a few minutes that gets it to work, but it definitely feels like a hack :)

**Comment by levithomason** [comment]
Sure, thing let's split up.  I'll fix the icon factory issue.

I'm not sure if the Dropdown is supposed to open on hover via CSS or JS via a Dropdown setting.  If the latter, then the Dropdown component needs extended as we do no currently support this.

**Comment by levithomason** [comment]
OK, the menu issue is that the augmentation simply needs reversed:

``` jsx
<Dropdown as={Menu.Item} icon='wrench'>
```

Instead of:

``` jsx
<Menu.Item as={Dropdown} icon='wrench'>
```

**Comment by jeffcarbs** [comment]
@levithomason - looks like the issue with the dropdown item icon is due to this change:

``` diff
- {iconName && <Icon name={iconClasses} />}
+ {createIcon(iconName)}
```

iconName is defined as:

```
iconName = icon || childrenUtils.someByType(children, 'DropdownMenu') && 'dropdown'
```

which can be `false` since `childrenUtils.someByType` returns a boolean. `false` isn't ignored by factories, only `null` or `undefined`.

Two options:
- update factories to ignore _.isNil(val) || val === false
- update `iconName=` here to be `childrenUtils.someByType(children, 'DropdownMenu') ? 'dropdown' : undefined`

I could see option 1 being viable: disable a factory by either setting nothing or setting to null/false

**Comment by levithomason** [comment]
Thanks for the investigation. I've added `return null` to factories for boolean values.  I think this is sane.  They accept string, object, or element only.  I'll push shortly.
