### ISSUE TITLE
feat(Image): add `label` shorthand

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#538]
There is interesting [example](http://semantic-ui.com/elements/label.html#corner) in SUI docs. 

``` html
<div class="ui fluid image">
  <a class="ui left corner label">
    <i class="heart icon"></i>
  </a>
  <img src="/images/wireframe/image.png">
</div>
```

It sends `Label` to `Image` as child while we don't handle this in `Image` component. While I'll work on `Label` docs I'll check all examples, but now my initial proposal is add `label` shorthand for `Image`.

**Comment by levithomason** [comment]
Agreed, seems like shorthand here.  Something to the effect of:

``` jsx
<Image label={{ corner: 'left', icon: 'heart' }} src="/images/wireframe/image.png" />
```

**Comment by levithomason** [comment]
In general, we're _trying_ to adhere to "no children for HTML elements that don't have children" such as an `img` or an `input`.

**Comment by layershifter** [comment]
> we're trying

[Nice try](https://github.com/TechnologyAdvice/stardust/pull/281/commits/1b1ca7f85d58b4ce58d5c8bee2361270fa937902#diff-9f3ccadb434184e78d107e1ee7d3b33aR101), comrade  😄  (joke, I understand why)

I am afraid that the markup of `Image` options may be too difficult for the shorthands like in `Input`, after I'll do `Label` docs it will be understandable.

**Comment by levithomason** [comment]
Oh boy, yes... wish I could have avoided that one!

I think we can do it with shorthand, though not completely opposed to having to use children as in the Input. If image children are provided, it would just dictate the `wrapped` markup (a `ui image` div wrapping the `img` tag).

**Comment by layershifter** [comment]
In #576 I don't find new use cases, so I'll `label` shorthand after #576 will be merged.
