### ISSUE TITLE
docs(shorthand): add dedicated shorthand docs page

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#561]
Shorthand props are at the heart of what makes our API so powerful and easy to work with.  With the recent updates and additions to our factories, the shorthand concept is becoming the crux of this library.  We're set to only further improve shorthand for arrays, child keys, and prop types.  Understanding how to use it is paramount to using Semantic-UI-React.

Shorthand is covered briefly half way down the introduction page.  However, it is incomplete and deserves more prominence.  We should add a dedicated "Shorthand" page under "Getting Started".

**Comment by levithomason** [comment]
Include information and examples from #882.

**Comment by levithomason** [comment]
Include an input example, see #1386.

**Comment by brianespinosa** [comment]
@levithomason Assigning this old one over to myself. I'll see about putting something together to help with this.

**Comment by brianespinosa** [comment]
I've officially blocked out a day to work on some of this over the holiday. 🎁 🎉

**Comment by layershifter** [comment]
Unstale, please :cat

**Comment by brianespinosa** [comment]
@layershifter I saw you mention elsewhere that you were thinking about changing to docs to be built with Gatsby. Is that something you are still considering?

If so, we might want to look into something like MDX files to generate our docs. I actually am putting something together with my team that does this right now internally.

**Comment by layershifter** [comment]
@brianespinosa we using ReactStatic now.

We can adopt MDX files there, just add an additional loader: https://github.com/Semantic-Org/Semantic-UI-React/blob/master/static.webpack.js#L41

I don't have there a strategy for this now. Feel free to promote it 👍

**Comment by brianespinosa** [comment]
Ah got it. Let me see how things pan out with our internal work first and once I have some more feedback on pros/cons I can put a proposal together.

**Comment by layershifter** [comment]
@brianespinosa MDX support is added, #3196 ✌️
