### ISSUE TITLE
<Card /> Add more prop expand/collapse

### ISSUE THREAD

**Issue by NgKhanh** [Semantic-Org/Semantic-UI-React#577]
**Card** so great, but sometime we need **expand/collapse** them. Maybe use this prop with **item** too (when we touch on mobile, it expands more button for option, it'll be better dropdown, maybe)

P/s : I tried with accordion, but the Accordion's title only get string, not <component/> as I wish

**Comment by levithomason** [comment]
Please be more specific so we can help.  It is most helpful to use the issue template provided.

**Comment by levithomason** [comment]
Closing this for housekeeping.

My assumption was that the request is for _adding styles and/or markup_ to allow expanding/collapsing the Card.  This sounds like core SUI feature request as we only handle generating valid SUI markup.  Adding styles is beyond our scope here.
