### ISSUE TITLE
feat(Table): add `attached` prop

### ISSUE THREAD

**Issue by x-shd** [Semantic-Org/Semantic-UI-React#591]
Hi, missing prop attached

**Comment by levithomason** [comment]
Hi there, I don't see `attached` in the SUI docs for Table.  Could you please provide much more specificity and info so we can best help?

**Comment by yesmin** [comment]
Here is a good example
http://semantic-ui.com/examples/attached.html

**Comment by x-shd** [comment]
Here is a good example
http://semantic-ui.com/examples/attached.html

**Comment by levithomason** [comment]
Thanks much.  Could you let me know why you did not use the issue template?  It has valuable information on it for us, but I notice very few people answer the questions in it.  We want to create useful stuff, so I'd greatly appreciate any feedback on how we might improve the template in a way that you would use it.

**Comment by yesmin** [comment]
#593
