### ISSUE TITLE
fix(Checkbox): prevent onChange and onClick when disabled 

### ISSUE THREAD

**Issue by sprmn** [Semantic-Org/Semantic-UI-React#600]
**Version**
0.52.2

**Steps to Reproduce**
1. Create checkbox with prop disabled set to true.
2. Try to toggle and check if the `onChange` function is called

**Expected**
The Checkbox should not trigger the `onChange` function when disabled, since it doesn't change. 

**Result**
The Checkbox does call the onChange function.

**Testcase**
http://codepen.io/sprmn/pen/JROPjO

**Comment by levithomason** [comment]
Thanks for the superb bug report!  Indeed, neither `onChange` nor `onClick` should fire.  I've updated the test case to show both handlers and included a vanilla checkbox for comparison.

Our component should be fixed to work like the vanilla component: http://codepen.io/levithomason/pen/zKPGJW

**Comment by sprmn** [comment]
Thanks! Didn't know think about onClick. Guess my fix in #601 is not sufficient yet. I'll try to add some more fixes.
