### ISSUE TITLE
Move docs to react.semantic-ui.com

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#611]
This is a reminder to myself, pending https://github.com/Semantic-Org/Semantic-UI-React/issues/3.  Once transferred, I'll get with Jack to have the DNS setup for this.  Once that is done, we can update all our urls to point to the new doc location.
### Reminders
- [x] current `gh-pages` redirect hacks (see index.html)
- [x] webpack public path config updates (`/stardust`)
- [x] config `__BASE__` global, including `react-router` basename

**Comment by jlukic** [comment]
I can set the IP to whatever you need for the dns, let me know.

**Comment by levithomason** [comment]
@jlukic OK, everything is setup now.  We're using a github project page for docs. Per the docs for [setting up a custom subdomain](https://help.github.com/articles/setting-up-a-custom-subdomain/):

> **3)** Follow your DNS provider's instructions to create a CNAME record that points from your default pages domain, such as YOUR-GITHUB-USERNAME.github.io to your subdomain. Your DNS changes can take over a full day to update and the wait varies among DNS and hosting providers.

Can you crate this CNAME record?

**from**: http://semantic-org.github.io/Semantic-UI-React
**to**: react.semantic.com

**Comment by levithomason** [comment]
Appears you've beat me to the punch, or some other config has covered it :)

http://react.semantic-ui.com

**Comment by jlukic** [comment]
😄
