### ISSUE TITLE
what happened to <Modal />'s active props

### ISSUE THREAD

**Issue by hyusetiawan** [Semantic-Org/Semantic-UI-React#617]
### Steps
1. Do something
2. Do something else.
### Testcase

Fork: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by levithomason** [comment]
The prop is now `open`, see an example in the docs here: http://technologyadvice.github.io/stardust/modules/modal#size

This was updated with our new Portal component.  We've instituted much more clear `BREAKING CHANGE: ...` notes in the CHANGELOG.md moving forward.  Apologies for the confusion.

**Comment by hyusetiawan** [comment]
yeah i found it, that's why i immediately closed it, you answered too fast 👍
