### ISSUE TITLE
Add key to 'Support' section in README?

### ISSUE THREAD

**Issue by btamayo** [Semantic-Org/Semantic-UI-React#624]
Hi, I find the 'Support' section in the current README lacking a key for `_`, `X`, etc. I'm presuming `X` means that there is support for that item but perhaps we can add a key or change it to a checkmark instead?

**Comment by levithomason** [comment]
I had tried this previously, but they were hideous. Found I could copy the rendered `&check;` and paste it in, not bad:

https://github.com/TechnologyAdvice/stardust#support

Thanks
