### ISSUE TITLE
Question regarding testing using Karma/PhantomJS

### ISSUE THREAD

**Issue by server-monitor** [Semantic-Org/Semantic-UI-React#625]
First off, thank you authors and maintainers for this software. My apologies in advance if this has nothing to do with stardust.

My problem is that importing or requiring a stardust component results in this error:

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: Object is not a function (evaluating '_debug('stardust:' + namespace)')
  at webpack:///~/stardust/dist/commonjs/lib/debug.js:30:0 <- spec/components/snapshots/picture/index.spec.js:28332
```

Other tests with various ES6 code, import component statements, etc. work. I was looking at your test code and I installed karma-phantomjs-shim. I also copied this package's karma configuration to my karma configuration (frameworks, plugins). But they didn't fix the problem.

**Comment by server-monitor** [comment]
I had a globally defined object named _debug that's why it wasn't working. I renamed the object and all is well.

**Comment by levithomason** [comment]
Cool, thanks for closing!
