### ISSUE TITLE
fix(Dropdown): reopens after switching back to browser window

### ISSUE THREAD

**Issue by Chris-R3** [Semantic-Org/Semantic-UI-React#627]
### Steps
1. open [Dropdown docs](http://technologyadvice.github.io/stardust/modules/dropdown)
2. select/click on any item from the first example (file dropdown)
3. switch to another browser tab/window/application
4. switch back to Dropdown docs browser tab
### Expected

`Dropdown` should still be closed since no user interaction happened.
### Result

`Dropdown` opened / is visible without user interaction.
### Testcase

 [Dropdown docs](http://technologyadvice.github.io/stardust/modules/dropdown)

I tested this with the latest version of Chrome(Win10 & macOS) and the latest version of Safari (macOS).
The _Selection_, _Single Option_ and _Multiple Options_ examples work as expected!

**Comment by levithomason** [comment]
I'm not sure this should be considered a bug.  The Dropdown closes on blur, click outside, escape key, or item select.  None of these happen on tab switch, so it never closes.

None of the Dropdown examples close for me when switching to a new tab, so they are all open when I switch back.

Chrome 53.0.2785.143
MacOS X 10.10.5

Lastly, this is also the behavior of the [Dropdown](http://semantic-ui.com/modules/dropdown) in SUI core.  Closing as I don't think we should change anything here.

**Comment by levithomason** [comment]
Another way of looking at it is this, the user opened the menu so expecting:

> Dropdown should still be closed since no user interaction happened.

I don't think makes sense, since the user never gave interaction to close it initially.  Hope that helps clarify.

**Comment by Chris-R3** [comment]
The dropdown is already closed (after selecting an item) before switching to another tab/window! So when I switch back to the dropdown it should stay closed.

**Comment by levithomason** [comment]
Oh boy, shame on me for skipping step 2, thanks for the clarification.

<img src="https://pbs.twimg.com/media/CX-c4vaUEAAabqR.png" width="50" />

Best guess is that the focus event is being called again, therefore opening the Dropdown.  We probably need to blur the element after select.  This map also address https://github.com/TechnologyAdvice/stardust/issues/573 actually, since the focus will no longer be applied.

**Comment by rodryquintero** [comment]
Hello. I copied and pasted the code on the Menu example and got this error.

![image](https://cloud.githubusercontent.com/assets/1271370/21082507/d4f555c4-bfaa-11e6-86a3-636ef0d8e1fb.png)

This happens after I try to click on the dropdown to close it. It is also triggered on any click after the first one.

Here is the render function code:

```
return <Menu fixed="top" inverted={false}>
       <Dropdown as={Menu.Item} icon='wrench' simple>
          <Dropdown.Menu>
            <Dropdown.Item>
              <Icon />
              <span className='text'>New</span>

              <Dropdown.Menu>
                <Dropdown.Item>Document</Dropdown.Item>
                <Dropdown.Item>Image</Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown.Item>
            <Dropdown.Item>Open</Dropdown.Item>
            <Dropdown.Item>Save...</Dropdown.Item>
            <Dropdown.Item>Edit Permissions</Dropdown.Item>
            <Dropdown.Divider />
            <Dropdown.Header>Export</Dropdown.Header>
            <Dropdown.Item>Share</Dropdown.Item>
          </Dropdown.Menu>
        </Dropdown>
    </Menu>
  }
```
I am using the latest version of React Semantic.

**Comment by levithomason** [comment]
See #659
