### ISSUE TITLE
feat(Modal): support opening/closing multiple modals

### ISSUE THREAD

**Issue by koenvg** [Semantic-Org/Semantic-UI-React#636]
### Steps

The closeOnClickOutside and closeOnEscape props don't work as expected when opening more than one modal. The wanted behavior is that it only closed the top modal when the events are triggered. 
This also causes an issue that when both modals are open and you want to click inside the modal, all modals are closed as well. I placed an input field in the example for this issue.
1. Open a modal in a modal
2. Press ESC or click outside/inside the top modal
### Expected

It will only close the top modal.
### Result

All modals are closed.
### Testcase

http://codepen.io/anon/pen/yapmQw

**Comment by levithomason** [comment]
Thanks, this is something we should add.  I've updated the title and labels.
