### ISSUE TITLE
Step element: Waring on StepGroup

### ISSUE THREAD

**Issue by nicolo-paganin** [Semantic-Org/Semantic-UI-React#641]
Hi, it is only a warning on StepGroup, so the component is working well, but in the console is printed the following

`Warning: Failed prop type: StepGroup: prop type`items`is invalid; it must be a function, usually from React.PropTypes.`

Thanks

**Comment by craig1123** [comment]
I'm getting the same with Menu

`Warning: Failed prop type: Menu: prop type `items` is invalid; it must be a function, usually from React.PropTypes.`

along with Table.Row
`Warning: Failed prop type: TableRow: prop type `cells` is invalid; it must be a function, usually from React.PropTypes.`

I just recently updated stardust to semantic-ui-react when these errors started happening.

**Comment by levithomason** [comment]
This was fix but not released until just now, install `semantic-ui-react@0.54.3` and try again.
