### ISSUE TITLE
Using Modal crashes react

### ISSUE THREAD

**Issue by notadamking** [Semantic-Org/Semantic-UI-React#649]
```
import { Modal } from 'semantic-ui-react';

const LoginModal = ({ open, onClose,  handleSubmit }) => {
  return (
    <Modal dimmer open={open} onClose={onClose} size="small">
      <Modal.Header>Modal</Modal.Header>
      <Modal.Content>
          Content
      </Modal.Content>
    </Modal>
  );
};

export default LoginModal;
```

The above code gives me the runtime error:
`TypeError: Cannot read property '_currentElement' of null`

Am I doing something wrong?

**Comment by typehorror** [comment]
if you've done a straight copy/paste, your import is missing quotes:

``` jsx
import { Modal } from 'semantic-ui-react';
```

**PS**: I believe `TypeError: Cannot read property '_currentElement' of null` happens when the render throw an error during the initial mount.

**Comment by notadamking** [comment]
No it wasn't a straight copy/paste, I wasn't missing quotes in the actual code. I have been using stardust for a couple months now, and only just switched everything over to semantic-ui-react yesterday. Modal's are the only thing I can't get to work with the new library.

**Comment by levithomason** [comment]
@adamjking3 which version are you on?

**Comment by notadamking** [comment]
@levithomason    

 "semantic-ui-react": "^0.54.5",
"stardust": "0.42.6",

**Comment by levithomason** [comment]
Hm, can you provide a test case using the codepen provided in the issue template?

**Comment by levithomason** [comment]
Confirmed this is working with the latest version.  I've pasted your `LoginModal` into the doc site for testing.  The Modal opens on Button click and closes on both click outside and the escape key.  Closing as there must be a bug elsewhere in the code that is causing this.

``` jsx
import React, { Component } from 'react'
import { Button, Modal } from 'semantic-ui-react'

const LoginModal = ({ open, onClose,  handleSubmit }) => {
  return (
    <Modal dimmer open={open} onClose={onClose} size="small">
      <Modal.Header>Modal</Modal.Header>
      <Modal.Content>
          Content
      </Modal.Content>
    </Modal>
  )
}

class App extends Component {
  state = {
    open: false, 
    onClose: () => this.setState({ open: false }),
  }
  render() {
    return (
      <div>
        <Button onClick={() => this.setState({ open: true })} >Open</Button>
        <LoginModal {...this.state }/>
      </div>
    )
  }
}

export default App
```

![http://g.recordit.co/mNJVdvGrl4.gif](http://g.recordit.co/mNJVdvGrl4.gif)
