### ISSUE TITLE
Dynamic menu tabs 

### ISSUE THREAD

**Issue by Extra-lightwill** [Semantic-Org/Semantic-UI-React#650]
I'm wondering whether SUI react would be able to achieve a UI setup along this lines: (http://designrope.com/wp-content/uploads/2014/03/dashboard-ui-4.png) 

That is, there is a double menu - the one on the left is a dynamic tab type menu where an item is added if after a certain event in the application (e.g. a user adds something), and then a main menu ,that organises and renders the information associated with each tab. Menu tab is also removable so if an event takes place which gets rid of the information associated with the specific tab, the menu tab disappears.

I know this is a specific question, but having examined the SUI documentation thoroughly I can only find reference to dynamic tabs (and I'm unsure whether they would fulfil the requirements for what is shown and described above). 

If this is possible in SUI react, how exactly would I go about it?

**Comment by levithomason** [comment]
Hi there, I'd suggest posting this over at http://forums.semantic-ui.com/.  The forums are a good place to chat about Semantic UI.  The GitHub issue queue here is dedicated to bugs and features for Semantic-UI-React specifically.  Cheers!
