### ISSUE TITLE
fix(Confirm): All "show" buttons on the 'Confirm' docs page are not working

### ISSUE THREAD

**Issue by twang2218** [Semantic-Org/Semantic-UI-React#651]
The docs show the issue: http://react.semantic-ui.com/addons/confirm

Just trying to use the 'Confirm' component and checking the docs, however, all `Show` button on the doc page doesn't work. And there isn't any debug information on the console.

I tried the page on Chrome, Firefox and Safari on OSX, all the same.

**Comment by typehorror** [comment]
This is being worked on #634

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.55.0`, docs are also shipped.
