### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#661]
Hi, when using with my node.js app I'm getting `process is not defined`. Are you sure you wanted to use the process flags? That is used in server development not for client. For now, I set that variable manually

**Comment by levithomason** [comment]
We do indeed intentionally use `process.env`.  With React apps is it common place to use `process.env.NODE_ENV` in the code for environment based feature flipping.  

React itself uses this same approach, having its source code littered with `process.env.NODE_ENV` checks. See [their docs](https://facebook.github.io/react/downloads.html#npm) for suggested ways to ensure it is set properly.

**EDIT**

Here is another React [blog post](https://facebook.github.io/react/blog/2016/04/07/react-v15.html#installation) that covers setting `NODE_ENV`.
