### ISSUE TITLE
Code exmaple in docs for Menu, are missing link={true} 

### ISSUE THREAD

**Issue by yaronlevi** [Semantic-Org/Semantic-UI-React#665]
Looking at the docs for menu:
![screen shot 2016-10-12 at 2 19 19 pm](https://cloud.githubusercontent.com/assets/5398977/19308224/388203ce-9087-11e6-994f-92474bce8a15.png)

In this example, when you hover on the menu items their color is changed, yet if you take the attached code example as is, you won't get that behavior. You need to add link={true} to get this hover behavior. The docs should be updated with link={true}.

This may be simple, but for a new comer to semantic ui react, trying to build a simple menu this may be frustrating. 
(Have I not included the css file correctly? Do I have another css overriding this?)

**Comment by levithomason** [comment]
It is not clear which `Attached` example you are referring to.  Please fork the provided codepen in the issue template and provide a test case.  This is important as without it, we're left to guess.

I've tested 3 examples, but all 3 work correctly (the gif hides the cursor, though you can see the active style changing):

### Regular Menu

![http://g.recordit.co/Xd4kuoDGV5.gif](http://g.recordit.co/Xd4kuoDGV5.gif)

### Attached Menu Dropdown

![http://g.recordit.co/KP5R5jh0nE.gif](http://g.recordit.co/KP5R5jh0nE.gif)

### Segment Attached Menu

![http://g.recordit.co/5rxElf5t7t.gif](http://g.recordit.co/5rxElf5t7t.gif)
