### ISSUE TITLE
Dropdown Blur

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#670]
Hi, when using dropdown in Menu, I'm getting `_this._dropdown.blur is not a function`.
It makes me specify blur at all times ;/

This happens, when dropdown is used in Menu. It actually looks like a bug which makes dropdowns in menus unable to use. Thanks!

you receive error even in your example page with dropdowns in menus.

**Comment by levithomason** [comment]
In progress #659.  Thankful for the report, though please search for existing issues before opening new ones.
