### ISSUE TITLE
Dropdown links with inverted menu are painted white

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#673]
Hi, with below structure, the links in the Dropdown are painted white on white background.
Actually, is there also way of how to render dropdown items as links ? 

``` javascript
<Menu inverted color="blue">
<Dropdown text={i18n`library.label`} as={Menu.Item}>
    <Dropdown.Menu>
      <Dropdown.Item><Link to="schedules">{i18n`schedules.label`}</Link></Dropdown.Item>
    </Dropdown.Menu>
  </Dropdown>
 </Menu>
```

**Comment by levithomason** [comment]
Hm, this would be a CSS issue.  Can you link working example in the primary SUI docs?  We only generate valid HTML/CSS.  If there is a working example to reference, then we can update our components to generate the working markup.

**Comment by tomitrescak** [comment]
I am not sure what you are asking me.

**Comment by levithomason** [comment]
I'll need a working example to reference.  If you can provide a working example from the docs at http://semantic-ui.com, then we can make updates to our components.

**Comment by tomitrescak** [comment]
Would following do?

``` javascript
<Menu inverted color="blue">
<Dropdown text="Visible Text" as={Menu.Item}>
    <Dropdown.Menu>
      <Dropdown.Item>Item</Dropdown.Item>
    </Dropdown.Menu>
  </Dropdown>
 </Menu>
```

**Comment by levithomason** [comment]
I believe this issue is beyond the scope of our project.  Semantic-UI-React only generates valid Semantic-UI HTML.  We do not handle any styling.  If you'd like to change Semantic-UI's CSS, you'll need to open an issue over at [Semantic-UI](https://github.com/Semantic-Org/Semantic-UI) itself.

**Comment by mcrawshaw** [comment]
https://github.com/Semantic-Org/Semantic-UI/issues/1475

**Comment by levithomason** [comment]
Thank you for linking the issue.

**Comment by nhepner1** [comment]
As a quick workaround, I'm able to get something to show if I add the "ui" class to each link. Not ideal, but serves my purposes for now. 


```
<Menu inverted color="blue">
<Dropdown text="Visible Text" as={Menu.Item}>
    <Dropdown.Menu>
      <Dropdown.Item className="ui">Item</Dropdown.Item>
    </Dropdown.Menu>
  </Dropdown>
 </Menu>
```
