### ISSUE TITLE
Vertical divider not working anymore

### ISSUE THREAD

**Issue by slig** [Semantic-Org/Semantic-UI-React#677]
When using the <Divider vertical /> the dividers now float up on the left. They used to work before in the "stardust" package. 
### Version

0.56.0
### Testcase

Please go to the actual docs example to see the bug 
http://react.semantic-ui.com/elements/divider#vertical-divider

**Comment by levithomason** [comment]
This is due to Chrome changing how it deals with the CSS.  Beyond our scope, see this issue on the main repo https://github.com/Semantic-Org/Semantic-UI/issues/4342.

Jack has filed issues with Chromium and the W3C.
