### ISSUE TITLE
How do I validate forms with Semantic-UI-React

### ISSUE THREAD

**Issue by VanessaRLewis** [Semantic-Org/Semantic-UI-React#678]
I couldn't find documentation for Form Validation on http://react.semantic-ui.com and was hoping someone could point me in the right direction. 
Has Form Validation been implemented yet in Semantic-UI-React? If so, are there any usage documents I can look at? If not, do I use normal Semantic UI's form validation or something like formsy-react?
I did look at the RFC: Form Validation #407 (https://github.com/Semantic-Org/Semantic-UI-React/issues/407) but it seemed like proposals for ideal Form Validation & Form Component.

**Comment by levithomason** [comment]
Not yet implemented, see #407 for the latest convo.  For now, you'll have to roll your own validation.

**Comment by shahidmau** [comment]
+1

**Comment by mairh** [comment]
For you own validation I can recommend [Redux Form](http://redux-form.com/6.7.0/). It integrates nicely with Semantic-UI-React. If you need an example I can create a gist for you.

**Comment by TrebuhD** [comment]
@mairh I would love to see said example!

**Comment by mairh** [comment]
@TrebuhD Here you go https://gist.github.com/mairh/233f6b4ffdbaaed8ec75bb0bef087e8f

I tried to explain things as clearly as I could and also divided the code into separate components so that it reusable thought the codebase. You still have to define the `redux-form` in your reducers. (I have omitted that part since it is redux specific - Not related to `redux-form` or `semantic-ui-react`

**Comment by dondre** [comment]
I just bite the bullet and installed forms.js and jquery. This validation was too good to pass up.

**Comment by levithomason** [comment]
Just know it will break as soon as React replaces one of the DOM nodes on render.  jQuery event listeners will be attached to the old DOM node.

I would highly recommend using one of the react libs and implementations suggested in #407. 
 There are many great solutions there.

**Comment by dondre** [comment]
That won't happen as I'm writing to the document body. I actually had to add a check to prevent the script from duplicating on re-renders. 

I really like this form-validation, I hope you guys can implement something similar.

**Comment by doanhuudung** [comment]
![image](https://user-images.githubusercontent.com/4019600/34809009-d58f2e86-f6c4-11e7-9886-7d2d9cd328f4.png)
Waiting for validation's feature 💃

**Comment by levithomason** [comment]
@doanhuudung Good news, that feature was [shipped in 2016](https://github.com/Semantic-Org/Semantic-UI-React/issues/247) :)

Semantic-UI-React !== Semantic-UI

The React port (this repo) is jQuery free for the reasons noted.  The original repo is a jQuery based implementation.
