### ISSUE TITLE
Menu.Item allows icon to be set as boolean

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#681]
Menu.Item icon prop is defined as boolean, while it should be of type Icon. 

```
<Menu.Item icon="doctor" />
```

renders correctly but gives error: Failed prop type: Invalid prop `icon` of type `string` supplied to `MenuItem`, expected `boolean`.

**Comment by levithomason** [comment]
See #681

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.56.1`
