### ISSUE TITLE
Dropdown error using trigger prop

### ISSUE THREAD

**Issue by dongjinahn** [Semantic-Org/Semantic-UI-React#688]
**Steps to Reproduce**

To reproduce, i executed Custom Trigger example at http://react.semantic-ui.com/modules/dropdown

**Expected**
No warnings

**Result**
console.error!
warning.js:36
Warning: Failed prop type: `children` prop in `Dropdown` requires props: `text`.

So i added text="" to Dropdown's props, but then it says warning.js:36 Warning: Failed prop type: Prop `trigger` in `Dropdown` conflicts with props: `text`. They cannot be defined together, choose one or the other.

**Comment by levithomason** [comment]
Duplicate #676

**Comment by levithomason** [comment]
@olafahn this is now fixed in `semantic-ui-react@0.56.4`, cheers!
