### ISSUE TITLE
Input documentation missing placeholder and onChange.

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#689]
Hi, the documentation for Input is missing placeholder and onInput or onChange event.

**Comment by levithomason** [comment]
We don't document standard HTML props like `placeholder`.  We also do not document many of the standard React equivalent props, such as `onChange`.  Both HTML and React props should be expected to work as they do in vanilla React.

Note an `<Input />` supports many undocumented props such as:

React Props
- selected
- defaultValue
- defaultChecked

HTML props
- autoComplete
- autoFocus
- checked
- form
- max
- maxLength
- min
- name
- onChange
- pattern
- placeholder
- readOnly
- required
- step
- type
- value

These are some of the props we explicitly handle.  As you can see, if we documented _every_ supported prop for every component, the docs would be overwhelming.
