### ISSUE TITLE
Modal is missing "open" in the documentation of props.

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#690]

**Comment by levithomason** [comment]
Though all the [Modal variation examples](http://react.semantic-ui.com/modules/modal#variations) make use of the `open` prop, if would be nice to show an explicit example for a "controlled" Modal utilizing the open prop.

I'm thinking something similar to how the Accordion has [an example](http://react.semantic-ui.com/modules/accordion#active-index) showing how the `activeIndex` controls which panel is open.

PRs welcome for this.
