### ISSUE TITLE
Dropdown 'openOnSpace' triggered through TextArea

### ISSUE THREAD

**Issue by fel1xw** [Semantic-Org/Semantic-UI-React#692]
Hey guys,

I've multiple `Dropdown` components at one page, and also other form components like `TextArea` included. When I use the dropdown components everything works fine, but when I then use my TextArea and press space inside, all my previous selected dropdowns are opening.
Looks like it has something to do with the `search`-attribute for the dropdown, when I remove this, it works.
### Steps
1. Select item in dropdown
2. select textarea
3. start typing
4. press `space`
### Expected Result

The listener for `space`-key should be removed for dropdowns if losing focus.
### Actual Result

Dropdown/s is/are opened.
### Version

0.56.0
### Testcase

http://codepen.io/treckerflx/pen/ALPdPg?editors=0010

**Comment by levithomason** [comment]
Thank you for the superb report.  I've labeled this issue for fixing.

**Comment by levithomason** [comment]
I've got a fix in progress, PR coming soon.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.56.3`

**Comment by fel1xw** [comment]
Thank you guys, incredible fast fix. :) 👍

**Comment by levithomason** [comment]
No problem!
