### ISSUE TITLE
fix(Menu): There is a flaw while using image in the menu.

### ISSUE THREAD

**Issue by yeongjet** [Semantic-Org/Semantic-UI-React#698]
![](http://7xqhly.com1.z0.glb.clouddn.com/Image%201.png)
The image and the texts is not in the same central line when I use `pointing secondary` options, and I find the size of image is always 35*35,so how  to enlarge the image? Thanks!

**Comment by yeongjet** [comment]
Solved it, I import another css file and set `padding` and `!important` value inside. I wish it could be fixed in the better way,thanks.

**Comment by levithomason** [comment]
Glad you got it solved.  Please note, CSS is beyond the scope of Semantic-UI-React.  Our components only generate valid Semantic-UI HTML and CSS.  Future issues concerning changes to the HTML or CSS should be opened on [Semantic-UI](https://github.com/Semantic-Org/Semantic-UI).
