### ISSUE TITLE
(0.56.6) semantic-ui-react unable to find React or ReactDOM module

### ISSUE THREAD

**Issue by tomjaimz** [Semantic-Org/Semantic-UI-React#703]
### Steps
1. Upgraded from 0.56.1 to 0.56.6
2. Ran "react-scripts start"
### Expected Result

Compiled successfully!
### Actual Result

Failed to compile.

Error in ./~/semantic-ui-react/dist/umd/semantic-ui-react.min.js
Module not found: 'React' in /home/ec2-user/test/node_modules/semantic-ui-react/dist/umd

 @ ./~/semantic-ui-react/dist/umd/semantic-ui-react.min.js 1:82-98

Error in ./~/semantic-ui-react/dist/umd/semantic-ui-react.min.js
Module not found: 'ReactDOM' in /home/ec2-user/test/node_modules/semantic-ui-react/dist/umd

 @ ./~/semantic-ui-react/dist/umd/semantic-ui-react.min.js 1:99-118
### Version

0.56.6

**Comment by levithomason** [comment]
It is importing the `browser` bundle for some reason, instead of the `main`.  See package.json.

What do your imports look like?

**Comment by tomjaimz** [comment]
I stripped down my app to the bare minimum that still exhibits this error.

Here is my index.js:

``` javascript
import React from 'react'
import { render } from 'react-dom'
import { Header } from 'semantic-ui-react'

render(
    <Header as='h1'>Test</Header>,
    document.getElementById('root')
)
```

Here are the dependencies in my package.json:

``` javascript
  "dependencies": {
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "semantic-ui-react": "0.56.6"
  },
```

**Comment by flipvrijn** [comment]
When pulling the latest changes after reporting #699, version 0.56.6 broke for me with the following error:

> ERROR in ./~/semantic-ui-react/dist/umd/semantic-ui-react.min.js
> Module not found: Error: Cannot resolve module 'ReactDOM' in /Users/f.vanrijn/Workspace/dop/node_modules/semantic-ui-react/dist/umd
>  @ ./~/semantic-ui-react/dist/umd/semantic-ui-react.min.js 1:99-118

Version 0.56.5 does work for me and not getting the error when using webpack. I tested it with the example in #699.

**Comment by levithomason** [comment]
Thanks for the extra reporting, checking into this.  Hang tight.

**Comment by levithomason** [comment]
@tomjaimz @flipvrijn This should be fixed in `semantic-ui-react@0.56.7`, please LMK.

**Comment by tomjaimz** [comment]
Yep, all fixed - thanks for your fast response @levithomason!

**Comment by levithomason** [comment]
No problem, thanks for the report.  I've deprecated `0.56.6` as well. Cheers 🍻 !
