### ISSUE TITLE
Segment does not support "middle" attachment

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#716]
Segment does not support attached="middle" it throws errors

**Comment by tomitrescak** [comment]
Nevermid .. for that purpose you accept `attached={true}`

**Comment by levithomason** [comment]
Also, boolean attributes are `true` by default in React.  So these are equivalent:

``` jsx
<Segment attached />
<Segment attached={true} />
```

Cheers!
