### ISSUE TITLE
Getting the value from <Input/>

### ISSUE THREAD

**Issue by mattmacpherson** [Semantic-Org/Semantic-UI-React#723]
With an HTML input I would just do `this.refs.whatever.value` but what do I do with a Semantic `<Input/>`?

**Comment by levithomason** [comment]
Using a `ref` is accessing the DOM directly and not preferred.  The React way to get the value from an input is using the onChange callback and getting the value from the event:

``` jsx
<input onChange={e => console.log(e.target.value)} />
```

You can get the value for an `<Input />` just as you can in React:

``` jsx
<Input onChange={e => console.log(e.target.value)} />
```

**Comment by hopewise** [comment]
I think its changed now to:

```
onChange={(e,data)=>{
 console.log(data.value)
        }
```
