### ISSUE TITLE
0.56.11 fails to install correctly

### ISSUE THREAD

**Issue by jasrusable** [Semantic-Org/Semantic-UI-React#724]
Hi, I cannot get 0.56.11 to install.

The following command
`npm install --save semantic-ui-react@0.56.11`
runs successfully, however, semantic-ui-react does not seem to actually be built thereafter. (There is no dist directory in ./node_modules/semantic-ui-react)
### Steps
1. Install version 0.56.11

`npm install --save semantic-ui-react@0.56.11`
### Expected Result

semantic-ui-react to have been importable.
### Actual Result

Cannot import from semantic-ui-react.

```
> require('semantic-ui-react')
Error: Cannot find module 'semantic-ui-react'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
> 
```
### Version

0.56.11

**Comment by wmelani** [comment]
Same here - for now I am referencing the /src directory and running it through babel.

**Comment by levithomason** [comment]
Looks like the dist is missing. I'm away from a computer at the moment but I'll publish a fix shortly.

**Comment by levithomason** [comment]
This issue is fixed however, I'm wrestling a test that is suddenly failing only on CI. Hang tight while I triage.  There will be no updated release until the tests pass, of course.

**Comment by levithomason** [comment]
`semantic-ui-react@0.56.12` is published.
