### ISSUE TITLE
Does the <Popup/> Component have 'manual' behavior as the normal popup does?

### ISSUE THREAD

**Issue by thomasdola** [Semantic-Org/Semantic-UI-React#727]
in the normal semantic ui popup element we are able to control is state as when to show and hide by setting the tiger to 'manual'.
But the react version does'nt seem to have that feature.
So is there anyway we can achieve that result?
any help is much appreciated...

**Comment by levithomason** [comment]
The `on` prop controls which event the Popup should open on: http://react.semantic-ui.com/modules/popup#triggers.  I assume this is not sufficient for your use case?

Please provide the information requested in the issue template as we'd love to help. We need some example code, the behavior you expect, and the actual behavior.

**Comment by jeffcarbs** [comment]
@thomasdola - Most of our components can be used in both "controlled" and "uncontrolled" fashion. For the popup, you can control whether or not the popup is visible by specifying a value for the `open` prop. When controlling the value (passing the `open` prop), the Popup won't automatically open/close but it will call the `onOpen` and `onClose` callbacks when it would have opened/closed so you can have your code react to those events.

I think the "controlled" usage is the equivalent of `manual` mode. Not all props translate 1-1 given the inherent differences b/w jquery and React.

Note: #749 fixes a small bug with onOpen/onClose and also adds an example for controlled usage.

**Comment by levithomason** [comment]
Thanks for the superb response @jcarbo 👍

**Comment by thomasdola** [comment]
thanks...
