### ISSUE TITLE
Menu collection + dropdown item = error

### ISSUE THREAD

**Issue by AlvMF1** [Semantic-Org/Semantic-UI-React#732]
### Steps
1. Go to [http://react.semantic-ui.com/collections/menu#size](url)
2. On size examples, open _language_ dropdown, click outside then try to open it again.
### Expected Result

Opening the dropdown. :)
### Actual Result

Uncaught TypeError: a._dropdown.blur is not a function(…)
### Version

0.56.12
Chrome 54.0.2840.71 (64-bit)

**Comment by levithomason** [comment]
Duplicate #659

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.4`.
