### ISSUE TITLE
IE support?

### ISSUE THREAD

**Issue by mclarentgp** [Semantic-Org/Semantic-UI-React#733]
I am receiving the following error when trying to load the dropdown control int IE, Object doesn't support property or method 'startsWith'.  I have a Grid on the same page and as long as i remove the code for the drop down everything loads correctly.  I'm using IE11 Version 11.0.9600.18500.  Has anyone else experienced this issue or is IE not supported?

**Comment by levithomason** [comment]
Thanks for the report, fix coming in #745.
