### ISSUE TITLE
Webpack / CSS / Oh no! 

### ISSUE THREAD

**Issue by bluengreen** [Semantic-Org/Semantic-UI-React#734]
Are there any plans to include the CSS with this package? My app has to work across firewalls / proxies etc and whitelisting a CDN isn't gonna happen.  I tried including the semantic-ui npm but its clunky gulp requirement isn't webpack friendly. I've included semantic-ui-css npm but the CSS isn't compiling in the correct order so still missing CSS, images, and fonts. 

Thought this was gonna be a lifesaver. Seems like every CSS framework out there has some snafu with react. 

Any thoughts? Any plans to include CSS? Looks great from the demo site. Just can't use it unless I include the CDN CSS. 

thanks in advance

**Comment by cattermo** [comment]
You can use the semantic-ui-less package. I followed this guide and got it to work in our project 
https://www.artembutusov.com/webpack-semantic-ui/

**Comment by levithomason** [comment]
No sir there are no plans for CSS.  This project concerns itself with React components only.  You can use any Semantic theme you like.  You can use the default precompiled `semantic-ui-css` package as well.  It is also available on cdnjs.
