### ISSUE TITLE
Item.Image doesn't honor size prop

### ISSUE THREAD

**Issue by clemensw** [Semantic-Org/Semantic-UI-React#746]
The wrapped Image produced by Item.Image doesn't seem to honor the size prop.

Item.Image renders as a wrapped image with ui=false.  Looking at http://semantic-ui.com/views/item.html#image seems to indicate that their wrapped image uses
<div class="ui tiny image"><img ... /> </div>.

Indeed adding ui=true to the Image produced by Item.Image seems to resolve the size issue.
_Update:_ there is an explicit test ensuring ui=false, so perhaps there's something I don't understand about how semantic is supposed to work.

**Comment by Rex90** [comment]
I dont believe this is fixed when the item.group is unstackable the image prop is not honoured

**Comment by levithomason** [comment]
Please open a new issue with a complete report.  We are happy to help.
