### ISSUE TITLE
Accordion defaultActiveIndex

### ISSUE THREAD

**Issue by AlvMF1** [Semantic-Org/Semantic-UI-React#761]
### Steps

http://codepen.io/anon/pen/JRqzQO
### Expected Result

state.activeIndex = 1
('what kinds of dogs are there?' active)
### Actual Result

state.activeIndex = -1
(none active)
### Version

0.56.14

**Comment by levithomason** [comment]
Confirmed, bug fix coming.

**Comment by AlvMF1** [comment]
Hey, thanks for the reply.
I see that you have a test for that, but even after I updated to v0.58.0, the bug still persists.
Also, was it supposed to work on the codepen I sent? If so, it isn't working as well.
Thanks.

**Comment by levithomason** [comment]
The controlled component pattern only works with the "panels" prop where the Accordion has control over creating the title/content children with the correct "active" prop set. 

If you use subcomponents, as in the codepen, then you are responsible for the props on the subcomponents as well. In React there are no implicit parent child relationships. The docs could be more  clear on this.
