### ISSUE TITLE
Accordion does not work properly when defaultActiveIndex is 0

### ISSUE THREAD

**Issue by bitmapdata** [Semantic-Org/Semantic-UI-React#772]
set defaultIndex to 0, the panel will not unfold. but rest of the index, it works properly.

My code here (v0.58.0)

```
import React, { Component } from 'react'
import { Accordion } from 'semantic-ui-react'
import faker from 'faker'
import _ from 'lodash'

const panels = _.times(3, () => ({
  title: faker.lorem.sentence(),
  content: faker.lorem.paragraphs(),
}))

export default class AccordionPanelsPropExample extends Component {
  render() {
    return (
      // at index 0 not working, but rest index working fine. 1 or 2
      <Accordion defaultActiveIndex={0} panels={panels} />
    )
  }
}
```

**Comment by AlvMF1** [comment]
#761

**Comment by levithomason** [comment]
Duplicate, see above.

**Comment by levithomason** [comment]
Ah, there is a nuance here I've overlooked.  The `0` default case is not working.

**Comment by oswaldosan** [comment]
i used this for reactBoostrap accordion i think you can use something similar in your defaultActiveIndex={0}  parameter


`
 <Card key={item.id}> 
    <Card.Header>
      <Accordion.Toggle as={Button} variant="link" eventKey={index === 0 ? '0' : index}>
        {item.title} 
      </Accordion.Toggle>
    </Card.Header>
    <Accordion.Collapse eventKey={index === 0 ? '0' : index}>
      <Card.Body>
             CARD BODY
      </Card.Body>
    </Accordion.Collapse>
  </Card>
`
