### ISSUE TITLE
Accordion indexes

### ISSUE THREAD

**Issue by AlvMF1** [Semantic-Org/Semantic-UI-React#773]
### Steps

```
<Accordion>
  <Accordion.Title>First title</Accordion.Title>
  <Accordion.Content>First content</Accordion.Content>
  <Accordion.Title>Second title</Accordion.Title>
  <Accordion.Content>Second content</Accordion.Content>
  <Accordion.Title>Third title</Accordion.Title>
  <Accordion.Content>Third content</Accordion.Content>
</Accordion>
```
### Expected Result

First title -> activeIndex = 0
Second title -> activeIndex = 1
Third title -> activeIndex = 2
### Actual Result

First title -> activeIndex = 0
Second title -> activeIndex = 2
Third title -> activeIndex = 4
### Version

0.58.0

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.60.7`.
