### ISSUE TITLE
class !important issue

### ISSUE THREAD

**Issue by Maxhodges** [Semantic-Org/Semantic-UI-React#777]
are you guys whacking `!important` onto all these styles for some reason? Makes it hard to override them in my theme!

![image](https://cloud.githubusercontent.com/assets/957271/19852162/0513ac7c-9fa5-11e6-9cf9-ad288609dc67.png)

**Comment by Maxhodges** [comment]
ah, seems to be defined in the SUI definition for dropdown that way. I'll take it up with @jlukic !

**Comment by levithomason** [comment]
Clarification and for others, this repo is JS only.  No styles are added.
