### ISSUE TITLE
Library request in cdnjs.

### ISSUE THREAD

**Issue by Piicksarn** [Semantic-Org/Semantic-UI-React#778]
Hi ~
There's a [library request](https://github.com/cdnjs/cdnjs/issues/9349) in [cdnjs](https://github.com/cdnjs/cdnjs), and we desire to contain Semantic-UI-React.
However, I must to make a check for the files that we need to added.

The file I'd like to add is:

`dist/umd/semantic-ui-react.min.js`

Is that complete for the user? Or other files required?

Thanks for your great work ✨

Piicksarn

**Comment by levithomason** [comment]
@Piicksarn That is correct.  We also plan to add many more files.  Preferably, we would include the entire `dist/umd/*` directory.  If this is not possible, is this something that we can add ourselves later?

Thanks much for the response.

**Comment by levithomason** [comment]
@Piicksarn any update on this? Thanks again.

**Comment by levithomason** [comment]
Cool, looks like it is available now 👍
