### ISSUE TITLE
Dimmer - Inactive dimmer still overlays segment contents, making them unclickable

### ISSUE THREAD

**Issue by ben174** [Semantic-Org/Semantic-UI-React#780]
### Steps
1. Create a Segment with a Dimmer, Loader, and Button
```html
      <Segment>
        <Dimmer active={false} inverted>
          <Loader />
        </Dimmer>
        <Button>Test</Button>
      </Segment>
```

2. Click the button

### Expected Result

Button should be clickable. Cursor should be pointer.

### Actual Result

Button is unclickable. Inspecting the DOM shows that the dimmer node is still present, preventing clicks from items behind it.

### Version

0.58.1

### Testcase

http://codepen.io/ben174/pen/pEMYVG

**Comment by levithomason** [comment]
Confirmed.  We should be adding the `disabled` class when `!active`.  This class reduces the size to 0x0 pixels:

![image](https://cloud.githubusercontent.com/assets/5067638/19911330/2975b9e2-a050-11e6-81b2-320a5c3714f9.png)

**Comment by ben174** [comment]
Yea, I just figured out the same. Was just forking the repo and can create
a PR shortly if you haven't already fixed it.

**Comment by levithomason** [comment]
No sir, I haven't.  A PR would be of great help.

**Comment by ben174** [comment]
Awesome, will do thanks!
