### ISSUE TITLE
Docs site is down

### ISSUE THREAD

**Issue by zeneben** [Semantic-Org/Semantic-UI-React#786]
Appears the doc site is down, sorry if this isn't the right place to create an issue about it, but thought you'd like to know:

Looks like `vendor.332facbd595679008f1b.js` is missing.

**Comment by zeneben** [comment]
http://react.semantic-ui.com/

**Comment by levithomason** [comment]
Interesting, checking into it.  Thanks.

**Comment by levithomason** [comment]
Well, this is odd.  The bundle certainly is there: https://github.com/Semantic-Org/Semantic-UI-React/blob/gh-pages/vendor.332facbd595679008f1b.js

Indeed, all of the assets are: https://github.com/Semantic-Org/Semantic-UI-React/blob/gh-pages.

I can also pull the `gh-pages` branch and serve it locally with no issues.  @jlukic did anything change with the hosting?

**Comment by levithomason** [comment]
Scratch hosting issues, I've turned off the react.semanti-ui.com `CNAME` and the direct gh-pages project link still fails: http://semantic-org.github.io/Semantic-UI-React.

This one is on GitHub.  I'll see if deploying again fixes it, otherwise, we're dead in the water until GitHub resolves the issue.

**Comment by ben174** [comment]
You can try forcing a gh-pages deploy by pushing a empty commit to your `gh-pages` branch.

**Comment by levithomason** [comment]
Yep, did that twice already.  I'm thinking we're up against a size limitation or availability issue with the `gh-pages` server.  There is no response from GitHub:

https://semantic-org.github.io/Semantic-UI-React/vendor.72287be50c36a97a2314.js

But, for example, the rawgit CDN for the same file has no issues:

https://cdn.rawgit.com/Semantic-Org/Semantic-UI-React/gh-pages/vendor.72287be50c36a97a2314.js

The load times were getting pretty horrendous, see #765, so I'm going to assume we've hit a limit or bug here.  We should split the bundle.  I'll see if I get the bundles to serve from rawgit as an interim solution.

**Comment by ben174** [comment]
Hah, I'm going to tell myself my ~100 byte PR #782 is what set it over the top 😉 

But honestly I find it highly unlikely that a 7mb js asset won't work on gh-pages. But it's definitely something broken on their end. Probably worth contacting support over. And maybe hosting on a s3 bucket for now.

**Comment by levithomason** [comment]
Fixed. What ever the reason, GitHub simply can't serve the vendor bundle any longer.  I've moved all assets to serve from rawgit.  Thanks much for the quick notice.
