### ISSUE TITLE
Missing <Dimmer/> Component

### ISSUE THREAD

**Issue by davidsharp** [Semantic-Org/Semantic-UI-React#787]
I'm trying to use the Dimmer component, but it seems to be completely missing from my `semantic-ui-react`

### Steps
1. `const {Dimmer} = require('semantic-ui-react')`

### Expected Result
For Dimmer to not be undefined

### Actual Result
`Dimmer === undefined; //true` 

### Version
0.56.14

**Comment by layershifter** [comment]
@davidsharp Seems, you need simply run update to latest version, `Dimmer` was merged in 0.58.1.

**Comment by davidsharp** [comment]
Ah, thanks.
I'd assumed NPM had given me the most recent version.

**Comment by levithomason** [comment]
Heads up, `npm install` will ignore patch version updates for `0.x.x` version dependencies, unfortunately.  You'll need to install the `@latest` tag in order to ensure you truly get the latest.

```
npm install semantic-ui-react@latest --save
```

This does apply to packages that are at 1.0.
