### ISSUE TITLE
question: can this be used for react native?

### ISSUE THREAD

**Issue by pcompassion** [Semantic-Org/Semantic-UI-React#790]
I'm new to react/native/semantic-ui. 
Probably question is dumb. but can this be used for react native?

**Comment by levithomason** [comment]
Unfortunately not.  Our components only generate valid HTML, whereas React native components would generate native UI elements.

**Comment by tarang9211** [comment]
@pcompassion would you be interested in creating a react native library for semantic-ui?

**Comment by malixsys** [comment]
@tarang9211 I would

**Comment by HintikkaKimmo** [comment]
I took a jump to semantic-ui and not looking back. The react-native capability would be something I would like to see as well. However, I wouldn't know where to start. Is there any organised project around this where I would take few pieces to work on ?

**Comment by mmahalwy** [comment]
@HintikkaKimmo I can start working on it. Give me a few days

**Comment by billh93** [comment]
@HintikkaKimmo @mmahalwy Keep us posted with the development! It would certainly streamline my development process from web to mobile.

**Comment by levithomason** [comment]
Hey folks, love to see continued interest around this.  Let's move it over to the more updated issue #1000.
