### ISSUE TITLE
Prevent dropdown from opening when disabled

### ISSUE THREAD

**Issue by jeffcarbs** [Semantic-Org/Semantic-UI-React#791]
Currently when the dropdown gets the `disabled` prop it sets the `disabled` class. The default `disabled` styling in SUI-css has the rule `pointer-events: none` which prevents the dropdown from opening by preventing mouse events. However this has two downsides:
- You can't use a `Popup` on a disabled dropdown because the `Popup` depends on mouse events to trigger.
- This only prevents opening on mouse events. The dropdown still opens when tab-focused (screenshot of disabled but open via focus):
<img width="229" alt="screen shot 2016-11-03 at 10 33 18 pm" src="https://cloud.githubusercontent.com/assets/847027/19992614/c3e9443c-a215-11e6-99b0-b627da844cc7.png">

Here's the example on codepen: http://codepen.io/jeffcarbs/pen/yVLgJv?editors=0010

We should prevent the dropdown from opening when in the disabled state in the component itself. FWIW, SUI-core handles this correctly: https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L3144-L3146

Some thoughts in terms of how to handle this:
- Preventing the `open` state from being set to true will be tough, if not impossible, given it's an auto controlled component.
- We could just prevent the menu from opening by changing `const menuClasses = open ? 'visible' : ''` to `const menuClasses = (open && !disabled) ? 'visible' : ''`.
  - There's a lot of logic happening that's purely dependent on the `open` state.
  - It would be weird for state to be `open` and the menu to not be open.
  - Not sure why someone would want to, but you wouldn't be able to manually set open AND disabled at the same time. I guess I could see displaying a disabled notifcation in-menu or something.

I'm kinda leaning 1, with the idea that SUI-react (in the uncontrolled usage) won't set state to open if disabled. However, we won't prevent the user from setting it to open in the controlled state if they choose to.

Thoughts?

cc @levithomason  @layershifter

**Comment by levithomason** [comment]
> We should prevent the dropdown from opening when in the disabled state in the component itself. 
> ...
> I'm kinda leaning 1, with the idea that SUI-react (in the uncontrolled usage) won't set state to open if disabled. However, we won't prevent the user from setting it to open in the controlled state if they choose to.

Agreed.

As a side note, the menu should really have its own `active` or `open` prop as well.  Currently, we're passing classNames down which is against our props API.
