### ISSUE TITLE
Where are real life examples?

### ISSUE THREAD

**Issue by ssachtleben** [Semantic-Org/Semantic-UI-React#797]
Hey,

I like all the examples on the page but i'm missing a bit proper implementation examples. Like a input field and writing the values to the store (using redux). Anyone can link me some examples?

I guess the implementation is different from semantic-ui itself which has an integration example with jquery...

Best,
Seastian

**Comment by levithomason** [comment]
The Semantic-UI-React implementation with Redux is the same as it is with vanilla React.  I'd suggest reading through Redux's excellent [Usage With React](http://redux.js.org/docs/basics/UsageWithReact.html).  Once you have Redux setup, you can use `react-redux` to `connect` Semantic-UI-React components just as you would built-in React components.

---

Though it's well beyond this project's scope, here's a naive example. Say you had a "dumb" UserForm component, for capturing user data:

``` jsx
import React, { Component, PropTypes } from 'react'
import { Form } from 'semantic-ui-react'

class UserForm extends Component {
  static propTypes = {
    name: PropTypes.string,
    email: PropTypes.string,
    onSubmit: PropTypes.func.isRequired,
  }

  handleSubmit = (e, data) => this.props.onSubmit(data)

  render() {
    const { name, email } = this.props
    return (
      <Form onSubmit={this.handleSubmit}>
        <Form.Input label='name' defaultValue={name} />
        <Form.Input label='email' defaultValue={email} type='email' />
        <Form.Button>Login</Form.Button>
      </Form>
    )
  }
}
```

Then, assume you have an "async action" `updateUser()` that updates the user on the server and followed the request/success/failure action dispatch cycle.  You could then add a "container" component to connect the UserForm to the data and async action:

``` jsx
import { connect } from 'react-redux'
import { updateUser } from '../modules/user'

import UserForm from '../components/UserForm'

export default connect(
  state => ({
    name: state.user.name,
    email: state.user.email,
  }),
  {
    updateUser,
  }
)(UserForm)
```

Now, when the UserForm is rendered, it will default to the current Redux store values.  When the UserForm is submitted, it will update the user's info on the server in the store, assuming you've setup your reducer to do so with the update user success action.

What I'd like to note here is that you can replace all the Semantic-UI-React components with _any_ other components you like and not have to change the Redux code.  There are no special paradigms presented here by Semantic-UI-React.

For further help, you may also want to look at the forums: http://forums.semantic-ui.com.  Cheers! 🍻 

> **Disclaimer:** I wrote this ad hoc and didn't actually run this code, so it could have bugs but the point stands.

**Comment by ssachtleben** [comment]
Hey,

thanks for your explaination. My problem is exactly in the submit handler well for me its input handler. This is my "search component":

```
import { Input } from 'semantic-ui-react'

import React, { Component, PropTypes } from 'react';

class Search extends Component
{

    render()
    {
        return (
            <Input size='small' icon='search' placeholder='Search...'
                onInput={this.props.handleInput} />
        );
    }

}

Search.propTypes = {
    handleInput : PropTypes.func.isRequired
};

export default Search;
```

I'm using it like this:

```
<Search handleInput={this.handleSearchInput} />
```

And this is my input handler:

```
handleSearchInput(event) {
    console.log('Search input:', this, event.target.value);
}
```

But this in the method is empty. Log looks like this:

```
Search input: null dsvds
```

 So I dont really know how to write the value into the state. I saw that the event is wrapped in a react event. But couldnt find a suitable method. I just need to access somehow the dispatch or state.

**Comment by ssachtleben** [comment]
ok got it. I was missing the binding in constructor...

```
constructor(props)
{
    super(props);
    this.handleSearchInput = this.handleSearchInput.bind( this );
}
```

**Comment by levithomason** [comment]
Also, `onInput` is not an prop of `<Input />`, you'd be looking for `onChange` 👍
