### ISSUE TITLE
Getting value from Form.Select

### ISSUE THREAD

**Issue by picorelli** [Semantic-Org/Semantic-UI-React#798]
How do I can get a selected value from Form.Select Class? I tried a onChange event, but the result is an undefined value.

**Comment by levithomason** [comment]
The Select has the same `onChange` signature as the Dropdown:

``` jsx
<Select onChange={(e, { value }) => alert(value)} />
```

Working example here: http://react.semantic-ui.com/modules/dropdown#remote

**Comment by jmndao** [comment]
You made my day.... Thanks
