### ISSUE TITLE
Confirmation after Popup disappears

### ISSUE THREAD

**Issue by mikesparr** [Semantic-Org/Semantic-UI-React#807]
I am trying to find the best practice for what I feel may be a common use case where a user mouses over `Popup` options and then upon choosing one, a `Confirm` appears and they must select an action before continuing. 

I have a (OrderProductForm) component built with latest build of SUI-react (`0.58.3`) and uses `<Popup flowing ...` and presents 3 options to choose similar to the examples in docs. Upon clicking `Choose` I update state for a confirm window and the `onConfirm` and `onCancel` handlers do their necessary logic.

If I include this Component in a parent component and trigger the Popup, then click "Choose" the confirm window appears but when I move mouse away from popup towards the confirm buttons, they both disappear.

Is it possible to transition from a`<Popup>` to a `<Confirm>` and if so, how?

![screen shot 2016-11-07 at 3 37 09 pm](https://cloud.githubusercontent.com/assets/5553105/20079023/208a6364-a500-11e6-9141-144c38e186f7.png)

**Comment by mikesparr** [comment]
I display this same component on a page where it displays fixed (not in Popup) and it works fine as expected, but I'd really love to reuse the form component and allow it to be included in popups around site when needed.

## Works fine if not in a Popup

![screen shot 2016-11-07 at 3 44 37 pm](https://cloud.githubusercontent.com/assets/5553105/20079261/21e39f54-a501-11e6-952d-76d5dc4566cb.png)

**Comment by levithomason** [comment]
I wasn't exactly sure of the question here, so I answered two that I thought were potentials.

## Can I nest a Confirm in a Popup and keep the Confirm open after the Popup closes?

No, because the Popup is rendering the Confirm so when the Popup unmounts it will destroy all nodes in its render method, including the Confirm.

## Can I open a Popup, trigger a Confirm, and keep the Confirm open after the Popup closes?

Yep, here you go.

### Demonstration

![http://g.recordit.co/MUfVuz5K5o.gif](http://g.recordit.co/MUfVuz5K5o.gif)

### Working Example

Paste this into the [Popup Flowing](http://react.semantic-ui.com/modules/popup#flowing) example to try it out live:

``` jsx
import React from 'react'
import { Header, Button, Confirm, Popup, Grid } from 'semantic-ui-react'

class PopupExampleFlowing extends React.Component {
  state = {}

  handleClick = (plan) => () => this.setState({ confirm: true, plan })

  render() {
    return (
      <div>
        <Confirm
        open={this.state.confirm} 
        header={`Purchase the ${this.state.plan} Plan`}
        onCancel={() => this.setState({ confirm: false })}
        onConfirm={() => this.setState({ confirm: false })}
        />
        <Popup
          trigger={<Button>Show flowing popup</Button>}
          flowing
          hoverable
        >
          <Grid centered divided columns={3}>
            <Grid.Column textAlign='center'>
              <Header as='h4'>Basic Plan</Header>
              <p><b>2</b> projects, $10 a month</p>
              <Button onClick={this.handleClick('Basic')}>Choose</Button>
            </Grid.Column>
            <Grid.Column textAlign='center'>
              <Header as='h4'>Business Plan</Header>
              <p><b>5</b> projects, $20 a month</p>
              <Button onClick={this.handleClick('Business')}>Choose</Button>
            </Grid.Column>
            <Grid.Column textAlign='center'>
              <Header as='h4'>Premium Plan</Header>
              <p><b>8</b> projects, $25 a month</p>
              <Button onClick={this.handleClick('Premium')}>Choose</Button>
            </Grid.Column>
          </Grid>
        </Popup>
      </div>
    )
  }
}

export default PopupExampleFlowing
```

**Comment by mikesparr** [comment]
Thanks for clarification. I believe my code already does what you illustrate here. It works fine on a page dedicated to the form. When I include the component in the popup though, it fails due to the entire component is the child of the Popup on another page.

I'm trying to reuse the component but on one page it is triggered by a button/popup and another it is just part of the page. I'll brainstorm a way but appreciate your clarification on how the children are destroyed.
