### ISSUE TITLE
Make text property of dropdown accept React.Node not only text

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#825]
Dropdowns can currently only render text, but when I need to add an icon to the dropdown header it is not possible, as there is no way of doing that.

Dropdown HAS icon prop, but that for some reason changes the "carret" icon, and does not add icon to the left of the text. Thanks!

**Comment by levithomason** [comment]
It sounds like you're looking for the `trigger` prop.  This allows you to replace the `text` entirely with any component:

http://react.semantic-ui.com/modules/dropdown#trigger

**Comment by levithomason** [comment]
I should note, you can then disable the caret icon with `icon={null}`.
