### ISSUE TITLE
Basic semantic-ui examples

### ISSUE THREAD

**Issue by bali182** [Semantic-Org/Semantic-UI-React#836]
It would be very nice to have the basic sui examples ( http://semantic-ui.com/usage/layout.html ) using these components. It would be a really big help (even without any business logic).

**Comment by levithomason** [comment]
Indeed, let's leave this one open.  I'd like to add some examples.  We get a lot of questions about CSS especially.  I also think it would be good to add some minimal Webpack examples.
- [x] Port SUI Core layout examples
- [x] Basic Webpack project example
- [x] CDN CSS example
- [x] `semantic-ui-css` example

**Comment by bali182** [comment]
I'm actively trying to recreate some of the samples, if I have some completely recreated, I'll make a PR

**Comment by iamcaleberic** [comment]
@levithomason @bali182 would like to help with this

**Comment by levithomason** [comment]
Awesome, PRs very much welcomed.  I'd like to have the SUI core layout examples in the `/docs` app with a link in the docs sidebar.  The rest of the examples are really full project examples, I'd like to add these to a new directory, `/examples`, with a sub directory for each.

**Comment by bali182** [comment]
Sorry, I kinda forgot about this... I started recreating the login example, component names are spot on, everything was easy to find. However it doesn't really look like the original example:

https://gist.github.com/bali182/c05da546c2b16e74e5c8e9ca1ec3b613

![148123190056399](https://cloud.githubusercontent.com/assets/3879181/21028255/236124e8-bd8c-11e6-85de-1b11f5c30d16.png)

I get the background, but the positioning is weird.

**Comment by iamcaleberic** [comment]
@levithomason thanks for clarifying I'll keep working on it

**Comment by levithomason** [comment]
@bali182 there is sometimes a small amount of override CSS applied to those examples.  I'd inspect the elements and check their styling.  It is likely that the original examples include some CSS that is not coming from the CSS framework.

**Comment by iamcaleberic** [comment]
![screenshot from 2016-12-14 16-36-52](https://cloud.githubusercontent.com/assets/14331364/21190979/a89c3f1a-c21b-11e6-9bbe-bc220ae7eeeb.png)
@levithomason is the menu item for layouts correctly placed

https://github.com/iamcaleberic/Semantic-UI-React/tree/layout_examples

**Comment by levithomason** [comment]
👍 Looks great

**Comment by iamcaleberic** [comment]
@levithomason Do you want to add the layouts page after all the layouts are complete or i can make a pr for it thought it has placeholder links?

**Comment by levithomason** [comment]
I'm a fan of rapid small steps.  If you have even one layout working and the link, we can get that merged.

**Comment by iamcaleberic** [comment]
@levithomason Alright no problem thanks

**Comment by levithomason** [comment]
@iamcaleberic would you like to open a PR with what you have so far and we can get it merged?

**Comment by bobbyz-dk** [comment]
Would be very, very nice with an example of using semantic-ui-css. If someone could get me started I would love to help with it.

**Comment by iamcaleberic** [comment]
@bobbyz-dk to start you off you can checkout my [page](https://github.com/iamcaleberic/iamcaleberic.github.io) in the ` iamcaleberic.github.io/app/src/App.js` folder check the import of semantic css. Alternatively you can the add the cdn for [semantic-ui-css](https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.css) in your root index file

**Comment by iamcaleberic** [comment]
@levithomason  having a bit of an issue with the view source
