### ISSUE TITLE
RFC: `transition` and `popup` common shorthand

### ISSUE THREAD

**Issue by jeffcarbs** [Semantic-Org/Semantic-UI-React#837]
### Background

I've been using `<Popup>` in my app for tooltips and it's a little cumbersome to use. Here's an example usage for showing a popup on a disabled button (note: this doesn't actually work out of the box since pointer-events are disabled on buttons 😐 )

```js
const buttonElement = (
  <Button
    content='Some action!'
    disabled={disabled}
    loading={loading}
    onClick={onClick}
    primary
  />
)

if (!disabled) {
  return buttonElement
}

return (
  <Popup
    content='This button is disabled!'
    trigger={buttonElement}
  />
)
```

### Proposal

What if we were to add a `popup` common shorthand prop to all components. The same example from above could be written as:

```js
<Button
  content='Some action!'
  disabled={disabled}
  loading={loading}
  onClick={onClick}
  popup={disabled && 'This button is disabled!'}
  primary
/>
```

Under the hood, it would use a `Popup.create` shorthand factory:
```js
Popup.create(props.popup, { trigger: /*regularly rendered button*/ })

// In this case would render
<Popup content='This button is disabled!' trigger={<Button>Some action</Button>} />
```

### Transition

The `Transition` component (currently underway in #813) strikes me as something that will have the same cumbersome usage.
```js
<Transition animation='slide'><Button /></Transition>
```
could be written as
```js
<Button transition='slide' />
```

To me the former reads like "render a transition that results in a button", whereas the latter reads more naturally: "render a button with the slide transition".

Both the `transition` and `popup` props would be shorthand so they could be customized even further. For example:

```
<Button popup={{ inverted: true, on: 'click', content: 'Clicked!' }} />
```

### Implementation

I think it would be crazy to try to do this with our components as-is given that we'd have to touch every single file. I really think we need to solve #419 first and get all of our components rendering via some common method. Whether it's a render method utility, a base component that every component eventually renders down to, or some factory.

cc @layershifter @levithomason - would love your thoughts!

**Comment by levithomason** [comment]
Man, I love your proposals :)  Yes, a `popup` prop has been on mind since day one.  I also think we should solve the base component idea before doing this.

I hadn't considered transition, but it also makes perfect sense to me.  This gets me thinking that the Dropdown menu could also take advantage of this pattern, using `trigger`.  Really, any component wraps or appears beside another component could / should be added as a prop IMO.  

Imagine:

``` jsx
<Dropdown trigger={<Image avatar src='...' />} options={options} />

// vs

<Image avatar src='...' dropdown={options} />
```

Not only is a single import needed, but it seems like it follows the more natural logical progression "I want to add a Popup/Dropdown to an Image" rather than "I want to wrap an Image in a Popup/Dropdown".

**Comment by levithomason** [comment]
I've removed this from the 1.0 requirement, still think we should do this, just not as a blocking item.

**Comment by padrefuture** [comment]
Im looking into building a menu with an animated transition. Was thinking of using popup with a transition but it doesnt seem to work. Any ideas?

**Comment by layershifter** [comment]
Transitions aren't supported by components yet. We're working on it, no ETA.

**Comment by padrefuture** [comment]
This site: http://stoplight.io/platform/design/
was listed as an example site...is this not built in React / Semantic UI?
I suppose i will build the menu without in hopes of adding later. Only other option is to use something other than react?

**Comment by levithomason** [comment]
@padrefuture Note that most landing pages are not built with React.  React is best suited for apps.  Stoplight still appears to use SUIR in their apps:

https://app.stoplight.io
https://next.stoplight.io

**Comment by levithomason** [comment]
Thanks to @rijk, we have improved how we handle stale issues, see #2761.   Reopening.

**Comment by pferreir** [comment]
Any news on this? Any way I could help?
