### ISSUE TITLE
Consistent Input change API 

### ISSUE THREAD

**Issue by destan** [Semantic-Org/Semantic-UI-React#842]
As stated [here](https://github.com/Semantic-Org/Semantic-UI-React/issues/638#issuecomment-252044282) `<Checkbox>`, `<Radio>` and `<Dropdown>` components has a second argument for `onChange` but other inputs don't.

As stated [here](https://github.com/Semantic-Org/Semantic-UI-React/issues/638#issuecomment-252047219) @levithomason says he will make input's `onChange` have 2 arguments.

I thought it would be nice to have an issue to track this.

**Comment by levithomason** [comment]
Sounds good, this should be an easy PR.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.60.5`
