### ISSUE TITLE
Knob dial component 

### ISSUE THREAD

**Issue by SanskarSans** [Semantic-Org/Semantic-UI-React#843]
This library has covered almost all component but there is no Interactive knob dial like component which can be used so much in analytics. Will this come sooner if not soon?

Thanks

**Comment by levithomason** [comment]
Note, this project only concerns itself with JavaScript components that render down to valid Semantic-UI HTML.  Issues related to Semantic-UI HTML or CSS should be opened on the main repo:

https://github.com/Semantic-Org/Semantic-UI

Once the primary framework supports a new feature, we'll implement it here.  Cheers!

P.S.

I do not know if such a component is under consideration yet.
