### ISSUE TITLE
Server side rendering failing 

### ISSUE THREAD

**Issue by gz2432** [Semantic-Org/Semantic-UI-React#848]
Server side rendering fails at `lib/debug.js`

>             console.warning('Semantic-UI-React could not enable debug.');

Works in v60.0.4.  Appears #518 removed the fix from #365.

**Comment by levithomason** [comment]
`console.warning` is not a method in Node.  I've replaced it with `console.error` instead.  Releasing a patch, hang tight...

**Comment by levithomason** [comment]
Have a go with `semantic-ui-react@0.60.6`.  There is a browser check now that should resolve the issue.

**Comment by gz2432** [comment]
Yep works now.  Thanks!
