### ISSUE TITLE
Dropdown bug in react semantic-ui website

### ISSUE THREAD

**Issue by georges-hatem** [Semantic-Org/Semantic-UI-React#850]
### Steps to reproduce
1. Go to http://react.semantic-ui.com/collections/menu#size
2. Click on the "Language" dropdown on the right-hand side
3. Click anywhere on the page afterwards, a typeerror appears in the browser console:
    Uncaught TypeError: a._dropdown.blur is not a function
4. The dropdown that caused the error no longer opens afterwards

### Version
Not sure which version is used on the website, but the npm version is v0.60.6 at the time of writing.

**Comment by levithomason** [comment]
Duplicate #659

**Comment by georges-hatem** [comment]
ah sorry, my bad

**Comment by levithomason** [comment]
No worries, happens a lot :)  Thanks for looking out for us.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.4`.
