### ISSUE TITLE
User defined theming

### ISSUE THREAD

**Issue by kolpav** [Semantic-Org/Semantic-UI-React#851]
Hello,

First of all thanks for this absolutely awesome library! Its the only one I don't have to fight to get things done.

To my question.
Lets imagine we have web application where users can create blogs. Its build using Semantic a you would like to allow your users to customize theme for each of their blogs. Your application is super popular with millions blogs each with different theme.

I would like theme creation page where all components would be displayed and user could edit different variables and more advanced users could even write css for each component. Changes to theme could be previewed in real time or after refresh.

Is something like this even possible? Can you please elaborate on different solutions to this problem? I must admit I am not that good with CSS so there might be obvious solution.

**Comment by levithomason** [comment]
This repo only concerns itself with JS components that render valid Semantic-UI HTML.   All CSS is handled elsewhere.  You can read #366 for a little more on theming.

I would also suggest taking a look at the power of Semantic-UI theming by visiting https://github.com/Semantic-Org/example-github.  This repo shows a live editable theme, you can take inspiration from there on how to allow users to "select" different themes.  In the README.md click on "Modern Layout", then:

![image](https://cloud.githubusercontent.com/assets/5067638/20275134/30e5bb90-aa4c-11e6-9198-7f2a89d47565.png)
