### ISSUE TITLE
Very low performance caused by `getUnhandledProps`

### ISSUE THREAD

**Issue by ladjzero** [Semantic-Org/Semantic-UI-React#859]
I have Form and Table inside of Container. And Table would be updated asynchronously.

I found that the UI is laggy when updating state, (updating table data), and eventually the browser may crash if I update table twice and more.

According to the CPU profiles, it seems that `getUnhandledProps` consumes too much time. (it calls baseClone which is very time-consuming)

![selection_458](https://cloud.githubusercontent.com/assets/4110311/20298115/1e2cf424-ab4f-11e6-8e79-85140f6e7219.png)

How I can avoid of `getUnhandledProps`?

### Version
0.59.0

```javascript
import React from 'react'
import { Container, Form, Table, Icon, Button, Modal, Segment, Dimmer, Loader } from 'semantic-ui-react'

export default class FaildedMessage extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      messages: [],
      searching: false,
    }
  }

  search() {
    this.setState({ searching: true})
    setTimeout(() => {
      this.setState({
        searching: false,
        messages: [1,2,3,4,5,6,7,8,9,10]
      })
    }, 1000)
  }

  render() {
    const { messages, searching } = this.state

    return (
      <Container>
        <Form size="small">
          <Form.Group>
            <Form.Button
              basic
              primary
              loading={searching}
              onClick={e => {
                e.preventDefault()
                this.search()
                // sorry, the statement below is pasted here by mistake. please remove it.
                //this.setState({ searching: !searching })
              }}
              style={{
                position: 'absolute',
                right: 0,
                bottom: 0,
              }}
            >查询</Form.Button>
          </Form.Group>
        </Form>

        <Segment basic size="small" style={{ marginTop: '2rem', padding: 0 }}>
          <Dimmer inverted active={searching}>
          <Loader inverted />
          </Dimmer>
          <Table basic>
          <Table.Header>
            <Table.Row>
              <Table.HeaderCell>ID</Table.HeaderCell>
              <Table.HeaderCell></Table.HeaderCell>
            </Table.Row>
          </Table.Header>
          <Table.Body>
          {
            messages.map(m => (
              <Table.Row key={m}>
                <Table.Cell>{m}</Table.Cell>
                <Table.Cell textAlign="right">
                  <Modal dimmer="blurring" size="small" trigger={<Button basic primary icon="info" circular size="mini" />}>
                    <Modal.Header>alert</Modal.Header>
                    <Modal.Content>hehe</Modal.Content>
                    <Modal.Actions>
                      <Button.Group>
                        <Button basic color="red">delete</Button>
                        <Button basic color="red">cancel</Button>
                      </Button.Group>
                    </Modal.Actions>
                  </Modal>
                </Table.Cell>
              </Table.Row>
            ))
          }
          </Table.Body>
          <Table.Footer>
          <Table.Row>
          <Table.HeaderCell colSpan="8">
            </Table.HeaderCell>
            </Table.Row>
          </Table.Footer>
          </Table>
        </Segment>
      </Container>
    )
  }
}

```

**Comment by levithomason** [comment]
Thanks for the report, I'll look into this.  I've profiled a similar issue when using redux for form data onChange.  That is a known pattern to cause lag, but this was only a 2 field form.  I'll be investigating performance in the near future.

**Comment by levithomason** [comment]
I also notice a bug in your code:

``` js
this.search()
this.setState({ searching: !searching })
```

`this.search()` sets `this.state.searching` to `true`, then state is immediately set again, `this.setState({ searching: !searching })`.  `this.search()` will not wait for the `setTimeout` to finish since it is a callback and is asynchronous.  The variable `searching` at that point is still `false` because it was plucked from `this.state` above, before `this.search()` was called.  So it is again trying to `this.setState({ searching: true })`.

You can tell by doing:

``` js
this.search()
alert(searching) // false
this.setState({ searching: !searching })
```

So you can remove `this.setState({ searching: !searching })` from the click handler.

Also, I do not see any lag when I paste your example into the doc site and run it.  Where are you seeing lag?

**Comment by levithomason** [comment]
@ladjzero I've just released a fix in `semantic-ui-react@0.60.10`, let me know your results.

**Comment by ladjzero** [comment]
@levithomason thank you for your comment 
sorry, the statement `this.setState({ searching: !searching })` is pasted here by mistake. I'll remove it and try 0.60.0

**Comment by levithomason** [comment]
Sounds good, I'm assuming you mean `v0.60.10` ;)

**Comment by ladjzero** [comment]
@levithomason I've tried. It works perfectly. Thank you for your attention.

**Comment by levithomason** [comment]
Awesome! 🎉 Thanks for reporting back.
