### ISSUE TITLE
Support jsnext:main and module fields

### ISSUE THREAD

**Issue by dvdzkwsk** [Semantic-Org/Semantic-UI-React#862]
This is fairly low on the priority list, especially since `v1.0.0` is still looking to be shipped, but I wanted to document it for record keeping.

It would be great for SUIR to provide a bundle that maintains ES6 imports/exports so that bundlers that natively understand ES6 modules (webpack 2, rollup) can [tree shake](https://blog.engineyard.com/2016/tree-shaking) its usage in order to produce smaller bundles. Adding support for `babel-plugin-lodash` is already a great start, especially for webpack 1.0 and similar; this change would take it a step further by allowing bundlers to perform the same thing natively without the overhead of additional tooling.

**Note:** it's important that the code still be preprocessed with babel, because we should not assume anything else about the user's environment.

I believe that this is important piece of functionality, especially as the library grows, because it means that users don't have to be as concerned about the library's weight as a whole and can reap the benefits of targeted bundles without additional work on their part, especially as more bundlers implement tree shaking natively.

See:
* https://github.com/ReactTraining/react-router/pull/3672
* https://github.com/reactjs/redux/issues/1042

### Steps
1. Import SUIR in a bundler that understands ES6 modules.
2. Do not use a plugin to transform imports (such as `babel-plugin-lodash`)

### Expected Result
Unused SUIR code should not be included in the final bundle.

### Actual Result
All SUIR code is put into the bundle regardless of whether or not it was used.

### Version
all

**Comment by levithomason** [comment]
Agreed, this should be pretty easy to setup.

**Comment by levithomason** [comment]
Can reference this PR for a roadmap, https://github.com/reactjs/redux/pull/1369.

**Comment by levithomason** [comment]
@davezuko is something you'd want to pick up?

**Comment by dvdzkwsk** [comment]
I could, but don't want to assign it to myself until I have time to commit to it, especially with the holidays coming up. Will keep it in mind and if I manage to take a crack at it I'll let you know/post a PR and link here.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.4`.
