### ISSUE TITLE
Support onKeyDown in Input

### ISSUE THREAD

**Issue by cattermo** [Semantic-Org/Semantic-UI-React#884]
To be able to allow/disallow different keys in input fields it would be nice if the `Input` component would have an `onKeyDown` prop where I could provide my custom event handler. If I call `e.preventDefault()` in the `onKeyDown` event handler the `onChange` handler would not be called.

This might be as easy as to add the `onKeyDown` into `htmlInputPropNames` array?

### Version
0.60.9

**Comment by levithomason** [comment]
You're correct, I've added #886 to address this.  I also tested it in the browser to ensure it works as expected.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.61.1`.

**Comment by danydhondt** [comment]
The `onKeyDown` property should be added to the documentation. Great feature!

**Comment by guillemcanal** [comment]
@levithomason I may be wrong, but it don't seems to be supported anymore.

**Comment by lextoc** [comment]
Doesn't seem to be present in `"version": "0.86.0"`, is it removed? Is there a way to force a regex on user input via event listeners?

**Comment by svey** [comment]
why was this removed?

**Comment by layershifter** [comment]
@guillemcanal @svey 
It's supported, please check: https://codesandbox.io/s/semantic-ui-example-kt84y. It also covered in our docs: https://react.semantic-ui.com/augmentation#unhandled-props-dom-attributes
