### ISSUE TITLE
Dropdown gets clipped when rendering within a modal or a window

### ISSUE THREAD

**Issue by dkwin** [Semantic-Org/Semantic-UI-React#888]
### Steps
1. Trying to render a simple semantic ui dropdown within a table cell, the dropdown list gets clipped

### Expected Result

Dropdown should not be clipped or atleast configurable not to be clipped.  I believe this is an issue with the CSS?

### Actual Result

Semantic UI dropdown is clipped when it should not be.

### Version
0.61.0

### Testcase
![overlaycelldropdown](https://cloud.githubusercontent.com/assets/3934306/20404258/2d3976e8-acd2-11e6-80db-a71bcde18d31.gif)

Left dropdown is the semantic ui dropdown and right dropdown is a native dropdown.  The left dropdown gets clipped and it is un-usable, whereas the right dropdown does not clip and the user can select options.

**Comment by levithomason** [comment]
Duplicate #497.

This in indeed strictly a CSS issue, please file the issue on the main repo as this project only deals with JS components that render valid SUI HTML.
