### ISSUE TITLE
Inconsistent selection dropdown behavior

### ISSUE THREAD

**Issue by congrady** [Semantic-Org/Semantic-UI-React#899]
Hello,

I have a problem with selection dropdown

In DEV environment (not-minified), dropdown selection closes after clicking on it.

In PROD environment (minified, uglified), dropdown doesn't close and stays open forever.
A very strange inline style appears (adds `display: block !important;` to the menu). 
If I manually remove this inline style (using chrome dev tools), dropdown closes as expected.

This is how my component looks like.

```
  <Dropdown
      options={options}
      selection
      onChange={(e, opt) => {
        const value = opt.value ? opt.value : e.target.value;
        router.navigate({ queryParams: { location_id: value } });
      }}
      defaultValue={location_id}
  />
```

Is there a way to programatically close dropdown? Or is there any other solution that would close the dropdown after selecting an item or clicking on dropdown's "head"?

Thanks

**Comment by levithomason** [comment]
Hm, it sounds like you might have the jQuery plugin also running in your PROD environment.  We do not add any `display: block !important;` styles, but the jQuery plugins do.  Can you first verify this?

It is best to submit the codepen in the issue template when submitting bug reports, this way we can debug actual usages in a controlled environment.  That said, the default codepen we provide is built with built with `NODE_ENV=production` and the Dropdown works there, http://codepen.io/levithomason/pen/ZpBaJX.

Also, the doc site is built in production mode and the Dropdowns there work.

**Comment by congrady** [comment]
Hi, thanks for the answear!

Yes, you are right. I am using jQuery in my production mode. My SPA (that uses react-semantic) is just a subpart of the entire site (which uses classic semantic with jQuery).

Do you have any suggestion that might help me solve this problem? To be fair, I have no idea how one would fix this. Thanks!

**Comment by levithomason** [comment]
The good news is that we wrote Semantic-UI-React _entirely jQuery free_ so you can use the entire library without any Semantic-UI core JavaScript or jQuery.  You can see a little note about that here: http://react.semantic-ui.com/introduction#jquery-free.

The bad news here is that I'm not sure how you'd prevent your legacy Semantic-UI plugins from invoking on top of your React components.  I see no way to make these two compatible. :/

I would work to separate your two apps.   Currently, they are loading conflicting JavaScript (jQuery plugins and React components) that are both trying to manipulate and control the same section of the DOM, at the same time, and with the same class selectors.
