### ISSUE TITLE
Replace class usage with attributes.

### ISSUE THREAD

**Issue by eanplatter** [Semantic-Org/Semantic-UI-React#9]
<h1>Button</h1>
- [ ] fluid
- [ ] colors (all semantic colors)
- [ ] size (all semantic sizes)

<h1>Image</h1>
- [ ] fluid
- [ ] rounded
- [ ] circular
- [ ] ["top aligned", "middle aligned", "bottom alignded"]
- [ ] size
- [ ] centered
- [ ] bordered
- [ ]

**Comment by levithomason** [comment]
This has now been reverted.  We will be handling Semantic UI classes as classes in the grand majority of cases.  See the [Component Guidelines](https://github.com/TechnologyAdvice/stardust/blob/master/docs/app/Component%20Guidelines.md) for specifics.
