### ISSUE TITLE
fix(Input): onChange callback does not pass the value of the input when using Input with children

### ISSUE THREAD

**Issue by josie11** [Semantic-Org/Semantic-UI-React#909]
Similar to this open issue: https://github.com/Semantic-Org/Semantic-UI-React/issues/907

When using the Input component with children, you have to use the onChange callback with the child input tag, and no second data parameter is passed to the callback.

**Steps to Reproduce**
1. Create a Input with children, you must use your own <input /> tag as per the Docs. The semantics <Input> tag will not run the onChange callback, you must pass as an option in your <input /> tag.
2. pass the onChange option with a callback option, have the callback console.log the arguments.

**Expected**
The onChange callback function should receive the input value as a second parameter in the callback.

**Result**
The callback option does not receive the value of the input as the second parameter.

**Testcase**
http://codepen.io/tintin301/pen/rWyBvw

**Comment by levithomason** [comment]
Thanks for the report, this is a confirmed bug.  We are not passing any of the `htmlInputProps` to the `input` child.

**Input.js**
```jsx
const htmlInputProps = _.pick(this.props, htmlInputPropNames)
if (onChange) htmlInputProps.onChange = this.handleChange

const ElementType = getElementType(Input, this.props)

if (children) {
  return <ElementType {...rest} className={classes}>{children}</ElementType>
}
```

We need to find the input child and spread the `htmlInputProps` on it.  We have a `findByType()` util in `lib` for this.  We simply need to find the input child and spread the props on it.

**Comment by levithomason** [comment]
See #916, will merge on pass.
