### ISSUE TITLE
Spread unhandled props on the root element

### ISSUE THREAD

**Issue by athurman** [Semantic-Org/Semantic-UI-React#91]
The issue I am running across, is when passing a style object into the Checkbox component, it acts as it should and applies styles to the actual checkbox input, yet I need the styles to be attributed to the parent `'ui checkbox'` div in order to get it to float right as needed.

Here is a screen shot of how the custom styled checkbox renders:
<img width="581" alt="screen shot 2015-10-25 at 2 14 43 pm" src="https://cloud.githubusercontent.com/assets/5421430/10717355/361476d2-7b23-11e5-9907-7bb7b60dac52.png">

Because the style shows on the input, and not the parent semantic div, the entire checkbox semantic element  does not float right as it should.

Here is a screenshot of the rendered markup:
<img width="1207" alt="screen shot 2015-10-25 at 2 15 37 pm" src="https://cloud.githubusercontent.com/assets/5421430/10717358/633bb33c-7b23-11e5-91f7-efd168701f40.png">

**Comment by levithomason** [comment]
This makes sense.  Labeled and renamed.

For this use case you can probably achieve the same result by splitting the header and using alignment classes.

**Comment by levithomason** [comment]
Updated this description and marked for v1 release. I think we should spread unhandled props on the root element. This will not only solve the issue above but also give predictable results. Event handlers will still also bubble up to the root component from any input children.

**Comment by levithomason** [comment]
Done.  All components now spread props on the root element.
