### ISSUE TITLE
append extra data to Components such as Form.Select

### ISSUE THREAD

**Issue by georges-hatem** [Semantic-Org/Semantic-UI-React#912]
#### Follow-up from Gitter

> Hello, I am trying to append extra data to the Form.Select options, for use upon selecting an option, as such:
```
const productOptions = this.props.products.map(function(p) {
  return {
    'text': p.label,
    'id': p.id,
    'value': p.label
  }
});

handleProductChange(e, selected) {
  console.log("changed product:");
  console.log(selected.value);
  console.log(selected.id);
}
```

> products is an array of product objects that contain fields for id and label.
> following the docs, 'value' is printing correctly, but 'id' is undefined.

> Is there any way to do this, to identify which item was selected? (label may not be unique)

#### Reply from @levithomason 

> We are currently working to standardize all callbacks to include all the data one might need. 

Thanks!

**Comment by levithomason** [comment]
Confirmed, per https://github.com/Semantic-Org/Semantic-UI-React/issues/623#issuecomment-261018287, we're updating all callbacks to follow the signature `(event, data)` where `data` includes as much information as possible.  This will usually be a combination of `props` and `state`.

The Select is a variation of the Dropdown.  Currently, the Dropdown `onChange` callback only passes back `{ name, value }` of the newly active item. We simply need to spread the item's props in the callback here:

https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L416

Then update the `onChange` prop description per the new callback spec, shown in https://github.com/Semantic-Org/Semantic-UI-React/issues/623#issuecomment-261018287.

Finally, we need to add a Dropdown `onChange` test that asserts that extra item props are passed back `onChange`.

**Comment by levithomason** [comment]
As I began work on this, I realized this has come up before and I'm not sure we should make this change.  See #754.

@jcarbo do you have any input on this?  The issue I linked just above has a succinct description of the issue and my initial conclusion.  We can technically support this and it would make the the callback signature more consistent with other components (passing back `data` instead of a string or array of strings) but I think it also means we'd need to change the Dropdown value prop for `multiple` from an array of values to an array of option objects.  This way, we're either using all "primitive values" or all "object literals" for the value and callbacks.  I don't think we should mix and match the two.  Otherwise, you can't capture `onChange` and pipe it to `value`.

**Comment by jeffcarbs** [comment]
IMHO, I think we're conflating the handlers for `onClick` in `DropdownItem` and `onChange` in `Dropdown`:
- `DropdownItem`'s `onClick` should return the `(e, clickedDropdownItemProps)`. Internally the `Dropdown` uses this handler to detect changes and library users can tap into this handler directly if they want.
- `Dropdown`'s `onChange` should return `(e, { ...dropdownProps, value: dropdownState.value)`. `value` will either be an array or a literal depending on the `multiple` prop. Given the fact that `Dropdown` is auto-controlled, the `value` it returns would be the "proposed" value.

I don't think the `Dropdown` should return any information about the most recently clicked item. It uses the click event to determine what it's next value should be, and that value is what is returned in the `data` of the `onChange`. 

We should make the following change:
```diff
  handleChange = (e, value) => {
    debug('handleChange()')
    debug(value)
-   const { name, onChange } = this.props
-   if (onChange) onChange(e, { name, value })
+   const { onChange } = this.props
+   if (onChange) onChange(e, { ...this.props, value })
  }
```

Within `data` there'd be enough information (the `options` and `value`) to derive the necessary fields in the case where you want to provide additional data.

Another thing to consider for this particular use-case is that whatever additional props that are included in each object of `options` will be spread onto the underlying `DropdownItem` div. So in the example where you're adding the `id` in each option it's actually going to set the HTML `id` attribute of each `DropdownItem`.

I think going down the path of `value` being an object or array of objects representing the currently selected option(s) would be too complex.

**Comment by levithomason** [comment]
>`DropdownItem`'s onClick should return the `(e, clickedDropdownItemProps)`... `Dropdown`'s onChange should return `(e, { ...dropdownProps, value: dropdownState.value)`

Ah, of course.  How I missed this, I dunno.  This is obviously correct, thanks much.

@Khorkhe we'll close this and call it a duplicate of #754 which includes help on how to get the data you need.  Those suggestions are also future proof against our upcoming changes to standardize all callbacks, detailed in #623.

**Comment by georges-hatem** [comment]
@levithomason, @jcarbo,

Thanks for the great feedback.  Thinking about it again, having multiple dropdown items with the same value would be a terrible idea. So the workaround presented in #754 will be sufficient, as well as enforcing uniqueness of values on the backend.
