### ISSUE TITLE
react.semantic-ui.com is down

### ISSUE THREAD

**Issue by devsli** [Semantic-Org/Semantic-UI-React#914]
### Steps

1. Open react.semantic-ui.com

### Expected Result

Documentation displayed

### Actual Result

Github 404 File not found error

### Version

current

### Testcase

None

**Comment by levithomason** [comment]
Thanks, per #915, it looks like GH was (is?) having issues serving gh-pages branches.  It is partially resolved as of now.

**Comment by Simba-Mupfunya** [comment]
The site is down again

**Comment by layershifter** [comment]
There are two issues for this problem: #1404 #1429.
