### ISSUE TITLE
Unable to access documentation

### ISSUE THREAD

**Issue by padsbanger** [Semantic-Org/Semantic-UI-React#915]
Hello,

When I am trying to access documentation via: http://react.semantic-ui.com/ I get Gitub 404, anyone else seeing this too ?

**Comment by daugsbi** [comment]
Hey, got the same problem here. 

### Steps
1. Click the official link in your readme to: https://semantic-org.github.io/Semantic-UI-React/
2. Redirects to http://react.semantic-ui.com/ with 301.
OR 
1. Directly enter http://react.semantic-ui.com/

### Expected Result
The Documentation page should be shown (as before)

### Actual Result
404 Page not found from github

### Alternative workaround
1. Call http://react.semantic-ui.com/index.html
2. Renders 404 page of react doc -> then navigation works fine
3. A reload of i. e. at http://react.semantic-ui.com/elements/container returns 404 github page again.

**Comment by sioked** [comment]
@daugsbi Thanks for the workaround!

**Comment by daugsbi** [comment]
Your welcome.

It looks like there is a problem with github pages in general. The status page https://status.github.com/ reference it as
"16:07 CET - We're investigating an increase in 404 responses when serving GitHub Pages."

**Comment by levithomason** [comment]
Hm, I'm not seeing this issue and from @daugsbi's comment.  It seems to be on GH's side.  Going to close for now since it is beyond our control.  Thanks for the report and helpful workarounds everyone!
