### ISSUE TITLE
Support for Menu.Item defaultActive parameter

### ISSUE THREAD

**Issue by zeneben** [Semantic-Org/Semantic-UI-React#918]
Much like there is a `defaultValue` for `Input`, and a `defaultChecked` for checkboxes, would it make sense to support a `defaultActive` for `Menu.Item`s that you do not wish to bind the `active` state? My use case is that I would like to populate the `active` state of a `Menu.Item` from the query string on initial page load. But subsequent clicks to the `Menu.Item` should update that URL through an event handler. The way I handle this in `Input`s is just to use the `defaultValue` parameter which works swimmingly.

Sorry, I don't have a test case for this since it's more of a feature request than a bug.

**Comment by levithomason** [comment]
Menu shorthand is poorly documented and there is no example for this, but it is already available:

http://codepen.io/levithomason/pen/ENmgEY

If you're using the `items` prop of the `Menu`, then you're looking for `defaultActiveIndex` 👍

**Comment by zeneben** [comment]
I should have mentioned, I did notice this for the Menu Item, but in my case I'm using the Menu as a multiple-select filter. Is there a way I could have multiple active indexes? 

```
const items = ['Running', 'Success', 'Failed']

# I'd like to have both 'Success' and 'Failed' selected 
const App = () => <Menu items={items} defaultActiveIndexes={[1, 2]} />
```

**Comment by zeneben** [comment]
Hmm, upon looking further into this, I may be using Menu.Items wrong. Perhaps I should be using Checkboxes instead? And using the `as` parameter to render them as Menu.Items so they'll fit snlugly into the menu I've embedded them in.

**Comment by levithomason** [comment]
Hm, it sounds like you might be looking for a `<Button.Group />` with some buttons active?

http://react.semantic-ui.com/elements/button#group

Perhaps a group of toggle buttons?

http://react.semantic-ui.com/elements/button#toggle

**Comment by zeneben** [comment]
Yes but again, without a defaultActive parameter I'm back in the same
situation.

**Comment by levithomason** [comment]
Correct, you'd be using a controlled component pattern for this to work.
