### ISSUE TITLE
Peer dependency

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#924]
Hi, jus wondering why are you keeping peer dependences

```
 "react": ">=0.14.0 <= 15",
    "react-dom": ">=0.14.0 <= 15"
```

Do you really want such old react?

**Comment by levithomason** [comment]
You're free to use any version in the range.  We use the latest version.  I see no harm in allowing older versions of React, since, we're not doing anything special to support them.  If we run into bugs or hangups related to older version then we'll update the version range but I wouldn't want to arbitrarily claim we support a smaller version range.

**Comment by jonashao** [comment]
I got a problem when I install semantic-ui-react,  but I had react and react-dom the latest version installed.

+-- UNMET PEER DEPENDENCY react@>=0.14.0 <= 15
+-- UNMET PEER DEPENDENCY react-dom@>=0.14.0 <= 15
`-- semantic-ui-react@0.62.0
  +-- classnames@2.2.5
  +-- debug@2.3.3
  | `-- ms@0.7.2
  `-- lodash@4.17.2

npm WARN semantic-ui-react@0.62.0 requires a peer of react@>=0.14.0 <= 15 but none was installed.
npm WARN semantic-ui-react@0.62.0 requires a peer of react-dom@>=0.14.0 <= 15 but none was installed.

**Comment by levithomason** [comment]
I cannot reproduce this on a fresh project:

```
in foo/  
› npm i react react-dom -S
foo@1.0.0 /Users/levithomason/src/foo
├─┬ react@15.4.1 
│ ├─┬ fbjs@0.8.6 
│ │ ├── core-js@1.2.7 
│ │ ├─┬ isomorphic-fetch@2.2.1 
│ │ │ ├─┬ node-fetch@1.6.3 
│ │ │ │ ├─┬ encoding@0.1.12 
│ │ │ │ │ └── iconv-lite@0.4.15 
│ │ │ │ └── is-stream@1.1.0 
│ │ │ └── whatwg-fetch@2.0.1 
│ │ ├─┬ promise@7.1.1 
│ │ │ └── asap@2.0.5 
│ │ └── ua-parser-js@0.7.12 
│ ├─┬ loose-envify@1.3.0 
│ │ └── js-tokens@2.0.0 
│ └── object-assign@4.1.0 
└── react-dom@15.4.1 

npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.

in foo/  
› npm i semantic-ui-react -S 
foo@1.0.0 /Users/levithomason/src/foo
└─┬ semantic-ui-react@0.62.0 
  ├── classnames@2.2.5 
  ├─┬ debug@2.3.3 
  │ └── ms@0.7.2 
  └── lodash@4.17.2 
```

If I'm missing react and/or react-dom, then I get warnings:

```
in foo/  
› npm un react react-dom -S
- asap@2.0.5 node_modules/asap
- core-js@1.2.7 node_modules/core-js
- iconv-lite@0.4.15 node_modules/iconv-lite
- encoding@0.1.12 node_modules/encoding
- is-stream@1.1.0 node_modules/is-stream
- js-tokens@2.0.0 node_modules/js-tokens
- loose-envify@1.3.0 node_modules/loose-envify
- node-fetch@1.6.3 node_modules/node-fetch
- object-assign@4.1.0 node_modules/object-assign
- promise@7.1.1 node_modules/promise
- ua-parser-js@0.7.12 node_modules/ua-parser-js
- whatwg-fetch@2.0.1 node_modules/whatwg-fetch
- isomorphic-fetch@2.2.1 node_modules/isomorphic-fetch
- fbjs@0.8.6 node_modules/fbjs
- react@15.4.1 node_modules/react
- react-dom@15.4.1 node_modules/react-dom
npm WARN semantic-ui-react@0.62.0 requires a peer of react@>=0.14.0 <= 15 but none was installed.
npm WARN semantic-ui-react@0.62.0 requires a peer of react-dom@>=0.14.0 <= 15 but none was installed.
npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.
```

Nuke your node_modules and install again.
