### ISSUE TITLE
Docs site down due to react version not on cloudflare

### ISSUE THREAD

**Issue by Johnnycon** [Semantic-Org/Semantic-UI-React#934]
Looks like the docs site is down because it's pointing to a reactjs version 15.4.1 that isn't on cloudflare yet.  Seeing 404's for that file.

**Comment by keeslinp** [comment]
Yeah, the most recent version on cloudflare is 15.4.0. It looks like Greenkeeper.io updated everything automatically before cloudflare got a new version up. I would have thought the tests would have failed and stopped the process but I guess not. Commit #923 and #924 are the ones causing it.

**Comment by levithomason** [comment]
Thanks guys. The publishing process for cdnjs is automated, so I assume it will update timely.  However, I'll roll that back to get us by for now.

**Comment by levithomason** [comment]
Fixed in 4471d3dec1988724dbf6ac18686fc6d976079fec.  Will go live when this build finishes:

https://circleci.com/gh/Semantic-Org/Semantic-UI-React/1026

**Comment by levithomason** [comment]
Sorry folks, I failed to remove the `^` from the version bump, so `15.4.1` was installed anyway.  I've just locked in the exact version and redeployed:

https://circleci.com/gh/Semantic-Org/Semantic-UI-React/1030

**Comment by Johnnycon** [comment]
Thanks @levithomason - your efforts are certainly appreciated :) Great work on this library!

**Comment by levithomason** [comment]
💥 
http://react.semantic-ui.com
