### ISSUE TITLE
Documentation Incorrect

### ISSUE THREAD

**Issue by jimmyspiffy** [Semantic-Org/Semantic-UI-React#935]
GOTO: http://react.semantic-ui.com/usage

Scroll to the bottom.

The following is incorrect:
`npm install semantic-ui --save-dev`

It should be:
`npm install semantic-ui-react --save-dev`

(^_^)Y

**Comment by levithomason** [comment]
`semantic-ui` is actually correct in this case as it is referring to instructions on creating a custom theme, which is done with the main project.  `semantic-ui-react` only concerns itself with React components that render down to valid Semantic UI HTML.  We do not provide any CSS as this is handled by the main project.
