### ISSUE TITLE
Image size="medium" collides with name="medium"

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#937]
Please rename the Icon medium to support the medium size with other icons or reorder the position in the icon.css so, that the medium selector is defined before the other selectors.
Otherwise size="medium" will render the medium char.

**Comment by levithomason** [comment]
Could you please provide a codepen, the results you're expecting, and the actual results? It is immensely helpful for us to understand the issue and help find a proper solution. 

This project also does not provide any CSS so issues related to CSS may need to be opened on the main Semantic UI repo. Though, after seeing the additional information, we can may be able to solve this without changing the CSS.

**Comment by ghost** [comment]
[Codepen](http://codepen.io/anon/pen/yVXQXa)
`i.icon.medium:before {
    content: "\f23a";
}`
`i.icon.at:before {
    content: "\f1fa";
}`
The medium selector was defined after the at selector and will overload them, but "medium" is not the icon. Its the size.

**Comment by levithomason** [comment]
Got it, thanks for the codepen that cleared the issue right up.  This is a CSS issue and should be submitted to [Semantic-OrgUI/Semantic-UI](https://github.com/Semantic-Org/Semantic-UI).

Semantic-UI-React only provides JS React components that render down to valid Semantic-UI HTML.  We do not provide nor modify any CSS.
