### ISSUE TITLE
Image size Attribute will by overwriten by corner

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-React#938]
The corner selector is more specific like the size selector so the size will be ignored when corner will be used,

**Comment by levithomason** [comment]
I am not sure what is being reported here. Can you please provide the information requested in the issue template?

**Comment by ghost** [comment]
[Codepen](http://codepen.io/anon/pen/yVXQXa)
`i.icons .corner.icon {
...
    font-size: .45em;
...
}`
`i.small.icon, i.small.icons {
 ...
    font-size: .75em;
}`
The corner selector is more specific than the small selector. So the a cornered item can't be sized.

**Comment by levithomason** [comment]
It looks like this codepen link was overriden with the one provided #937, however, it looks like this is another CSS issue and should be submitted to [Semantic-OrgUI/Semantic-UI](https://github.com/Semantic-Org/Semantic-UI).

Semantic-UI-React only provides JS React components that render down to valid Semantic-UI HTML.  We do not provide nor modify any CSS.
