### ISSUE TITLE
Why are component color props limited to a predefined set? 

### ISSUE THREAD

**Issue by Orbyt** [Semantic-Org/Semantic-UI-React#941]
Eg, when using an `<Icon />` or `<Button />`, the `color` prop only accepts a few different values, such as:

> red, orange, yellow, olive, green, teal, blue, violet, purple, pink, brown, grey, black

Why is it limited this way? I am unable to color an`<Icon />` using other common colors like white, or using hex strings like `#fffffff`. I have to instead find html element being rendered and color it manually via CSS.

This seems wrong.

**Comment by levithomason** [comment]
The color names are defined by Semantic UI css selectors, they are not actual inline style css colors.
