### ISSUE TITLE
Importing individual CSS files

### ISSUE THREAD

**Issue by jmcrthrs** [Semantic-Org/Semantic-UI-React#942]
I am importing the Dropdown component like so:
```

import { Dropdown } from 'semantic-ui-react';

import '../node_modules/semantic-ui-css/semantic.min.css';
```

This works great and my Dropdown appears when the icon is clicked. 

However I would prefer to import only the necessary CSS files.

I have tried the following:

```

import '../node_modules/semantic-ui-css/components/menu.min.css';

import '../node_modules/semantic-ui-css/components/dropdown.min.css';

import '../node_modules/semantic-ui-css/components/item.min.css';

import '../node_modules/semantic-ui-css/components/icon.min.css';

```

But the menu does not appear when the trigger is clicked.

1. Is importing individual CSS files a valid approach for Semantic UI?
2. How can I find out which components depend on which CSS files?

**Comment by levithomason** [comment]
Hm, that would seem correct to me as well. I have not tried this myself yet, though.

There is a repo for each component, https://github.com/Semantic-Org/UI-Dropdown, which appears to only include the `dropdown.css` for the Dropdown component.

If you want to create a codepen, I can take a look and see what I can find out.

**Comment by levithomason** [comment]
Closing for housekeeping here.  Will reopen if there is more info and a reproduction repo where we can investigate further.

**Comment by Joosakur** [comment]
I had this same issue. When clicking the dropdown the classname `visible` gets added but `display: none;` still remains. So some base css rule is missing if only importing the dropdown.css.

My solution was to bug-fix it with the styled-component wrapper that I was anyway going to use for theming the dropdown:
```
const StyledDropdown = styled(SemanticDropdown)`
  &.ui.selection.dropdown {
    .menu.visible {
      display: block;
    }
  }
`
```

**Comment by aditianand2507** [comment]
> Hm, that would seem correct to me as well. I have not tried this myself yet, though.
> 
> There is a repo for each component, https://github.com/Semantic-Org/UI-Dropdown, which appears to only include the `dropdown.css` for the Dropdown component.
> 
> If you want to create a codepen, I can take a look and see what I can find out.

Hi Levithomason,

I have a dropdown component and have imported "semantic-ui-css/components/dropdown.min.css". The styling is applied to dropdown, but on click of dropdown options are not appearing. Is there any other css files that need to be imported, please let me know. 

Codepen : https://codesandbox.io/s/semantic-ui-example-forked-1w8vf?file=/example.js:81-124

**Comment by tomitrescak** [comment]
Do you guys have a solution to this?

**Comment by layershifter** [comment]
> I have a dropdown component and have imported "semantic-ui-css/components/dropdown.min.css". The styling is applied to dropdown, but on click of dropdown options are not appearing. Is there any other css files that need to be imported, please let me know.

As I remember `dropdown.css` requires also `transition.css`, please try to import it from https://github.com/Semantic-Org/UI-Transition.
