### ISSUE TITLE
Form.Select Error with redux form Field

### ISSUE THREAD

**Issue by Tilican** [Semantic-Org/Semantic-UI-React#948]
### Steps
hi,
I create a Field ( from Redux form ) with as="" a Form.Select component from semantic ui react component.

<Field
              label="Configuration"
              name="key"
              options={this.props.selectBox}
              component={GenerateField}
              required
            />

// GenerateField

<Form.Select
            search
            label={field.label}
            options={field.options}
            onChange={(e, data) => field.input.onChange(data.value)}
             required={field.required}
          />

### Expected Result
Not an error ...

### Actual Result
Uncaught TypeError: Cannot set property 'initialValue' of null(…)
postUpdateWrapper @ ReactDOMSelect.js:167
postUpdateSelectWrapper @ ReactDOMComponent.js:293
notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:206
perform @ Transaction.js:153
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147

### Version
0.61.6

thx

**Comment by levithomason** [comment]
Hi there, could you create a repro for this?  We have no code that includes `initialValue` and I don't see any of our modules in the stack trace.

**Comment by Tilican** [comment]
Hi,
It's a react bug : [redux-form#321](https://github.com/erikras/redux-form/issues/321).
It's not in Semantic UI react bug 👍
