### ISSUE TITLE
<button> does not get emphasis on hover

### ISSUE THREAD

**Issue by cemremengu** [Semantic-Org/Semantic-UI-React#952]
The simple button example (including all button examples) like

```
<Button>Click Here</Button>
```
get emphasis on hover. However, for some reason I am not getting it using any of the examples except when using animated which should be used with an icon so that the button will not get truncated.

**Comment by jeffcarbs** [comment]
I am not sure what is being reported here. Can you please provide the information requested in the issue template?

Also be sure you're using the `<Button>` component provided by semantic-ui-react, and not the `<button>` HTML component.

**Comment by levithomason** [comment]
I've tested all hover effects on all buttons and they are working.  FWIW, hover effects are also CSS powered which is beyond the scope of our project at this time.  Closing for now, will re-open if there is more information to go on.

**Comment by cemremengu** [comment]
@levithomason @jcarbo I believe it was due to using CSS from the CDN because it works now. Maybe it was not loading properly at that time.

I am an amateur when it comes to front-end so I apologize if this was a stupid question :) Thanks for the quick responses and keep up the amazing work.

**Comment by levithomason** [comment]
Whoa, no stupid questions!  I am an amateur at life so I apologize if my response seemed to indicate that your question was not cool enough for me :P
