### ISSUE TITLE
fix(Menu): Dropdown as a Menu.Item without 'simple' property opens once, then throws error.

### ISSUE THREAD

**Issue by josie11** [Semantic-Org/Semantic-UI-React#954]
Perhaps not the highest priority issue...

**Steps to Reproduce**
1. Use Dropdown as a menu item without simple property.
2. Click Dropdown once, let it close, re-click.

**Expected**
It should reopen and close without issue.

**Result**
You can open the dropdown once, and the next time you try to open it, you get the following error: Uncaught TypeError: a._dropdown.blur is not a function. 

Bug is visible in the menu docs.

**Testcase**
http://react.semantic-ui.com/collections/menu
See: vertical menu with dropdown. There is another example (dropdown with an icon) that works. If you delete the simple property, it breaks.

**Comment by levithomason** [comment]
Duplicate #659

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.4`.
