### ISSUE TITLE
fix(Dropdown): your description

### ISSUE THREAD

**Issue by hommalex** [Semantic-Org/Semantic-UI-React#956]
**Steps to Reproduce**
1. Opening Any Dropdown

**Expected**
An onOpen Event props func to fire

**Result**
The function is not fire

**Testcase**

**Comment by levithomason** [comment]
There is not enough information to go on here.  Please submit a more detailed report.

Here is an example of a Dropdown with a working `onOpen` and `onClose` handler:

![http://g.recordit.co/ZzOwDpfZS6.gif](http://g.recordit.co/ZzOwDpfZS6.gif)

```jsx
import React, { Component } from 'react'
import { Dropdown } from 'semantic-ui-react'

const options = [{ text: 'One', value: 1 }]

class DropdownExample extends Component {
  state = {}
  handleOpen = () => this.setState({ open: true })
  handleClose = () => this.setState({ open: false })
  render() {
    return (
      <div>
        <p>It is {this.state.open ? 'open' : 'closed'}.</p>
        <Dropdown
          selection
          onOpen={this.handleOpen}
          onClose={this.handleClose}
          options={options}
        />
      </div>
    )
  }
}

export default DropdownExample
```

**Comment by hommalex** [comment]
hi Levi Thanks for your message.

I'm using "version": "0.56.10" and in can't see any onClose props.
~\semantic-ui-react\src\modules\Dropdown\Dropdown.js

I guess this was implement later

**Comment by levithomason** [comment]
Ah, very possible.  `0.56` was sometime ago and we've implemented _a lot_ of new things since then.
