### ISSUE TITLE
Provide typings definitions (TypeScript) for semantic-ui-react

### ISSUE THREAD

**Issue by DylanLukes** [Semantic-Org/Semantic-UI-React#957]
Previously, issue #361 mentioned the potential for typescript typings. It would be really handy to have these, especially considering the substantially improved Typescript/react interoperation. 

### Version
0.61.7

**Comment by DylanLukes** [comment]
Here is the output of `dts-gen -m semantic-ui-react` as a starting point:

https://gist.github.com/DylanLukes/e864dc61a663b6a5a03a6c4f5e15fd38

**Comment by levithomason** [comment]
Duplicate #674, see that work for the latest developments.
