### ISSUE TITLE
vertically expand component support?

### ISSUE THREAD

**Issue by cdaringe** [Semantic-Org/Semantic-UI-React#960]
### Steps
1. add an element (like a segment, or card!)
2. attempt to vertically expand it

### Expected Result

ability to vertically expand Elements to their container's height?  if feasible?

### Actual Result

non-vertically expanding thingies 

### Version
0.61.x

### Testcase
Fork: http://codepen.io/cdaringe/pen/oYozjd

#### discussion

i do realize that this may be a better fit for the semantic-css project, but i figured i'd take a first pass here to get an opinion?  if not an opinion, maybe a hot tip? :)

**Comment by levithomason** [comment]
I'm not sure what you mean by expand it?  The codepen appears to render everything correctly.  Can you be more specific?

**Comment by cdaringe** [comment]
hi @levithomason, sorry for the lack of clarity.  yes, the codepen does render everything correctly (though the service appears to be partially down, ATM?), it's just I wanted the "BLAH BLAH" `<Segment />` to expand to have the same height as it's neighbor, or similarly, the same height as the parent element.

i'm wondering what the best way is in order to make an `Element` do something similar to `height: 100%` to fill it's parent container, without writing my own CSS.

i do realize it's somewhat a chicken before the egg problem, where the container expands to accommodate its children's height, but similarly, I want "shorter children" to fill the parent's height if they would be shorter.  i've got a feeling this is a flexbox only thing--unsure if SUI has that baked in or not!

**Comment by layershifter** [comment]
If I correctly understand, you're looking for [stretched grid](http://react.semantic-ui.com/collections/grid#stretched).

**Comment by levithomason** [comment]
Thanks for the clarification, @layershifter hit it on the money, see the docs linked there.

**Comment by cdaringe** [comment]
thanks @layershifter, but that's for filling `width`, not `height`

**Comment by levithomason** [comment]
No sir, this fills the height.

**Comment by cdaringe** [comment]
i guess there's actually a little bit of a discrepancy in the docs page.  the top table says height, but the example says width

**Comment by levithomason** [comment]
Indeed!  The description is certainly wrong.

![http://g.recordit.co/EV1DFjbI7t.gif](http://g.recordit.co/EV1DFjbI7t.gif)

**Comment by cdaringe** [comment]
ohhhh nm. i was mixing Grid & Grid.Row.  thx! i'll try this out

**Comment by cdaringe** [comment]
thanks again for your time guys.  let me ask one more tip on the matter:

```jsx
<Grid.Row stretched>
    <Grid.Column>
        <Segment> {/* <== yes, i expand to fill the vertical space */}
          {/*
              but say here lands another component, e.g another Segment... can I grow vertically too?
              i could load in _more_ Grid DOM, but im looking for a shortcut!
              */}
        </Segment>
      </Grid.Column>
  </Grid.Row>
```

**Comment by cdaringe** [comment]
http://codepen.io/cdaringe/pen/oYozjd

**Comment by levithomason** [comment]
The grid is implementing flex box CSS to accomplished the stretched feature.  You can apply flex to any element.  I would suggest perusing the grid CSS on Semantic-UI and reading some CSS flex tutorials on how to use flex.
