### ISSUE TITLE
[Demo website] Exception when dismiss dropdown

### ISSUE THREAD

**Issue by nhducit** [Semantic-Org/Semantic-UI-React#961]
### Steps
- Visit this site http://react.semantic-ui.com/collections/menu#size
- click on `language` Dropdown 
- click on page to dismiss dropdrown
- console show this error message
```
 Uncaught TypeError: a._dropdown.blur is not a function(…)
```

### Expected Result
Console show error message
### Actual Result
Console doesn't show error message

### Version
0.61.7
### Testcase
http://react.semantic-ui.com/collections/menu#size

**Comment by levithomason** [comment]
Duplicate #659

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.4`.
