### ISSUE TITLE
Button.Or content prop

### ISSUE THREAD

**Issue by L3V147H4N** [Semantic-Org/Semantic-UI-React#963]
Provide prop for Button.Or to change the 'or' value in the button content

**Comment by levithomason** [comment]
I'd love to do this as well, however, this needs to change in the CSS over at the main repo, Semantic-UI.

![image](https://cloud.githubusercontent.com/assets/5067638/20772946/79e010ec-b704-11e6-8869-4729939f0c97.png)


The CSS should make could/should make use of `content: attr(data-or, 'or');` to allow inserting any content there but default to `or`.  Attr docs [here](https://developer.mozilla.org/en-US/docs/Web/CSS/attr).

Then we could use take in a prop to allow changing that as well.

**Comment by levithomason** [comment]
FWIW, you can add some overriding CSS that does exactly this.
