### ISSUE TITLE
How to refer rendered component?

### ISSUE THREAD

**Issue by littlehome-eugene** [Semantic-Org/Semantic-UI-React#968]
After input validation, I'd like to add error=true to `<Input />` 

I read `ref` callback is not supported in semantic-ui-react,  
How should I refer the `<Input />` component ? store them somewhere for later access?

**Comment by levithomason** [comment]
Refs are certainly supported, at least on all class components.  React itself does not support refs on stateless functional components, though, the `<Input />` is a class component.

That said, if you'd like to add `error` to the component after validation, you should do so by capturing the value in `onChange`, performing validation, and passing the `error` to the `Input`.  You should avoid `refs` at all costs as they leave the virtual DOM and access the real DOM.

Here's a working example of validation:

http://codepen.io/levithomason/pen/VmypjX

**Comment by littlehome-eugene** [comment]
How should I go about checking if required input is empty?

**Comment by levithomason** [comment]
The codepen I linked there shows how to validate the value of the input.  It is validating the length right now, so adjusting that to `0` would be for an empty input.  👍
