### ISSUE TITLE
Modal continuously updating

### ISSUE THREAD

**Issue by flipvrijn** [Semantic-Org/Semantic-UI-React#969]
Whenever a modal is open and you check the updates being done by React, the modal is being updated constantly even when doing nothing. I don't know if this is intended or not, but I imagine it puts strain on the rendering.

### Steps
1. Go to: http://react.semantic-ui.com/modules/modal
2. Click on a modal button
3. Enable `Trace React Updates` in the React tab of the Web Developer Console.
4. ...

### Expected Result
No continuous updating of the modal

### Actual Result
Continuously updating the modal as shown here:
![Continuously updating modal](http://i.imgur.com/s6MZ2Bp.gif)

### Version
Checked versions 0.61.7 and 0.61.8.

**Comment by jeffcarbs** [comment]
Nice catch! Just opened a PR to fix it 👍
