### ISSUE TITLE
Delete icon for multiselect dropdown generates warning

### ISSUE THREAD

**Issue by cemremengu** [Semantic-Org/Semantic-UI-React#971]
This warning happens in other components as well for example `right arrow` generates the same warning. Using `arrow right` fixes it. However, not sure how to fix it for dropdown.

This may again be just related to CSS but wanted to mention it nevertheless.

CSS: `//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.css`

### Steps
1. Use ` <Dropdown fluid  placeholder='KPI' multiple search selection options={ myOptions }  />`
2. Select a value.

### Expected Result
No warnings

### Actual Result
![dropdown](https://cloud.githubusercontent.com/assets/1297759/20795383/f222c166-b7e1-11e6-9341-c719aa329f9c.PNG)

![error](https://cloud.githubusercontent.com/assets/1297759/20795379/ebd8c35a-b7e1-11e6-8000-5bfa985d2ae3.PNG)

### Version
`^0.61.4`

**Comment by jeffcarbs** [comment]
This was fixed in `v0.61.6` via #944
