### ISSUE TITLE
Add doc examples for color, size, and inverted Statistic Groups

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#974]
@jcarbo just added `color`, `size`, and `inverted` support to the `StatisticGroup` in #972.  We should add doc site examples for these as well.

We currently only show regular groups and evenly divided groups.

**Comment by tarang9211** [comment]
@levithomason im looking to start contributing to this repo! would this be a good one to pick up?

**Comment by levithomason** [comment]
Absolutely. You can reference the existing docs in `/docs/app/examples/views/Statistic`. Our docs follow the layout of the core docs at www.semantic-ui.com.

**Comment by tarang9211** [comment]
what exactly does this issue entail?

**Comment by levithomason** [comment]
All the examples featured on react.semantic-ui.com live in `/docs/app/Examples`.  We show usage examples for all features of all our components.  The Statistic component was updated to have new features, however, the docs have not been updated to show these new features.

This issue was opened as a reminder that we need to add examples showing usage of the Statistic Group's `color`, `size`, and `inverted` props.  Currently, there are no examples showing these props for this component.

**Comment by tarang9211** [comment]
Awesome, I'll get started on it today!

**Comment by tarang9211** [comment]
@levithomason  On the live site, I do see examples of `color`, `size`, and `inverted` props.  They seem to correlate to the `js` files here https://github.com/Semantic-Org/Semantic-UI-React/tree/master/docs/app/Examples/views/Statistic/Variations

Also, do I have appropriate access rights? Github says my fork is 9 commits behind. I tried to `git pull upstream master` and it complained about inappropriate access rights.

**Comment by tarang9211** [comment]
@jcarbo  @levithomason I pushed a commit to my forked repo. Is this what you're getting at?
https://github.com/tarang9211/Semantic-UI-React/commit/6c4df6321766a8436144d1e456b08d38909a7819

**Comment by tarang9211** [comment]
Hey guys!

Could you give me some feedback on the Github comments?

Thanks!
Tarang

Regards
-Tarang Hirani

**Comment by levithomason** [comment]
>On the live site, I do see examples of color, size, and inverted props. They seem to correlate to the js files here https://github.com/Semantic-Org/Semantic-UI-React/tree/master/docs/app/Examples/views/Statistic/Variations

These are only for the individual Statistic component.  We need color, size, and inverted examples for the `<Statistic.Group />` component as well.

>Also, do I have appropriate access rights? Github says my fork is 9 commits behind. I tried to git pull upstream master and it complained about inappropriate access rights.

This repo is open source so anyone can pull from it.  My guess is that your remote may be using ssh and you do not have ssh keys setup.  Try:

```
git remote -v
```

If the url for `Semantic-UI-React.git` begins with `git@github.com` then it is trying to use ssh.  Either [change your remote url](https://help.github.com/articles/changing-a-remote-s-url/) to use https or [setup ssh](https://help.github.com/articles/generating-an-ssh-key/).

>I pushed a commit to my forked repo. Is this what you're getting at?
tarang9211@6c4df63

This is just about right!  We'd like to use a separate example file for each example.  Reference the individual `<Statistic />` examples and note how there is a different example file for each prop.

**Comment by tarang9211** [comment]
Give me an hour or two and I'll have to ready!

**Comment by tarang9211** [comment]
@levithomason created a PR. does this look better? created a file for each statistic group prop type.

https://github.com/Semantic-Org/Semantic-UI-React/pull/1058

**Comment by levithomason** [comment]
Thanks, let's move future convo over to that PR.  I'll get a review as soon as I am able.

**Comment by layershifter** [comment]
This issue was fixed #1058. Closing for housekeeping
