### ISSUE TITLE
Portal `mouseOver` should be `mouseEnter`

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#978]
The `mouseOver` event is called on [enter _and_ on leave](http://jsfiddle.net/ZCWvJ/7/).  This is creating duplicate timers for opening the portal.  If you add a `mouseOverDelay` this bug is very obvious.  The portal will open after the mouse leaves the element even though the timer is cleared.

**This is a simple fix** as we simply need to replace all `mouseOver` references with `mouseEnter` in the Portal, Modal, Popup including docs and tests.

Unfortunately, this is a breaking change since all `[mM]ouseOver` props will become `[mM]ouseEnter`.

## Bug demo with mouseOverDelay={1000}

![http://g.recordit.co/Z7Aei4wnUw.gif](http://g.recordit.co/Z7Aei4wnUw.gif)

## Fix demo with mouseEnterDelay={1000}

![http://g.recordit.co/tyM2LqQPVT.gif](http://g.recordit.co/tyM2LqQPVT.gif)

## Why is this happening?

The mouse over event is creating two "open" timers, one on mouse enter and another on mouse leave.  The mouse leave event is only clearing one of those, the latest one.  The first open timer is left running in memory.  When it expires, it opens the portal, even though the mouse has left and the _latest_ open timer has been canceled.

**Comment by dvdzkwsk** [comment]
WIP PR: https://github.com/Semantic-Org/Semantic-UI-React/pull/989.

I'd be willing to go through and maintain backwards compatibility by using `mouseOver` if it exists and `mouseEnter` does not, while also logging a warning, but seeing as Stardust is pre-1.0.0 I'd prefer this to be discussed before just implementing it, since I'm not convinced it's worth adding a deprecation warning to such a version.

**Comment by levithomason** [comment]
Awesome, thanks for starting this.  Agreed on skipping deprecation warnings.  It is inline with our development phase warnings at the top of the README:

>Hey, we're in development. Prior to reaching [v1.0.0][6]:
>
>1. **MINOR** versions represent **breaking changes**
>1. **PATCH** versions represent **fixes _and_ features**
>1. There are **no deprecation warnings** between releases
>1. You should consult the [**CHANGELOG**][18] and related issues/PRs for more information

We've been handling breaking changes with the pseudo commit message type `breaking(scope): msg` so users can find them easily in the changelog.  Then, we give concise breaking change notes and upgrade examples in the PR description.  You can have a look at some recent breaking PRs for reference:

- **breaking(DropdownItem): callback with (e, props) onClick #805**
- **breaking(AutoControlledProps): Ignore undefined #788**

Once we hit 1.0, we'll start using our `customPropTypes.deprecate()` checker for deprecation warnings and also ensure backward compatibility.
