### ISSUE TITLE
Form.Select onChange is not working as it should

### ISSUE THREAD

**Issue by kusalstha** [Semantic-Org/Semantic-UI-React#981]
### Expected Result
While using the library's Form.Input's event onChange the object sent to the handler properly shows the target and the value. 
Thus, should not the Form.Select do the same?
### Actual Result
Yet Form.Select's event onChange handler receives an object with target as a DOM node of div, which is not useful.

Is there a solution to get a proper value from the Form.Select onChange event?

**Comment by jeffcarbs** [comment]
Duplicate of https://github.com/Semantic-Org/Semantic-UI-React/issues/638

See this comment in particular: https://github.com/Semantic-Org/Semantic-UI-React/issues/638#issuecomment-252035750
