### ISSUE TITLE
Container inside Grid

### ISSUE THREAD

**Issue by LukaGiorgadze** [Semantic-Org/Semantic-UI-React#985]
The problem is, when you wrap a Container inside Grid and you want to have left floated and right floated elements, you see that everything is works fine, but when you resize screen (for mobile version), there is some unexpected variations.
For more details, please see an example: http://codepen.io/anon/pen/bBLQJK?editors=0010#0

### Version
2.2 (June 2016)

### Testcase
http://codepen.io/anon/pen/bBLQJK?editors=0010#0
(Resize screen for mobile version)

**Comment by levithomason** [comment]
Semantic-UI-React only concerns itself with JS components that render down to valid Semantic-UI markup.  Issues with CSS and HTML markup should be posted on the main repo:

https://github.com/Semantic-Org/Semantic-UI

Cheers!

P.S.  It looks like you might just be missing a column, Grid > Row > Column.  Also, rows are only necessary if you need special row formatting.  Here is your example updated with no row:

http://codepen.io/levithomason/pen/xRWdPj
