### ISSUE TITLE
Modal close icon color

### ISSUE THREAD

**Issue by AlvMF1** [Semantic-Org/Semantic-UI-React#986]
Modal close icon is a great feature!

However, when we use it with `dimmer='inverted'` it's bearly visible.
It would be nice to have a `closeIconColor` or `closeIcon='remove red'`.

**Comment by jeffcarbs** [comment]
`closeIcon` is a "Shorthand" prop, meaning that if you pass an object that object will be passed as props to the component. So you can do:
```js
<Modal closeIcon={{ name: 'remove', color: 'red' }}>
```
