### ISSUE TITLE
Dropdown in menu item causes Uncaught TypeError

### ISSUE THREAD

**Issue by mtruyens** [Semantic-Org/Semantic-UI-React#992]
It seems that dropdown items within a menu cause the following error: "Uncaught TypeError: a._dropdown.blur is not a function(…)" when an item is clicked.

See for example the menu that contains the "Account", "Settings" and "Display Options" on http://react.semantic-ui.com/collections/menu. I reprint the code of that sample-code below. 

Tested on 0.61.10, but the error seems present in many recent previous versions.

`import React, { Component } from 'react'
import { Dropdown, Menu } from 'semantic-ui-react'

export default class MenuExampleVerticalDropdown extends Component {
  state = { activeItem: 'account' }

  handleItemClick = (e, { name }) => this.setState({ activeItem: name })

  render() {
    const { activeItem } = this.state

    return (
      <Menu secondary vertical>
        <Menu.Item name='account' active={activeItem === 'account'} onClick={this.handleItemClick} />
        <Menu.Item name='settings' active={activeItem === 'settings'} onClick={this.handleItemClick} />
        <Dropdown as={Menu.Item} text='Display Options'>
          <Dropdown.Menu>
            <Dropdown.Header>Text Size</Dropdown.Header>
            <Dropdown.Item>Small</Dropdown.Item>
            <Dropdown.Item>Medium</Dropdown.Item>
            <Dropdown.Item>Large</Dropdown.Item>
          </Dropdown.Menu>
        </Dropdown>
      </Menu>
    )
  }
}`

**Comment by levithomason** [comment]
Duplicate #659

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.4`.
