### ISSUE TITLE
Dropdown keyboard arrows don't work when rendering with children dropdown menu

### ISSUE THREAD

**Issue by fracmak** [Semantic-Org/Semantic-UI-React#993]
You can see this on the docs page, example: http://react.semantic-ui.com/modules/dropdown#dropdown

 Gives the error `Uncaught TypeError: Cannot read property 'length' of undefined` because getMenuOptions() doesn't know anything about the child menu items and returns undefined

### Version
0.61.10

**Comment by levithomason** [comment]
This is a known issue, however, I'm not sure that we'll support any subcomponents in the Dropdown in the long term.  There is simply too much wiring involved to manage state and event handlers to make it worthwhile for users.  Said wiring can be offloaded to the Dropdown if the children are defined via props instead (i.e. `options`, etc) where the Dropdown itself can then manage state and handle events.

You can see more on the discussion around extending the API in #889.  I'll close this issue in favor of continued conversation over there.
