### ISSUE TITLE
Reveal alignment  (feature request)

### ISSUE THREAD

**Issue by raptoria** [Semantic-Org/Semantic-UI-React#994]
It doesn't seem possible at the moment to center or right align the Reveal component.

**Comment by levithomason** [comment]
Semantic-UI-React only concerns itself with JS components that render down to valid Semantic-UI markup. Issues with CSS and HTML markup should be posted on the main repo:

https://github.com/Semantic-Org/Semantic-UI

Once it is supported in core, then we can update components to implement the new HTML/CSS features.
