### ISSUE TITLE
Where are the Headers and Footers?

### ISSUE THREAD

**Issue by quadsurf** [Semantic-Org/Semantic-UI-React#996]
I can't find the header and footer boilerplate any where... please help me locate them in the docs.

**Comment by levithomason** [comment]
Did you try the doc search bar?

**Comment by levithomason** [comment]
Header: http://react.semantic-ui.com/elements/header
There is no footer.

**Comment by quadsurf** [comment]
@levithomason of course i tried the search bar, and it yields no relevant results!

A search does pull up the header tag (H1,H2,etc), but if i'm asking about a footer too, then the context of header is most likely a "header nav bar", not a header tag.

So I take it there is no header nav bar boilerplate then?

**Comment by levithomason** [comment]
Correct, the docs show all the supported components.  Although, you're probably wanting a Menu for the "header nav".

http://react.semantic-ui.com/collections/menu
