### ISSUE TITLE
Setting background color of Menu.Item

### ISSUE THREAD

**Issue by AdamBCo** [Semantic-Org/Semantic-UI-React#999]
How do you set the background color of a Menu.Item, or invert a single Menu.Item element?

For example I want to make the background color of the checkmark item green.

`     <Menu secondary>
            <Menu.Item icon="trash outline" />
            <Menu.Item color={'green'} icon="checkmark" />
        </Menu secondary>
`

**Comment by levithomason** [comment]
These are all the possible color options:

http://react.semantic-ui.com/collections/menu#colored

If none of these work for your use case, you should use some other additional form of styling such as inline styles, an override stylesheet, or a custom theme:

http://semantic-ui.com/usage/theming.html.
